globalThis.__OUT = {"elektronYerlesim":{
"ilkokul":{
"kolay":[
{"q":"Bir sinema salonunda insanlar koltuklara nasıl oturur? Atomda elektronlar da yerleşirken hangi sıraya uyar?","steps":[{"t":"Önce yakın koltuklar","a":"en yakın yerler","d":"Sinemada insanlar genelde önce perdeye en yakın boş koltukları doldurur."},{"t":"Elektron da öyle","a":"önce yakın yer","d":"Elektronlar da çekirdeğe <b>en yakın</b> ve en rahat yerlere önce yerleşir."}],"ans":"Elektronlar, tıpkı koltukları dolduran insanlar gibi önce çekirdeğe en yakın yerlere yerleşir."},
{"q":"Çekirdeğe en yakın kabuğa en fazla kaç elektron sığabilir?","steps":[{"t":"İlk kabuk küçüktür","a":"en içteki halka","d":"Çekirdeğe en yakın ilk kabuk küçüktür, az yer vardır."},{"t":"Sınır 2","a":"2 elektron","d":"Bu ilk kabuğa en fazla <b>2 elektron</b> sığar."}],"ans":"Çekirdeğe en yakın ilk kabuğa en fazla 2 elektron sığar."},
{"q":"Elektronlar çekirdeğin etrafına yerleşirken ilk dolan kabuk dolmadan ikinci kabuk dolar mı?","steps":[{"t":"Önce iç kabuk","a":"içten başlar","d":"Elektronlar önce en içteki kabuğu doldurmaya başlar."},{"t":"Sonra dışa geçer","a":"dolunca dışa","d":"İç kabuk <b>dolmadan</b> elektron dış kabuğa kolayca geçmez."}],"ans":"Hayır, önce iç kabuk dolar, dolduktan sonra elektronlar dış kabuğa geçer."},
{"q":"Bir atomda 3 elektron varsa bunlar nasıl yerleşir?","steps":[{"t":"İlk kabuğa 2","a":"2 elektron","d":"İlk kabuğa en fazla 2 elektron sığar, ikisi buraya yerleşir."},{"t":"Kalan dışa","a":"1 elektron dışta","d":"Geriye kalan <b>1 elektron</b> ikinci kabuğa geçer."}],"ans":"3 elektronun 2'si ilk kabuğa, 1'i ikinci kabuğa yerleşir."},
{"q":"İki çocuğa boş bir sıra verilirse yan yana mı oturur, yoksa ayrı ayrı mı? Elektronlar da nasıl davranır?","steps":[{"t":"Önce ayrı oturma","a":"ayrı yerler","d":"İki çocuğa boş bir sıra verilince genelde önce ayrı ayrı yerlere otururlar."},{"t":"Elektron da paylaşmaz","a":"önce tek tek","d":"Elektronlar da boş yerler varken önce <b>tek tek</b> ayrı yerlere yerleşmeyi sever."}],"ans":"Elektronlar, boş yerler varken çocuklar gibi önce ayrı ayrı yerlere yerleşir."}
],
"zor":[
{"q":"Bir atomda 11 elektron var. İlk kabuğa 2, ikinci kabuğa 8 elektron yerleştikten sonra üçüncü kabukta kaç elektron kalır?","steps":[{"t":"İlk iki kabuk","a":"2 + 8 = 10","d":"İlk kabuğa 2, ikinci kabuğa 8 elektron yerleşir; toplam 10 olur."},{"t":"Kalan","a":"1 elektron","d":"11 elektrondan 10'u dolunca geriye <b>1 elektron</b> kalır, o üçüncü kabuğa geçer."}],"ans":"Üçüncü kabukta 1 elektron kalır (2 + 8 + 1 = 11)."},
{"q":"Bir tiyatroda ön sıralar dolmadan arka sıralar neden boş kalır? Bu kural elektronlar için neden vardır?","steps":[{"t":"Yakın yer rahattır","a":"en az enerji","d":"İzleyici için ön sıra, elektron için çekirdeğe yakın yer en rahat ve az enerjili yerdir."},{"t":"Önce rahat yer dolar","a":"içten dışa","d":"Bu yüzden önce <b>yakın (içteki)</b> yerler dolar, sonra dışa geçilir."}],"ans":"En rahat (en az enerjili) yakın yerler önce dolduğu için, ön sıralar gibi içteki kabuklar önce dolar."},
{"q":"Bir kabukta dört boş yer ve üç elektron varsa, elektronlar ikişer mi yan yana durur yoksa ayrı ayrı mı dağılır?","steps":[{"t":"Boş yer çok","a":"4 yer, 3 elektron","d":"Dört boş yer için üç elektron vardır, herkese ayrı yer düşebilir."},{"t":"Önce tek tek","a":"ayrı ayrı","d":"Elektronlar boş yer varken önce <b>tek tek</b> ayrı yerlere yerleşir, hemen eşleşmez."}],"ans":"Üç elektron, boş yerler varken ayrı ayrı yerlere dağılır, ikişer eşleşmez."},
{"q":"Bir atomun elektronları yerleşirken neden hep önce en içteki kabuktan başlanır?","steps":[{"t":"Çekirdek çeker","a":"en güçlü çekim","d":"Çekirdek, kendisine en yakın yerdeki elektronu en güçlü çeker."},{"t":"Önce o yer dolar","a":"en kararlı yer","d":"En çok çekilen ve en <b>kararlı</b> yer olduğu için iç kabuk önce dolar."}],"ans":"En içteki kabuk çekirdeğe en yakın ve en kararlı yer olduğu için elektronlar yerleşmeye oradan başlar."},
{"q":"Bir atomda 7 elektron var. Bunların kaçı ilk kabukta, kaçı ikinci kabukta olur?","steps":[{"t":"İlk kabuk","a":"2 elektron","d":"İlk kabuğa en fazla 2 elektron sığar, ikisi buraya gelir."},{"t":"İkinci kabuk","a":"5 elektron","d":"Geriye kalan <b>5 elektron</b> ikinci kabuğa yerleşir (2 + 5 = 7)."}],"ans":"7 elektronun 2'si ilk kabukta, 5'i ikinci kabukta bulunur."}
]
},
"ortaokul":{
"kolay":[
{"q":"Elektronlar çekirdeğin etrafına yerleşirken hangi kuralı izler?","steps":[{"t":"Enerji düzeyleri","a":"düşükten yükseğe","d":"Çekirdeğin etrafında farklı enerji düzeyleri (kabuklar) vardır."},{"t":"Doldurma sırası","a":"önce düşük enerji","d":"Elektronlar önce <b>en düşük enerjili</b> kabuğu doldurur, sonra yükseğe geçer."}],"ans":"Elektronlar önce en düşük enerjili kabuğu doldurur, sonra daha yüksek enerjili kabuklara geçer."},
{"q":"İlk üç elektron kabuğuna sırasıyla en fazla kaç elektron sığar?","steps":[{"t":"İlk iki kabuk","a":"2 ve 8","d":"İlk kabuğa 2, ikinci kabuğa 8 elektron sığar."},{"t":"Üçüncü kabuk","a":"8 elektron","d":"Üçüncü kabuğa ortaokul düzeyinde en fazla <b>8 elektron</b> kabul edilir."}],"ans":"İlk üç kabuğa sırasıyla en fazla 2, 8 ve 8 elektron sığar."},
{"q":"Atom numarası 12 olan magnezyumun elektronları kabuklara nasıl dağılır?","steps":[{"t":"Elektron sayısı","a":"12 elektron","d":"Nötr atomda elektron sayısı atom numarasına eşittir, yani 12'dir."},{"t":"Dağılım","a":"2, 8, 2","d":"İlk kabuğa 2, ikinciye 8, üçüncüye <b>2</b> elektron yerleşir (2 + 8 + 2 = 12)."}],"ans":"Magnezyumun 12 elektronu kabuklara 2, 8, 2 biçiminde dağılır."},
{"q":"Bir atomun en dış kabuğundaki elektronlara ne ad verilir?","steps":[{"t":"En dış kabuk","a":"son kabuk","d":"Elektronların yerleştiği en dıştaki kabuk son enerji düzeyidir."},{"t":"Adı","a":"değerlik elektronları","d":"Bu kabuktaki elektronlara <b>değerlik elektronları</b> denir; bağ yapımında etkilidir."}],"ans":"En dış kabuktaki elektronlara değerlik (valans) elektronları denir."},
{"q":"Atom numarası 8 olan oksijenin son kabuğunda kaç elektron bulunur?","steps":[{"t":"Dağılım","a":"2, 6","d":"8 elektron; ilk kabuğa 2, ikinci (son) kabuğa 6 elektron yerleşir."},{"t":"Son kabuk","a":"6 elektron","d":"Son kabukta <b>6 değerlik elektronu</b> bulunur."}],"ans":"Oksijenin elektron dağılımı 2, 6'dır; son kabuğunda 6 elektron bulunur."}
],
"zor":[
{"q":"Atom numarası 17 olan klorun elektron dağılımı nedir ve son kabuğunda kaç elektron vardır?","steps":[{"t":"Dağılım","a":"2, 8, 7","d":"17 elektron kabuklara 2, 8, 7 biçiminde yerleşir (2 + 8 + 7 = 17)."},{"t":"Son kabuk","a":"7 elektron","d":"Son kabukta <b>7 değerlik elektronu</b> vardır; klor 1 elektron alarak kararlı olmak ister."}],"ans":"Klorun dağılımı 2, 8, 7'dir; son kabuğunda 7 elektron bulunur."},
{"q":"Sodyum (atom no 11) neden 1 elektron vermeye eğilimlidir?","steps":[{"t":"Dağılım","a":"2, 8, 1","d":"Sodyumun 11 elektronu 2, 8, 1 biçiminde dağılır; son kabukta tek elektron vardır."},{"t":"Kararlılık isteği","a":"1 elektron verir","d":"Son kabuktaki <b>1 elektronu</b> verince geriye 2, 8 dağılımı kalır; bu kararlı bir düzendir."}],"ans":"Son kabuğunda tek elektron olduğu için sodyum, onu vererek (2, 8) kararlı düzene ulaşmak ister."},
{"q":"İki atomun da son kabuğunda 8 elektron varsa bu atomlar hakkında ne söylenebilir?","steps":[{"t":"Dolu son kabuk","a":"oktet","d":"Son kabukta 8 elektron olması (oktet) en kararlı düzendir."},{"t":"Kararlı yapı","a":"tepkimeye girmez","d":"Bu atomlar genelde <b>kararlıdır</b> ve kolay kolay bağ yapmaz (soygazlar gibi)."}],"ans":"Son kabuğunda 8 elektron olan atomlar kararlıdır ve genelde tepkimeye girmek istemez (oktet kuralı)."},
{"q":"Atom numarası 19 olan potasyumda 3. kabuk 8 elektronla dolduktan sonra 19. elektron nereye yerleşir?","steps":[{"t":"İlk üç kabuk","a":"2 + 8 + 8 = 18","d":"İlk üç kabuğa sırasıyla 2, 8, 8 elektron yerleşir; toplam 18 olur."},{"t":"Son elektron","a":"4. kabuk","d":"Kalan <b>1 elektron</b> dördüncü kabuğa geçer (2, 8, 8, 1)."}],"ans":"19. elektron dördüncü kabuğa yerleşir; potasyumun dağılımı 2, 8, 8, 1 olur."},
{"q":"Aynı element olmalarına rağmen Na ve Na⁺ taneciklerinin elektron dağılımı neden farklıdır?","steps":[{"t":"Nötr atom","a":"2, 8, 1","d":"Nötr sodyum atomunun 11 elektronu 2, 8, 1 biçiminde dağılır."},{"t":"İyon","a":"2, 8","d":"Na⁺, 1 elektron verdiği için <b>10 elektronludur</b>; dağılımı 2, 8 olur."}],"ans":"Na⁺ bir elektron verdiğinden 10 elektronludur; dağılımı 2, 8 iken nötr Na'da 2, 8, 1'dir."}
]
},
"lise":{
"kolay":[
{"q":"Aufbau ilkesine göre elektronlar orbitallere nasıl yerleştirilir?","steps":[{"t":"Enerji sırası","a":"düşükten yükseğe","d":"Aufbau ilkesi, elektronların en düşük enerjili orbitalden başlayarak yerleştiğini söyler."},{"t":"Doldurma sırası","a":"1s 2s 2p 3s 3p 4s 3d...","d":"Sıra şöyledir: <b>1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p, 5s...</b> Daha düşük enerjili orbital önce dolar."}],"ans":"Aufbau ilkesine göre elektronlar en düşük enerjili orbitalden başlayarak (1s, 2s, 2p, 3s, 3p, 4s, 3d...) yerleşir."},
{"q":"Pauli dışarlama ilkesine göre bir orbitalde en fazla kaç elektron bulunabilir ve nasıl yerleşir?","steps":[{"t":"Sınır","a":"2 elektron","d":"Pauli ilkesine göre bir orbitalde en fazla 2 elektron bulunur."},{"t":"Spin","a":"zıt spinli","d":"Bu iki elektron <b>zıt spinli</b> olmalıdır (↑↓); aynı dört kuantum sayısına sahip olamazlar."}],"ans":"Pauli ilkesine göre bir orbitalde en fazla 2 elektron bulunur ve bunlar zıt spinli (↑↓) olmalıdır.","fig":"<svg viewBox='0 0 320 120'><rect x='120' y='45' width='80' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='150' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='170' y='68' font-size='22' text-anchor='middle' fill='#e0552b'>↓</text><text x='160' y='100' font-size='12' text-anchor='middle' fill='#1a2b45'>bir orbital: zıt spinli 2 elektron</text></svg>"},
{"q":"Hund kuralına göre aynı enerjili orbitaller (örneğin 2p) nasıl doldurulur?","steps":[{"t":"Önce tek tek","a":"paralel spin","d":"Hund kuralına göre eş enerjili orbitaller önce birer elektronla, aynı (paralel) spinle doldurulur."},{"t":"Sonra eşleşme","a":"zıt spin eklenir","d":"Tüm orbitaller birer elektron aldıktan sonra <b>eşleşme</b> başlar (zıt spinli ikinci elektron eklenir)."}],"ans":"Hund kuralına göre eş enerjili orbitallere önce tek tek paralel spinli elektron yerleşir, hepsi dolunca eşleşme başlar.","fig":"<svg viewBox='0 0 340 120'><rect x='40' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='110' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='180' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='70' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='140' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='210' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='170' y='100' font-size='12' text-anchor='middle' fill='#1a2b45'>2p³: önce tek tek (Hund)</text></svg>"},
{"q":"Karbon atomunun (Z = 6) elektron dizilimi nasıl yazılır?","steps":[{"t":"Doldurma sırası","a":"1s, 2s, 2p","d":"6 elektron Aufbau sırasıyla 1s, 2s ve 2p orbitallerine yerleşir."},{"t":"Dizilim","a":"1s² 2s² 2p²","d":"Karbonun elektron dizilimi <b>1s² 2s² 2p²</b> şeklindedir (2 + 2 + 2 = 6)."}],"ans":"Karbonun elektron dizilimi 1s² 2s² 2p²'dir.","fig":"<svg viewBox='0 0 360 130'><text x='10' y='30' font-size='13' fill='#1a2b45'>1s²</text><rect x='40' y='45' width='44' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='52' y='66' font-size='14' fill='#2b6be0'>↑</text><text x='64' y='66' font-size='14' fill='#e0552b'>↓</text><text x='100' y='30' font-size='13' fill='#1a2b45'>2s²</text><rect x='100' y='45' width='44' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='112' y='66' font-size='14' fill='#2b6be0'>↑</text><text x='124' y='66' font-size='14' fill='#e0552b'>↓</text><text x='200' y='30' font-size='13' fill='#1a2b45'>2p²</text><rect x='180' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='222' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='264' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='200' y='66' font-size='15' text-anchor='middle' fill='#2b6be0'>↑</text><text x='242' y='66' font-size='15' text-anchor='middle' fill='#2b6be0'>↑</text><text x='150' y='105' font-size='12' text-anchor='middle' fill='#1a2b45'>C: 1s² 2s² 2p²</text></svg>"},
{"q":"Neon atomunun (Z = 10) elektron dizilimini yazın.","steps":[{"t":"Elektron sayısı","a":"10 elektron","d":"Nötr neonda 10 elektron vardır."},{"t":"Dizilim","a":"1s² 2s² 2p⁶","d":"Sıralı doldurmayla dizilim <b>1s² 2s² 2p⁶</b> olur; ikinci kabuk tamamen doludur (oktet)."}],"ans":"Neonun elektron dizilimi 1s² 2s² 2p⁶'dır.","fig":"<svg viewBox='0 0 360 130'><text x='10' y='30' font-size='13' fill='#1a2b45'>1s²</text><rect x='36' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='46' y='66' font-size='13' fill='#2b6be0'>↑</text><text x='58' y='66' font-size='13' fill='#e0552b'>↓</text><text x='90' y='30' font-size='13' fill='#1a2b45'>2s²</text><rect x='90' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='100' y='66' font-size='13' fill='#2b6be0'>↑</text><text x='112' y='66' font-size='13' fill='#e0552b'>↓</text><text x='200' y='30' font-size='13' fill='#1a2b45'>2p⁶</text><rect x='150' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='192' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='234' y='45' width='40' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='160' y='66' font-size='13' fill='#2b6be0'>↑</text><text x='172' y='66' font-size='13' fill='#e0552b'>↓</text><text x='202' y='66' font-size='13' fill='#2b6be0'>↑</text><text x='214' y='66' font-size='13' fill='#e0552b'>↓</text><text x='244' y='66' font-size='13' fill='#2b6be0'>↑</text><text x='256' y='66' font-size='13' fill='#e0552b'>↓</text><text x='160' y='105' font-size='12' text-anchor='middle' fill='#1a2b45'>Ne: tüm orbitaller dolu (oktet)</text></svg>"},
{"q":"Oksijen atomunun (Z = 8) değerlik elektron dizilimi nedir?","steps":[{"t":"Tam dizilim","a":"1s² 2s² 2p⁴","d":"Oksijenin 8 elektronu 1s² 2s² 2p⁴ biçiminde dağılır."},{"t":"Değerlik kabuğu","a":"2s² 2p⁴","d":"En yüksek baş kuantum sayılı kabuk (n = 2) değerlik kabuğudur: <b>2s² 2p⁴</b>, yani 6 değerlik elektronu."}],"ans":"Oksijenin değerlik elektron dizilimi 2s² 2p⁴'tür (6 değerlik elektronu)."},
{"q":"4s orbitali, 3d orbitalinden önce dolar. Bunun nedeni nedir?","steps":[{"t":"Enerji karşılaştırması","a":"4s < 3d","d":"Baş kuantum sayısı küçük olmasına rağmen 4s orbitalinin enerjisi 3d'den biraz düşüktür."},{"t":"Aufbau sonucu","a":"4s önce dolar","d":"Aufbau ilkesi düşük enerjiyi öncelediği için <b>4s, 3d'den önce</b> dolar."}],"ans":"4s orbitalinin enerjisi 3d'den düşük olduğu için Aufbau ilkesine göre 4s önce dolar."},
{"q":"Azot atomunun (Z = 7) 2p orbitalleri Hund kuralına göre nasıl doldurulur?","steps":[{"t":"2p elektron sayısı","a":"3 elektron","d":"Azotun dizilimi 1s² 2s² 2p³'tür; 2p düzeyinde 3 elektron vardır."},{"t":"Hund dağılımı","a":"her orbitale 1","d":"Üç 2p orbitaline <b>birer elektron</b> paralel spinle yerleşir (↑ ↑ ↑), eşleşme olmaz."}],"ans":"Azotun 3 elektronu üç 2p orbitaline tek tek, paralel spinle (↑ ↑ ↑) yerleşir.","fig":"<svg viewBox='0 0 340 120'><rect x='40' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='110' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='180' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='70' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='140' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='210' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='250' y='62' font-size='13' fill='#1a2b45'>2p³</text></svg>"},
{"q":"Soygazlardan argonun (Z = 18) elektron dizilimi nedir?","steps":[{"t":"Elektron sayısı","a":"18 elektron","d":"Nötr argonda 18 elektron vardır."},{"t":"Dizilim","a":"1s² 2s² 2p⁶ 3s² 3p⁶","d":"Dağılım <b>1s² 2s² 2p⁶ 3s² 3p⁶</b> olur; bu kararlı düzen [Ar] kor diziliminin temelidir."}],"ans":"Argonun elektron dizilimi 1s² 2s² 2p⁶ 3s² 3p⁶'dır; kısaca [Ar] ile gösterilir."},
{"q":"Kor (soygaz) gösterimiyle sodyumun (Z = 11) elektron dizilimi nasıl yazılır?","steps":[{"t":"Önceki soygaz","a":"[Ne]","d":"Sodyumdan önceki soygaz neondur (Z = 10), dizilimi 1s² 2s² 2p⁶'dır."},{"t":"Kalan elektron","a":"3s¹","d":"11. elektron 3s orbitaline girer; dizilim <b>[Ne]3s¹</b> olarak yazılır."}],"ans":"Sodyumun kor gösterimli dizilimi [Ne]3s¹'dir."},
{"q":"Berilyum (Z = 4) ve karbon (Z = 6) arasındaki fark elektron diziliminde nasıl görünür?","steps":[{"t":"Berilyum","a":"1s² 2s²","d":"Berilyumun 4 elektronu 1s² 2s² biçiminde dizilir; 2p boştur."},{"t":"Karbon","a":"1s² 2s² 2p²","d":"Karbonda 2 elektron daha vardır; bunlar 2p'ye girerek <b>1s² 2s² 2p²</b> dizilimini verir."}],"ans":"Berilyum 1s² 2s², karbon ise 1s² 2s² 2p²'dir; aradaki fark 2p orbitaline giren 2 elektrondur."},
{"q":"Bir orbital diyagramında 2s² orbitali neden ↑↓ ile gösterilir?","steps":[{"t":"Dolu orbital","a":"2 elektron","d":"2s² ifadesi, 2s orbitalinde 2 elektron olduğunu gösterir."},{"t":"Zıt spin zorunlu","a":"↑↓","d":"Pauli ilkesi gereği bu iki elektron <b>zıt spinli</b> olmalıdır; bu yüzden ↑↓ çizilir."}],"ans":"2s² dolu bir orbitaldir; Pauli ilkesi gereği iki elektron zıt spinli olduğundan ↑↓ ile gösterilir."},
{"q":"Flor atomunun (Z = 9) elektron dizilimini yazıp değerlik elektron sayısını belirtin.","steps":[{"t":"Dizilim","a":"1s² 2s² 2p⁵","d":"Florun 9 elektronu 1s² 2s² 2p⁵ biçiminde dağılır."},{"t":"Değerlik","a":"7 elektron","d":"Değerlik kabuğu n = 2'dir: 2s² 2p⁵, yani <b>7 değerlik elektronu</b>; flor 1 elektron alarak oktedi tamamlar."}],"ans":"Florun dizilimi 1s² 2s² 2p⁵'tir; 7 değerlik elektronu vardır."},
{"q":"Demirin (Z = 26) elektron dizilimi kor gösterimiyle nasıl yazılır?","steps":[{"t":"Önceki soygaz","a":"[Ar]","d":"Demirden önceki soygaz argondur (Z = 18); 18 elektron [Ar] ile gösterilir."},{"t":"Kalan elektronlar","a":"3d⁶ 4s²","d":"Kalan 8 elektron Aufbau gereği önce 4s'e (2), sonra 3d'ye (6) girer: <b>[Ar]3d⁶4s²</b>."}],"ans":"Demirin elektron dizilimi [Ar]3d⁶4s²'dir."},
{"q":"Aufbau diyagramında doldurma sırasını belirlemek için kullanılan pratik yöntem nedir?","steps":[{"t":"Çapraz oklar","a":"diyagonal kural","d":"Orbitaller alt alta yazılıp sağ üstten sol alta çapraz oklarla izlenir (diyagonal/Madelung kuralı)."},{"t":"Sıra okunur","a":"1s 2s 2p 3s 3p 4s 3d 4p...","d":"Bu çaprazlar takip edilince doldurma sırası <b>1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p, 5s, 4d...</b> olarak çıkar."}],"ans":"Çapraz (diyagonal/Madelung) ok yöntemiyle doldurma sırası 1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p... biçiminde elde edilir.","fig":"<svg viewBox='0 0 300 170'><text x='30' y='30' font-size='15' fill='#1a2b45'>1s</text><text x='30' y='60' font-size='15' fill='#1a2b45'>2s</text><text x='80' y='60' font-size='15' fill='#1a2b45'>2p</text><text x='30' y='90' font-size='15' fill='#1a2b45'>3s</text><text x='80' y='90' font-size='15' fill='#1a2b45'>3p</text><text x='130' y='90' font-size='15' fill='#1a2b45'>3d</text><text x='30' y='120' font-size='15' fill='#1a2b45'>4s</text><text x='80' y='120' font-size='15' fill='#1a2b45'>4p</text><line x1='95' y1='52' x2='35' y2='92' stroke='#e0552b' stroke-width='1.5'/><line x1='145' y1='82' x2='35' y2='122' stroke='#e0552b' stroke-width='1.5'/><text x='150' y='150' font-size='12' text-anchor='middle' fill='#1a2b45'>çapraz doldurma yönü</text></svg>"}
],
"zor":[
{"q":"Fosfor atomunun (Z = 15) tam elektron dizilimini yazıp orbital diyagramıyla 3p elektronlarının yerleşimini açıklayın.","steps":[{"t":"Dizilim","a":"1s² 2s² 2p⁶ 3s² 3p³","d":"15 elektron Aufbau sırasıyla 1s² 2s² 2p⁶ 3s² 3p³ biçiminde dağılır."},{"t":"Hund uygulaması","a":"3p: ↑ ↑ ↑","d":"3p düzeyindeki 3 elektron, Hund kuralı gereği üç orbitale <b>tek tek paralel spinle</b> yerleşir, eşleşmez."}],"ans":"Fosforun dizilimi 1s² 2s² 2p⁶ 3s² 3p³'tür; 3p elektronları Hund kuralıyla üç orbitale tek tek (↑ ↑ ↑) yerleşir.","fig":"<svg viewBox='0 0 340 120'><rect x='40' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='110' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='180' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='70' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='140' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='210' y='68' font-size='22' text-anchor='middle' fill='#2b6be0'>↑</text><text x='255' y='62' font-size='13' fill='#1a2b45'>3p³</text></svg>"},
{"q":"Kükürt (Z = 16) ile fosfor (Z = 15) atomlarının orbital diyagramları karşılaştırıldığında 3p düzeyinde ne fark görülür?","steps":[{"t":"Fosfor 3p³","a":"↑ ↑ ↑","d":"Fosforda 3 elektron üç orbitale tek tek yerleşir; eşleşmemiş 3 elektron vardır."},{"t":"Kükürt 3p⁴","a":"↑↓ ↑ ↑","d":"Kükürtte 4. elektron Hund sonrası ilk orbitale eşleşir: <b>↑↓ ↑ ↑</b>; eşleşmemiş 2 elektron kalır."}],"ans":"Fosforda 3p³ üç orbitalde tek tek (↑ ↑ ↑) iken, kükürtte 3p⁴ olduğundan ilk orbital eşleşir (↑↓ ↑ ↑); kükürtte 2 eşleşmemiş elektron vardır.","fig":"<svg viewBox='0 0 340 130'><rect x='40' y='40' width='55' height='32' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='105' y='40' width='55' height='32' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='170' y='40' width='55' height='32' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='60' y='62' font-size='17' fill='#2b6be0'>↑</text><text x='72' y='62' font-size='17' fill='#e0552b'>↓</text><text x='132' y='62' font-size='17' text-anchor='middle' fill='#2b6be0'>↑</text><text x='197' y='62' font-size='17' text-anchor='middle' fill='#2b6be0'>↑</text><text x='245' y='60' font-size='13' fill='#1a2b45'>S: 3p⁴</text></svg>"},
{"q":"İyonlaşma sırasında potasyumun (Z = 19) son giren elektronunun 4s'ten ayrılmasının elektron diziliminden gerekçesini açıklayın.","steps":[{"t":"Nötr dizilim","a":"[Ar]4s¹","d":"Potasyumun son elektronu Aufbau gereği 4s orbitaline girer: [Ar]4s¹."},{"t":"İyon oluşumu","a":"4s elektronu kopar","d":"En dış ve en yüksek enerjili (en az tutulan) elektron 4s'tekidir; bu yüzden K⁺ oluşurken <b>4s elektronu</b> ayrılır ve dizilim [Ar] olur."}],"ans":"En dıştaki ve en az tutulan elektron 4s'te olduğundan, K⁺ oluşurken bu elektron kopar ve dizilim [Ar] olur."},
{"q":"Bir atomun elektron dizilimi 1s² 2s² 2p⁶ 3s² 3p⁴ ise bu atomun grup ve değerlik elektron sayısını dizilimden çıkarın.","steps":[{"t":"Değerlik kabuğu","a":"3s² 3p⁴","d":"En yüksek baş kuantum sayısı n = 3'tür; değerlik kabuğu 3s² 3p⁴, toplam 6 elektrondur."},{"t":"Grup belirleme","a":"6A grubu","d":"6 değerlik elektronu, atomun periyodik tabloda <b>6A grubunda</b> (kükürt) olduğunu gösterir."}],"ans":"Değerlik elektron sayısı 6'dır; atom 6A grubunda yer alır (kükürt)."},
{"q":"Aynı orbitaldeki iki elektronun dört kuantum sayısının tümüyle aynı olamayacağını Pauli ilkesiyle açıklayın.","steps":[{"t":"İlk üç kuantum sayısı","a":"aynı","d":"Aynı orbitaldeki iki elektronun n, ℓ ve mₗ değerleri aynıdır (aynı orbital)."},{"t":"Spin farkı zorunlu","a":"mₛ = +½ ve −½","d":"Pauli ilkesine göre dört kuantum sayısı aynı olamaz; bu yüzden spin kuantum sayıları <b>zıt</b> olmak zorundadır (↑↓)."}],"ans":"İlk üç kuantum sayısı aynı olduğundan, Pauli ilkesi gereği iki elektron yalnızca zıt spinle (mₛ = +½ ve −½) ayrılır; böylece dört kuantum sayısı asla tümüyle aynı olmaz."},
{"q":"Karbonun temel hâl orbital diyagramında 2p elektronlarının aynı orbitalde eşleşmek yerine ayrı orbitallere dağılmasının enerjisel nedeni nedir?","steps":[{"t":"Eşleşme maliyeti","a":"itme enerjisi","d":"İki elektron aynı orbitalde eşleşince aralarındaki itme (eşleşme enerjisi) artar."},{"t":"Hund tercihi","a":"ayrı orbital, paralel spin","d":"Bu itmeyi azaltmak için elektronlar <b>ayrı orbitallere</b> paralel spinle dağılır; bu daha düşük enerjili, daha kararlı düzendir."}],"ans":"Aynı orbitalde eşleşme elektron itmesini artırdığından, Hund kuralı gereği elektronlar ayrı orbitallere paralel spinle dağılarak daha düşük enerjili düzeni seçer."},
{"q":"Çinko (Z = 30) atomunun elektron dizilimini kor gösterimiyle yazıp 3d ve 4s düzeylerinin doluluğunu yorumlayın.","steps":[{"t":"Dizilim","a":"[Ar]3d¹⁰4s²","d":"Kalan 12 elektron önce 4s'e (2), sonra 3d'ye (10) girer: [Ar]3d¹⁰4s²."},{"t":"Doluluk yorumu","a":"d tam dolu","d":"3d alt kabuğu <b>tam dolu (d¹⁰)</b> ve 4s dolu olduğundan çinko kararlı bir düzene sahiptir."}],"ans":"Çinkonun dizilimi [Ar]3d¹⁰4s²'dir; hem 3d tam dolu (d¹⁰) hem 4s dolu olduğundan kararlı bir yapı oluşur."},
{"q":"Bir atomun elektron dizilimi 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁵ olarak verilirse, bu atomun atom numarasını ve eşleşmemiş elektron sayısını bulun.","steps":[{"t":"Elektron toplamı","a":"25","d":"Elektronlar toplanır: 2 + 2 + 6 + 2 + 6 + 2 + 5 = 25; atom numarası 25'tir (mangan)."},{"t":"Eşleşmemiş elektron","a":"5 elektron","d":"3d⁵ düzeyinde 5 orbitalin her birinde birer elektron (Hund) vardır; <b>5 eşleşmemiş</b> elektron bulunur."}],"ans":"Atom numarası 25'tir (mangan) ve 3d⁵ yarı dolu olduğundan 5 eşleşmemiş elektron vardır."},
{"q":"Niçin 3d orbitalleri 4s'ten sonra dolmaya başlasa da iyonlaşmada önce 4s elektronları kopar? Bu görünür çelişkiyi açıklayın.","steps":[{"t":"Doldurmada 4s önce","a":"nötr atomda düşük enerji","d":"Boş 3d varken 4s, 3d'den biraz düşük enerjili olduğundan Aufbau'da önce dolar."},{"t":"İyonlaşmada tersine","a":"4s daha dışta","d":"3d dolmaya başlayınca enerji sıralaması değişir; 4s daha dış ve daha az tutulan düzey olur, bu yüzden iyonlaşmada <b>önce 4s elektronları</b> kopar."}],"ans":"Nötr atomda 4s, 3d'den düşük enerjili olduğu için önce dolar; ancak 3d dolunca 4s daha dışta ve az tutulan düzey hâline geldiğinden iyonlaşmada önce 4s elektronları kopar."},
{"q":"Mangan (Z = 25) ile demir (Z = 26) iyonlarından Mn²⁺ ve Fe²⁺'nin 3d elektron sayılarını dizilimden bulun.","steps":[{"t":"Nötr dizilimler","a":"Mn:[Ar]3d⁵4s², Fe:[Ar]3d⁶4s²","d":"Mangan [Ar]3d⁵4s², demir [Ar]3d⁶4s² dizilimine sahiptir."},{"t":"İki elektron kopar","a":"önce 4s","d":"+2 iyonlarda önce 4s'teki 2 elektron kopar: Mn²⁺ → <b>[Ar]3d⁵</b>, Fe²⁺ → <b>[Ar]3d⁶</b>."}],"ans":"Mn²⁺ 3d⁵ (5 elektron), Fe²⁺ ise 3d⁶ (6 elektron) düzenine sahiptir; her ikisinde de önce 4s elektronları koptu."},
{"q":"Bir orbital diyagramında 2p⁴ düzeyinin neden ↑↓ ↑ ↑ biçiminde gösterildiğini Hund ve Pauli ilkeleriyle gerekçelendirin.","steps":[{"t":"Önce tek tek","a":"3 orbitale ↑ ↑ ↑","d":"İlk üç elektron Hund kuralıyla üç orbitale paralel spinle dağılır (↑ ↑ ↑)."},{"t":"4. elektron eşleşir","a":"↑↓ ↑ ↑","d":"Dördüncü elektron yeni boş orbital kalmadığından ilk orbitale Pauli gereği <b>zıt spinle</b> eşleşir: ↑↓ ↑ ↑."}],"ans":"İlk üç elektron Hund kuralıyla ayrı orbitallere (↑ ↑ ↑), dördüncü elektron ise boş orbital kalmadığından Pauli gereği ilk orbitale zıt spinle (↑↓ ↑ ↑) yerleşir.","fig":"<svg viewBox='0 0 340 120'><rect x='40' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='110' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='180' y='45' width='60' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='62' y='68' font-size='20' fill='#2b6be0'>↑</text><text x='76' y='68' font-size='20' fill='#e0552b'>↓</text><text x='140' y='68' font-size='20' text-anchor='middle' fill='#2b6be0'>↑</text><text x='210' y='68' font-size='20' text-anchor='middle' fill='#2b6be0'>↑</text><text x='258' y='65' font-size='13' fill='#1a2b45'>2p⁴</text></svg>"},
{"q":"Alüminyum (Z = 13) atomunun temel hâl dizilimini yazıp en yüksek enerjili (son giren) elektronunun bulunduğu orbitali belirtin.","steps":[{"t":"Dizilim","a":"1s² 2s² 2p⁶ 3s² 3p¹","d":"13 elektron Aufbau sırasıyla 1s² 2s² 2p⁶ 3s² 3p¹ biçiminde dağılır."},{"t":"Son elektron","a":"3p orbitali","d":"En son giren elektron <b>3p</b> orbitalindedir; bu, alüminyumu 3. periyot 3A grubuna yerleştirir."}],"ans":"Alüminyumun dizilimi 1s² 2s² 2p⁶ 3s² 3p¹'dir; son elektron 3p orbitaline girmiştir."},
{"q":"Elektron dizilimi 1s² 2s² 2p⁶ 3s² 3p⁶ olan bir atom (argon) neden kimyasal olarak çok kararlıdır?","steps":[{"t":"Dolu kabuk","a":"3s² 3p⁶ tam dolu","d":"Değerlik kabuğu 3s² 3p⁶ ile tamamen dolu (oktet) hâldedir."},{"t":"Kararlılık","a":"tepkimeye girmez","d":"Tam dolu değerlik kabuğu en düşük enerjili, en kararlı düzendir; bu yüzden argon <b>elektron alıp vermeye eğilimli değildir</b>."}],"ans":"Değerlik kabuğu (3s² 3p⁶) tamamen dolu olduğundan argon çok düşük enerjili, kararlı bir düzendedir ve kolayca tepkimeye girmez."},
{"q":"Bir atomun 4s² 3d³ değerlik düzenine sahip olduğu söyleniyor. Bu atomun toplam elektron sayısını ve hangi blokta yer aldığını belirleyin.","steps":[{"t":"Toplam elektron","a":"23 (vanadyum)","d":"[Ar] çekirdeği 18 elektron; üzerine 4s²3d³ = 5 elektron eklenir, toplam 23 (vanadyum)."},{"t":"Blok","a":"d bloğu","d":"Son giren elektronlar 3d orbitaline yerleştiğinden atom <b>d bloğu</b> (geçiş metali) elementidir."}],"ans":"Atom 23 elektronlu vanadyumdur; son elektronları 3d'ye girdiği için d bloğunda (geçiş metalleri) yer alır."},
{"q":"Silisyum (Z = 14) atomunun orbital diyagramında kaç eşleşmemiş elektron bulunur? Diziliminden çıkarın.","steps":[{"t":"Dizilim","a":"1s² 2s² 2p⁶ 3s² 3p²","d":"14 elektron 1s² 2s² 2p⁶ 3s² 3p² biçiminde dağılır."},{"t":"3p² dağılımı","a":"↑ ↑ (2 eşleşmemiş)","d":"3p² düzeyinde 2 elektron Hund gereği ayrı orbitallere yerleşir (↑ ↑); bu yüzden <b>2 eşleşmemiş</b> elektron vardır."}],"ans":"Silisyumun dizilimi 1s² 2s² 2p⁶ 3s² 3p²'dir; 3p² Hund kuralıyla ↑ ↑ olduğundan 2 eşleşmemiş elektronu vardır."}
]
}
}};
