globalThis.__OUT = {"kureselSimetri":{
"ilkokul":{
"kolay":[
{"q":"Bir rafa kitapları dizerken bütün gözleri eşit doldurmak neden daha düzenli görünür?","steps":[{"t":"Eşit dağıtım","a":"her göz eşit","d":"Kitaplar her göze eşit sayıda dizilirse raf düzenli ve dengeli durur."},{"t":"Atomda da düzen","a":"eşit yerleşim","d":"Atomda da elektronlar <b>eşit ve düzenli</b> yerleşince yapı daha dengeli olur."}],"ans":"Eşit ve düzenli yerleşim daha dengeli durur; atomda da elektronların eşit dağılımı yapıyı kararlı yapar."},
{"q":"Bir takımda oyuncuların sahaya eşit dağılması mı, hepsinin bir köşede toplanması mı daha düzenlidir?","steps":[{"t":"Eşit dağılım","a":"dengeli takım","d":"Oyuncular sahaya eşit dağılırsa takım daha düzenli ve dengeli olur."},{"t":"Elektronlarda da öyle","a":"dengeli yerleşim","d":"Elektronlar da <b>eşit dağıldığında</b> atom daha kararlı bir yapı kazanır."}],"ans":"Eşit dağılım daha dengelidir; atomda elektronların dengeli yerleşmesi de kararlılık sağlar."},
{"q":"Bir kutudaki bölmelerin hepsine birer şeker koymak mı, bir bölmeyi tıka basa doldurup diğerini boş bırakmak mı daha düzenlidir?","steps":[{"t":"Eşit doldurma","a":"her bölmeye birer","d":"Her bölmeye birer şeker koymak daha düzenli ve dengeli görünür."},{"t":"Atomdaki benzetme","a":"dengeli yapı","d":"Atomda da elektronlar bölmelere <b>dengeli</b> dağılınca yapı kararlı olur."}],"ans":"Her bölmeye eşit dağıtmak daha düzenlidir; atomda da elektronların dengeli dağılımı kararlılık verir."},
{"q":"Bir simit halkasına boncukları eşit aralıkla dizmek neden daha güzel ve dengeli durur?","steps":[{"t":"Eşit aralık","a":"simetrik dizilim","d":"Boncuklar eşit aralıkla dizilince halka her yönden aynı (simetrik) görünür."},{"t":"Atomda kararlılık","a":"dengeli yerleşim","d":"Atomda da elektronlar <b>eşit (simetrik)</b> dağıldığında yapı dengeli ve kararlı olur."}],"ans":"Eşit (simetrik) dizilim her yönden dengeli durur; atomda da elektronların simetrik dağılımı kararlılık sağlar."},
{"q":"Bir grup arkadaş oturma yerlerini eşit paylaşırsa mı, biri çok yer kaplayıp diğeri sıkışırsa mı daha rahat oturulur?","steps":[{"t":"Eşit paylaşım","a":"herkes rahat","d":"Yerler eşit paylaşılırsa herkes rahat eder, düzen bozulmaz."},{"t":"Elektronlarda da","a":"dengeli yer","d":"Elektronlar da yerleri <b>eşit paylaşınca</b> atom daha rahat ve kararlı olur."}],"ans":"Eşit paylaşım herkesi rahatlatır; atomda da elektronların dengeli paylaşımı kararlı bir yapı oluşturur."}
],
"zor":[
{"q":"Bazen bir oyuncu, takımın dengesi için kendi rahat yerinden vazgeçip başka yere geçer. Atomda da elektronlar bazen neden benzer bir şey yapar?","steps":[{"t":"Denge için yer değişimi","a":"daha dengeli takım","d":"Bir oyuncu yer değiştirince takımın tamamı daha dengeli hâle gelebilir."},{"t":"Elektronun geçişi","a":"daha kararlı atom","d":"Atomda da bir elektron yer değiştirip dağılımı <b>eşit (dengeli)</b> yaparsa atom daha kararlı olur."}],"ans":"Tıpkı takımı dengeleyen oyuncu gibi, bir elektron yer değiştirip dağılımı eşitleyerek atomu daha kararlı yapabilir."},
{"q":"İki rafın birinde tüm gözler yarıya kadar eşit dolu, diğerinde gözler karışık dolu. Hangisi daha düzenli görünür?","steps":[{"t":"Eşit yarı dolu","a":"düzenli görünüm","d":"Tüm gözleri yarıya kadar eşit dolu raf, her yönden dengeli ve düzenli görünür."},{"t":"Atomda kararlılık","a":"yarı dolu denge","d":"Atomda da bölmeler <b>eşit yarı dolu</b> olduğunda özel bir denge ve kararlılık oluşur."}],"ans":"Eşit yarı dolu raf daha düzenlidir; atomda da bölmelerin eşit yarı dolu olması kararlılık sağlar."},
{"q":"Bir elektronun komşu bir bölmeye geçmesiyle bütün bölmeler eşit hâle geliyorsa, atom bu geçişi neden tercih eder?","steps":[{"t":"Eşitlik sağlanır","a":"dengeli dağılım","d":"Tek bir elektronun geçişiyle tüm bölmeler eşit (dengeli) dolabilir."},{"t":"Kararlılık kazanılır","a":"daha kararlı atom","d":"Eşit dağılım atomu <b>daha kararlı</b> yaptığı için atom bu geçişi tercih eder."}],"ans":"Tek elektronun geçişiyle dağılım eşitlenip atom daha kararlı olduğundan, atom bu geçişi tercih eder."},
{"q":"Tamamen dolu bir kutu ile tamamen boş bir kutu mu, yoksa yarısı dolu karışık bir kutu mu daha düzenli sayılır?","steps":[{"t":"Tam dolu/tam eşit","a":"düzenli","d":"Tamamen dolu ya da her gözü eşit dolu kutular düzenli ve dengelidir."},{"t":"Atomdaki karşılığı","a":"tam dolu kararlılık","d":"Atomda da bir bölme <b>tam dolu</b> olduğunda özel bir kararlılık ortaya çıkar."}],"ans":"Tam dolu (ya da eşit dolu) düzen daha kararlıdır; atomda da bölmelerin tam dolması özel kararlılık sağlar."},
{"q":"Bir orkestrada herkesin sesi eşit dengelenince müzik neden daha hoş olur? Bu, atomdaki elektron dengesiyle nasıl benzeşir?","steps":[{"t":"Eşit denge","a":"uyumlu ses","d":"Sesler eşit dengelenince orkestra uyumlu ve hoş bir müzik çıkarır."},{"t":"Atomda uyum","a":"dengeli elektron dağılımı","d":"Atomda da elektronlar <b>dengeli</b> dağıldığında yapı uyumlu ve kararlı olur."}],"ans":"Eşit denge orkestrada uyum yaratır; atomda da elektronların dengeli dağılımı kararlı, uyumlu bir yapı oluşturur."}
]
},
"ortaokul":{
"kolay":[
{"q":"Bir alt kabuğun yarısının eşit dolması (her orbitalde birer elektron) atoma ne kazandırır?","steps":[{"t":"Yarı dolu düzen","a":"simetrik dağılım","d":"Bir alt kabuğun yarısı, her orbitale birer elektron gelecek şekilde eşit (simetrik) dolar."},{"t":"Kararlılık","a":"ekstra denge","d":"Bu <b>yarı dolu</b> simetrik düzen atoma fazladan kararlılık kazandırır."}],"ans":"Bir alt kabuğun yarı dolu (simetrik) olması atoma fazladan kararlılık kazandırır."},
{"q":"Tam dolu bir alt kabuk neden kararlı kabul edilir?","steps":[{"t":"Tam dolu düzen","a":"hepsi eşleşmiş","d":"Tam dolu alt kabukta tüm orbitaller eşleşmiş elektronlarla doludur, dağılım simetriktir."},{"t":"En düşük enerji","a":"kararlı yapı","d":"Bu simetrik, <b>tam dolu</b> düzen düşük enerjili ve kararlıdır."}],"ans":"Tam dolu alt kabuk simetrik ve düşük enerjili olduğu için kararlı kabul edilir."},
{"q":"Krom atomu bazen elektron dağılımında küçük bir 'kayma' yapar. Bunun amacı nedir?","steps":[{"t":"Kayma olur","a":"bir elektron yer değiştirir","d":"Kromda bir elektron, beklenenden farklı bir bölmeye geçer."},{"t":"Amaç kararlılık","a":"daha dengeli düzen","d":"Bu kayma, alt kabuğu <b>yarı dolu (simetrik)</b> yaparak atomu daha kararlı kılmak içindir."}],"ans":"Krom, bir elektronu kaydırarak yarı dolu simetrik düzene ulaşır ve böylece daha kararlı olur."},
{"q":"Elektronların bir alt kabukta eşit (simetrik) dağılması neden tercih edilir?","steps":[{"t":"Eşit dağılım","a":"simetrik düzen","d":"Elektronlar bir alt kabukta eşit dağıldığında simetrik bir düzen oluşur."},{"t":"Düşük enerji","a":"kararlılık","d":"Simetrik düzen genellikle daha <b>düşük enerjili</b> ve kararlı olduğundan tercih edilir."}],"ans":"Simetrik (eşit) dağılım daha düşük enerjili ve kararlı olduğu için elektronlar bu düzeni tercih eder."},
{"q":"Yarı dolu ve tam dolu alt kabukların ortak özelliği nedir?","steps":[{"t":"İkisi de simetrik","a":"dengeli dağılım","d":"Yarı dolu (her orbitalde 1 elektron) ve tam dolu (hepsi eşleşmiş) düzenlerin ikisi de simetriktir."},{"t":"Ekstra kararlılık","a":"daha dengeli","d":"Bu simetri her ikisine de <b>fazladan kararlılık</b> kazandırır."}],"ans":"Yarı dolu ve tam dolu alt kabukların ikisi de simetrik olduğundan fazladan kararlılık kazandırır."}
],
"zor":[
{"q":"Krom atomu, dağılımını değiştirip bir alt kabuğu yarı dolu hâle getirerek neden daha kararlı olur?","steps":[{"t":"Yarı dolu düzen","a":"simetrik dağılım","d":"Krom bir elektronu kaydırarak alt kabuğunu yarı dolu (her orbitalde birer elektron) yapar."},{"t":"Kararlılık artar","a":"düşük enerji","d":"Bu <b>simetrik yarı dolu</b> düzen daha düşük enerjili ve kararlı olduğundan krom bunu tercih eder."}],"ans":"Krom bir elektron kaydırarak yarı dolu simetrik düzene geçer; bu düzen düşük enerjili olduğundan atom daha kararlı olur."},
{"q":"Bakır atomunun bir alt kabuğu tam dolu hâle getirmesi atomu nasıl etkiler?","steps":[{"t":"Tam dolu düzen","a":"simetrik dağılım","d":"Bakır bir elektron kaydırarak alt kabuğunu tam dolu (hepsi eşleşmiş) hâle getirir."},{"t":"Kararlılık","a":"düşük enerji","d":"Bu <b>tam dolu simetrik</b> düzen düşük enerjili ve kararlıdır; bu yüzden bakır onu tercih eder."}],"ans":"Bakır bir elektron kaydırarak tam dolu simetrik düzene geçer; bu düşük enerjili düzen atomu daha kararlı yapar."},
{"q":"İki atomdan birinde alt kabuk karışık (eşit olmayan) dolu, diğerinde tam dolu. Hangisi daha kararlıdır, neden?","steps":[{"t":"Karışık dolu","a":"daha az dengeli","d":"Karışık (eşit olmayan) dolu alt kabuk simetrik değildir, enerjisi daha yüksektir."},{"t":"Tam dolu","a":"simetrik ve kararlı","d":"Tam dolu alt kabuk <b>simetriktir</b> ve düşük enerjili olduğundan daha kararlıdır."}],"ans":"Tam dolu olan daha kararlıdır; çünkü simetrik ve düşük enerjili bir düzendir, karışık dolu ise değildir."},
{"q":"Bir elektronun küçük bir geçiş yapması atomu nasıl daha kararlı hâle getirebilir?","steps":[{"t":"Geçişin sonucu","a":"simetrik düzen","d":"Bir elektronun komşu boş bölmeye geçmesi, alt kabuğu yarı dolu veya tam dolu (simetrik) yapabilir."},{"t":"Kararlılık kazancı","a":"daha düşük enerji","d":"Oluşan <b>simetrik</b> düzen daha düşük enerjili olduğundan atom bu geçişle daha kararlı hâle gelir."}],"ans":"Bir elektronun geçişiyle alt kabuk simetrik (yarı/tam dolu) hâle gelir; bu düşük enerjili düzen atomu daha kararlı yapar."},
{"q":"Krom ile bakırın ortak özelliği, ikisinin de elektron dağılımında 'beklenenden farklı' davranmasıdır. Bu davranışın temel nedeni nedir?","steps":[{"t":"Ortak amaç","a":"simetrik kabuk","d":"Hem krom hem bakır bir elektron kaydırarak alt kabuğu simetrik (krom yarı dolu, bakır tam dolu) yapar."},{"t":"Temel neden","a":"ekstra kararlılık","d":"Her ikisi de bu kaymayı <b>fazladan kararlılık</b> kazanmak için yapar."}],"ans":"Her ikisi de bir elektron kaydırıp alt kabuğu simetrik (yarı/tam dolu) yaparak fazladan kararlılık kazanmak için bu farklı davranışı gösterir."}
]
},
"lise":{
"kolay":[
{"q":"Yarı dolu (d⁵) ve tam dolu (d¹⁰) alt kabukların atoma kazandırdığı özellik nedir?","steps":[{"t":"Simetrik dağılım","a":"küresel simetri","d":"d⁵ (her orbitalde 1 elektron) ve d¹⁰ (hepsi eşleşmiş) düzenleri küresel simetriye sahiptir."},{"t":"Kararlılık","a":"ekstra kararlılık","d":"Bu simetrik düzenler atoma <b>fazladan kararlılık</b> (düşük enerji) kazandırır."}],"ans":"Yarı dolu (d⁵) ve tam dolu (d¹⁰) alt kabuklar küresel simetri sayesinde atoma fazladan kararlılık kazandırır."},
{"q":"Kromun (Z = 24) beklenen ve gerçek elektron dizilimi nedir?","steps":[{"t":"Beklenen dizilim","a":"[Ar]3d⁴4s²","d":"Aufbau kuralına göre kromun beklenen dizilimi [Ar]3d⁴4s²'dir."},{"t":"Gerçek dizilim","a":"[Ar]3d⁵4s¹","d":"Gerçekte 4s'ten 3d'ye bir elektron geçer; dizilim <b>[Ar]3d⁵4s¹</b> olur (3d yarı dolu)."}],"ans":"Kromun beklenen dizilimi [Ar]3d⁴4s², gerçek dizilimi ise [Ar]3d⁵4s¹'dir.","fig":"<svg viewBox='0 0 360 150'><rect x='20' y='50' width='40' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='62' y='50' width='40' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='104' y='50' width='40' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='146' y='50' width='40' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='188' y='50' width='40' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='40' y='73' font-size='18' text-anchor='middle' fill='#2b6be0'>↑</text><text x='82' y='73' font-size='18' text-anchor='middle' fill='#2b6be0'>↑</text><text x='124' y='73' font-size='18' text-anchor='middle' fill='#2b6be0'>↑</text><text x='166' y='73' font-size='18' text-anchor='middle' fill='#2b6be0'>↑</text><text x='208' y='73' font-size='18' text-anchor='middle' fill='#2b6be0'>↑</text><rect x='270' y='50' width='40' height='34' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='285' y='73' font-size='16' fill='#2b6be0'>↑</text><text x='124' y='110' font-size='13' text-anchor='middle' fill='#1a2b45'>3d⁵ (yarı dolu)</text><text x='290' y='110' font-size='13' text-anchor='middle' fill='#1a2b45'>4s¹</text></svg>"},
{"q":"Bakırın (Z = 29) beklenen ve gerçek elektron dizilimi nedir?","steps":[{"t":"Beklenen dizilim","a":"[Ar]3d⁹4s²","d":"Aufbau kuralına göre bakırın beklenen dizilimi [Ar]3d⁹4s²'dir."},{"t":"Gerçek dizilim","a":"[Ar]3d¹⁰4s¹","d":"Gerçekte 4s'ten 3d'ye bir elektron geçer; dizilim <b>[Ar]3d¹⁰4s¹</b> olur (3d tam dolu)."}],"ans":"Bakırın beklenen dizilimi [Ar]3d⁹4s², gerçek dizilimi ise [Ar]3d¹⁰4s¹'dir.","fig":"<svg viewBox='0 0 360 130'><text x='10' y='30' font-size='13' fill='#1a2b45'>3d¹⁰</text><rect x='20' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='56' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='92' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='128' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='164' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='30' y='62' font-size='14' fill='#2b6be0'>↑</text><text x='42' y='62' font-size='14' fill='#e0552b'>↓</text><text x='66' y='62' font-size='14' fill='#2b6be0'>↑</text><text x='78' y='62' font-size='14' fill='#e0552b'>↓</text><text x='102' y='62' font-size='14' fill='#2b6be0'>↑</text><text x='114' y='62' font-size='14' fill='#e0552b'>↓</text><text x='138' y='62' font-size='14' fill='#2b6be0'>↑</text><text x='150' y='62' font-size='14' fill='#e0552b'>↓</text><text x='174' y='62' font-size='14' fill='#2b6be0'>↑</text><text x='186' y='62' font-size='14' fill='#e0552b'>↓</text><rect x='250' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='260' y='62' font-size='14' fill='#2b6be0'>↑</text><text x='240' y='95' font-size='13' fill='#1a2b45'>4s¹</text><text x='90' y='95' font-size='13' fill='#1a2b45'>tam dolu (d¹⁰)</text></svg>"},
{"q":"Kromda 4s elektronunun 3d'ye geçmesinin nedeni nedir?","steps":[{"t":"Geçişin sonucu","a":"3d⁵ ve 4s¹","d":"Bir 4s elektronu 3d'ye geçince 3d⁵ (yarı dolu) ve 4s¹ düzeni oluşur."},{"t":"Kararlılık kazancı","a":"küresel simetri","d":"Yarı dolu 3d⁵ <b>küresel simetri</b> sağlar; bu düşük enerjili düzen atomu daha kararlı yapar."}],"ans":"Krom, 4s'ten 3d'ye bir elektron aktararak yarı dolu (d⁵) küresel simetrik düzene ulaşır; bu daha kararlı olduğu için bu geçiş gerçekleşir."},
{"q":"Bakırda 4s elektronunun 3d'ye geçmesinin nedeni nedir?","steps":[{"t":"Geçişin sonucu","a":"3d¹⁰ ve 4s¹","d":"Bir 4s elektronu 3d'ye geçince 3d¹⁰ (tam dolu) ve 4s¹ düzeni oluşur."},{"t":"Kararlılık kazancı","a":"tam dolu simetri","d":"Tam dolu 3d¹⁰ <b>küresel simetrik</b> ve düşük enerjilidir; bu yüzden bakır bu düzeni tercih eder."}],"ans":"Bakır, 4s'ten 3d'ye bir elektron aktararak tam dolu (d¹⁰) küresel simetrik düzene ulaşır; bu daha kararlı olduğu için geçiş gerçekleşir."},
{"q":"Bir d alt kabuğu en fazla kaç elektron alır ve hangi dolulukları 'özel kararlı' kabul edilir?","steps":[{"t":"d kapasitesi","a":"10 elektron","d":"d alt kabuğunda 5 orbital vardır, en fazla 10 elektron alır."},{"t":"Özel kararlı durumlar","a":"d⁵ ve d¹⁰","d":"Yarı dolu <b>d⁵</b> ve tam dolu <b>d¹⁰</b> düzenleri küresel simetri nedeniyle özel kararlı kabul edilir."}],"ans":"d alt kabuğu en fazla 10 elektron alır; yarı dolu d⁵ ve tam dolu d¹⁰ düzenleri özel kararlı kabul edilir.","fig":"<svg viewBox='0 0 360 170'><text x='10' y='28' font-size='13' fill='#1a2b45'>d⁵ (yarı dolu)</text><rect x='20' y='38' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='52' y='38' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='84' y='38' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='116' y='38' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='148' y='38' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='35' y='58' font-size='15' text-anchor='middle' fill='#2b6be0'>↑</text><text x='67' y='58' font-size='15' text-anchor='middle' fill='#2b6be0'>↑</text><text x='99' y='58' font-size='15' text-anchor='middle' fill='#2b6be0'>↑</text><text x='131' y='58' font-size='15' text-anchor='middle' fill='#2b6be0'>↑</text><text x='163' y='58' font-size='15' text-anchor='middle' fill='#2b6be0'>↑</text><text x='10' y='108' font-size='13' fill='#1a2b45'>d¹⁰ (tam dolu)</text><rect x='20' y='118' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='52' y='118' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='84' y='118' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='116' y='118' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='148' y='118' width='30' height='28' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='28' y='138' font-size='13' fill='#2b6be0'>↑</text><text x='38' y='138' font-size='13' fill='#e0552b'>↓</text><text x='60' y='138' font-size='13' fill='#2b6be0'>↑</text><text x='70' y='138' font-size='13' fill='#e0552b'>↓</text><text x='92' y='138' font-size='13' fill='#2b6be0'>↑</text><text x='102' y='138' font-size='13' fill='#e0552b'>↓</text><text x='124' y='138' font-size='13' fill='#2b6be0'>↑</text><text x='134' y='138' font-size='13' fill='#e0552b'>↓</text><text x='156' y='138' font-size='13' fill='#2b6be0'>↑</text><text x='166' y='138' font-size='13' fill='#e0552b'>↓</text></svg>"},
{"q":"Kromun gerçek diziliminde 3d düzeyinde kaç eşleşmemiş elektron bulunur?","steps":[{"t":"Dizilim","a":"[Ar]3d⁵4s¹","d":"Kromun gerçek dizilimi [Ar]3d⁵4s¹'dir; 3d düzeyinde 5 elektron vardır."},{"t":"Hund dağılımı","a":"5 eşleşmemiş","d":"3d⁵'te beş orbitalin her birinde birer elektron bulunur (Hund); <b>5 elektron eşleşmemiştir</b>."}],"ans":"Kromun 3d⁵ düzeyinde 5 elektronun tümü eşleşmemiştir; ayrıca 4s¹ ile birlikte toplam 6 eşleşmemiş elektronu vardır."},
{"q":"Tam dolu d¹⁰ düzeninde kaç eşleşmemiş elektron bulunur?","steps":[{"t":"Tam dolu kabuk","a":"hepsi eşleşmiş","d":"d¹⁰ düzeyinde 5 orbitalin hepsi ikişer (eşleşmiş) elektron taşır."},{"t":"Eşleşmemiş yok","a":"0 elektron","d":"Tüm elektronlar eşleştiği için <b>eşleşmemiş elektron bulunmaz</b>."}],"ans":"Tam dolu d¹⁰ düzeninde tüm elektronlar eşleşmiştir; eşleşmemiş elektron bulunmaz."},
{"q":"Kromun [Ar]3d⁵4s¹ ve bakırın [Ar]3d¹⁰4s¹ diziliminin ortak özelliği nedir?","steps":[{"t":"Ortak geçiş","a":"4s → 3d","d":"Her ikisinde de bir 4s elektronu 3d'ye geçmiş, 4s¹ düzeyi oluşmuştur."},{"t":"Ortak amaç","a":"simetrik d kabuğu","d":"Bu geçiş, kromda <b>yarı dolu d⁵</b>, bakırda <b>tam dolu d¹⁰</b> küresel simetrik düzen sağlar."}],"ans":"Her ikisinde de bir 4s elektronu 3d'ye geçerek 4s¹ olur; böylece krom d⁵ (yarı dolu), bakır d¹⁰ (tam dolu) küresel simetrik kararlı düzene ulaşır."},
{"q":"Küresel simetri kavramı yarı dolu ve tam dolu alt kabuklarda neyi ifade eder?","steps":[{"t":"Eşit elektron dağılımı","a":"simetrik bulut","d":"d⁵ ve d¹⁰ düzenlerinde elektronlar orbitallere eşit dağılır, elektron bulutu her yönde benzer olur."},{"t":"Kararlılık","a":"düşük enerji","d":"Bu küresel <b>simetrik</b> dağılım çekirdek perdelemesini dengeler ve düşük enerjili, kararlı bir düzen oluşturur."}],"ans":"Küresel simetri, d⁵ ve d¹⁰ gibi alt kabuklarda elektronların eşit dağılarak simetrik, düşük enerjili ve kararlı bir bulut oluşturmasını ifade eder."},
{"q":"Manganın (Z = 25) [Ar]3d⁵4s² dizilimi neden krom gibi bir kaymaya ihtiyaç duymaz?","steps":[{"t":"Mangan dizilimi","a":"[Ar]3d⁵4s²","d":"Manganda 3d zaten doğrudan 5 elektronla (yarı dolu) dolar, 4s de doludur."},{"t":"Kayma gereksiz","a":"d⁵ hazır","d":"3d⁵ <b>küresel simetri</b> kendiliğinden sağlandığından mangan, krom gibi bir elektron kaydırmasına gerek duymaz."}],"ans":"Manganda 3d zaten yarı dolu (d⁵) hâle geldiğinden küresel simetri kendiliğinden sağlanır; bu yüzden krom gibi bir kaymaya ihtiyaç duymaz."},
{"q":"Çinkonun (Z = 30) [Ar]3d¹⁰4s² dizilimi neden bakır gibi bir kaymaya ihtiyaç duymaz?","steps":[{"t":"Çinko dizilimi","a":"[Ar]3d¹⁰4s²","d":"Çinkoda 3d zaten 10 elektronla (tam dolu) dolar, 4s de doludur."},{"t":"Kayma gereksiz","a":"d¹⁰ hazır","d":"3d¹⁰ <b>küresel simetri</b> kendiliğinden sağlandığından çinko, bakır gibi bir kaymaya gerek duymaz."}],"ans":"Çinkoda 3d zaten tam dolu (d¹⁰) olduğundan küresel simetri kendiliğinden sağlanır; bu yüzden bakır gibi bir kaymaya gerek yoktur."},
{"q":"Kromda 4s'ten 3d'ye geçiş olunca 4s orbitalinde kaç elektron kalır?","steps":[{"t":"Başlangıç","a":"4s² beklenir","d":"Aufbau'a göre 4s'te 2 elektron beklenir ([Ar]3d⁴4s²)."},{"t":"Geçiş sonrası","a":"4s¹","d":"Bir 4s elektronu 3d'ye geçtiğinden 4s'te <b>1 elektron</b> kalır: [Ar]3d⁵4s¹."}],"ans":"Geçiş sonrası 4s'te 1 elektron kalır; kromun dizilimi [Ar]3d⁵4s¹ olur."},
{"q":"Yarı dolu d⁵ düzeninin kararlılığı, atomun manyetik özelliğini nasıl etkiler?","steps":[{"t":"Eşleşmemiş elektronlar","a":"5 tane","d":"d⁵ düzeyinde 5 elektronun tümü eşleşmemiştir (Hund kuralı)."},{"t":"Manyetik etki","a":"güçlü paramanyetiklik","d":"Çok sayıda eşleşmemiş elektron, atomu <b>güçlü paramanyetik</b> yapar; manyetik alana çekilir."}],"ans":"d⁵ düzeyinde 5 eşleşmemiş elektron bulunduğundan atom güçlü paramanyetik olur ve manyetik alana çekilir."},
{"q":"Periyodik tabloda 6. grup (krom) ve 11. grup (bakır) elementlerinin elektron diziliminde benzer bir istisna görülmesinin temel nedeni nedir?","steps":[{"t":"Konum ve ihtiyaç","a":"d⁴ ve d⁹ kararsız","d":"Bu gruplarda Aufbau d⁴ (6. grup) ve d⁹ (11. grup) verir; ikisi de simetrik değildir."},{"t":"Simetri arayışı","a":"d⁵ ve d¹⁰","d":"Bir 4s elektronu 3d'ye geçince <b>d⁵</b> (yarı dolu) ve <b>d¹⁰</b> (tam dolu) küresel simetrik kararlı düzen elde edilir."}],"ans":"6. grupta d⁴, 11. grupta d⁹ simetrik olmadığından, bir 4s elektronu 3d'ye geçer; böylece d⁵ ve d¹⁰ küresel simetrik kararlı düzenler oluşur."}
],
"zor":[
{"q":"Kromun temel hâl diziliminin [Ar]3d⁴4s² yerine [Ar]3d⁵4s¹ olmasını küresel simetri ve enerji açısından gerekçelendirin.","steps":[{"t":"İki düzenin karşılaştırması","a":"d⁵4s¹ daha kararlı","d":"[Ar]3d⁴4s² simetrik değildir; bir 4s elektronu 3d'ye geçince 3d⁵ yarı dolu (simetrik) olur."},{"t":"Enerji kazancı","a":"değiş-tokuş enerjisi","d":"Yarı dolu d⁵'teki paralel spinli 5 elektron arasındaki <b>değiş-tokuş (exchange) enerjisi</b> en yükseğe çıkar; bu, küçük 4s-3d enerji farkını telafi edip düzeni daha kararlı kılar."}],"ans":"[Ar]3d⁵4s¹'de 3d yarı dolu ve küresel simetriktir; paralel spinlerin değiş-tokuş enerjisi en yüksek olduğundan bu düzen [Ar]3d⁴4s²'den daha kararlıdır, bu yüzden krom bu dizilimi alır."},
{"q":"Bakırın [Ar]3d⁹4s² yerine [Ar]3d¹⁰4s¹ dizilimini tercih etmesinin enerjisel temelini açıklayın.","steps":[{"t":"İki düzen","a":"d¹⁰4s¹ daha kararlı","d":"[Ar]3d⁹4s²'de 3d simetrik değildir; bir 4s elektronu 3d'ye geçince 3d¹⁰ tam dolu (simetrik) olur."},{"t":"Kararlılık nedeni","a":"tam dolu simetri","d":"Tam dolu d¹⁰ küresel simetriktir; tüm elektronlar eşleşip <b>en düşük enerjili</b> simetrik düzeni verir, bu küçük 4s-3d farkını telafi eder."}],"ans":"[Ar]3d¹⁰4s¹'de 3d tam dolu ve küresel simetriktir; bu düşük enerjili simetrik düzen, 4s-3d enerji farkını telafi ederek [Ar]3d⁹4s²'den daha kararlı olduğundan bakır bu dizilimi alır."},
{"q":"Cr ve Cu istisnalarında geçişin neden 4s'ten 3d'ye doğru olduğunu (tersinin değil) açıklayın.","steps":[{"t":"Enerji yakınlığı","a":"4s ≈ 3d","d":"Geçiş metallerinde 4s ve 3d enerjileri birbirine çok yakındır, küçük bir kazanç dengeyi değiştirebilir."},{"t":"Simetri sağlayan yön","a":"4s → 3d","d":"3d'yi d⁵ ya da d¹⁰ yapan yön <b>4s'ten 3d'ye</b> geçiştir; ters yön simetri kazandırmayacağından gerçekleşmez."}],"ans":"4s ve 3d enerjileri çok yakın olduğundan, simetrik d⁵/d¹⁰ düzenini sağlayan 4s'ten 3d'ye geçiş gerçekleşir; ters yön kararlılık kazandırmadığı için olmaz."},
{"q":"Cr⁺ ve Cu⁺ iyonları oluşurken hangi orbitalden elektron koptuğunu ve sonuç dizilimleri açıklayın.","steps":[{"t":"Nötr dizilimler","a":"Cr:[Ar]3d⁵4s¹, Cu:[Ar]3d¹⁰4s¹","d":"Kromun nötr dizilimi [Ar]3d⁵4s¹, bakırınki [Ar]3d¹⁰4s¹'dir; her ikisinde de tek 4s elektronu vardır."},{"t":"İyonlaşma","a":"4s kopar","d":"En dıştaki tek 4s elektronu koptuğunda Cr⁺ → <b>[Ar]3d⁵</b>, Cu⁺ → <b>[Ar]3d¹⁰</b> olur; her ikisi de küresel simetrik kalır."}],"ans":"Her iki iyonda da tek 4s elektronu kopar: Cr⁺ [Ar]3d⁵ (yarı dolu), Cu⁺ [Ar]3d¹⁰ (tam dolu) olur; her iki iyon da küresel simetrik kararlı düzendedir."},
{"q":"Kromun 6 eşleşmemiş elektrona sahip olmasını dizilimiyle gösterip bunun küresel simetriyle ilişkisini açıklayın.","steps":[{"t":"Dizilim","a":"[Ar]3d⁵4s¹","d":"Kromun gerçek dizilimi [Ar]3d⁵4s¹'dir."},{"t":"Eşleşmemiş elektronlar","a":"3d⁵ (5) + 4s¹ (1) = 6","d":"3d⁵'te beş orbitalin her birinde birer eşleşmemiş elektron, 4s'te de bir tek elektron vardır; toplam <b>6 eşleşmemiş</b> elektron. Bu, yarı dolu küresel simetrik düzenin sonucudur."}],"ans":"Kromun [Ar]3d⁵4s¹ dizilimi 3d⁵'te 5, 4s¹'de 1 olmak üzere 6 eşleşmemiş elektron taşır; bu, 4s elektronunun 3d'ye geçerek oluşturduğu yarı dolu küresel simetrik düzenin sonucudur."},
{"q":"Değiş-tokuş (exchange) enerjisi kavramını kullanarak yarı dolu d⁵ düzeninin neden ekstra kararlı olduğunu açıklayın.","steps":[{"t":"Paralel spin eşleşmeleri","a":"çok sayıda eşleşme","d":"d⁵'te 5 elektron paralel spinlidir; aynı spinli elektron çiftleri arasında kararlılık sağlayan değiş-tokuş etkileşimleri oluşur."},{"t":"Maksimum kazanç","a":"en yüksek exchange enerjisi","d":"Yarı dolu d⁵'te paralel spinli çift sayısı en yüksektir; bu da <b>değiş-tokuş enerjisini</b> en üst düzeye çıkararak düzeni özel kararlı yapar."}],"ans":"d⁵ düzeyindeki 5 paralel spinli elektron, en fazla sayıda değiş-tokuş etkileşimi oluşturur; bu enerji kazancı yarı dolu kabuğu özel kararlı kılar."},
{"q":"Aynı periyotta mangan [Ar]3d⁵4s² 'doğal' yarı dolu iken kromun [Ar]3d⁵4s¹ olarak istisna sayılmasının nedenini karşılaştırarak açıklayın.","steps":[{"t":"Mangan","a":"d⁵ doğrudan","d":"Manganın 7 değerlik elektronu Aufbau'da doğal olarak 3d⁵4s² verir; d⁵ kendiliğinden oluşur, istisna yoktur."},{"t":"Krom","a":"kayma ile d⁵","d":"Kromun beklenen dizilimi 3d⁴4s²'dir; <b>yarı dolu d⁵</b>'e ulaşmak için bir 4s elektronu 3d'ye kaymak zorundadır, bu yüzden istisnadır."}],"ans":"Manganda d⁵ Aufbau'dan doğal olarak çıkar; kromda ise d⁵ ancak bir 4s elektronunun 3d'ye kaymasıyla oluştuğundan krom bir istisnadır."},
{"q":"Geçiş metallerinde 4s ve 3d enerjilerinin yakın olması, Cr ve Cu istisnalarının ortaya çıkmasında neden belirleyicidir?","steps":[{"t":"Küçük enerji farkı","a":"4s ≈ 3d","d":"4s ile 3d orbitallerinin enerjileri çok yakın olduğundan, küçük bir kararlılık kazancı bile dağılımı değiştirmeye yetebilir."},{"t":"Simetri kazancı baskın gelir","a":"d⁵/d¹⁰ tercih edilir","d":"Yarı/tam dolu kabuğun sağladığı simetri ve değiş-tokuş enerjisi, bu <b>küçük enerji farkını</b> aşar; bu yüzden Cr ve Cu beklenenden farklı dizilim alır."}],"ans":"4s ve 3d enerjileri çok yakın olduğundan, d⁵/d¹⁰ simetrisinin sağladığı kararlılık kazancı bu küçük farkı aşar; bu nedenle Cr ve Cu istisnaları ortaya çıkar."},
{"q":"Cu²⁺ iyonunun dizilimini bularak bakırın iyonlaşmasında 3d ve 4s elektronlarının sırasını açıklayın.","steps":[{"t":"Nötr dizilim","a":"[Ar]3d¹⁰4s¹","d":"Bakırın nötr dizilimi [Ar]3d¹⁰4s¹'dir."},{"t":"İki elektron kopar","a":"önce 4s, sonra 3d","d":"İlk önce tek 4s elektronu (Cu⁺ → [Ar]3d¹⁰), ardından bir 3d elektronu kopar; Cu²⁺ → <b>[Ar]3d⁹</b> olur."}],"ans":"Cu²⁺'nin dizilimi [Ar]3d⁹'dur; önce 4s elektronu (Cu⁺ → [Ar]3d¹⁰), sonra bir 3d elektronu koparak oluşur."},
{"q":"Tam dolu d¹⁰ ve yarı dolu d⁵ düzenlerinin ikisinin de 'küresel simetrik' sayılmasına rağmen aralarındaki temel farkı eşleşmemiş elektron ve manyetiklik açısından karşılaştırın.","steps":[{"t":"d⁵ durumu","a":"5 eşleşmemiş, paramanyetik","d":"d⁵'te 5 orbitalin her birinde birer eşleşmemiş elektron vardır; atom güçlü paramanyetiktir."},{"t":"d¹⁰ durumu","a":"0 eşleşmemiş, diyamanyetik","d":"d¹⁰'da tüm elektronlar eşleşmiştir; eşleşmemiş elektron yoktur, bu yüzden bu düzey <b>diyamanyetik</b>tir."}],"ans":"Her ikisi de küresel simetriktir; ancak d⁵'te 5 eşleşmemiş elektron olduğundan güçlü paramanyetik, d¹⁰'da hiç eşleşmemiş elektron olmadığından diyamanyetik davranış görülür."},
{"q":"Kromun [Ar]3d⁵4s¹ diziliminden yola çıkarak değerlik elektron sayısını ve neden +2 ile +3 yükseltgenme basamaklarını kolayca verebildiğini açıklayın.","steps":[{"t":"Değerlik elektronları","a":"3d⁵ + 4s¹ = 6","d":"Kromun değerlik elektronları 3d ve 4s düzeylerindedir: 5 + 1 = 6 elektron."},{"t":"Yükseltgenme","a":"+2, +3 yaygın","d":"Önce 4s elektronu (+1 yönünde), sonra 3d elektronları kopabildiğinden krom kolayca <b>+2 ve +3</b> (hatta +6'ya kadar) basamak verir."}],"ans":"Kromun 6 değerlik elektronu (3d⁵4s¹) vardır; 4s ve 3d elektronları görece kolay koptuğundan +2, +3 (ve daha yükseğe kadar) yükseltgenme basamaklarını verebilir."},
{"q":"Bir öğrenci kromun dizilimini [Ar]3d⁴4s² yazıyor. Bu yazımın neden eksik/yanlış olduğunu küresel simetri ilkesiyle düzeltin.","steps":[{"t":"Yazımın sorunu","a":"simetri gözetilmemiş","d":"[Ar]3d⁴4s² yalnızca Aufbau'un ham hâlidir; d⁴ simetrik değildir ve gerçek temel hâli yansıtmaz."},{"t":"Doğru dizilim","a":"[Ar]3d⁵4s¹","d":"Bir 4s elektronu 3d'ye geçerek <b>yarı dolu d⁵</b> küresel simetrik kararlı düzeni oluşturur; doğru dizilim [Ar]3d⁵4s¹'dir."}],"ans":"[Ar]3d⁴4s² simetrik değildir ve gerçek temel hâli yansıtmaz; bir 4s elektronu 3d'ye geçerek d⁵ (yarı dolu) küresel simetri oluşur, doğru dizilim [Ar]3d⁵4s¹'dir."},
{"q":"Cr ve Cu dışında, 5. periyotta gümüş (Ag, Z = 47) gibi elementlerde de benzer istisnaların görülmesini küresel simetri ilkesiyle ilişkilendirin.","steps":[{"t":"Gümüşün durumu","a":"[Kr]4d¹⁰5s¹","d":"Gümüşte de bir 5s elektronu 4d'ye geçerek 4d¹⁰5s¹ tam dolu (simetrik) düzeni oluşur."},{"t":"Ortak ilke","a":"d⁵/d¹⁰ kararlılığı","d":"Bakırla aynı grupta olan gümüş de aynı nedenle, yani <b>tam dolu d¹⁰ küresel simetrisinin</b> sağladığı kararlılık için bu istisnayı gösterir."}],"ans":"Gümüş de bakır gibi bir s elektronunu d'ye aktararak 4d¹⁰5s¹ (tam dolu) düzenine geçer; bu da d¹⁰ küresel simetrisinin sağladığı kararlılıktan kaynaklanır, yani istisna aynı ilkeyle açıklanır."},
{"q":"Yarı dolu ve tam dolu alt kabuk kararlılığının yalnızca d için değil, neden genel bir ilke olduğunu (örneğin p³ ve f düzeyleri) açıklayın.","steps":[{"t":"Genel kural","a":"simetrik alt kabuk","d":"Küresel simetri ilkesi yalnızca d⁵/d¹⁰ için değil, yarı/tam dolu tüm alt kabuklar için geçerlidir (p³, p⁶, f⁷, f¹⁴)."},{"t":"Ortak neden","a":"değiş-tokuş ve simetri","d":"Yarı dolu (örn. azotun 2p³) ve tam dolu düzenler de paralel spin <b>değiş-tokuş enerjisi</b> ve simetri nedeniyle ekstra kararlıdır."}],"ans":"Küresel simetri kararlılığı genel bir ilkedir: p³, p⁶, d⁵, d¹⁰, f⁷, f¹⁴ gibi yarı/tam dolu tüm alt kabuklar, simetri ve paralel spin değiş-tokuş enerjisi nedeniyle ekstra kararlıdır."},
{"q":"Kromun [Ar]3d⁵4s¹ ve bakırın [Ar]3d¹⁰4s¹ dizilimlerini orbital kutu diyagramı üzerinde karşılaştırarak yarı dolu ile tam dolu küresel simetri arasındaki farkı açıklayın.","steps":[{"t":"Krom 3d⁵","a":"5 kutu, her birinde ↑","d":"Kromda 3d'nin beş orbitalinin her birinde tek (paralel spinli) elektron vardır; yarı dolu simetrik düzen oluşur."},{"t":"Bakır 3d¹⁰","a":"5 kutu, her birinde ↑↓","d":"Bakırda 3d'nin beş orbitalinin hepsi eşleşmiştir (↑↓); <b>tam dolu</b> simetrik düzen oluşur, eşleşmemiş elektron kalmaz."}],"ans":"Kromun 3d⁵'inde beş orbital tek tek dolu (↑, 5 eşleşmemiş, paramanyetik), bakırın 3d¹⁰'unda ise hepsi eşleşmiştir (↑↓, 0 eşleşmemiş, diyamanyetik); her ikisi de küresel simetriktir ama doluluk dereceleri farklıdır.","fig":"<svg viewBox='0 0 360 200'><text x='10' y='30' font-size='13' fill='#1a2b45'>Cr 3d⁵</text><rect x='20' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='56' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='92' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='128' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='164' y='40' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='37' y='62' font-size='16' text-anchor='middle' fill='#2b6be0'>↑</text><text x='73' y='62' font-size='16' text-anchor='middle' fill='#2b6be0'>↑</text><text x='109' y='62' font-size='16' text-anchor='middle' fill='#2b6be0'>↑</text><text x='145' y='62' font-size='16' text-anchor='middle' fill='#2b6be0'>↑</text><text x='181' y='62' font-size='16' text-anchor='middle' fill='#2b6be0'>↑</text><text x='10' y='115' font-size='13' fill='#1a2b45'>Cu 3d¹⁰</text><rect x='20' y='125' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='56' y='125' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='92' y='125' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='128' y='125' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><rect x='164' y='125' width='34' height='30' fill='none' stroke='#1a2b45' stroke-width='2'/><text x='30' y='147' font-size='14' fill='#2b6be0'>↑</text><text x='42' y='147' font-size='14' fill='#e0552b'>↓</text><text x='66' y='147' font-size='14' fill='#2b6be0'>↑</text><text x='78' y='147' font-size='14' fill='#e0552b'>↓</text><text x='102' y='147' font-size='14' fill='#2b6be0'>↑</text><text x='114' y='147' font-size='14' fill='#e0552b'>↓</text><text x='138' y='147' font-size='14' fill='#2b6be0'>↑</text><text x='150' y='147' font-size='14' fill='#e0552b'>↓</text><text x='174' y='147' font-size='14' fill='#2b6be0'>↑</text><text x='186' y='147' font-size='14' fill='#e0552b'>↓</text></svg>"}
]
}
}};
