globalThis.__OUT = {"kuantumSayilari":{"ilkokul":{"kolay":[
{"q":"Bir atomda elektronlar gelişigüzel değil, belli yerlerde dururlar. Her elektronun durduğu yeri bir <b>adres</b> gibi düşünebilir miyiz?","steps":[{"t":"Elektronun yeri","a":"belli bir bölge","d":"Elektronlar çekirdeğin çevresinde rastgele değil, kendilerine ait belli bölgelerde bulunur."},{"t":"Adres benzetmesi","a":"evet, adres gibi","d":"Her elektronun yerini, bir evin adresi gibi sayılarla tarif edebiliriz."}],"ans":"Evet; her elektronun durduğu yeri, tıpkı bir ev adresi gibi sayılarla tarif edebiliriz."},
{"q":"Bir apartmanda her ailenin kat ve daire numarası vardır. Atomda elektronların yerini de benzer sayılarla anlatan kurallara ne diyebiliriz?","steps":[{"t":"Apartman benzetmesi","a":"kat ve numara","d":"Apartmanda bir aileyi bulmak için kat ve daire numarası gerekir."},{"t":"Atomda karşılığı","a":"sayılarla adres","d":"Atomda da elektronun yerini anlatan sayılara <b>kuantum sayıları</b> denir."}],"ans":"Elektronun yerini kat-daire numarası gibi anlatan sayılara kuantum sayıları denir."},
{"q":"Çekirdeğe yakın katta duran bir elektron mu yoksa uzak katta duran bir elektron mu çekirdeğe daha yakındır?","steps":[{"t":"Katları düşün","a":"yakın kat","d":"Çekirdeğe yakın kat, çekirdeğe daha yakın bölgedir."},{"t":"Karşılaştır","a":"yakın kattaki","d":"Yakın katta duran elektron, uzak kattakine göre çekirdeğe daha yakındır."}],"ans":"Çekirdeğe yakın katta duran elektron, uzak kattakinden çekirdeğe daha yakındır."},
{"q":"İki elektronun adresinin tamamen aynı olması mümkün müdür?","steps":[{"t":"Adresi düşün","a":"herkese özel","d":"Bir apartmanda iki aile aynı daireye yazılamaz; her aileye ayrı adres verilir."},{"t":"Atomda kural","a":"aynı olamaz","d":"Atomda da iki elektronun adresi (tüm sayıları) tıpatıp aynı olamaz."}],"ans":"Hayır; her elektronun adresi kendine özeldir, iki elektronun adresi tamamen aynı olamaz."},
{"q":"Elektronlar küçük bir topaç gibi kendi etrafında döner diye düşünülür. Bu dönüş bir elektron için iki farklı yönde olabilir mi?","steps":[{"t":"Topaç benzetmesi","a":"iki dönüş yönü","d":"Bir topaç saat yönünde ya da tersine dönebilir; iki ayrı yön vardır."},{"t":"Elektron için","a":"evet iki yön","d":"Elektronun bu dönüş yönü iki farklı durumdan biri olabilir."}],"ans":"Evet; elektronun dönüşü iki farklı yönden (topaç gibi) biri olarak düşünülür."}
],"zor":[
{"q":"Bir apartmanda 1. kat çekirdeğe yakın, 3. kat uzaktır. Hangi kattaki dairelerde toplam daha çok aile (elektron) sığabilir?","steps":[{"t":"Üst katlar geniş","a":"uzak kat","d":"Çekirdekten uzak katlar daha geniştir, içinde daha çok daire vardır."},{"t":"Sonuç","a":"3. katta çok","d":"Uzak kat (3. kat) daha çok daire içerdiği için daha çok elektron sığar."}],"ans":"Çekirdekten uzak kat (3. kat) daha geniş olduğundan içinde daha çok elektron sığar."},
{"q":"Bir dairede en fazla 2 elektron oturabiliyorsa ve bu iki elektronun ayırt edilmesi gerekiyorsa, onları neyle ayırırız?","steps":[{"t":"Aynı daire","a":"iki elektron","d":"Bir dairede (orbitalde) en çok 2 elektron bulunur."},{"t":"Ayırt etme","a":"dönüş yönü","d":"Aynı dairedeki iki elektron, ters dönüş yönleriyle birbirinden ayrılır."}],"ans":"Aynı dairedeki iki elektron, biri bir yöne biri ters yöne dönerek birbirinden ayrılır."},
{"q":"Çekirdeğe yakın bir kattaki elektron mu yoksa uzak kattaki elektron mu daha çok enerjiye sahiptir?","steps":[{"t":"Uzaklık ve enerji","a":"uzak = yüksek","d":"Çekirdekten uzaklaşmak için daha çok enerji gerekir."},{"t":"Karşılaştır","a":"uzak kattaki","d":"Bu yüzden uzak kattaki elektronun enerjisi daha yüksektir."}],"ans":"Çekirdekten uzak kattaki elektron, yakın kattakine göre daha yüksek enerjiye sahiptir."},
{"q":"Bir apartmanın katlarını 1, 2, 3 diye numaralarız. Atomda elektronun bulunduğu katı belirten sayı en az kaç olabilir?","steps":[{"t":"İlk kat","a":"1. kat","d":"Çekirdeğe en yakın kat 1. kattır, daha düşüğü yoktur."},{"t":"En küçük değer","a":"1","d":"Kat numarası 0 olamaz; en küçük değeri 1'dir."}],"ans":"Elektronun bulunduğu kat (enerji düzeyi) en az 1 olabilir; sıfırıncı kat yoktur."},
{"q":"İki elektron aynı katta, aynı dairede ve aynı dönüş yönünde olabilir mi?","steps":[{"t":"Adresi karşılaştır","a":"tümü aynı olur","d":"Aynı kat, aynı daire ve aynı dönüş yönü olsaydı iki elektronun adresi tıpatıp aynı olurdu."},{"t":"Kural","a":"olamaz","d":"İki elektronun adresi tamamen aynı olamayacağı için en az dönüş yönleri farklı olmalıdır."}],"ans":"Hayır; aynı katta aynı dairede olsalar bile dönüş yönleri farklı olmak zorundadır, hepsi aynı olamaz."}
]},"ortaokul":{"kolay":[
{"q":"Bir elektronun atom içindeki yerini ve durumunu tarif eden sayılara ne ad verilir?","steps":[{"t":"Elektronun durumu","a":"sayılarla tarif","d":"Bir elektronun hangi enerji düzeyinde ve nasıl bir bölgede olduğu sayılarla belirtilir."},{"t":"Adlandır","a":"kuantum sayıları","d":"Bu sayıların tümüne <b>kuantum sayıları</b> denir."}],"ans":"Bir elektronun yerini ve durumunu tarif eden sayılara kuantum sayıları denir."},
{"q":"Baş kuantum sayısı (n) bir elektron hakkında bize en çok neyi söyler?","steps":[{"t":"n neyi gösterir","a":"enerji düzeyi","d":"Baş kuantum sayısı n, elektronun bulunduğu temel enerji düzeyini (kabuğu) gösterir."},{"t":"Uzaklıkla ilişki","a":"çekirdek uzaklığı","d":"n büyüdükçe elektron çekirdekten ortalama olarak daha uzakta ve daha yüksek enerjilidir."}],"ans":"Baş kuantum sayısı n, elektronun bulunduğu enerji düzeyini (kabuğu) ve çekirdeğe ortalama uzaklığını gösterir."},
{"q":"Bir orbital, elektron için neyi ifade eder?","steps":[{"t":"Orbital nedir","a":"bulunma bölgesi","d":"Orbital, elektronun büyük olasılıkla bulunduğu bölgedir."},{"t":"Ev benzetmesi","a":"şekilli ev","d":"Orbitali, elektronun belli bir şekli olan 'evi' gibi düşünebiliriz."}],"ans":"Orbital, bir elektronun büyük olasılıkla bulunduğu, belli şekli olan bölgedir; elektronun 'evi' gibidir."},
{"q":"Bir orbitalde en fazla kaç elektron bulunabilir?","steps":[{"t":"Orbital kapasitesi","a":"sınırlı","d":"Her orbital sınırlı sayıda elektron alabilir."},{"t":"Sayıyı söyle","a":"2 elektron","d":"Bir orbitalde en fazla 2 elektron bulunur; bunlar ters dönüş yönlüdür."}],"ans":"Bir orbitalde en fazla 2 elektron bulunabilir ve bu iki elektronun dönüş yönü zıttır."},
{"q":"Spin kuantum sayısı (mₛ) bir elektronun hangi özelliğiyle ilgilidir?","steps":[{"t":"Spin nedir","a":"dönüş yönü","d":"Spin, elektronun kendi etrafındaki dönüş yönü gibi düşünülen özelliğidir."},{"t":"İki değer","a":"+½ ve −½","d":"Spin kuantum sayısı yalnızca iki değer alır: +½ veya −½."}],"ans":"Spin kuantum sayısı mₛ, elektronun dönüş yönüyle ilgilidir ve yalnızca +½ ya da −½ değerini alır."}
],"zor":[
{"q":"Baş kuantum sayısı n = 1 olan kabukta en fazla 2, n = 2 olan kabukta en fazla 8 elektron bulunur. Bu sayılar arasında nasıl bir ilişki vardır?","steps":[{"t":"Değerleri yaz","a":"2 ve 8","d":"1. kabukta 2, 2. kabukta 8 elektron bulunur."},{"t":"Kuralı bul","a":"2n²","d":"Bu sayılar 2·1² = 2 ve 2·2² = 8 olarak çıkar; kapasite 2n² ile bulunur."}],"ans":"Bir kabuğun en fazla elektron sayısı 2n² kuralıyla bulunur: n=1 için 2, n=2 için 8 elektrondur."},
{"q":"İki elektron aynı orbitalde bulunuyorsa spin kuantum sayıları (mₛ) nasıl olmalıdır?","steps":[{"t":"Aynı orbital","a":"diğerleri aynı","d":"Aynı orbitaldeki iki elektronun ilk üç kuantum sayısı (n, ℓ, mₗ) aynıdır."},{"t":"Ayrım gereği","a":"zıt spin","d":"İkisinin adresi tıpatıp aynı olamayacağı için spinleri zıt olmalıdır: biri +½, biri −½."}],"ans":"Aynı orbitaldeki iki elektronun spinleri zıttır; biri +½ ise diğeri −½ olmak zorundadır."},
{"q":"Hangi kural, bir atomdaki iki elektronun dört kuantum sayısının tamamının aynı olamayacağını söyler?","steps":[{"t":"Benzersizlik fikri","a":"her elektron özel","d":"Her elektronun dört kuantum sayısından oluşan adresi kendine özeldir."},{"t":"İlkeyi adlandır","a":"Pauli ilkesi","d":"Bu kurala <b>Pauli dışarlama ilkesi</b> denir."}],"ans":"Bu kurala Pauli dışarlama ilkesi denir; iki elektronun dört kuantum sayısı aynı anda aynı olamaz."},
{"q":"3. kabukta (n = 3) en fazla kaç elektron bulunabilir?","steps":[{"t":"Kuralı yaz","a":"2n²","d":"Bir kabuğun kapasitesi 2n² ile bulunur."},{"t":"Yerine koy","a":"2·3²","d":"n = 3 için: 2 × 9 = 18."}],"ans":"3. kabukta en fazla 2n² = 2·3² = 18 elektron bulunabilir."},
{"q":"Bir elektronu tam olarak tanımlamak için kaç tane kuantum sayısı gerekir ve bunlar nelerdir?","steps":[{"t":"Sayıyı bul","a":"4 tane","d":"Bir elektronun durumunu tam tanımlamak için dört kuantum sayısı gerekir."},{"t":"İsimlerini say","a":"n, ℓ, mₗ, mₛ","d":"Bunlar baş (n), açısal (ℓ), manyetik (mₗ) ve spin (mₛ) kuantum sayılarıdır."}],"ans":"Bir elektron dört kuantum sayısıyla tanımlanır: baş (n), açısal (ℓ), manyetik (mₗ) ve spin (mₛ)."}
]},"lise":{"kolay":[
{"q":"Dört kuantum sayısı (n, ℓ, mₗ, mₛ) sırasıyla hangi özellikleri belirler?","steps":[{"t":"n ve ℓ","a":"düzey ve alt kabuk","d":"Baş kuantum sayısı n enerji düzeyini, açısal kuantum sayısı ℓ alt kabuğun türünü (s, p, d, f) belirler."},{"t":"mₗ ve mₛ","a":"yönelim ve spin","d":"Manyetik kuantum sayısı mₗ orbitalin uzaydaki yönelimini, spin kuantum sayısı mₛ elektronun dönüş yönünü belirler."}],"ans":"n enerji düzeyini, ℓ alt kabuğu (orbital türünü), mₗ orbitalin yönelimini, mₛ ise elektronun spinini belirler."},
{"q":"Açısal kuantum sayısı ℓ'nin alabileceği değerler baş kuantum sayısı n'ye nasıl bağlıdır?","steps":[{"t":"Bağıntıyı yaz","a":"ℓ = 0 ... n−1","d":"ℓ, 0'dan başlayıp n−1'e kadar tam sayı değerler alır."},{"t":"Örnek ver","a":"n=3 → ℓ=0,1,2","d":"n = 3 için ℓ değerleri 0, 1 ve 2 olur; yani s, p ve d alt kabukları bulunur."}],"ans":"Açısal kuantum sayısı ℓ, 0'dan n−1'e kadar değer alır; örneğin n=3 için ℓ = 0, 1, 2'dir (s, p, d)."},
{"q":"Açısal kuantum sayısı ℓ = 0, 1, 2, 3 değerleri hangi alt kabuklara (orbital türlerine) karşılık gelir?","steps":[{"t":"Eşleştir","a":"s, p, d, f","d":"ℓ = 0 → s, ℓ = 1 → p, ℓ = 2 → d, ℓ = 3 → f alt kabuğuna karşılık gelir."},{"t":"Sıralama","a":"artan ℓ","d":"ℓ büyüdükçe alt kabuk türü s, p, d, f sırasıyla değişir."}],"ans":"ℓ = 0 s, ℓ = 1 p, ℓ = 2 d, ℓ = 3 f alt kabuğuna karşılık gelir."},
{"q":"Manyetik kuantum sayısı mₗ'nin alabileceği değerler hangi aralıktadır?","steps":[{"t":"Aralığı yaz","a":"−ℓ ... +ℓ","d":"mₗ, −ℓ'den +ℓ'ye kadar tam sayı değerler alır (0 dahil)."},{"t":"Örnek","a":"ℓ=1 → −1,0,+1","d":"ℓ = 1 (p) için mₗ = −1, 0, +1 olur; yani 3 yönelim vardır."}],"ans":"Manyetik kuantum sayısı mₗ, −ℓ'den +ℓ'ye kadar (0 dahil) tam sayı değerler alır."},
{"q":"Spin kuantum sayısı mₛ kaç farklı değer alabilir ve bunlar nelerdir?","steps":[{"t":"Değer sayısı","a":"2 değer","d":"Spin kuantum sayısı yalnızca iki farklı değer alabilir."},{"t":"Değerleri yaz","a":"+½ ve −½","d":"Bu değerler +½ ve −½'dir; bir orbitaldeki iki elektronun spinleri bu ikisinden biridir."}],"ans":"Spin kuantum sayısı mₛ iki değer alır: +½ ve −½."},
{"q":"Bir alt kabuktaki orbital sayısı, açısal kuantum sayısı ℓ'ye nasıl bağlıdır?","fig":"<svg viewBox='0 0 320 110'><rect x='20' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='34' y='90' font-size='11' text-anchor='middle' fill='#1a2b45'>s</text><text x='34' y='30' font-size='10' text-anchor='middle' fill='#1a2b45'>1</text><rect x='90' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='120' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='150' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='134' y='90' font-size='11' text-anchor='middle' fill='#1a2b45'>p</text><text x='134' y='30' font-size='10' text-anchor='middle' fill='#1a2b45'>3</text><rect x='210' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='240' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='270' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='254' y='90' font-size='11' text-anchor='middle' fill='#1a2b45'>d</text><text x='254' y='30' font-size='10' text-anchor='middle' fill='#1a2b45'>5</text></svg>","steps":[{"t":"Bağıntıyı yaz","a":"2ℓ + 1","d":"Bir alt kabuktaki orbital sayısı 2ℓ + 1 ile bulunur (mₗ'nin değer sayısı kadar)."},{"t":"Örnekle","a":"s=1, p=3, d=5","d":"ℓ=0 için 1 (s), ℓ=1 için 3 (p), ℓ=2 için 5 (d) orbital olur."}],"ans":"Bir alt kabuktaki orbital sayısı 2ℓ + 1'dir: s'de 1, p'de 3, d'de 5 orbital bulunur."},
{"q":"Baş kuantum sayısı n olan bir kabuğun alabileceği en fazla elektron sayısı hangi bağıntıyla bulunur?","steps":[{"t":"Kabuk kapasitesi","a":"2n²","d":"Bir kabuktaki orbital sayısı n² olduğundan, her orbitale 2 elektron sığarak kapasite 2n² olur."},{"t":"Örnekle","a":"n=2 → 8","d":"n = 2 için 2·2² = 8 elektron; n = 3 için 2·3² = 18 elektron."}],"ans":"Bir kabuğun en fazla elektron kapasitesi 2n²'dir; n=2 için 8, n=3 için 18 elektrondur."},
{"q":"n = 2 enerji düzeyinde hangi alt kabuklar bulunur ve bunlar kaç orbital içerir?","steps":[{"t":"ℓ değerleri","a":"0 ve 1","d":"n = 2 için ℓ = 0 (s) ve ℓ = 1 (p) alt kabukları bulunur."},{"t":"Orbital sayıları","a":"1 + 3 = 4","d":"2s'de 1, 2p'de 3 orbital vardır; toplam 4 orbital, 8 elektron kapasitesi."}],"ans":"n = 2'de 2s (1 orbital) ve 2p (3 orbital) alt kabukları bulunur; toplam 4 orbital, 8 elektron alır."},
{"q":"n = 3, ℓ = 2 değerleri hangi alt kabuğu gösterir ve bu alt kabukta kaç orbital vardır?","steps":[{"t":"Alt kabuğu belirle","a":"3d","d":"n = 3 ve ℓ = 2 olduğundan bu 3d alt kabuğudur."},{"t":"Orbital sayısı","a":"2ℓ+1 = 5","d":"ℓ = 2 için 2·2+1 = 5 orbital bulunur."}],"ans":"n = 3, ℓ = 2 değerleri 3d alt kabuğunu gösterir ve bu alt kabukta 5 orbital vardır."},
{"q":"Bir elektronun kuantum sayıları n = 4, ℓ = 0 ise hangi orbitaldedir ve mₗ değeri ne olabilir?","steps":[{"t":"Orbitali belirle","a":"4s","d":"n = 4, ℓ = 0 olduğundan elektron 4s orbitalindedir."},{"t":"mₗ değeri","a":"yalnızca 0","d":"ℓ = 0 için mₗ değeri −0 ile +0 arası, yani sadece 0 olur (tek orbital)."}],"ans":"Elektron 4s orbitalindedir; ℓ = 0 olduğu için mₗ yalnızca 0 değerini alır."},
{"q":"Aşağıdaki kuantum sayısı dörtlüsü neden olanaksızdır: n = 2, ℓ = 2, mₗ = 0, mₛ = +½?","steps":[{"t":"ℓ kuralını uygula","a":"ℓ ≤ n−1","d":"n = 2 için ℓ en fazla n−1 = 1 olabilir; ℓ = 0 veya 1 olmalıdır."},{"t":"Çelişkiyi bul","a":"ℓ=2 yasak","d":"ℓ = 2 değeri n = 2 için izin verilen aralığın dışındadır."}],"ans":"Olanaksızdır; çünkü n = 2 için ℓ en çok 1 olabilir, ℓ = 2 değeri izin verilen aralığın dışındadır."},
{"q":"ℓ = 1 (p alt kabuğu) için manyetik kuantum sayısı mₗ kaç farklı değer alır ve bu ne anlama gelir?","fig":"<svg viewBox='0 0 320 120'><line x1='160' y1='10' x2='160' y2='110' stroke='#1a2b45' stroke-width='1'/><line x1='40' y1='60' x2='280' y2='60' stroke='#1a2b45' stroke-width='1'/><ellipse cx='160' cy='40' rx='14' ry='28' fill='none' stroke='#2b6be0' stroke-width='1.5'/><ellipse cx='160' cy='80' rx='14' ry='28' fill='none' stroke='#2b6be0' stroke-width='1.5'/><text x='185' y='35' font-size='10' fill='#1a2b45'>pz</text><ellipse cx='130' cy='60' rx='28' ry='14' fill='none' stroke='#e0552b' stroke-width='1.5'/><ellipse cx='190' cy='60' rx='28' ry='14' fill='none' stroke='#e0552b' stroke-width='1.5'/><text x='235' y='58' font-size='10' fill='#1a2b45'>px</text></svg>","steps":[{"t":"Değer sayısı","a":"2ℓ+1 = 3","d":"ℓ = 1 için mₗ = −1, 0, +1 olmak üzere 3 değer alır."},{"t":"Anlamı","a":"3 yönelim","d":"Bu üç değer, p orbitalinin uzayda px, py, pz olarak 3 farklı yönelimine karşılık gelir."}],"ans":"ℓ = 1 için mₗ = −1, 0, +1'dir (3 değer); bu, p orbitalinin uzayda 3 farklı yönelimini (px, py, pz) gösterir."},
{"q":"Bir kabukta bulunan toplam orbital sayısı baş kuantum sayısı n'ye nasıl bağlıdır?","steps":[{"t":"Alt kabukları topla","a":"1+3+5+...","d":"n'inci kabukta ℓ = 0'dan n−1'e kadar alt kabuklar vardır; orbital sayıları 1, 3, 5, ... biçiminde toplanır."},{"t":"Toplamı bul","a":"n²","d":"Bu ardışık tek sayıların toplamı n²'ye eşittir; örneğin n=3 için 1+3+5 = 9 = 3²."}],"ans":"Bir kabuktaki toplam orbital sayısı n²'dir; örneğin n = 3 için 9 orbital bulunur."},
{"q":"Spin kuantum sayısının iki değerli olması (±½), bir orbitalin neden en fazla 2 elektron alabildiğini nasıl açıklar?","steps":[{"t":"İlk üç sayı sabit","a":"n, ℓ, mₗ aynı","d":"Aynı orbitaldeki elektronlar için n, ℓ ve mₗ aynıdır."},{"t":"Pauli ile sınır","a":"yalnızca spin değişir","d":"Pauli ilkesine göre elektronlar yalnızca spinle (±½) ayrılabildiğinden, en çok 2 elektron sığar."}],"ans":"Aynı orbitalde n, ℓ, mₗ aynı olduğundan elektronlar yalnızca spinle (+½ ve −½) ayrılabilir; bu nedenle bir orbital en fazla 2 elektron alır."},
{"q":"Bir elektronun açısal kuantum sayısı ℓ = 2 ise, manyetik kuantum sayısı mₗ kaç farklı değer alabilir ve bu hangi alt kabuğa karşılık gelir?","steps":[{"t":"Alt kabuğu belirle","a":"d alt kabuğu","d":"ℓ = 2 değeri d alt kabuğuna karşılık gelir."},{"t":"mₗ değerleri","a":"−2 ... +2","d":"mₗ, −ℓ'den +ℓ'ye kadar değer alır: −2, −1, 0, +1, +2 olmak üzere 5 değer (2ℓ+1 = 5)."}],"ans":"ℓ = 2 (d alt kabuğu) için mₗ = −2, −1, 0, +1, +2'dir; yani 5 farklı değer (2ℓ+1 = 5) alır."}
],"zor":[
{"q":"n = 3 enerji düzeyinde bulunan alt kabukları, her birinin orbital sayısını ve düzeyin toplam elektron kapasitesini bulunuz.","steps":[{"t":"Alt kabukları yaz","a":"3s, 3p, 3d","d":"n = 3 için ℓ = 0, 1, 2 olur; yani 3s, 3p ve 3d alt kabukları bulunur."},{"t":"Orbital sayıları","a":"1, 3, 5","d":"2ℓ+1'den 3s'de 1, 3p'de 3, 3d'de 5 orbital; toplam 9 orbital."},{"t":"Kapasite","a":"2·9 = 18","d":"Her orbital 2 elektron aldığından toplam 18 elektron; bu 2n² = 2·3² = 18 ile uyumludur."}],"ans":"n = 3'te 3s (1), 3p (3) ve 3d (5) toplam 9 orbital bulunur; kapasite 2·9 = 18 = 2n² elektrondur."},
{"q":"Bir elektronun kuantum sayıları n = 4, ℓ = 2, mₗ = +1 olarak verilmiştir. Bu elektron hangi alt kabuktadır ve mₛ'nin olası değerleri nelerdir?","steps":[{"t":"Alt kabuğu belirle","a":"4d","d":"n = 4 ve ℓ = 2 olduğundan elektron 4d alt kabuğundadır."},{"t":"mₗ kontrolü","a":"geçerli","d":"ℓ = 2 için mₗ = −2,−1,0,+1,+2 aralığındadır; +1 bu aralıktadır, geçerlidir."},{"t":"mₛ değerleri","a":"+½ veya −½","d":"Spin her zaman iki değerden birini alır: +½ ya da −½."}],"ans":"Elektron 4d alt kabuğundadır; mₗ = +1 geçerlidir ve mₛ değeri +½ veya −½ olabilir."},
{"q":"n = 4 olan bir kabukta toplam kaç orbital ve en fazla kaç elektron bulunur? Alt kabukları da gösteriniz.","steps":[{"t":"Alt kabuklar","a":"4s,4p,4d,4f","d":"n = 4 için ℓ = 0,1,2,3; yani 4s, 4p, 4d, 4f alt kabukları vardır."},{"t":"Orbital sayısı","a":"1+3+5+7 = 16","d":"Orbital sayıları 1, 3, 5, 7 toplanır: 16 orbital (n² = 4² = 16)."},{"t":"Elektron sayısı","a":"2·16 = 32","d":"Her orbital 2 elektron aldığından kapasite 2n² = 2·16 = 32 elektrondur."}],"ans":"n = 4'te 4s, 4p, 4d, 4f alt kabukları toplam 16 orbital içerir; en fazla 2·16 = 32 elektron bulunur."},
{"q":"Aşağıdaki dört kuantum sayısı dörtlüsünden hangileri olanaksızdır, gerekçesiyle belirtiniz: (a) n=2, ℓ=1, mₗ=−1, mₛ=+½  (b) n=3, ℓ=3, mₗ=0, mₛ=−½  (c) n=1, ℓ=0, mₗ=0, mₛ=−½","steps":[{"t":"(a)'yı denetle","a":"geçerli","d":"n=2 için ℓ=1 izinli (ℓ≤n−1), mₗ=−1 (−1..+1) aralığında, mₛ=+½ geçerli."},{"t":"(b)'yi denetle","a":"olanaksız","d":"n=3 için ℓ en çok 2 olabilir; ℓ=3 izinli değildir, bu dörtlü olanaksızdır."},{"t":"(c)'yi denetle","a":"geçerli","d":"n=1 için ℓ=0, mₗ=0, mₛ=−½: tüm değerler kurallara uygundur."}],"ans":"Yalnızca (b) olanaksızdır; çünkü n = 3 için ℓ en fazla 2 olabilir, ℓ = 3 izin verilen aralık dışındadır. (a) ve (c) geçerlidir."},
{"q":"ℓ = 2 (d alt kabuğu) için manyetik kuantum sayısı mₗ'nin tüm değerlerini ve bu alt kabuğun en fazla elektron sayısını bulunuz.","fig":"<svg viewBox='0 0 320 90'><rect x='30' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='45' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>−2</text><rect x='80' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='95' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>−1</text><rect x='130' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='145' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>0</text><rect x='180' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='195' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>+1</text><rect x='230' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='245' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>+2</text></svg>","steps":[{"t":"mₗ değerleri","a":"−2..+2","d":"ℓ = 2 için mₗ = −2, −1, 0, +1, +2 olmak üzere 5 değer alır."},{"t":"Orbital sayısı","a":"5 orbital","d":"2ℓ+1 = 5 orbital vardır."},{"t":"Elektron sayısı","a":"2·5 = 10","d":"Her orbital 2 elektron aldığından d alt kabuğu en fazla 10 elektron alır."}],"ans":"ℓ = 2 için mₗ = −2, −1, 0, +1, +2'dir (5 orbital); d alt kabuğu en fazla 2·5 = 10 elektron alır."},
{"q":"3p alt kabuğunda bulunabilecek bir elektronun dört kuantum sayısından oluşan bir geçerli örneği yazınız ve bu alt kabuğun toplam elektron kapasitesini belirtiniz.","steps":[{"t":"n ve ℓ","a":"n=3, ℓ=1","d":"3p alt kabuğu için n = 3 ve ℓ = 1'dir."},{"t":"mₗ ve mₛ seç","a":"mₗ=0, mₛ=+½","d":"mₗ = −1, 0, +1 arasından örneğin 0, mₛ olarak +½ seçilebilir."},{"t":"Kapasite","a":"6 elektron","d":"3 orbital × 2 elektron = 6 elektron kapasitesi vardır (p⁶)."}],"ans":"Geçerli bir örnek: n = 3, ℓ = 1, mₗ = 0, mₛ = +½'dir; 3p alt kabuğu toplam 6 elektron alır."},
{"q":"Bir atomda n + ℓ değeri (enerji sıralaması yaklaşımı) 4s ile 3d orbitalleri için karşılaştırınız ve hangisinin daha düşük enerjili sayıldığını belirtiniz.","steps":[{"t":"4s için n+ℓ","a":"4+0 = 4","d":"4s orbitalinde n = 4, ℓ = 0 olduğundan n + ℓ = 4'tür."},{"t":"3d için n+ℓ","a":"3+2 = 5","d":"3d orbitalinde n = 3, ℓ = 2 olduğundan n + ℓ = 5'tir."},{"t":"Karşılaştır","a":"4s daha düşük","d":"n + ℓ küçük olan daha düşük enerjilidir; 4 < 5 olduğundan 4s, 3d'den önce dolar."}],"ans":"4s için n+ℓ = 4, 3d için n+ℓ = 5'tir; küçük olan daha düşük enerjili sayıldığından 4s, 3d'den önce dolar."},
{"q":"n = 5 olan kabukta kaç alt kabuk, kaç orbital ve en fazla kaç elektron bulunur?","steps":[{"t":"Alt kabuk sayısı","a":"5 tane","d":"n = 5 için ℓ = 0,1,2,3,4 olur; yani 5 alt kabuk (5s, 5p, 5d, 5f, 5g)."},{"t":"Orbital sayısı","a":"n² = 25","d":"Orbital sayısı 1+3+5+7+9 = 25 = n²'dir."},{"t":"Elektron sayısı","a":"2·25 = 50","d":"Kapasite 2n² = 2·25 = 50 elektrondur."}],"ans":"n = 5'te 5 alt kabuk, n² = 25 orbital ve en fazla 2n² = 50 elektron bulunur."},
{"q":"Bir orbitaldeki iki elektron için n = 2, ℓ = 1, mₗ = 0 ortaktır. Pauli dışarlama ilkesine göre bu iki elektronu yalnızca hangi kuantum sayısı ayırır ve değerleri ne olur?","fig":"<svg viewBox='0 0 320 90'><rect x='130' y='30' width='60' height='32' fill='none' stroke='#1a2b45' stroke-width='1.5'/><line x1='150' y1='38' x2='150' y2='56' stroke='#2b6be0' stroke-width='2'/><polygon points='150,38 146,45 154,45' fill='#2b6be0'/><line x1='170' y1='56' x2='170' y2='38' stroke='#e0552b' stroke-width='2'/><polygon points='170,56 166,49 174,49' fill='#e0552b'/><text x='160' y='80' font-size='10' text-anchor='middle' fill='#1a2b45'>↑↓ (zıt spin)</text></svg>","steps":[{"t":"Ortak değerler","a":"n,ℓ,mₗ aynı","d":"İki elektronun n = 2, ℓ = 1, mₗ = 0 değerleri ortaktır; ilk üç sayı aynıdır."},{"t":"Pauli gereği","a":"spin farklı","d":"Dört sayının tümü aynı olamayacağından, ayırt eden tek sayı spin mₛ'dir."},{"t":"Değerleri yaz","a":"+½ ve −½","d":"Biri +½, diğeri −½ spinlidir (↑↓)."}],"ans":"İki elektronu yalnızca spin kuantum sayısı mₛ ayırır; biri +½, diğeri −½ değerini alır."},
{"q":"Argon atomunun (Z = 18) son elektronu 3p orbitaline yerleşir. Bu son elektron için olası bir dört kuantum sayısı takımı yazınız ve neden ℓ'nin 1 olduğunu açıklayınız.","steps":[{"t":"Dizilimi düşün","a":"...3p⁶","d":"Ar dizilimi 1s² 2s² 2p⁶ 3s² 3p⁶'dır; son elektron 3p alt kabuğundadır."},{"t":"n ve ℓ","a":"n=3, ℓ=1","d":"3p için n = 3, p alt kabuğu olduğundan ℓ = 1'dir."},{"t":"mₗ, mₛ seç","a":"mₗ=+1, mₛ=−½","d":"mₗ = −1, 0, +1 arasından örneğin +1, mₛ = −½ alınabilir."}],"ans":"Son elektron 3p'de olduğundan ℓ = 1'dir (p alt kabuğu); olası takım n = 3, ℓ = 1, mₗ = +1, mₛ = −½'dir."},
{"q":"n = 3 düzeyinde mₗ = 0 değerini alabilen kaç farklı orbital vardır? Hangi alt kabuklarda bulunurlar?","steps":[{"t":"Alt kabukları yaz","a":"3s, 3p, 3d","d":"n = 3 için ℓ = 0, 1, 2 alt kabukları vardır."},{"t":"mₗ=0 var mı","a":"hepsinde var","d":"mₗ aralığı −ℓ..+ℓ olduğundan 0 değeri her alt kabukta bulunur (s, p, d)."},{"t":"Say","a":"3 orbital","d":"3s, 3p ve 3d'de birer tane mₗ = 0 orbitali olmak üzere toplam 3 orbital vardır."}],"ans":"n = 3'te mₗ = 0 değerini 3s, 3p ve 3d alt kabuklarındaki birer orbital alır; toplam 3 orbital bulunur."},
{"q":"Bir elektronun n = 2, ℓ = 1 olduğu biliniyor. Bu elektronun kalan iki kuantum sayısı (mₗ ve mₛ) için kaç farklı geçerli kombinasyon (kombinasyon = orbital × spin) vardır?","steps":[{"t":"mₗ seçenekleri","a":"−1, 0, +1","d":"ℓ = 1 için mₗ üç değer alır; yani 3 orbital seçeneği vardır."},{"t":"mₛ seçenekleri","a":"+½, −½","d":"Her orbital için spin 2 değerden biri olabilir."},{"t":"Çarp","a":"3 × 2 = 6","d":"Toplam geçerli kombinasyon 3 × 2 = 6'dır; bu, 2p alt kabuğunun 6 elektron kapasitesidir."}],"ans":"mₗ için 3, mₛ için 2 seçenek olduğundan 3 × 2 = 6 geçerli kombinasyon vardır (2p alt kabuğunun 6 elektron kapasitesi)."},
{"q":"Bir kuantum sayısı takımında n = 3, ℓ = 0 verilmiştir. mₗ'nin alabileceği değer(ler) ile bu alt kabuğun orbital sayısını ve elektron kapasitesini bulunuz.","steps":[{"t":"mₗ değeri","a":"yalnızca 0","d":"ℓ = 0 için mₗ aralığı −0..+0, yani sadece 0'dır."},{"t":"Orbital sayısı","a":"2ℓ+1 = 1","d":"3s alt kabuğunda yalnızca 1 orbital bulunur."},{"t":"Kapasite","a":"2 elektron","d":"Tek orbital 2 elektron aldığından 3s en fazla 2 elektron (s²) alır."}],"ans":"n = 3, ℓ = 0 (3s) için mₗ yalnızca 0'dır; alt kabukta 1 orbital ve en fazla 2 elektron (s²) bulunur."},
{"q":"Hund kuralı, bir alt kabuktaki orbitallere elektronların önce nasıl yerleştiğini söyler. 2p³ diziliminde elektronların spin durumunu açıklayınız.","fig":"<svg viewBox='0 0 320 90'><rect x='70' y='30' width='34' height='32' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='110' y='30' width='34' height='32' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='150' y='30' width='34' height='32' fill='none' stroke='#1a2b45' stroke-width='1.5'/><line x1='87' y1='58' x2='87' y2='36' stroke='#2b6be0' stroke-width='2'/><polygon points='87,36 83,43 91,43' fill='#2b6be0'/><line x1='127' y1='58' x2='127' y2='36' stroke='#2b6be0' stroke-width='2'/><polygon points='127,36 123,43 131,43' fill='#2b6be0'/><line x1='167' y1='58' x2='167' y2='36' stroke='#2b6be0' stroke-width='2'/><polygon points='167,36 163,43 171,43' fill='#2b6be0'/><text x='160' y='82' font-size='10' text-anchor='middle' fill='#1a2b45'>↑ ↑ ↑ (paralel)</text></svg>","steps":[{"t":"Hund kuralı","a":"önce tek tek","d":"Eş enerjili 3 p orbitaline elektronlar önce birer birer, paralel spinli yerleşir."},{"t":"2p³ durumu","a":"3 yarı dolu","d":"Üç elektron, üç p orbitaline birer tane ve aynı spinle (örneğin hepsi +½) dağılır."}],"ans":"Hund kuralına göre 2p³'te elektronlar üç p orbitaline birer birer ve paralel spinle (↑ ↑ ↑) yerleşir; eşleşme henüz olmaz."},
{"q":"Bir atomda 4f alt kabuğu (ℓ = 3) tam dolduğunda kaç elektron içerir? Orbital sayısını da gösteriniz.","steps":[{"t":"Orbital sayısı","a":"2ℓ+1 = 7","d":"ℓ = 3 için mₗ = −3,−2,−1,0,+1,+2,+3 olmak üzere 7 orbital vardır."},{"t":"Elektron sayısı","a":"2·7 = 14","d":"Her orbital 2 elektron aldığından 4f tam dolduğunda 14 elektron (f¹⁴) içerir."}],"ans":"4f alt kabuğu 7 orbital içerir ve tam dolduğunda 2·7 = 14 elektron (f¹⁴) bulunur."}
]}}};
