globalThis.__OUT = {"kuantumSayilari":{"ilkokul":{"kolay":[
{"q":"Bir okul binasında her öğrencinin sınıfı, sırası ve yeri bellidir. Atomda elektronların yerini de buna benzer sayılarla anlatabilir miyiz?","steps":[{"t":"Okul benzetmesi","a":"belli bir yer","d":"Okulda her öğrencinin kat, sınıf ve sıra numarası gibi belli bir yeri vardır."},{"t":"Atomda karşılığı","a":"sayılarla adres","d":"Atomda da elektronun yerini anlatan sayılar vardır; bunlara <b>kuantum sayıları</b> denir."}],"ans":"Evet; tıpkı bir öğrencinin okuldaki yerini sayılarla anlatmak gibi, elektronun yerini de kuantum sayılarıyla anlatırız."},
{"q":"Çekirdeğe yakın bir basamakta duran elektron mu, yoksa uzak basamakta duran elektron mu çekirdeğe daha yakındır?","steps":[{"t":"Basamakları düşün","a":"yakın basamak","d":"Çekirdeğe yakın basamak, çekirdeğe daha yakın bölgedir."},{"t":"Karşılaştır","a":"yakındaki","d":"Yakın basamaktaki elektron, uzaktakinden çekirdeğe daha yakındır."}],"ans":"Çekirdeğe yakın basamaktaki elektron, uzak basamaktakinden çekirdeğe daha yakındır."},
{"q":"İki elektronun yerinin ve durumunun tıpatıp aynı olması mümkün müdür?","steps":[{"t":"Adresi düşün","a":"herkese özel","d":"Bir sınıfta iki öğrenci aynı sıraya aynı anda oturamaz; herkesin yeri ayrıdır."},{"t":"Atomda kural","a":"aynı olamaz","d":"Atomda da iki elektronun tüm sayıları tıpatıp aynı olamaz."}],"ans":"Hayır; her elektronun durumu kendine özeldir, iki elektron tamamen aynı olamaz."},
{"q":"Elektronlar küçük bir topaç gibi kendi etrafında döner diye düşünülür. Bu dönüş kaç farklı yönde olabilir?","steps":[{"t":"Topaç benzetmesi","a":"iki yön","d":"Bir topaç saat yönünde ya da tersine dönebilir; iki ayrı yön vardır."},{"t":"Elektron için","a":"iki dönüş","d":"Elektronun bu dönüşü de iki ayrı durumdan biri olabilir."}],"ans":"İki farklı yönde; elektronun dönüşü tıpkı bir topaç gibi iki durumdan biri olur."},
{"q":"Bir apartmanda kat numarası bir aileyi bulmaya yarar. Atomda elektronun hangi katta (enerji basamağında) olduğunu söyleyen sayı en az kaç olur?","steps":[{"t":"İlk kat","a":"1. kat","d":"Çekirdeğe en yakın basamak 1. basamaktır, daha küçüğü yoktur."},{"t":"En küçük değer","a":"1","d":"Bu sayı 0 olamaz; en küçük değeri 1'dir."}],"ans":"Elektronun bulunduğu kat (enerji basamağı) en az 1 olur; sıfırıncı kat yoktur."}
],"zor":[
{"q":"Çekirdekten uzak basamak mı, yakın basamak mı daha geniştir ve daha çok elektron alır?","steps":[{"t":"Uzak basamak geniş","a":"uzak basamak","d":"Çekirdekten uzak basamaklar daha geniştir, daha çok yer içerir."},{"t":"Sonuç","a":"uzak çok alır","d":"Geniş olduğu için uzak basamak daha çok elektron alabilir."}],"ans":"Çekirdekten uzak basamak daha geniş olduğundan daha çok elektron alır."},
{"q":"Bir orbital (elektronun evi) en fazla 2 elektron alıyorsa, bu iki elektronu birbirinden neyle ayırırız?","steps":[{"t":"Aynı ev","a":"iki elektron","d":"Bir orbitalde (elektronun evinde) en çok 2 elektron bulunur."},{"t":"Ayırt etme","a":"dönüş yönü","d":"Aynı evdeki iki elektron, ters dönüş yönleriyle birbirinden ayrılır."}],"ans":"Aynı orbitaldeki iki elektronu, biri bir yöne biri ters yöne döndüğü için ayırırız."},
{"q":"Çekirdeğe yakın basamaktaki elektron mu, uzak basamaktaki elektron mu daha çok enerjiye sahiptir?","steps":[{"t":"Uzaklık ve enerji","a":"uzak = yüksek","d":"Çekirdekten uzaklaşmak daha çok enerji gerektirir."},{"t":"Karşılaştır","a":"uzaktaki","d":"Bu yüzden uzak basamaktaki elektronun enerjisi daha yüksektir."}],"ans":"Çekirdekten uzak basamaktaki elektron, yakındakine göre daha yüksek enerjilidir."},
{"q":"İki elektron aynı basamakta, aynı evde (orbitalde) ve aynı dönüş yönünde olabilir mi?","steps":[{"t":"Durumu karşılaştır","a":"tümü aynı olur","d":"Aynı basamak, aynı orbital ve aynı dönüş yönü olsaydı iki elektron tıpatıp aynı olurdu."},{"t":"Kural","a":"olamaz","d":"İki elektron tamamen aynı olamayacağı için en az dönüş yönleri farklı olmalıdır."}],"ans":"Hayır; aynı orbitalde bile dönüş yönleri farklı olmak zorundadır, hepsi aynı olamaz."},
{"q":"Bir atomdaki elektronu tarif etmek için bir tek sayı mı yeterlidir, yoksa birkaç sayı mı gerekir?","steps":[{"t":"Tek sayı yetmez","a":"birden çok","d":"Sadece bir sayı, elektronun hangi evde olduğunu ve nasıl döndüğünü anlatmaya yetmez."},{"t":"Birkaç sayı","a":"adres takımı","d":"Elektronu tam tarif etmek için birkaç sayıdan oluşan bir takım gerekir."}],"ans":"Birkaç sayı gerekir; elektronun yerini ve durumunu ancak bir sayı takımı tam tarif eder."}
]},"ortaokul":{"kolay":[
{"q":"Bir elektronun atom içindeki yerini ve durumunu tarif eden sayılara ne ad verilir?","steps":[{"t":"Elektronun durumu","a":"sayılarla tarif","d":"Bir elektronun hangi enerji düzeyinde ve nasıl bir bölgede olduğu sayılarla belirtilir."},{"t":"Adlandır","a":"kuantum sayıları","d":"Bu sayıların tümüne <b>kuantum sayıları</b> denir."}],"ans":"Bir elektronun yerini ve durumunu tarif eden sayılara kuantum sayıları denir."},
{"q":"Baş kuantum sayısı (n) bir elektron hakkında bize en çok neyi söyler?","steps":[{"t":"n neyi gösterir","a":"enerji düzeyi","d":"Baş kuantum sayısı n, elektronun bulunduğu temel enerji düzeyini (kabuğu) gösterir."},{"t":"Uzaklıkla ilişki","a":"çekirdek uzaklığı","d":"n büyüdükçe elektron çekirdekten ortalama olarak daha uzakta ve daha yüksek enerjilidir."}],"ans":"Baş kuantum sayısı n, elektronun enerji düzeyini (kabuğu) ve çekirdeğe ortalama uzaklığını gösterir."},
{"q":"Bir orbitalde en fazla kaç elektron bulunabilir?","steps":[{"t":"Orbital kapasitesi","a":"sınırlı","d":"Her orbital sınırlı sayıda elektron alabilir."},{"t":"Sayıyı söyle","a":"2 elektron","d":"Bir orbitalde en fazla 2 elektron bulunur; bunlar ters dönüş yönlüdür."}],"ans":"Bir orbitalde en fazla 2 elektron bulunabilir ve bu iki elektronun dönüş yönü zıttır."},
{"q":"Spin kuantum sayısı (mₛ) bir elektronun hangi özelliğiyle ilgilidir?","steps":[{"t":"Spin nedir","a":"dönüş yönü","d":"Spin, elektronun kendi etrafındaki dönüş yönü gibi düşünülen özelliğidir."},{"t":"İki değer","a":"+½ ve −½","d":"Spin kuantum sayısı yalnızca iki değer alır: +½ veya −½."}],"ans":"Spin kuantum sayısı mₛ, elektronun dönüş yönüyle ilgilidir ve yalnızca +½ ya da −½ değerini alır."},
{"q":"Bir atomdaki iki elektronun dört kuantum sayısının tamamı aynı olabilir mi?","steps":[{"t":"Benzersizlik","a":"her elektron özel","d":"Her elektronun kuantum sayılarından oluşan takımı kendine özeldir."},{"t":"Kural","a":"aynı olamaz","d":"İki elektronun dört kuantum sayısı aynı anda aynı olamaz."}],"ans":"Hayır; bir atomda iki elektronun dört kuantum sayısının tamamı aynı olamaz."}
],"zor":[
{"q":"Baş kuantum sayısı n = 1 olan kabukta en fazla 2, n = 2 olan kabukta en fazla 8 elektron bulunur. Bu sayılar arasında nasıl bir kural vardır?","steps":[{"t":"Değerleri yaz","a":"2 ve 8","d":"1. kabukta 2, 2. kabukta 8 elektron bulunur."},{"t":"Kuralı bul","a":"2n²","d":"Bu sayılar 2·1² = 2 ve 2·2² = 8 olarak çıkar; kapasite 2n² ile bulunur."}],"ans":"Bir kabuğun en fazla elektron sayısı 2n² kuralıyla bulunur: n=1 için 2, n=2 için 8 elektrondur."},
{"q":"Aynı orbitalde bulunan iki elektronun spin kuantum sayıları (mₛ) nasıl olmalıdır?","steps":[{"t":"Aynı orbital","a":"diğerleri aynı","d":"Aynı orbitaldeki iki elektronun ilk üç kuantum sayısı (n, ℓ, mₗ) aynıdır."},{"t":"Ayrım gereği","a":"zıt spin","d":"İkisinin durumu tıpatıp aynı olamayacağı için spinleri zıt olmalıdır: biri +½, biri −½."}],"ans":"Aynı orbitaldeki iki elektronun spinleri zıttır; biri +½ ise diğeri −½ olmak zorundadır."},
{"q":"Bir atomda iki elektronun dört kuantum sayısının aynı olamayacağını söyleyen kuralın adı nedir?","steps":[{"t":"Benzersizlik fikri","a":"her elektron özel","d":"Her elektronun dört kuantum sayısından oluşan takımı kendine özeldir."},{"t":"İlkeyi adlandır","a":"Pauli ilkesi","d":"Bu kurala <b>Pauli dışarlama ilkesi</b> denir."}],"ans":"Bu kurala Pauli dışarlama ilkesi denir; iki elektronun dört kuantum sayısı aynı anda aynı olamaz."},
{"q":"3. kabukta (n = 3) en fazla kaç elektron bulunabilir?","steps":[{"t":"Kuralı yaz","a":"2n²","d":"Bir kabuğun kapasitesi 2n² ile bulunur."},{"t":"Yerine koy","a":"2·3²","d":"n = 3 için: 2 × 9 = 18."}],"ans":"3. kabukta en fazla 2n² = 2·3² = 18 elektron bulunabilir."},
{"q":"Bir elektronu tam olarak tanımlamak için kaç tane kuantum sayısı gerekir ve bunlar nelerdir?","steps":[{"t":"Sayıyı bul","a":"4 tane","d":"Bir elektronun durumunu tam tanımlamak için dört kuantum sayısı gerekir."},{"t":"İsimlerini say","a":"n, ℓ, mₗ, mₛ","d":"Bunlar baş (n), açısal (ℓ), manyetik (mₗ) ve spin (mₛ) kuantum sayılarıdır."}],"ans":"Bir elektron dört kuantum sayısıyla tanımlanır: baş (n), açısal (ℓ), manyetik (mₗ) ve spin (mₛ)."}
]},"lise":{"kolay":[
{"q":"Dört kuantum sayısı (n, ℓ, mₗ, mₛ) sırasıyla hangi özellikleri belirler?","steps":[{"t":"n ve ℓ","a":"düzey ve alt kabuk","d":"Baş kuantum sayısı n enerji düzeyini, açısal kuantum sayısı ℓ alt kabuğun türünü (s, p, d, f) belirler."},{"t":"mₗ ve mₛ","a":"yönelim ve spin","d":"Manyetik kuantum sayısı mₗ orbitalin uzaydaki yönelimini, spin kuantum sayısı mₛ elektronun dönüş yönünü belirler."}],"ans":"n enerji düzeyini, ℓ alt kabuğu (orbital türünü), mₗ orbitalin yönelimini, mₛ ise elektronun spinini belirler."},
{"q":"Açısal kuantum sayısı ℓ'nin alabileceği değerler baş kuantum sayısı n'ye nasıl bağlıdır?","steps":[{"t":"Bağıntıyı yaz","a":"ℓ = 0 ... n−1","d":"ℓ, 0'dan başlayıp n−1'e kadar tam sayı değerler alır."},{"t":"Örnek ver","a":"n=3 → ℓ=0,1,2","d":"n = 3 için ℓ değerleri 0, 1 ve 2 olur; yani s, p ve d alt kabukları bulunur."}],"ans":"Açısal kuantum sayısı ℓ, 0'dan n−1'e kadar değer alır; örneğin n=3 için ℓ = 0, 1, 2'dir (s, p, d)."},
{"q":"Açısal kuantum sayısı ℓ = 0, 1, 2, 3 değerleri hangi alt kabuklara (orbital türlerine) karşılık gelir?","steps":[{"t":"Eşleştir","a":"s, p, d, f","d":"ℓ = 0 → s, ℓ = 1 → p, ℓ = 2 → d, ℓ = 3 → f alt kabuğuna karşılık gelir."},{"t":"Sıralama","a":"artan ℓ","d":"ℓ büyüdükçe alt kabuk türü s, p, d, f sırasıyla değişir."}],"ans":"ℓ = 0 s, ℓ = 1 p, ℓ = 2 d, ℓ = 3 f alt kabuğuna karşılık gelir."},
{"q":"Manyetik kuantum sayısı mₗ'nin alabileceği değerler hangi aralıktadır?","steps":[{"t":"Aralığı yaz","a":"−ℓ ... +ℓ","d":"mₗ, −ℓ'den +ℓ'ye kadar tam sayı değerler alır (0 dahil)."},{"t":"Örnek","a":"ℓ=1 → −1,0,+1","d":"ℓ = 1 (p) için mₗ = −1, 0, +1 olur; yani 3 yönelim vardır."}],"ans":"Manyetik kuantum sayısı mₗ, −ℓ'den +ℓ'ye kadar (0 dahil) tam sayı değerler alır."},
{"q":"Bir alt kabuktaki orbital sayısı açısal kuantum sayısı ℓ'ye nasıl bağlıdır?","fig":"<svg viewBox='0 0 320 110'><rect x='20' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='34' y='90' font-size='11' text-anchor='middle' fill='#1a2b45'>s</text><text x='34' y='30' font-size='10' text-anchor='middle' fill='#1a2b45'>1</text><rect x='90' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='120' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='150' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='134' y='90' font-size='11' text-anchor='middle' fill='#1a2b45'>p</text><text x='134' y='30' font-size='10' text-anchor='middle' fill='#1a2b45'>3</text><rect x='210' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='240' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><rect x='270' y='40' width='28' height='28' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='254' y='90' font-size='11' text-anchor='middle' fill='#1a2b45'>d</text><text x='254' y='30' font-size='10' text-anchor='middle' fill='#1a2b45'>5</text></svg>","steps":[{"t":"Bağıntıyı yaz","a":"2ℓ + 1","d":"Bir alt kabuktaki orbital sayısı 2ℓ + 1 ile bulunur (mₗ'nin değer sayısı kadar)."},{"t":"Örnekle","a":"s=1, p=3, d=5","d":"ℓ=0 için 1 (s), ℓ=1 için 3 (p), ℓ=2 için 5 (d) orbital olur."}],"ans":"Bir alt kabuktaki orbital sayısı 2ℓ + 1'dir: s'de 1, p'de 3, d'de 5 orbital bulunur."}
],"zor":[
{"q":"n = 3 enerji düzeyinde bulunan alt kabukları, her birinin orbital sayısını ve düzeyin toplam elektron kapasitesini bulunuz.","steps":[{"t":"Alt kabukları yaz","a":"3s, 3p, 3d","d":"n = 3 için ℓ = 0, 1, 2 olur; yani 3s, 3p ve 3d alt kabukları bulunur."},{"t":"Orbital sayıları","a":"1, 3, 5","d":"2ℓ+1'den 3s'de 1, 3p'de 3, 3d'de 5 orbital; toplam 9 orbital."},{"t":"Kapasite","a":"2·9 = 18","d":"Her orbital 2 elektron aldığından toplam 18 elektron; bu 2n² = 2·3² = 18 ile uyumludur."}],"ans":"n = 3'te 3s (1), 3p (3) ve 3d (5) toplam 9 orbital bulunur; kapasite 2·9 = 18 = 2n² elektrondur."},
{"q":"Bir elektronun kuantum sayıları n = 4, ℓ = 2, mₗ = +1 olarak verilmiştir. Bu elektron hangi alt kabuktadır ve mₛ'nin olası değerleri nelerdir?","steps":[{"t":"Alt kabuğu belirle","a":"4d","d":"n = 4 ve ℓ = 2 olduğundan elektron 4d alt kabuğundadır."},{"t":"mₗ kontrolü","a":"geçerli","d":"ℓ = 2 için mₗ = −2,−1,0,+1,+2 aralığındadır; +1 bu aralıktadır, geçerlidir."},{"t":"mₛ değerleri","a":"+½ veya −½","d":"Spin her zaman iki değerden birini alır: +½ ya da −½."}],"ans":"Elektron 4d alt kabuğundadır; mₗ = +1 geçerlidir ve mₛ değeri +½ veya −½ olabilir."},
{"q":"Aşağıdaki dört kuantum sayısı dörtlüsünden hangileri olanaksızdır, gerekçesiyle belirtiniz: (a) n=2, ℓ=1, mₗ=−1, mₛ=+½  (b) n=3, ℓ=3, mₗ=0, mₛ=−½  (c) n=1, ℓ=0, mₗ=0, mₛ=−½","steps":[{"t":"(a)'yı denetle","a":"geçerli","d":"n=2 için ℓ=1 izinli (ℓ≤n−1), mₗ=−1 (−1..+1) aralığında, mₛ=+½ geçerli."},{"t":"(b)'yi denetle","a":"olanaksız","d":"n=3 için ℓ en çok 2 olabilir; ℓ=3 izinli değildir, bu dörtlü olanaksızdır."},{"t":"(c)'yi denetle","a":"geçerli","d":"n=1 için ℓ=0, mₗ=0, mₛ=−½: tüm değerler kurallara uygundur."}],"ans":"Yalnızca (b) olanaksızdır; çünkü n = 3 için ℓ en fazla 2 olabilir, ℓ = 3 izin verilen aralık dışındadır. (a) ve (c) geçerlidir."},
{"q":"ℓ = 2 (d alt kabuğu) için manyetik kuantum sayısı mₗ'nin tüm değerlerini ve bu alt kabuğun en fazla elektron sayısını bulunuz.","fig":"<svg viewBox='0 0 320 90'><rect x='30' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='45' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>−2</text><rect x='80' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='95' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>−1</text><rect x='130' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='145' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>0</text><rect x='180' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='195' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>+1</text><rect x='230' y='35' width='30' height='30' fill='none' stroke='#1a2b45' stroke-width='1.5'/><text x='245' y='28' font-size='9' text-anchor='middle' fill='#1a2b45'>+2</text></svg>","steps":[{"t":"mₗ değerleri","a":"−2..+2","d":"ℓ = 2 için mₗ = −2, −1, 0, +1, +2 olmak üzere 5 değer alır."},{"t":"Orbital sayısı","a":"5 orbital","d":"2ℓ+1 = 5 orbital vardır."},{"t":"Elektron sayısı","a":"2·5 = 10","d":"Her orbital 2 elektron aldığından d alt kabuğu en fazla 10 elektron alır."}],"ans":"ℓ = 2 için mₗ = −2, −1, 0, +1, +2'dir (5 orbital); d alt kabuğu en fazla 2·5 = 10 elektron alır."},
{"q":"Bir orbitaldeki iki elektron için n = 2, ℓ = 1, mₗ = 0 ortaktır. Pauli dışarlama ilkesine göre bu iki elektronu yalnızca hangi kuantum sayısı ayırır ve değerleri ne olur?","fig":"<svg viewBox='0 0 320 90'><rect x='130' y='30' width='60' height='32' fill='none' stroke='#1a2b45' stroke-width='1.5'/><line x1='150' y1='38' x2='150' y2='56' stroke='#2b6be0' stroke-width='2'/><polygon points='150,38 146,45 154,45' fill='#2b6be0'/><line x1='170' y1='56' x2='170' y2='38' stroke='#e0552b' stroke-width='2'/><polygon points='170,56 166,49 174,49' fill='#e0552b'/><text x='160' y='80' font-size='10' text-anchor='middle' fill='#1a2b45'>spin zit</text></svg>","steps":[{"t":"Ortak değerler","a":"n,ℓ,mₗ aynı","d":"İki elektronun n = 2, ℓ = 1, mₗ = 0 değerleri ortaktır; ilk üç sayı aynıdır."},{"t":"Pauli gereği","a":"spin farklı","d":"Dört sayının tümü aynı olamayacağından, ayırt eden tek sayı spin mₛ'dir."},{"t":"Değerleri yaz","a":"+½ ve −½","d":"Biri +½, diğeri −½ spinlidir (zıt yönlü)."}],"ans":"İki elektronu yalnızca spin kuantum sayısı mₛ ayırır; biri +½, diğeri −½ değerini alır."}
]}}};
