globalThis.__OUT = {"bohrModeli":{"ilkokul":{"kolay":[
{"q":"Bohr'a göre elektronlar çekirdeğin etrafında nasıl dolaşır?","fig":"<svg viewBox='0 0 320 175'><circle cx='160' cy='88' r='11' fill='#e0552b' stroke='#1a2b45'/><circle cx='160' cy='88' r='34' fill='none' stroke='#1a2b45'/><circle cx='160' cy='88' r='60' fill='none' stroke='#1a2b45'/><circle cx='194' cy='88' r='5' fill='#2b6be0'/><circle cx='160' cy='28' r='5' fill='#2b6be0'/><text x='160' y='168' font-size='11' text-anchor='middle' fill='#1a2b45'>belirli halkalarda döner</text></svg>","steps":[{"t":"Halka yollar","a":"yörünge","d":"Bohr'a göre elektronlar çekirdeğin etrafındaki belirli halkalar (yörüngeler) üzerinde döner."},{"t":"Düzenli","a":"karışmaz","d":"Gezegenlerin Güneş'in etrafında dönmesi gibi, her elektron kendi halkasında düzenli döner."}],"ans":"Bohr'a göre elektronlar çekirdeğin etrafında belirli halkalarda (yörüngelerde) düzenli döner."},
{"q":"Bohr modelinde elektronların döndüğü halkalara ne ad verilir?","steps":[{"t":"Halkanın adı","a":"katman (yörünge)","d":"Elektronların döndüğü her halkaya katman ya da enerji düzeyi denir."},{"t":"Basamak gibi","a":"sıralı","d":"Katmanlar çekirdekten dışa doğru basamak basamak sıralanır."}],"ans":"Elektronların döndüğü halkalara katman (yörünge) denir."},
{"q":"Çekirdeğe en yakın katmanda mı yoksa en uzakta mı daha az enerji vardır?","steps":[{"t":"Yakın katman","a":"az enerji","d":"Çekirdeğe en yakın katmandaki elektron en düşük enerjiye sahiptir."},{"t":"Uzak katman","a":"çok enerji","d":"Çekirdekten uzaklaştıkça katmanın enerjisi artar."}],"ans":"Çekirdeğe en yakın katmanda enerji en azdır; uzaklaştıkça enerji artar."},
{"q":"Bohr modeli atomu neye benzetir?","fig":"<svg viewBox='0 0 320 175'><circle cx='160' cy='88' r='13' fill='#f4d03f' stroke='#1a2b45'/><circle cx='160' cy='88' r='40' fill='none' stroke='#1a2b45'/><circle cx='160' cy='88' r='66' fill='none' stroke='#1a2b45'/><circle cx='200' cy='88' r='5' fill='#2b6be0'/><circle cx='160' cy='22' r='5' fill='#2b6be0'/><text x='160' y='168' font-size='11' text-anchor='middle' fill='#1a2b45'>Güneş ve gezegenler gibi</text></svg>","steps":[{"t":"Güneş","a":"çekirdek","d":"Ortadaki çekirdek, Güneş gibi merkezdedir."},{"t":"Gezegenler","a":"elektronlar","d":"Elektronlar da gezegenler gibi belirli yollarda çekirdeğin etrafında döner."}],"ans":"Bohr modeli atomu, Güneş'in etrafında dönen gezegenlere benzetir."},
{"q":"Elektron kendi katmanında dönerken enerji kaybeder mi?","steps":[{"t":"Kendi yolunda","a":"kararlı","d":"Elektron kendi katmanında dönerken kararlıdır."},{"t":"Sonuç","a":"kaybetmez","d":"Bu sırada enerji kaybetmez, sürekli aynı yolda döner."}],"ans":"Hayır; elektron kendi katmanında dönerken enerji kaybetmez, kararlıdır."}
],"zor":[
{"q":"Bohr modeline göre bir elektron neden çekirdeğe düşmez?","steps":[{"t":"Belirli yörünge","a":"izinli yol","d":"Elektron yalnız belirli izinli yörüngelerde durabilir; arada duramaz."},{"t":"Enerji yaymaz","a":"kararlı kalır","d":"Bu yörüngelerde enerji yaymadığı için yavaşlayıp çekirdeğe düşmez."}],"ans":"Elektron belirli izinli yörüngelerde enerji yaymadan kararlı kaldığı için çekirdeğe düşmez."},
{"q":"K katmanı ile L katmanı arasındaki fark nedir?","fig":"<svg viewBox='0 0 320 180'><circle cx='160' cy='90' r='11' fill='#e0552b' stroke='#1a2b45'/><circle cx='160' cy='90' r='32' fill='none' stroke='#1a2b45'/><circle cx='160' cy='90' r='60' fill='none' stroke='#1a2b45'/><text x='160' y='62' font-size='11' text-anchor='middle' fill='#1a2b45'>K</text><text x='160' y='34' font-size='11' text-anchor='middle' fill='#1a2b45'>L</text></svg>","steps":[{"t":"K katmanı","a":"en içte","d":"K katmanı çekirdeğe en yakın, en düşük enerjili katmandır."},{"t":"L katmanı","a":"bir dışta","d":"L katmanı K'nin hemen dışındadır ve daha yüksek enerjilidir."}],"ans":"K katmanı çekirdeğe en yakın ve düşük enerjili, L katmanı ise bir dış katman ve daha yüksek enerjilidir."},
{"q":"Her katmanın belirli sayıda elektron alması ne anlama gelir?","steps":[{"t":"Sınırlı yer","a":"belirli sayı","d":"Her katman ancak belirli sayıda elektron taşıyabilir (K en fazla 2, L en fazla 8 gibi)."},{"t":"Önce iç dolar","a":"sıralı dolma","d":"Elektronlar önce çekirdeğe yakın iç katmanları doldurur, sonra dış katmanlara geçer."}],"ans":"Her katmanın taşıyabileceği elektron sayısı sınırlıdır ve elektronlar önce iç katmanları doldurur."},
{"q":"Bohr modeli, kendinden önceki Rutherford modeline göre hangi yeniliği getirdi?","steps":[{"t":"Rutherford","a":"çekirdek + boşluk","d":"Rutherford çekirdeği buldu ama elektronların nasıl döndüğünü tam açıklayamadı."},{"t":"Bohr","a":"belirli katman","d":"Bohr, elektronların belirli enerjili katmanlarda kararlı döndüğünü ekledi."}],"ans":"Bohr, elektronların belirli enerjili katmanlarda düzenli döndüğünü açıklayarak Rutherford modelini geliştirdi."},
{"q":"Bir atomun ışık yayması Bohr modeline göre nasıl olur?","steps":[{"t":"Üst katmana çık","a":"enerji al","d":"Elektron enerji alıp üst (daha uzak) bir katmana çıkar."},{"t":"Geri dön","a":"ışık ver","d":"Geri alt katmana inerken aldığı enerjiyi ışık olarak dışarı verir."}],"ans":"Elektron enerji alıp üst katmana çıkar, geri inerken bu enerjiyi ışık olarak yayar."}
]},"ortaokul":{"kolay":[
{"q":"Bohr atom modelinin temel fikri nedir?","fig":"<svg viewBox='0 0 320 180'><circle cx='160' cy='90' r='11' fill='#e0552b' stroke='#1a2b45'/><circle cx='160' cy='90' r='30' fill='none' stroke='#1a2b45'/><circle cx='160' cy='90' r='52' fill='none' stroke='#1a2b45'/><circle cx='160' cy='90' r='72' fill='none' stroke='#1a2b45'/><text x='160' y='176' font-size='10' text-anchor='middle' fill='#1a2b45'>belirli enerji düzeyleri</text></svg>","steps":[{"t":"Belirli düzeyler","a":"enerji katmanı","d":"Elektronlar yalnız belirli enerjili katmanlarda (yörüngelerde) bulunabilir."},{"t":"Kararlılık","a":"enerji yaymaz","d":"Elektron kendi katmanında dönerken enerji yaymaz, yani kararlıdır."}],"ans":"Bohr modeline göre elektronlar belirli enerjili katmanlarda kararlı şekilde döner ve bu katmanlarda enerji yaymaz."},
{"q":"Bohr modelinde katmanlar nasıl adlandırılır ve hangisi en düşük enerjilidir?","steps":[{"t":"Adlandırma","a":"K, L, M, N","d":"Katmanlar çekirdekten dışa doğru K, L, M, N şeklinde adlandırılır."},{"t":"En düşük","a":"K katmanı","d":"Çekirdeğe en yakın olan K katmanı en düşük enerjiye sahiptir."}],"ans":"Katmanlar K, L, M, N olarak adlandırılır; çekirdeğe en yakın K katmanı en düşük enerjilidir."},
{"q":"K, L ve M katmanları en fazla kaçar elektron alabilir?","steps":[{"t":"İç katmanlar","a":"K=2, L=8","d":"İlk katman K en fazla 2, ikinci katman L en fazla 8 elektron alır."},{"t":"M katmanı","a":"18 (ilk 8)","d":"Üçüncü katman M toplamda 18 alabilir; temel düzeyde ilk 8 elektronla dolması yeterlidir."}],"ans":"K katmanı en fazla 2, L katmanı 8, M katmanı toplamda 18 elektron alabilir."},
{"q":"Bir elektron üst katmana çıkmak için ne yapmalıdır?","steps":[{"t":"Enerji gerekli","a":"enerji al","d":"Üst (daha uzak) katmana çıkmak için elektronun dışarıdan enerji alması gerekir."},{"t":"Sıçrama","a":"belirli miktar","d":"Bu enerji rastgele değildir; iki katmanın enerji farkı kadar belirli bir miktar olmalıdır."}],"ans":"Bir elektron üst katmana çıkmak için iki katman arasındaki fark kadar belirli bir enerji almalıdır."},
{"q":"Bohr modeline göre 'enerji düzeyi' ne demektir?","steps":[{"t":"Belirli enerji","a":"sabit değer","d":"Her katmanın belirli, sabit bir enerji değeri vardır; elektron orada bu enerjiyle bulunur."},{"t":"Ara değer yok","a":"basamak gibi","d":"Elektron iki katman arasında ara bir enerjide bulunamaz; enerji basamaklar gibi belirlidir."}],"ans":"Enerji düzeyi, bir katmanın sahip olduğu belirli ve sabit enerjidir; elektron ancak bu düzeylerde bulunabilir."}
],"zor":[
{"q":"Bohr modeli, Rutherford modelindeki hangi soruna çözüm getirmiştir?","steps":[{"t":"Rutherford sorunu","a":"kararsızlık","d":"Rutherford modelinde dönen elektronun sürekli enerji kaybedip çekirdeğe düşmesi beklenir; atom kararsız görünür."},{"t":"Bohr çözümü","a":"kararlı düzey","d":"Bohr, belirli enerji düzeylerinde elektronun enerji yaymadan kararlı kaldığını öne sürerek bu sorunu çözdü."}],"ans":"Bohr, belirli enerji düzeylerinde elektronun enerji yaymadığını söyleyerek Rutherford modelinin kararsızlık sorununu çözmüştür."},
{"q":"Elektronların enerji düzeylerinin 'kuantlı (kesikli)' olması ne demektir?","fig":"<svg viewBox='0 0 320 175'><line x1='70' y1='140' x2='250' y2='140' stroke='#1a2b45'/><line x1='70' y1='105' x2='250' y2='105' stroke='#1a2b45'/><line x1='70' y1='70' x2='250' y2='70' stroke='#1a2b45'/><line x1='70' y1='40' x2='250' y2='40' stroke='#1a2b45'/><circle cx='160' cy='140' r='5' fill='#2b6be0'/><text x='270' y='144' font-size='10' fill='#1a2b45'>n=1</text><text x='270' y='74' font-size='10' fill='#1a2b45'>n=3</text><text x='160' y='165' font-size='10' text-anchor='middle' fill='#1a2b45'>basamaklı enerji</text></svg>","steps":[{"t":"Belirli değerler","a":"sadece izinli","d":"Elektronun enerjisi yalnız belirli (izinli) değerler alabilir, aradaki değerler yasaktır."},{"t":"Merdiven gibi","a":"ara basamak yok","d":"Bu durum merdivene benzer; ancak basamaklarda durabilir, basamaklar arasında bir yerde duramaz."}],"ans":"Kuantlı olması, elektron enerjisinin yalnız belirli izinli değerler alabilmesi, aradaki değerlerin yasak olması demektir (merdiven basamağı gibi)."},
{"q":"Bohr modeline göre bir elektron L katmanından K katmanına inerken ne olur?","steps":[{"t":"Daha düşük düzey","a":"enerji azalır","d":"K katmanı L'den daha düşük enerjilidir; elektron alt düzeye inerken fazla enerjisinden kurtulur."},{"t":"Enerji yayımı","a":"ışık (foton)","d":"Aradaki enerji farkı, belirli renkte bir ışık (foton) olarak dışarı yayılır."}],"ans":"Elektron L'den K'ye inerken aradaki enerji farkını belirli renkte bir ışık (foton) olarak yayar."},
{"q":"Bohr modelinin temel bir eksikliği nedir?","steps":[{"t":"Tek elektron sınırı","a":"sadece hidrojen","d":"Bohr modeli yalnız hidrojen gibi tek elektronlu atomları doğru açıklar."},{"t":"Çok elektron sorunu","a":"yetersiz","d":"Birden çok elektronu olan atomların davranışını ve spektrumunu tam açıklayamaz."}],"ans":"Bohr modeli yalnız tek elektronlu (hidrojen gibi) atomlarda işler; çok elektronlu atomları açıklamakta yetersizdir."},
{"q":"Bir atomun elektron dizilimi 2,8,1 ise bu Bohr modeline göre neyi gösterir?","fig":"<svg viewBox='0 0 320 185'><circle cx='160' cy='92' r='11' fill='#e0552b' stroke='#1a2b45'/><circle cx='160' cy='92' r='30' fill='none' stroke='#1a2b45'/><circle cx='160' cy='92' r='52' fill='none' stroke='#1a2b45'/><circle cx='160' cy='92' r='74' fill='none' stroke='#1a2b45'/><text x='160' y='66' font-size='9' text-anchor='middle' fill='#1a2b45'>2</text><text x='160' y='44' font-size='9' text-anchor='middle' fill='#1a2b45'>8</text><text x='160' y='180' font-size='10' text-anchor='middle' fill='#1a2b45'>2,8,1 dizilimi</text></svg>","steps":[{"t":"Katman doluluğu","a":"K=2, L=8","d":"İlk katmanda 2, ikinci katmanda 8 elektron vardır; bu iki katman tam doludur."},{"t":"Son katman","a":"1 elektron","d":"Üçüncü (son) katmanda 1 elektron vardır; bu, atomun toplam 11 elektronu olduğunu (sodyum) gösterir."}],"ans":"2,8,1 dizilimi K ve L katmanlarının dolu, son katmanda 1 elektron olduğunu (toplam 11 elektronlu sodyum) gösterir."}
]},"lise":{"kolay":[
{"q":"Bohr atom modelinin temel varsayımları nelerdir?","fig":"<svg viewBox='0 0 320 185'><circle cx='160' cy='92' r='10' fill='#e0552b' stroke='#1a2b45'/><circle cx='160' cy='92' r='28' fill='none' stroke='#1a2b45'/><circle cx='160' cy='92' r='50' fill='none' stroke='#1a2b45'/><circle cx='160' cy='92' r='72' fill='none' stroke='#1a2b45'/><text x='160' y='180' font-size='10' text-anchor='middle' fill='#1a2b45'>kararlı, kuantlı enerji düzeyleri</text></svg>","steps":[{"t":"Kararlı yörünge","a":"belirli enerji","d":"Elektron yalnız belirli (kuantlı) enerjili yörüngelerde bulunur ve bu yörüngelerde enerji yaymaz."},{"t":"Geçişte foton","a":"al/ver","d":"Elektron bir düzeyden diğerine geçerken iki düzeyin enerji farkı kadar foton soğurur veya yayar."}],"ans":"Bohr'a göre elektron belirli kararlı enerji düzeylerinde döner, bu düzeylerde enerji yaymaz ve ancak düzeyler arası geçişte foton alıp verir."},
{"q":"Bohr modelinde enerji düzeylerinin kuantlanması ne anlama gelir?","steps":[{"t":"Ayrık değerler","a":"izinli enerjiler","d":"Elektronun enerjisi sürekli değil, yalnız belirli ayrık değerler (n=1, 2, 3...) alabilir."},{"t":"Sonuç","a":"ara değer yok","d":"İki izinli düzey arasında elektronun bulunabileceği bir enerji yoktur."}],"ans":"Kuantlanma, elektron enerjisinin yalnız belirli ayrık (izinli) değerler alabilmesi, ara değerlerin yasak olması demektir."},
{"q":"Bohr modelinde temel hâl (taban durum) ile uyarılmış hâl arasındaki fark nedir?","steps":[{"t":"Temel hâl","a":"n=1, en kararlı","d":"Elektron en düşük enerjili düzeyde (n=1) bulunduğunda atom temel hâldedir ve en kararlıdır."},{"t":"Uyarılmış hâl","a":"üst düzey, kararsız","d":"Elektron enerji soğurup üst bir düzeye (n=2, 3...) çıktığında atom uyarılmış ve daha kararsız hâldedir."}],"ans":"Temel hâlde elektron en düşük (n=1) düzeydedir ve kararlıdır; uyarılmış hâlde enerji alıp üst düzeye çıkmış, kararsız hâldedir."},
{"q":"Bohr modeli hangi deneysel gözlemi başarıyla açıklamıştır?","steps":[{"t":"Gözlem","a":"çizgi spektrumu","d":"Hidrojen gazı uyarıldığında yalnız belirli dalga boylarında kesikli ışık çizgileri yayar."},{"t":"Açıklama","a":"enerji geçişleri","d":"Bohr, bu çizgilerin elektronun belirli enerji düzeyleri arasında geçişiyle yayılan fotonlardan kaynaklandığını gösterdi."}],"ans":"Bohr modeli, hidrojenin kesikli çizgi spektrumunu elektronun enerji düzeyleri arası geçişleriyle başarıyla açıklamıştır."},
{"q":"Bohr modeline göre yörünge yarıçapı arttıkça elektronun enerjisi nasıl değişir?","steps":[{"t":"Uzaklık etkisi","a":"yarıçap büyür","d":"n arttıkça (üst düzeylerde) elektronun çekirdekten uzaklığı, yani yörünge yarıçapı büyür."},{"t":"Enerji","a":"artar","d":"Çekirdeğe uzaklaştıkça elektronun enerjisi artar; düzeyler arası fark ise giderek azalır."}],"ans":"Yörünge yarıçapı (n) büyüdükçe elektronun enerjisi artar, ancak ardışık düzeyler arasındaki enerji farkı azalır."}
],"zor":[
{"q":"Bohr modeline göre hidrojen atomunda elektron n=3'ten n=2'ye geçerse ne tür bir olay gözlenir?","fig":"<svg viewBox='0 0 320 180'><circle cx='160' cy='92' r='10' fill='#e0552b' stroke='#1a2b45'/><circle cx='160' cy='92' r='28' fill='none' stroke='#1a2b45'/><circle cx='160' cy='92' r='52' fill='none' stroke='#1a2b45'/><circle cx='160' cy='92' r='76' fill='none' stroke='#1a2b45'/><line x1='160' y1='16' x2='160' y2='44' stroke='#e0552b' stroke-width='2'/><polygon points='160,44 156,36 164,36' fill='#e0552b'/><text x='200' y='30' font-size='9' fill='#1a2b45'>n=3→n=2</text><text x='160' y='176' font-size='10' text-anchor='middle' fill='#1a2b45'>foton yayımı</text></svg>","steps":[{"t":"Alt düzeye iniş","a":"enerji açığa çıkar","d":"n=3 düzeyi n=2'den daha yüksek enerjilidir; elektron inerken fazla enerjisinden kurtulur."},{"t":"Foton yayımı","a":"belirli dalga boyu","d":"İki düzeyin enerji farkı (ΔE = E₃ − E₂) kadar enerji, belirli dalga boylu bir foton olarak yayılır ve görünür bölgede bir çizgi oluşturur."}],"ans":"Elektron n=3'ten n=2'ye inerken iki düzeyin enerji farkı kadar belirli dalga boylu bir foton (görünür çizgi) yayar; bu emisyondur."},
{"q":"Bohr modeli çok elektronlu atomların spektrumunu neden tam açıklayamaz?","steps":[{"t":"Elektron etkileşimi","a":"itme kuvvetleri","d":"Çok elektronlu atomlarda elektronlar birbirini iter; Bohr modeli bu karşılıklı itmeleri hesaba katmaz."},{"t":"Sonuç","a":"sapma","d":"Bu yüzden hesaplanan enerji düzeyleri, gözlenen karmaşık spektrumla tam uyuşmaz."}],"ans":"Bohr modeli elektronlar arası itmeleri içermediği için çok elektronlu atomların karmaşık spektrumunu tam açıklayamaz."},
{"q":"Bohr modelinin kabul ettiği 'kesin yörünge' varsayımı modern fizikle neden çelişir?","steps":[{"t":"Belirsizlik ilkesi","a":"konum + hız","d":"Heisenberg belirsizlik ilkesine göre elektronun konumu ve hızı (momentumu) aynı anda kesin ölçülemez."},{"t":"Çelişki","a":"yörünge anlamsız","d":"Konum ve hız birlikte kesin bilinemediğinden, elektronun çizgisel kesin bir yörüngesi olduğunu söylemek anlamını yitirir."}],"ans":"Heisenberg belirsizlik ilkesi konum ve hızın aynı anda kesin bilinemeyeceğini söylediğinden, Bohr'un kesin yörünge varsayımı modern fizikle çelişir."},
{"q":"Bohr modeline göre enerji düzeyleri arasındaki fark üst düzeylere çıkıldıkça neden azalır?","fig":"<svg viewBox='0 0 320 180'><line x1='80' y1='150' x2='240' y2='150' stroke='#1a2b45'/><line x1='80' y1='95' x2='240' y2='95' stroke='#1a2b45'/><line x1='80' y1='60' x2='240' y2='60' stroke='#1a2b45'/><line x1='80' y1='42' x2='240' y2='42' stroke='#1a2b45'/><line x1='80' y1='33' x2='240' y2='33' stroke='#1a2b45'/><text x='255' y='154' font-size='9' fill='#1a2b45'>n=1</text><text x='255' y='37' font-size='9' fill='#1a2b45'>n=5</text><text x='160' y='172' font-size='10' text-anchor='middle' fill='#1a2b45'>üstte sıklaşır</text></svg>","steps":[{"t":"Enerji bağıntısı","a":"1/n² ile orantılı","d":"Düzey enerjisi yaklaşık 1/n² ile değişir; n büyüdükçe enerjideki değişim giderek yavaşlar."},{"t":"Sonuç","a":"düzeyler sıklaşır","d":"Bu nedenle üst düzeylere çıkıldıkça ardışık düzeyler birbirine yaklaşır ve aradaki enerji farkı azalır."}],"ans":"Düzey enerjisi 1/n² ile değiştiğinden n büyüdükçe düzeyler birbirine yaklaşır; bu yüzden üstlere çıkıldıkça enerji farkı azalır."},
{"q":"Bohr modeli, klasik fiziğin hangi kuralını terk ederek atomun kararlılığını açıklamıştır?","steps":[{"t":"Klasik kural","a":"ivmeli yük ışır","d":"Klasik elektromanyetizmaya göre, çembersel hareket yapan (ivmeli) yüklü elektron sürekli ışıma yapıp enerji kaybetmelidir."},{"t":"Bohr varsayımı","a":"kararlı düzeyde ışımaz","d":"Bohr bu kuralı terk ederek, belirli izinli düzeylerde elektronun ışıma yapmadan kararlı kaldığını varsaydı."}],"ans":"Bohr, 'ivmeli yükün sürekli ışıması' klasik kuralını terk edip belirli düzeylerde elektronun ışımadan kararlı kaldığını varsayarak atomun kararlılığını açıkladı."}
]}}};
