globalThis.__OUT = {"rutherford":{"ilkokul":{"kolay":[
{"q":"Rutherford altın levha deneyinde levhaya doğru ne gönderilmiştir?","steps":[{"t":"Gönderilen tanecik","a":"küçük tanecikler","d":"Rutherford, çok ince altın levhanın üzerine pozitif yüklü küçük tanecikler (alfa) gönderdi."},{"t":"Amaç","a":"içini anlamak","d":"Bu taneciklerin nasıl davrandığına bakarak atomun içinin nasıl olduğunu anlamak istedi."}],"ans":"Rutherford ince altın levhaya doğru pozitif yüklü küçük tanecikler (alfa) gönderdi."},
{"q":"Rutherford deneyindeki taneciklerin çoğu altın levhadan nasıl geçti?","fig":"<svg viewBox='0 0 320 160'><rect x='150' y='25' width='10' height='110' fill='#ffd54a' stroke='#1a2b45'/><text x='155' y='150' font-size='11' text-anchor='middle' fill='#1a2b45'>altın levha</text><line x1='30' y1='80' x2='150' y2='80' stroke='#e0552b' stroke-width='2'/><line x1='160' y1='80' x2='290' y2='80' stroke='#e0552b' stroke-width='2'/><polygon points='290,80 281,76 281,84' fill='#e0552b'/><text x='80' y='70' font-size='10' fill='#1a2b45'>tanecik</text></svg>","steps":[{"t":"Çoğunun yolu","a":"düz geçti","d":"Taneciklerin büyük çoğunluğu levhadan hiç sapmadan düz bir şekilde geçip gitti."},{"t":"Anlamı","a":"içerisi boş","d":"Bu, atomun büyük bölümünün boş olduğunu gösterdi."}],"ans":"Taneciklerin çoğu altın levhadan sapmadan düz geçti; bu atomun çoğunun boşluk olduğunu gösterdi."},
{"q":"Bazı tanecikler neden geri sekti veya yön değiştirdi?","steps":[{"t":"Sebep","a":"sert bir yere çarptı","d":"Az sayıda tanecik atomun ortasındaki çok küçük ve yoğun bir yere çarpıp geri seke geldi."},{"t":"O yer","a":"çekirdek","d":"Bu küçük, sert ve pozitif yüklü bölgeye çekirdek denir."}],"ans":"Bazı tanecikler atomun ortasındaki küçük, yoğun ve pozitif çekirdeğe çarptığı için geri sekti."},
{"q":"Rutherford deneyiyle atomun ortasında ne olduğunu keşfetti?","steps":[{"t":"Keşfedilen yapı","a":"çekirdek","d":"Rutherford, atomun tam ortasında küçük ama ağır bir çekirdek olduğunu buldu."},{"t":"Yükü","a":"pozitif (+)","d":"Bu çekirdek pozitif (artı) yüklüdür."}],"ans":"Rutherford atomun ortasında küçük, ağır ve pozitif yüklü bir çekirdek olduğunu keşfetti."},
{"q":"Atomun büyük kısmı neyle doludur?","fig":"<svg viewBox='0 0 300 160'><circle cx='150' cy='80' r='60' fill='none' stroke='#1a2b45'/><circle cx='150' cy='80' r='7' fill='#e0552b'/><text x='150' y='150' font-size='11' text-anchor='middle' fill='#1a2b45'>küçük çekirdek, geniş boşluk</text></svg>","steps":[{"t":"İç yapı","a":"çoğu boş","d":"Atomun çok büyük kısmı boşluktur, içinde madde yoktur."},{"t":"Küçük çekirdek","a":"ortada","d":"Sadece ortadaki minik çekirdek doludur, geri kalan yer neredeyse boştur."}],"ans":"Atomun büyük kısmı boşluktur; sadece ortadaki küçük çekirdek doludur."}
],"zor":[
{"q":"Rutherford deneyinde taneciklerin çok azının geri sekmesi neyi kanıtlar?","steps":[{"t":"Az sekme","a":"çekirdek küçük","d":"Çok az tanecik geri seksesi, çarptıkları yoğun çekirdeğin atoma göre çok küçük olduğunu gösterir."},{"t":"Çoğu geçer","a":"boşluk çok","d":"Geri kalan çok sayıda tanecik geçtiği için atomun büyük kısmı boştur."}],"ans":"Taneciklerin çok azının geri sekmesi, atomdaki pozitif çekirdeğin çok küçük, geri kalanın ise boşluk olduğunu kanıtlar."},
{"q":"Rutherford'dan önce atomun nasıl olduğu düşünülüyordu ve onun deneyi bunu nasıl değiştirdi?","steps":[{"t":"Eski düşünce","a":"her yeri dolu","d":"Önceden atomun içinin her yerinin eşit biçimde dolu olduğu sanılıyordu."},{"t":"Yeni bilgi","a":"boş + çekirdek","d":"Rutherford, atomun ortasında küçük bir çekirdek, çevresinde ise geniş boşluk olduğunu gösterdi."}],"ans":"Önceden atomun her yerinin dolu olduğu sanılırdı; Rutherford ortada küçük çekirdek, çevresinde boşluk olduğunu gösterdi."},
{"q":"Çekirdek pozitif yüklü olduğu için tanecikler ona yaklaşınca ne olur?","steps":[{"t":"İki artı yük","a":"birbirini iter","d":"Gönderilen tanecikler de çekirdek de pozitiftir; aynı yükler birbirini iter."},{"t":"Sonuç","a":"sapma/sekme","d":"Çekirdeğe yaklaşan tanecik bu itme yüzünden yön değiştirir veya geri seker."}],"ans":"Pozitif çekirdek, pozitif tanecikleri iter; bu yüzden çekirdeğe yaklaşan tanecikler sapar ya da geri seker."},
{"q":"Atomun kütlesinin büyük kısmı nerede toplanmıştır ve bunu deneyden nasıl anlarız?","steps":[{"t":"Kütle yeri","a":"çekirdekte","d":"Atomun kütlesinin neredeyse tamamı küçük çekirdekte toplanmıştır."},{"t":"Kanıt","a":"sekme","d":"Hızlı tanecikleri geri sektirebilecek kadar ağır olması, kütlenin çekirdekte yoğunlaştığını gösterir."}],"ans":"Atomun kütlesinin büyük kısmı çekirdektedir; hızlı tanecikleri geri sektirebilmesi çekirdeğin çok ağır olduğunu gösterir."},
{"q":"Rutherford modelinde çekirdeğin çevresinde ne bulunur?","fig":"<svg viewBox='0 0 300 170'><circle cx='150' cy='85' r='8' fill='#e0552b'/><circle cx='150' cy='85' r='55' fill='none' stroke='#1a2b45' stroke-dasharray='4 3'/><circle cx='205' cy='85' r='5' fill='#2b6be0'/><text x='150' y='160' font-size='11' text-anchor='middle' fill='#1a2b45'>çekirdek + dış elektron</text></svg>","steps":[{"t":"Dış bölge","a":"elektronlar","d":"Pozitif çekirdeğin çevresindeki boşlukta eksi yüklü elektronlar dolaşır."},{"t":"Denge","a":"artı + eksi","d":"Pozitif çekirdek ile eksi elektronlar birlikte atomu oluşturur."}],"ans":"Rutherford modelinde pozitif çekirdeğin çevresindeki boşlukta eksi yüklü elektronlar bulunur."}
]},"ortaokul":{"kolay":[
{"q":"Rutherford altın levha (saçılma) deneyinde hangi tür ışın kullanılmıştır?","steps":[{"t":"Kullanılan ışın","a":"alfa taneciği","d":"Rutherford, pozitif yüklü ve hızlı hareket eden alfa taneciklerini ince altın levhaya gönderdi."},{"t":"Gözlem yöntemi","a":"floresan ekran","d":"Taneciklerin levhadan sonra nereye gittiği, çevredeki ışıldayan ekran üzerinde gözlendi."}],"ans":"Rutherford deneyinde pozitif yüklü, hızlı alfa tanecikleri kullanılmış ve sapmaları ışıldayan ekranda izlenmiştir."},
{"q":"Deneyde gözlenen üç farklı tanecik davranışı nedir?","fig":"<svg viewBox='0 0 320 170'><rect x='150' y='20' width='9' height='130' fill='#ffd54a' stroke='#1a2b45'/><line x1='30' y1='60' x2='290' y2='60' stroke='#e0552b' stroke-width='2'/><line x1='30' y1='95' x2='154' y2='95' stroke='#e0552b' stroke-width='2'/><line x1='159' y1='95' x2='250' y2='130' stroke='#e0552b' stroke-width='2'/><line x1='30' y1='125' x2='150' y2='125' stroke='#e0552b' stroke-width='2'/><line x1='150' y1='125' x2='60' y2='150' stroke='#e0552b' stroke-width='2'/><text x='250' y='155' font-size='10' fill='#1a2b45'>levha</text></svg>","steps":[{"t":"Çoğu düz","a":"sapmadan geçer","d":"Taneciklerin çoğu hiç sapmadan levhadan düz geçer."},{"t":"Az sapan/sekenler","a":"saparlar","d":"Bazıları açıyla sapar, çok azı ise geri seker."}],"ans":"Tanecikler ya düz geçer, ya açıyla sapar ya da çok azı geri seker; bu üç farklı davranış gözlenir."},
{"q":"Taneciklerin çoğunun düz geçmesi atom hakkında ne söyler?","steps":[{"t":"Düz geçiş","a":"engelle karşılaşmaz","d":"Taneciklerin çoğu yolda bir engelle karşılaşmadan geçer."},{"t":"Sonuç","a":"atom çoğunlukla boş","d":"Bu da atomun büyük bir kısmının boşluktan oluştuğunu gösterir."}],"ans":"Taneciklerin çoğunun düz geçmesi, atomun büyük kısmının boşluk olduğunu gösterir."},
{"q":"Çekirdeğin yükü nedir ve bunu hangi gözlem gösterir?","steps":[{"t":"Yük","a":"pozitif","d":"Çekirdek pozitif (artı) yüklüdür."},{"t":"Gözlem","a":"pozitif tanecik sapması","d":"Pozitif alfa taneciklerinin saparak/geri sekerek itilmesi, çekirdeğin de pozitif olduğunu gösterir."}],"ans":"Çekirdek pozitif yüklüdür; pozitif alfa taneciklerini itip saptırması bunu gösterir."},
{"q":"Rutherford deneyinde alfa taneciklerinin geri sekmesi neyi gösterir?","steps":[{"t":"Geri sekme","a":"sert ve yoğun","d":"Geri sekme, taneciklerin çok yoğun ve sert bir bölgeye çarptığını gösterir."},{"t":"O bölge","a":"çekirdek","d":"Bu bölge, atomun kütlesinin toplandığı küçük çekirdektir."}],"ans":"Geri sekme, taneciklerin atomdaki küçük, yoğun ve ağır çekirdeğe çarptığını gösterir."}
],"zor":[
{"q":"Rutherford'un saçılma deneyi, Thomson'un üzümlü kek modelini neden çürütmüştür?","steps":[{"t":"Thomson modeli","a":"yük dağınık","d":"Thomson'a göre pozitif yük atoma eşit yayılmış, elektronlar içine gömülüydü; büyük sapma beklenmezdi."},{"t":"Deney sonucu","a":"büyük sapma var","d":"Bazı taneciklerin geri sekmesi, yükün dağınık değil küçük bir çekirdekte toplandığını gösterdi."}],"ans":"Bazı taneciklerin geri sekmesi, yükün dağınık olmadığını, küçük bir çekirdekte toplandığını gösterdi; bu Thomson modelini çürüttü."},
{"q":"Sadece çok az taneciğin büyük açıyla sapması, çekirdeğin boyutu hakkında ne söyler?","steps":[{"t":"Az sayı","a":"hedef küçük","d":"Yalnızca çok az tanecik büyük açıyla sapıyorsa, çarptıkları çekirdeğin atoma göre çok küçük olması gerekir."},{"t":"Oran","a":"çekirdek minik","d":"Çekirdek, atomun yanında bilye yanındaki bir toz tanesi kadar küçüktür."}],"ans":"Çok az taneciğin büyük açıyla sapması, çekirdeğin atoma göre çok küçük bir hedef olduğunu gösterir."},
{"q":"Bir alfa taneciği çekirdeğe ne kadar yakından geçerse sapma açısı nasıl değişir?","fig":"<svg viewBox='0 0 320 160'><circle cx='160' cy='80' r='8' fill='#e0552b'/><text x='160' y='105' font-size='10' text-anchor='middle' fill='#1a2b45'>çekirdek</text><line x1='30' y1='40' x2='160' y2='40' stroke='#2b6be0' stroke-width='2'/><line x1='160' y1='40' x2='270' y2='25' stroke='#2b6be0' stroke-width='2'/><line x1='30' y1='75' x2='150' y2='75' stroke='#e0552b' stroke-width='2'/><line x1='150' y1='75' x2='90' y2='130' stroke='#e0552b' stroke-width='2'/></svg>","steps":[{"t":"Uzak geçiş","a":"az sapma","d":"Çekirdekten uzaktan geçen tanecik az itilir, bu yüzden küçük açıyla sapar."},{"t":"Yakın geçiş","a":"çok sapma","d":"Çekirdeğe çok yaklaşan tanecik daha güçlü itilir, büyük açıyla sapar veya geri seker."}],"ans":"Tanecik çekirdeğe ne kadar yakın geçerse itme o kadar güçlü olur ve sapma açısı o kadar büyür."},
{"q":"Rutherford modeli atomun kütle ve hacim dağılımını nasıl açıklar?","steps":[{"t":"Kütle","a":"çekirdekte yoğun","d":"Atomun kütlesinin neredeyse tamamı çok küçük çekirdekte toplanmıştır."},{"t":"Hacim","a":"boşlukta","d":"Atomun hacminin büyük kısmı ise çekirdek çevresindeki boş bölgedir; bu yüzden çekirdek çok yoğundur."}],"ans":"Rutherford modeline göre kütle küçük çekirdekte yoğunlaşmıştır, hacmin büyük kısmı ise çevredeki boşluktur."},
{"q":"Deneyde altın levhanın çok ince seçilmesi neden önemlidir?","steps":[{"t":"İnce levha","a":"birkaç atom kalınlık","d":"Levha çok ince olursa tanecikler yalnızca birkaç atom katmanından geçer."},{"t":"Sebep","a":"tek çarpışmayı görmek","d":"Böylece her taneciğin tek bir çekirdekle nasıl etkileştiği net biçimde gözlenebilir; çok katlı çarpışma karmaşası önlenir."}],"ans":"İnce levha taneciklerin az sayıda atomdan geçmesini sağlar; böylece tek çekirdek çarpışmasının etkisi net görülür."}
]},"lise":{"kolay":[
{"q":"Rutherford altın levha deneyinde ince levhaya gönderilen tanecik ve bunun gözlenmesinin amacı nedir?","steps":[{"t":"Gönderilen tanecik","a":"alfa (²⁺)","d":"Pozitif yüklü alfa tanecikleri (helyum çekirdeği) yüksek hızla ince altın levhaya gönderildi."},{"t":"Amaç","a":"yük dağılımı","d":"Taneciklerin sapma açıları incelenerek atomdaki pozitif yükün ve kütlenin nasıl dağıldığı araştırıldı."}],"ans":"Pozitif yüklü alfa tanecikleri ince altın levhaya gönderildi; amaç sapmalardan atomdaki yük ve kütle dağılımını belirlemekti."},
{"q":"Deneyde gözlenen sonuçlar ve her birinin atom yapısı için anlamı nedir?","steps":[{"t":"Çoğu sapmasız","a":"boşluk","d":"Taneciklerin büyük çoğunluğunun sapmadan geçmesi, atomun büyük kısmının boş olduğunu gösterdi."},{"t":"Az sayı sapma/sekme","a":"küçük yoğun çekirdek","d":"Az sayıda taneciğin sapması ve çok azının geri sekmesi, kütle ve pozitif yükün küçük bir çekirdekte yoğunlaştığını gösterdi."}],"ans":"Çoğu tanecik sapmadan geçti (atom çoğunlukla boş); az kısmı saptı, çok azı geri sekti (kütle ve artı yük küçük çekirdekte yoğun)."},
{"q":"Rutherford modeli, Thomson modelinden hangi temel noktada ayrılır?","steps":[{"t":"Thomson","a":"yük yayılmış","d":"Thomson modelinde pozitif yük atoma düzgün yayılmış, elektronlar bu kütleye gömülüydü."},{"t":"Rutherford","a":"yük çekirdekte","d":"Rutherford'da pozitif yük ve kütle merkezdeki küçük çekirdekte toplanmış, elektronlar çevrede dolaşır."}],"ans":"Thomson'da yük atoma yayılmıştır; Rutherford'da ise pozitif yük ve kütle merkezdeki küçük çekirdekte toplanmıştır."},
{"q":"Çekirdeğin atom hacmine oranla çok küçük olduğu deney sonucundan nasıl çıkarılır?","steps":[{"t":"Sapma oranı","a":"çok düşük","d":"Binlerce tanecikten yalnızca çok azının büyük açıyla sapması, çekirdeğin küçük bir hedef olduğunu gösterir."},{"t":"Hacim oranı","a":"çok büyük fark","d":"Bu oran, çekirdeğin atom çapına göre on binlerce kat küçük olduğunu gösterir; atom büyük oranda boştur."}],"ans":"Taneciklerin çok azının saptığı gözleminden, çekirdeğin atom hacmine göre çok küçük olduğu çıkarılır."},
{"q":"Rutherford modeline göre atomdaki elektronların konumu ve görevi nedir?","fig":"<svg viewBox='0 0 300 170'><circle cx='150' cy='85' r='9' fill='#e0552b'/><circle cx='150' cy='85' r='40' fill='none' stroke='#1a2b45' stroke-dasharray='4 3'/><circle cx='150' cy='85' r='62' fill='none' stroke='#1a2b45' stroke-dasharray='4 3'/><circle cx='190' cy='85' r='5' fill='#2b6be0'/><circle cx='150' cy='23' r='5' fill='#2b6be0'/><text x='150' y='160' font-size='11' text-anchor='middle' fill='#1a2b45'>çekirdek + dolaşan elektronlar</text></svg>","steps":[{"t":"Konum","a":"çekirdek çevresinde","d":"Eksi yüklü elektronlar, pozitif çekirdeğin çevresindeki geniş boşlukta dolaşır."},{"t":"Görev","a":"yük dengesi","d":"Elektronların eksi yükü, çekirdeğin artı yükünü dengeleyerek atomu nötr tutar."}],"ans":"Elektronlar pozitif çekirdek çevresindeki boşlukta dolaşır ve eksi yükleriyle atomun yük dengesini sağlar."}
],"zor":[
{"q":"Rutherford modeli klasik fiziğe göre neden kararsızdır ve bu eksiklik nasıl giderilmiştir?","steps":[{"t":"Klasik sorun","a":"enerji ışıması","d":"Klasik fiziğe göre çekirdek çevresinde dolaşan (ivmeli) elektron sürekli enerji yayar ve çekirdeğe düşmelidir."},{"t":"Çözüm","a":"Bohr modeli","d":"Bohr, elektronların yalnızca belirli (kararlı) enerji düzeylerinde dolaştığını öne sürerek bu çökme sorununu giderdi."}],"ans":"Rutherford modelinde dolaşan elektron sürekli enerji yayıp çekirdeğe düşmelidir; bu eksiklik Bohr'un kararlı enerji düzeyleri modeliyle giderilmiştir."},
{"q":"Alfa taneciğinin sapma açısı ile çekirdeğe yaklaşma uzaklığı (çarpma parametresi) arasındaki ilişki nedir?","fig":"<svg viewBox='0 0 320 170'><circle cx='170' cy='85' r='9' fill='#e0552b'/><text x='170' y='110' font-size='10' text-anchor='middle' fill='#1a2b45'>çekirdek (+)</text><line x1='25' y1='45' x2='170' y2='45' stroke='#2b6be0' stroke-width='2'/><line x1='170' y1='45' x2='285' y2='35' stroke='#2b6be0' stroke-width='2'/><line x1='25' y1='80' x2='158' y2='80' stroke='#e0552b' stroke-width='2'/><line x1='158' y1='80' x2='110' y2='150' stroke='#e0552b' stroke-width='2'/><text x='40' y='38' font-size='9' fill='#1a2b45'>uzak: az sapma</text></svg>","steps":[{"t":"Büyük uzaklık","a":"küçük açı","d":"Çekirdeğe büyük uzaklıktan (büyük çarpma parametresi) geçen tanecik zayıf itilir, küçük açıyla sapar."},{"t":"Küçük uzaklık","a":"büyük açı","d":"Çekirdeğe çok yaklaşan tanecik güçlü Coulomb itmesiyle büyük açıyla sapar, tam üzerine gidenler geri seker."}],"ans":"Çarpma parametresi (yaklaşma uzaklığı) küçüldükçe Coulomb itmesi artar ve sapma açısı büyür; uzaktan geçenler az, yakından geçenler çok sapar."},
{"q":"Çekirdeğin yoğunluğunun olağanüstü büyük olduğu, deney verileriyle nasıl açıklanır?","steps":[{"t":"Kütle ve hacim","a":"büyük kütle/küçük hacim","d":"Atomun kütlesinin neredeyse tamamı çekirdekte, ama çekirdeğin hacmi atomun çok küçük bir kesridir."},{"t":"Yoğunluk","a":"aşırı yüksek","d":"Yoğunluk = kütle/hacim olduğundan, büyük kütlenin küçük hacme sığması çekirdek yoğunluğunu olağanüstü büyük yapar."}],"ans":"Kütlenin tamamına yakını çok küçük çekirdek hacmine sığdığından, yoğunluk (kütle/hacim) olağanüstü büyük çıkar."},
{"q":"Rutherford deneyinde sapan taneciklerin pozitif çekirdek tarafından itildiğini hangi kuvvet açıklar?","steps":[{"t":"Kuvvet türü","a":"Coulomb itmesi","d":"Pozitif alfa taneciği ile pozitif çekirdek arasında elektriksel (Coulomb) itme kuvveti vardır."},{"t":"Uzaklıkla değişim","a":"yakınken güçlü","d":"Bu kuvvet uzaklığın karesiyle ters orantılıdır; çekirdeğe yaklaşıldıkça hızla güçlenir ve büyük sapmaya yol açar."}],"ans":"Sapma, pozitif alfa taneciği ile pozitif çekirdek arasındaki Coulomb (elektriksel) itme kuvvetiyle açıklanır; bu kuvvet yaklaşınca güçlenir."},
{"q":"Rutherford'un atom modeli hangi parçacığı öngörmüş, hangisini açıklayamamıştır?","steps":[{"t":"Öngördüğü","a":"proton (çekirdek yükü)","d":"Çekirdekteki pozitif yükü taşıyan parçacık olan protonun varlığı bu modelden anlaşıldı."},{"t":"Açıklayamadığı","a":"nötron","d":"Çekirdekteki kütlenin yalnızca protonla açıklanamayan fazlası, sonradan keşfedilen nötronla anlaşıldı; Rutherford bunu modelinde gösteremedi."}],"ans":"Rutherford modeli çekirdekteki pozitif protonu öngördü, ancak çekirdek kütlesinin fazlasını veren yüksüz nötronu açıklayamadı."}
]}}};
