globalThis.__OUT = {"atomNoKutleNo":{"ilkokul":{"kolay":[
{"q":"Atom numarası bir atomun neyini gösterir?","steps":[{"t":"Gösterdiği sayı","a":"proton sayısı","d":"Atom numarası, atomun çekirdeğindeki proton sayısını gösterir."},{"t":"Kimlik","a":"element belli olur","d":"Proton sayısı, hangi element olduğunu söyleyen kimlik gibidir."}],"ans":"Atom numarası, bir atomun çekirdeğindeki proton sayısını gösterir."},
{"q":"Çekirdekte hangi iki tanecik bulunur?","fig":"<svg viewBox='0 0 300 160'><circle cx='150' cy='80' r='34' fill='none' stroke='#1a2b45'/><circle cx='138' cy='72' r='8' fill='#e0552b'/><circle cx='162' cy='72' r='8' fill='#e0552b'/><circle cx='138' cy='92' r='8' fill='#5b6b85'/><circle cx='162' cy='92' r='8' fill='#5b6b85'/><text x='150' y='150' font-size='11' text-anchor='middle' fill='#1a2b45'>proton (kırmızı) + nötron (gri)</text></svg>","steps":[{"t":"Birinci tanecik","a":"proton","d":"Çekirdekte artı yüklü protonlar bulunur."},{"t":"İkinci tanecik","a":"nötron","d":"Çekirdekte ayrıca yüksüz nötronlar bulunur."}],"ans":"Çekirdekte protonlar (artı yüklü) ve nötronlar (yüksüz) bulunur."},
{"q":"Kütle numarası neyin toplamıdır?","steps":[{"t":"Toplanan tanecikler","a":"proton + nötron","d":"Kütle numarası, çekirdekteki proton sayısı ile nötron sayısının toplamıdır."},{"t":"Kısaca","a":"A = p + n","d":"Kütle numarası A ile gösterilir; A = proton + nötron."}],"ans":"Kütle numarası, çekirdekteki proton ve nötron sayılarının toplamıdır (A = p + n)."},
{"q":"Atom numarası 6 olan bir atomun kaç protonu vardır?","steps":[{"t":"Atom numarası","a":"= proton","d":"Atom numarası proton sayısına eşittir."},{"t":"Sonuç","a":"6 proton","d":"Atom numarası 6 ise atomun 6 protonu vardır (bu karbondur)."}],"ans":"Atom numarası 6 olan atomun 6 protonu vardır."},
{"q":"7 protonu ve 7 nötronu olan bir atomun kütle numarası kaçtır?","steps":[{"t":"Toplam yap","a":"7 + 7","d":"Kütle numarası proton ile nötronun toplamıdır; 7 + 7 yapılır."},{"t":"Sonuç","a":"14","d":"7 + 7 = 14, yani kütle numarası 14'tür."}],"ans":"7 proton ve 7 nötronu olan atomun kütle numarası 14'tür."}
],"zor":[
{"q":"Kütle numarası 12 ve proton sayısı 6 olan atomun nötron sayısı kaçtır?","steps":[{"t":"Kural","a":"n = A − p","d":"Nötron sayısı, kütle numarasından proton sayısı çıkarılarak bulunur."},{"t":"Hesap","a":"12 − 6 = 6","d":"12 − 6 = 6, yani atomda 6 nötron vardır."}],"ans":"Kütle numarası 12, proton sayısı 6 olan atomun nötron sayısı 12 − 6 = 6'dır."},
{"q":"İki atomun proton sayısı aynı ama nötron sayısı farklıysa bunlara ne denir?","steps":[{"t":"Aynı proton","a":"aynı element","d":"Proton sayısı aynı olduğundan iki atom da ayni elementtir."},{"t":"Farklı nötron","a":"izotop","d":"Nötron sayıları farklı olan aynı elementin atomlarına izotop denir."}],"ans":"Proton sayısı aynı, nötron sayısı farklı olan aynı elementin atomlarına izotop denir."},
{"q":"Nötr bir atomda proton sayısı ile elektron sayısı nasıldır?","fig":"<svg viewBox='0 0 300 165'><circle cx='150' cy='80' r='12' fill='#e0552b' stroke='#1a2b45'/><text x='150' y='85' font-size='11' text-anchor='middle' fill='#fff'>+</text><circle cx='150' cy='80' r='45' fill='none' stroke='#1a2b45'/><circle cx='195' cy='80' r='5' fill='#2b6be0'/><circle cx='105' cy='80' r='5' fill='#2b6be0'/><text x='150' y='155' font-size='11' text-anchor='middle' fill='#1a2b45'>artı = eksi (nötr)</text></svg>","steps":[{"t":"Yük dengesi","a":"eşit","d":"Nötr atomda artı yük (proton) ile eksi yük (elektron) sayıları eşittir."},{"t":"Sonuç","a":"p = e","d":"Bu yüzden nötr atomda proton sayısı elektron sayısına eşittir."}],"ans":"Nötr bir atomda proton sayısı elektron sayısına eşittir (p = e)."},
{"q":"Atom numarası 11 olan sodyumun kütle numarası 23 ise nötron sayısı kaçtır?","steps":[{"t":"Kural","a":"n = A − p","d":"Nötron sayısı, kütle numarasından proton (atom numarası) çıkarılarak bulunur."},{"t":"Hesap","a":"23 − 11 = 12","d":"23 − 11 = 12, yani sodyum atomunda 12 nötron vardır."}],"ans":"Sodyumun (atom no 11, kütle no 23) nötron sayısı 23 − 11 = 12'dir."},
{"q":"Bir elementin kimliğini (hangi element olduğunu) belirleyen sayı hangisidir?","steps":[{"t":"Kimlik sayısı","a":"atom numarası","d":"Bir atomun hangi element olduğunu proton sayısı, yani atom numarası belirler."},{"t":"Nötron etkisi","a":"kimliği değiştirmez","d":"Nötron sayısı değişse bile (izotop) proton sayısı aynı kaldıkça element değişmez."}],"ans":"Bir elementin kimliğini atom numarası (proton sayısı) belirler; nötron sayısı kimliği değiştirmez."}
]},"ortaokul":{"kolay":[
{"q":"Atom numarası (Z) neyi ifade eder ve element kimliğiyle ilişkisi nedir?","steps":[{"t":"Tanım","a":"proton sayısı","d":"Atom numarası Z, çekirdekteki proton sayısına eşittir."},{"t":"Kimlik","a":"elementi belirler","d":"Her elementin proton sayısı farklıdır; bu yüzden Z elementin kimliğini belirler."}],"ans":"Atom numarası Z, proton sayısına eşittir ve her element için farklı olduğundan elementin kimliğini belirler."},
{"q":"Kütle numarası (A) nasıl hesaplanır?","fig":"<svg viewBox='0 0 300 160'><circle cx='150' cy='80' r='36' fill='none' stroke='#1a2b45'/><circle cx='136' cy='70' r='8' fill='#e0552b'/><circle cx='160' cy='70' r='8' fill='#e0552b'/><circle cx='136' cy='92' r='8' fill='#5b6b85'/><circle cx='160' cy='92' r='8' fill='#5b6b85'/><text x='150' y='150' font-size='11' text-anchor='middle' fill='#1a2b45'>A = proton + nötron</text></svg>","steps":[{"t":"Toplam","a":"p + n","d":"Kütle numarası, proton sayısı ile nötron sayısının toplamıdır."},{"t":"Formül","a":"A = p + n","d":"Elektronlar çok hafif olduğundan kütleye katılmaz; A yalnızca proton ve nötrondan oluşur."}],"ans":"Kütle numarası A, proton ve nötron sayılarının toplamıdır: A = p + n."},
{"q":"Nötron sayısı atom numarası ve kütle numarasından nasıl bulunur?","steps":[{"t":"Düzenleme","a":"A = p + n","d":"A = p + n eşitliğinde n yalnız bırakılır."},{"t":"Formül","a":"n = A − Z","d":"Nötron sayısı, kütle numarasından atom numarası çıkarılarak bulunur: n = A − Z."}],"ans":"Nötron sayısı, kütle numarasından atom numarası çıkarılarak bulunur: n = A − Z."},
{"q":"Atom numarası 17, kütle numarası 35 olan klorun proton, nötron ve elektron sayıları nedir?","steps":[{"t":"Proton ve elektron","a":"17 ve 17","d":"Atom numarası 17 olduğundan 17 proton vardır; nötr atomda elektron sayısı da 17'dir."},{"t":"Nötron","a":"35 − 17 = 18","d":"Nötron = A − Z = 35 − 17 = 18'dir."}],"ans":"Klorda 17 proton, 17 elektron ve 35 − 17 = 18 nötron bulunur."},
{"q":"İzotop nedir? Örnek vererek açıklayınız.","steps":[{"t":"Tanım","a":"aynı p, farklı n","d":"İzotoplar, proton sayısı aynı ama nötron sayısı farklı olan aynı elementin atomlarıdır."},{"t":"Örnek","a":"karbon-12 ve karbon-14","d":"Karbon-12 (6 proton, 6 nötron) ile karbon-14 (6 proton, 8 nötron) aynı elementin izotoplarıdır."}],"ans":"İzotop, proton sayısı aynı ama nötron sayısı farklı atomlardır; örneğin karbon-12 ve karbon-14 karbonun izotoplarıdır."}
],"zor":[
{"q":"Karbon-12 ve karbon-14 izotoplarının proton, nötron ve elektron sayılarını karşılaştırınız.","fig":"<svg viewBox='0 0 320 160'><circle cx='80' cy='75' r='30' fill='none' stroke='#1a2b45'/><circle cx='70' cy='68' r='6' fill='#e0552b'/><circle cx='90' cy='68' r='6' fill='#e0552b'/><circle cx='70' cy='84' r='6' fill='#5b6b85'/><circle cx='90' cy='84' r='6' fill='#5b6b85'/><text x='80' y='130' font-size='11' text-anchor='middle' fill='#1a2b45'>C-12: 6p, 6n</text><circle cx='235' cy='75' r='30' fill='none' stroke='#1a2b45'/><circle cx='225' cy='66' r='6' fill='#e0552b'/><circle cx='245' cy='66' r='6' fill='#e0552b'/><circle cx='225' cy='84' r='6' fill='#5b6b85'/><circle cx='245' cy='84' r='6' fill='#5b6b85'/><circle cx='235' cy='52' r='6' fill='#5b6b85'/><text x='235' y='130' font-size='11' text-anchor='middle' fill='#1a2b45'>C-14: 6p, 8n</text></svg>","steps":[{"t":"Ortak özellik","a":"6 proton, 6 e⁻","d":"Her ikisi de karbon olduğundan 6 protona ve nötr halde 6 elektrona sahiptir."},{"t":"Farklı özellik","a":"nötron 6 ve 8","d":"Karbon-12'de 12 − 6 = 6 nötron, karbon-14'te 14 − 6 = 8 nötron vardır; nötron sayıları farklıdır."}],"ans":"İkisinin de 6 protonu ve 6 elektronu vardır; karbon-12'de 6, karbon-14'te 8 nötron bulunur (izotop)."},
{"q":"Bir atomun proton, nötron ve elektron sayısı sırasıyla 19, 20, 19 ise atom numarası, kütle numarası ve yük durumu nedir?","steps":[{"t":"Atom ve kütle no","a":"Z=19, A=39","d":"Atom numarası proton sayısına eşittir (Z = 19); kütle numarası A = p + n = 19 + 20 = 39'dur."},{"t":"Yük","a":"nötr","d":"Proton (19) ile elektron (19) eşit olduğundan atom nötrdür, yüklü değildir (potasyum)."}],"ans":"Atom numarası 19, kütle numarası 39'dur; proton ve elektron eşit olduğundan atom nötrdür (potasyum-39)."},
{"q":"Bir atomda 8 proton, 10 nötron ve 8 elektron varsa kütle numarası ve element nedir?","steps":[{"t":"Kütle numarası","a":"8 + 10 = 18","d":"Kütle numarası A = p + n = 8 + 10 = 18'dir."},{"t":"Element","a":"oksijen","d":"Proton sayısı (atom numarası) 8 olan element oksijendir; bu atom oksijen-18 izotopudur."}],"ans":"Kütle numarası 18'dir ve atom numarası 8 olduğundan element oksijendir (oksijen-18)."},
{"q":"Klorun iki izotopu olan ³⁵Cl ve ³⁷Cl arasındaki tek fark nedir ve kimyasal özellikleri neden aynıdır?","steps":[{"t":"Tek fark","a":"nötron sayısı","d":"³⁵Cl'de 35 − 17 = 18, ³⁷Cl'de 37 − 17 = 20 nötron vardır; tek fark nötron sayısıdır."},{"t":"Kimya aynı","a":"e⁻ dizilimi aynı","d":"Her ikisinin de proton ve elektron sayısı 17 olduğundan değerlik elektron dizilimi aynıdır; kimyasal özellikleri bu yüzden özdeştir."}],"ans":"İki izotop yalnızca nötron sayısında (18 ve 20) farklıdır; proton ve elektron sayıları aynı olduğundan kimyasal özellikleri özdeştir."},
{"q":"Atom numarası 12 ve kütle numarası 24 olan magnezyum, 2 elektron verip Mg²⁺ olduğunda proton, nötron ve elektron sayıları ne olur?","steps":[{"t":"Proton ve nötron","a":"12 ve 12","d":"İyonlaşma çekirdeği değiştirmez; proton 12, nötron A − Z = 24 − 12 = 12 olarak kalır."},{"t":"Elektron","a":"12 − 2 = 10","d":"2 elektron verildiğinden elektron sayısı 10'a düşer; yük = 12 − 10 = +2 (Mg²⁺) olur."}],"ans":"Mg²⁺'da 12 proton ve 12 nötron değişmeden kalır, elektron sayısı 10'a düşer; yük +2 olur."}
]},"lise":{"kolay":[
{"q":"Atom numarası Z'nin proton sayısı, element kimliği ve nötr atomda elektron sayısıyla ilişkisi nedir?","steps":[{"t":"Z = proton","a":"element kimliği","d":"Atom numarası Z proton sayısına eşittir ve her element için benzersiz olduğundan elementin kimliğini belirler."},{"t":"Nötr atom","a":"Z = elektron","d":"Nötr atomda proton ile elektron eşit olduğundan elektron sayısı da Z'ye eşittir."}],"ans":"Z proton sayısına eşittir, elementin kimliğini belirler ve nötr atomda elektron sayısına da eşittir."},
{"q":"Kütle numarası A'nın tanımı nedir ve elektronlar neden A'ya katılmaz?","steps":[{"t":"Tanım","a":"A = p + n","d":"Kütle numarası, çekirdekteki proton ve nötron sayılarının toplamıdır."},{"t":"Elektron etkisi","a":"çok hafif","d":"Elektronun kütlesi protonun yaklaşık 1/1836'sı kadardır; ihmal edilebilecek kadar küçük olduğundan A'ya katılmaz."}],"ans":"Kütle numarası A = p + n'dir; elektronlar çok hafif (protonun yaklaşık 1/1836'sı) olduğundan kütle numarasına katılmaz."},
{"q":"₁₇³⁵Cl gösteriminde hangi sayı atom, hangisi kütle numarasıdır ve nötron sayısı kaçtır?","fig":"<svg viewBox='0 0 300 150'><text x='150' y='90' font-size='52' text-anchor='middle' fill='#1a2b45'>Cl</text><text x='95' y='62' font-size='26' text-anchor='middle' fill='#e0552b'>35</text><text x='95' y='110' font-size='26' text-anchor='middle' fill='#2b6be0'>17</text><text x='150' y='135' font-size='12' text-anchor='middle' fill='#1a2b45'>üst: A=35   alt: Z=17</text></svg>","steps":[{"t":"Gösterim","a":"alt: Z, üst: A","d":"Sembolün solunda alttaki sayı atom numarası (Z = 17), üstteki sayı kütle numarasıdır (A = 35)."},{"t":"Nötron","a":"35 − 17 = 18","d":"Nötron sayısı n = A − Z = 35 − 17 = 18'dir."}],"ans":"Alttaki 17 atom numarası (Z), üstteki 35 kütle numarasıdır (A); nötron sayısı 35 − 17 = 18'dir."},
{"q":"İzotop kavramını tanımlayıp neden izotopların kimyasal özelliklerinin aynı olduğunu açıklayınız.","steps":[{"t":"Tanım","a":"aynı Z, farklı A","d":"İzotoplar aynı proton sayısına (Z) ama farklı nötron sayısına (dolayısıyla farklı A'ya) sahip aynı elementin atomlarıdır."},{"t":"Kimya","a":"e⁻ dizilimi aynı","d":"Proton sayısı aynı olduğundan elektron sayısı ve değerlik dizilimi de aynıdır; kimyasal davranışı belirleyen elektronlar aynı olduğundan kimyasal özellikleri özdeştir."}],"ans":"İzotop, aynı Z'ye fakat farklı nötron sayısına sahip atomlardır; elektron dizilimleri aynı olduğundan kimyasal özellikleri özdeştir."},
{"q":"Bir atomda 26 proton, 30 nötron ve 23 elektron varsa atom numarası, kütle numarası ve yükü nedir?","steps":[{"t":"Z ve A","a":"26 ve 56","d":"Atom numarası proton sayısına eşittir (Z = 26, demir); kütle numarası A = 26 + 30 = 56'dır."},{"t":"Yük","a":"26 − 23 = +3","d":"Yük = proton − elektron = 26 − 23 = +3; bu tanecik Fe³⁺ iyonudur."}],"ans":"Atom numarası 26, kütle numarası 56'dır; yük 26 − 23 = +3, yani tanecik Fe³⁺ iyonudur."}
],"zor":[
{"q":"Bir elementin ortalama atom kütlesi, izotop kütleleri ve bollukları kullanılarak nasıl hesaplanır? Klor için örnekleyiniz.","steps":[{"t":"Yöntem","a":"ağırlıklı ortalama","d":"Ortalama atom kütlesi, her izotopun kütlesinin bolluk yüzdesiyle çarpılıp toplanmasıyla bulunur."},{"t":"Klor hesabı","a":"≈ 35,5","d":"³⁵Cl (%75) ve ³⁷Cl (%25) için: 35 · 0,75 + 37 · 0,25 = 26,25 + 9,25 = 35,5'tir."}],"ans":"Ortalama atom kütlesi izotop kütlelerinin bolluklarıyla ağırlıklı ortalamasıdır; klor için 35 · 0,75 + 37 · 0,25 = 35,5 çıkar."},
{"q":"Atom numarası aynı, kütle numarası farklı taneciklerin izotop; kütle numarası aynı, atom numarası farklı taneciklerin izobar olması ne anlama gelir?","steps":[{"t":"İzotop","a":"aynı Z","d":"İzotoplarda proton sayısı (Z) aynı, nötron sayısı (ve A) farklıdır; örneğin ¹²C ve ¹⁴C aynı elementtir."},{"t":"İzobar","a":"aynı A","d":"İzobarlarda kütle numarası A aynı, atom numarası Z farklıdır; bunlar farklı elementlerdir (örneğin ⁴⁰Ar ve ⁴⁰Ca)."}],"ans":"İzotoplar aynı Z'ye sahip aynı elementtir (n farklı); izobarlar ise aynı A'ya sahip farklı elementlerdir (Z farklı)."},
{"q":"S²⁻ iyonunda 16 proton, 16 nötron ve 18 elektron varsa kütle numarasını, yükü ve atomdan farkını açıklayınız.","steps":[{"t":"Kütle numarası","a":"16 + 16 = 32","d":"Kütle numarası yalnız çekirdeğe bağlıdır: A = p + n = 16 + 16 = 32'dir; iyonlaşma A'yı değiştirmez."},{"t":"Yük ve fark","a":"16 − 18 = −2","d":"Yük = proton − elektron = 16 − 18 = −2; nötr S atomuna göre 2 elektron fazlası olduğundan S²⁻ anyonudur."}],"ans":"Kütle numarası 32'dir (çekirdek değişmez); yük 16 − 18 = −2, yani nötr atomdan 2 elektron fazlası olan S²⁻ anyonudur."},
{"q":"Nötron sayısı = A − Z formülü, izotop sembolü ₉₂²³⁵U için nasıl uygulanır ve U-235 ile U-238 arasındaki fark nedir?","steps":[{"t":"U-235 nötronu","a":"235 − 92 = 143","d":"Uranyum atom numarası 92'dir; U-235'te nötron = A − Z = 235 − 92 = 143'tür."},{"t":"U-238 ile fark","a":"3 nötron","d":"U-238'de nötron = 238 − 92 = 146'dır; iki izotop arasında 146 − 143 = 3 nötron farkı vardır, proton sayısı aynıdır."}],"ans":"U-235'in nötron sayısı 235 − 92 = 143'tür; U-238 (146 nötron) ile aralarında yalnızca 3 nötronluk fark vardır, ikisi de 92 protonludur (izotop)."},
{"q":"İki nötr atomun atom numaraları farklı ama kütle numaraları eşitse (izobar), proton, nötron ve elektron sayıları nasıl karşılaştırılır? ⁴⁰₁₈Ar ve ⁴⁰₂₀Ca için açıklayınız.","steps":[{"t":"Proton ve elektron","a":"18 ve 20","d":"Argon 18, kalsiyum 20 protonludur; nötr olduklarından elektron sayıları da sırasıyla 18 ve 20'dir, yani farklıdır."},{"t":"Nötron","a":"22 ve 20","d":"Ar'da n = 40 − 18 = 22, Ca'da n = 40 − 20 = 20'dir; kütle numaraları eşit (40) olmasına rağmen nötron sayıları farklıdır."}],"ans":"Ar (18 p, 22 n, 18 e) ile Ca (20 p, 20 n, 20 e) farklı elementlerdir; kütle numaraları eşit olsa da proton, nötron ve elektron sayıları farklıdır (izobar)."}
]}}};
