globalThis.__OUT = {"katmanDizilimi":{"ilkokul":{"kolay":[
{"q":"Elektronlar atomda çekirdeğin çevresinde nereye dizilir?","fig":"<svg viewBox='0 0 300 170'><circle cx='150' cy='85' r='8' fill='#e0552b' stroke='#1a2b45'/><circle cx='150' cy='85' r='32' fill='none' stroke='#1a2b45'/><circle cx='150' cy='85' r='58' fill='none' stroke='#1a2b45'/><circle cx='182' cy='85' r='5' fill='#2b6be0'/><circle cx='150' cy='27' r='5' fill='#2b6be0'/><text x='150' y='160' font-size='11' text-anchor='middle' fill='#1a2b45'>katmanlar</text></svg>","steps":[{"t":"Çevredeki halkalar","a":"katmanlar","d":"Elektronlar çekirdeğin çevresindeki katman denilen halkalara yerleşir."},{"t":"Sıra","a":"içten dışa","d":"Önce içteki katman dolar, sonra dıştaki katmana geçilir."}],"ans":"Elektronlar çekirdeğin çevresindeki katmanlara içten dışa doğru sırayla dizilir."},
{"q":"Çekirdeğe en yakın ilk katmana en çok kaç elektron sığar?","steps":[{"t":"İlk katman","a":"en içteki","d":"Çekirdeğe en yakın katman ilk dolan katmandır."},{"t":"Kapasite","a":"2 elektron","d":"Bu ilk katmana en çok 2 elektron yerleşir."}],"ans":"Çekirdeğe en yakın ilk katmana en çok 2 elektron sığar."},
{"q":"İkinci katmana en çok kaç elektron sığar?","steps":[{"t":"İkinci katman","a":"dıştaki halka","d":"İlk katman dolduktan sonra elektronlar ikinci katmana yerleşir."},{"t":"Kapasite","a":"8 elektron","d":"İkinci katmana en çok 8 elektron sığar."}],"ans":"İkinci katmana en çok 8 elektron sığar."},
{"q":"En dış katmandaki elektronlara ne ad verilir?","steps":[{"t":"En dış katman","a":"dıştaki halka","d":"Atomun en dışındaki katmandaki elektronlar özeldir."},{"t":"Adı","a":"değerlik elektronu","d":"Bu elektronlara değerlik elektronu denir."}],"ans":"En dış katmandaki elektronlara değerlik elektronu denir."},
{"q":"Bir atomun en dış katmanı tamamen dolu olduğunda atom nasıl olur?","fig":"<svg viewBox='0 0 300 170'><circle cx='150' cy='85' r='8' fill='#e0552b' stroke='#1a2b45'/><circle cx='150' cy='85' r='50' fill='none' stroke='#1a2b45'/><circle cx='200' cy='85' r='4' fill='#2b6be0'/><circle cx='100' cy='85' r='4' fill='#2b6be0'/><circle cx='150' cy='35' r='4' fill='#2b6be0'/><circle cx='150' cy='135' r='4' fill='#2b6be0'/><text x='150' y='162' font-size='11' text-anchor='middle' fill='#1a2b45'>dolu katman = kararlı</text></svg>","steps":[{"t":"Dış katman dolu","a":"tam","d":"En dış katman elektronla tamamen dolduğunda atom istediği duruma ulaşır."},{"t":"Durum","a":"kararlı","d":"Bu durumda atom kararlıdır, kolay kolay tepkimeye girmez."}],"ans":"En dış katmanı dolu olan atom kararlı (mutlu) hale gelir ve kolay tepkimeye girmez."}
],"zor":[
{"q":"8 elektronlu bir atomun katman dizilimi nasıldır?","steps":[{"t":"İlk katman","a":"2 elektron","d":"İlk katmana önce 2 elektron yerleşir."},{"t":"Kalan","a":"6 dışta","d":"Geriye kalan 6 elektron ikinci katmana yerleşir; dizilim 2, 6 olur."}],"ans":"8 elektronlu atomun dizilimi 2, 6'dır."},
{"q":"Elektronlar katmanlara dizilirken hangi sırayı izler?","fig":"<svg viewBox='0 0 300 175'><circle cx='150' cy='90' r='8' fill='#e0552b' stroke='#1a2b45'/><circle cx='150' cy='90' r='30' fill='none' stroke='#1a2b45'/><circle cx='150' cy='90' r='56' fill='none' stroke='#1a2b45'/><text x='150' y='66' font-size='10' text-anchor='middle' fill='#1a2b45'>2</text><text x='150' y='40' font-size='10' text-anchor='middle' fill='#1a2b45'>8</text><text x='150' y='168' font-size='10' text-anchor='middle' fill='#1a2b45'>önce iç katman dolar</text></svg>","steps":[{"t":"İçten başla","a":"en yakın","d":"Elektronlar önce çekirdeğe en yakın katmana yerleşir."},{"t":"Dolunca geç","a":"sonra dışa","d":"İç katman (2) dolunca sonraki katmana (8) geçilir."}],"ans":"Elektronlar önce içteki katmanı doldurur, dolunca dıştaki katmana geçer (2, 8 ...)."},
{"q":"Değerlik elektronu az olan bir atom kararlı olmak için ne yapar?","steps":[{"t":"Az değerlik","a":"1-2 elektron","d":"En dış katmanında 1-2 elektronu olan atom için bunları vermek kolaydır."},{"t":"Yol","a":"elektron verir","d":"Bu az elektronu vererek altındaki dolu katmanı en dış katman yapar ve kararlı olur."}],"ans":"Değerlik elektronu az olan atom, bu elektronları vererek kararlı (dolu dış katmanlı) hale gelir."},
{"q":"Çoğu atom için kararlılık kaç değerlik elektronuyla sağlanır (oktet)?","steps":[{"t":"Hedef sayı","a":"8 elektron","d":"Çoğu atom en dış katmanında 8 elektron olunca kararlı olur."},{"t":"Adı","a":"oktet","d":"En dış katmanda 8 elektronla sağlanan bu kararlılığa oktet denir."}],"ans":"Çoğu atom en dış katmanında 8 elektronla (oktet) kararlı hale gelir."},
{"q":"Hidrojen ve helyum gibi küçük atomlar kaç elektronla kararlı olur (dublet)?","steps":[{"t":"Küçük atom","a":"ilk katman","d":"Çok küçük atomlar yalnızca ilk katmanı kullanır; bu katmana en çok 2 elektron sığar."},{"t":"Adı","a":"dublet","d":"En dış katmanda 2 elektronla sağlanan kararlılığa dublet denir."}],"ans":"Hidrojen ve helyum gibi küçük atomlar en dış katmanlarında 2 elektronla (dublet) kararlı olur."}
]},"ortaokul":{"kolay":[
{"q":"İlk üç elektron katmanına en fazla kaçar elektron sığar?","fig":"<svg viewBox='0 0 300 180'><circle cx='150' cy='90' r='8' fill='#e0552b' stroke='#1a2b45'/><circle cx='150' cy='90' r='26' fill='none' stroke='#1a2b45'/><circle cx='150' cy='90' r='50' fill='none' stroke='#1a2b45'/><circle cx='150' cy='90' r='74' fill='none' stroke='#1a2b45'/><text x='150' y='70' font-size='10' text-anchor='middle' fill='#1a2b45'>2</text><text x='150' y='46' font-size='10' text-anchor='middle' fill='#1a2b45'>8</text><text x='150' y='22' font-size='10' text-anchor='middle' fill='#1a2b45'>8</text></svg>","steps":[{"t":"İlk katman","a":"2","d":"Birinci katmana en çok 2 elektron sığar."},{"t":"Sonraki ikisi","a":"8 ve 8","d":"İkinci ve üçüncü katmanlara (temel düzeyde) en çok 8'er elektron yerleşir."}],"ans":"İlk üç katmanın en çok kapasitesi sırasıyla 2, 8, 8 elektrondur."},
{"q":"Değerlik elektronu nedir ve neden önemlidir?","steps":[{"t":"Tanım","a":"en dış katman e⁻","d":"Değerlik elektronu, atomun en dış katmanındaki elektronlardır."},{"t":"Önemi","a":"kimyasal davranış","d":"Atomun başka atomlarla nasıl birleşeceğini değerlik elektronları belirler."}],"ans":"Değerlik elektronu en dış katmandaki elektrondur; atomun kimyasal davranışını belirler."},
{"q":"Oktet ve dublet kuralı arasındaki fark nedir?","steps":[{"t":"Oktet","a":"8 elektron","d":"Çoğu atom en dış katmanında 8 elektronla (oktet) kararlı olur."},{"t":"Dublet","a":"2 elektron","d":"H ve He gibi küçük atomlar en dış katmanlarında 2 elektronla (dublet) kararlı olur."}],"ans":"Oktet en dış katmanda 8, dublet ise 2 elektronla sağlanan kararlılıktır."},
{"q":"Sodyum atomunun (11 elektron) katman dizilimi nasıldır?","fig":"<svg viewBox='0 0 300 185'><circle cx='150' cy='95' r='8' fill='#e0552b' stroke='#1a2b45'/><circle cx='150' cy='95' r='26' fill='none' stroke='#1a2b45'/><circle cx='150' cy='95' r='49' fill='none' stroke='#1a2b45'/><circle cx='150' cy='95' r='72' fill='none' stroke='#1a2b45'/><text x='150' y='76' font-size='10' text-anchor='middle' fill='#1a2b45'>2</text><text x='150' y='53' font-size='10' text-anchor='middle' fill='#1a2b45'>8</text><circle cx='222' cy='95' r='4' fill='#2b6be0'/><text x='150' y='178' font-size='10' text-anchor='middle' fill='#1a2b45'>Na: 2, 8, 1</text></svg>","steps":[{"t":"Dolum","a":"2 + 8","d":"İlk katmana 2, ikinci katmana 8 elektron yerleşir; toplam 10 olur."},{"t":"Kalan","a":"1 dışta","d":"Geriye kalan 1 elektron üçüncü katmana yerleşir; dizilim 2, 8, 1 olur."}],"ans":"Sodyumun (11 elektron) katman dizilimi 2, 8, 1'dir."},
{"q":"Bir atomun değerlik elektronu sayısı 8 ise (en dış katman dolu) atom nasıl davranır?","steps":[{"t":"Dolu dış katman","a":"oktet sağlandı","d":"En dış katmanda 8 elektron varsa oktet zaten sağlanmıştır."},{"t":"Davranış","a":"tepkimeye girmez","d":"Atom kararlı olduğundan elektron alıp vermeye ihtiyaç duymaz; soygazlar buna örnektir."}],"ans":"En dış katmanı 8 elektronlu (oktet) atom kararlıdır ve genelde tepkimeye girmez (soygaz gibi)."}
],"zor":[
{"q":"19 elektronlu potasyumun katman dizilimi nasıldır ve değerlik elektronu kaçtır?","steps":[{"t":"Dolum","a":"2, 8, 8","d":"İlk üç katman 2 + 8 + 8 = 18 elektronla dolar."},{"t":"Kalan","a":"1 → değerlik","d":"Geriye 1 elektron kalır, 4. katmana yerleşir; dizilim 2, 8, 8, 1, değerlik elektronu 1'dir."}],"ans":"Potasyumun dizilimi 2, 8, 8, 1'dir; değerlik elektronu sayısı 1'dir."},
{"q":"Sodyum (2, 8, 1) neden 1 elektron vererek kararlı olmayı tercih eder?","fig":"<svg viewBox='0 0 320 175'><circle cx='80' cy='85' r='7' fill='#e0552b'/><circle cx='80' cy='85' r='22' fill='none' stroke='#1a2b45'/><circle cx='80' cy='85' r='40' fill='none' stroke='#1a2b45'/><circle cx='120' cy='85' r='4' fill='#2b6be0'/><text x='80' y='150' font-size='10' text-anchor='middle' fill='#1a2b45'>Na 2,8,1</text><line x1='150' y1='85' x2='200' y2='85' stroke='#1a2b45' stroke-width='2'/><polygon points='200,85 191,81 191,89' fill='#1a2b45'/><circle cx='250' cy='85' r='7' fill='#e0552b'/><circle cx='250' cy='85' r='22' fill='none' stroke='#1a2b45'/><text x='250' y='150' font-size='10' text-anchor='middle' fill='#1a2b45'>Na⁺ 2,8</text></svg>","steps":[{"t":"Tek değerlik","a":"1 vermek kolay","d":"Sodyumun en dış katmanında 1 elektron vardır; bunu vermek 7 elektron almaktan çok daha kolaydır."},{"t":"Sonuç","a":"2, 8 oktet","d":"1 elektron verince alttaki dolu katman (2, 8) en dış katman olur ve oktete ulaşılır."}],"ans":"Sodyum tek değerlik elektronunu vererek alttaki dolu 2, 8 katmanını dış katman yapar ve kolayca oktete ulaşır."},
{"q":"Bir atomun değerlik elektronu sayısı ile oluşturacağı iyon yükü arasında nasıl bir ilişki vardır?","steps":[{"t":"1-3 değerlik","a":"verir, (+)","d":"En dış katmanında 1, 2 veya 3 elektron olan atom bunları verme eğilimindedir ve +1, +2, +3 yüklü olur."},{"t":"5-7 değerlik","a":"alır, (−)","d":"En dış katmanında 5, 6, 7 elektron olan atom oktete tamamlamak için elektron alır; −3, −2, −1 yüklü olur."}],"ans":"Az değerlikli atom elektron verip artı, oktete yakın atom elektron alıp eksi yüklü olur; yük değerlik sayısıyla belirlenir."},
{"q":"Klor (2, 8, 7) ve magnezyum (2, 8, 2) oktete ulaşmak için ne yapar?","steps":[{"t":"Klor","a":"1 e⁻ alır","d":"Klorun en dış katmanında 7 elektron vardır; 1 elektron alarak 2, 8, 8 oktetine ulaşır (Cl⁻)."},{"t":"Magnezyum","a":"2 e⁻ verir","d":"Magnezyumun en dış katmanında 2 elektron vardır; bunları vererek 2, 8 düzenine iner (Mg²⁺)."}],"ans":"Klor 1 elektron alarak Cl⁻ (2, 8, 8), magnezyum 2 elektron vererek Mg²⁺ (2, 8) olur; ikisi de oktete ulaşır."},
{"q":"Aynı grupta yer alan Li, Na ve K'nin benzer davranmasının nedeni katman dizilimiyle nasıl açıklanır?","steps":[{"t":"Ortak değerlik","a":"hepsi 1","d":"Li (2, 1), Na (2, 8, 1), K (2, 8, 8, 1) hepsinin en dış katmanında 1 değerlik elektronu vardır."},{"t":"Aynı eğilim","a":"hepsi 1 e⁻ verir","d":"Hepsi bu tek elektronu verip kararlı düzene ulaşır; bu yüzden hepsi benzer biçimde +1 yüklü iyon oluşturur."}],"ans":"Li, Na, K'nin tümünün değerlik elektronu 1 olduğundan birini verip +1 yüklü iyon oluşturur; benzer davranışları katman diziliminden gelir."}
]},"lise":{"kolay":[
{"q":"Bir atomun katman (kabuk) elektron dağılımı hangi sırayla yapılır?","fig":"<svg viewBox='0 0 300 185'><circle cx='150' cy='95' r='8' fill='#e0552b' stroke='#1a2b45'/><circle cx='150' cy='95' r='25' fill='none' stroke='#1a2b45'/><circle cx='150' cy='95' r='47' fill='none' stroke='#1a2b45'/><circle cx='150' cy='95' r='69' fill='none' stroke='#1a2b45'/><text x='150' y='78' font-size='9' text-anchor='middle' fill='#1a2b45'>K:2</text><text x='150' y='56' font-size='9' text-anchor='middle' fill='#1a2b45'>L:8</text><text x='150' y='34' font-size='9' text-anchor='middle' fill='#1a2b45'>M:8</text></svg>","steps":[{"t":"Düşük enerji","a":"içten dışa","d":"Elektronlar en düşük enerjili (çekirdeğe en yakın) katmandan başlayarak dışa doğru dizilir."},{"t":"Kapasite","a":"2, 8, 8","d":"K katmanına 2, L'ye 8, M'ye (temel düzeyde) 8 elektron sığacak şekilde sırayla doldurulur."}],"ans":"Elektronlar en düşük enerjili katmandan dışa doğru, 2, 8, 8 kapasitelerine göre sırayla dizilir."},
{"q":"Değerlik elektronu sayısı ile bir atomun kimyasal davranışı arasında nasıl bir ilişki vardır?","steps":[{"t":"Değerlik sayısı","a":"dış katman e⁻","d":"En dış katmandaki elektron sayısı atomun elektron alma/verme eğilimini belirler."},{"t":"Eğilim","a":"oktete yakınlık","d":"Az değerlikli atomlar elektron vermeye (metalik), oktete yakınlar almaya (ametalik) eğilimlidir."}],"ans":"Değerlik elektronu sayısı atomun elektron alma/verme eğilimini ve dolayısıyla kimyasal davranışını belirler."},
{"q":"Oktet kuralı nedir ve hangi atomlar için dublet geçerlidir?","steps":[{"t":"Oktet","a":"8 değerlik e⁻","d":"Atomlar en dış katmanlarında 8 elektrona ulaşarak soygaz düzenine (kararlılığa) erişme eğilimindedir."},{"t":"Dublet","a":"H, He","d":"Yalnız ilk katmanı kullanabilen küçük atomlar (H, He) 2 elektronla (dublet) kararlı olur."}],"ans":"Oktet en dış katmanda 8 elektronla kararlılıktır; H ve He gibi küçük atomlar için 2 elektronlu dublet geçerlidir."},
{"q":"Baş grup (A grubu) elementlerinde değerlik elektronu ile grup numarası arasındaki ilişki nedir?","steps":[{"t":"İlişki","a":"grup = değerlik","d":"Baş gruplarda grup numarası, atomun değerlik elektronu sayısına eşittir."},{"t":"Örnek","a":"2A → 2 e⁻","d":"1A grubunun 1, 2A grubunun 2, 7A grubunun 7 değerlik elektronu vardır."}],"ans":"Baş gruplarda grup numarası değerlik elektronu sayısına eşittir; örneğin 2A grubunun 2 değerlik elektronu vardır."},
{"q":"Kalsiyum (20 elektron) atomunun katman dağılımı nasıldır ve değerlik elektronu kaçtır?","steps":[{"t":"Dağılım","a":"2, 8, 8, 2","d":"20 elektron sırayla yerleşince 2 + 8 + 8 dolar, geriye 2 elektron kalır; dağılım 2, 8, 8, 2'dir."},{"t":"Değerlik","a":"2 elektron","d":"En dış katmanda (4. katman) 2 elektron vardır; değerlik elektronu sayısı 2'dir."}],"ans":"Kalsiyumun dağılımı 2, 8, 8, 2'dir; değerlik elektronu sayısı 2'dir."}
],"zor":[
{"q":"Sodyumun iyon oluşumunu katman dizilimi değişimiyle açıklayınız (Na → Na⁺).","fig":"<svg viewBox='0 0 320 175'><circle cx='80' cy='85' r='7' fill='#e0552b'/><circle cx='80' cy='85' r='20' fill='none' stroke='#1a2b45'/><circle cx='80' cy='85' r='38' fill='none' stroke='#1a2b45'/><circle cx='118' cy='85' r='4' fill='#2b6be0'/><text x='80' y='150' font-size='10' text-anchor='middle' fill='#1a2b45'>Na: 2,8,1</text><line x1='150' y1='85' x2='200' y2='85' stroke='#1a2b45' stroke-width='2'/><polygon points='200,85 191,81 191,89' fill='#1a2b45'/><circle cx='250' cy='85' r='7' fill='#e0552b'/><circle cx='250' cy='85' r='20' fill='none' stroke='#1a2b45'/><text x='250' y='150' font-size='10' text-anchor='middle' fill='#1a2b45'>Na⁺: 2,8</text></svg>","steps":[{"t":"Nötr dizilim","a":"2, 8, 1","d":"Nötr sodyumun dizilimi 2, 8, 1'dir; en dış katmanda 1 değerlik elektronu vardır."},{"t":"İyon dizilimi","a":"2, 8 → Na⁺","d":"1 elektron verince dizilim 2, 8 olur (neon düzeni); yük +1, yani Na⁺ olur."}],"ans":"Sodyum 1 elektron vererek dizilimini 2, 8, 1'den 2, 8'e indirir ve Na⁺ iyonu oluşturur."},
{"q":"S²⁻ iyonu (kükürt 16 elektron) kaç elektrona sahiptir ve dizilimi nedir?","steps":[{"t":"Elektron sayısı","a":"16 + 2 = 18","d":"Kükürt 16 elektronludur; −2 yüklü olması 2 elektron aldığını gösterir, toplam 18 elektron olur."},{"t":"Dizilim","a":"2, 8, 8","d":"18 elektron 2, 8, 8 şeklinde dizilir; bu argon ile izoelektronik kararlı düzendir."}],"ans":"S²⁻ iyonu 18 elektrona sahiptir ve dizilimi 2, 8, 8'dir (argon düzeni)."},
{"q":"Na⁺ ile Ne'nin izoelektronik olması ne anlama gelir?","steps":[{"t":"Tanım","a":"eşit elektron","d":"İzoelektronik tanecikler aynı elektron sayısı ve dizilimine sahiptir, proton sayıları farklı olabilir."},{"t":"Örnek","a":"Na⁺ ≡ Ne","d":"Na⁺ (10 elektron, 2, 8) ile Ne (10 elektron, 2, 8) aynı dizilime sahiptir; ikisi de izoelektroniktir."}],"ans":"Na⁺ ve Ne'nin ikisi de 10 elektronlu ve 2, 8 dizilimindedir; aynı elektron diziliminde olmaları onları izoelektronik yapar."},
{"q":"2. periyot ametalleri N, O ve F oktete ulaşmak için kaç elektron alır?","steps":[{"t":"Değerlik eksiği","a":"8 − değerlik","d":"Bir ametalin alacağı elektron sayısı, oktete tamamlamak için gereken eksik kadardır (8 − değerlik)."},{"t":"Karşılaştırma","a":"N:3, O:2, F:1","d":"Azot (2, 5) 3, oksijen (2, 6) 2, flor (2, 7) 1 elektron alarak sırasıyla N³⁻, O²⁻, F⁻ oluşturur."}],"ans":"Her ametal oktete eksiği kadar elektron alır: N 3 (N³⁻), O 2 (O²⁻), F 1 (F⁻) elektron alır."},
{"q":"Değerlik elektronu 4 olan karbon neden elektron alıp vermek yerine ortaklaşma (kovalent) eğilimindedir?","steps":[{"t":"Eşit zorluk","a":"4 ver/4 al zor","d":"4 değerlik elektronu için hem 4 elektron vermek hem 4 elektron almak enerjice çok güçtür."},{"t":"Çözüm","a":"ortaklaşma","d":"Karbon oktete ulaşmak için elektronları başka atomlarla paylaşır (kovalent bağ)."}],"ans":"4 değerlik elektronlu karbon, 4 elektron vermek de almak da çok zor olduğundan elektronları paylaşır (kovalent bağ kurar)."}
]}}};
