globalThis.__OUT = {"baglar":{"ilkokul":{"kolay":[
{"q":"Atomlar neden tek başına durmak yerine birbirine tutunur?","steps":[{"t":"Yalnız atom","a":"kararsız","d":"Çoğu atom tek başına rahat değildir, daha sağlam bir yapıya geçmek ister."},{"t":"Tutunma","a":"birleşir","d":"Atomlar birbirine tutunarak daha kararlı ve dayanıklı bir yapı oluşturur."}],"ans":"Atomlar daha kararlı (sağlam) bir yapıya ulaşmak için birbirine tutunur, yani bağ kurar."},
{"q":"İki atomun birleşip oluşturduğu yeni yapıya ne denir?","steps":[{"t":"Birleşme","a":"atomlar yan yana","d":"İki ya da daha çok atom bir araya gelip tutunur."},{"t":"Yeni yapı","a":"molekül","d":"Birbirine bağlı bu atom topluluğuna molekül denir."}],"ans":"Birbirine bağlanan atomların oluşturduğu yapıya molekül denir."},
{"q":"Su molekülünde kaç çeşit atom birleşmiştir?","fig":"<svg viewBox='0 0 320 170'><circle cx='160' cy='90' r='26' fill='#e0552b' stroke='#1a2b45'/><text x='160' y='95' font-size='14' text-anchor='middle' fill='#1a2b45'>O</text><circle cx='110' cy='60' r='16' fill='#cfd8e8' stroke='#1a2b45'/><text x='110' y='65' font-size='11' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='210' cy='60' r='16' fill='#cfd8e8' stroke='#1a2b45'/><text x='210' y='65' font-size='11' text-anchor='middle' fill='#1a2b45'>H</text><line x1='133' y1='75' x2='128' y2='68' stroke='#1a2b45' stroke-width='2'/><line x1='187' y1='75' x2='192' y2='68' stroke='#1a2b45' stroke-width='2'/><text x='160' y='150' font-size='11' text-anchor='middle' fill='#1a2b45'>su (H₂O)</text></svg>","steps":[{"t":"Atomlar","a":"hidrojen ve oksijen","d":"Su molekülünde hidrojen (H) ve oksijen (O) atomları bulunur."},{"t":"Sayı","a":"iki çeşit","d":"İki farklı çeşit atom (H ve O) birleşerek suyu oluşturur."}],"ans":"Su molekülünde hidrojen ve oksijen olmak üzere iki çeşit atom birleşmiştir."},
{"q":"Atomlar bağ kurarken hangi küçük tanecikleri kullanır?","steps":[{"t":"Dış tanecik","a":"elektron","d":"Atomun en dışındaki elektronlar bağ kurmada rol oynar."},{"t":"Paylaşım","a":"elektronlarla","d":"Atomlar bu dış elektronları vererek, alarak ya da paylaşarak tutunur."}],"ans":"Atomlar bağ kurarken en dıştaki elektronlarını kullanır."},
{"q":"Tuz (yemek tuzu) hangi iki atomun birleşmesiyle oluşur?","steps":[{"t":"Birinci atom","a":"sodyum","d":"Yemek tuzunda sodyum (Na) atomu bulunur."},{"t":"İkinci atom","a":"klor","d":"Sodyum, klor (Cl) atomu ile birleşerek tuzu (NaCl) oluşturur."}],"ans":"Yemek tuzu, sodyum (Na) ve klor (Cl) atomlarının birleşmesiyle oluşur."}
],"zor":[
{"q":"Bir atom dış elektronlarını tamamladığında ne kazanır?","steps":[{"t":"Tam dolu dış","a":"kararlı","d":"En dış katmanı dolduğunda atom daha sağlam, kararlı bir yapıya ulaşır."},{"t":"Bağ kurar","a":"birleşerek","d":"Bunu çoğu zaman başka atomlarla birleşip elektron paylaşarak ya da alıp vererek başarır."}],"ans":"Dış elektronlarını tamamlayan atom kararlı (sağlam) bir yapı kazanır."},
{"q":"Neden iki hidrojen atomu birleşip H₂ oluşturur?","fig":"<svg viewBox='0 0 320 160'><circle cx='120' cy='80' r='24' fill='#cfd8e8' stroke='#1a2b45'/><text x='120' y='85' font-size='13' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='200' cy='80' r='24' fill='#cfd8e8' stroke='#1a2b45'/><text x='200' y='85' font-size='13' text-anchor='middle' fill='#1a2b45'>H</text><line x1='144' y1='80' x2='176' y2='80' stroke='#1a2b45' stroke-width='3'/><text x='160' y='140' font-size='11' text-anchor='middle' fill='#1a2b45'>H₂</text></svg>","steps":[{"t":"Tek H zayıf","a":"yalnız kalmaz","d":"Tek bir hidrojen atomu kararlı değildir, eşleşmek ister."},{"t":"Paylaşım","a":"elektron ortak","d":"İki hidrojen elektronlarını paylaşarak birlikte daha kararlı bir yapı (H₂) kurar."}],"ans":"İki hidrojen atomu elektronlarını paylaşıp daha kararlı olduğu için birleşip H₂ oluşturur."},
{"q":"Bir atom elektron verir, diğeri alırsa nasıl bir bağ oluşur?","steps":[{"t":"Veren ve alan","a":"aktarım","d":"Bir atom elektronunu verir, diğer atom bu elektronu alır."},{"t":"Çekim","a":"zıt yükler","d":"Veren atom artı, alan atom eksi yüklenir; zıt yükler birbirini çeker ve bağ oluşur."}],"ans":"Bir atomun elektron verip diğerinin alması, zıt yüklerin birbirini çektiği bir bağ oluşturur."},
{"q":"Aynı atomlar mı yoksa farklı atomlar mı bir araya gelebilir, örnek ver?","steps":[{"t":"Aynı atomlar","a":"O₂ gibi","d":"Aynı çeşit atomlar birleşebilir; örneğin iki oksijen birleşip O₂ olur."},{"t":"Farklı atomlar","a":"H₂O gibi","d":"Farklı atomlar da birleşebilir; hidrojen ve oksijen birleşip suyu (H₂O) oluşturur."}],"ans":"Hem aynı (O₂) hem farklı (H₂O) atomlar bir araya gelip bağ kurabilir."},
{"q":"Soy gazlar neden başka atomlarla kolayca birleşmez?","steps":[{"t":"Dış katman","a":"zaten dolu","d":"Helyum, neon gibi soy gazların en dış katmanı zaten doludur."},{"t":"İhtiyaç yok","a":"kararlı","d":"Dış katmanları dolu olduğu için kararlıdırlar, başka atomla birleşmeye ihtiyaç duymazlar."}],"ans":"Soy gazların dış katmanı zaten dolu ve kararlı olduğundan başka atomlarla kolayca birleşmezler."}
]},"ortaokul":{"kolay":[
{"q":"Atomların bağ kurmasının temel amacı nedir?","steps":[{"t":"Kararsızlık","a":"dış katman eksik","d":"Çoğu atomun en dış katmanı (değerlik katmanı) tam dolu değildir, bu durum kararsızdır."},{"t":"Kararlı yapı","a":"dış katmanı tamamlamak","d":"Atom elektron alıp vererek ya da paylaşarak dış katmanını tamamlar ve kararlı hale gelir."}],"ans":"Atomlar, en dış katmanını tamamlayıp kararlı hale gelmek için bağ kurar."},
{"q":"Soy gaz (kararlı) elektron düzeni ne demektir?","fig":"<svg viewBox='0 0 320 175'><circle cx='160' cy='90' r='10' fill='#e0552b' stroke='#1a2b45'/><circle cx='160' cy='90' r='34' fill='none' stroke='#1a2b45'/><circle cx='160' cy='56' r='5' fill='#2b6be0'/><circle cx='194' cy='90' r='5' fill='#2b6be0'/><circle cx='160' cy='124' r='5' fill='#2b6be0'/><circle cx='126' cy='90' r='5' fill='#2b6be0'/><text x='160' y='162' font-size='10' text-anchor='middle' fill='#1a2b45'>dolu son katman</text></svg>","steps":[{"t":"Dolu katman","a":"8 (veya 2) elektron","d":"Son katmanında 8 elektron (ilk katmanda 2) bulunan düzen kararlıdır."},{"t":"Soy gaz benzeri","a":"hedef yapı","d":"Atomlar bağ kurarken en yakın soy gazın bu dolu düzenine ulaşmaya çalışır."}],"ans":"Soy gaz düzeni, son katmanın 8 (ilk katmanda 2) elektronla tam dolu olduğu kararlı elektron dizilimidir."},
{"q":"İyonik bağ hangi tür atomlar arasında oluşur?","steps":[{"t":"Taraflar","a":"metal + ametal","d":"İyonik bağ, bir metal ile bir ametal atom arasında oluşur."},{"t":"Elektron aktarımı","a":"ver-al","d":"Metal elektron verir (+ yüklenir), ametal elektron alır (− yüklenir); zıt iyonlar çekilir."}],"ans":"İyonik bağ, metal ile ametal arasında elektron aktarımıyla oluşur."},
{"q":"Kovalent bağ nasıl kurulur?","fig":"<svg viewBox='0 0 320 160'><circle cx='120' cy='80' r='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='120' y='85' font-size='13' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='200' cy='80' r='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='200' y='85' font-size='13' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='152' cy='80' r='5' fill='#2b6be0'/><circle cx='168' cy='80' r='5' fill='#2b6be0'/><text x='160' y='140' font-size='11' text-anchor='middle' fill='#1a2b45'>ortak elektron çifti</text></svg>","steps":[{"t":"Taraflar","a":"ametal + ametal","d":"Kovalent bağ genellikle iki ametal atom arasında oluşur."},{"t":"Paylaşım","a":"elektron ortaklığı","d":"Atomlar elektronlarını alıp vermek yerine ortak kullanarak (paylaşarak) bağ kurar."}],"ans":"Kovalent bağ, iki ametal atomun elektronlarını ortaklaşa kullanmasıyla kurulur."},
{"q":"NaCl bileşiğinde sodyum ve klorun yükleri ne olur?","steps":[{"t":"Sodyum","a":"Na⁺","d":"Sodyum 1 elektron vererek Na⁺ (artı yüklü) iyona dönüşür."},{"t":"Klor","a":"Cl⁻","d":"Klor bu elektronu alarak Cl⁻ (eksi yüklü) iyona dönüşür."}],"ans":"NaCl'de sodyum Na⁺, klor ise Cl⁻ yüküne sahip olur."}
],"zor":[
{"q":"Bir atomun kaç elektron alıp vereceğini ne belirler?","steps":[{"t":"Değerlik elektronu","a":"son katman sayısı","d":"En dış katmandaki (değerlik) elektron sayısı atomun davranışını belirler."},{"t":"Hedef düzen","a":"oktete ulaşmak","d":"Atom, son katmanı 8'e (oktet) tamamlamak için kaç elektrona ihtiyacı varsa o kadar alıp verir veya paylaşır."}],"ans":"Atomun son katmanındaki elektron sayısı, oktete ulaşmak için kaç elektron alıp vereceğini belirler."},
{"q":"İyonik bağlı bileşikler neden yüksek erime noktasına sahiptir?","steps":[{"t":"Güçlü çekim","a":"zıt iyon ağı","d":"İyonik katıda artı ve eksi iyonlar düzenli bir ağ (örgü) içinde güçlü çekimle tutulur."},{"t":"Çok enerji","a":"erimesi zor","d":"Bu güçlü çekimleri kırıp eritmek için yüksek sıcaklık (çok enerji) gerekir."}],"ans":"İyonik bileşiklerde zıt iyonlar arası çekim çok güçlü olduğundan erime noktaları yüksektir."},
{"q":"O₂ molekülündeki bağ tek bağ mıdır, açıklayın?","fig":"<svg viewBox='0 0 320 160'><circle cx='120' cy='80' r='28' fill='#e0552b' stroke='#1a2b45'/><text x='120' y='85' font-size='13' text-anchor='middle' fill='#fff'>O</text><circle cx='200' cy='80' r='28' fill='#e0552b' stroke='#1a2b45'/><text x='200' y='85' font-size='13' text-anchor='middle' fill='#fff'>O</text><line x1='148' y1='72' x2='172' y2='72' stroke='#1a2b45' stroke-width='3'/><line x1='148' y1='88' x2='172' y2='88' stroke='#1a2b45' stroke-width='3'/><text x='160' y='140' font-size='11' text-anchor='middle' fill='#1a2b45'>O=O çift bağ</text></svg>","steps":[{"t":"İhtiyaç","a":"2 elektron","d":"Her oksijen oktete ulaşmak için 2 elektron paylaşmalıdır."},{"t":"Çift bağ","a":"iki ortak çift","d":"Bu yüzden iki oksijen, iki ortak elektron çifti paylaşır; bu bir çift bağdır (O=O)."}],"ans":"Hayır; O₂'de oksijenler iki elektron çifti paylaştığı için aralarında çift bağ (O=O) vardır."},
{"q":"Polar ve apolar kovalent bağ arasındaki fark nedir?","steps":[{"t":"Apolar","a":"eşit paylaşım","d":"Aynı ya da çekim gücü eşit atomlar elektronu eşit paylaşırsa bağ apolardır (örneğin H₂)."},{"t":"Polar","a":"eşitsiz paylaşım","d":"Bir atom elektronu daha güçlü çekerse ortak çift ona kayar, bağ polar olur (örneğin H–Cl)."}],"ans":"Apolar bağda elektronlar eşit, polar bağda ise bir atoma daha yakın (eşitsiz) paylaşılır."},
{"q":"Metalik bağ diğer bağlardan hangi yönüyle ayrılır?","steps":[{"t":"Serbest elektron","a":"elektron denizi","d":"Metal atomları değerlik elektronlarını ortak bir 'elektron denizine' bırakır."},{"t":"Hareketli e⁻","a":"iletkenlik","d":"Bu serbest elektronlar tüm yapıda gezdiği için metaller elektriği ve ısıyı iyi iletir."}],"ans":"Metalik bağda değerlik elektronları serbestçe dolaşan bir 'elektron denizi' oluşturur; bu, metallere iletkenlik kazandırır."}
]},"lise":{"kolay":[
{"q":"Oktet kuralı nedir ve atomların bağ kurmasıyla nasıl ilişkilidir?","steps":[{"t":"Kural","a":"son katman 8","d":"Atomlar son katmanlarında 8 elektron (soy gaz düzeni) bulundurmaya eğilimlidir."},{"t":"Bağ ile ulaşma","a":"al-ver-paylaş","d":"Atom oktete ulaşmak için elektron alır, verir veya paylaşır; bu da bağ oluşumunu sağlar."}],"ans":"Oktet kuralı, atomların son katmanını 8 elektrona tamamlama eğilimidir; atomlar bunu bağ kurarak gerçekleştirir."},
{"q":"İyonik bağ oluşumunu Na ve Cl üzerinden açıklayınız.","fig":"<svg viewBox='0 0 320 175'><circle cx='95' cy='85' r='28' fill='#cfd8e8' stroke='#1a2b45'/><text x='95' y='90' font-size='13' text-anchor='middle' fill='#1a2b45'>Na</text><circle cx='225' cy='85' r='28' fill='#9ed9a8' stroke='#1a2b45'/><text x='225' y='90' font-size='13' text-anchor='middle' fill='#1a2b45'>Cl</text><line x1='124' y1='85' x2='194' y2='85' stroke='#2b6be0' stroke-width='2'/><polygon points='194,85 184,80 184,90' fill='#2b6be0'/><text x='159' y='72' font-size='10' text-anchor='middle' fill='#1a2b45'>e⁻ aktarımı</text><text x='159' y='160' font-size='11' text-anchor='middle' fill='#1a2b45'>Na⁺ + Cl⁻ → NaCl</text></svg>","steps":[{"t":"Elektron aktarımı","a":"Na → Cl","d":"Sodyum son katmanındaki 1 elektronu klora aktarır; Na⁺ ve Cl⁻ iyonları oluşur."},{"t":"Elektrostatik çekim","a":"zıt yük","d":"Zıt yüklü Na⁺ ve Cl⁻ iyonları arasındaki elektrostatik çekim iyonik bağı oluşturur."}],"ans":"Na bir elektronunu Cl'a aktarır; oluşan Na⁺ ve Cl⁻ iyonları elektrostatik çekimle iyonik bağ kurar (NaCl)."},
{"q":"Kovalent bağda bağ polaritesini ne belirler?","steps":[{"t":"Elektronegatiflik","a":"çekim gücü","d":"Bağ polaritesini atomların elektronegatiflik (ortak elektronu çekme gücü) farkı belirler."},{"t":"Fark etkisi","a":"büyük fark = polar","d":"Elektronegatiflik farkı büyüdükçe ortak çift bir atoma kayar ve bağ daha polar olur."}],"ans":"Kovalent bağda polariteyi atomların elektronegatiflik farkı belirler; fark büyüdükçe bağ polarlaşır."},
{"q":"H₂O molekülünün polar olmasının nedeni nedir?","fig":"<svg viewBox='0 0 320 175'><circle cx='160' cy='80' r='26' fill='#e0552b' stroke='#1a2b45'/><text x='160' y='85' font-size='13' text-anchor='middle' fill='#fff'>O</text><circle cx='110' cy='130' r='16' fill='#cfd8e8' stroke='#1a2b45'/><text x='110' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='210' cy='130' r='16' fill='#cfd8e8' stroke='#1a2b45'/><text x='210' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>H</text><line x1='142' y1='98' x2='120' y2='118' stroke='#1a2b45' stroke-width='2'/><line x1='178' y1='98' x2='200' y2='118' stroke='#1a2b45' stroke-width='2'/><text x='160' y='40' font-size='11' text-anchor='middle' fill='#1a2b45'>δ⁻</text><text x='95' y='160' font-size='11' fill='#1a2b45'>δ⁺</text><text x='215' y='160' font-size='11' fill='#1a2b45'>δ⁺</text></svg>","steps":[{"t":"Polar bağ","a":"O–H","d":"Oksijen hidrojenden daha elektronegatiftir; her O–H bağı polardır ve oksijen kısmi eksi (δ⁻) yüklenir."},{"t":"Açısal geometri","a":"dipoller toplanır","d":"Molekül açısal (~104,5°) olduğu için bağ dipolleri birbirini götürmez, net bir dipol oluşur."}],"ans":"H₂O'da polar O–H bağları açısal geometride birbirini götürmediği için molekül net dipole sahiptir, yani polardır."},
{"q":"Metalik bağ metallerin hangi fiziksel özelliklerini açıklar?","steps":[{"t":"Serbest elektronlar","a":"elektron denizi","d":"Metalik bağda değerlik elektronları kafes içinde serbestçe hareket eden bir 'elektron denizi' oluşturur."},{"t":"Özellikler","a":"iletkenlik, işlenebilirlik","d":"Hareketli elektronlar elektrik/ısı iletkenliğini; katmanların kayabilmesi dövülebilirlik ve tel haline gelmeyi sağlar."}],"ans":"Metalik bağdaki serbest elektronlar metallerin elektrik-ısı iletkenliğini, dövülebilirliğini ve parlaklığını açıklar."}
],"zor":[
{"q":"NH₃ molekülünde merkez azot atomunun bağ yapısını ve ortaklanmamış çiftini açıklayınız.","fig":"<svg viewBox='0 0 320 180'><circle cx='160' cy='80' r='26' fill='#5b6b85' stroke='#1a2b45'/><text x='160' y='85' font-size='13' text-anchor='middle' fill='#fff'>N</text><circle cx='100' cy='130' r='15' fill='#cfd8e8' stroke='#1a2b45'/><text x='100' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='160' cy='145' r='15' fill='#cfd8e8' stroke='#1a2b45'/><text x='160' y='150' font-size='10' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='220' cy='130' r='15' fill='#cfd8e8' stroke='#1a2b45'/><text x='220' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>H</text><line x1='142' y1='95' x2='110' y2='120' stroke='#1a2b45' stroke-width='2'/><line x1='160' y1='106' x2='160' y2='130' stroke='#1a2b45' stroke-width='2'/><line x1='178' y1='95' x2='210' y2='120' stroke='#1a2b45' stroke-width='2'/><circle cx='152' cy='52' r='3' fill='#2b6be0'/><circle cx='168' cy='52' r='3' fill='#2b6be0'/><text x='160' y='40' font-size='9' text-anchor='middle' fill='#1a2b45'>ortaklanmamış çift</text></svg>","steps":[{"t":"Bağ sayısı","a":"3 N–H bağı","d":"Azotun 5 değerlik elektronundan 3'ü, üç hidrojenle birer ortak çift oluşturur (3 kovalent bağ)."},{"t":"Ortaklanmamış çift","a":"1 çift kalır","d":"Geri kalan 2 elektron, azotta ortaklanmamış (yalnız) çift olarak kalır ve molekülü üçgen piramit yapar."}],"ans":"NH₃'te azot üç hidrojenle 3 kovalent bağ kurar; üzerinde kalan 1 ortaklanmamış çift molekülü üçgen piramit yapar."},
{"q":"Aynı atom sayısına sahip CO₂ apolar, H₂O polarken bunun nedeni nedir?","steps":[{"t":"Bağ dipolleri","a":"ikisinde de polar bağ","d":"Hem CO₂ hem H₂O polar bağlar içerir; fark molekül geometrisindedir."},{"t":"Geometri etkisi","a":"doğrusal vs açısal","d":"CO₂ doğrusal olduğundan zıt yönlü bağ dipolleri birbirini götürür (net dipol sıfır); H₂O açısal olduğundan dipoller toplanır."}],"ans":"CO₂ doğrusal geometride bağ dipollerini götürdüğü için apolar; H₂O açısal geometride dipoller toplandığı için polardır."},
{"q":"Hidrojen bağı nedir ve suyun yüksek kaynama noktasını nasıl açıklar?","fig":"<svg viewBox='0 0 320 175'><circle cx='90' cy='70' r='20' fill='#e0552b' stroke='#1a2b45'/><text x='90' y='75' font-size='11' text-anchor='middle' fill='#fff'>O</text><circle cx='130' cy='100' r='12' fill='#cfd8e8' stroke='#1a2b45'/><text x='130' y='104' font-size='9' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='220' cy='120' r='20' fill='#e0552b' stroke='#1a2b45'/><text x='220' y='125' font-size='11' text-anchor='middle' fill='#fff'>O</text><line x1='140' y1='105' x2='205' y2='118' stroke='#2b6be0' stroke-width='2' stroke-dasharray='4 3'/><text x='175' y='100' font-size='9' text-anchor='middle' fill='#1a2b45'>hidrojen bağı</text></svg>","steps":[{"t":"Tanım","a":"H ile F/O/N çekimi","d":"Hidrojen bağı; bir moleküldeki kısmi artı H'nin, komşu molekülün elektronegatif O/N/F atomuyla yaptığı güçlü çekimdir."},{"t":"Kaynama etkisi","a":"ekstra enerji","d":"Su molekülleri arası hidrojen bağlarını koparmak fazladan enerji gerektirdiğinden kaynama noktası beklenenden yüksektir."}],"ans":"Hidrojen bağı, kısmi artı H ile komşu O/N/F arası güçlü çekimdir; bu bağları koparmak ek enerji gerektirdiğinden suyun kaynama noktası yüksektir."},
{"q":"Bir kovalent bağın σ (sigma) mı π (pi) mı olduğunu ne belirler ve çift bağda dağılım nasıldır?","steps":[{"t":"Örtüşme türü","a":"eksenel vs yanal","d":"Orbitaller bağ ekseni boyunca uç uca örtüşürse σ, yanal örtüşürse π bağı oluşur."},{"t":"Çift bağ dağılımı","a":"1 σ + 1 π","d":"Çift bağ bir σ ve bir π bağından; üçlü bağ ise bir σ ve iki π bağından oluşur."}],"ans":"Eksenel (uç uca) örtüşme σ, yanal örtüşme π bağı verir; çift bağ 1 σ + 1 π, üçlü bağ 1 σ + 2 π şeklindedir."},
{"q":"İyonik ve kovalent bileşiklerin elektrik iletkenliği neden farklıdır?","steps":[{"t":"İyonik","a":"erimiş/çözeltide iletir","d":"İyonik bileşikler katı halde iletmez; ancak eridiğinde veya suda çözündüğünde serbest iyonlar yükü taşır."},{"t":"Kovalent","a":"genelde iletmez","d":"Kovalent (moleküler) bileşiklerde serbest iyon/elektron olmadığından genellikle elektriği iletmezler."}],"ans":"İyonik bileşikler eriyik/çözeltide serbest iyonlarla iletir; kovalent bileşiklerde yük taşıyıcı serbest iyon olmadığından genelde iletmezler."}
]}}};
