globalThis.__OUT = {"atomNedir":{"ilkokul":{"kolay":[
{"q":"Çevremizdeki her şeyi oluşturan çok küçük yapı taşının adı nedir?","fig":"<svg viewBox='0 0 320 160'><rect x='40' y='60' width='70' height='50' fill='#cfd8e8' stroke='#1a2b45'/><text x='75' y='130' font-size='11' text-anchor='middle' fill='#1a2b45'>madde</text><text x='150' y='90' font-size='16' text-anchor='middle' fill='#1a2b45'>→</text><circle cx='235' cy='75' r='8' fill='#e0552b'/><circle cx='255' cy='90' r='8' fill='#e0552b'/><circle cx='240' cy='98' r='8' fill='#e0552b'/><text x='240' y='130' font-size='11' text-anchor='middle' fill='#1a2b45'>atomlar</text></svg>","steps":[{"t":"Madde nedir","a":"yer kaplayan her şey","d":"Etrafımızda gördüğümüz su, taş, hava gibi yer kaplayan her şeye madde denir."},{"t":"Yapı taşı","a":"atom","d":"Bütün maddeler çok küçük yapı taşlarından oluşur ve bu yapı taşına atom denir."}],"ans":"Her şeyi oluşturan en küçük yapı taşına atom denir."},
{"q":"Atomlar büyük mü yoksa çok küçük müdür?","steps":[{"t":"Boyut","a":"çok küçük","d":"Atomlar gözle göremeyeceğimiz kadar küçüktür."},{"t":"Karşılaştırma","a":"toz tanesinden bile küçük","d":"Bir toz tanesinin içinde bile sayamayacağımız kadar çok atom vardır."}],"ans":"Atomlar gözle görülemeyecek kadar çok küçüktür."},
{"q":"Bir bardak suyun içinde atom var mıdır?","steps":[{"t":"Su da madde","a":"evet madde","d":"Su da bir maddedir, çünkü yer kaplar ve ağırlığı vardır."},{"t":"Atomdan oluşur","a":"su atomlardan oluşur","d":"Her madde gibi su da çok küçük atomlardan oluşur."}],"ans":"Evet, bir bardak su sayısız küçük atomdan oluşur."},
{"q":"Demir bir çivi ile tahta bir kalem aynı şeyden mi yapılmıştır?","steps":[{"t":"İkisi de madde","a":"madde","d":"Hem çivi hem kalem birer maddedir."},{"t":"Atomdan oluşur","a":"farklı atomlar","d":"İkisi de atomlardan oluşur ama içlerindeki atom türleri farklıdır."}],"ans":"İkisi de atomlardan oluşur, ama içlerindeki atom çeşitleri birbirinden farklıdır."},
{"q":"Atomları neden gözümüzle göremeyiz?","steps":[{"t":"Çok küçük","a":"gözle görülmez","d":"Atomlar gözümüzün seçebileceğinden çok daha küçüktür."},{"t":"Yardımcı araç","a":"özel mikroskop","d":"Atomları ancak çok güçlü özel araçlarla incelenebilir."}],"ans":"Atomlar gözle görülemeyecek kadar küçük olduğu için onları doğrudan göremeyiz."}
],"zor":[
{"q":"Bir kum tanesi mi yoksa bir atom mu daha küçüktür?","steps":[{"t":"Kum tanesi","a":"görülebilir","d":"Bir kum tanesini gözümüzle görebiliriz, demek ki çok küçük değildir."},{"t":"Atom","a":"çok daha küçük","d":"Atom, kum tanesinin içinde milyonlarca tanesi bulunan çok daha küçük bir yapıdır."}],"ans":"Atom, kum tanesinden çok çok daha küçüktür; bir kum tanesinde milyonlarca atom vardır."},
{"q":"Bir maddeyi küçük parçalara böle böle gidersek en sonunda neye ulaşırız?","steps":[{"t":"Bölme","a":"gittikçe küçülür","d":"Bir maddeyi sürekli daha küçük parçalara ayırabiliriz."},{"t":"En küçük parça","a":"atom","d":"En sonunda o maddenin özelliğini taşıyan en küçük yapı taşına, yani atoma ulaşırız."}],"ans":"Bir maddeyi böle böle gidince sonunda maddenin en küçük yapı taşı olan atoma ulaşırız."},
{"q":"Hava boş gibi görünür; havada atom var mıdır?","steps":[{"t":"Hava da madde","a":"evet","d":"Hava görünmese de yer kaplar ve bir maddedir; balonu şişirebilmemiz bunu gösterir."},{"t":"Atomdan oluşur","a":"gaz atomları","d":"Hava, gözle görülmeyen çok küçük atom ve taneciklerden oluşur."}],"ans":"Evet, boş görünse de hava çok küçük atom ve taneciklerden oluşur."},
{"q":"İnsan vücudu da atomlardan oluşur mu?","steps":[{"t":"Vücut madde","a":"madde","d":"Bizim vücudumuz da yer kaplar ve ağırlığı olan bir maddedir."},{"t":"Atomdan oluşur","a":"sayısız atom","d":"Kemiklerimiz, kanımız, derimiz hepsi sayısız küçük atomdan oluşur."}],"ans":"Evet, insan vücudu da sayısız küçük atomdan oluşur."},
{"q":"Bilim insanları çok eski zamanlardan beri atom hakkında ne düşünmüştür?","steps":[{"t":"Eski fikir","a":"en küçük parça","d":"Çok eski zamanlarda bile insanlar maddenin bölünemeyen en küçük bir parçası olabileceğini düşündü."},{"t":"Bugünkü bilgi","a":"atom","d":"Bugün bu en küçük yapı taşına atom diyoruz ve onu daha iyi tanıyoruz."}],"ans":"İnsanlar eskiden beri maddenin en küçük bir yapı taşı olduğunu düşünmüş; bugün ona atom diyoruz."}
]},"ortaokul":{"kolay":[
{"q":"Atom nedir ve maddeyle ilişkisi nasıldır?","steps":[{"t":"Tanım","a":"maddenin yapı taşı","d":"Atom, bütün maddeleri oluşturan en küçük temel yapı taşıdır."},{"t":"İlişki","a":"madde = atom topluluğu","d":"Her madde, bir araya gelmiş çok sayıda atomdan oluşur."}],"ans":"Atom, maddeyi oluşturan en küçük yapı taşıdır; tüm maddeler atomlardan meydana gelir."},
{"q":"Atomların boyutu hakkında ne söylenebilir?","steps":[{"t":"Ölçek","a":"son derece küçük","d":"Atomlar metrenin milyarda biri mertebesinde, gözle görülemeyecek kadar küçüktür."},{"t":"Sonuç","a":"çıplak gözle görülmez","d":"Bu yüzden tek bir atomu çıplak gözle ya da sıradan mikroskopla göremeyiz."}],"ans":"Atomlar son derece küçüktür; tek bir atom çıplak gözle görülemez."},
{"q":"Saf altın ile saf bakır farklı maddelerdir; bu farkın temel nedeni nedir?","steps":[{"t":"Yapı taşı","a":"atom","d":"İki madde de atomlardan oluşur."},{"t":"Atom türü farkı","a":"farklı atomlar","d":"Altını altın yapan atomlar ile bakırı bakır yapan atomlar birbirinden farklı türdedir."}],"ans":"Altın ve bakır farklıdır çünkü onları oluşturan atom türleri birbirinden farklıdır."},
{"q":"Maddenin katı, sıvı ve gaz hâllerinin hepsi atomlardan mı oluşur?","steps":[{"t":"Hâller","a":"katı-sıvı-gaz","d":"Buz, su ve su buharı aynı maddenin üç farklı hâlidir."},{"t":"Ortak yapı","a":"hepsi atom","d":"Hangi hâlde olursa olsun madde yine atom ve taneciklerden oluşur; değişen taneciklerin diziliş ve hareketidir."}],"ans":"Evet, maddenin katı, sıvı ve gaz hâllerinin hepsi atomlardan oluşur; sadece taneciklerin düzeni değişir."},
{"q":"Bir maddeyi gittikçe daha küçük parçalara ayırdığımızda en küçük birim ne olur?","steps":[{"t":"Bölme süreci","a":"küçülen parçalar","d":"Bir maddeyi parçalara ayırdıkça parçalar küçülür."},{"t":"Sınır","a":"atom","d":"O maddenin kimyasal özelliğini taşıyan en küçük birime ulaşırız; bu birim atomdur."}],"ans":"Bir maddeyi bölmenin ulaşabileceği en küçük yapı taşı atomdur."}
],"zor":[
{"q":"Atomlar bu kadar küçükken bir maddeyi gözle görebilmemiz nasıl açıklanır?","steps":[{"t":"Tek atom","a":"görülemez","d":"Tek bir atom gözle görülemeyecek kadar küçüktür."},{"t":"Çok sayıda atom","a":"birikince görünür","d":"Görebildiğimiz en küçük madde parçasında bile sayılamayacak kadar çok atom bir aradadır; bu yığın gözle görünür."}],"ans":"Tek atom görülmez; ancak çok sayıda atom bir araya geldiğinde oluşan madde yığını gözle görülebilir hale gelir."},
{"q":"'Her şey atomlardan oluşur' ifadesi neyi kapsar?","steps":[{"t":"Kapsam","a":"tüm maddeler","d":"Canlı-cansız, katı-sıvı-gaz fark etmeksizin bütün maddeler atomlardan oluşur."},{"t":"İstisna düşüncesi","a":"madde olmayan","d":"Işık ya da ses gibi madde olmayan şeyler atomlardan oluşmaz; ifade yalnızca maddeler için geçerlidir."}],"ans":"İfade bütün maddeleri (canlı-cansız her türlü maddeyi) kapsar; ışık-ses gibi madde olmayanları kapsamaz."},
{"q":"Aynı tür atomlardan ve farklı tür atomlardan oluşan maddeler arasındaki fark nedir?","steps":[{"t":"Tek tür atom","a":"element","d":"Yalnızca tek çeşit atomdan oluşan saf maddeye element denir (örneğin demir)."},{"t":"Farklı tür atom","a":"bileşik","d":"Birbirine bağlanmış farklı türde atomlardan oluşan maddeye ise bileşik denir (örneğin su)."}],"ans":"Tek tür atomdan oluşan madde element, farklı tür atomların birleşmesiyle oluşan madde ise bileşiktir."},
{"q":"Bir demir çubuğu eritip şeklini değiştirdiğimizde atomlarına ne olur?","steps":[{"t":"Erime","a":"hâl değişimi","d":"Erime, maddenin katıdan sıvıya geçtiği fiziksel bir değişimdir."},{"t":"Atomlar","a":"değişmez","d":"Demir atomları erime sırasında yok olmaz ya da başka atoma dönüşmez; yalnızca dizilişleri ve hareketleri değişir."}],"ans":"Erimede demir atomları değişmez; yalnızca taneciklerin düzeni ve hareketi değiştiği için demir yine demir kalır."},
{"q":"Atomun var olduğu fikrine bilim nasıl ulaşmıştır?","steps":[{"t":"Gözlem ve deney","a":"dolaylı kanıt","d":"Bilim insanları maddenin davranışını gözleyip deneyler yaparak atomun varlığına dair kanıtlar buldu."},{"t":"Model geliştirme","a":"atom modeli","d":"Bu kanıtlardan yola çıkarak maddenin atomlardan oluştuğu fikrini açıklayan modeller geliştirdiler."}],"ans":"Bilim, maddenin davranışını açıklayan deney ve gözlemlerden yola çıkarak atomun varlığı fikrine ulaşmıştır."}
]},"lise":{"kolay":[
{"q":"Modern kimyada atom nasıl tanımlanır ve neden 'temel yapı taşı' sayılır?","steps":[{"t":"Tanım","a":"elementin en küçük birimi","d":"Atom, bir elementin kimyasal özelliğini taşıyan ve kimyasal yollarla daha basit parçalara ayrılamayan en küçük birimidir."},{"t":"Temel yapı taşı","a":"madde inşası","d":"Tüm maddeler atomların belirli düzen ve sayılarda bir araya gelmesiyle oluştuğu için atom maddenin temel yapı taşı kabul edilir."}],"ans":"Atom, bir elementin kimyasal özelliğini taşıyan en küçük birimdir; tüm maddeler atomlardan oluştuğu için temel yapı taşıdır."},
{"q":"Atomun büyüklük mertebesi nedir ve bu neden günlük deneyimimize ters görünür?","steps":[{"t":"Boyut mertebesi","a":"yaklaşık 10⁻¹⁰ m","d":"Bir atomun çapı yaklaşık 0,1 nanometre (10⁻¹⁰ m) düzeyindedir."},{"t":"Günlük algı","a":"sürekli madde","d":"Atomlar çok küçük ve çok sayıda olduğundan madde bize boşluksuz ve sürekli görünür; oysa tanecikli yapıdadır."}],"ans":"Atom yaklaşık 10⁻¹⁰ m çapındadır; bu kadar küçük ve çok sayıda olduğu için madde bize sürekli (tanecikli olmayan) görünür."},
{"q":"Atom ile molekül kavramları arasındaki ilişki nedir?","fig":"<svg viewBox='0 0 320 160'><circle cx='70' cy='80' r='16' fill='#e0552b' stroke='#1a2b45'/><text x='70' y='130' font-size='11' text-anchor='middle' fill='#1a2b45'>atom</text><circle cx='210' cy='80' r='16' fill='#e0552b' stroke='#1a2b45'/><circle cx='180' cy='100' r='11' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='240' cy='100' r='11' fill='#cfd8e8' stroke='#1a2b45'/><line x1='210' y1='80' x2='180' y2='100' stroke='#1a2b45'/><line x1='210' y1='80' x2='240' y2='100' stroke='#1a2b45'/><text x='210' y='135' font-size='11' text-anchor='middle' fill='#1a2b45'>molekül (H₂O)</text></svg>","steps":[{"t":"Atom","a":"temel birim","d":"Atom, maddenin kimyasal kimliğini taşıyan en küçük yapı taşıdır."},{"t":"Molekül","a":"bağlı atom grubu","d":"Molekül, iki ya da daha çok atomun kimyasal bağlarla birleşmesiyle oluşan tanecik grubudur (örneğin H₂O, O₂)."}],"ans":"Atom maddenin temel yapı taşıdır; molekül ise birden çok atomun kimyasal bağlarla birleşmesiyle oluşan tanecik grubudur."},
{"q":"'Madde tanecikli yapıdadır' ifadesi atom kavramıyla nasıl ilişkilendirilir?","steps":[{"t":"Tanecikli yapı","a":"boşluklu","d":"Madde sürekli değil, tanecikler ve aralarındaki boşluklardan oluşur."},{"t":"Taneciklerin temeli","a":"atom","d":"Bu taneciklerin temelinde atomlar bulunur; atomlar tek başına ya da molekül/iyon halinde maddeyi oluşturur."}],"ans":"Madde sürekli değil tanecikli ve boşlukludur; bu taneciklerin temelinde maddenin yapı taşı olan atomlar bulunur."},
{"q":"Bir element örneği ile o elementi oluşturan atom arasındaki fark nedir?","steps":[{"t":"Element örneği","a":"makroskobik madde","d":"Elinizdeki bir parça bakır, gözle görülen, ölçülebilen makroskobik bir madde örneğidir."},{"t":"Atom","a":"mikroskobik yapı taşı","d":"O bakır parçasını oluşturan tek bir bakır atomu ise gözle görülemeyen mikroskobik yapı taşıdır."}],"ans":"Element örneği gözle görülen makroskobik maddedir; atom ise o maddeyi oluşturan, görülemeyen mikroskobik yapı taşıdır."}
],"zor":[
{"q":"Bir kömür parçasının kütlesinin tamamına yakını karbon atomlarındaysa, kütle ile atom sayısı arasındaki ilişki nasıl kurulur?","steps":[{"t":"Mol kavramı","a":"6,02·10²³ tane","d":"1 mol madde 6,02·10²³ tanecik (atom) içerir; bu Avogadro sayısıdır."},{"t":"Kütle-tane ilişkisi","a":"mol üzerinden","d":"12 g karbon yaklaşık 1 mol, yani 6,02·10²³ karbon atomu demektir; kütle arttıkça atom sayısı orantılı artar."}],"ans":"Kütle ile atom sayısı mol üzerinden ilişkilidir; örneğin 12 g karbon ≈ 1 mol = 6,02·10²³ atom içerir."},
{"q":"Atomlar gözle görülemezken atomun varlığına dair bilimsel güven neye dayanır?","steps":[{"t":"Dolaylı kanıtlar","a":"tutarlı deneyler","d":"Sabit oranlar yasası, katlı oranlar ve gaz davranışları gibi pek çok deney atom varsayımıyla tutarlı sonuçlar verir."},{"t":"Doğrudan görüntüleme","a":"taramalı mikroskop","d":"Taramalı tünelleme mikroskobu gibi ileri tekniklerle atomların konumları günümüzde görüntülenebilmektedir."}],"ans":"Atomun varlığı hem onunla tutarlı çok sayıda deneye hem de ileri mikroskoplarla elde edilen doğrudan görüntülere dayanır."},
{"q":"'Atom kimyasal yolla bölünemez' denir; bu ifade ile çekirdek tepkimeleri nasıl bağdaştırılır?","steps":[{"t":"Kimyasal sınır","a":"elektron düzeyi","d":"Kimyasal tepkimeler atomların elektronlarını ilgilendirir; atomun çekirdek kimliği değişmez, dolayısıyla atom kimyasal yolla bölünmez sayılır."},{"t":"Çekirdek tepkimesi","a":"farklı süreç","d":"Çekirdek tepkimelerinde proton/nötron sayısı değişir ve atom başka elemente dönüşebilir; ancak bu kimyasal değil nükleer bir süreçtir."}],"ans":"Atom kimyasal yolla bölünemez; bölünme yalnızca çekirdeği değiştiren nükleer (kimyasal olmayan) tepkimelerde gerçekleşir."},
{"q":"Maddenin korunumu ilkesi, atom kavramıyla nasıl temellendirilir?","steps":[{"t":"İlke","a":"kütle korunur","d":"Kimyasal bir tepkimede toplam kütle değişmez; tepken kütlesi ürün kütlesine eşittir."},{"t":"Atom temeli","a":"atom sayısı sabit","d":"Çünkü tepkimede atomlar yok olmaz ya da yoktan var olmaz; yalnızca yeniden düzenlenir, böylece atom türü ve sayısı korunur."}],"ans":"Kütle korunur çünkü kimyasal tepkimede atomlar yok olmayıp yalnızca yeniden düzenlenir; atom türü ve sayısı sabit kalır."},
{"q":"Evrendeki çeşitliliğe rağmen sınırlı sayıda atom türünün bu kadar farklı maddeyi oluşturabilmesi nasıl açıklanır?","steps":[{"t":"Sınırlı tür","a":"elementler","d":"Doğada görece az sayıda farklı atom türü (element) vardır."},{"t":"Kombinasyon","a":"çok sayıda dizilim","d":"Bu atomların farklı sayı, oran ve düzenlerde birleşmesi sayısız farklı madde oluşturur; tıpkı az sayıda harften sonsuz kelime kurulması gibi."}],"ans":"Sınırlı sayıda atom türü, farklı sayı ve düzenlerde birleşerek sayısız madde oluşturur; çeşitlilik bağlanma kombinasyonlarından doğar."}
]}}};
