globalThis.__OUT = {"enerjiPiramidi":{"ilkokul":{"kolay":[
{"q":"Enerji piramidi nedir? Kısaca açıkla.","steps":[{"t":"Piramidin şekli","a":"alttan geniş","d":"Enerji piramidi, altı geniş üstü dar olan üçgene benzer bir şekildir."},{"t":"Ne gösterir","a":"besindeki enerji","d":"Her basamakta canlılardaki enerjinin ne kadar olduğunu gösterir."}],"ans":"Enerji piramidi, besin basamaklarındaki canlıların enerjisini gösteren, alttan geniş üstten dar bir şekildir."},
{"q":"Enerji piramidinin en altında hangi canlılar bulunur?","steps":[{"t":"Besini kim üretir","a":"bitkiler","d":"Bitkiler güneş ışığıyla kendi besinini üretir."},{"t":"En alt basamak","a":"üreticiler","d":"Besini üreten bitkiler piramidin en altında, en geniş yerde bulunur."}],"ans":"Enerji piramidinin en altında besin üreten bitkiler (üreticiler) bulunur."},
{"q":"Enerji piramidinde yukarı çıktıkça enerji nasıl değişir?","steps":[{"t":"Alt basamak","a":"çok enerji","d":"En altta, bitkilerde en çok enerji vardır."},{"t":"Yukarı çıkınca","a":"enerji azalır","d":"Bir üst basamağa çıkıldıkça enerji azalır."}],"ans":"Enerji piramidinde yukarı çıkıldıkça enerji azalır."},
{"q":"Çimen → çekirge → kuş sıralamasında en çok enerji hangisindedir?","steps":[{"t":"En alttaki canlı","a":"çimen","d":"Çimen bitkidir ve kendi besinini üretir, en altta bulunur."},{"t":"En çok enerji","a":"çimende","d":"En alttaki canlıda en çok enerji olur, o da çimendir."}],"ans":"Bu sıralamada en çok enerji en alttaki çimende bulunur."},
{"q":"Neden enerji piramidinin üstüne doğru daha az hayvan olur?","steps":[{"t":"Yukarıda enerji","a":"az enerji","d":"Yukarı çıkınca besindeki enerji azalır."},{"t":"Sonuç","a":"az hayvan beslenir","d":"Az enerji, daha az hayvanı doyurabilir, bu yüzden üstte az canlı olur."}],"ans":"Yukarıda enerji az olduğu için daha az hayvanı doyurur, bu yüzden üstte canlı sayısı azdır."}
],"zor":[
{"q":"Bir enerji piramidinde aslan neden en üstte, az sayıda bulunur?","steps":[{"t":"Aslan ne yer","a":"başka hayvan","d":"Aslan etçildir, başka hayvanları yiyerek beslenir."},{"t":"Yukarıdaki enerji","a":"çok azalmış","d":"En üste gelene kadar enerji basamak basamak azalır."},{"t":"Sonuç","a":"az aslan","d":"Az enerji olduğu için çok az aslan beslenebilir."}],"ans":"En üste çıkana kadar enerji çok azaldığı için aslan en üstte ve az sayıda bulunur."},
{"q":"Bir bitkinin enerjisinin tamamı onu yiyen tavşana geçer mi?","steps":[{"t":"Bitkinin enerjisi","a":"çok enerji","d":"Bitkide güneşten gelen bol enerji vardır."},{"t":"Tavşana geçen","a":"az kısmı","d":"Tavşan bitkiyi yer ama enerjinin sadece küçük bir kısmını alabilir."},{"t":"Kaybolan enerji","a":"ısı olarak","d":"Enerjinin çoğu hareket ve ısı olarak kaybolur."}],"ans":"Hayır; bitkinin enerjisinin sadece küçük bir kısmı tavşana geçer, çoğu kaybolur."},
{"q":"Neden çok uzun bir besin zinciri (10 basamaklı) doğada zor görülür?","steps":[{"t":"Her basamakta","a":"enerji azalır","d":"Her yukarı basamakta enerjinin çoğu kaybolur."},{"t":"Çok basamak sonra","a":"enerji biter","d":"Çok basamak çıkılırsa en üstte beslenecek enerji kalmaz."},{"t":"Sonuç","a":"zincir kısadır","d":"Bu yüzden besin zincirleri genelde kısadır."}],"ans":"Her basamakta enerji azaldığı için çok uzun zincirde üstte enerji kalmaz, bu yüzden zincir kısa olur."},
{"q":"Çayırdaki otların enerjisi nereden gelir ve sonra nereye gider?","steps":[{"t":"Otların enerjisi","a":"güneşten","d":"Otlar güneş ışığını kullanarak enerji elde eder."},{"t":"Otu yiyen","a":"otçul hayvan","d":"Otları inek veya tavşan gibi otçul hayvanlar yer."},{"t":"Enerjinin yönü","a":"yukarı taşınır","d":"Enerji otçuldan onu yiyen etçile doğru taşınır."}],"ans":"Otların enerjisi güneşten gelir, sonra otu yiyen hayvanlara ve onları yiyen hayvanlara taşınır."},
{"q":"Enerji piramidinde en üstteki canlı ölünce enerjisi tamamen yok mu olur?","steps":[{"t":"Ölen canlı","a":"çürür","d":"Ölen canlının bedeni toprakta çürür."},{"t":"Çürütücüler","a":"ayrıştırıcılar","d":"Bakteri ve mantarlar bedeni parçalayıp enerjisinden yararlanır."},{"t":"Sonuç","a":"yok olmaz","d":"Enerji yok olmaz, çürütücülere ve toprağa geçer."}],"ans":"Hayır; ölen canlının enerjisi çürütücülere (ayrıştırıcılara) ve toprağa geçer, tamamen yok olmaz."}
]},"ortaokul":{"kolay":[
{"q":"Enerji piramidinde her basamağa ne ad verilir?","steps":[{"t":"Basamağın adı","a":"trofik düzey","d":"Besin piramidindeki her bir beslenme basamağına trofik düzey denir."},{"t":"Sıralama","a":"üretici en altta","d":"En alt trofik düzey üreticiler, üstte ise tüketicilerdir."}],"ans":"Enerji piramidindeki her beslenme basamağına trofik düzey denir."},
{"q":"Enerji piramidinde üreticiler hangi trofik düzeydedir?","steps":[{"t":"Üreticiler","a":"bitkiler","d":"Üreticiler fotosentez yapan bitkilerdir."},{"t":"Düzeyi","a":"birinci trofik","d":"Besini üretip zinciri başlattıkları için ilk (birinci) trofik düzeydedir."}],"ans":"Üreticiler enerji piramidinin birinci (en alt) trofik düzeyinde yer alır."},
{"q":"Bir trofik düzeyden diğerine geçerken enerjinin yaklaşık ne kadarı aktarılır?","steps":[{"t":"Aktarım oranı","a":"yaklaşık %10","d":"Bir basamaktan üstüne enerjinin yaklaşık %10'u aktarılır."},{"t":"Kalan kısım","a":"%90 kaybolur","d":"Geri kalan yaklaşık %90'lık enerji kaybolur."}],"ans":"Bir trofik düzeyden bir üstüne enerjinin yaklaşık %10'u aktarılır."},
{"q":"Enerji piramidinde kaybolan enerji çoğunlukla hangi şekilde dışarı atılır?","steps":[{"t":"Solunum ve hareket","a":"enerji harcanır","d":"Canlılar solunum ve hareket için enerji harcar."},{"t":"Dışarı atılan biçim","a":"ısı","d":"Harcanan bu enerjinin büyük kısmı ısı olarak ortama yayılır."}],"ans":"Trofik düzeyler arasında kaybolan enerji çoğunlukla ısı olarak dışarı atılır."},
{"q":"Neden enerji piramidi yukarı doğru daralan bir şekle sahiptir?","steps":[{"t":"Alt basamak","a":"çok enerji","d":"En altta üreticilerde en fazla enerji bulunur."},{"t":"Yukarı çıkınca","a":"enerji azalır","d":"Her basamakta enerji azaldığı için üst basamaklar daha küçük çizilir."}],"ans":"Her trofik düzeyde enerji azaldığı için piramit yukarı doğru daralan bir şekle sahiptir."}
],"zor":[
{"q":"Bir üreticide 10000 birim enerji varsa, birincil tüketiciye yaklaşık ne kadarı geçer?","steps":[{"t":"Aktarım kuralı","a":"%10 kuralı","d":"Bir üst düzeye enerjinin yaklaşık %10'u aktarılır."},{"t":"Hesap","a":"10000 × 0,10","d":"10000 biriminin %10'u: 10000 × 0,10 = 1000 birim."},{"t":"Sonuç","a":"1000 birim","d":"Birincil tüketiciye yaklaşık 1000 birim enerji geçer."}],"ans":"Üreticideki 10000 birim enerjinin %10'u, yani yaklaşık 1000 birim birincil tüketiciye geçer."},
{"q":"%10 kuralına göre üç basamak çıkıldığında enerji kaç katına iner? (üretici 1000 birim)","steps":[{"t":"1. tüketici","a":"100 birim","d":"1000 biriminin %10'u: 1000 × 0,10 = 100 birim."},{"t":"2. tüketici","a":"10 birim","d":"100 biriminin %10'u: 100 × 0,10 = 10 birim."},{"t":"3. tüketici","a":"1 birim","d":"10 biriminin %10'u: 10 × 0,10 = 1 birim."}],"ans":"Üç basamak çıkıldığında 1000 birim enerji 1 birime, yani binde birine iner."},
{"q":"Biyokütle piramidi nedir ve neyi gösterir?","steps":[{"t":"Biyokütle anlamı","a":"canlı kütlesi","d":"Biyokütle, bir trofik düzeydeki canlıların toplam ağırlığıdır."},{"t":"Piramidin gösterdiği","a":"kütle azalması","d":"Yukarı çıktıkça toplam canlı kütlesinin azaldığını gösterir."}],"ans":"Biyokütle piramidi, her trofik düzeydeki canlıların toplam kütlesini gösterir ve yukarı çıkınca bu kütle azalır."},
{"q":"Sayı piramidi ile enerji piramidi arasındaki fark nedir?","steps":[{"t":"Sayı piramidi","a":"birey sayısı","d":"Sayı piramidi her düzeydeki canlı sayısını gösterir."},{"t":"Enerji piramidi","a":"enerji miktarı","d":"Enerji piramidi her düzeydeki enerji miktarını gösterir."},{"t":"Fark","a":"farklı ölçüm","d":"Biri canlı sayısını, diğeri enerjiyi ölçer; sayı bazen yanıltabilir."}],"ans":"Sayı piramidi canlı sayısını, enerji piramidi ise enerji miktarını gösterir; ikisi farklı şeyler ölçer."},
{"q":"Bir besin zinciri neden genellikle 4-5 basamaktan uzun olmaz?","steps":[{"t":"Her basamakta kayıp","a":"%90 kaybolur","d":"Her trofik düzeyde enerjinin yaklaşık %90'ı kaybolur."},{"t":"Üst basamaklarda","a":"çok az enerji","d":"4-5 basamak sonra geriye yetecek enerji kalmaz."},{"t":"Sonuç","a":"zincir kısalır","d":"Beslenecek enerji bulunmadığı için zincir daha fazla uzayamaz."}],"ans":"Her basamakta enerjinin çoğu kaybolduğu için 4-5 basamak sonra yetecek enerji kalmaz; bu yüzden zincir kısa olur."}
]},"lise":{"kolay":[
{"q":"Ekolojik piramit kavramını tanımlayınız.","steps":[{"t":"Tanım","a":"grafiksel gösterim","d":"Ekolojik piramit, trofik düzeyler arasındaki enerji, biyokütle veya birey sayısının grafiksel gösterimidir."},{"t":"Genel şekil","a":"yukarı daralan","d":"Çoğunlukla üreticiden üst tüketiciye doğru daralan bir biçim alır."}],"ans":"Ekolojik piramit, trofik düzeylerdeki enerji, biyokütle ya da birey sayısını gösteren ve genelde yukarı daralan grafiksel gösterimdir."},
{"q":"Trofik düzey nedir ve nasıl numaralandırılır?","steps":[{"t":"Tanım","a":"beslenme basamağı","d":"Trofik düzey, bir canlının besin zincirindeki beslenme konumudur."},{"t":"Numaralandırma","a":"üreticiden başlar","d":"Üreticiler 1. düzey, otçullar 2., birincil etçiller 3. düzeydir."}],"ans":"Trofik düzey, bir canlının besin zincirindeki beslenme basamağıdır; üreticiden (1. düzey) başlayarak numaralanır."},
{"q":"%10 enerji aktarım kuralının (Lindeman kuralı) içeriği nedir?","steps":[{"t":"Kural","a":"yaklaşık %10 aktarım","d":"Bir trofik düzeydeki enerjinin yalnızca yaklaşık %10'u bir üst düzeye aktarılır."},{"t":"Kayıp","a":"%90 kayıp","d":"Geri kalan %90, solunum, hareket ve ısı yoluyla kaybolur."}],"ans":"%10 kuralına göre bir trofik düzeydeki enerjinin yalnızca yaklaşık %10'u bir üst düzeye aktarılır, kalanı kaybolur."},
{"q":"Enerji piramidi neden her zaman düz (yukarı daralan) bir şekildedir?","steps":[{"t":"Termodinamik kayıp","a":"enerji azalır","d":"Her trofik düzeyde enerjinin büyük kısmı ısı olarak kaybolduğu için enerji azalır."},{"t":"Tersine dönemez","a":"alt > üst","d":"Üst düzey alttan fazla enerjiye sahip olamaz, bu yüzden piramit ters dönmez."}],"ans":"Enerji her basamakta azaldığı ve üst düzey alttakinden fazla enerji içeremeyeceği için enerji piramidi daima yukarı daralan biçimdedir."},
{"q":"Birincil üretici, birincil tüketici ve ikincil tüketici terimlerini açıklayınız.","steps":[{"t":"Birincil üretici","a":"ototrof","d":"Fotosentezle besin üreten canlılardır (1. trofik düzey)."},{"t":"Birincil tüketici","a":"otçul","d":"Üreticilerle beslenen otçul canlılardır (2. trofik düzey)."},{"t":"İkincil tüketici","a":"etçil","d":"Otçulları yiyen etçil canlılardır (3. trofik düzey)."}],"ans":"Birincil üretici fotosentez yapan ototrof, birincil tüketici otçul, ikincil tüketici ise otçulla beslenen etçildir."},
{"q":"Brüt birincil üretim (GPP) ile net birincil üretim (NPP) arasındaki fark nedir?","steps":[{"t":"GPP","a":"toplam üretim","d":"Brüt birincil üretim, üreticilerin fotosentezle ürettiği toplam organik maddedir."},{"t":"NPP","a":"GPP − solunum","d":"Net birincil üretim, GPP'den üreticinin solunum kaybı çıkarılınca kalan miktardır."}],"ans":"GPP üreticinin toplam organik üretimi, NPP ise bundan solunum kaybı çıkarıldıktan sonra kalan, üst düzeylere aktarılabilen üretimdir."},
{"q":"Biyokütle piramidi neyi ölçer ve hangi birimlerle ifade edilir?","steps":[{"t":"Ölçtüğü","a":"kuru kütle","d":"Her trofik düzeydeki canlıların birim alandaki toplam (genellikle kuru) kütlesini ölçer."},{"t":"Birim","a":"g/m² gibi","d":"Genellikle g/m² veya kg/hektar gibi birim alan başına kütle olarak verilir."}],"ans":"Biyokütle piramidi her trofik düzeydeki canlıların birim alandaki toplam kütlesini ölçer ve g/m² gibi birimlerle ifade edilir."},
{"q":"Sayı piramidi nedir ve hangi durumda yanıltıcı olabilir?","steps":[{"t":"Tanım","a":"birey sayısı","d":"Sayı piramidi her trofik düzeydeki birey sayısını gösterir."},{"t":"Yanıltıcı durum","a":"büyük üretici","d":"Tek bir büyük ağaç çok sayıda böceği beslerse alt basamak dar görünebilir."}],"ans":"Sayı piramidi her düzeydeki birey sayısını gösterir; tek bir büyük üreticinin çok tüketiciyi beslediği durumda ters/yanıltıcı görünebilir."},
{"q":"Enerji piramidinde enerjinin tek yönlü aktığını söylemek ne demektir?","steps":[{"t":"Akış yönü","a":"alttan üste","d":"Enerji üreticiden tüketicilere doğru tek yönde akar."},{"t":"Geri dönmez","a":"döngü yok","d":"Madde gibi geri dönüştürülmez; ısı olarak kaybolup sisteme yeniden girmez."}],"ans":"Enerjinin tek yönlü akması, enerjinin üreticiden üst düzeylere doğru aktığını ve ısı olarak kaybolup geri dönmediğini ifade eder."},
{"q":"Ayrıştırıcılar enerji piramidinde nasıl bir rol oynar?","steps":[{"t":"Beslenme","a":"ölü organik madde","d":"Ayrıştırıcılar her trofik düzeydeki ölü canlı ve atıkları parçalar."},{"t":"Enerji geri kazanımı","a":"kalan enerjiyi alır","d":"Üst düzeylere geçmeyen enerjinin bir kısmından ayrıştırıcılar yararlanır."}],"ans":"Ayrıştırıcılar ölü organik maddeyi parçalayarak diğer düzeylerden artan enerjiyi kullanır ve maddenin döngüye dönmesini sağlar."},
{"q":"Bir besin ağı ile bir besin zinciri arasındaki fark enerji aktarımı açısından nedir?","steps":[{"t":"Besin zinciri","a":"tek yol","d":"Besin zinciri enerjinin tek bir doğrusal yolunu gösterir."},{"t":"Besin ağı","a":"çok yol","d":"Besin ağı, birbirine bağlı birçok zinciri ve alternatif enerji yollarını gösterir."}],"ans":"Besin zinciri enerjinin tek bir yolunu, besin ağı ise birçok birbirine bağlı zincirle alternatif enerji aktarım yollarını gösterir."},
{"q":"Neden bir ekosistemde etçiller otçullardan daha az sayıda bulunur?","steps":[{"t":"Üst düzey","a":"daha az enerji","d":"Etçiller daha üst trofik düzeyde olduğu için onlara daha az enerji ulaşır."},{"t":"Sonuç","a":"az birey","d":"Az enerji daha az bireyi destekleyebilir, bu yüzden etçil sayısı azdır."}],"ans":"Etçiller daha üst trofik düzeyde olup daha az enerji aldıkları için otçullardan daha az sayıda bulunur."},
{"q":"Enerji piramidi ile biyokütle piramidi her zaman aynı biçimde mi olur?","steps":[{"t":"Enerji piramidi","a":"daima düz","d":"Enerji piramidi termodinamik nedenle her zaman yukarı daralır."},{"t":"Biyokütle piramidi","a":"ters olabilir","d":"Bazı sucul sistemlerde anlık biyokütle ters dönebilir."}],"ans":"Hayır; enerji piramidi her zaman düzdür, fakat biyokütle piramidi bazı sucul ekosistemlerde ters dönebilir."},
{"q":"Üst düzey tüketicilerin beslenmesi neden geniş bir alan gerektirir?","steps":[{"t":"Enerji ihtiyacı","a":"çok besin","d":"Üst tüketiciye az enerji ulaştığı için ihtiyacını karşılamak çok av gerektirir."},{"t":"Alan","a":"geniş habitat","d":"Yeterli avı bulmak için geniş bir avlanma alanına ihtiyaç duyarlar."}],"ans":"Üst düzey tüketicilere az enerji ulaştığı için ihtiyaçlarını karşılayacak çok sayıda avı bulmaları gerekir, bu da geniş alan gerektirir."},
{"q":"Trofik düzeyler arasındaki enerji aktarım verimi neye bağlıdır?","steps":[{"t":"Sindirim verimi","a":"yenenin oranı","d":"Avın ne kadarının yenip sindirilebildiği verimi etkiler."},{"t":"Metabolik kayıp","a":"solunum/ısı","d":"Canlının solunum ve ısı kaybı ne kadar yüksekse aktarılan enerji o kadar azalır."}],"ans":"Aktarım verimi, besinin sindirilebilen oranına ve canlının solunum/ısı gibi metabolik enerji kayıplarına bağlıdır."}
],"zor":[
{"q":"Üreticide 50000 kJ enerji varsa, %10 kuralına göre üçüncül tüketiciye (4. trofik düzey) ulaşan enerji kaç kJ olur?","steps":[{"t":"2. düzey","a":"5000 kJ","d":"50000 × 0,10 = 5000 kJ (birincil tüketici)."},{"t":"3. düzey","a":"500 kJ","d":"5000 × 0,10 = 500 kJ (ikincil tüketici)."},{"t":"4. düzey","a":"50 kJ","d":"500 × 0,10 = 50 kJ (üçüncül tüketici)."}],"ans":"50000 kJ enerji üç basamak aktarılınca üçüncül tüketiciye 50 kJ ulaşır."},
{"q":"Bir ikincil tüketiciye 80 kJ enerji ulaşmışsa, %10 kuralına göre üreticideki enerji yaklaşık ne kadardı?","steps":[{"t":"Düzeyler arası","a":"iki basamak","d":"Üreticiden ikincil tüketiciye iki basamak çıkılır, her basamakta ÷0,10."},{"t":"1. tüketici","a":"800 kJ","d":"İkincil tüketiciye gelen 80 kJ için birincil tüketicide 80 ÷ 0,10 = 800 kJ olmalı."},{"t":"Üretici","a":"8000 kJ","d":"Üreticide ise 800 ÷ 0,10 = 8000 kJ enerji bulunmalı."}],"ans":"%10 kuralına göre ikincil tüketiciye 80 kJ ulaşması için üreticide yaklaşık 8000 kJ enerji bulunmalıdır."},
{"q":"Enerji piramidinde her basamakta enerjinin yaklaşık %90'ı neden ve nasıl kaybolur?","steps":[{"t":"Solunum","a":"ATP üretimi","d":"Enerjinin büyük kısmı hücresel solunumda harcanıp ısı olarak yayılır."},{"t":"Yenmeyen/sindirilemeyen","a":"dışkı, atık","d":"Avın bir kısmı yenmez ya da sindirilemeden dışkıyla atılır."},{"t":"Hareket ve ısı","a":"metabolik kayıp","d":"Hareket, ısınma ve diğer yaşamsal etkinlikler de enerji tüketir."}],"ans":"Enerjinin yaklaşık %90'ı; solunumda ısıya dönüşme, sindirilemeyen kısmın atılması ve hareket/metabolik etkinlikler nedeniyle kaybolur."},
{"q":"Çayır → çekirge → kurbağa → yılan zincirinde üretici 100000 kJ ise yılana ulaşan enerjiyi hesaplayınız.","steps":[{"t":"Çekirge (2.)","a":"10000 kJ","d":"100000 × 0,10 = 10000 kJ çekirgeye geçer."},{"t":"Kurbağa (3.)","a":"1000 kJ","d":"10000 × 0,10 = 1000 kJ kurbağaya geçer."},{"t":"Yılan (4.)","a":"100 kJ","d":"1000 × 0,10 = 100 kJ yılana geçer."}],"ans":"Üreticideki 100000 kJ enerjinin yalnızca 100 kJ'ü dördüncü düzeydeki yılana ulaşır."},
{"q":"Sucul ekosistemde biyokütle piramidinin ters dönebilmesinin nedeni nedir?","steps":[{"t":"Üretici tipi","a":"fitoplankton","d":"Üreticiler hızlı üreyip hızlı tüketilen küçük fitoplanktonlardır."},{"t":"Anlık kütle","a":"düşük durağan kütle","d":"Belirli bir anda mevcut fitoplankton kütlesi tüketicilerden az olabilir."},{"t":"Üretim hızı","a":"yüksek devir","d":"Yüksek üreme hızı sayesinde toplam enerji akışı yine de yeterlidir."}],"ans":"Fitoplankton gibi üreticilerin hızlı üreyip hızla tüketilmesi nedeniyle anlık biyokütleleri tüketicilerden az olabilir, bu da biyokütle piramidini ters çevirir."},
{"q":"Enerji piramidinin neden hiçbir koşulda ters dönemeyeceğini termodinamik açıdan açıklayınız.","steps":[{"t":"Enerji kaynağı","a":"alttan gelir","d":"Tüm enerji üreticiden başlar; üst düzey ancak alttan aldığı kadar enerjiye sahip olur."},{"t":"Kayıp zorunlu","a":"ısı kaybı","d":"Termodinamiğin 2. yasası gereği her aktarımda bir kısım enerji ısı olarak kaybolur."},{"t":"Sonuç","a":"üst < alt","d":"Üst düzey daima alttan az enerji içerir, bu yüzden piramit ters dönemez."}],"ans":"Termodinamiğin 2. yasası gereği her aktarımda enerji ısı olarak kaybolduğundan üst düzey daima alttan az enerji içerir; bu nedenle enerji piramidi ters dönemez."},
{"q":"Bir zincirde besin (toplam) verimi %15 ise, üreticideki 20000 kJ enerjinin 3. trofik düzeye ulaşan miktarı kaç kJ olur?","steps":[{"t":"2. düzey","a":"3000 kJ","d":"20000 × 0,15 = 3000 kJ birincil tüketiciye geçer."},{"t":"3. düzey","a":"450 kJ","d":"3000 × 0,15 = 450 kJ ikincil tüketiciye geçer."},{"t":"Sonuç","a":"450 kJ","d":"İki basamak %15 verimle aktarılınca 3. düzeye 450 kJ ulaşır."}],"ans":"Verim %15 olduğunda 20000 kJ enerji iki basamak aktarılarak 3. trofik düzeye 450 kJ olarak ulaşır."},
{"q":"İnsanların et yerine doğrudan bitkisel besinle beslenmesi enerji açısından neden daha verimlidir?","steps":[{"t":"Bitkisel beslenme","a":"2. düzey","d":"Bitki yiyen insan birincil tüketici (2. düzey) olur, üreticiye yakın beslenir."},{"t":"Etle beslenme","a":"3. düzey","d":"Et yiyen insan üst düzeye çıkar, arada bir basamak daha enerji kaybı olur."},{"t":"Sonuç","a":"daha az kayıp","d":"Üreticiye yakın beslenmek daha az enerji kaybı, yani daha çok beslenebilen insan demektir."}],"ans":"Bitkisel beslenmede insan üreticiye bir basamak daha yakın olduğundan arada daha az enerji kaybolur; bu yüzden aynı arazi daha çok insanı besleyebilir."},
{"q":"Bir enerji piramidinde 4. trofik düzeye 25 kJ ulaşıyorsa, %10 kuralına göre üreticideki enerjiyi bulunuz.","steps":[{"t":"3. düzey","a":"250 kJ","d":"4. düzeye 25 kJ ulaşması için 3. düzeyde 25 ÷ 0,10 = 250 kJ olmalı."},{"t":"2. düzey","a":"2500 kJ","d":"3. düzey için 250 ÷ 0,10 = 2500 kJ gerekir."},{"t":"Üretici","a":"25000 kJ","d":"Üreticide 2500 ÷ 0,10 = 25000 kJ enerji bulunmalıdır."}],"ans":"4. düzeye 25 kJ ulaşması için üreticide yaklaşık 25000 kJ enerji bulunması gerekir."},
{"q":"Trofik düzey sayısının artması en üst yırtıcının popülasyon büyüklüğünü nasıl etkiler?","steps":[{"t":"Her basamak","a":"%90 kayıp","d":"Eklenen her trofik düzeyde enerjinin yaklaşık %90'ı daha kaybolur."},{"t":"Üst yırtıcıya","a":"çok az enerji","d":"Daha fazla basamak, en üst yırtıcıya ulaşan enerjiyi daha da azaltır."},{"t":"Popülasyon","a":"küçük kalır","d":"Az enerji yalnızca küçük bir popülasyonu destekleyebilir."}],"ans":"Trofik düzey sayısı arttıkça en üst yırtıcıya ulaşan enerji katlanarak azalır, bu da yırtıcının popülasyonunu küçük tutar."},
{"q":"Net birincil üretim (NPP) bir ekosistemin taşıyabileceği canlı miktarını neden belirler?","steps":[{"t":"NPP anlamı","a":"kullanılabilir enerji","d":"NPP, tüketicilere aktarılabilen toplam organik madde/enerjidir."},{"t":"Aktarım","a":"%10 ile üst düzeye","d":"Bu enerji %10 kuralıyla üst düzeylere aktarılır."},{"t":"Sınır","a":"taşıma kapasitesi","d":"Az NPP az enerji demektir; bu da beslenebilecek canlı sayısını sınırlar."}],"ans":"NPP, tüketicilere aktarılabilen toplam enerjiyi belirler; bu enerji sınırlı olduğundan ekosistemin besleyebileceği canlı miktarını (taşıma kapasitesini) doğrudan sınırlar."},
{"q":"Aynı miktarda araziden elde edilen tahıl ile sığır eti karşılaştırıldığında neden tahıl daha çok insanı besler?","steps":[{"t":"Tahıl yolu","a":"doğrudan üretici","d":"Tahıl üreticidir; insan onu yiyince enerjinin büyük kısmını alır."},{"t":"Et yolu","a":"araya hayvan","d":"Sığır önce tahılı yer, enerjinin %90'ını kaybeder, insana azı kalır."},{"t":"Sonuç","a":"tahıl verimli","d":"Arada basamak olmadığı için tahıl çok daha fazla insanı besler."}],"ans":"Tahıl doğrudan tüketildiğinde enerji kaybı az olur; sığır arada bir trofik basamak ekleyip enerjinin %90'ını kaybettiğinden, aynı arazi tahılla çok daha fazla insanı besler."},
{"q":"Enerji piramidinde 'ekolojik verimlilik' kavramı ne anlama gelir ve nasıl hesaplanır?","steps":[{"t":"Tanım","a":"aktarılan oran","d":"Ekolojik verimlilik, bir düzeydeki enerjinin üst düzeye aktarılan yüzdesidir."},{"t":"Hesap","a":"(üst ÷ alt)×100","d":"Üst düzey enerjisinin alt düzey enerjisine bölünüp 100 ile çarpılmasıyla bulunur."},{"t":"Tipik değer","a":"~%10","d":"Çoğu ekosistemde bu değer ortalama %10 civarındadır."}],"ans":"Ekolojik verimlilik, bir trofik düzeyden üstüne aktarılan enerji oranıdır; (üst düzey enerjisi ÷ alt düzey enerjisi)×100 ile hesaplanır ve genelde %10 dolayındadır."},
{"q":"Bir piramitte 1. düzey 10000 kJ, 2. düzey 1200 kJ ise bu basamaktaki ekolojik verimlilik kaçtır?","steps":[{"t":"Formül","a":"(üst÷alt)×100","d":"Ekolojik verimlilik = (2. düzey ÷ 1. düzey) × 100."},{"t":"Yerine koy","a":"(1200÷10000)×100","d":"(1200 ÷ 10000) × 100 = 0,12 × 100."},{"t":"Sonuç","a":"%12","d":"Bu basamaktaki ekolojik verimlilik %12'dir."}],"ans":"Ekolojik verimlilik (1200 ÷ 10000) × 100 = %12 olarak bulunur."},
{"q":"Toksik maddelerin (örneğin DDT) üst trofik düzeylerde yoğunlaşması (biyobirikim) enerji piramidiyle nasıl ilişkilidir?","steps":[{"t":"Enerji azalır","a":"madde değil","d":"Yukarı çıkıldıkça enerji azalır ama parçalanmayan toksik madde vücutta kalır."},{"t":"Daha çok av","a":"çok birikim","d":"Üst düzey, ihtiyacını karşılamak için çok sayıda av yiyip toksini biriktirir."},{"t":"Sonuç","a":"en üstte zirve","d":"Toksin her basamakta yoğunlaşır ve en üst yırtıcıda en yüksek düzeye ulaşır."}],"ans":"Enerji yukarı çıkınca azalırken parçalanmayan toksik madde azalmaz; üst düzey çok sayıda av tükettiği için toksin her basamakta yoğunlaşarak en üst yırtıcıda zirve yapar (biyomagnifikasyon)."}
]}}};
