globalThis.__OUT = {"habitatNiche":{"ilkokul":{"kolay":[
{"q":"Bir canlının yaşadığı yere ne ad verilir?","steps":[{"t":"Yaşanılan yer","a":"yuva gibi düşün","d":"Her canlının yaşadığı, beslendiği ve barındığı bir yer vardır. Bu yer onun adresi gibidir."},{"t":"Bilimsel ad","a":"habitat","d":"Canlının yaşadığı bu yere <b>habitat</b> denir. Örneğin balığın habitatı sudur."}],"ans":"Bir canlının yaşadığı yere <b>habitat</b> (yaşama alanı) denir."},
{"q":"Habitatı su olan bir canlıya örnek ver.","steps":[{"t":"Suda yaşayanlar","a":"sucul canlılar","d":"Bazı canlılar yaşamlarını suda geçirir; suyun içinde yüzer ve beslenirler."},{"t":"Örnek","a":"balık","d":"Balığın habitatı sudur. Balık suyun dışında uzun süre yaşayamaz."}],"ans":"Balığın habitatı (yaşama alanı) sudur."},
{"q":"Solucanın yaşama alanı (habitatı) neresidir?","steps":[{"t":"Nerede görürüz?","a":"toprakta","d":"Solucanı çoğu zaman nemli toprağı kazınca görürüz. Toprağın içinde dolaşır."},{"t":"Habitat","a":"toprak","d":"Solucanın <b>habitatı</b> nemli topraktır. Orada beslenir ve barınır."}],"ans":"Solucanın habitatı (yaşama alanı) nemli topraktır."},
{"q":"Bir canlının habitatı, onun günlük yaşamında neyi sağlar?","steps":[{"t":"İhtiyaçlar","a":"yiyecek, su, barınak","d":"Her canlının yaşamak için yiyeceğe, suya ve saklanacak bir yere ihtiyacı vardır."},{"t":"Habitatın görevi","a":"ihtiyaçları karşılar","d":"<b>Habitat</b>, canlıya bu ihtiyaçları sağlayan yaşama alanıdır."}],"ans":"Habitat, canlıya yiyecek, su ve barınak gibi ihtiyaçlarını sağlayan yaşama alanıdır."},
{"q":"Kutup ayısının habitatı nasıl bir yerdir?","steps":[{"t":"Nerede yaşar?","a":"soğuk yerler","d":"Kutup ayısı çok soğuk, karlı ve buzlu bölgelerde yaşar."},{"t":"Habitat","a":"buzul/kutup bölgesi","d":"Kalın kürkü sayesinde soğuk <b>habitatına</b> uyum sağlamıştır."}],"ans":"Kutup ayısının habitatı soğuk, karlı ve buzlu kutup bölgeleridir."}
],"zor":[
{"q":"Habitat 'adres' ise, ekolojik niş neye benzer?","steps":[{"t":"Adres ne demek?","a":"yaşadığı yer","d":"Bir canlının habitatı, onun yaşadığı yer yani adresidir."},{"t":"Niş ne demek?","a":"yaptığı iş/meslek","d":"<b>Ekolojik niş</b>, canlının doğada yaptığı iştir; yani onun mesleği gibidir."}],"ans":"Habitat canlının adresi (yaşadığı yer), ekolojik niş ise onun mesleği (yaptığı iş) gibidir."},
{"q":"Bir arının ekolojik nişi (doğadaki işi) nedir?","steps":[{"t":"Arı ne yapar?","a":"çiçek tozu taşır","d":"Arı çiçekten çiçeğe gezerken çiçek tozlarını taşır ve bal yapar."},{"t":"Doğadaki işi","a":"tozlaşmayı sağlar","d":"Arının <b>nişi</b>, çiçeklerin tozlaşmasına yardım etmektir. Bu onun doğadaki işidir."}],"ans":"Arının ekolojik nişi, çiçekten çiçeğe gezerek tozlaşmayı sağlamaktır."},
{"q":"Aynı bahçede yaşayan solucan ile kuş farklı işler yapar. Bu duruma ne denir?","steps":[{"t":"Habitat aynı mı?","a":"aynı bahçe","d":"İkisi de aynı yerde, yani aynı habitatta yaşıyor olabilir."},{"t":"İşleri farklı","a":"farklı niş","d":"Solucan toprağı havalandırır, kuş böcek yer. İşleri farklı olduğu için <b>nişleri</b> farklıdır."}],"ans":"Aynı habitatta yaşasalar da işleri (nişleri) farklı olduğu için her birinin ayrı ekolojik nişi vardır."},
{"q":"İki hayvan tamamen aynı yiyeceği ve aynı yeri isterse ne olur?","steps":[{"t":"İstekler aynı","a":"aynı şeyi isterler","d":"İki hayvan aynı yiyeceği ve aynı yeri isterse aralarında bir çekişme başlar."},{"t":"Sonuç","a":"yarışırlar","d":"Aynı şeyi istedikleri için <b>yarışırlar</b> (rekabet). Genelde biri kazanır, diğeri başka yere gider."}],"ans":"Aynı şeyi isteyen iki hayvan birbiriyle yarışır (rekabet eder); biri kazanır, diğeri başka kaynak veya yer arar."},
{"q":"Baykuş gece, atmaca gündüz avlanır. Bu durum onlara nasıl yardım eder?","steps":[{"t":"Farklı zaman","a":"gece-gündüz","d":"Baykuş geceleri, atmaca gündüzleri avlanır. Av zamanları farklıdır."},{"t":"Faydası","a":"yarışmazlar","d":"Farklı zamanlarda avlandıkları için aynı avı paylaşmak için fazla <b>yarışmazlar</b>; ikisi de rahat beslenir."}],"ans":"Farklı zamanlarda avlandıkları için aynı yiyecek için fazla yarışmazlar; böylece ikisi de rahatça yaşar."}
]},"ortaokul":{"kolay":[
{"q":"Habitat ile ekolojik niş arasındaki temel fark nedir?","steps":[{"t":"Habitat","a":"yaşanılan yer","d":"<b>Habitat</b>, bir canlının yaşadığı fiziksel ortamdır; yani onun adresidir."},{"t":"Ekolojik niş","a":"canlının rolü","d":"<b>Ekolojik niş</b>, canlının ekosistemdeki görevidir; beslenme, üreme ve diğer canlılarla ilişkilerini kapsar."}],"ans":"Habitat canlının yaşadığı yer (adres), ekolojik niş ise canlının ekosistemdeki rolü (meslek) olarak özetlenir."},
{"q":"Bir kurbağanın habitatı ile nişini ayrı ayrı açıkla.","steps":[{"t":"Habitatı","a":"göl kenarı/sulak alan","d":"Kurbağa nemli, sulak alanlarda; göl ve dere kenarlarında yaşar. Bu onun <b>habitatıdır</b>."},{"t":"Nişi","a":"böcek avcısı","d":"Kurbağa böcekleri yiyerek böcek sayısını dengeler; kendisi de leyleğe besin olur. Bu onun <b>nişidir</b>."}],"ans":"Kurbağanın habitatı sulak alanlardır; nişi ise böcek avlayıp besin zincirinde yer almasıdır."},
{"q":"Ekolojik niş hangi bilgileri içerir?","steps":[{"t":"Beslenme","a":"ne yer, kime yem olur","d":"Niş; canlının neyle beslendiğini ve hangi canlılara besin olduğunu içerir."},{"t":"İlişkiler ve ortam","a":"sıcaklık, rekabet, üreme","d":"Ayrıca canlının dayandığı sıcaklık aralığı, rekabet ettiği türler ve üreme biçimini de kapsar."}],"ans":"Ekolojik niş; canlının beslenmesini, diğer canlılarla ilişkilerini, ortam koşullarına dayanımını ve üreme biçimini içerir."},
{"q":"Aynı habitatta yaşayan kartal ile fare farklı nişlere sahip midir? Neden?","steps":[{"t":"Habitat","a":"aynı çayır","d":"Kartal ve fare aynı çayır habitatını paylaşabilir."},{"t":"Niş farkı","a":"avcı ve av","d":"Fare bitki yer, kartal fareyi avlar. Beslenme rolleri farklı olduğu için <b>nişleri</b> farklıdır."}],"ans":"Evet; aynı habitatı paylaşsalar da kartal avcı, fare ot oburudur, bu yüzden ekolojik nişleri farklıdır."},
{"q":"Bir bitkinin ekolojik nişi neden hayvanlardan farklı tanımlanır?","steps":[{"t":"Bitkinin beslenmesi","a":"fotosentez","d":"Bitki besinini kendisi üretir; güneş ışığı, su ve karbondioksit kullanır."},{"t":"Nişi","a":"üretici rolü","d":"Bu nedenle bitkinin nişi <b>üretici</b> olmaktır; ekosisteme besin ve oksijen sağlar."}],"ans":"Bitkinin nişi üretici olmaktır; fotosentezle besin ve oksijen üreterek ekosistemi besler."}
],"zor":[
{"q":"İki tür tamamen aynı nişi paylaşmaya çalışırsa uzun vadede ne olur?","steps":[{"t":"Kaynak rekabeti","a":"aynı kaynağı isterler","d":"Aynı nişi isteyen iki tür, aynı besin ve alan için sürekli <b>rekabet</b> eder."},{"t":"Sonuç","a":"biri elenir","d":"Daha az başarılı olan tür azalır veya bölgeden çekilir. Buna <b>rekabetçi dışlama</b> denir."}],"ans":"İki tür aynı nişi tam paylaşamaz; rekabet sonucu biri bölgeden dışlanır (rekabetçi dışlama ilkesi)."},
{"q":"Aynı ağaçta beslenen iki kuş türü nasıl bir arada yaşayabilir?","steps":[{"t":"Sorun","a":"aynı kaynak","d":"İkisi de aynı ağaçtan besleniyorsa rekabet riski vardır."},{"t":"Çözüm","a":"niş ayrımı","d":"Biri üst dallardan, diğeri alt dallardan beslenirse <b>nişleri ayrışır</b> ve rekabet azalır."}],"ans":"Beslenme yerlerini ağacın farklı bölümlerine ayırarak (niş ayrımı) rekabeti azaltıp bir arada yaşarlar."},
{"q":"Bir baykuş ve bir atmacanın aynı bölgede yaşamasını sağlayan niş farkı nedir?","steps":[{"t":"Ortak yön","a":"aynı avlar","d":"İkisi de küçük kemirgenlerle beslenebilir, bu rekabet yaratabilir."},{"t":"Niş ayrımı","a":"farklı zaman","d":"Baykuş gece, atmaca gündüz avlanır. Avlanma zamanları farklı olduğu için <b>nişleri ayrışır</b>."}],"ans":"Baykuş gece, atmaca gündüz avlandığı için zaman bakımından nişleri ayrışır ve aynı bölgede yaşayabilirler."},
{"q":"Bir göldeki balık türlerinin farklı derinliklerde yaşaması nişle nasıl açıklanır?","steps":[{"t":"Gözlem","a":"farklı derinlik","d":"Bir türü yüzeye yakın, diğeri dipte yaşar. Aynı gölü paylaşırlar."},{"t":"Açıklama","a":"niş ayrımı","d":"Farklı derinliklerde farklı besin bulurlar; böylece kaynaklar paylaşılır ve <b>rekabet azalır</b>."}],"ans":"Türler farklı derinliklerde beslenerek nişlerini ayırır; kaynaklar paylaşıldığı için rekabet azalır."},
{"q":"Bir türün doğal düşmanı olmasaydı yaşayabileceği geniş niş ile gerçekte yaşadığı dar niş nasıl adlandırılır?","steps":[{"t":"İdeal durum","a":"temel niş","d":"Hiç rakip ve düşman olmasaydı türün kullanabileceği tüm kaynaklara <b>temel niş</b> denir."},{"t":"Gerçek durum","a":"gerçekleşen niş","d":"Rekabet ve düşman baskısı yüzünden türün gerçekte kullandığı dar alana <b>gerçekleşen niş</b> denir."}],"ans":"Geniş ideal alan temel niş, rekabet nedeniyle daralan gerçek alan gerçekleşen niş olarak adlandırılır."}
]},"lise":{"kolay":[
{"q":"Habitat ve ekolojik niş kavramlarını bilimsel olarak tanımla.","steps":[{"t":"Habitat","a":"fiziksel yaşam alanı","d":"<b>Habitat</b>, bir türün doğal olarak bulunduğu, belirli abiyotik ve biyotik koşullara sahip fiziksel ortamdır."},{"t":"Ekolojik niş","a":"işlevsel rol","d":"<b>Ekolojik niş</b>, bir türün ekosistemdeki işlevsel rolüdür; kaynak kullanımı, ilişkileri ve etkileri kapsar."}],"ans":"Habitat türün yaşadığı fiziksel ortam; ekolojik niş ise türün o ortamdaki işlevsel rolü ve kaynak kullanım biçimidir."},
{"q":"Ekolojik niş neden çok boyutlu bir kavram olarak ele alınır?","steps":[{"t":"Tek değişken yetersiz","a":"birçok faktör","d":"Bir türün yaşamı tek bir koşula değil; sıcaklık, nem, besin, ışık gibi çok sayıda faktöre bağlıdır."},{"t":"Çok boyutluluk","a":"hiper-hacim","d":"Bu faktörlerin her biri bir eksen olarak düşünülürse niş, çok boyutlu bir <b>hiper-hacim</b> olarak tanımlanır (Hutchinson)."}],"ans":"Niş, sıcaklık, nem, besin gibi birçok çevresel eksenin oluşturduğu çok boyutlu bir hiper-hacim olduğundan çok boyutlu kabul edilir."},
{"q":"Temel niş (fundamental) ile gerçekleşen niş (realized) arasındaki fark nedir?","steps":[{"t":"Temel niş","a":"potansiyel kullanım","d":"<b>Temel niş</b>, türün hiçbir biyotik kısıt olmadan kullanabileceği tüm koşulların toplamıdır."},{"t":"Gerçekleşen niş","a":"fiili kullanım","d":"<b>Gerçekleşen niş</b>, rekabet ve avcılık gibi etkileşimler sonucu türün gerçekte işgal ettiği daha dar alandır."}],"ans":"Temel niş türün potansiyel olarak kullanabileceği tüm koşullar, gerçekleşen niş ise biyotik kısıtlarla daralan fiili kullanım alanıdır."},
{"q":"Rekabetçi dışlama ilkesi (Gause ilkesi) neyi ifade eder?","steps":[{"t":"İlke","a":"aynı niş paylaşılamaz","d":"İki tür aynı kaynakları aynı şekilde kullanıyorsa, yani <b>özdeş niş</b> paylaşıyorsa kalıcı olarak bir arada var olamaz."},{"t":"Sonuç","a":"biri elenir","d":"Daha verimli tür kazanır; diğeri ya yerel olarak yok olur ya da nişini değiştirir."}],"ans":"Rekabetçi dışlama ilkesi, özdeş niş paylaşan iki türün kalıcı olarak birlikte yaşayamayacağını; birinin elenmesi gerektiğini ifade eder."},
{"q":"Niş ayrımı (kaynak paylaşımı) bir arada yaşamayı nasıl mümkün kılar?","steps":[{"t":"Sorun","a":"kaynak çakışması","d":"Benzer türler aynı kaynağı kullanırsa rekabet şiddetlenir."},{"t":"Çözüm","a":"kaynakların bölüşülmesi","d":"Türler besini, zamanı veya mekânı bölüşerek <b>niş ayrımı</b> yapar; nişlerdeki örtüşme azalır ve birlikte yaşam mümkün olur."}],"ans":"Niş ayrımı, türlerin kaynak, zaman veya mekânı bölüşmesiyle niş örtüşmesini azaltarak rekabeti hafifletir ve bir arada yaşamayı sağlar."},
{"q":"Aynı habitatı paylaşan iki türün farklı nişlere sahip olabilmesi neyi gösterir?","steps":[{"t":"Habitat ortak","a":"aynı alan","d":"İki tür aynı orman ya da gölü paylaşabilir; yani habitatları aynıdır."},{"t":"Niş farkı","a":"farklı rol","d":"Farklı besin veya tabaka kullanırlarsa rolleri ayrışır; bu, <b>habitatın paylaşılabildiğini ama nişin türe özgü olduğunu</b> gösterir."}],"ans":"Aynı habitatın paylaşılabilmesine karşın nişlerin farklı olması, habitatın ortak, nişin ise türe özgü işlevsel rol olduğunu gösterir."},
{"q":"Bir türün generalist (genelci) ve specialist (uzmanlaşmış) niş tipi arasındaki fark nedir?","steps":[{"t":"Genelci","a":"geniş niş","d":"<b>Genelci</b> türler çok çeşitli kaynak ve koşulu kullanır; geniş bir nişe sahiptir (ör. fare, karga)."},{"t":"Uzmanlaşmış","a":"dar niş","d":"<b>Uzmanlaşmış</b> türler belirli kaynağa bağımlıdır; dar nişe sahiptir (ör. yalnız okaliptus yiyen koala)."}],"ans":"Genelci türlerin geniş bir nişi (çeşitli kaynak), uzmanlaşmış türlerin ise dar bir nişi (sınırlı kaynak) vardır."},
{"q":"Karbonsuz dünyada bile bir bitkinin nişi neden 'üretici' rolüyle tanımlanır?","steps":[{"t":"Trofik konum","a":"besin üretimi","d":"Bitki, fotosentezle inorganik maddeden organik besin üretir; bu onun temel işlevidir."},{"t":"Niş tanımı","a":"üretici niş","d":"Niş, türün ekosistemdeki işlevsel rolü olduğundan bitkinin nişi <b>üretici</b> (ototrof) konumudur."}],"ans":"Niş işlevsel rolü ifade ettiğinden, fotosentezle besin üreten bitkinin ekolojik nişi üretici (ototrof) rolüdür."},
{"q":"Bir tür yeni bir bölgeye girdiğinde yerli türün gerçekleşen nişi nasıl etkilenebilir?","steps":[{"t":"Yeni rekabet","a":"kaynak çakışması","d":"İstilacı tür, yerli türle aynı kaynakları kullanırsa rekabet artar."},{"t":"Niş daralması","a":"daralan kullanım","d":"Yerli tür kaynakların bir kısmından çekilir; <b>gerçekleşen nişi daralır</b>, hatta yok olabilir."}],"ans":"İstilacı tür rekabeti artırarak yerli türün gerçekleşen nişini daraltabilir, kaynak kullanımını sınırlar."},
{"q":"Habitat çeşitliliği ile tür çeşitliliği arasındaki ilişki nedir?","steps":[{"t":"Çeşitli habitat","a":"farklı koşullar","d":"Bir alanda farklı habitatlar (su, kaya, orman tabakası) bulunması çeşitli yaşam koşulları sunar."},{"t":"Niş sayısı","a":"çok niş, çok tür","d":"Daha fazla farklı koşul daha fazla <b>niş</b> demektir; bu da daha çok türün bir arada yaşamasını sağlar."}],"ans":"Habitat çeşitliliği arttıkça kullanılabilir niş sayısı artar, bu da tür çeşitliliğinin yükselmesine olanak tanır."},
{"q":"İki türün nişlerinin kısmen örtüşmesi ne anlama gelir?","steps":[{"t":"Kısmi örtüşme","a":"ortak kaynak","d":"İki tür bazı kaynakları paylaşır ama her birinin kendine özgü kaynakları da vardır."},{"t":"Sonuç","a":"sınırlı rekabet","d":"Örtüşen bölümde <b>rekabet</b> olur; örtüşmeyen kaynaklar sayesinde tam dışlanma olmadan bir arada yaşayabilirler."}],"ans":"Kısmi niş örtüşmesi, örtüşen kaynaklarda rekabet doğurur; ancak ayrı kaynaklar olduğundan türler tam dışlanmadan bir arada var olabilir."},
{"q":"Bir türün nişinde sıcaklık 'tolerans aralığı' neden önemlidir?","steps":[{"t":"Tolerans","a":"yaşam sınırı","d":"Her türün yaşayabildiği bir alt ve üst sıcaklık sınırı (tolerans aralığı) vardır."},{"t":"Niş boyutu","a":"niş ekseni","d":"Bu aralık nişin bir <b>boyutudur</b>; türün hangi bölgede ve mevsimde yaşayabileceğini belirler."}],"ans":"Sıcaklık tolerans aralığı nişin bir boyutudur ve türün dağılımını, hangi koşullarda yaşayabileceğini belirler."},
{"q":"Aynı çiçeği ziyaret eden farklı tozlaşma zamanlarına sahip iki böcek nişi nasıl paylaşır?","steps":[{"t":"Ortak kaynak","a":"aynı çiçek","d":"İki böcek de aynı çiçeğin nektarını kullanır, bu rekabet yaratabilir."},{"t":"Zamansal ayrım","a":"farklı saat","d":"Biri sabah, diğeri öğleden sonra ziyaret ederse <b>zamansal niş ayrımı</b> ile aynı çiçeği paylaşırlar."}],"ans":"Böcekler çiçeği farklı saatlerde ziyaret ederek zamansal niş ayrımı yapar ve aynı kaynağı paylaşabilir."},
{"q":"Niş kavramı bir ekosistemde 'boş niş' fikrini nasıl açıklar?","steps":[{"t":"Boş niş","a":"kullanılmayan rol","d":"Bir ekosistemde henüz hiçbir türün kullanmadığı kaynak veya işlevsel rol bulunabilir; buna <b>boş niş</b> denir."},{"t":"Doldurulması","a":"yeni tür/uyum","d":"Bu niş, dışarıdan gelen ya da uyum sağlayan bir türle zamanla doldurulabilir."}],"ans":"Boş niş, ekosistemde henüz bir türün kullanmadığı işlevsel roldür ve göç veya evrimsel uyumla doldurulabilir."},
{"q":"Habitatın bozulması bir türün nişini nasıl ortadan kaldırabilir?","steps":[{"t":"Habitat kaybı","a":"koşullar yok olur","d":"Ormanın kesilmesi gibi durumlarda türün ihtiyaç duyduğu koşullar ortadan kalkar."},{"t":"Niş kaybı","a":"rol icra edilemez","d":"Koşullar olmadan tür işlevsel rolünü (nişini) sürdüremez; bölgede <b>yok olabilir</b>."}],"ans":"Habitat bozulduğunda türün ihtiyaç duyduğu koşullar yok olur; tür nişini icra edemez ve yerel olarak yok olabilir."}
],"zor":[
{"q":"Gause'nin Paramecium deneyi rekabetçi dışlama ilkesini nasıl kanıtlar?","steps":[{"t":"Deney düzeneği","a":"iki tür aynı kapta","d":"Gause, aynı besinle beslenen iki Paramecium türünü aynı kapta yetiştirdi."},{"t":"Gözlem","a":"biri eledi","d":"Bir tür sayıca arttı, diğeri azalıp <b>yok oldu</b>. Ayrı kaplarda ise ikisi de yaşadı."},{"t":"Sonuç","a":"özdeş niş yaşatmaz","d":"Özdeş niş paylaşan türlerin bir arada kalamayacağı, yani <b>rekabetçi dışlama</b> doğrulandı."}],"ans":"Aynı kapta özdeş niş paylaşan iki Paramecium türünden biri elenirken ayrı kaplarda ikisinin de yaşaması, rekabetçi dışlama ilkesini kanıtlar."},
{"q":"MacArthur'un ötleğen kuşları çalışması niş ayrımını nasıl gösterir?","steps":[{"t":"Sorun","a":"aynı ağaç, aynı besin","d":"Beş ötleğen türü aynı ladin ağacında böceklerle besleniyordu; özdeş niş beklentisi vardı."},{"t":"Gözlem","a":"farklı tabaka","d":"Her tür ağacın farklı bölgesinde (üst, orta, alt, iç, dış) beslenmekteydi."},{"t":"Sonuç","a":"mekânsal niş ayrımı","d":"Beslenme bölgelerini bölüşerek <b>niş ayrımı</b> yaptılar; rekabetçi dışlama olmadan bir arada yaşadılar."}],"ans":"Beş ötleğen türü aynı ağacın farklı bölgelerinde beslenerek mekânsal niş ayrımı yaptı; bu, özdeş niş gerginliğini çözerek bir arada yaşamayı sağladı."},
{"q":"Connell'in deniz minaresi (Chthamalus-Balanus) deneyi temel niş ile gerçekleşen niş ayrımını nasıl ortaya koyar?","steps":[{"t":"Dağılım","a":"farklı yükseklik","d":"Kayalık kıyıda Chthamalus üst, Balanus alt bölgede yaşıyordu."},{"t":"Balanus uzaklaştırılınca","a":"Chthamalus yayıldı","d":"Balanus elenince Chthamalus alt bölgeye de yayıldı; yani <b>temel nişi</b> daha genişti."},{"t":"Sonuç","a":"rekabet daraltır","d":"Doğal koşulda Balanus rekabetle Chthamalus'u üst bölgeye sıkıştırıyordu; bu daralmış alan <b>gerçekleşen niştir</b>."}],"ans":"Balanus uzaklaştırılınca Chthamalus'un alt bölgeye yayılması, geniş temel nişin rekabetle daraldığını ve gözlenen dar alanın gerçekleşen niş olduğunu gösterir."},
{"q":"Karakter kayması (character displacement) niş ayrımıyla nasıl ilişkilidir?","steps":[{"t":"Tek başına","a":"benzer özellik","d":"Bir tür yalnız yaşadığında özellikleri (ör. gaga boyu) belirli bir aralıktadır."},{"t":"Birlikte yaşayınca","a":"özellik farklılaşır","d":"Aynı bölgede benzer bir türle yaşadığında, rekabeti azaltmak için özellikleri <b>farklılaşır</b> (ör. gagalar farklı boyutlara kayar)."},{"t":"Sonuç","a":"niş ayrımı pekişir","d":"Bu evrimsel farklılaşma, türlerin farklı kaynakları kullanmasını sağlayıp <b>niş ayrımını</b> güçlendirir."}],"ans":"Karakter kayması, birlikte yaşayan benzer türlerin özelliklerinin evrimle farklılaşmasıdır; bu farklılaşma kaynak kullanımını ayırarak niş ayrımını pekiştirir."},
{"q":"Rekabetçi dışlama ilkesi her durumda neden gerçekleşmez? Hangi etmenler dışlamayı engeller?","steps":[{"t":"İlkenin koşulu","a":"sabit, özdeş niş","d":"Dışlama, kaynaklar sabit ve nişler tam özdeş olduğunda beklenir."},{"t":"Engelleyen etmenler","a":"bozulma, avcılık","d":"Çevresel dalgalanmalar, avcılık ve karışıklıklar dengeyi sürekli bozarak hiçbir türün tam üstünlük kurmasını engeller."},{"t":"Sonuç","a":"birlikte yaşam sürer","d":"Kaynaklar değişken olduğundan veya avcı baskısı eşitlediğinden türler <b>bir arada</b> kalabilir."}],"ans":"Çevresel dalgalanmalar, avcılık ve karışıklıklar tam rekabetçi üstünlüğü engellediğinden, nişler özdeşe yakın olsa bile dışlama her zaman gerçekleşmez."},
{"q":"Hutchinson'ın n-boyutlu hiper-hacim niş modeli klasik niş tanımını nasıl geliştirir?","steps":[{"t":"Klasik tanım","a":"rol/yer","d":"Daha önce niş, türün rolü ya da yeri olarak nitel tanımlanıyordu."},{"t":"Hutchinson modeli","a":"çok boyutlu hacim","d":"Sıcaklık, nem, besin gibi her çevresel değişken bir eksen kabul edilir; nişi bu eksenlerin oluşturduğu <b>n-boyutlu hiper-hacim</b> tanımlar."},{"t":"Katkı","a":"ölçülebilirlik","d":"Bu model nişi nicel ve <b>ölçülebilir</b> hale getirir; temel ve gerçekleşen niş tam olarak ayrılabilir."}],"ans":"Hutchinson modeli nişi, her çevresel değişkenin bir eksen olduğu n-boyutlu bir hiper-hacim olarak tanımlayarak nişi nicel, ölçülebilir ve temel/gerçekleşen ayrımına uygun hale getirir."},
{"q":"Niş örtüşmesinin derecesi ile rekabet şiddeti arasındaki ilişki nasıl değerlendirilir?","steps":[{"t":"Örtüşme ölçütü","a":"ortak kaynak oranı","d":"İki türün niş hiper-hacimlerinin örtüşen bölümü, paylaşılan kaynak miktarını gösterir."},{"t":"İlişki","a":"örtüşme ↑ rekabet ↑","d":"Örtüşme arttıkça aynı kaynaklara olan talep artar; bu da <b>rekabet şiddetini</b> yükseltir."},{"t":"Eşik","a":"sınır benzerlik","d":"Belirli bir örtüşme eşiğini aşan türler bir arada yaşayamaz; bu eşiğe <b>sınır benzerlik (limiting similarity)</b> denir."}],"ans":"Niş örtüşmesi arttıkça rekabet şiddeti artar; sınır benzerlik eşiği aşıldığında türler bir arada yaşayamaz ve dışlama beklenir."},
{"q":"Bir türün temel nişi neden gerçekleşen nişinden daima daha büyük (veya eşit) olur?","steps":[{"t":"Temel niş","a":"kısıtsız potansiyel","d":"Temel niş, biyotik etkileşimler hiç olmasaydı türün kullanabileceği tüm koşulları kapsar."},{"t":"Daraltıcı etkiler","a":"rekabet, avcılık","d":"Gerçekte rekabet, avcılık ve parazitlik gibi etkiler türün kullanımını <b>kısıtlar</b>."},{"t":"Sonuç","a":"daralma","d":"Bu kısıtlar kaynak eklemez, yalnızca çıkarır; bu yüzden gerçekleşen niş temel nişin <b>alt kümesidir</b>."}],"ans":"Biyotik etkileşimler ancak kaynak kullanımını daraltabildiğinden, gerçekleşen niş temel nişin alt kümesidir ve ondan daima küçük ya da eşittir."},
{"q":"Niş yapılandırma (niche construction) kavramı, türün kendi nişini nasıl değiştirdiğini açıklar; örnekle anlat.","steps":[{"t":"Tanım","a":"ortamı değiştirme","d":"Bazı türler etkinlikleriyle çevreyi değiştirerek kendi ve diğer türlerin nişini yeniden biçimlendirir."},{"t":"Örnek","a":"kunduz barajı","d":"Kunduz baraj yaparak akarsuyu göle çevirir; bu hem kendi nişini hem de sulak alan türlerinin nişini <b>oluşturur</b>."},{"t":"Sonuç","a":"geri besleme","d":"Bu değişiklik gelecekteki seçilim baskılarını da etkiler; tür ile ortam arasında <b>geri besleme</b> doğar."}],"ans":"Niş yapılandırma, kunduzun baraj yapması gibi türlerin çevreyi değiştirerek kendi ve diğer türlerin nişini biçimlendirmesidir ve ortamla evrimsel geri besleme yaratır."},
{"q":"İstilacı türler yerli türleri rekabetçi dışlama yoluyla nasıl elimine eder; süreci adımlandır.","steps":[{"t":"Giriş ve üstünlük","a":"avantajlı istilacı","d":"İstilacı tür, yeni alanda doğal düşmandan yoksun ve kaynak kullanımında daha verimli olabilir."},{"t":"Niş örtüşmesi","a":"aynı kaynak","d":"Yerli türle yüksek niş örtüşmesi olduğunda aynı kaynak için yoğun <b>rekabet</b> başlar."},{"t":"Dışlama","a":"yerli tür çekilir","d":"İstilacı kaynakları daha hızlı tüketerek yerli türün gerçekleşen nişini sıfıra indirir; yerli tür <b>yerel olarak yok olur</b>."}],"ans":"İstilacı tür, üstün kaynak kullanımı ve yüksek niş örtüşmesiyle yerli türle rekabete girer, kaynakları tüketerek onun gerçekleşen nişini yok eder ve yerel yok oluşa sürükler."},
{"q":"Trofik niş ile mekânsal niş ayrımının bir besin ağındaki birlikte yaşamı nasıl desteklediğini açıkla.","steps":[{"t":"Trofik niş","a":"ne yediği","d":"Trofik niş, türün besin ağındaki beslenme düzeyini ve avını tanımlar."},{"t":"Mekânsal niş","a":"nerede beslendiği","d":"Mekânsal niş, türün kaynağı hangi konum/tabakada kullandığını belirtir."},{"t":"Birleşik etki","a":"çok eksenli ayrım","d":"Türler hem ne yedikleri hem nerede beslendikleri bakımından ayrışırsa örtüşme azalır; bu <b>çok eksenli niş ayrımı</b> rekabeti düşürerek bir arada yaşamı destekler."}],"ans":"Trofik (ne yediği) ve mekânsal (nerede beslendiği) niş ayrımının birleşmesi, niş örtüşmesini birden çok eksende azaltarak rekabeti düşürür ve türlerin bir arada yaşamasını destekler."},
{"q":"Bir adaya ulaşan tek bir ata türden çok sayıda farklı türün oluşması (uyumsal açılım) niş kavramıyla nasıl açıklanır?","steps":[{"t":"Boş nişler","a":"kullanılmamış kaynaklar","d":"Yeni adada rakip az olduğundan birçok kaynak ve işlevsel rol, yani <b>boş niş</b> bulunur."},{"t":"Farklılaşma","a":"niş işgali","d":"Ata türün soyları farklı kaynaklara uyum sağlayarak değişik nişleri işgal eder (ör. Darwin ispinozlarında gaga çeşitliliği)."},{"t":"Sonuç","a":"uyumsal açılım","d":"Niş ayrımıyla giden hızlı tür oluşumuna <b>uyumsal açılım (adaptive radiation)</b> denir."}],"ans":"Yeni ortamdaki boş nişler, ata türün soylarının farklı kaynaklara uyum sağlayıp ayrı nişleri işgal etmesini sağlar; bu niş temelli çeşitlenme uyumsal açılım olarak açıklanır."},
{"q":"Avcı baskısının türlerin gerçekleşen nişlerini genişletip rekabetçi dışlamayı engellemesi (predator-mediated coexistence) nasıl işler?","steps":[{"t":"Rekabet riski","a":"baskın tür","d":"Avcı yoksa en güçlü rakip tür kaynakları kapar ve diğerlerini dışlama eğilimindedir."},{"t":"Avcının etkisi","a":"baskını sınırlar","d":"Avcı, baskın türün sayısını düşürünce bu türün kaynak üzerindeki baskısı azalır."},{"t":"Sonuç","a":"birlikte yaşam","d":"Zayıf rakipler de kaynağa erişip nişlerini koruyabilir; böylece avcılık <b>rekabetçi dışlamayı engeller</b> ve çeşitliliği artırır."}],"ans":"Avcı, baskın rakibin sayısını sınırlayarak onun kaynak üzerindeki üstünlüğünü azaltır; bu sayede zayıf rakipler de var olur ve avcı aracılı birlikte yaşam rekabetçi dışlamayı engeller."},
{"q":"Çevresel değişkenlik ve karışıklıkların orta düzeyde olması (orta düzey bozulma hipotezi) niş doluluğu ve tür çeşitliliğini nasıl etkiler?","steps":[{"t":"Düşük bozulma","a":"rekabet baskın","d":"Çok az karışıklıkta en güçlü rakip nişleri kapar; rekabetçi dışlamayla çeşitlilik <b>azalır</b>."},{"t":"Yüksek bozulma","a":"yalnız dirençliler","d":"Çok sık karışıklıkta yalnızca hızlı toparlanan birkaç tür kalır; çeşitlilik yine <b>düşer</b>."},{"t":"Orta düzey","a":"en yüksek çeşitlilik","d":"Orta düzey bozulmada hem rekabetçi hem öncü türler nişlerini koruyabilir; bu yüzden tür çeşitliliği <b>en yüksektir</b>."}],"ans":"Orta düzey bozulma hipotezine göre çeşitlilik orta seviye karışıklıkta en yüksektir; çünkü hem güçlü rakipler hem öncü türler nişlerini koruyup rekabetçi dışlama tamamlanmaz."},
{"q":"Bir türün temel nişinin tamamen rakipler tarafından kaplanması durumunda hayatta kalmak için izleyebileceği ekolojik ve evrimsel yollar nelerdir?","steps":[{"t":"Sorun","a":"niş kaplanmış","d":"Rakip tür, hedef türün temel nişiyle tamamen örtüşürse gerçekleşen niş sıfıra yaklaşır."},{"t":"Ekolojik yanıt","a":"göç/kaynak değişimi","d":"Tür, rakibin bulunmadığı bir bölgeye göç edebilir veya kullanılmayan alternatif kaynaklara <b>kayabilir</b>."},{"t":"Evrimsel yanıt","a":"karakter kayması","d":"Uzun vadede seçilim, türün özelliklerini farklılaştırır (karakter kayması) ve <b>yeni bir niş</b> ayrışmasını sağlar; aksi halde yerel yok oluş gerçekleşir."}],"ans":"Tür ya rakibin olmadığı alana göç eder veya alternatif kaynağa kayar (ekolojik kaçış), ya da karakter kaymasıyla evrimsel niş ayrışması geliştirir; bu yollar başarısız olursa yerel yok oluşla karşılaşır."}
]}}};
