globalThis.__OUT = {"turlerArasi":{"ilkokul":{"kolay":[
{"q":"Arı ile çiçek arasında nasıl bir yardımlaşma vardır?","steps":[{"t":"Arının kazancı","a":"besin alır","d":"Arı çiçekten tatlı bal özünü (nektar) alarak karnını doyurur."},{"t":"Çiçeğin kazancı","a":"taşınır","d":"Arı uçarken çiçek tozlarını başka çiçeğe taşır, böylece çiçek çoğalır."}],"ans":"Arı çiçekten besin alır, çiçek de arı sayesinde çoğalır; ikisi de yarar görür."},
{"q":"Aslan ile ceylan arasında nasıl bir ilişki vardır?","steps":[{"t":"Kim avlar","a":"aslan avlar","d":"Aslan karnını doyurmak için ceylanı kovalayıp yakalar."},{"t":"Kim av olur","a":"ceylan av","d":"Ceylan aslandan kaçmaya çalışır çünkü ona yem olabilir."}],"ans":"Aslan avcıdır, ceylan ise avdır; buna avcı-av ilişkisi denir."},
{"q":"Köpekteki pireler köpeğe yarar mı verir, zarar mı?","steps":[{"t":"Pirenin işi","a":"kan emer","d":"Pire köpeğin üzerinde yaşar ve onun kanını emerek beslenir."},{"t":"Köpeğin durumu","a":"zarar görür","d":"Köpek kaşınır ve rahatsız olur, yani zarar görür."}],"ans":"Pire köpekten kan emerek yarar görür, köpek ise zarar görür."},
{"q":"İki köpek aynı kemiği isterse ne olur?","steps":[{"t":"Aynı şeyi isteme","a":"ikisi de ister","d":"İki köpek de aynı kemiği yemek ister."},{"t":"Sonuç","a":"yarışırlar","d":"Aynı şeyi paylaşamadıkları için birbirleriyle yarışır, buna rekabet denir."}],"ans":"İki köpek aynı kemik için yarışır; buna rekabet (yarış) denir."},
{"q":"Kuş, ineğin sırtına konup üzerindeki böcekleri yerse kim yarar görür?","steps":[{"t":"Kuşun kazancı","a":"besin bulur","d":"Kuş ineğin üzerindeki böcekleri yiyerek karnını doyurur."},{"t":"İneğin kazancı","a":"böceklerden kurtulur","d":"İnek de onu rahatsız eden böceklerden temizlenir."}],"ans":"Kuş böcekleri yiyerek doyar, inek de böceklerden kurtulur; ikisi de yarar görür."}
],"zor":[
{"q":"Bir kuş, ağacın dalına yuva yaparsa kuş ile ağaç bu ilişkiden nasıl etkilenir?","steps":[{"t":"Kuşun kazancı","a":"barınak bulur","d":"Kuş ağacın dalında güvenli bir yuva yapıp yumurtalarını korur."},{"t":"Ağacın durumu","a":"etkilenmez","d":"Ağaç bundan ne yarar görür ne de zarar; ona bir şey olmaz."}],"ans":"Kuş ağaçtan barınak kazanır, ağaca ise bir şey olmaz; kuş yarar görür, ağaç etkilenmez."},
{"q":"Otları aynı tarlada yiyen iki tavşan neden birbirine zorluk çıkarır?","steps":[{"t":"Aynı besin","a":"aynı otları yer","d":"İki tavşan da aynı tarladaki otlarla beslenir."},{"t":"Az besin","a":"yetmeyebilir","d":"Otlar azalınca ikisine birden yetmez, biri çok yerse diğerine az kalır."},{"t":"Sonuç","a":"rekabet","d":"Aynı besin için yarıştıkları için aralarında rekabet vardır."}],"ans":"İki tavşan aynı otlar için yarıştığından birbirine zorluk çıkarır; buna rekabet denir."},
{"q":"Baykuş geceleri fareleri avlarsa, farelerin sayısı çok artarsa ne olur?","steps":[{"t":"Bol av","a":"çok fare","d":"Fareler çoğalınca baykuşa bol miktarda yiyecek olur."},{"t":"Avcının çoğalması","a":"baykuş artar","d":"Bol besin bulan baykuşlar da zamanla çoğalır."},{"t":"Sonuç","a":"fare azalır","d":"Çok baykuş daha çok fare avlayınca fare sayısı tekrar azalır."}],"ans":"Fareler çoğalınca baykuşlar da artar, sonra fareleri çok avlayıp sayılarını azaltır; avcı ve av birbirini dengeler."},
{"q":"Bir solucan, bir insanın bağırsağında yaşayıp besinini çalarsa kim yarar kim zarar görür?","steps":[{"t":"Solucanın kazancı","a":"hazır besin","d":"Solucan insanın yediği besinden pay alarak beslenir."},{"t":"İnsanın durumu","a":"zarar görür","d":"İnsan yeterli besin alamaz, halsizleşir ve hastalanır."}],"ans":"Solucan hazır besin bulup yarar görür, insan ise zarar görür; buna parazitlik denir."},
{"q":"Bir çiçek tarlasında arılar olmasaydı çiçekler için ne değişirdi?","steps":[{"t":"Arının görevi","a":"çiçek tozu taşır","d":"Arılar bir çiçekten ötekine çiçek tozu taşıyarak çoğalmaya yardım eder."},{"t":"Arı olmazsa","a":"taşınmaz","d":"Arı olmazsa çiçek tozları başka çiçeğe gidemez."},{"t":"Sonuç","a":"çoğalamaz","d":"Tozlaşma olmayınca çiçekler tohum yapıp çoğalamaz."}],"ans":"Arılar olmasaydı çiçek tozu taşınamaz, çiçekler tohum yapıp çoğalamazdı; arı ile çiçek birbirine yardım eder."}
]},"ortaokul":{"kolay":[
{"q":"İki canlının da yarar gördüğü ortak yaşama ne ad verilir?","steps":[{"t":"İlişkinin yönü","a":"iki tarafa yarar","d":"Bu ilişkide canlıların ikisi de birbirinden fayda sağlar."},{"t":"Adı","a":"mutualizm","d":"Karşılıklı yarar sağlanan bu ilişkiye mutualizm (ortak yaşam) denir."}],"ans":"İki canlının da yarar gördüğü ilişkiye mutualizm denir."},
{"q":"Parazitlik ilişkisinde taraflar nasıl etkilenir?","steps":[{"t":"Parazitin durumu","a":"yarar görür","d":"Parazit, üzerinde yaşadığı canlıdan besin alarak yarar görür."},{"t":"Konağın durumu","a":"zarar görür","d":"Üzerinde yaşanan canlı (konak) ise besin kaybeder ve zarar görür."}],"ans":"Parazitlikte parazit yarar görür, konak zarar görür."},
{"q":"Av-avcı ilişkisinde avcının görevi nedir?","steps":[{"t":"Avcının beslenmesi","a":"avı yer","d":"Avcı, başka bir canlıyı (avı) yakalayıp yiyerek beslenir."},{"t":"İlişkinin türü","a":"bir taraf zarar","d":"Av yenildiği için zarar görür, avcı ise besin kazanır."}],"ans":"Av-avcı ilişkisinde avcı avı yakalayıp yer; avcı yarar, av zarar görür."},
{"q":"Aynı besin ve alan için iki canlının yarışmasına ne denir?","steps":[{"t":"Ortak ihtiyaç","a":"aynı kaynak","d":"İki canlı aynı besin, su veya yaşama alanına ihtiyaç duyar."},{"t":"Adı","a":"rekabet","d":"Sınırlı kaynak için yarıştıkları bu ilişkiye rekabet denir."}],"ans":"Aynı kaynak için yarışan canlılar arasındaki ilişkiye rekabet denir."},
{"q":"Bir canlının yarar gördüğü, diğerinin ne yarar ne zarar gördüğü ilişkiye ne denir?","steps":[{"t":"Bir tarafın durumu","a":"yarar görür","d":"İlişkideki bir canlı barınma veya taşınma gibi bir yarar sağlar."},{"t":"Diğer tarafın durumu","a":"etkilenmez","d":"Diğer canlı bu ilişkiden etkilenmez; ne kazanır ne kaybeder."}],"ans":"Biri yarar gördüğü, diğerinin etkilenmediği ilişkiye komensalizm (kommensalizm) denir."}
],"zor":[
{"q":"Likende yaşayan mantar ve alg arasındaki ilişkiyi açıklayınız.","steps":[{"t":"Algin katkısı","a":"besin üretir","d":"Alg fotosentez yaparak ortak yaşam için besin üretir."},{"t":"Mantarın katkısı","a":"su ve mineral","d":"Mantar su ve mineral tutarak alge koruma ve nem sağlar."},{"t":"İlişki türü","a":"mutualizm","d":"İkisi de yarar gördüğü için bu bir mutualizm örneğidir."}],"ans":"Likende alg besin üretir, mantar su ve koruma sağlar; ikisi de yarar gördüğü için bu bir mutualizmdir."},
{"q":"Köpekbalığının yanında yüzen ve artıklarını yiyen küçük balıkların ilişkisi hangi türdür?","steps":[{"t":"Küçük balığın durumu","a":"yarar görür","d":"Küçük balık köpekbalığının yemek artıklarını yiyerek beslenir."},{"t":"Köpekbalığının durumu","a":"etkilenmez","d":"Köpekbalığı bu durumdan ne yarar görür ne de zarar."},{"t":"İlişki türü","a":"komensalizm","d":"Biri yarar görüp diğeri etkilenmediği için bu komensalizmdir."}],"ans":"Küçük balık artıkları yiyerek yarar görür, köpekbalığı etkilenmez; bu komensalizmdir."},
{"q":"Bir bölgede kurtlar yok edilirse geyik sayısı neden önce artar, sonra sorun çıkarır?","steps":[{"t":"Avcı yok","a":"baskı kalkar","d":"Kurtlar gidince geyikleri avlayan baskı ortadan kalkar."},{"t":"Aşırı artış","a":"geyik çoğalır","d":"Avlanmadıkları için geyik sayısı hızla artar."},{"t":"Sonuç","a":"bitki tükenir","d":"Çok sayıda geyik bitkileri aşırı yer, besin tükenir ve geyikler aç kalır."}],"ans":"Avcı kurt olmayınca geyik aşırı çoğalır, bitkileri tüketir ve sonunda besin yetmediği için zorluk yaşanır; avcı popülasyonu dengede tutar."},
{"q":"Bağırsak solucanı ile insan arasındaki parazitlik ilişkisini taraflar açısından değerlendiriniz.","steps":[{"t":"Solucanın durumu","a":"besin alır","d":"Solucan insanın bağırsağındaki hazır besinden pay alarak beslenir."},{"t":"İnsanın durumu","a":"zarar görür","d":"İnsan besin kaybeder, halsizleşir ve hastalanabilir."},{"t":"İlişki türü","a":"parazitlik","d":"Biri yarar, diğeri zarar gördüğü için bu bir parazitlik ilişkisidir."}],"ans":"Solucan hazır besinden yarar görür, insan besin kaybedip zarar görür; bu bir parazitlik (iç parazit) ilişkisidir."},
{"q":"Baklagil bitkisi ile köklerindeki azot bakterileri arasındaki ilişkiyi açıklayınız.","steps":[{"t":"Bakterinin katkısı","a":"azot sağlar","d":"Bakteriler havadaki azotu bitkinin kullanabileceği biçime dönüştürür."},{"t":"Bitkinin katkısı","a":"besin ve yer","d":"Bitki, bakterilere besin ve köklerinde barınma yeri sağlar."},{"t":"İlişki türü","a":"mutualizm","d":"İkisi de yarar gördüğü için bu bir mutualizm örneğidir."}],"ans":"Bakteri bitkiye azot sağlar, bitki bakteriye besin ve barınak verir; ikisi de yarar gördüğü için mutualizmdir."}
]},"lise":{"kolay":[
{"q":"Türler arası ilişkilerde +/− gösterimi neyi ifade eder?","steps":[{"t":"Artı işareti","a":"yarar","d":"+ işareti, ilişkiden o türün yarar (fayda) gördüğünü belirtir."},{"t":"Eksi ve sıfır","a":"zarar ve nötr","d":"− işareti zararı, 0 işareti ise etkilenmemeyi (nötr) gösterir."}],"ans":"+ yararı, − zararı, 0 ise etkilenmemeyi gösterir; ilişkiler bu işaretlerle sınıflandırılır."},
{"q":"Mutualizm ilişkisini +/− gösterimiyle ifade ediniz.","steps":[{"t":"Taraf etkileri","a":"iki tarafa yarar","d":"Mutualizmde her iki tür de ilişkiden fayda sağlar."},{"t":"Gösterim","a":"(+ / +)","d":"İki tarafa da yarar olduğu için gösterim (+ / +) biçimindedir."}],"ans":"Mutualizm (+ / +) olarak gösterilir; her iki tür de yarar görür."},
{"q":"Komensalizm ilişkisini +/− gösterimiyle ifade ediniz.","steps":[{"t":"Taraf etkileri","a":"biri yarar biri nötr","d":"Komensalizmde bir tür yarar görür, diğeri etkilenmez."},{"t":"Gösterim","a":"(+ / 0)","d":"Yarar gören için +, etkilenmeyen için 0 yazılır."}],"ans":"Komensalizm (+ / 0) olarak gösterilir; bir tür yarar görür, diğeri etkilenmez."},
{"q":"Parazitlik ilişkisini +/− gösterimiyle ifade ediniz.","steps":[{"t":"Taraf etkileri","a":"parazit + konak −","d":"Parazit konaktan beslenerek yarar görür, konak zarar görür."},{"t":"Gösterim","a":"(+ / −)","d":"Parazit için +, konak için − yazılarak gösterilir."}],"ans":"Parazitlik (+ / −) olarak gösterilir; parazit yarar, konak zarar görür."},
{"q":"Rekabet (kompetisyon) ilişkisini +/− gösterimiyle ifade ediniz.","steps":[{"t":"Taraf etkileri","a":"iki tarafa zarar","d":"Sınırlı kaynak için yarışan her iki tür de kaynaktan kısıtlı pay alır."},{"t":"Gösterim","a":"(− / −)","d":"Her iki taraf da olumsuz etkilendiği için (− / −) gösterilir."}],"ans":"Rekabet (− / −) olarak gösterilir; sınırlı kaynak yüzünden her iki tür de zarar görür."},
{"q":"Av-avcı (predasyon) ilişkisinde tarafların etkilerini belirtiniz.","steps":[{"t":"Avcının durumu","a":"yarar (+)","d":"Avcı, avı yakalayıp tükettiği için besin kazanır."},{"t":"Avın durumu","a":"zarar (−)","d":"Av yendiği için bireysel olarak zarar görür."}],"ans":"Av-avcı ilişkisi (+ / −) biçimindedir; avcı yarar görür, av zarar görür."},
{"q":"Amensalizm ilişkisi nedir, taraflar nasıl etkilenir?","steps":[{"t":"Bir tarafın etkisi","a":"zarar (−)","d":"Bir tür, ürettiği maddeyle diğerinin gelişimini engeller veya zarar verir."},{"t":"Diğer tarafın etkisi","a":"etkilenmez (0)","d":"Zarar veren tür bu ilişkiden ne yarar ne zarar görür, nötrdür."}],"ans":"Amensalizm (− / 0) biçimindedir; bir tür zarar görürken diğeri hiç etkilenmez."},
{"q":"İç parazit ile dış parazit arasındaki fark nedir?","steps":[{"t":"İç parazit","a":"vücut içinde","d":"İç parazit konağın vücudunun içinde (örneğin bağırsakta) yaşar."},{"t":"Dış parazit","a":"vücut yüzeyinde","d":"Dış parazit konağın derisi veya tüyleri üzerinde yaşar (bit, pire)."}],"ans":"İç parazit konağın iç organlarında, dış parazit ise vücut yüzeyinde yaşar; ikisi de konaktan beslenir."},
{"q":"Mutualizm ile komensalizm arasındaki temel fark nedir?","steps":[{"t":"Mutualizm","a":"(+ / +)","d":"Mutualizmde her iki tür de ilişkiden yarar sağlar."},{"t":"Komensalizm","a":"(+ / 0)","d":"Komensalizmde yalnız bir tür yarar görür, diğeri etkilenmez."}],"ans":"Mutualizmde her iki taraf da yarar görür (+ / +), komensalizmde ise yalnızca bir taraf yarar görür, diğeri etkilenmez (+ / 0)."},
{"q":"Predasyon (av-avcı) ile parazitlik arasındaki temel fark nedir?","steps":[{"t":"Predasyon","a":"av öldürülür","d":"Avcı avını genellikle hızla öldürerek tüketir."},{"t":"Parazitlik","a":"konak yaşar","d":"Parazit konağı genellikle hemen öldürmez, ondan uzun süre beslenir."}],"ans":"Predasyonda av yakalanıp öldürülür; parazitlikte konak çoğunlukla canlı kalır ve parazit ondan sürekli beslenir."},
{"q":"Mutualizmde 'zorunlu' ve 'isteğe bağlı' ortaklık ne anlama gelir?","steps":[{"t":"Zorunlu mutualizm","a":"biri olmadan yaşayamaz","d":"Zorunlu (obligat) mutualizmde türler birbiri olmadan yaşayamaz (likendeki mantar-alg)."},{"t":"İsteğe bağlı","a":"ayrı da yaşar","d":"İsteğe bağlı (fakültatif) mutualizmde türler ayrı da yaşayabilir ama birlikte daha avantajlıdır."}],"ans":"Zorunlu mutualizmde türler birbiri olmadan yaşayamaz; isteğe bağlı mutualizmde ayrı yaşayabilirler ama birliktelik avantaj sağlar."},
{"q":"Konak (host) kavramı parazitlikte neyi ifade eder?","steps":[{"t":"Konağın tanımı","a":"barındıran canlı","d":"Konak, parazitin üzerinde veya içinde yaşadığı, ondan beslendiği canlıdır."},{"t":"Konağın etkisi","a":"zarar görür","d":"Konak besin ve enerji kaybeder, bu yüzden zarar gören taraftır."}],"ans":"Konak, parazitin üzerinde veya içinde yaşayıp beslendiği canlıdır ve parazitlikten zarar gören taraftır."},
{"q":"Ekosistemde av-avcı ilişkisinin denge sağlayıcı rolü nedir?","steps":[{"t":"Av sayısı artışı","a":"avcıya bol besin","d":"Av popülasyonu artınca avcılar bol besin bulup çoğalır."},{"t":"Avcı baskısı","a":"avı azaltır","d":"Çoğalan avcılar avı daha çok tüketerek sayısını düşürür."},{"t":"Geri dönüş","a":"dengeye gelir","d":"Av azalınca avcı da azalır; iki popülasyon birbirini dengede tutar."}],"ans":"Av ve avcı popülasyonları birbirini izleyerek dalgalanır; bu karşılıklı denetim ekosistemde sayısal dengeyi korur."},
{"q":"Temizleyici (ortakçı) balıkların büyük balıklarla ilişkisi hangi türdür ve neden?","steps":[{"t":"Temizleyicinin kazancı","a":"besin","d":"Temizleyici balık, büyük balığın derisindeki parazit ve ölü dokuyu yiyerek beslenir."},{"t":"Büyük balığın kazancı","a":"temizlenir","d":"Büyük balık parazitlerden arınır, böylece sağlığı korunur."}],"ans":"Bu bir mutualizmdir; temizleyici balık besin bulur, büyük balık parazitlerden temizlenir, her iki taraf da yarar görür."},
{"q":"Allelopati olayı hangi türler arası ilişkiyle ilgilidir?","steps":[{"t":"Allelopatinin tanımı","a":"kimyasal salgı","d":"Bir bitki, salgıladığı kimyasal maddelerle çevresindeki başka bitkilerin gelişimini engeller."},{"t":"Etki yönü","a":"biri zarar biri nötr","d":"Engellenen bitki zarar görür, salgılayan bitki bu durumdan etkilenmez."}],"ans":"Allelopati bir amensalizm örneğidir (− / 0); salgılanan kimyasal komşu bitkiye zarar verirken salgılayan tür etkilenmez."}
],"zor":[
{"q":"Yarış (rekabet) iki tür arasında türler arası, aynı tür içinde tür içi olabilir; bu ayrımın ekolojik sonucu nedir?","steps":[{"t":"Tür içi rekabet","a":"aynı tür","d":"Aynı türün bireyleri tamamen aynı kaynağı kullandığından rekabet çok şiddetlidir."},{"t":"Türler arası rekabet","a":"farklı tür","d":"Farklı türler kaynakların yalnız bir kısmında çakışır, rekabet daha sınırlıdır."},{"t":"Sonuç","a":"niş ayrışması","d":"Şiddetli rekabet, türleri farklı niş kullanmaya iter; buna niş ayrışması denir."}],"ans":"Tür içi rekabet aynı niş yüzünden daha şiddetlidir; türler arası rekabet ise niş ayrışmasına yol açarak türlerin bir arada yaşamasını sağlar."},
{"q":"Gause'un rekabetçi dışlama ilkesi (competitive exclusion) ne ifade eder?","steps":[{"t":"İlkenin tanımı","a":"aynı niş bir arada olmaz","d":"Aynı kaynağı tamamen aynı şekilde kullanan iki tür aynı yerde sürekli bir arada yaşayamaz."},{"t":"Sonuç","a":"biri dışlanır","d":"Daha verimli tür kaynağı ele geçirir, diğeri yerel olarak yok olur ya da göç eder."},{"t":"Kaçış yolu","a":"niş farklılaşması","d":"Türler kaynak kullanımını farklılaştırarak (niş ayrışması) bir arada kalabilir."}],"ans":"Rekabetçi dışlama ilkesine göre tam aynı nişi paylaşan iki tür uzun süre bir arada yaşayamaz; biri dışlanır ya da türler nişlerini farklılaştırır."},
{"q":"Ko-evrim (birlikte evrim) kavramını av-avcı ilişkisi üzerinden açıklayınız.","steps":[{"t":"Avcı baskısı","a":"seçilim","d":"Avcılar en yavaş, en savunmasız avları yakalar; hızlı/savunmalı bireyler hayatta kalır."},{"t":"Avın evrimi","a":"savunma gelişir","d":"Zamanla avda hız, kamuflaj veya zehir gibi savunmalar gelişir."},{"t":"Avcının yanıtı","a":"karşı uyum","d":"Avcıda da daha keskin duyu, hız veya zehir direnci gelişir; iki tür birbirini şekillendirir."}],"ans":"Ko-evrimde av üzerindeki avcı baskısı savunma özelliklerini seçer, avcı da bunlara karşı uyum geliştirir; iki tür karşılıklı olarak birbirinin evrimini yönlendirir."},
{"q":"Mutualizm ile parazitliğin sınırının her zaman keskin olmadığını bir örnekle açıklayınız.","steps":[{"t":"Koşula bağlı etki","a":"ortam değişir","d":"Bazı simbiyotik ilişkiler ortam koşullarına göre yararlı ya da zararlı hale gelebilir."},{"t":"Örnek","a":"bağırsak bakterileri","d":"Bağırsak bakterileri normalde sindirime yardım eder (mutualizm), bağışıklık zayıflayınca hastalık yapabilir (parazitlik)."},{"t":"Sonuç","a":"süreklilik","d":"Bu nedenle ilişkiler kesin kutular değil, bir süreklilik üzerinde yer alır."}],"ans":"İlişkiler koşula bağlı değişebilir; bağırsak bakterileri normalde mutualist iken konak zayıfladığında patojen (parazit) olabilir, yani sınır her zaman keskin değildir."},
{"q":"Endoparazit ile ektoparazitin konak üzerindeki etkilerini ve uyumlarını karşılaştırınız.","steps":[{"t":"Endoparazit","a":"iç organda","d":"Tenya gibi iç parazitler bağırsakta yaşar; sindirim sistemi körelmiş, üreme yetenekleri çok gelişmiştir."},{"t":"Ektoparazit","a":"yüzeyde","d":"Bit, kene gibi dış parazitler yüzeyde yaşar; tutunma organları ve kan emici ağız yapıları gelişmiştir."},{"t":"Ortak etki","a":"konağa zarar","d":"İkisi de konaktan besin/kan alarak ona zarar verir, hastalık taşıyabilir."}],"ans":"Endoparazitler iç organlarda yaşayıp körelmiş sindirim ve güçlü üremeye uyum gösterir; ektoparazitler yüzeyde tutunma ve kan emme yapılarına sahiptir; her ikisi de konağa zarar verir."},
{"q":"Bir mutualizm ilişkisi olan mikoriza (mantar-bitki kökü) ortaklığını madde alışverişi açısından açıklayınız.","steps":[{"t":"Mantarın katkısı","a":"su ve mineral","d":"Mantar hifleri kök yüzeyini genişleterek su ve mineral (özellikle fosfor) alımını artırır."},{"t":"Bitkinin katkısı","a":"organik besin","d":"Bitki fotosentezle ürettiği glikozu mantara aktarır."},{"t":"Sonuç","a":"karşılıklı yarar","d":"Madde alışverişiyle iki taraf da daha iyi beslenir; bu bir mutualizmdir."}],"ans":"Mikorizada mantar bitkiye su ve mineral sağlar, bitki mantara fotosentez ürünü organik besin verir; karşılıklı madde alışverişine dayanan bir mutualizmdir."},
{"q":"Predasyonun ekosistemde tür çeşitliliğini koruyabildiğini 'anahtar taşı tür' (keystone) kavramıyla açıklayınız.","steps":[{"t":"Anahtar avcı","a":"baskın avı denetler","d":"Anahtar taşı avcı, ortamda baskınlaşma eğilimindeki türü avlayarak sayısını sınırlar."},{"t":"Rekabetin azalması","a":"yer açılır","d":"Baskın tür kontrol altında tutulunca zayıf rakipler de yaşam alanı bulur."},{"t":"Sonuç","a":"çeşitlilik artar","d":"Böylece tek türün her şeyi ele geçirmesi engellenir, tür çeşitliliği korunur."}],"ans":"Anahtar taşı avcı, baskınlaşacak avı denetleyerek rekabeti azaltır ve daha fazla türe yaşam alanı bırakır; böylece predasyon tür çeşitliliğini koruyabilir."},
{"q":"Lotka-Volterra modelinde av ve avcı popülasyonlarının grafikte neden gecikmeli (faz farklı) dalgalandığını açıklayınız.","steps":[{"t":"Av artışı","a":"avcıdan önce","d":"Av bol olunca önce av sayısı yükselir."},{"t":"Avcı yanıtı","a":"gecikmeli artış","d":"Avcı, bol avla beslenip ürediği için biraz gecikmeyle artar."},{"t":"Çöküş sırası","a":"av önce düşer","d":"Çok avcı avı tüketince önce av azalır, ardından besinsiz kalan avcı azalır."}],"ans":"Avcı, av artışına ancak üreyerek gecikmeyle yanıt verdiği için iki eğri faz farkıyla dalgalanır; av zirvesini avcı zirvesi gecikmeli olarak izler."},
{"q":"Komensalizm örneklerinde 'etkisiz' tarafın gerçekte hafifçe etkilenebileceği eleştirisi nedir?","steps":[{"t":"Klasik tanım","a":"(+ / 0)","d":"Komensalizmde bir tür yarar görür, diğeri etkilenmez kabul edilir."},{"t":"Gerçek durum","a":"hafif etki olabilir","d":"Örneğin dala yuva yapan kuş ağaca çok küçük bir yük veya yarar getirebilir."},{"t":"Sonuç","a":"yaklaşık nötr","d":"Etki ölçülemeyecek kadar küçük olduğunda pratikte 0 kabul edilir."}],"ans":"Saf nötr etki nadirdir; etkilenmeyen tarafta çoğu zaman çok küçük bir etki bulunur, ancak ihmal edilebilir düzeyde olduğu için komensalizm (+ / 0) kabul edilir."},
{"q":"Çiçekli bitki ile tozlaştırıcı böcek arasındaki ko-evrimsel uyuma bir örnek veriniz.","steps":[{"t":"Bitkinin uyumu","a":"derin nektar","d":"Bazı orkidelerin nektarı çok derin bir borucukta bulunur."},{"t":"Böceğin uyumu","a":"uzun hortum","d":"Bu nektara ulaşan kelebek/güvelerde olağanüstü uzun bir emme hortumu gelişmiştir."},{"t":"Karşılıklı seçilim","a":"birlikte evrim","d":"Bitki daha derin nektarla en uygun tozlaştırıcıyı seçer, böcek de daha uzun hortumla buna uyar."}],"ans":"Derin nektarlı orkide ile uzun hortumlu güve örneğinde, bitki ve tozlaştırıcı birbirinin yapısını karşılıklı seçilimle şekillendirmiştir; bu bir ko-evrim örneğidir."},
{"q":"Aynı kaynağı kullanan iki türün bir arada kalabilmesini sağlayan 'kaynak bölüşümü' (resource partitioning) nasıl işler?","steps":[{"t":"Çakışma sorunu","a":"aynı kaynak","d":"İki tür aynı besin veya alan için yarışırsa rekabet şiddetlenir."},{"t":"Bölüşüm","a":"farklı kullanım","d":"Türler kaynağı zaman, yer veya boyut bakımından farklı kullanarak çakışmayı azaltır."},{"t":"Örnek","a":"farklı dal yüksekliği","d":"Aynı ağaçta beslenen ötücü kuşların farklı dal yüksekliklerini kullanması gibi."}],"ans":"Kaynak bölüşümünde türler aynı kaynağı zaman, yer veya boyut bakımından farklı kullanarak rekabeti azaltır; böylece niş ayrışmasıyla bir arada yaşayabilirler."},
{"q":"Bir parazitin konağını hemen öldürmemesi neden evrimsel olarak avantajlıdır?","steps":[{"t":"Konağın işlevi","a":"besin ve yaşam alanı","d":"Konak, parazit için hem sürekli besin kaynağı hem de yaşam ortamıdır."},{"t":"Erken ölüm","a":"parazite zarar","d":"Konak hemen ölürse parazit hem besin kaynağını hem üreme/yayılma fırsatını kaybeder."},{"t":"Seçilim","a":"ılımlı zarar","d":"Konağı yaşatan, daha az öldürücü parazit soyları daha çok yayılır ve seçilir."}],"ans":"Konak parazite sürekli besin ve yayılma fırsatı sağladığından, konağı yaşatan daha az öldürücü parazitler evrimsel olarak avantajlıdır ve doğal seçilimle çoğalır."},
{"q":"Mutualizmin bazen 'aldatma' (cheating) ile bozulabileceğini bir örnekle açıklayınız.","steps":[{"t":"Normal mutualizm","a":"karşılıklı hizmet","d":"Çiçek nektar sunar, böcek de tozlaştırma hizmeti verir; iki taraf yarar görür."},{"t":"Aldatan taraf","a":"hizmet vermeden alır","d":"Bazı böcekler çiçeğin yanını delip nektarı çalar ama tozlaştırma yapmaz (nektar hırsızlığı)."},{"t":"Sonuç","a":"denge bozulur","d":"Hizmet vermeden yarar sağlayan aldatıcılar artarsa ortaklığın karşılıklı yararı zayıflar."}],"ans":"Nektar hırsızı böceklerin tozlaştırma yapmadan nektar çalması gibi durumlarda bir taraf hizmet vermeden yarar sağlar; bu aldatma, mutualizmin karşılıklı yarar dengesini bozabilir."},
{"q":"Bir ekosistemde üst düzey avcının (apex predator) yok olmasının zincirleme etkisini (trofik kaskad) açıklayınız.","steps":[{"t":"Avcı yok","a":"otçul artar","d":"Üst avcı kaybolunca onun avladığı otçul tür hızla çoğalır."},{"t":"Bitki baskısı","a":"bitki azalır","d":"Aşırı çoğalan otçullar bitki örtüsünü ağır biçimde tüketir."},{"t":"Zincirleme etki","a":"tüm sistem etkilenir","d":"Bitki azalması toprağı, su kaynaklarını ve diğer türleri de etkiler; etki tüm besin ağına yayılır."}],"ans":"Üst düzey avcı yok olunca otçullar artar, bitki örtüsü tükenir ve etki besin ağı boyunca yayılır; bu yukarıdan aşağıya zincirleme etkiye trofik kaskad denir."},
{"q":"Amensalizm ile rekabet arasındaki ayrımı etki yönü bakımından açıklayınız.","steps":[{"t":"Rekabet","a":"(− / −)","d":"Rekabette her iki tür de sınırlı kaynak yüzünden olumsuz etkilenir."},{"t":"Amensalizm","a":"(− / 0)","d":"Amensalizmde bir tür zarar görürken diğeri hiç etkilenmez."},{"t":"Ayrım noktası","a":"karşılıklılık","d":"Rekabette zarar karşılıklıdır; amensalizmde tek yönlüdür ve genelde kaynak yarışı değildir."}],"ans":"Rekabette zarar karşılıklıdır (− / −); amensalizmde ise zarar tek yönlüdür ve bir tür etkilenmez (− / 0); temel fark zararın karşılıklı olup olmamasıdır."}
]}}};
