globalThis.__OUT = {"pigmentler":{
"ilkokul":{
"kolay":[
{"q":"Yaprakların yeşil görünmesini sağlayan madde nedir?","steps":[{"t":"1. adım: Renkli madde","a":"Pigment","d":"Bitkilerin renklerini renk veren maddelere pigment denir."},{"t":"2. adım: Yeşil pigment","a":"Klorofil","d":"Yapraklarda en çok bulunan yeşil pigmentin adı klorofildir."}],"ans":"Yaprakları yeşil yapan madde <b>klorofil</b>dir."},
{"q":"Klorofil yaprağın hangi bölümünde bol bulunur?","steps":[{"t":"1. adım: Yaprağın yeşil kısmı","a":"Yaprak ayası","d":"Yaprağın yassı ve geniş yeşil bölümünde bol klorofil vardır."},{"t":"2. adım: Sonuç","a":"Yeşil yaprak dokusu","d":"Bu yüzden yaprağın geniş bölümü yemyeşil görünür."}],"ans":"Klorofil yaprağın <b>yeşil ayasında</b> bol bulunur."},
{"q":"Bitkiler güneş ışığını yakalamak için neyi kullanır?","steps":[{"t":"1. adım: Işığı yakalayan madde","a":"Klorofil","d":"Yeşil klorofil güneş ışığını yakalayıp bitkiye yardım eder."},{"t":"2. adım: Ne işe yarar","a":"Besin yapımı","d":"Yakalanan ışıkla bitki kendi besinini üretir."}],"ans":"Bitkiler ışığı yakalamak için <b>klorofil</b> kullanır."},
{"q":"Bir yaprağın rengi neden çoğu zaman yeşildir?","steps":[{"t":"1. adım: İçindeki pigment","a":"Bol klorofil","d":"Yaprakta çok miktarda yeşil klorofil bulunur."},{"t":"2. adım: Görünen renk","a":"Yeşil","d":"Klorofil çok olunca yaprak bize yeşil görünür."}],"ans":"Yaprak çok <b>klorofil</b> taşıdığı için yeşil görünür."},
{"q":"Havuçların turuncu rengini sağlayan boya maddesi de bir pigment midir?","steps":[{"t":"1. adım: Pigment nedir","a":"Renk maddesi","d":"Canlılara renk veren maddelere pigment denir."},{"t":"2. adım: Havuçtaki renk","a":"Turuncu pigment","d":"Havuçtaki turuncu renk de bir pigmenttir."}],"ans":"Evet, havucun turuncu rengi de bir <b>pigmenttir</b>."}
],
"zor":[
{"q":"Sonbaharda yapraklar neden sararıp kızarır?","steps":[{"t":"1. adım: Yeşil pigmentin azalması","a":"Klorofil azalır","d":"Hava soğuyunca yapraktaki yeşil klorofil yavaş yavaş yok olur."},{"t":"2. adım: Diğer renkler ortaya çıkar","a":"Sarı-turuncu pigment","d":"Klorofil gidince altta gizli duran sarı ve turuncu pigmentler görünür."}],"ans":"Klorofil azalınca sarı-turuncu pigmentler görünür ve yaprak <b>sararır</b>."},
{"q":"Yaprakların yeşili dışında başka renkleri de var mıdır?","steps":[{"t":"1. adım: Gizli pigmentler","a":"Var","d":"Yaprakta yeşil dışında sarı ve turuncu pigmentler de gizlidir."},{"t":"2. adım: Neden görünmezler","a":"Yeşil baskındır","d":"Klorofil çok olduğu için diğer renkleri örter."}],"ans":"Evet, yaprakta gizli <b>sarı ve turuncu</b> pigmentler de vardır."},
{"q":"Karanlıkta uzun süre kalan bir bitki neden sararır?","steps":[{"t":"1. adım: Işık gerekir","a":"Klorofil için ışık","d":"Bitkinin yeşil klorofili yapması için ışığa ihtiyacı vardır."},{"t":"2. adım: Işık olmazsa","a":"Klorofil yapılamaz","d":"Karanlıkta klorofil üretilemez, bitki soluk ve sarı kalır."}],"ans":"Işık olmayınca klorofil yapılamaz, bitki <b>sararır</b>."},
{"q":"Yeşil bir yaprağı suya koyup ısıtırsak su yeşile boyanabilir; bu neyi gösterir?","steps":[{"t":"1. adım: Renk nereden geldi","a":"Yapraktan","d":"Yapraktaki yeşil renk maddesi suya geçmiştir."},{"t":"2. adım: O madde nedir","a":"Klorofil","d":"Suyu yeşile boyayan madde yapraktaki klorofildir."}],"ans":"Bu, yaprakta <b>klorofil</b> adlı yeşil bir madde olduğunu gösterir."},
{"q":"Domates olgunlaşırken neden yeşilden kırmızıya döner?","steps":[{"t":"1. adım: Yeşil pigmentin gitmesi","a":"Klorofil azalır","d":"Domates olgunlaşırken içindeki yeşil klorofil kaybolur."},{"t":"2. adım: Kırmızı pigment artar","a":"Kırmızı pigment","d":"Aynı sırada kırmızı renk veren pigment çoğalır."}],"ans":"Klorofil azalıp kırmızı pigment artınca domates <b>kırmızı</b> olur."}
]
},
"ortaokul":{
"kolay":[
{"q":"Fotosentezde ışığı soğuran temel pigment hangisidir?","steps":[{"t":"1. adım: Pigment görevi","a":"Işığı soğurmak","d":"Pigmentler güneş ışığının enerjisini soğurur."},{"t":"2. adım: Temel pigment","a":"Klorofil","d":"Fotosentezde ışığı soğuran en önemli pigment klorofildir."}],"ans":"Fotosentezde ışığı soğuran temel pigment <b>klorofil</b>dir."},
{"q":"Klorofil hangi renkleri soğurur, hangi rengi yansıtır?","steps":[{"t":"1. adım: Soğurulan renkler","a":"Kırmızı ve mavi","d":"Klorofil ışığın kırmızı ve mavi kısmını soğurur."},{"t":"2. adım: Yansıyan renk","a":"Yeşil","d":"Yeşil ışığı soğurmaz, geri yansıtır; bu yüzden yeşil görürüz."}],"ans":"Klorofil <b>kırmızı ve maviyi</b> soğurur, <b>yeşili</b> yansıtır."},
{"q":"Klorofilin kaç çeşidi en çok bilinir?","steps":[{"t":"1. adım: Ana çeşitler","a":"İki çeşit","d":"Bitkilerde en çok klorofil a ve klorofil b bulunur."},{"t":"2. adım: Görevleri","a":"Işık soğurma","d":"İkisi de ışığı soğurur ama biraz farklı renklerde çalışır."}],"ans":"En çok bilinen iki çeşit <b>klorofil a ve klorofil b</b>dir."},
{"q":"Havuç ve kabağa turuncu-sarı renk veren pigment grubu nedir?","steps":[{"t":"1. adım: Renk grubu","a":"Karotenoidler","d":"Sarı, turuncu renk veren pigmentlere karotenoid denir."},{"t":"2. adım: Örnek","a":"Havuç","d":"Havucun turuncu rengi karotenoidlerden gelir."}],"ans":"Sarı-turuncu renk veren pigment grubu <b>karotenoidlerdir</b>."},
{"q":"Pigmentler fotosentez için neden gereklidir?","steps":[{"t":"1. adım: Enerji kaynağı","a":"Güneş ışığı","d":"Fotosentez için güneş enerjisi gerekir."},{"t":"2. adım: Enerjiyi yakalama","a":"Pigmentler soğurur","d":"Pigmentler ışık enerjisini soğurarak fotosenteze aktarır."}],"ans":"Pigmentler ışık enerjisini soğurduğu için fotosenteze <b>gereklidir</b>."}
],
"zor":[
{"q":"Bir yaprak neden hem klorofil hem karotenoid bulundurur?","steps":[{"t":"1. adım: Klorofilin sınırı","a":"Bazı renkleri kaçırır","d":"Klorofil özellikle yeşil bölgedeki ışığı pek soğuramaz."},{"t":"2. adım: Karotenoidin yardımı","a":"Farklı renkleri soğurur","d":"Karotenoidler klorofilin kaçırdığı bazı ışıkları soğurup ona aktarır."}],"ans":"Karotenoidler klorofilin soğuramadığı ışıkları yakalayıp <b>yardımcı olur</b>."},
{"q":"Sonbaharda yaprakların sararmasını pigmentlerle açıklayınız.","steps":[{"t":"1. adım: Klorofilin parçalanması","a":"Klorofil yıkılır","d":"Soğuk ve kısalan günlerle birlikte klorofil parçalanıp azalır."},{"t":"2. adım: Karotenoidlerin görünmesi","a":"Sarı renk ortaya çıkar","d":"Daha dayanıklı olan karotenoidler kalır ve yaprak sarı-turuncu görünür."}],"ans":"Klorofil azalınca dayanıklı <b>karotenoidler</b> görünür ve yaprak sararır."},
{"q":"Yaprağa beyaz ışık tuttuğumuzda neden yeşil rengi gözümüze ulaşır?","steps":[{"t":"1. adım: Beyaz ışığın içeriği","a":"Tüm renkler","d":"Beyaz ışık kırmızı, yeşil, mavi gibi tüm renkleri içerir."},{"t":"2. adım: Klorofilin seçimi","a":"Yeşili yansıtır","d":"Klorofil kırmızı-maviyi soğurur, yeşili yansıttığı için onu görürüz."}],"ans":"Klorofil yeşili soğurmayıp yansıttığı için göze <b>yeşil</b> ulaşır."},
{"q":"Klorofil a ile klorofil b arasındaki temel fark nedir?","steps":[{"t":"1. adım: Görev farkı","a":"a ana, b yardımcı","d":"Klorofil a esas iş gören pigment, klorofil b yardımcı pigmenttir."},{"t":"2. adım: Soğurma farkı","a":"Biraz farklı renk","d":"İkisi ışığın biraz farklı renklerini soğurarak birbirini tamamlar."}],"ans":"Klorofil a esas, <b>klorofil b</b> yardımcı pigmenttir ve farklı renkleri soğururlar."},
{"q":"Akvaryumdaki kırmızı bir su yosunu da fotosentez yapabilir mi?","steps":[{"t":"1. adım: Farklı pigment","a":"Kırmızı pigment","d":"Bazı yosunlarda klorofil yanında kırmızı renkli pigmentler de bulunur."},{"t":"2. adım: Sonuç","a":"Evet yapar","d":"Bu pigmentler suyun altına ulaşan ışığı soğurarak fotosentezi sürdürür."}],"ans":"Evet, farklı <b>pigmentleri</b> sayesinde kırmızı yosun da fotosentez yapar."}
]
},
"lise":{
"kolay":[
{"q":"Fotosentezde rol alan pigmentler hangi organelin hangi yapısında bulunur?","steps":[{"t":"1. adım: Organel","a":"Kloroplast","d":"Fotosentez pigmentleri kloroplast içinde yer alır."},{"t":"2. adım: Konum","a":"Tilakoit zarı","d":"Pigmentler tilakoit zarındaki fotosistemlere bağlıdır."}],"ans":"Pigmentler kloroplastın <b>tilakoit zarında</b> bulunur."},
{"q":"Klorofil a hangi renk bölgelerinde en güçlü soğurma yapar?","steps":[{"t":"1. adım: Mavi bölge","a":"≈430 nm","d":"Klorofil a mavi ışığı yaklaşık 430 nm civarında güçlü soğurur."},{"t":"2. adım: Kırmızı bölge","a":"≈660-680 nm","d":"Kırmızı ışığı da yaklaşık 660-680 nm civarında soğurur."}],"ans":"Klorofil a <b>mavi (≈430 nm)</b> ve <b>kırmızı (≈660 nm)</b> bölgelerde güçlü soğurur."},
{"q":"Yaprakların yeşil görünmesinin fiziksel nedeni nedir?","steps":[{"t":"1. adım: Soğurulan dalga boyları","a":"Mavi ve kırmızı","d":"Klorofiller ışığın mavi ve kırmızı bölgelerini soğurur."},{"t":"2. adım: Yansıyan dalga boyu","a":"Yeşil","d":"Yeşil (≈500-560 nm) bölgesi az soğurulup yansıtılır, gözümüze ulaşır."}],"ans":"Mavi-kırmızı soğurulup <b>yeşil yansıdığı</b> için yapraklar yeşil görünür."},
{"q":"Karotenoidler hangi renk bölgesinde ışık soğurur?","steps":[{"t":"1. adım: Soğurma bölgesi","a":"Mavi-yeşil","d":"Karotenoidler ışığın mavi ve mavi-yeşil bölgesini (≈400-500 nm) soğurur."},{"t":"2. adım: Görünen renk","a":"Sarı-turuncu","d":"Bu bölgeyi soğurup sarı-turuncuyu yansıttıkları için o renkte görünürler."}],"ans":"Karotenoidler <b>mavi-yeşil (≈400-500 nm)</b> bölgeyi soğurur, sarı-turuncuyu yansıtır."},
{"q":"Klorofil a ve klorofil b'nin işlevsel ayrımı nedir?","steps":[{"t":"1. adım: Klorofil a","a":"Reaksiyon merkezi","d":"Klorofil a, fotosistemin reaksiyon merkezinde doğrudan elektron verir."},{"t":"2. adım: Klorofil b","a":"Yardımcı (anten)","d":"Klorofil b yardımcı pigmenttir; soğurduğu enerjiyi klorofil a'ya aktarır."}],"ans":"Klorofil a <b>reaksiyon merkezi</b>, klorofil b ise <b>yardımcı</b> pigmenttir."},
{"q":"Aksesuar (yardımcı) pigmentlerin temel görevi nedir?","steps":[{"t":"1. adım: Görev","a":"Soğurma aralığını genişletmek","d":"Yardımcı pigmentler klorofil a'nın soğuramadığı dalga boylarını soğurur."},{"t":"2. adım: Enerji aktarımı","a":"Klorofil a'ya iletir","d":"Soğurdukları enerjiyi reaksiyon merkezindeki klorofil a'ya aktarırlar."}],"ans":"Yardımcı pigmentler farklı dalga boylarını soğurup enerjiyi <b>klorofil a'ya</b> aktarır."},
{"q":"Anten kompleksi (ışık toplayıcı kompleks) nedir?","steps":[{"t":"1. adım: Yapı","a":"Pigment topluluğu","d":"Çok sayıda pigment molekülünün bir araya geldiği toplayıcı yapıdır."},{"t":"2. adım: İşlev","a":"Enerjiyi toplar","d":"Soğurulan ışık enerjisini reaksiyon merkezine doğru aktarır."}],"ans":"Anten kompleksi, ışığı toplayıp enerjiyi <b>reaksiyon merkezine</b> ileten pigment topluluğudur."},
{"q":"Bir pigmentin absorpsiyon spektrumu neyi gösterir?","steps":[{"t":"1. adım: Tanım","a":"Soğurma-dalga boyu grafiği","d":"Pigmentin hangi dalga boyunda ne kadar ışık soğurduğunu gösteren grafiktir."},{"t":"2. adım: Yorum","a":"Pik bölgeler","d":"Grafikteki tepe noktaları pigmentin en çok soğurduğu renkleri belirtir."}],"ans":"Absorpsiyon spektrumu, pigmentin <b>dalga boyuna göre soğurma miktarını</b> gösterir."},
{"q":"Klorofil ışığın yeşil bölgesini neden zayıf soğurur?","steps":[{"t":"1. adım: Yapısal seçicilik","a":"Belirli enerji düzeyleri","d":"Klorofil yalnızca belirli enerjili (mavi-kırmızı) fotonları soğurur."},{"t":"2. adım: Sonuç","a":"Yeşili yansıtır","d":"Yeşil bölgenin enerjisi bu düzeylere uymadığı için soğurulmaz, yansır."}],"ans":"Yeşilin enerjisi klorofilin soğurma düzeyine uymadığı için <b>zayıf soğurulur</b>."},
{"q":"Ksantofil hangi pigment grubuna girer ve neye katkı sağlar?","steps":[{"t":"1. adım: Grup","a":"Karotenoid","d":"Ksantofiller oksijen içeren karotenoidlerdir, sarı renk verir."},{"t":"2. adım: Katkı","a":"Işık soğurma + koruma","d":"Hem ışık soğurur hem de fazla ışıkta klorofili korumaya yardım eder."}],"ans":"Ksantofil bir <b>karotenoid</b>dir; ışık soğurur ve klorofili korumaya katkı sağlar."},
{"q":"Etkinlik (aksiyon) spektrumu ile absorpsiyon spektrumu arasındaki ilişki nedir?","steps":[{"t":"1. adım: Absorpsiyon","a":"Soğurma","d":"Absorpsiyon spektrumu pigmentin soğurduğu dalga boylarını gösterir."},{"t":"2. adım: Aksiyon","a":"Fotosentez hızı","d":"Aksiyon spektrumu hangi dalga boyunda fotosentezin hızlandığını gösterir; ikisi büyük ölçüde örtüşür."}],"ans":"Pigmentin <b>soğurduğu</b> dalga boyları, fotosentezin <b>en hızlı</b> olduğu dalga boylarıyla örtüşür."},
{"q":"Sonbaharda yaprakların sararmasının pigment temeli nedir?","steps":[{"t":"1. adım: Klorofil yıkımı","a":"Klorofil parçalanır","d":"Kısalan günler ve soğukla klorofil parçalanıp azalır."},{"t":"2. adım: Karotenoid kalması","a":"Sarı görünür","d":"Daha kararlı karotenoidler kaldığı için yaprak sarı-turuncu görünür."}],"ans":"Klorofil yıkılınca kalan <b>karotenoidler</b> sayesinde yaprak sararır."},
{"q":"Neden fotosentez en çok mavi ve kırmızı ışıkta verimlidir?","steps":[{"t":"1. adım: Pigment soğurması","a":"Mavi-kırmızı pik","d":"Klorofiller en güçlü soğurmayı mavi ve kırmızı bölgede yapar."},{"t":"2. adım: Sonuç","a":"Yüksek verim","d":"Bu bölgelerde daha çok enerji soğurulduğu için fotosentez hızı artar."}],"ans":"Klorofil mavi-kırmızıyı güçlü soğurduğu için fotosentez bu renklerde <b>verimlidir</b>."},
{"q":"Karadeniz'de derin sularda yaşayan yosunların farklı pigment taşıması ne sağlar?","steps":[{"t":"1. adım: Derinlikte ışık","a":"Mavi-yeşil baskın","d":"Derin sulara çoğunlukla mavi-yeşil ışık ulaşır."},{"t":"2. adım: Pigment uyumu","a":"Bu ışığı soğurur","d":"Bu yosunların ek pigmentleri mavi-yeşil ışığı soğurarak fotosentez yapmasını sağlar."}],"ans":"Ek pigmentler derine ulaşan <b>mavi-yeşil ışığı</b> soğurarak fotosentezi sürdürür."},
{"q":"Pigment molekülü ışık soğurduğunda molekülde ne olur?","steps":[{"t":"1. adım: Elektron uyarılması","a":"Uyarılmış hâl","d":"Soğurulan foton enerjisiyle pigmentteki elektron üst enerji düzeyine çıkar."},{"t":"2. adım: Enerji aktarımı","a":"İletilir","d":"Bu enerji komşu pigmente ya da reaksiyon merkezine aktarılır."}],"ans":"Işık soğurulunca elektron <b>uyarılır</b> ve enerji reaksiyon merkezine aktarılır."}
],
"zor":[
{"q":"Anten kompleksindeki pigmentler enerjiyi nasıl reaksiyon merkezine taşır?","steps":[{"t":"1. adım: Yardımcı pigment soğurur","a":"Foton soğurma","d":"Karotenoid ve klorofil b gibi yardımcı pigmentler fotonu soğurup uyarılır."},{"t":"2. adım: Rezonans aktarımı","a":"Pigmentten pigmente","d":"Enerji, rezonansla komşu pigmentlere sıçrayarak ilerler."},{"t":"3. adım: Reaksiyon merkezi","a":"Klorofil a","d":"Enerji sonunda reaksiyon merkezindeki özelleşmiş klorofil a'ya ulaşır."}],"ans":"Yardımcı pigmentler soğurdukları enerjiyi <b>rezonansla</b> aktararak reaksiyon merkezindeki klorofil a'ya taşır."},
{"q":"Klorofil a ve klorofil b'nin absorpsiyon spektrumları neden tam üst üste değildir?","steps":[{"t":"1. adım: Yapı farkı","a":"Yan grup farkı","d":"Klorofil b'de bir metil grubu yerine aldehit grubu bulunur."},{"t":"2. adım: Soğurma kayması","a":"Pikler kayar","d":"Bu yapı farkı, soğurma piklerini biraz farklı dalga boylarına kaydırır."},{"t":"3. adım: İşlevsel kazanım","a":"Daha geniş aralık","d":"Böylece ikisi birlikte daha geniş bir ışık aralığını soğurur."}],"ans":"Yapı farkı pikleri kaydırdığı için ikisi birlikte <b>daha geniş</b> dalga boyu aralığını soğurur."},
{"q":"Karotenoidlerin yalnızca ışık soğurma dışında fotokoruma görevi nasıl gerçekleşir?","steps":[{"t":"1. adım: Aşırı uyarılma riski","a":"Üçlü klorofil","d":"Çok ışıkta klorofil tehlikeli uyarılmış (üçlü) hâle geçebilir."},{"t":"2. adım: Karotenoid söndürme","a":"Enerjiyi alır","d":"Karotenoid bu fazla enerjiyi alıp ısı olarak dağıtır."},{"t":"3. adım: Sonuç","a":"Hasar önlenir","d":"Böylece zararlı reaktif oksijen oluşumu ve klorofil hasarı önlenir."}],"ans":"Karotenoidler fazla enerjiyi söndürerek <b>reaktif oksijeni</b> ve klorofil hasarını önler."},
{"q":"Mor ışık altında tutulan yaprakta fotosentez hızı yeşil ışığa göre neden yüksektir?","steps":[{"t":"1. adım: Pigment soğurması","a":"Mor güçlü soğurulur","d":"Klorofil ve karotenoidler mor-mavi ışığı güçlü soğurur."},{"t":"2. adım: Yeşil zayıf","a":"Az soğurulur","d":"Yeşil ışık büyük ölçüde yansıtılır, az enerji soğurulur."},{"t":"3. adım: Hız farkı","a":"Mor hızlı","d":"Daha çok enerji soğurulduğu için mor ışıkta fotosentez hızı yüksektir."}],"ans":"Mor ışık güçlü soğurulduğundan, yeşile göre fotosentez hızı <b>yüksektir</b>."},
{"q":"Aksiyon spektrumunun yeşil bölgede sıfır olmaması neyi kanıtlar?","steps":[{"t":"1. adım: Klorofil zayıf","a":"Yeşili az soğurur","d":"Yalnız klorofil olsa yeşilde fotosentez neredeyse durmalıydı."},{"t":"2. adım: Yardımcı pigmentler","a":"Yeşili kısmen soğurur","d":"Karotenoidler ve diğer pigmentler yeşil bölgenin bir kısmını soğurur."},{"t":"3. adım: Kanıt","a":"Çoklu pigment","d":"Yeşilde hâlâ fotosentez olması, birden çok pigmentin katkısını kanıtlar."}],"ans":"Yeşilde fotosentez sürmesi, <b>yardımcı pigmentlerin</b> katkısını kanıtlar."},
{"q":"Engelmann'ın spirogyra deneyi pigmentlerin soğurması hakkında ne gösterir?","steps":[{"t":"1. adım: Düzenek","a":"Prizma + bakteri","d":"Yosun farklı renklere ayrılan ışığa konur, oksijen seven bakteriler eklenir."},{"t":"2. adım: Bakteri dağılımı","a":"Mavi-kırmızıda toplanır","d":"Bakteriler en çok oksijenin çıktığı mavi ve kırmızı ışık bölgesinde toplanır."},{"t":"3. adım: Sonuç","a":"Soğurma piki","d":"Bu, fotosentezin pigmentlerin güçlü soğurduğu renklerde en hızlı olduğunu gösterir."}],"ans":"Bakteriler mavi-kırmızıda toplanarak fotosentezin pigment <b>soğurma piklerinde</b> en hızlı olduğunu gösterir."},
{"q":"Klorofil molekülünün ışık soğurmasını sağlayan yapısal özelliği nedir?","steps":[{"t":"1. adım: Porfirin halkası","a":"Konjuge çift bağlar","d":"Klorofilin baş kısmında çok sayıda değişimli çift bağ içeren porfirin halkası vardır."},{"t":"2. adım: Elektron uyarılması","a":"Görünür ışık","d":"Bu konjuge sistemdeki elektronlar görünür ışık enerjisiyle kolayca uyarılır."},{"t":"3. adım: Sonuç","a":"Soğurma","d":"Bu yapı sayesinde klorofil mavi ve kırmızı ışığı verimle soğurur."}],"ans":"Porfirin halkasındaki <b>konjuge çift bağ sistemi</b> klorofilin görünür ışığı soğurmasını sağlar."},
{"q":"Bir bitkiye yalnızca yeşil ışık verilirse uzun vadede ne beklenir?","steps":[{"t":"1. adım: Soğurma azlığı","a":"Düşük enerji","d":"Yeşil ışık pigmentlerce az soğurulduğu için az enerji sağlanır."},{"t":"2. adım: Fotosentez düşer","a":"Az besin","d":"Düşük enerji nedeniyle fotosentez ve besin üretimi azalır."},{"t":"3. adım: Sonuç","a":"Zayıf büyüme","d":"Uzun vadede bitki zayıflar, büyümesi yavaşlar."}],"ans":"Yeşil az soğurulduğu için fotosentez düşer ve bitki <b>zayıf büyür</b>."},
{"q":"Fikobilinler gibi ek pigmentler kırmızı alglerde hangi avantajı sağlar?","steps":[{"t":"1. adım: Su ve ışık","a":"Derinde mavi-yeşil","d":"Suyun derininde özellikle mavi-yeşil ışık kalır."},{"t":"2. adım: Fikobilin soğurması","a":"Bu bölgeyi soğurur","d":"Fikobilinler klorofilin zayıf olduğu bu bölgeyi güçlü soğurur."},{"t":"3. adım: Avantaj","a":"Derinde fotosentez","d":"Böylece bu algler ışığın azaldığı derinliklerde fotosentez yapabilir."}],"ans":"Fikobilinler derine ulaşan <b>mavi-yeşil ışığı</b> soğurarak derinlikte fotosenteze olanak verir."},
{"q":"Soğurma spektrumunda iki klorofilin kırmızı bölge piklerinin yeşildeki çukurla ilişkisi nedir?","steps":[{"t":"1. adım: Kırmızı pikler","a":"Yüksek soğurma","d":"Klorofiller kırmızı bölgede yüksek soğurma piki gösterir."},{"t":"2. adım: Yeşil çukur","a":"Düşük soğurma","d":"Yeşil bölgede soğurma çukura iner, ışık çoğunlukla yansır."},{"t":"3. adım: İlişki","a":"Seçicilik","d":"Bu zıtlık, klorofilin belirli dalga boylarını seçici soğurduğunu gösterir; yeşil yansır, kırmızı tutulur."}],"ans":"Kırmızıdaki pik ve yeşildeki çukur, klorofilin <b>seçici soğurma</b> yaptığını ve yeşili yansıttığını gösterir."},
{"q":"Reaksiyon merkezi klorofili ile anten klorofili aynı molekül olsa da işlevleri neden farklıdır?","steps":[{"t":"1. adım: Aynı molekül","a":"Klorofil a","d":"İkisi de klorofil a'dır, kimyasal olarak aynıdır."},{"t":"2. adım: Çevre farkı","a":"Protein ortamı","d":"Reaksiyon merkezindeki klorofil özel proteinlere bağlıdır."},{"t":"3. adım: İşlev","a":"Elektron verme","d":"Bu özel ortam sayesinde yalnızca o klorofil uyarılınca elektron verebilir; antendekiler sadece enerji aktarır."}],"ans":"Bağlı oldukları <b>protein ortamı</b> farklı olduğu için reaksiyon merkezi klorofili elektron verir, antendekiler yalnızca enerji aktarır."},
{"q":"İki farklı pigment karışımının soğurma spektrumu tek pigmente göre neden daha geniştir?","steps":[{"t":"1. adım: Tek pigment","a":"Dar pikler","d":"Tek pigment yalnızca kendi dalga boylarını soğurur."},{"t":"2. adım: Karışım","a":"Pikler birleşir","d":"Farklı pigmentlerin pikleri üst üste binince soğurulan bölge genişler."},{"t":"3. adım: Sonuç","a":"Daha çok ışık","d":"Böylece güneş ışığının daha geniş bölümü fotosentezde kullanılabilir."}],"ans":"Farklı pigmentlerin pikleri birleştiği için karışım <b>daha geniş</b> dalga boyu aralığını soğurur."},
{"q":"Karotenoid bakımından zengin bir yaprakta ışık şiddeti çok yükseldiğinde ne gözlenir?","steps":[{"t":"1. adım: Aşırı ışık","a":"Hasar riski","d":"Yüksek ışık klorofili aşırı uyararak zarar verebilir."},{"t":"2. adım: Karotenoid devreye girer","a":"Enerji söndürme","d":"Karotenoidler fazla enerjiyi alıp ısıya çevirir."},{"t":"3. adım: Sonuç","a":"Koruma","d":"Bu sayede yaprak yüksek ışıkta daha az hasar görür."}],"ans":"Karotenoidler fazla enerjiyi söndürerek yaprağı yüksek ışık <b>hasarından korur</b>."},
{"q":"Klorofilin merkezindeki magnezyum iyonu çıkarılırsa pigmentin işlevi nasıl etkilenir?","steps":[{"t":"1. adım: Yapı bozulur","a":"Mg²⁺ çıkar","d":"Porfirin halkasının merkezindeki Mg²⁺ iyonu çıkarılınca yapı değişir."},{"t":"2. adım: Soğurma değişir","a":"Renk solar","d":"Magnezyumsuz molekül ışığı eskisi gibi soğuramaz, yeşil renk kahverengiye döner."},{"t":"3. adım: İşlev kaybı","a":"Fotosentez aksar","d":"Bu hâliyle enerjiyi etkili aktaramaz, fotosentezdeki görevi bozulur."}],"ans":"Mg²⁺ çıkınca soğurma bozulur, renk solar ve klorofilin fotosentezdeki <b>işlevi kaybolur</b>."},
{"q":"Bir laboratuvarda yaprak özütü kromatografi ile ayrılınca neden birden çok renkli bant oluşur?","steps":[{"t":"1. adım: Birden çok pigment","a":"Karışım","d":"Yaprak özütünde klorofil a, klorofil b, karotenoid ve ksantofil birlikte bulunur."},{"t":"2. adım: Farklı hareket","a":"Farklı hız","d":"Her pigment çözücüde farklı hızda ilerlediği için ayrı noktalarda toplanır."},{"t":"3. adım: Sonuç","a":"Renk bantları","d":"Bu nedenle yeşil, sarı ve turuncu farklı bantlar olarak görünür."}],"ans":"Yaprakta birden çok pigment olduğu ve farklı hızda ilerledikleri için <b>ayrı renk bantları</b> oluşur."}
]
}
}};
