globalThis.__OUT = {"etc":{"ilkokul":{"kolay":[
{"q":"Bitkinin yapraklarında, güneş ışığının enerjisini taşıyan küçük yollar vardır. Bu olay nerede gerçekleşir?","steps":[{"t":"Yaprağı düşün","a":"Yeşil yapraklar","d":"Bitkinin yeşil yaprakları güneş ışığını yakalar."},{"t":"İçindeki küçük fabrika","a":"Yaprağın içi","d":"Yaprağın içinde ışık enerjisini taşıyan minik yollar bulunur."}],"ans":"Bu olay yaprağın içinde gerçekleşir."},
{"q":"Güneş ışığı yaprağa düştüğünde enerjiye ne olur?","steps":[{"t":"Işık gelir","a":"Güneş ışığı","d":"Güneşten gelen ışık yaprağa ulaşır."},{"t":"Enerji taşınır","a":"Enerji aktarılır","d":"Işığın enerjisi yaprağın içinde bir yerden başka bir yere taşınır."}],"ans":"Işığın enerjisi yaprak içinde taşınır."},
{"q":"Yaprakta ışık enerjisi sonunda ne için kullanılır?","steps":[{"t":"Enerji toplanır","a":"Enerji","d":"Işıktan gelen enerji yaprakta toplanır."},{"t":"Besin yapılır","a":"Besin","d":"Bu enerjiyle bitki kendi besinini yapmaya hazırlanır."}],"ans":"Işık enerjisi bitkinin besin yapması için kullanılır."},
{"q":"Bir su borusunda su nasıl bir yerden başka yere akarsa, yaprakta da enerji öyle akar. Buna ne diyebiliriz?","steps":[{"t":"Akış fikri","a":"Akmak","d":"Su nasıl borudan akarsa, enerji de sırayla taşınır."},{"t":"Yaprakta akış","a":"Enerji akışı","d":"Yaprakta enerji bir noktadan diğerine akar."}],"ans":"Yaprakta enerji bir akış gibi taşınır."},
{"q":"Bitki bu enerjiyi yapraklarında saklayabilir mi?","steps":[{"t":"Enerji gelir","a":"Işık enerjisi","d":"Güneşten enerji gelir."},{"t":"Depolama","a":"Saklanır","d":"Bitki bu enerjiyi sonra kullanmak için biriktirir."}],"ans":"Evet, bitki enerjiyi saklayıp sonra kullanır."}
],"zor":[
{"q":"Yaprakta enerji taşınırken küçük 'taşıyıcılar' vardır. Bunlar enerjiyi ne yapar?","steps":[{"t":"Taşıyıcı nedir","a":"Yardımcı parça","d":"Enerjiyi elden ele aktaran küçük parçalardır."},{"t":"Ne yaparlar","a":"Enerjiyi taşır","d":"Enerjiyi bir taşıyıcıdan diğerine ulaştırırlar."}],"ans":"Taşıyıcılar enerjiyi elden ele aktarır."},
{"q":"Bir merdiven düşün; enerji basamak basamak iner. Yaprakta da enerji nasıl ilerler?","steps":[{"t":"Merdiven benzetmesi","a":"Basamaklar","d":"Enerji bir anda değil, basamak basamak hareket eder."},{"t":"Yaprakta","a":"Sırayla","d":"Yaprakta da enerji sırayla, adım adım taşınır."}],"ans":"Enerji yaprakta basamak basamak, sırayla taşınır."},
{"q":"Bu enerji taşıma sırasında bitki neyi biriktirir?","steps":[{"t":"Taşıma olur","a":"Enerji akar","d":"Enerji taşınırken bir şeyler de toplanır."},{"t":"Biriken şey","a":"Güç deposu","d":"Bitki bu sırada kullanacağı bir güç deposu hazırlar."}],"ans":"Bitki kullanacağı enerji deposunu biriktirir."},
{"q":"Yağmur damlaları bir oluktan akarken aşağıya iner. Yaprakta enerji taşınırken neye benzer bir şey olur?","steps":[{"t":"Akış","a":"Akmak","d":"Su gibi enerji de bir yönde akar."},{"t":"Sonuç","a":"Toplanma","d":"Akışın sonunda enerji belli bir yerde toplanır."}],"ans":"Enerji su gibi akar ve bir yerde toplanır."},
{"q":"Eğer güneş hiç doğmasaydı, yaprakta bu enerji taşıması olur muydu?","steps":[{"t":"Enerji kaynağı","a":"Güneş","d":"Enerjinin kaynağı güneş ışığıdır."},{"t":"Işık yoksa","a":"Taşıma durur","d":"Işık olmazsa taşınacak enerji de olmaz."}],"ans":"Hayır, ışık olmazsa enerji taşıması olmaz."}
]},"ortaokul":{"kolay":[
{"q":"Fotosentezde ışık enerjisini kullanan tepkimeler bitki hücresinin hangi yapısında olur?","steps":[{"t":"Yapıyı bul","a":"Kloroplast","d":"Fotosentez bitki hücresindeki kloroplastlarda gerçekleşir."},{"t":"İç zarlar","a":"Tilakoit","d":"Işık tepkimeleri kloroplast içindeki tilakoit zarlarında olur."}],"ans":"Işık enerjisi tepkimeleri tilakoit zarında gerçekleşir."},
{"q":"Tilakoit zarında elektronlar bir yapıdan diğerine taşınır. Bu olaya ne ad verilir?","steps":[{"t":"Elektron hareketi","a":"Taşınma","d":"Elektronlar zardaki yapılar arasında hareket eder."},{"t":"Adı","a":"Elektron taşıma zinciri","d":"Bu sıralı taşımaya elektron taşıma zinciri denir."}],"ans":"Bu olaya elektron taşıma zinciri denir."},
{"q":"Elektron taşıma zincirinde elektronlara enerji veren temel kaynak nedir?","steps":[{"t":"Kaynak","a":"Işık","d":"Güneş ışığı elektronları yüksek enerjili hale getirir."},{"t":"Sonuç","a":"Taşınma başlar","d":"Enerji alan elektronlar zincir boyunca taşınmaya başlar."}],"ans":"Elektronlara enerjiyi güneş ışığı verir."},
{"q":"Elektron taşıma zinciri sonunda bitki ne tür yararlı maddeler üretir?","steps":[{"t":"Taşıma sonucu","a":"Enerji","d":"Elektron taşıması enerji açığa çıkarır."},{"t":"Ürünler","a":"ATP","d":"Bu enerjiyle bitki için enerji parası olan ATP üretilir."}],"ans":"Elektron taşıma zinciri ATP üretimine yardım eder."},
{"q":"Elektronlar zincir boyunca taşınırken enerjileri genel olarak nasıl değişir?","steps":[{"t":"Başlangıç","a":"Yüksek enerji","d":"Elektronlar zincire yüksek enerjiyle girer."},{"t":"İlerleyiş","a":"Azalır","d":"Her basamakta biraz enerji kullanılır, elektron enerjisi azalır."}],"ans":"Elektronların enerjisi zincir boyunca giderek azalır."}
],"zor":[
{"q":"Tilakoit zarında elektron taşırken görev yapan hareketli bir taşıyıcı molekül hangisidir?","steps":[{"t":"Taşıyıcı kavramı","a":"Mekik molekül","d":"Bazı moleküller elektronu bir yapıdan alıp diğerine taşır."},{"t":"Örnek","a":"Plastokinon (PQ)","d":"Plastokinon elektronları bir kompleksten diğerine taşıyan mekiktir."}],"ans":"Plastokinon (PQ) elektron taşıyan hareketli bir moleküldür."},
{"q":"Elektron taşıma zincirinde elektronlar hangi yönde, hangi sistemden hangisine akar?","steps":[{"t":"Başlangıç","a":"Fotosistem II","d":"Elektronlar ilk olarak fotosistem II'den ayrılır."},{"t":"Varış","a":"Fotosistem I","d":"Elektronlar zincir üzerinden fotosistem I'e doğru akar."}],"ans":"Elektronlar fotosistem II'den fotosistem I'e doğru akar."},
{"q":"Elektronlar taşınırken tilakoit boşluğuna (lümen) hangi parçacıklar pompalanır?","steps":[{"t":"Taşıma enerjisi","a":"Enerji açığa çıkar","d":"Elektron taşınırken açığa çıkan enerji bir işi yapar."},{"t":"Pompalanan","a":"H⁺ (proton)","d":"Bu enerjiyle hidrojen iyonları (H⁺) lümene pompalanır."}],"ans":"Tilakoit boşluğuna H⁺ (proton) pompalanır."},
{"q":"Tilakoit boşluğunda H⁺ birikmesi neden önemlidir?","steps":[{"t":"Birikme","a":"H⁺ yoğunlaşır","d":"Lümende H⁺ derişimi artar, bir yoğunluk farkı oluşur."},{"t":"Yarar","a":"ATP üretimi","d":"Bu yoğunluk farkı ATP üretiminde kullanılır."}],"ans":"Lümende biriken H⁺, ATP üretimi için enerji farkı sağlar."},
{"q":"Elektron taşıma zincirinde fotosistem II ile fotosistem I arasında köprü görevi gören kompleks hangisidir?","steps":[{"t":"Aradaki yapı","a":"Bir kompleks","d":"İki fotosistem arasında elektronu aktaran bir yapı vardır."},{"t":"Adı","a":"Sitokrom b6f","d":"Sitokrom b6f kompleksi elektronu PSII tarafından alıp PSI yönüne aktarır."}],"ans":"İki fotosistem arasındaki köprü sitokrom b6f kompleksidir."}
]},"lise":{"kolay":[
{"q":"Fotosentezde elektron taşıma zinciri (ETZ) kloroplastın tam olarak hangi yapısında yer alır?","steps":[{"t":"Bölge","a":"Kloroplast","d":"Fotosentezin ışık tepkimeleri kloroplastta gerçekleşir."},{"t":"Zar","a":"Tilakoit zarı","d":"ETZ bileşenleri tilakoit zarına gömülü olarak bulunur."}],"ans":"Elektron taşıma zinciri tilakoit zarında bulunur."},
{"q":"Tilakoit zarındaki elektron taşıma zincirinde elektronlar hangi fotosistemden başlayarak akar?","steps":[{"t":"Başlangıç noktası","a":"PSII","d":"Doğrusal akışta elektronlar fotosistem II'den (PSII) köken alır."},{"t":"Yön","a":"PSI'e doğru","d":"Elektronlar PSII'den PSI'e doğru taşınır."}],"ans":"Elektronlar PSII'den başlayıp PSI'e akar."},
{"q":"Plastokinon (PQ) elektron taşıma zincirinde hangi görevi üstlenir?","steps":[{"t":"Tür","a":"Hareketli taşıyıcı","d":"PQ lipit fazda hareket edebilen küçük bir mekik moleküldür."},{"t":"Görev","a":"PSII → b6f","d":"Elektronu PSII'den sitokrom b6f kompleksine taşır."}],"ans":"PQ, elektronu PSII'den sitokrom b6f'e taşıyan hareketli taşıyıcıdır."},
{"q":"Plastosiyanin (PC) elektron taşıma zincirinde hangi iki yapı arasında elektron taşır?","steps":[{"t":"Konum","a":"Lümen yüzeyi","d":"PC tilakoit lümeninde bulunan bakır içeren bir proteindir."},{"t":"Görev","a":"b6f → PSI","d":"Elektronu sitokrom b6f kompleksinden PSI'e taşır."}],"ans":"PC, elektronu sitokrom b6f kompleksinden PSI'e taşır."},
{"q":"Sitokrom b6f kompleksi elektron taşıma zincirinde nasıl bir konumda bulunur?","steps":[{"t":"Konum","a":"PSII ile PSI arası","d":"b6f, iki fotosistem arasında yer alan bir zar kompleksidir."},{"t":"Görev","a":"Elektron aktarımı + H⁺ pompası","d":"Elektronu PQ'dan alıp PC'ye verir ve H⁺ pompalar."}],"ans":"Sitokrom b6f, PSII ile PSI arasında yer alıp elektronu aktarır ve H⁺ pompalar."},
{"q":"Elektron taşıma zincirinde elektronlar zincir boyunca ilerlerken enerjileri nasıl değişir?","steps":[{"t":"Giriş","a":"Yüksek enerji","d":"Işıkla uyarılan elektronlar zincire yüksek enerjili girer."},{"t":"Akış","a":"Kademeli düşüş","d":"Her redoks basamağında enerji düşer; açığa çıkan enerji H⁺ pompalar."}],"ans":"Elektronların enerjisi zincir boyunca kademeli olarak azalır."},
{"q":"Elektron taşıma zincirinde açığa çıkan enerji öncelikle hangi işte kullanılır?","steps":[{"t":"Enerji kaynağı","a":"Redoks basamakları","d":"Elektron aktarımındaki enerji düşüşü iş yapacak enerjiyi sağlar."},{"t":"Kullanım","a":"H⁺ pompalama","d":"Bu enerji ile H⁺ stromadan lümene pompalanır."}],"ans":"Açığa çıkan enerji H⁺'nin lümene pompalanmasında kullanılır."},
{"q":"Elektron taşıma sırasında protonlar (H⁺) hangi bölmeye doğru pompalanır?","steps":[{"t":"Bölmeler","a":"Stroma / lümen","d":"Tilakoit zarı stroma ile lümeni ayırır."},{"t":"Yön","a":"Lümene","d":"H⁺ stromadan tilakoit lümenine pompalanır."}],"ans":"Protonlar tilakoit lümenine doğru pompalanır."},
{"q":"Tilakoit lümeninde H⁺ birikmesi sonucu ne oluşur?","steps":[{"t":"Birikim","a":"H⁺ derişimi artar","d":"Lümende H⁺ yoğunluğu stromaya göre yükselir."},{"t":"Sonuç","a":"Proton gradyanı","d":"Zarın iki yanı arasında bir proton (H⁺) gradyanı doğar."}],"ans":"Lümende H⁺ birikmesi bir proton gradyanı oluşturur."},
{"q":"Proton gradyanının enerjisi sonunda hangi molekülün üretiminde kullanılır?","steps":[{"t":"Gradyan","a":"H⁺ enerjisi","d":"Lümen-stroma arası H⁺ farkı potansiyel enerji depolar."},{"t":"Kullanım","a":"ATP","d":"ATP sentaz bu enerjiyi kullanarak ATP üretir."}],"ans":"Proton gradyanının enerjisi ATP üretiminde kullanılır."},
{"q":"PSII'den ayrılan elektronların yerine gelen elektronlar nereden sağlanır?","steps":[{"t":"Eksik elektron","a":"PSII açığı","d":"Işıkla elektron kaybeden PSII'nin elektron açığı kapanmalıdır."},{"t":"Kaynak","a":"Suyun ayrışması","d":"Su molekülünün parçalanmasıyla açığa çıkan elektronlar PSII'ye gelir."}],"ans":"PSII'nin elektron açığı suyun ayrışmasıyla giderilir."},
{"q":"Elektron taşıma zincirinin sonunda PSI'den ayrılan elektronlar hangi moleküle aktarılır?","steps":[{"t":"Son alıcı","a":"NADP⁺","d":"Doğrusal akışta son elektron alıcısı NADP⁺'dir."},{"t":"Ürün","a":"NADPH","d":"NADP⁺ elektron ve H⁺ alarak NADPH'ye indirgenir."}],"ans":"PSI'den çıkan elektronlar NADP⁺'ye aktarılıp NADPH oluşturur."},
{"q":"Plastokinon (PQ) elektron taşırken zarda nasıl hareket eder?","steps":[{"t":"Yapı","a":"Lipitte çözünür","d":"PQ yağ fazında çözünebilen küçük bir moleküldür."},{"t":"Hareket","a":"Zar içinde difüzyon","d":"Tilakoit zarı içinde yana doğru difüzyonla hareket eder."}],"ans":"PQ tilakoit zarı içinde difüzyonla hareket ederek elektron taşır."},
{"q":"Elektron taşıma zinciri 'zincir' olarak adlandırılırken hangi temel özelliği vurgulanır?","steps":[{"t":"Zincir benzetmesi","a":"Sıralı bileşenler","d":"Bileşenler belirli bir sırayla dizilmiştir."},{"t":"Aktarım","a":"Ardışık redoks","d":"Elektron her bileşene sırayla aktarılır."}],"ans":"Elektronun ardışık olarak bileşenden bileşene aktarılması vurgulanır."},
{"q":"Plastosiyanin (PC) yapısında elektron taşımasını sağlayan element hangisidir?","steps":[{"t":"Protein türü","a":"Metalloprotein","d":"PC, içinde metal iyonu bulunan küçük bir proteindir."},{"t":"Element","a":"Bakır (Cu)","d":"PC, bakır iyonunun yükseltgenip indirgenmesiyle elektron taşır."}],"ans":"Plastosiyanin elektron taşımasını bakır (Cu) iyonu ile sağlar."}
],"zor":[
{"q":"Doğrusal elektron akışında elektronların izlediği bileşen sırası nasıldır?","steps":[{"t":"Başlangıç","a":"H₂O → PSII","d":"Su ayrışır, elektron PSII'ye, oradan ışıkla uyarılıp feofitine geçer."},{"t":"Orta zincir","a":"PQ → b6f → PC","d":"Elektron plastokinon, sitokrom b6f ve plastosiyanin üzerinden ilerler."},{"t":"Son","a":"PSI → NADP⁺","d":"PSI'de tekrar uyarılan elektron ferredoksin yoluyla NADP⁺'ye aktarılır."}],"ans":"Sıra: H₂O → PSII → PQ → b6f → PC → PSI → NADP⁺ (NADPH)."},
{"q":"Sitokrom b6f kompleksi neden proton gradyanına PSII'den daha fazla katkı sağlayabilir?","steps":[{"t":"Q-çevrimi","a":"PQ döngüsü","d":"b6f'te plastokinol oksidasyonu Q-çevrimi ile gerçekleşir."},{"t":"Ek pompalama","a":"Fazla H⁺","d":"Q-çevrimi her elektron için lümene ek H⁺ taşınmasını sağlar."}],"ans":"Q-çevrimi sayesinde b6f, lümene fazladan H⁺ pompalayarak gradyana güçlü katkı verir."},
{"q":"Plastokinonun (PQ) hem elektron hem proton taşıması gradyan oluşumuna nasıl katkı sağlar?","steps":[{"t":"İndirgenme","a":"Stroma yüzeyi","d":"PQ, PSII'den 2 elektron ve stromadan 2 H⁺ alarak PQH₂ olur."},{"t":"Yükseltgenme","a":"Lümen yüzeyi","d":"PQH₂, b6f'te yükseltgenir; aldığı H⁺'leri lümene bırakır."}],"ans":"PQ, H⁺'leri stromadan alıp lümene bırakarak proton gradyanını besler."},
{"q":"Elektron taşıma zincirindeki bileşenler neden belirli bir sırayla dizilmiştir?","steps":[{"t":"İlke","a":"Redoks potansiyeli","d":"Her bileşenin elektron çekme eğilimi (redoks potansiyeli) farklıdır."},{"t":"Dizilim","a":"Artan potansiyel","d":"Elektron, düşük potansiyelden yüksek potansiyelli bileşene kendiliğinden akar."}],"ans":"Bileşenler artan redoks potansiyeline göre dizildiği için elektron akışı kendiliğinden olur."},
{"q":"Tilakoit lümeni ile stroma arasındaki proton gradyanı hangi iki bileşenden oluşur?","steps":[{"t":"Birinci bileşen","a":"Kimyasal gradyan (ΔpH)","d":"Lümende H⁺ derişimi yüksek olduğundan pH farkı oluşur."},{"t":"İkinci bileşen","a":"Elektriksel gradyan","d":"Yük ayrımı zar boyunca bir elektriksel potansiyel yaratır."}],"ans":"Proton gradyanı kimyasal (ΔpH) ve elektriksel potansiyel farkının toplamından oluşur."},
{"q":"PSII'de oluşan elektron açığının suyla kapatılması sırasında lümene ne katkıda bulunulur?","steps":[{"t":"Suyun ayrışması","a":"2H₂O → O₂ + 4H⁺ + 4e⁻","d":"Su ayrışması lümen tarafında gerçekleşir."},{"t":"Gradyana katkı","a":"Lümene H⁺","d":"Açığa çıkan H⁺ doğrudan lümende kalarak gradyanı artırır."}],"ans":"Suyun ayrışmasıyla açığa çıkan H⁺ lümende birikerek proton gradyanına katkı sağlar."},
{"q":"Elektronlar PSI'e ulaşmadan önce neden ışık enerjisiyle yeniden uyarılmaları gerekir?","steps":[{"t":"Enerji kaybı","a":"Zincirde düşüş","d":"Elektronlar PSII'den PSI'e gelirken redoks basamaklarında enerji kaybeder."},{"t":"Tekrar uyarılma","a":"PSI'de ışık","d":"NADP⁺'yi indirgeyecek kadar enerji için PSI'de tekrar uyarılırlar."}],"ans":"Zincirde enerji kaybeden elektronlar, NADP⁺'yi indirgeyebilmek için PSI'de yeniden uyarılır."},
{"q":"Plastosiyanin (PC) elektron taşıma zincirinde nerede ve nasıl hareket eder?","steps":[{"t":"Konum","a":"Lümen içinde","d":"PC, tilakoit lümeninde çözünmüş halde bulunan küçük bir proteindir."},{"t":"Hareket","a":"Yüzey difüzyonu","d":"Lümende b6f ile PSI arasında difüzyonla mekik dokur."}],"ans":"PC, tilakoit lümeninde b6f ile PSI arasında difüzyonla hareket ederek elektron taşır."},
{"q":"Sitokrom b6f kompleksi içinde elektron hangi bileşenler arasında aktarılır?","steps":[{"t":"Giriş","a":"PQH₂'den","d":"Elektronlar indirgenmiş plastokinon (PQH₂) tarafından getirilir."},{"t":"İç aktarım","a":"Demir-kükürt ve sitokromlar","d":"Rieske demir-kükürt merkezi ve sitokrom f üzerinden elektron PC'ye verilir."}],"ans":"b6f içinde elektron, Rieske Fe-S merkezi ve sitokrom f üzerinden PQH₂'den PC'ye aktarılır."},
{"q":"Doğrusal (asiklik) elektron akışı ile döngüsel (siklik) akış arasındaki temel fark nedir?","steps":[{"t":"Doğrusal akış","a":"PSII + PSI","d":"Elektron sudan gelir, NADPH ile O₂ üretilir; hem ATP hem NADPH oluşur."},{"t":"Döngüsel akış","a":"Yalnız PSI","d":"Elektron PSI'den b6f'e geri döner; yalnız ATP üretilir, NADPH ve O₂ oluşmaz."}],"ans":"Doğrusalda PSII+PSI ile ATP ve NADPH üretilir; döngüselde yalnız PSI ile sadece ATP üretilir."},
{"q":"Elektron taşıma zinciri durduğunda proton gradyanına ve ATP üretimine ne olur?","steps":[{"t":"Akış durur","a":"H⁺ pompalanmaz","d":"Elektron akışı kesilince lümene yeni H⁺ pompalanamaz."},{"t":"Gradyan söner","a":"ATP azalır","d":"Var olan gradyan tüketilir ve ATP sentaz enerjisiz kalarak ATP üretimi durur."}],"ans":"Elektron akışı durunca proton gradyanı sönerek ATP üretimi durur."},
{"q":"Tilakoit lümeni pH'ının stromaya göre düşük (asidik) olmasının nedeni nedir?","steps":[{"t":"H⁺ kaynağı","a":"Pompalama + su ayrışması","d":"b6f H⁺ pompalar, su ayrışması da lümene H⁺ bırakır."},{"t":"Sonuç","a":"Asidik lümen","d":"Lümende H⁺ birikmesi pH'ı düşürerek ortamı asidik yapar."}],"ans":"Lümene H⁺ pompalanıp su ayrışmasıyla H⁺ eklendiği için lümen stromaya göre asidiktir."},
{"q":"Plastokinonun zincirdeki konumu, b6f kompleksinin H⁺ pompalama yeteneğiyle nasıl ilişkilidir?","steps":[{"t":"PQ taşıması","a":"H⁺ + e⁻","d":"PQ hem elektron hem proton taşıyabilen bir moleküldür."},{"t":"b6f kullanımı","a":"Q-çevrimi","d":"b6f, PQ'nun bu çift taşıma özelliğini Q-çevriminde kullanarak ek H⁺ pompalar."}],"ans":"PQ'nun H⁺+e⁻ taşıma özelliği, b6f'in Q-çevrimi ile fazladan H⁺ pompalamasını mümkün kılar."},
{"q":"Elektron taşıma zincirinin oksijen üretimiyle ilişkisi nasıl açıklanır?","steps":[{"t":"Elektron talebi","a":"PSII açığı","d":"PSII ışıkla elektron kaybedince bir elektron açığı oluşur."},{"t":"Su ayrışması","a":"O₂ açığa çıkar","d":"Bu açığı kapatmak için su ayrışır ve yan ürün olarak O₂ oluşur."}],"ans":"ETZ, PSII'nin elektron talebiyle su ayrışmasını tetikler; bunun yan ürünü oksijendir."},
{"q":"Kemiozmotik kuram, elektron taşıma zinciri ile ATP üretimini nasıl ilişkilendirir?","steps":[{"t":"Enerji dönüşümü","a":"Elektron → gradyan","d":"Elektron akışının enerjisi proton gradyanı olarak depolanır."},{"t":"Gradyan → ATP","a":"ATP sentaz","d":"H⁺'ler gradyan boyunca ATP sentazdan stromaya akarken ATP üretilir."}],"ans":"Kemiozmotik kurama göre ETZ'nin oluşturduğu proton gradyanı, ATP sentaz aracılığıyla ATP üretimini sağlar."}
]}}};