globalThis.__OUT = {"calvin":{
"ilkokul":{
"kolay":[
{"q":"Bitkiler havadan aldıkları karbondioksit gazını ne yapmak için kullanır?","steps":[{"t":"Havadan gaz alınır","a":"karbondioksit","d":"Yaprak, havadaki karbondioksit gazını içine alır."},{"t":"Şeker yapılır","a":"besin yapımı","d":"Bitki bu gazı kullanarak kendine <b>şeker</b> (besin) yapar."}],"ans":"Bitkiler karbondioksitten kendine şeker (besin) yapmak için kullanır."},
{"q":"Bitkinin şeker yaptığı bu işlemler yaprağın hangi bölümünde olur?","steps":[{"t":"Yaprağın içi","a":"yeşil kısım","d":"Yaprağın yeşil kısmında küçük üretim odaları vardır."},{"t":"Şeker burada yapılır","a":"yaprakta","d":"Karbondioksitten <b>şeker</b> yapma işi yaprağın içinde olur."}],"ans":"Bitkinin şeker yapması yaprağın içindeki yeşil bölümde olur."},
{"q":"Bitki şeker yaparken havadan aldığı karbondioksiti neyle birleştirir?","steps":[{"t":"İki şey gerekir","a":"karbondioksit ve enerji","d":"Bitki, karbondioksit gazını güneşten gelen enerjiyle birleştirir."},{"t":"Sonuç şeker","a":"şeker","d":"Bu birleşmeden bitkinin besini olan <b>şeker</b> oluşur."}],"ans":"Bitki karbondioksiti güneşten aldığı enerjiyle birleştirip şeker yapar."},
{"q":"Bitkinin yaptığı şeker bitkiye ne sağlar?","steps":[{"t":"Şeker besindir","a":"besin","d":"Şeker, bitkinin yiyeceği yani besinidir."},{"t":"Bitki büyür","a":"enerji ve büyüme","d":"Bitki bu <b>besin</b> sayesinde enerji bulur ve büyür."}],"ans":"Bitkinin yaptığı şeker ona besin olur, böylece büyür ve yaşar."},
{"q":"Bitkiler şeker yapmak için karbondioksiti nereden alır?","steps":[{"t":"Kaynak hava","a":"hava","d":"Karbondioksit gazı havanın içinde bulunur."},{"t":"Yaprak alır","a":"yapraktan","d":"Bitki bu gazı <b>yaprakları</b> ile havadan alır."}],"ans":"Bitkiler karbondioksiti havadan, yaprakları yardımıyla alır."}
],
"zor":[
{"q":"Bir bitki gece güneş olmadığı halde içinde biriken karbondioksitten neden hemen şeker yapamaz?","steps":[{"t":"Şeker yapımı için enerji şart","a":"enerji gerekir","d":"Karbondioksitten şeker yapmak için bitkiye enerji lazımdır."},{"t":"Enerji güneşten gelir","a":"güneş yok","d":"Bu enerji güneş ışığından sağlanır; gece <b>güneş olmadığı</b> için enerji azdır."}],"ans":"Çünkü şeker yapmak için enerji gerekir, gece güneş olmadığından bu enerji bulunamaz."},
{"q":"Bir bahçedeki bitki bol karbondioksit alıyor ama hiç şeker yapamıyorsa eksik olan ilk şey ne olabilir?","steps":[{"t":"Gaz var","a":"karbondioksit yeterli","d":"Bitkide bol karbondioksit gazı bulunuyor."},{"t":"Enerji eksik","a":"ışık yok","d":"Şeker yapmak için gereken <b>ışık enerjisi</b> eksik olabilir."}],"ans":"Bitkiye gereken ışık (enerji) eksik olabilir, bu yüzden şeker yapamaz."},
{"q":"Bitki yaptığı şekerin fazlasını ileride kullanmak için ne yapar?","steps":[{"t":"Fazla şeker olur","a":"artan şeker","d":"Bitki ihtiyacından fazla şeker yapabilir."},{"t":"Saklar","a":"depolar","d":"Fazla şekeri kök, meyve gibi yerlerde <b>depolar</b>, sonra kullanır."}],"ans":"Bitki fazla şekeri kök ve meyve gibi yerlerde saklayıp (depolayıp) sonra kullanır."},
{"q":"İki saksı bitkiden birine bol ışık verilir, diğeri karanlıkta tutulur. İkisinde de hava aynıdır. Hangisi daha çok şeker yapar, neden?","steps":[{"t":"Hava aynı","a":"karbondioksit eşit","d":"İki bitkide de karbondioksit gazı aynıdır."},{"t":"Işık farkı","a":"ışıklı kazanır","d":"<b>Işıklı</b> bitkinin enerjisi çoktur, bu yüzden daha çok şeker yapar."}],"ans":"Bol ışık alan bitki daha çok şeker yapar, çünkü şeker yapmak için ışık enerjisi gerekir."},
{"q":"Bitkinin yaptığı şeker neden sadece bitki için değil, bizim için de önemlidir?","steps":[{"t":"Şeker besin","a":"besin oluşur","d":"Bitki karbondioksitten besin olan şeker yapar."},{"t":"Biz de yeriz","a":"bizim besinimiz","d":"İnsanlar ve hayvanlar bu bitkileri yiyerek <b>besin</b> alır."}],"ans":"Bitkinin yaptığı şeker hem bitkiye hem de onu yiyen insan ve hayvanlara besin olur."}
]
},
"ortaokul":{
"kolay":[
{"q":"Fotosentezde karbondioksitin şekere dönüştürüldüğü tepkimelere ne ad verilir?","steps":[{"t":"İki evre vardır","a":"ışık ve karanlık","d":"Fotosentezin ışığa bağlı ve ışıktan bağımsız evreleri vardır."},{"t":"Şeker yapan evre","a":"ışıktan bağımsız reaksiyonlar","d":"Karbondioksitin şekere dönüştüğü evreye <b>ışıktan bağımsız reaksiyonlar</b> (Calvin döngüsü) denir."}],"ans":"Karbondioksitin şekere dönüştüğü evreye ışıktan bağımsız reaksiyonlar (Calvin döngüsü) denir."},
{"q":"Calvin döngüsü kloroplastın hangi bölümünde gerçekleşir?","steps":[{"t":"Kloroplastın kısımları","a":"stroma ve tilakoit","d":"Kloroplastta sıvı dolu stroma ve zarlı tilakoitler bulunur."},{"t":"Döngünün yeri","a":"stroma","d":"Calvin döngüsü kloroplastın sıvı kısmı olan <b>stromada</b> gerçekleşir."}],"ans":"Calvin döngüsü kloroplastın sıvı kısmı olan stromada gerçekleşir."},
{"q":"Calvin döngüsünde karbondioksiti şekere dönüştürmek için hangi iki madde harcanır?","steps":[{"t":"Işık evresinin ürünleri","a":"ATP ve NADPH","d":"Işığa bağlı evrede enerji taşıyan ATP ve NADPH üretilir."},{"t":"Döngüde kullanılır","a":"ATP ve NADPH","d":"Calvin döngüsü bu <b>ATP ve NADPH</b>'yi kullanarak şeker yapar."}],"ans":"Calvin döngüsünde ATP ve NADPH harcanarak karbondioksit şekere dönüştürülür."},
{"q":"Calvin döngüsü neden 'ışıktan bağımsız reaksiyonlar' diye adlandırılır?","steps":[{"t":"Işığı doğrudan kullanmaz","a":"ışık gerekmez","d":"Bu tepkimeler için doğrudan ışığa gerek yoktur."},{"t":"Hazır enerjiyle çalışır","a":"ATP-NADPH ile","d":"Işık evresinde üretilen <b>ATP ve NADPH</b> ile çalışır, ışığa doğrudan ihtiyaç duymaz."}],"ans":"Doğrudan ışık kullanmadan, ışık evresinde üretilen ATP ve NADPH ile çalıştığı için bu adı alır."},
{"q":"Calvin döngüsünün temel ürünü olan ve bitkinin besin yapımında kullandığı madde nedir?","steps":[{"t":"Karbondioksit girer","a":"karbondioksit","d":"Döngüye havadan karbondioksit alınır."},{"t":"Şeker çıkar","a":"glikoz (şeker)","d":"Döngü sonunda karbondioksitten <b>glikoz</b> gibi şeker yapılır."}],"ans":"Calvin döngüsünün ürünü, glikoz gibi bitkiye besin olan şekerdir."}
],
"zor":[
{"q":"Işığa bağlı evre durduğunda Calvin döngüsü de bir süre sonra neden durur?","steps":[{"t":"Döngünün ihtiyacı","a":"ATP ve NADPH","d":"Calvin döngüsü çalışmak için ATP ve NADPH'ye ihtiyaç duyar."},{"t":"Kaynak kesilir","a":"üretim durur","d":"Işık evresi durunca <b>ATP ve NADPH</b> üretilemez, döngü bu maddeler bitince durur."}],"ans":"Işık evresi durunca ATP ve NADPH üretilemez; bu maddeler tükenince Calvin döngüsü de durur."},
{"q":"Calvin döngüsünde karbondioksiti yakalayan tepkimeyi hızlandıran enzim hangisidir?","steps":[{"t":"Karbon tutulması","a":"karbon bağlama","d":"Döngünün ilk adımında karbondioksit bir moleküle bağlanır."},{"t":"Görevli enzim","a":"RuBisCO","d":"Bu bağlama tepkimesini <b>RuBisCO</b> enzimi hızlandırır."}],"ans":"Calvin döngüsünde karbondioksiti yakalayan tepkimeyi RuBisCO enzimi hızlandırır."},
{"q":"Bir bitkiye verilen karbondioksit kesilirse Calvin döngüsünün ürünü olan şeker neden azalır?","steps":[{"t":"Şekerin kaynağı","a":"karbondioksit","d":"Döngüde şekerin karbonu havadan alınan karbondioksitten gelir."},{"t":"Hammadde biter","a":"şeker yapılamaz","d":"Karbondioksit kesilince döngü <b>hammaddesiz</b> kalır ve şeker yapımı azalır."}],"ans":"Şekerin karbonu karbondioksitten geldiği için, karbondioksit kesilince döngü hammaddesiz kalır ve şeker azalır."},
{"q":"Calvin döngüsüne neden 'döngü' denir?","steps":[{"t":"Başlangıç maddesi","a":"karbon yakalayıcı molekül","d":"Döngü, karbondioksiti yakalayan bir molekülle başlar."},{"t":"Tekrar üretilir","a":"yeniden oluşur","d":"Bu yakalayıcı molekül sonunda <b>yeniden üretilir</b>, böylece tepkimeler tekrar başlar."}],"ans":"Karbonu yakalayan molekül sonunda yeniden üretilip tepkimeler tekrarlandığı için 'döngü' denir."},
{"q":"Gündüz bol şeker yapan bir bitki, üretimin büyük kısmını neden ışık evresine değil Calvin döngüsüne borçludur?","steps":[{"t":"Işık evresinin işi","a":"enerji üretimi","d":"Işık evresi şeker değil, ATP ve NADPH gibi enerji taşıyıcıları üretir."},{"t":"Şekeri kim yapar","a":"Calvin döngüsü","d":"Asıl <b>şeker</b> (besin), karbondioksiti bağlayan Calvin döngüsünde yapılır."}],"ans":"Çünkü ışık evresi sadece enerji üretir; asıl şeker, karbondioksiti bağlayan Calvin döngüsünde yapılır."}
]
},
"lise":{
"kolay":[
{"q":"Calvin döngüsü kloroplastın hangi kısmında ve hangi evrede gerçekleşir?","steps":[{"t":"Bölge","a":"stroma","d":"Calvin döngüsü kloroplastın sıvı dolu kısmı olan stromada yürür."},{"t":"Evre","a":"ışıktan bağımsız evre","d":"Bu tepkimeler fotosentezin <b>ışıktan bağımsız</b> (karanlık) evresini oluşturur."}],"ans":"Calvin döngüsü kloroplastın stromasında, ışıktan bağımsız evrede gerçekleşir."},
{"q":"Calvin döngüsünde karbondioksiti bağlayan 5 karbonlu molekül hangisidir?","steps":[{"t":"Karbon tutucu","a":"RuBP","d":"Döngüde karbondioksiti yakalayan molekül 5 karbonlu ribuloz-1,5-bifosfattır (RuBP)."},{"t":"Birleşme","a":"karbon tutulması","d":"Karbondioksit, <b>RuBP</b>'ye bağlanarak karbon tutulmasını başlatır."}],"ans":"Calvin döngüsünde karbondioksiti bağlayan 5 karbonlu molekül RuBP'dir (ribuloz-1,5-bifosfat)."},
{"q":"Karbondioksit ile RuBP'nin birleşmesini katalizleyen enzim hangisidir?","steps":[{"t":"Tepkime","a":"karbon tutulması","d":"Karbondioksit ile RuBP'nin birleşmesi karbon tutulması (fiksasyon) tepkimesidir."},{"t":"Enzim","a":"RuBisCO","d":"Bu tepkimeyi <b>RuBisCO</b> (ribuloz bifosfat karboksilaz) enzimi katalizler."}],"ans":"Karbondioksit ile RuBP'nin birleşmesini RuBisCO enzimi katalizler."},
{"q":"Karbondioksitin RuBP'ye bağlanmasıyla oluşan kararsız 6 karbonlu molekül hemen neye dönüşür?","steps":[{"t":"İlk ürün kararsız","a":"6 karbonlu ara ürün","d":"CO₂ + RuBP birleşince oluşan 6 karbonlu molekül çok kararsızdır."},{"t":"Parçalanma","a":"iki molekül 3-PGA","d":"Bu molekül hemen ikiye bölünerek iki molekül <b>3-PGA</b> (3 karbonlu) oluşturur."}],"ans":"Kararsız 6 karbonlu molekül hemen ikiye bölünerek iki molekül 3-PGA oluşturur."},
{"q":"Calvin döngüsünün ürettiği 3 karbonlu şeker molekülü hangisidir?","steps":[{"t":"İndirgenme ürünü","a":"G3P","d":"3-PGA, ATP ve NADPH ile indirgenerek gliseraldehit-3-fosfata (G3P) dönüşür."},{"t":"Çıkış molekülü","a":"G3P","d":"<b>G3P</b>, döngüden çıkıp glikoz ve diğer organik maddelerin yapımında kullanılır."}],"ans":"Calvin döngüsünün ürettiği 3 karbonlu şeker G3P'dir (gliseraldehit-3-fosfat)."},
{"q":"Calvin döngüsü ışık evresinin hangi iki ürününü tüketir?","steps":[{"t":"Enerji kaynağı","a":"ATP","d":"Döngü, hem fosfat aktarımı için ATP'yi kullanır."},{"t":"İndirgeyici","a":"NADPH","d":"Hem de 3-PGA'yı G3P'ye indirgemek için <b>NADPH</b>'yi kullanır."}],"ans":"Calvin döngüsü ışık evresinde üretilen ATP ve NADPH'yi tüketir."},
{"q":"Calvin döngüsünde 3-PGA'nın G3P'ye dönüşmesine ne ad verilir?","steps":[{"t":"Elektron eklenir","a":"indirgenme","d":"3-PGA'ya NADPH'den elektron (hidrojen) eklenmesi indirgenmedir."},{"t":"Evre adı","a":"indirgenme evresi","d":"Bu adım Calvin döngüsünün <b>indirgenme</b> evresini oluşturur."}],"ans":"3-PGA'nın G3P'ye dönüşmesine indirgenme (redüksiyon) evresi denir."},
{"q":"Calvin döngüsünün üç temel evresi hangileridir?","steps":[{"t":"Önce yakalama","a":"karbon tutulması","d":"İlk evrede CO₂, RuBP'ye bağlanır (karbon tutulması/fiksasyon)."},{"t":"Sonra dönüşüm ve yenileme","a":"indirgenme ve yenilenme","d":"İkinci evre <b>indirgenme</b> (G3P oluşumu), üçüncü evre RuBP'nin <b>yenilenmesidir</b>."}],"ans":"Üç evre: karbon tutulması (fiksasyon), indirgenme ve RuBP'nin yenilenmesidir."},
{"q":"Calvin döngüsünde RuBP'nin yenilenmesi neden gereklidir?","steps":[{"t":"RuBP tüketilir","a":"karbon tutmada harcanır","d":"Karbon tutulmasında RuBP, CO₂'yi bağlayıp tükenir."},{"t":"Döngü sürmeli","a":"yeniden üretilir","d":"Döngünün devam etmesi için <b>RuBP</b> G3P'lerden yeniden üretilmelidir."}],"ans":"RuBP karbon tutmada tükendiği için, döngünün sürmesi adına sürekli yeniden üretilmesi gerekir."},
{"q":"Calvin döngüsünde bir molekül glikoz oluşturmak için kaç tur dönmek gerekir?","steps":[{"t":"Tur başına karbon","a":"1 CO₂","d":"Her turda 1 molekül CO₂ bağlanır, glikoz için 6 karbon gerekir."},{"t":"Tur sayısı","a":"6 tur","d":"6 karbonlu glikoz için döngünün <b>6 tur</b> dönüp 6 CO₂ bağlaması gerekir."}],"ans":"Bir molekül glikoz için Calvin döngüsünün 6 tur dönüp 6 CO₂ bağlaması gerekir."},
{"q":"Calvin döngüsünün enerjisini sağlayan ışığa bağlı reaksiyonlar nerede gerçekleşir?","steps":[{"t":"Işık evresinin yeri","a":"tilakoit zar","d":"Işığa bağlı reaksiyonlar tilakoit zarlarda gerçekleşir."},{"t":"Ürünler stromaya geçer","a":"ATP ve NADPH","d":"Burada üretilen <b>ATP ve NADPH</b> stromadaki Calvin döngüsüne aktarılır."}],"ans":"Işığa bağlı reaksiyonlar tilakoit zarlarda olur; ürünleri stromadaki Calvin döngüsüne gider."},
{"q":"Calvin döngüsünden çıkan G3P'nin döngü dışındaki başlıca kullanımı nedir?","steps":[{"t":"Yapı taşı","a":"3 karbonlu şeker","d":"G3P, 3 karbonlu basit bir şeker molekülüdür."},{"t":"Büyük moleküller","a":"glikoz, nişasta","d":"İki G3P birleşip <b>glikoz</b> verir; glikozlar nişasta ve selüloza dönüşebilir."}],"ans":"G3P, glikoz yapımında kullanılır; glikozlar da nişasta, selüloz gibi maddelere dönüşür."},
{"q":"Calvin döngüsü neden 'karbon fiksasyonu' (karbon tutulması) yolu olarak da bilinir?","steps":[{"t":"İnorganik karbon","a":"CO₂","d":"Havadaki karbondioksit inorganik bir karbon kaynağıdır."},{"t":"Organik yapıya katılır","a":"karbon tutulması","d":"Döngü, bu CO₂'yi organik moleküllere bağlar; bu işleme <b>karbon tutulması</b> denir."}],"ans":"Havadaki inorganik CO₂'yi organik moleküllere bağladığı için karbon fiksasyonu yolu olarak bilinir."},
{"q":"Calvin döngüsünde NADPH ve ATP'nin görevleri arasındaki temel fark nedir?","steps":[{"t":"ATP'nin görevi","a":"enerji/fosfat","d":"ATP, tepkimelere fosfat ve enerji sağlar (örneğin RuBP yenilenmesinde)."},{"t":"NADPH'nin görevi","a":"indirgeyici","d":"<b>NADPH</b> ise elektron-hidrojen vererek 3-PGA'yı G3P'ye indirger."}],"ans":"ATP enerji/fosfat sağlar, NADPH ise indirgeyici olarak elektron-hidrojen verir."},
{"q":"Calvin döngüsü 'karanlık reaksiyonlar' diye anılsa da neden gerçekte ışığa bağımlıdır?","steps":[{"t":"Doğrudan ışık kullanmaz","a":"ışıksız işler","d":"Döngünün tepkimeleri için doğrudan ışık gerekmez."},{"t":"Dolaylı bağımlılık","a":"ATP-NADPH üzerinden","d":"Ama kullandığı <b>ATP ve NADPH</b> ışık evresinde üretildiğinden dolaylı olarak ışığa bağımlıdır."}],"ans":"Doğrudan ışık kullanmasa da, gereken ATP ve NADPH ışık evresinde üretildiği için dolaylı olarak ışığa bağımlıdır."}
],
"zor":[
{"q":"Calvin döngüsünün bir tam turunda 3 CO₂ bağlandığında üretilen 6 G3P'nin kaçı RuBP yenilenmesine, kaçı net ürüne ayrılır?","steps":[{"t":"Üretilen G3P","a":"6 G3P","d":"3 CO₂ + 3 RuBP'den 6 molekül G3P (toplam 18 karbon) oluşur."},{"t":"Dağılım","a":"5 yenilenmeye, 1 net ürün","d":"6 G3P'nin 5'i RuBP'yi yenilemek için kullanılır, <b>1</b> tanesi net kazanç olarak döngüden çıkar."}],"ans":"6 G3P'nin 5'i RuBP yenilenmesine, 1'i ise net ürün olarak döngüden ayrılır."},
{"q":"3 CO₂ bağlayan bir tam Calvin turunda kaç ATP ve kaç NADPH harcanır?","steps":[{"t":"İndirgenme aşaması","a":"6 ATP, 6 NADPH","d":"6 molekül 3-PGA'nın G3P'ye indirgenmesinde 6 ATP ve 6 NADPH kullanılır."},{"t":"Yenilenme aşaması","a":"+3 ATP","d":"RuBP'nin yenilenmesinde ek <b>3 ATP</b> harcanır; toplam 9 ATP ve 6 NADPH olur."}],"ans":"3 CO₂'lik bir turda toplam 9 ATP ve 6 NADPH harcanır."},
{"q":"Bir molekül glikoz sentezi için Calvin döngüsünün toplam ATP ve NADPH gereksinimi nedir?","steps":[{"t":"6 tur gerekir","a":"6 CO₂","d":"Glikoz için 6 CO₂ bağlanır, yani döngü 6 kez döner."},{"t":"Toplam maliyet","a":"18 ATP, 12 NADPH","d":"Tur başına 3 ATP + 2 NADPH; 6 tur için <b>18 ATP</b> ve <b>12 NADPH</b> gerekir."}],"ans":"Bir glikoz molekülü için toplam 18 ATP ve 12 NADPH harcanır."},
{"q":"RuBisCO'nun oksijene de bağlanması (fotorespirasyon) Calvin döngüsünün verimini nasıl etkiler?","steps":[{"t":"Rekabet","a":"O₂ ile CO₂ yarışır","d":"RuBisCO hem CO₂ hem O₂ bağlayabilir; O₂ bağlanınca fotorespirasyon başlar."},{"t":"Verim düşer","a":"karbon kaybı","d":"O₂ bağlanması faydalı şeker yerine <b>karbon kaybına</b> yol açar, döngünün net verimi düşer."}],"ans":"RuBisCO O₂ bağladığında fotorespirasyon olur; bu, karbon kazancını azaltarak döngünün verimini düşürür."},
{"q":"Aniden karanlığa alınan bir bitkide RuBP miktarının önce artıp 3-PGA'nın birikmesinin nedeni nedir?","steps":[{"t":"Karbon tutulması sürer","a":"3-PGA oluşur","d":"Karanlıkta da RuBisCO bir süre CO₂'yi bağlamaya devam eder, 3-PGA oluşur."},{"t":"İndirgenme durur","a":"ATP-NADPH biter","d":"Ama ışık olmadığı için <b>ATP ve NADPH</b> tükenir; 3-PGA, G3P'ye dönüşemez ve <b>birikir</b>."}],"ans":"Karanlıkta ATP-NADPH üretimi durur; 3-PGA indirgenemediği için birikir, RuBP'ye dönüşüm de yavaşlar."},
{"q":"Aniden CO₂'si kesilen bir bitkide RuBP'nin birikip 3-PGA'nın azalmasının nedeni nedir?","steps":[{"t":"Tutulma durur","a":"3-PGA azalır","d":"CO₂ olmayınca RuBP bağlanacak karbon bulamaz; 3-PGA üretimi durur ve azalır."},{"t":"Yenilenme sürer","a":"RuBP birikir","d":"ATP-NADPH bir süre var olduğundan <b>RuBP</b> üretilmeye devam eder ama tüketilmediği için birikir."}],"ans":"CO₂ kesilince 3-PGA üretilemeyip azalır; tüketilmeyen RuBP ise birikir."},
{"q":"C4 bitkilerinin sıcak ortamda Calvin döngüsünü neden daha verimli çalıştırabildiğini açıklayın.","steps":[{"t":"Sorun fotorespirasyon","a":"sıcakta O₂ artar","d":"Sıcak-kurak ortamda gözenekler kapanır, hücrede O₂ artıp CO₂ azalır; RuBisCO O₂ bağlar."},{"t":"C4 çözümü","a":"CO₂ derişimini artırır","d":"C4 bitkileri CO₂'yi önce 4 karbonlu moleküle bağlayıp demet kını hücrelerine taşır; orada <b>yüksek CO₂</b> sağlayarak RuBisCO'nun verimli çalışmasını sağlar."}],"ans":"C4 bitkileri CO₂'yi yoğunlaştırıp RuBisCO çevresinde derişimi artırır; böylece fotorespirasyonu azaltıp Calvin döngüsünü sıcakta da verimli çalıştırır."},
{"q":"Calvin döngüsünde tüketilen karbonun tamamı CO₂'den geldiği halde RuBP yenilenmesi için neden ayrıca enerji (ATP) gerekir?","steps":[{"t":"Karbon iskeleti yeterli değil","a":"5 G3P → 3 RuBP","d":"5 molekül G3P'den (15 karbon) 3 molekül RuBP'nin (15 karbon) karbon iskeleti elde edilir."},{"t":"Fosforilasyon gerekir","a":"ATP ile aktifleşir","d":"Ancak RuBP'nin reaktif olması için fosfat eklenmesi şarttır; bu <b>ATP</b> ile sağlanır."}],"ans":"Karbon iskeleti G3P'den gelse de, RuBP'yi reaktif kılan fosfat grubunun eklenmesi için ATP enerjisi gerekir."},
{"q":"Calvin döngüsünün ışık olmadan kısa süre sürüp uzun süre süremeyişini, ürün ve substrat dengesiyle açıklayın.","steps":[{"t":"Kısa süre devam","a":"depo ATP-NADPH","d":"Işık kesildiğinde stromada kalan ATP ve NADPH ile döngü kısa süre devam eder."},{"t":"Sonra durur","a":"taşıyıcılar tükenir","d":"Bu taşıyıcılar yenilenmediği için tükenince indirgenme durur, döngü <b>uzun süre süremez</b>."}],"ans":"Stromadaki ATP-NADPH stoğuyla döngü kısa süre devam eder; bu taşıyıcılar yenilenmediği için tükenince durur."},
{"q":"RuBisCO'nun Dünya'daki en bol protein sayılmasının, Calvin döngüsündeki rolüyle bağlantısını açıklayın.","steps":[{"t":"Yavaş enzim","a":"düşük hız","d":"RuBisCO, katalitik hızı düşük (saniyede az tepkime) bir enzimdir."},{"t":"Bol miktar gerekir","a":"yüksek derişim","d":"Yeterli karbon tutulması için çok sayıda enzim gerekir; bu yüzden <b>çok bol</b> bulunur. Ayrıca tüm karbon tutulması ona dayanır."}],"ans":"RuBisCO yavaş çalıştığı ve gezegendeki karbon tutulmasının tamamını üstlendiği için çok yüksek miktarda bulunur; bu onu en bol protein yapar."},
{"q":"Calvin döngüsünde net 1 G3P üretmek için döngünün kaç kez dönmesi ve kaç CO₂ bağlaması gerektiğini açıklayın.","steps":[{"t":"Net ürün oranı","a":"tur başına 1/3 G3P net","d":"Her turda 1 CO₂ bağlanır; 3 turda 1 net G3P çıkışı olur (6 G3P'den 1'i net)."},{"t":"Sonuç","a":"3 tur, 3 CO₂","d":"Net 1 G3P için döngü <b>3 kez</b> dönmeli ve <b>3 CO₂</b> bağlamalıdır."}],"ans":"Net 1 G3P için döngü 3 kez dönmeli ve 3 CO₂ bağlamalıdır."},
{"q":"Işık evresi ürünleri ATP/NADPH ile Calvin döngüsü arasında neden 'geri besleme' türü bir bağımlılık vardır?","steps":[{"t":"Calvin tüketir","a":"ADP, NADP⁺ açığa çıkar","d":"Calvin döngüsü ATP ve NADPH'yi kullanıp ADP, Pi ve NADP⁺'a çevirir."},{"t":"Işık evresi yeniden yükler","a":"ADP, NADP⁺ gerekir","d":"Işık evresi çalışmak için <b>ADP ve NADP⁺</b>'ya ihtiyaç duyar; Calvin durursa bunlar bitip ışık evresi de yavaşlar."}],"ans":"Calvin döngüsü ATP-NADPH'yi ADP ve NADP⁺'a çevirip ışık evresine geri verir; biri durursa diğeri de yavaşladığı için karşılıklı (geri besleme) bağımlılık vardır."},
{"q":"Calvin döngüsünde 3-PGA'nın G3P'ye indirgenmesinin neden hem ATP hem NADPH gerektirdiğini açıklayın.","steps":[{"t":"Önce fosforilasyon","a":"ATP harcanır","d":"3-PGA önce ATP ile fosforillenerek 1,3-bifosfogliserata dönüşür (enerji yüklenir)."},{"t":"Sonra indirgeme","a":"NADPH harcanır","d":"Ardından <b>NADPH</b>, bu molekülü indirgeyerek G3P'ye çevirir (elektron eklenir)."}],"ans":"3-PGA önce ATP ile fosforillenir, sonra NADPH ile indirgenir; bu yüzden indirgenme adımı hem ATP hem NADPH gerektirir."},
{"q":"İzotopla işaretli ¹⁴CO₂ verilen bir bitkide işaretli karbonun ilk olarak hangi molekülde görülmesi beklenir, neden?","steps":[{"t":"İlk bağlanma","a":"karbon tutulması","d":"¹⁴CO₂ önce RuBP'ye bağlanır (RuBisCO katalizi)."},{"t":"İlk kararlı ürün","a":"3-PGA","d":"Oluşan 6 karbonlu ara ürün hemen parçalanır; işaretli karbon ilk olarak kararlı <b>3-PGA</b>'da görülür."}],"ans":"İşaretli karbon ilk kararlı ürün olan 3-PGA'da görülür; çünkü CO₂ önce RuBP'ye bağlanıp hemen 3-PGA'ya dönüşür."},
{"q":"Calvin döngüsünün tek başına bitkiyi besleyemeyeceğini, ışık evresiyle zorunlu işbirliğini gerekçelendirerek açıklayın.","steps":[{"t":"Calvin enerji üretmez","a":"sadece tüketir","d":"Calvin döngüsü kendi enerjisini üretmez; ATP ve NADPH'yi dışarıdan (ışık evresinden) alıp tüketir."},{"t":"Işık evresi şeker yapmaz","a":"işbirliği şart","d":"Işık evresi de şeker yapmaz, yalnızca taşıyıcı üretir; bu yüzden besin yapımı iki evrenin <b>zorunlu işbirliğiyle</b> olur."}],"ans":"Calvin döngüsü enerji üretmeyip ışık evresinin ATP-NADPH'sine bağımlıdır; ışık evresi de şeker yapmaz, bu yüzden besin yapımı iki evrenin zorunlu işbirliğiyle gerçekleşir."}
]
}
}};
