globalThis.__OUT = {"monohibrit":{"ilkokul":{"kolay":[
  {"q":"Anne kedi ve baba kedinin ikisi de kara renkli. Yavru kedi büyük olasılıkla hangi renkte olur?","steps":[{"t":"Anne ve babaya bak","a":"İkisi de kara","d":"Yavrular özelliklerini anne ve babadan alır. İkisi de kara renkliyse renk kara taraftan gelir."},{"t":"Yavruyu tahmin et","a":"Kara renkli","d":"Anne baba kara olunca yavru da çoğunlukla kara renkli olur."}],"ans":"Yavru kedi büyük olasılıkla kara renkli olur."},
  {"q":"Uzun boylu bir bezelye bitkisi ile yine uzun boylu bir bezelye bitkisinin tohumundan çıkan yeni bitki çoğunlukla nasıl olur?","steps":[{"t":"Ana bitkilere bak","a":"İkisi de uzun","d":"Yeni bitki özelliklerini iki ana bitkiden alır. İkisi de uzunsa uzunluk özelliği geçer."},{"t":"Yeni bitkiyi tahmin et","a":"Uzun boylu","d":"Uzun ile uzunun tohumundan çoğunlukla uzun bitki çıkar."}],"ans":"Yeni bitki çoğunlukla uzun boylu olur."},
  {"q":"Bir çiçeğin kırmızı renk özelliği anneden mi babadan mı yoksa ikisinden de mi gelebilir?","steps":[{"t":"Özellik nereden gelir?","a":"Anne ve babadan","d":"Canlılar özelliklerini hem anneden hem babadan alır. Renk de böyle bir özelliktir."},{"t":"Cevabı söyle","a":"İkisinden de","d":"Kırmızı renk özelliği hem anneden hem babadan gelebilir."}],"ans":"Renk özelliği hem anneden hem babadan gelebilir."},
  {"q":"Sarı tüylü anne tavşan ile sarı tüylü baba tavşanın yavruları en çok hangi renkte olur?","steps":[{"t":"Anne babanın rengi","a":"İkisi de sarı","d":"Yavru tüy rengini anne ve babadan alır. İkisi de sarıysa sarı renk yavruya geçer."},{"t":"Yavruyu tahmin et","a":"Sarı tüylü","d":"Sarı ile sarıdan çoğunlukla sarı tüylü yavru olur."}],"ans":"Yavrular en çok sarı tüylü olur."},
  {"q":"Bir bitkinin tohumundan çıkan yeni bitkiler neden ana bitkiye benzer?","steps":[{"t":"Benzerlik nereden?","a":"Ana bitkiden","d":"Yeni bitki özelliklerini tohumu veren ana bitkiden alır."},{"t":"Sonucu söyle","a":"Özellik aktarılır","d":"Renk, boy gibi özellikler ana bitkiden yeni bitkiye geçtiği için birbirlerine benzerler."}],"ans":"Çünkü özellikler ana bitkiden yeni bitkiye aktarılır."}
],"zor":[
  {"q":"Anne tavşan beyaz, baba tavşan da beyaz. Ama büyük annenin kara olduğu biliniyor. Yavrularda kara renk ortaya çıkabilir mi?","steps":[{"t":"Gizli özellik","a":"Karadan gelen iz","d":"Beyaz tavşanlarda büyük anneden gelen kara renk özelliği gizli kalmış olabilir."},{"t":"Yavruyu düşün","a":"Bazen kara çıkar","d":"Anne ve babada gizli duran kara özellik birleşirse bazı yavrularda kara renk görülebilir."}],"ans":"Evet, gizli kalan kara özellik birleşirse bazı yavrular kara olabilir."},
  {"q":"Uzun anne ile kısa baba bitkinin tohumundan çıkan bitkiler hep uzun oluyor. Hangi özellik daha güçlü görünmüştür?","steps":[{"t":"Hangi özellik göründü?","a":"Uzunluk","d":"Yavruların hepsi uzun çıktıysa uzunluk özelliği kısalığı bastırıp görünür olmuştur."},{"t":"Sonucu söyle","a":"Uzun daha güçlü","d":"Burada uzunluk özelliği kısalıktan daha baskın (güçlü) görünmüştür."}],"ans":"Uzunluk özelliği daha güçlü (baskın) görünmüştür."},
  {"q":"İki kahverengi gözlü anne baba, mavi gözlü bir bebeğe sahip oldu. Bu nasıl olabilir?","steps":[{"t":"Gizli özellik var mı?","a":"Mavi göz gizli","d":"Anne ve babanın gözü kahverengi olsa da içlerinde gizli mavi göz özelliği taşıyor olabilir."},{"t":"Bebeği açıkla","a":"Gizliler birleşti","d":"İki gizli mavi özellik bebekte bir araya gelirse bebek mavi gözlü olabilir."}],"ans":"Anne babada gizli duran mavi göz özelliği bebekte birleştiği için bebek mavi gözlü olmuştur."},
  {"q":"Bir çiftçi en uzun bitkilerden tohum alıp ekiyor ve her yıl bitkileri daha çok uzun çıkıyor. Çiftçi neyi kullanmıştır?","steps":[{"t":"Ne yaptı?","a":"Uzunları seçti","d":"Çiftçi sadece uzun bitkilerin tohumunu ekerek uzunluk özelliğini yeni bitkilere aktarmıştır."},{"t":"Sonucu söyle","a":"Özellik aktarımı","d":"Özelliklerin ana bitkiden yeni bitkiye geçmesini kullanarak uzun bitkiler elde etmiştir."}],"ans":"Özelliklerin yavruya aktarılmasını kullanarak uzun bitkileri seçmiştir."},
  {"q":"Bir hayvan türünde siyah tüy beyaz tüyü bastırıyor. İki siyah hayvanın yavrularından bazıları beyaz çıktı. Anne baba nasıl olmalı?","steps":[{"t":"Beyaz nasıl çıktı?","a":"Gizli beyaz","d":"Siyah beyazı bastırdığı için anne baba siyah görünür ama içlerinde gizli beyaz özellik taşıyor olabilir."},{"t":"Sonucu söyle","a":"İkisi de gizli taşıyor","d":"Hem anne hem baba gizli beyaz özellik taşıdığı için bazı yavrular beyaz olmuştur."}],"ans":"Anne ve babanın ikisi de gizli beyaz özellik taşımaktadır."}
]},"ortaokul":{"kolay":[
  {"q":"Bir özelliği belirleyen ve anne babadan yavruya geçen yapı birimine ne denir?","steps":[{"t":"Özelliği ne taşır?","a":"Gen","d":"Boy, renk gibi özellikleri belirleyen ve anne babadan yavruya geçen kalıtım birimine gen denir."},{"t":"Sonucu söyle","a":"Gen","d":"Genler kalıtsal özelliklerin aktarılmasını sağlar."}],"ans":"Bu yapı birimine <b>gen</b> denir."},
  {"q":"Baskın gen ile çekinik gen arasındaki fark nedir?","steps":[{"t":"Baskın gen","a":"Görünür olan","d":"Baskın gen, yanında çekinik gen olsa bile özelliğini dışarıdan gösterir."},{"t":"Çekinik gen","a":"Gizlenen","d":"Çekinik gen ancak iki tane bir araya gelirse kendini gösterir; tek başına baskın tarafından örtülür."}],"ans":"Baskın gen tek başına bile özelliğini gösterir; çekinik gen ancak iki tane olunca görünür."},
  {"q":"Bezelyede mor çiçek (A) beyaza (a) baskındır. Aa genotipli bitkinin çiçek rengi ne olur?","steps":[{"t":"Genleri incele","a":"A baskın","d":"Aa bitkisinde bir baskın (A) bir çekinik (a) gen vardır."},{"t":"Görünüşü belirle","a":"Mor","d":"Baskın gen A bulunduğu için çiçek mor görünür; beyaz gen gizli kalır."}],"ans":"Aa genotipli bitkinin çiçeği <b>mor</b> olur."},
  {"q":"Bir canlının gözlemlediğimiz dış görünüşüne (örneğin mor çiçek) ne ad verilir?","steps":[{"t":"Dış görünüş nedir?","a":"Fenotip","d":"Canlının gözle görülen özelliklerine (renk, boy gibi) fenotip denir."},{"t":"Sonucu söyle","a":"Fenotip","d":"Mor çiçek, uzun boy gibi gözlemlenen özellikler fenotiptir."}],"ans":"Dış görünüşe <b>fenotip</b> denir."},
  {"q":"AA ve aa gibi gen yazılışlarına, yani bir canlının taşıdığı genlerin tamamına ne denir?","steps":[{"t":"Gen yapısı nedir?","a":"Genotip","d":"Bir canlının taşıdığı gen çiftine (AA, Aa, aa gibi) genotip denir."},{"t":"Sonucu söyle","a":"Genotip","d":"Genotip canlının gen yapısını, fenotip ise dış görünüşünü ifade eder."}],"ans":"Gen yapısına <b>genotip</b> denir."}
],"zor":[
  {"q":"Mor çiçek (A) beyaza (a) baskındır. Saf mor (AA) bir bitki ile beyaz (aa) bitki çaprazlanırsa F1 dölünün genotip ve fenotipi ne olur?","steps":[{"t":"Gametleri yaz","a":"A ve a","d":"AA bitkisi yalnız A, aa bitkisi yalnız a gameti verir."},{"t":"Birleştir","a":"Aa","d":"A ile a birleşince tüm yavrular Aa genotipinde olur."},{"t":"Fenotipi belirle","a":"Hepsi mor","d":"Aa bitkilerinde baskın A bulunduğu için tüm F1 bireyleri mor çiçeklidir."}],"ans":"F1 dölünün hepsi <b>Aa</b> genotipinde ve <b>mor</b> çiçeklidir."},
  {"q":"Aa × Aa çaprazlamasında oluşabilecek dört yavrudan kaçı çekinik özelliği (aa) gösterir?","steps":[{"t":"Punnett karesi","a":"AA, Aa, Aa, aa","d":"Aa × Aa çaprazında dört yavru AA, Aa, Aa, aa olarak oluşur."},{"t":"Çekiniği say","a":"1 tanesi aa","d":"Dört yavrudan yalnız biri aa genotipindedir."},{"t":"Sonucu söyle","a":"1/4","d":"Yani yavruların dörtte biri çekinik özelliği gösterir."}],"ans":"Dört yavrudan <b>1 tanesi</b> (1/4) çekinik özellik gösterir."},
  {"q":"Aa × Aa çaprazlamasında fenotip oranı kaça kaçtır?","steps":[{"t":"Olası yavrular","a":"AA, Aa, Aa, aa","d":"Punnett karesinde dört yavru AA, Aa, Aa, aa olur."},{"t":"Görünüşleri grupla","a":"3 baskın, 1 çekinik","d":"AA, Aa, Aa baskın görünür (3), yalnız aa çekinik görünür (1)."},{"t":"Oranı yaz","a":"3:1","d":"Bu yüzden baskın fenotip ile çekinik fenotip oranı 3:1 olur."}],"ans":"Fenotip oranı <b>3:1</b> (3 baskın, 1 çekinik) olur."},
  {"q":"Çekinik özellik gösteren beyaz çiçekli (aa) bir bezelyenin genotipi neden kesin olarak bilinir?","steps":[{"t":"Çekinik kuralı","a":"İki çekinik gerekir","d":"Çekinik özellik ancak iki çekinik gen (aa) bir araya gelince görünür."},{"t":"Sonucu çıkar","a":"Genotip aa","d":"Beyaz görünen bitkide baskın gen olamaz, bu yüzden genotipi kesinlikle aa'dır."}],"ans":"Çekinik fenotip yalnız <b>aa</b> ile oluştuğu için genotipi kesin aa'dır."},
  {"q":"Bir bitkinin uzun (A) olduğu biliniyor ama AA mı Aa mı bilinmiyor. Bunu anlamak için hangi çaprazlama yapılır?","steps":[{"t":"Bilinmeyeni bul","a":"Çekinikle çapraz","d":"Bilinmeyen genotipi anlamak için onu çekinik (aa) bir bireyle çaprazlarız; buna kontrol (geri) çaprazlaması denir."},{"t":"Sonucu yorumla","a":"Kısa çıkarsa Aa","d":"Yavrularda kısa (aa) birey çıkarsa bitki Aa'dır; hepsi uzun çıkarsa AA'dır."}],"ans":"Çekinik (aa) birey ile <b>kontrol çaprazlaması</b> yapılır."}
]},"lise":{"kolay":[
  {"q":"Monohibrit çaprazlama terimi neyi ifade eder?","steps":[{"t":"Tanımı incele","a":"Tek karakter","d":"Monohibrit çaprazlama, tek bir karakter (örneğin yalnız tohum rengi) bakımından farklı bireylerin çaprazlanmasıdır."},{"t":"Sonucu söyle","a":"Tek gen takibi","d":"Bu çaprazlamada tek bir gen çiftinin kalıtımı izlenir."}],"ans":"Monohibrit çaprazlama, <b>tek bir karakter</b> bakımından yapılan çaprazlamadır."},
  {"q":"Homozigot ve heterozigot birey ne demektir?","steps":[{"t":"Homozigot","a":"Aynı iki alel","d":"Bir gen için iki aleli aynı olan bireye homozigot (saf) denir: AA veya aa."},{"t":"Heterozigot","a":"Farklı iki alel","d":"Bir gen için alelleri farklı olan bireye heterozigot (melez) denir: Aa."}],"ans":"Homozigot alelleri aynıdır (AA, aa); heterozigot alelleri farklıdır (Aa)."},
  {"q":"Bezelyede sarı tohum (Y) yeşile (y) baskındır. YY bireyinin oluşturabileceği gamet çeşitleri nelerdir?","steps":[{"t":"Aleller ayrılır","a":"İki Y aleli","d":"Mayozda homolog kromozomlar ve aleller birbirinden ayrılır. YY bireyinde her iki alel de Y'dir."},{"t":"Gametleri yaz","a":"Yalnız Y","d":"Her gamet bir alel taşıdığı için YY bireyinin tüm gametleri Y'dir."}],"ans":"YY bireyi yalnızca <b>Y</b> taşıyan gamet oluşturur."},
  {"q":"Heterozigot (Aa) bir bireyin oluşturabileceği gamet çeşitleri ve oranları nedir?","steps":[{"t":"Aleller ayrılır","a":"A ve a","d":"Mayozda Aa bireyinin alelleri ayrılır; bir kısım gamet A, bir kısmı a taşır."},{"t":"Oranı belirle","a":"1/2 A, 1/2 a","d":"Gametlerin yarısı A, yarısı a olur (1:1 oranında)."}],"ans":"Aa bireyi <b>1/2 A</b> ve <b>1/2 a</b> olmak üzere iki çeşit gamet oluşturur."},
  {"q":"Mendel'in ayrılma (segregasyon) ilkesi neyi açıklar?","steps":[{"t":"İlkeyi tanı","a":"Aleller ayrılır","d":"Ayrılma ilkesine göre bir bireydeki alel çifti, gamet oluşumunda birbirinden ayrılır."},{"t":"Sonucu söyle","a":"Her gamete bir alel","d":"Böylece her gamet o gen için yalnızca bir alel taşır."}],"ans":"Ayrılma ilkesi, alel çiftinin gamet oluşumunda ayrılıp her gamete bir alel gittiğini açıklar."},
  {"q":"AA × aa çaprazlamasında F1 dölünün genotipi nedir?","steps":[{"t":"Gametleri belirle","a":"A ve a","d":"AA bireyi yalnız A, aa bireyi yalnız a gameti verir."},{"t":"Birleştir","a":"Aa","d":"A ile a birleşince tüm F1 bireyleri Aa olur."}],"ans":"F1 dölünün tamamı <b>Aa</b> genotipindedir."},
  {"q":"Saf döl (homozigot) ile melez döl (heterozigot) arasındaki temel fark nedir?","steps":[{"t":"Saf döl","a":"Aynı alel","d":"Saf döl aynı alelleri taşır (AA veya aa) ve kendi içinde çaprazlanınca hep aynı tip yavru verir."},{"t":"Melez döl","a":"Farklı alel","d":"Melez döl farklı alelleri taşır (Aa) ve kendi içinde çaprazlanınca farklı genotipte yavrular verir."}],"ans":"Saf döl aynı (AA/aa), melez döl farklı (Aa) alelleri taşır."},
  {"q":"Eşit baskınlık (kodominantlık) ile tam baskınlık arasındaki fark nedir?","steps":[{"t":"Tam baskınlık","a":"Biri örter","d":"Tam baskınlıkta heterozigotta baskın alelin özelliği görünür, çekinik tamamen örtülür (Aa = baskın fenotip)."},{"t":"Eşit baskınlık","a":"İkisi birlikte","d":"Eşit baskınlıkta heterozigotta her iki alelin özelliği de ayrı ayrı görülür (örneğin AB kan grubu)."}],"ans":"Tam baskınlıkta yalnız baskın görünür; eşit baskınlıkta her iki alel de birlikte görünür."},
  {"q":"Bir bireyin fenotipini hem genotip hem de çevre etkiler. Buna bir örnek veriniz.","steps":[{"t":"Çevre etkisi","a":"Beslenme/sıcaklık","d":"Aynı genotipe sahip bir bitki, az ışık veya kötü beslenme nedeniyle daha kısa kalabilir."},{"t":"Sonucu yorumla","a":"Fenotip değişir","d":"Genotip aynı kalsa da çevre koşulları fenotipi (boy gibi) değiştirebilir."}],"ans":"Aynı genotipli bitkinin beslenme veya ışık farkıyla farklı boyda görünmesi çevre etkisine örnektir."},
  {"q":"P, F1 ve F2 kuşakları sırasıyla neyi ifade eder?","steps":[{"t":"P ve F1","a":"Ata ve ilk döl","d":"P (parental) çaprazlanan ata bireyleri, F1 onların ilk yavru kuşağıdır."},{"t":"F2","a":"İkinci döl","d":"F2, F1 bireylerinin kendi aralarında çaprazlanmasıyla oluşan ikinci yavru kuşağıdır."}],"ans":"P ata kuşağı, F1 ilk yavru kuşağı, F2 ise F1'lerin çaprazından oluşan ikinci kuşaktır."},
  {"q":"Bezelyede uzunluk (T) kısalığa (t) baskındır. Tt × tt çaprazlamasında fenotip oranı ne olur?","steps":[{"t":"Gametleri yaz","a":"T,t ve t","d":"Tt bireyi T ve t, tt bireyi yalnız t gameti verir."},{"t":"Birleştir","a":"Tt ve tt","d":"Yavruların yarısı Tt (uzun), yarısı tt (kısa) olur."},{"t":"Oranı belirle","a":"1:1","d":"Böylece uzun ile kısa fenotip oranı 1:1 olur."}],"ans":"Tt × tt çaprazında fenotip oranı <b>1:1</b> (uzun:kısa) olur."},
  {"q":"Punnett karesi ne işe yarar?","steps":[{"t":"Amacı tanı","a":"Yavru tahmini","d":"Punnett karesi, ana bireylerin gametlerini satır ve sütuna yazıp olası yavru genotiplerini gösteren bir tablodur."},{"t":"Sonucu söyle","a":"Olasılık hesabı","d":"Bu tablo sayesinde yavruların genotip ve fenotip oranları kolayca hesaplanır."}],"ans":"Punnett karesi, olası yavru genotip ve fenotip oranlarını tahmin etmeye yarar."},
  {"q":"Test çaprazlaması (kontrol çaprazlaması) hangi amaçla yapılır?","steps":[{"t":"Amacı tanı","a":"Genotip bulma","d":"Baskın fenotipli bir bireyin AA mı Aa mı olduğunu anlamak için çekinik (aa) bireyle çaprazlanır."},{"t":"Sonucu yorumla","a":"Yavruya bak","d":"Çekinik yavru çıkarsa birey heterozigot (Aa), tüm yavrular baskın çıkarsa homozigottur (AA)."}],"ans":"Test çaprazlaması, baskın fenotipli bireyin bilinmeyen genotipini belirlemek için yapılır."},
  {"q":"aa × aa çaprazlamasında yavruların genotip ve fenotipi nasıl olur?","steps":[{"t":"Gametleri yaz","a":"İkisi de a","d":"Her iki birey de homozigot çekinik olduğu için yalnız a gameti verir."},{"t":"Birleştir","a":"Tümü aa","d":"a ile a birleşince tüm yavrular aa genotipinde ve çekinik fenotiplidir."}],"ans":"Tüm yavrular <b>aa</b> genotipinde ve çekinik fenotiplidir."},
  {"q":"AA × Aa çaprazlamasında çekinik fenotipli (aa) birey çıkar mı?","steps":[{"t":"Gametleri yaz","a":"A ve A,a","d":"AA bireyi yalnız A; Aa bireyi A ve a gameti verir."},{"t":"Birleştir","a":"AA ve Aa","d":"Olası yavrular AA ve Aa olur; her ikisinde de baskın A bulunur."},{"t":"Sonucu yorumla","a":"Çekinik çıkmaz","d":"En az bir A her zaman bulunduğu için aa genotipli birey oluşamaz."}],"ans":"Hayır, en az bir A her zaman bulunduğundan çekinik (aa) birey çıkmaz."}
],"zor":[
  {"q":"Bezelyede sarı tohum (Y) yeşile (y) baskındır. Yy × Yy çaprazlamasında F2 dölünün genotip ve fenotip oranlarını bulunuz.","steps":[{"t":"Gametleri belirle","a":"Y ve y","d":"Her iki ebeveyn de Yy olduğundan 1/2 Y, 1/2 y gameti verir."},{"t":"Punnett karesi","a":"YY, Yy, Yy, yy","d":"Gametleri çaprazlayınca YY, Yy, Yy, yy yavruları oluşur."},{"t":"Oranları yaz","a":"1:2:1 ve 3:1","d":"Genotip oranı 1 YY : 2 Yy : 1 yy; sarı (YY+Yy) ile yeşil (yy) fenotip oranı 3:1'dir."}],"ans":"Genotip oranı <b>1:2:1</b>, fenotip oranı <b>3:1</b> (sarı:yeşil) olur."},
  {"q":"Yy × Yy çaprazlamasında sarı (baskın) görünen bir yavrunun heterozigot (Yy) olma olasılığı nedir?","steps":[{"t":"Genotipleri yaz","a":"1 YY:2 Yy:1 yy","d":"F2'de genotipler 1 YY, 2 Yy, 1 yy oranındadır."},{"t":"Sarı bireyleri seç","a":"YY ve Yy","d":"Sarı görünenler YY ve Yy bireyleridir; toplam 3 birimden (1 YY + 2 Yy) oluşur."},{"t":"Olasılığı hesapla","a":"2/3","d":"Sarı 3 birimin 2'si Yy olduğu için heterozigot olma olasılığı 2/3'tür."}],"ans":"Sarı bir yavrunun heterozigot olma olasılığı <b>2/3</b>'tür."},
  {"q":"Mor çiçekli (Aa) iki bitki çaprazlanıyor. Oluşan 480 yavrudan kaçının beyaz (aa) çiçekli olması beklenir?","steps":[{"t":"Çekinik oranı","a":"1/4","d":"Aa × Aa çaprazında çekinik (aa) fenotip oranı 1/4'tür."},{"t":"Sayıyla çarp","a":"480 × 1/4","d":"480 yavrunun 1/4'ü hesaplanır: 480 × 1/4 = 120."},{"t":"Sonucu yaz","a":"120 beyaz","d":"Beklenen beyaz çiçekli yavru sayısı 120'dir."}],"ans":"Yaklaşık <b>120</b> yavrunun beyaz çiçekli olması beklenir."},
  {"q":"Aa × Aa çaprazlamasından elde edilen 360 yavrudan kaç tanesinin baskın fenotipli olması beklenir?","steps":[{"t":"Baskın oranı","a":"3/4","d":"Aa × Aa çaprazında baskın fenotip oranı 3/4'tür (3 baskın : 1 çekinik)."},{"t":"Sayıyla çarp","a":"360 × 3/4","d":"360 yavrunun 3/4'ü: 360 × 3/4 = 270."},{"t":"Sonucu yaz","a":"270 baskın","d":"Beklenen baskın fenotipli yavru sayısı 270'tir."}],"ans":"Yaklaşık <b>270</b> yavrunun baskın fenotipli olması beklenir."},
  {"q":"Tt × Tt çaprazlamasında yavrularda hem homozigot baskın (TT) hem de homozigot çekinik (tt) çıkma olasılığı ayrı ayrı nedir?","steps":[{"t":"Genotipleri yaz","a":"1 TT:2 Tt:1 tt","d":"Tt × Tt çaprazında genotip oranı 1 TT : 2 Tt : 1 tt olur (toplam 4 birim)."},{"t":"Olasılıkları ayır","a":"TT=1/4, tt=1/4","d":"4 birimden 1'i TT, 1'i tt olduğu için her birinin olasılığı 1/4'tür."}],"ans":"TT olma olasılığı <b>1/4</b>, tt olma olasılığı da <b>1/4</b>'tür."},
  {"q":"Bir baskın fenotipli bitki, çekinik (aa) bir bitkiyle çaprazlanınca yavruların yarısı çekinik çıkıyor. Baskın bitkinin genotipi nedir?","steps":[{"t":"Çıkarımı yap","a":"Çekinik var","d":"Çaprazda çekinik (aa) yavru oluşması, baskın bitkinin bir çekinik (a) alel taşıdığını gösterir."},{"t":"Oranı yorumla","a":"1:1 oranı","d":"Yavruların yarısı baskın yarısı çekinik (1:1) çıkmasını ancak Aa × aa çaprazı verir."},{"t":"Sonucu yaz","a":"Aa","d":"Bu nedenle baskın bitkinin genotipi heterozigot (Aa) olmalıdır."}],"ans":"Baskın bitkinin genotipi <b>Aa</b> (heterozigot) olmalıdır."},
  {"q":"Yy × Yy çaprazlamasında bir yavrunun sarı tohumlu olma olasılığı ile aynı anda iki yavrunun da sarı olma olasılığı nedir?","steps":[{"t":"Tek yavru sarı","a":"3/4","d":"Aa türü çaprazda baskın (sarı) fenotip olasılığı 3/4'tür."},{"t":"İki yavru birden","a":"3/4 × 3/4","d":"Bağımsız olaylar olduğu için iki yavrunun da sarı olması: 3/4 × 3/4 = 9/16."},{"t":"Sonucu yaz","a":"9/16","d":"İki yavrunun da sarı olma olasılığı 9/16'dır."}],"ans":"Bir yavru için 3/4; iki yavrunun da sarı olması <b>9/16</b>'dır."},
  {"q":"Tam baskınlığın görülmediği aslanağzında kırmızı (RR) ile beyaz (BB) çiçek çaprazlanınca F1 pembe (RB) oluyor. RB × RB çaprazında F2 fenotip oranı ne olur?","steps":[{"t":"Eksik baskınlık","a":"Ara fenotip","d":"Burada heterozigot (RB) ara renk olan pembe görünür; bu eksik baskınlıktır."},{"t":"Punnett karesi","a":"RR, RB, RB, BB","d":"RB × RB çaprazında yavrular RR, RB, RB, BB oluşur."},{"t":"Fenotipleri grupla","a":"1:2:1","d":"Eksik baskınlıkta her genotip ayrı görünür: 1 kırmızı : 2 pembe : 1 beyaz."}],"ans":"Eksik baskınlık nedeniyle fenotip oranı <b>1:2:1</b> (kırmızı:pembe:beyaz) olur."},
  {"q":"Aa × Aa çaprazlamasından doğan 4 yavrunun da baskın fenotipli olma olasılığı nedir?","steps":[{"t":"Tek yavru baskın","a":"3/4","d":"Her bir yavru için baskın fenotip olasılığı 3/4'tür."},{"t":"Dört yavru çarp","a":"(3/4)⁴","d":"Olaylar bağımsız olduğundan dördünün de baskın olması (3/4)⁴ = 81/256'dır."},{"t":"Sonucu yaz","a":"81/256","d":"Dört yavrunun dördünün de baskın olma olasılığı 81/256 (≈ 0,32) olur."}],"ans":"Dört yavrunun da baskın olma olasılığı <b>81/256</b>'dır."},
  {"q":"Heterozigot uzun (Tt) bir bezelye kendi kendine tozlaşırsa, kısa (tt) yavru elde etme olasılığı ile uzun yavru olasılığını karşılaştırınız.","steps":[{"t":"Çaprazı kur","a":"Tt × Tt","d":"Kendine tozlaşma Tt × Tt çaprazına eşittir."},{"t":"Oranları bul","a":"3/4 uzun, 1/4 kısa","d":"Genotipler 1 TT : 2 Tt : 1 tt; uzun fenotip 3/4, kısa fenotip 1/4 olur."},{"t":"Karşılaştır","a":"Uzun 3 kat","d":"Uzun olma olasılığı (3/4), kısa olma olasılığının (1/4) 3 katıdır."}],"ans":"Uzun yavru olasılığı 3/4, kısa 1/4'tür; uzun olma olasılığı kısanın <b>3 katıdır</b>."},
  {"q":"Aa × aa çaprazlamasından 200 yavru doğuyor. Bunların kaçının çekinik (aa) fenotipli olması beklenir?","steps":[{"t":"Gametleri yaz","a":"A,a ve a","d":"Aa bireyi A ve a; aa bireyi yalnız a gameti verir."},{"t":"Oranı bul","a":"1/2 aa","d":"Yavrular 1/2 Aa, 1/2 aa olur; yani yarısı çekinik fenotiplidir."},{"t":"Sayıyla çarp","a":"200 × 1/2","d":"200 × 1/2 = 100; beklenen çekinik yavru sayısı 100'dür."}],"ans":"Yaklaşık <b>100</b> yavrunun çekinik fenotipli olması beklenir."},
  {"q":"Bir bezelye popülasyonunda Aa × Aa çaprazından oluşan yavrularda baskın fenotip ile çekinik fenotip sayıları 312 ve 104 ölçülmüştür. Bu sonuç hangi teorik orana uyar?","steps":[{"t":"Sayıları oranla","a":"312:104","d":"Gözlenen sayıların oranını sadeleştirelim: 312 ÷ 104 = 3, yani 312:104 = 3:1."},{"t":"Teoriyle karşılaştır","a":"3:1","d":"Bu oran, Aa × Aa monohibrit çaprazının beklenen 3:1 fenotip oranıyla uyumludur."}],"ans":"Sonuç, monohibrit çaprazın beklenen <b>3:1</b> fenotip oranına uyar."},
  {"q":"Yy × yy çaprazlamasından doğan iki yavrunun da yeşil (yy) olma olasılığı nedir?","steps":[{"t":"Tek yavru yeşil","a":"1/2","d":"Yy × yy çaprazında yavrular 1/2 Yy (sarı), 1/2 yy (yeşil) olur; yeşil olasılığı 1/2."},{"t":"İki yavru çarp","a":"1/2 × 1/2","d":"Bağımsız olduğu için iki yavrunun da yeşil olması: 1/2 × 1/2 = 1/4."},{"t":"Sonucu yaz","a":"1/4","d":"İki yavrunun da yeşil olma olasılığı 1/4'tür."}],"ans":"İki yavrunun da yeşil olma olasılığı <b>1/4</b>'tür."},
  {"q":"Aa × Aa çaprazlamasında ilk yavrunun baskın, ikinci yavrunun çekinik fenotipli olma olasılığı nedir?","steps":[{"t":"Tek tek olasılık","a":"3/4 ve 1/4","d":"Baskın fenotip olasılığı 3/4, çekinik fenotip olasılığı 1/4'tür."},{"t":"Sıralı çarpım","a":"3/4 × 1/4","d":"Belirli sıra istendiği için olasılıklar çarpılır: 3/4 × 1/4 = 3/16."},{"t":"Sonucu yaz","a":"3/16","d":"İlk baskın, ikinci çekinik olma olasılığı 3/16'dır."}],"ans":"İlk yavru baskın, ikinci çekinik olma olasılığı <b>3/16</b>'dır."},
  {"q":"Çekinik bir kalıtsal hastalık taşıyan iki sağlıklı (Aa) ebeveynin çocuğunun hasta (aa) olma olasılığı ve sağlıklı çocuğun taşıyıcı (Aa) olma olasılığı nedir?","steps":[{"t":"Çaprazı kur","a":"Aa × Aa","d":"İki taşıyıcı ebeveynin çaprazı Aa × Aa'dır; genotipler 1 AA : 2 Aa : 1 aa olur."},{"t":"Hasta olasılığı","a":"1/4","d":"Hastalık çekinik (aa) olduğundan çocuğun hasta olma olasılığı 1/4'tür."},{"t":"Taşıyıcı olasılığı","a":"2/3","d":"Sağlıklı çocuklar AA ve Aa'dır (3 birim); 2'si Aa olduğundan taşıyıcı olma olasılığı 2/3'tür."}],"ans":"Çocuğun hasta (aa) olma olasılığı <b>1/4</b>; sağlıklı bir çocuğun taşıyıcı olma olasılığı <b>2/3</b>'tür."}
]}}};
