globalThis.__OUT = {"dihibrit":{"ilkokul":{"kolay":[
{"q":"Bir bezelyenin hem sarı tohumu hem de düz yüzeyi var. Bunlar bir bitkide kaç özellik demektir?","steps":[{"t":"Özellikleri say","a":"İki özellik","d":"Burada bir özellik tohum <b>rengi</b> (sarı), bir özellik de tohum <b>yüzeyi</b> (düz) ile ilgilidir."},{"t":"Topla","a":"1 + 1 = 2","d":"Renk ve yüzey iki ayrı özellik olduğu için bezelyede aynı anda iki özelliğe bakılıyor demektir."}],"ans":"Renk ve yüzey iki ayrı özelliktir; yani bu bitkide iki özelliğe birlikte bakılıyor."},
{"q":"Anne kedi hem siyah tüylü hem uzun kuyruklu. Yavruya bu iki özellik birden geçebilir mi?","steps":[{"t":"Özellikler nereden gelir?","a":"Anne ve babadan","d":"Yavru, tüy rengini ve kuyruk uzunluğunu <b>anne ve babasından</b> alır."},{"t":"İki özellik birlikte","a":"Geçebilir","d":"Renk ve kuyruk ayrı ayrı geçtiği için yavruya iki özellik birden geçebilir."}],"ans":"Evet; tüy rengi ve kuyruk uzunluğu birlikte yavruya geçebilir."},
{"q":"Bir çiçeğin hem rengi hem de kokusu var. Bunlardan kaç tanesi özelliktir?","steps":[{"t":"Renk bir özellik mi?","a":"Evet","d":"Çiçeğin <b>rengi</b> onun bir özelliğidir."},{"t":"Koku da özellik mi?","a":"Evet","d":"Çiçeğin <b>kokusu</b> da ayrı bir özelliktir; ikisi birlikte iki özellik eder."}],"ans":"Renk ve koku iki ayrı özelliktir, yani toplam iki özellik vardır."},
{"q":"Bir köpek hem büyük hem de kahverengi. Bu iki özelliği aynı anda söyleyebilir miyiz?","steps":[{"t":"Boy bir özellik","a":"Büyüklük","d":"Köpeğin <b>büyüklüğü</b> bir özelliğidir."},{"t":"Renk de bir özellik","a":"Kahverengi","d":"Köpeğin <b>rengi</b> de ayrı bir özelliktir; ikisini birlikte söyleyebiliriz."}],"ans":"Evet; köpek hem büyük hem kahverengi diyerek iki özelliği birlikte söyleyebiliriz."},
{"q":"İki özelliğe (örneğin hem renk hem boy) aynı anda bakmaya günlük dille ne diyebiliriz?","steps":[{"t":"Kaç özellik var?","a":"İki özellik","d":"Burada renk ve boy gibi <b>iki ayrı özelliğe</b> birden bakılıyor."},{"t":"İkisine birden bakmak","a":"İki özelliği birlikte incelemek","d":"Tek özellik yerine iki özelliği aynı anda incelemeye iki özellikli inceleme diyebiliriz."}],"ans":"İki özelliğe (renk ve boy) aynı anda bakmaya iki özelliği birlikte inceleme denir."}
],"zor":[
{"q":"Bir bitki hem sarı hem düz tohumlu. Başka bir bitki hem yeşil hem buruşuk tohumlu. Toplamda kaç farklı özellik konuşuyoruz?","steps":[{"t":"Hangi özellikler var?","a":"Renk ve yüzey","d":"İki özellik konuşuyoruz: tohum <b>rengi</b> ve tohum <b>yüzeyi</b>."},{"t":"Özellik sayısı","a":"İki özellik","d":"Sarı/yeşil renk özelliği, düz/buruşuk ise yüzey özelliğidir; renk değişse de özellik sayısı yine ikidir."}],"ans":"Renk ve yüzey olmak üzere iki farklı özellik konuşuyoruz."},
{"q":"Bir tavşan hem beyaz tüylü hem uzun kulaklı olabiliyorsa, hem kahverengi tüylü hem kısa kulaklı da olabilir mi?","steps":[{"t":"Özellikler ayrı mı?","a":"Evet, ayrı","d":"Tüy <b>rengi</b> ve kulak <b>uzunluğu</b> birbirinden bağımsız iki özelliktir."},{"t":"Karışık olabilir mi?","a":"Olabilir","d":"İki özellik ayrı ayrı geçtiği için renk ve kulak her türlü birleşebilir."}],"ans":"Evet; renk ve kulak ayrı özellikler olduğu için her türlü birlikte görülebilir."},
{"q":"Anne çiçek hem kırmızı hem uzun, baba çiçek hem beyaz hem kısa. Yavruda kırmızı renk ile kısa boy birlikte görülebilir mi?","steps":[{"t":"Özellikler nereden gelir?","a":"Anneden ve babadan","d":"Yavru <b>rengi</b> bir ebeveynden, <b>boyu</b> başka ebeveynden alabilir."},{"t":"Karışım mümkün mü?","a":"Mümkün","d":"Renk anneden (kırmızı), boy babadan (kısa) gelirse iki özellik karışık birleşebilir."}],"ans":"Evet; renk anneden, boy babadan gelebileceği için kırmızı ve kısa birlikte görülebilir."},
{"q":"İki özellik birlikte düşünülünce kaç farklı görünüş çıkabileceğini örnekle gösterelim: renk (sarı/yeşil) ve yüzey (düz/buruşuk).","steps":[{"t":"Renk seçenekleri","a":"2 tane","d":"Renk için <b>sarı</b> ve <b>yeşil</b> olmak üzere iki seçenek vardır."},{"t":"Eşleştirmeleri yaz","a":"2 × 2 = 4","d":"Her renk her yüzeyle eşleşince sarı-düz, sarı-buruşuk, yeşil-düz, yeşil-buruşuk olmak üzere 4 görünüş çıkar."}],"ans":"İki özellik birleşince sarı-düz, sarı-buruşuk, yeşil-düz, yeşil-buruşuk olmak üzere 4 farklı görünüş olur."},
{"q":"Bir bahçede 4 çeşit fasulye var: sarı-düz, sarı-buruşuk, yeşil-düz, yeşil-buruşuk. Bu çeşitler kaç özelliğin karışmasıyla oluşmuş?","steps":[{"t":"Görünüşlere bak","a":"Renk ve yüzey","d":"İsimlerde hem <b>renk</b> (sarı/yeşil) hem <b>yüzey</b> (düz/buruşuk) geçiyor."},{"t":"Özellik sayısı","a":"İki özellik","d":"Dört çeşit, iki özelliğin (renk ve yüzey) farklı şekillerde birleşmesiyle oluşmuştur."}],"ans":"Bu dört çeşit, renk ve yüzey olmak üzere iki özelliğin karışmasıyla oluşmuştur."}
]},"ortaokul":{"kolay":[
{"q":"Dihibrit çaprazlama ne demektir?","steps":[{"t":"Kaç karaktere bakılır?","a":"İki karakter","d":"Dihibrit çaprazlamada aynı anda <b>iki ayrı karakter</b> (örneğin renk ve yüzey) incelenir."},{"t":"Tanımla","a":"İki karakterli çaprazlama","d":"İki karakter bakımından farklılık gösteren bireylerin çaprazlanmasına dihibrit çaprazlama denir."}],"ans":"Dihibrit çaprazlama, iki karakterin aynı anda incelendiği çaprazlamadır."},
{"q":"AaBb genotipli bir bireyde kaç karakter ve her karakterde hangi aleller vardır?","steps":[{"t":"Harfleri ayır","a":"Aa ve Bb","d":"Genotip iki harf çiftinden oluşur: bir karakter için <b>Aa</b>, diğer karakter için <b>Bb</b>."},{"t":"Karakter sayısı","a":"İki karakter","d":"A/a bir karakterin alelleri, B/b ikinci karakterin alelleridir; yani iki karakter vardır."}],"ans":"AaBb bireyde iki karakter vardır; birinde A ve a, diğerinde B ve b alelleri bulunur."},
{"q":"AaBb genotipli bir birey kaç çeşit ve hangi gametleri oluşturur?","steps":[{"t":"Her karakterden birer alel","a":"A veya a, B veya b","d":"Her gamet, A/a'dan birini ve B/b'den birini alır."},{"t":"Birleştir","a":"AB, Ab, aB, ab","d":"Bu aleller birleşince AB, Ab, aB, ab olmak üzere <b>4 çeşit</b> gamet oluşur."}],"ans":"AaBb bireyi AB, Ab, aB ve ab olmak üzere 4 çeşit gamet oluşturur."},
{"q":"AaBb × AaBb çaprazlamasında oğul döldeki fenotip oranı nedir?","steps":[{"t":"Bilinen oran","a":"9:3:3:1","d":"İki karakter de heterozigot çaprazlandığında klasik <b>9:3:3:1</b> oranı çıkar."},{"t":"Anlamı","a":"Dört fenotip","d":"En çok iki baskın özellikli (9), sonra tek baskınlılar (3 ve 3), en az çift çekinik (1) görülür."}],"ans":"AaBb × AaBb çaprazlamasının fenotip oranı 9:3:3:1'dir."},
{"q":"Bağımsız dağılım ilkesi kısaca neyi söyler?","steps":[{"t":"İki karakter","a":"Ayrı ayrı dağılır","d":"Gamet oluşurken bir karakterin alelleri, diğer karakterinkilerden <b>bağımsız</b> dağılır."},{"t":"Sonuç","a":"Karakterler birbirini etkilemez","d":"Bu yüzden A'nın hangi gamete gittiği B'nin gideceği yeri etkilemez; karakterler bağımsız aktarılır."}],"ans":"Bağımsız dağılım, iki karakterin alellerinin gametlere birbirinden bağımsız dağılmasıdır."}
],"zor":[
{"q":"AaBb × AaBb çaprazlamasında 9:3:3:1 oranındaki sayıların toplamı kaçtır ve bu hangi kareyle ilgilidir?","steps":[{"t":"Sayıları topla","a":"9 + 3 + 3 + 1 = 16","d":"Fenotip oranındaki dört sayıyı toplarsak <b>16</b> elde edilir."},{"t":"Punnett karesi","a":"16'lık kare","d":"Her ebeveyn 4 çeşit gamet verdiğinden Punnett karesi 4 × 4 = 16 kutudan oluşur; toplam da 16'dır."}],"ans":"9 + 3 + 3 + 1 = 16'dır; bu, 4 × 4'lük 16 kutuluk dihibrit Punnett karesiyle ilgilidir."},
{"q":"160 bezelye tohumu AaBb × AaBb çaprazlamasından elde edildi. Çift baskın (sarı-düz) fenotipte kaç tohum beklenir?","steps":[{"t":"Oranı yaz","a":"9/16","d":"9:3:3:1 oranında çift baskın fenotip <b>9/16</b> paya sahiptir."},{"t":"Sayıyla çarp","a":"160 × 9/16 = 90","d":"160 tohumu 9/16 ile çarparsak 160 ÷ 16 = 10, 10 × 9 = 90 tohum bulunur."}],"ans":"Çift baskın (sarı-düz) fenotipte yaklaşık 90 tohum beklenir."},
{"q":"AaBb × AaBb çaprazlamasında her ebeveynin oluşturduğu gamet çeşitleri çarpılırsa Punnett karesinde kaç kutu olur?","steps":[{"t":"Bir ebeveynin gametleri","a":"4 çeşit","d":"AaBb bireyi AB, Ab, aB, ab olmak üzere <b>4 çeşit</b> gamet oluşturur."},{"t":"Kutuları hesapla","a":"4 × 4 = 16","d":"Bir ebeveynin 4 gameti diğerinin 4 gametiyle eşleşince 4 × 4 = 16 kutu çıkar."}],"ans":"Her ebeveyn 4 gamet verdiği için Punnett karesinde 4 × 4 = 16 kutu olur."},
{"q":"AaBb × AaBb çaprazlamasında çift çekinik (yeşil-buruşuk) fenotip oranı nedir ve olasılık çarpımıyla nasıl bulunur?","steps":[{"t":"Her karakter ayrı","a":"aa için 1/4, bb için 1/4","d":"Aa × Aa'dan aa olasılığı 1/4, Bb × Bb'den bb olasılığı da <b>1/4</b>'tür."},{"t":"Olasılıkları çarp","a":"1/4 × 1/4 = 1/16","d":"İki karakter bağımsız olduğundan olasılıklar çarpılır: 1/4 × 1/4 = 1/16."}],"ans":"Çift çekinik fenotip oranı 1/16'dır; 1/4 × 1/4 olasılık çarpımıyla bulunur."},
{"q":"AaBb bireyinin oluşturduğu 4 gamet çeşidini, alelleri tek tek eşleştirerek gösteriniz.","steps":[{"t":"A ile B/b","a":"AB ve Ab","d":"A aleli, B veya b ile birleşerek <b>AB</b> ve <b>Ab</b> gametlerini verir."},{"t":"a ile B/b","a":"aB ve ab","d":"a aleli, B veya b ile birleşerek aB ve ab gametlerini verir; toplam 4 çeşit gamet olur."}],"ans":"AaBb bireyi AB, Ab, aB ve ab olmak üzere 4 çeşit gamet oluşturur."}
]},"lise":{"kolay":[
{"q":"Dihibrit çaprazlama hangi durumu ifade eder?","steps":[{"t":"İncelenen karakter sayısı","a":"İki karakter","d":"Dihibrit çaprazlama, <b>iki ayrı karakter</b> bakımından heterozigot bireylerin çaprazlanmasıdır."},{"t":"Örnek genotip","a":"AaBb × AaBb","d":"Tipik örnek, her iki karakterde de melez olan AaBb × AaBb çaprazlamasıdır."}],"ans":"Dihibrit çaprazlama, iki farklı karakter bakımından heterozigot bireylerin (AaBb × AaBb) çaprazlanmasıdır."},
{"q":"AaBb genotipli bir birey kaç çeşit gamet oluşturur ve bunlar nelerdir?","steps":[{"t":"Her karakterden bir alel","a":"A/a ve B/b","d":"Mayozda her gamet A veya a'dan birini, B veya b'den birini alır."},{"t":"Kombinasyonları yaz","a":"AB, Ab, aB, ab","d":"İki karakterin alelleri bağımsız birleşince 2² = 4 çeşit gamet oluşur: <b>AB, Ab, aB, ab</b>."}],"ans":"AaBb bireyi AB, Ab, aB, ab olmak üzere 4 çeşit gamet oluşturur."},
{"q":"AaBb × AaBb çaprazlamasının klasik fenotip oranı nedir?","steps":[{"t":"Mendel sonucu","a":"9:3:3:1","d":"İki bağımsız karakter heterozigot çaprazlandığında oğul dölde <b>9:3:3:1</b> fenotip oranı görülür."},{"t":"Oranın anlamı","a":"Dört fenotip sınıfı","d":"9 çift baskın, 3 ve 3 tek baskın, 1 çift çekinik bireyi temsil eder."}],"ans":"AaBb × AaBb çaprazlamasının klasik fenotip oranı 9:3:3:1'dir."},
{"q":"Bağımsız dağılım (bağımsız açılım) ilkesi nedir?","steps":[{"t":"Hangi karakterler","a":"Farklı kromozomlardaki genler","d":"İlke, farklı kromozomlarda yer alan genlerin (karakterlerin) gametlere <b>bağımsız</b> dağıldığını söyler."},{"t":"Mayozdaki temeli","a":"Homologların rastgele dizilişi","d":"Mayoz I'de homolog kromozom çiftleri ekvatorda rastgele dizildiğinden bir karakterin aktarımı diğerini etkilemez."}],"ans":"Bağımsız dağılım, farklı kromozomlardaki karakterlerin alellerinin gametlere birbirinden bağımsız olarak dağılmasıdır."},
{"q":"Dihibrit Punnett karesinde neden 16 kutu bulunur?","steps":[{"t":"Gamet çeşidi","a":"Her ebeveyn 4 çeşit","d":"AaBb bireyi <b>4 çeşit</b> gamet oluşturur."},{"t":"Kareyi oluştur","a":"4 × 4 = 16","d":"Bir ebeveynin 4 gameti diğerinin 4 gametiyle eşleştiğinden kare 4 × 4 = 16 kutudan oluşur."}],"ans":"Her ebeveyn 4 çeşit gamet oluşturduğundan Punnett karesi 4 × 4 = 16 kutu içerir."},
{"q":"AaBb × AaBb çaprazlamasında çift çekinik (aabb) fenotip oranı nedir?","steps":[{"t":"Her karakteri ayır","a":"aa: 1/4, bb: 1/4","d":"Aa × Aa'dan aa olasılığı 1/4, Bb × Bb'den bb olasılığı <b>1/4</b>'tür."},{"t":"Olasılıkları çarp","a":"1/4 × 1/4 = 1/16","d":"Bağımsız olaylar olduğu için olasılıklar çarpılır ve 1/16 bulunur."}],"ans":"Çift çekinik (aabb) fenotip oranı 1/16'dır."},
{"q":"Olasılık çarpımı yöntemi dihibrit çaprazlamada neden kullanılır?","steps":[{"t":"Karakterlerin ilişkisi","a":"Bağımsız","d":"İki karakter bağımsız dağıldığından her birinin olasılığı <b>ayrı ayrı</b> hesaplanabilir."},{"t":"Çarpım kuralı","a":"Olasılıkları çarp","d":"Bağımsız olayların birlikte gerçekleşme olasılığı, tek tek olasılıklarının çarpımına eşittir; bu yüzden 16'lık kare çizmeden sonuç bulunur."}],"ans":"İki karakter bağımsız olduğundan olasılık çarpımı yöntemiyle kareyi çizmeden istenen fenotip olasılığı hızlıca hesaplanır."},
{"q":"AaBb × AaBb çaprazlamasında bir karakter için baskın fenotip olasılığı nedir?","steps":[{"t":"Aa × Aa sonucu","a":"3 baskın : 1 çekinik","d":"Tek karakterlik Aa × Aa çaprazlamasında <b>3/4</b> baskın, 1/4 çekinik fenotip görülür."},{"t":"Olasılığı yaz","a":"3/4","d":"Dolayısıyla bir karakterde baskın fenotip olasılığı 3/4'tür."}],"ans":"Bir karakter için baskın fenotip olasılığı 3/4'tür."},
{"q":"9:3:3:1 oranında '9' hangi fenotip grubunu temsil eder?","steps":[{"t":"En büyük grup","a":"Çift baskın","d":"Oranın <b>9</b> kısmı, her iki karakterde de baskın fenotip gösteren bireyleri temsil eder."},{"t":"Olasılıkla doğrula","a":"3/4 × 3/4 = 9/16","d":"Her karakterde baskın olasılığı 3/4 olduğundan ikisinin çarpımı 9/16 olur; bu da 9'a karşılık gelir."}],"ans":"9:3:3:1 oranındaki '9', her iki karakterde de baskın fenotip gösteren (çift baskın) bireyleri temsil eder."},
{"q":"AaBb × AaBb çaprazlamasında her iki karakterde de baskın fenotip olasılığı olasılık çarpımıyla nasıl bulunur?","steps":[{"t":"Tek karakter olasılığı","a":"3/4","d":"Her karakterde baskın fenotip olasılığı Aa × Aa'dan <b>3/4</b>'tür."},{"t":"İkisini çarp","a":"3/4 × 3/4 = 9/16","d":"İki karakter bağımsız olduğundan olasılıklar çarpılır: 3/4 × 3/4 = 9/16."}],"ans":"Her iki karakterde de baskın fenotip olasılığı 3/4 × 3/4 = 9/16'dır."},
{"q":"AaBb genotipinin genotip ve fenotip arasındaki ilişkisi nasıldır?","steps":[{"t":"Genotip","a":"AaBb (melez)","d":"AaBb, her iki karakterde de bir baskın bir çekinik alel taşıyan <b>heterozigot</b> genotiptir."},{"t":"Fenotip","a":"Çift baskın görünüm","d":"Baskın aleller etkisini gösterdiğinden birey, her iki karakterde de baskın fenotipi sergiler."}],"ans":"AaBb genotipi her iki karakterde de heterozigottur ve fenotipte her iki karakterin baskın özelliğini gösterir."},
{"q":"Dihibrit çaprazlamada gamet çeşidi sayısı nasıl hesaplanır?","steps":[{"t":"Heterozigot karakter sayısı","a":"n = 2","d":"Birey, iki karakter bakımından da heterozigot olduğundan heterozigot gen sayısı <b>2</b>'dir."},{"t":"Formülü uygula","a":"2ⁿ = 2² = 4","d":"Gamet çeşidi 2ⁿ ile bulunur; n = 2 için 2² = 4 çeşit gamet oluşur."}],"ans":"Heterozigot karakter sayısı n ise gamet çeşidi 2ⁿ'dir; AaBb için 2² = 4 çeşit gamet oluşur."},
{"q":"AaBb × AaBb çaprazlamasında 9:3:3:1 oranındaki iki '3'lük grup neyi temsil eder?","steps":[{"t":"Birinci 3","a":"A baskın, b çekinik","d":"Bir '3'lük grup, birinci karakterde baskın, ikinci karakterde çekinik fenotip gösteren bireylerdir (A_bb)."},{"t":"İkinci 3","a":"a çekinik, B baskın","d":"Diğer '3'lük grup ise birinci karakterde çekinik, ikincide baskın fenotipli bireylerdir (aaB_)."}],"ans":"İki '3'lük grup, bir karakterde baskın diğerinde çekinik fenotip gösteren iki ayrı birey grubunu (A_bb ve aaB_) temsil eder."},
{"q":"AaBb × AaBb çaprazlamasında aabb (çift çekinik) genotipi hangi gametlerin birleşmesiyle oluşur?","steps":[{"t":"Gerekli gametler","a":"ab ve ab","d":"aabb oluşması için her iki ebeveynden de <b>ab</b> gametinin gelmesi gerekir."},{"t":"Olasılığı yaz","a":"1/4 × 1/4 = 1/16","d":"Her ebeveynde ab gameti olasılığı 1/4 olduğundan ikisinin birleşme olasılığı 1/16'dır."}],"ans":"aabb genotipi, her iki ebeveynden gelen ab gametlerinin birleşmesiyle oluşur ve olasılığı 1/16'dır."},
{"q":"AaBb × AaBb çaprazlamasında yalnızca bir karakterde baskın fenotip gösteren bireylerin toplam oranı nedir?","steps":[{"t":"İki olası grup","a":"A_bb ve aaB_","d":"Tek karakterde baskın olan bireyler ya birinci karakterde baskın (<b>A_bb</b>) ya da ikinci karakterde baskındır (aaB_)."},{"t":"Her grubun oranı","a":"3/16","d":"A_bb için 3/4 × 1/4 = 3/16, aaB_ için 1/4 × 3/4 = 3/16 olur."},{"t":"Toplamı al","a":"3/16 + 3/16 = 6/16","d":"İki grup toplanınca 6/16 (sadeleşmiş 3/8) bulunur."}],"ans":"Yalnızca bir karakterde baskın fenotip gösteren bireylerin toplam oranı 6/16'dır (3/8)."}
],"zor":[
{"q":"AaBb × AaBb çaprazlamasında 9:3:3:1 fenotip oranının olasılık çarpımıyla nasıl ortaya çıktığını adım adım gösteriniz.","steps":[{"t":"Tek karakter oranları","a":"3/4 baskın, 1/4 çekinik","d":"Her karakterde Aa × Aa'dan baskın fenotip <b>3/4</b>, çekinik 1/4 çıkar."},{"t":"Dört kombinasyon","a":"Çarpımları al","d":"Baskın-baskın 3/4 × 3/4 = 9/16, baskın-çekinik 3/4 × 1/4 = 3/16, çekinik-baskın 1/4 × 3/4 = 3/16, çekinik-çekinik 1/4 × 1/4 = 1/16."},{"t":"Oranı yaz","a":"9:3:3:1","d":"Paydalar eşit (16) olduğundan paylar 9, 3, 3, 1 olarak yazılır ve klasik 9:3:3:1 oranı elde edilir."}],"ans":"Her karakterde 3/4 ve 1/4 olasılıkları çarpılınca 9/16, 3/16, 3/16 ve 1/16 çıkar; bu da 9:3:3:1 fenotip oranını verir."},
{"q":"320 bireylik bir dihibrit (AaBb × AaBb) çaprazlamasında dört fenotip grubundaki birey sayılarını hesaplayınız.","steps":[{"t":"Bir birim payı","a":"320 ÷ 16 = 20","d":"Oran toplamı 16 olduğundan 320 birey 16'ya bölünür: bir birim <b>20</b> bireye karşılık gelir."},{"t":"Grupları çarp","a":"9·20, 3·20, 3·20, 1·20","d":"9 × 20 = 180, 3 × 20 = 60, 3 × 20 = 60, 1 × 20 = 20 birey bulunur."},{"t":"Sonucu yaz","a":"180:60:60:20","d":"Dört fenotip grubu sırasıyla 180, 60, 60 ve 20 bireyden oluşur; toplam yine 320'dir."}],"ans":"Dört fenotip grubu sırasıyla 180, 60, 60 ve 20 bireydir (çift baskın 180, tek baskınlar 60'ar, çift çekinik 20)."},
{"q":"AaBb × AaBb çaprazlamasında en az bir karakterde çekinik fenotip gösteren bireylerin oranını hesaplayınız.","steps":[{"t":"Tümleyenle düşün","a":"1 − P(ikisi de baskın)","d":"En az bir çekinik olma olasılığı, hiç çekinik olmama (her ikisi de baskın) olasılığının <b>tümleyenidir</b>."},{"t":"İkisi de baskın","a":"3/4 × 3/4 = 9/16","d":"Her iki karakterde de baskın fenotip olasılığı 9/16'dır."},{"t":"Tümleyeni al","a":"1 − 9/16 = 7/16","d":"En az bir karakterde çekinik gösterme olasılığı 16/16 − 9/16 = 7/16'dır."}],"ans":"En az bir karakterde çekinik fenotip gösteren bireylerin oranı 7/16'dır."},
{"q":"AaBb × Aabb çaprazlamasında oğul döldeki fenotip oranını olasılık çarpımıyla bulunuz.","steps":[{"t":"Birinci karakter","a":"Aa × Aa → 3:1","d":"İlk karakterde Aa × Aa olduğundan baskın : çekinik oranı <b>3/4 : 1/4</b>'tür."},{"t":"İkinci karakter","a":"Bb × bb → 1:1","d":"İkinci karakterde Bb × bb olduğundan baskın : çekinik oranı 1/2 : 1/2'dir."},{"t":"Oranları birleştir","a":"(3:1)·(1:1)","d":"İki oran çarpılınca 3·1 : 3·1 : 1·1 : 1·1 = 3:3:1:1 fenotip oranı elde edilir."}],"ans":"AaBb × Aabb çaprazlamasının fenotip oranı 3:3:1:1'dir."},
{"q":"AaBb genotipli bir bireyin 4 çeşit gamet oluşturmasını mayozdaki bağımsız dağılımla açıklayınız.","steps":[{"t":"Homologların dizilişi","a":"İki olası dizilim","d":"Mayoz I'de A/a ve B/b'yi taşıyan homolog çiftler ekvatorda <b>iki farklı</b> şekilde dizilebilir."},{"t":"Dizilimlerin gametleri","a":"AB,ab veya Ab,aB","d":"Bir dizilim AB ve ab gametlerini, diğer dizilim Ab ve aB gametlerini verir."},{"t":"Toplam çeşit","a":"4 çeşit","d":"İki dizilim eşit olasılıkla görüldüğünden toplamda AB, Ab, aB, ab olmak üzere 4 çeşit gamet eşit oranda oluşur."}],"ans":"Mayoz I'de homolog çiftlerin iki farklı bağımsız dizilimi, AB, Ab, aB ve ab olmak üzere 4 çeşit gametin eşit oranda oluşmasını sağlar."},
{"q":"Bir dihibrit çaprazlamada oğul dölün 3/16'sı yeşil-buruşuk dışında tek çekinikli çıkıyor diye düşünülüyor. AaBb × AaBb için tek karakterde çekinik (A_bb veya aaB_) oranlarını ayrı ayrı bulunuz.","steps":[{"t":"A_bb grubu","a":"3/4 × 1/4","d":"Birinci karakterde baskın (3/4), ikincide çekinik (1/4) olma olasılığı çarpılır: <b>3/16</b>."},{"t":"aaB_ grubu","a":"1/4 × 3/4","d":"Birinci karakterde çekinik (1/4), ikincide baskın (3/4) olma olasılığı çarpılır: 3/16."},{"t":"Karşılaştır","a":"İkisi de 3/16","d":"Her iki tek çekinikli grup da 3/16 oranındadır; toplam tek çekinikli oran 3/16 + 3/16 = 6/16'dır."}],"ans":"A_bb ve aaB_ gruplarının her biri 3/16 oranındadır; tek karakterde çekinik gösteren toplam oran 6/16'dır."},
{"q":"AaBb × aabb (kontrol çaprazlaması) yapıldığında oğul döldeki fenotip oranını bulunuz ve neden gamet çeşitlerini doğrudan yansıttığını açıklayınız.","steps":[{"t":"aabb'nin gameti","a":"Tek çeşit: ab","d":"aabb bireyi yalnızca <b>ab</b> gameti verir; bu çekinik gamet baskın aleli maskelemez."},{"t":"AaBb'nin gametleri","a":"AB, Ab, aB, ab","d":"AaBb bireyi 4 çeşit gamet verir; her biri ab ile birleşince doğrudan kendi fenotipini gösterir."},{"t":"Oranı yaz","a":"1:1:1:1","d":"Dört gamet eşit oranda olduğundan oğul dölde dört fenotip 1:1:1:1 oranında çıkar."}],"ans":"AaBb × aabb çaprazlamasının fenotip oranı 1:1:1:1'dir; çekinik birey tek çeşit (ab) gamet verdiğinden oğul döl, AaBb bireyinin gamet çeşitlerini doğrudan yansıtır."},
{"q":"Bir dihibrit (AaBb × AaBb) çaprazlamasında 16'lık Punnett karesinde AABB genotipinin neden sadece 1 kutuda çıktığını gösteriniz.","steps":[{"t":"Gerekli gametler","a":"AB ve AB","d":"AABB oluşması için her iki ebeveynden de <b>AB</b> gametinin gelmesi gerekir."},{"t":"Olasılığı hesapla","a":"1/4 × 1/4 = 1/16","d":"Her ebeveynde AB gameti olasılığı 4 gametten biri olduğu için 1/4'tür; ikisi çarpılınca 1/16 olur."},{"t":"Kutu sayısı","a":"1 kutu","d":"16 kutuluk karede 1/16 olasılık, tam olarak 1 kutuya karşılık gelir."}],"ans":"AABB yalnızca AB × AB birleşmesiyle oluşur; olasılığı 1/4 × 1/4 = 1/16 olduğundan 16'lık karede sadece 1 kutuda görülür."},
{"q":"AaBb × AaBb çaprazlamasında 9 çift baskın bireyin genotip dağılımını (AABB, AABb, AaBB, AaBb) olasılıklarıyla gösteriniz.","steps":[{"t":"Birinci karakter genotipleri","a":"AA: 1/4, Aa: 2/4","d":"Aa × Aa'dan baskın fenotipliler AA (1/4) ve <b>Aa</b> (2/4) genotiplidir."},{"t":"İkinci karakterle çarp","a":"BB:1/4, Bb:2/4","d":"Aynı şekilde Bb × Bb'den BB (1/4) ve Bb (2/4) çıkar; genotipler çarpılır."},{"t":"Dört genotip","a":"1:2:2:4","d":"AABB = 1/4·1/4 = 1/16, AABb = 1/4·2/4 = 2/16, AaBB = 2/4·1/4 = 2/16, AaBb = 2/4·2/4 = 4/16; toplam 9/16."}],"ans":"9'luk çift baskın grup AABB:AABb:AaBB:AaBb = 1:2:2:4 oranındadır; payları 1/16, 2/16, 2/16 ve 4/16 olup toplamı 9/16'dır."},
{"q":"Trihibrit AaBbCc bireyiyle karşılaştırarak, dihibrit AaBb bireyinin gamet çeşidi sayısının 2ⁿ formülüyle nasıl bulunduğunu açıklayınız.","steps":[{"t":"Formülün mantığı","a":"Her heterozigotta 2 seçenek","d":"Heterozigot her karakter gamete 2 farklı alelden birini verebildiğinden çeşit sayısı <b>2ⁿ</b> ile bulunur (n = heterozigot karakter sayısı)."},{"t":"Dihibrit hesabı","a":"2² = 4","d":"AaBb'de n = 2 olduğundan 2² = 4 çeşit gamet (AB, Ab, aB, ab) oluşur."},{"t":"Trihibritle karşılaştır","a":"2³ = 8","d":"AaBbCc'de n = 3 olduğundan 2³ = 8 çeşit gamet oluşur; her ek heterozigot karakter çeşit sayısını ikiye katlar."}],"ans":"Gamet çeşidi 2ⁿ ile bulunur; dihibrit AaBb için 2² = 4, trihibrit AaBbCc için 2³ = 8 çeşit gamet oluşur."},
{"q":"AaBb × AaBb çaprazlamasında oğul dölün hem A hem B bakımından homozigot (AABB, AAbb, aaBB, aabb) olma olasılığını toplam olarak bulunuz.","steps":[{"t":"Bir karakterde homozigot","a":"AA veya aa: 1/2","d":"Aa × Aa'da AA (1/4) ve aa (1/4) toplamı homozigot olma olasılığı <b>1/2</b>'dir."},{"t":"İki karakter için","a":"1/2 × 1/2","d":"İki karakter bağımsız olduğundan her ikisinde de homozigot olma olasılığı 1/2 × 1/2 ile bulunur."},{"t":"Sonucu hesapla","a":"1/4","d":"1/2 × 1/2 = 1/4; yani oğul dölün 4'te 1'i her iki karakterde de homozigottur."}],"ans":"Oğul dölün her iki karakterde de homozigot (AABB, AAbb, aaBB veya aabb) olma olasılığı 1/4'tür."},
{"q":"İki karakteri bağlı (aynı kromozomda) olan bir bireyin neden 9:3:3:1 oranı vermeyebileceğini bağımsız dağılım ilkesiyle ilişkilendirerek açıklayınız.","steps":[{"t":"9:3:3:1 şartı","a":"Bağımsız dağılım","d":"Klasik 9:3:3:1 oranı, iki karakterin <b>farklı kromozomlarda</b> bulunup bağımsız dağılmasına dayanır."},{"t":"Bağlı genler","a":"Birlikte kalıtım","d":"Genler aynı kromozomdaysa (bağlı), gametlere genellikle birlikte aktarılır ve bağımsız dağılım gerçekleşmez."},{"t":"Sonuç","a":"Oran sapar","d":"Bu yüzden ata genotip kombinasyonları beklenenden fazla, yeni kombinasyonlar (krossing-over ile) az çıkar; fenotip oranı 9:3:3:1'den sapar."}],"ans":"9:3:3:1 oranı bağımsız dağılıma dayanır; karakterler aynı kromozomda bağlıysa birlikte kalıtıldıklarından bağımsız dağılım bozulur ve fenotip oranı 9:3:3:1'den sapar."},
{"q":"Bir dihibrit çaprazlamadan elde edilen 800 tohumda çift baskın fenotipli 460 birey sayıldı. Bu sonucun beklenen 9/16 oranına ne kadar uyduğunu hesaplayarak yorumlayınız.","steps":[{"t":"Beklenen sayı","a":"800 × 9/16 = 450","d":"Beklenen çift baskın birey sayısı 800'ün <b>9/16</b>'sıdır: 800 ÷ 16 = 50, 50 × 9 = 450."},{"t":"Gözlemle karşılaştır","a":"460 ≈ 450","d":"Gözlenen 460 birey, beklenen 450'ye çok yakındır; aradaki fark yalnızca 10 bireydir."},{"t":"Yorumla","a":"Orana uyumlu","d":"Küçük sapma rastgele örnekleme dalgalanmasıyla açıklanabilir; sonuç 9/16 beklentisiyle uyumludur."}],"ans":"Beklenen çift baskın sayı 450'dir; gözlenen 460 buna çok yakın olduğundan sonuç, küçük rastgele sapmayla 9/16 oranına uyumludur."},
{"q":"AaBb × AaBb çaprazlamasında oğul dölün AaBb genotipli olma olasılığının neden 4/16 (en yüksek tek genotip) olduğunu açıklayınız.","steps":[{"t":"Birinci karakter","a":"Aa olasılığı 2/4","d":"Aa × Aa çaprazlamasında Aa genotipi iki kutuda çıktığından olasılığı <b>2/4</b>'tür."},{"t":"İkinci karakter","a":"Bb olasılığı 2/4","d":"Aynı şekilde Bb × Bb'den Bb genotipi olasılığı da 2/4'tür."},{"t":"İkisini çarp","a":"2/4 × 2/4 = 4/16","d":"İki bağımsız olasılık çarpılınca AaBb olma olasılığı 4/16 olur; her iki karakterde de heterozigotluk en olası durum olduğundan bu tek genotipler içinde en yüksektir."}],"ans":"Her karakterde heterozigot (Aa, Bb) olma olasılığı 2/4 olduğundan AaBb genotipi 2/4 × 2/4 = 4/16 ile tek genotipler arasında en yüksek olasılığa sahiptir."},
{"q":"AaBb × AaBb çaprazlamasında bir tohumun sarı (A baskın) VE yüzeyinin çekinik (bb buruşuk) olma olasılığını, ardından kardeşinin de aynı fenotipte olma olasılığını hesaplayınız.","steps":[{"t":"Tek tohumun olasılığı","a":"3/4 × 1/4 = 3/16","d":"Sarı (baskın) olasılığı 3/4, buruşuk (çekinik) olasılığı 1/4'tür; bağımsız olduklarından çarpılır: <b>3/16</b>."},{"t":"İki bağımsız tohum","a":"Olasılıkları çarp","d":"İki ayrı tohumun fenotipi birbirinden bağımsız olduğundan, ikisinin de sarı-buruşuk olma olasılığı tek tek olasılıkların çarpımıdır."},{"t":"Sonucu hesapla","a":"3/16 × 3/16 = 9/256","d":"3/16 × 3/16 = 9/256; yani her iki tohumun da sarı-buruşuk olma olasılığı 9/256'dır."}],"ans":"Bir tohumun sarı-buruşuk olma olasılığı 3/16'dır; iki bağımsız tohumun ikisinin de bu fenotipte olma olasılığı 3/16 × 3/16 = 9/256'dır."}
]}}};
