globalThis.__OUT = {"buzGenlesme":{"ilkokul":{"kolay":[
{"q":"Suyu buzluğa koyup dondurduğumuzda kabın içinde ne olur?","steps":[{"t":"Su donar","a":"buz olur","d":"Buzluktaki soğuk, sıvı suyu katı buza çevirir."},{"t":"Yer kaplar","a":"şişer","d":"Buz, sudan biraz daha fazla yer kapladığı için kabın içinde kabarır."}],"ans":"Su donunca buza döner ve eskisinden biraz daha fazla yer kaplar (şişer)."},
{"q":"Bir bardak suyu ağzına kadar doldurup dondurursak ne görürüz?","steps":[{"t":"Su donar","a":"buz olur","d":"Bardaktaki su soğuyunca katı buz hâline gelir."},{"t":"Taşar/kabarır","a":"yukarı çıkar","d":"Buz daha çok yer kapladığı için bardağın üstünden taşıp kabarır."}],"ans":"Donan su şiştiği için bardağın ağzından yukarı doğru kabarır."},
{"q":"Buz parçası bir bardak suya atıldığında ne yapar?","fig":"<svg viewBox='0 0 320 180'><rect x='90' y='40' width='140' height='110' fill='none' stroke='#1a2b45'/><rect x='92' y='80' width='136' height='68' fill='#cfe3f5'/><rect x='130' y='62' width='40' height='30' fill='#eaf4fc' stroke='#2b6be0'/><text x='160' y='168' font-size='12' text-anchor='middle' fill='#1a2b45'>buz suda yüzer</text></svg>","steps":[{"t":"Suya atılır","a":"batmaz","d":"Buz parçası suyun dibine inmez, üstte kalır."},{"t":"Yüzer","a":"hafif olduğu için","d":"Buz, sudan daha hafif olduğu için suyun üstünde yüzer."}],"ans":"Buz, sudan hafif olduğu için suya atınca batmaz, üstte yüzer."},
{"q":"Kışın çok soğukta su borusu neden patlayabilir?","steps":[{"t":"Su donar","a":"buz olur","d":"Borunun içindeki su soğukta donar."},{"t":"Şişer","a":"boruyu zorlar","d":"Donan su şişip yer kaplayınca boruyu içeriden zorlar ve patlatabilir."}],"ans":"Borudaki su donunca şişer ve boruyu zorlayarak patlatabilir."},
{"q":"Buzdolabında dondurduğumuz su şişesini neden ağzına kadar doldurmamalıyız?","steps":[{"t":"Su donar","a":"buz olur","d":"Şişedeki su donunca buza döner."},{"t":"Yer kaplar","a":"şişeyi şişirir","d":"Buz daha çok yer kapladığı için tam dolu şişeyi şişirip patlatabilir."}],"ans":"Donan su şiştiği için tam dolu şişe çatlayabilir; bu yüzden biraz boşluk bırakırız."}
],"zor":[
{"q":"Kışın göl yüzeyi buz tutarken altındaki su neden hâlâ sıvı kalır?","steps":[{"t":"Buz hafiftir","a":"üstte kalır","d":"Donan su hafiflediği için buz gölün üstünde yüzer."},{"t":"Alt korunur","a":"su sıvı kalır","d":"Üstteki buz tabakası örtü gibi davranıp alttaki suyun daha fazla soğumasını yavaşlatır."}],"ans":"Buz üstte yüzüp örtü oluşturduğu için göl dibindeki su sıvı kalabilir."},
{"q":"Balıklar kışın buz tutan gölde nasıl yaşamaya devam edebilir?","steps":[{"t":"Buz üstte","a":"yüzer","d":"Buz sudan hafif olduğu için gölün üst kısmını kaplar."},{"t":"Alt su sıvı","a":"yaşam sürer","d":"Buzun altındaki su donmadan sıvı kalır, balıklar burada yaşayabilir."}],"ans":"Buz üstte kaldığı için altındaki su donmaz; balıklar bu sıvı suda yaşar."},
{"q":"Aynı miktar su ile aynı miktar buzdan hangisi daha çok yer kaplar?","fig":"<svg viewBox='0 0 320 180'><rect x='60' y='70' width='70' height='80' fill='#cfe3f5' stroke='#1a2b45'/><text x='95' y='168' font-size='12' text-anchor='middle' fill='#1a2b45'>su</text><rect x='200' y='50' width='70' height='100' fill='#eaf4fc' stroke='#2b6be0'/><text x='235' y='168' font-size='12' text-anchor='middle' fill='#1a2b45'>buz</text></svg>","steps":[{"t":"Su donar","a":"buz olur","d":"Su donduğunda buza dönüşür."},{"t":"Hacim artar","a":"buz büyür","d":"Aynı kütledeki buz, sudan daha fazla yer kapladığı için daha büyüktür."}],"ans":"Aynı kütlede buz, sudan daha çok yer kaplar."},
{"q":"Bir göl, dipten yukarı doğru değil de üstten aşağı doğru donsaydı canlılar için ne olurdu?","steps":[{"t":"Normal durum","a":"üstten donar","d":"Gerçekte buz üstte yüzer, alt su sıvı kalır ve canlılar korunur."},{"t":"Tersi olsaydı","a":"dip donardı","d":"Buz dibe çökseydi göl tabandan tepeye kadar tamamen donardı."}],"ans":"Göl tümüyle donar, dipteki canlılar yaşayacak sıvı su bulamazdı."},
{"q":"Kayalardaki çatlaklara dolan su kışın kayayı nasıl parçalar?","steps":[{"t":"Su dolar","a":"çatlağa girer","d":"Yağmur veya kar suyu kayanın çatlaklarına dolar."},{"t":"Donup şişer","a":"kayayı çatlatır","d":"Donan su şişip çatlağı içeriden zorlar ve kayayı zamanla parçalar."}],"ans":"Çatlağa dolan su donup şişerek kayayı içeriden zorlar ve parçalar."}
]},"ortaokul":{"kolay":[
{"q":"Su donduğunda yoğunluğu neden azalır?","steps":[{"t":"Hacim artar","a":"buz şişer","d":"Su donunca molekülleri daha geniş yerleşir, hacmi artar."},{"t":"Yoğunluk düşer","a":"d = kütle/hacim","d":"Kütle aynı kalıp hacim arttığı için yoğunluk (kütle/hacim) azalır."}],"ans":"Su donunca hacmi arttığı için yoğunluğu azalır."},
{"q":"Buzun suda yüzmesinin temel nedeni nedir?","fig":"<svg viewBox='0 0 320 180'><rect x='80' y='50' width='160' height='110' fill='none' stroke='#1a2b45'/><rect x='82' y='90' width='156' height='68' fill='#cfe3f5'/><rect x='130' y='70' width='44' height='32' fill='#eaf4fc' stroke='#2b6be0'/><text x='160' y='175' font-size='11' text-anchor='middle' fill='#1a2b45'>buz: daha az yoğun</text></svg>","steps":[{"t":"Yoğunluk farkı","a":"buz < su","d":"Buzun yoğunluğu sıvı sudan daha düşüktür."},{"t":"Yüzme","a":"hafif üstte kalır","d":"Daha az yoğun cisim daha yoğun sıvının üstünde yüzer."}],"ans":"Buz sudan daha az yoğun olduğu için suyun üstünde yüzer."},
{"q":"Suyun en yoğun olduğu sıcaklık kaç derecedir?","steps":[{"t":"Anomali","a":"+4 °C","d":"Su 4 °C'de en küçük hacme, dolayısıyla en yüksek yoğunluğa ulaşır."},{"t":"Daha soğuk","a":"genleşir","d":"4 °C'den daha soğutulunca su yeniden genleşir, donunca iyice şişer."}],"ans":"Su, +4 °C'de en yoğundur; bundan daha soğukta genleşmeye başlar."},
{"q":"Buzun yapısında moleküller suya göre nasıl dizilir?","steps":[{"t":"Buz örgüsü","a":"düzenli açık","d":"Buzda su molekülleri düzenli, boşluklu bir kafes (örgü) oluşturur."},{"t":"Sonuç","a":"hacim artar","d":"Bu açık örgü, sıvı sudan daha fazla yer kapladığı için hacim artar."}],"ans":"Buzda moleküller düzenli ve boşluklu dizilir, bu yüzden hacim artar."},
{"q":"Göllerin üstten donması canlılar için neden önemlidir?","steps":[{"t":"Buz yüzer","a":"üstte tabaka","d":"Buz sudan hafif olduğu için göl yüzeyinde tabaka oluşturur."},{"t":"Yalıtım","a":"alt sıvı kalır","d":"Bu buz tabakası ısı yalıtımı yapar, alttaki suyun donmasını yavaşlatır."}],"ans":"Üstte yüzen buz yalıtım yapar, alttaki su sıvı kalır ve canlılar korunur."}
],"zor":[
{"q":"Suyun yoğunluk anomalisi hidrojen bağlarıyla nasıl açıklanır?","steps":[{"t":"Hidrojen bağı","a":"molekülleri bağlar","d":"Su molekülleri arasında çekici hidrojen bağları kurulur."},{"t":"Donunca","a":"açık örgü","d":"Donarken her molekül 4 komşusuyla bağ kurup düzenli, boşluklu bir örgü oluşturur."},{"t":"Sonuç","a":"hacim artar","d":"Bu boşluklu yerleşim hacmi büyütür, yoğunluğu düşürür."}],"ans":"Donunca hidrojen bağları boşluklu açık örgü kurar; hacim artar, yoğunluk azalır."},
{"q":"Su 4 °C'den 0 °C'ye soğutulurken hacmi nasıl değişir, neden?","steps":[{"t":"4 °C","a":"en küçük hacim","d":"Su 4 °C'de en yoğundur, yani hacmi en küçüktür."},{"t":"Soğutma","a":"hacim büyür","d":"4 °C'nin altında hidrojen bağları açık örgü kurmaya başlar, hacim genişler."},{"t":"Donma","a":"ani sıçrama","d":"0 °C'de tam buz örgüsü kurulunca hacim daha da artar."}],"ans":"4 °C'den 0 °C'ye soğurken su genleşir; açık örgü kurulduğu için hacmi büyür."},
{"q":"Eşit kütledeki su 0 °C'de donunca hacmi yaklaşık nasıl değişir, yoğunluğa etkisi nedir?","steps":[{"t":"Su yoğunluğu","a":"~1 g/cm³","d":"Sıvı suyun yoğunluğu yaklaşık 1 g/cm³'tür."},{"t":"Buz yoğunluğu","a":"~0,92 g/cm³","d":"Buzun yoğunluğu yaklaşık 0,92 g/cm³'e düşer, hacim yaklaşık %9 artar."},{"t":"Sonuç","a":"buz yüzer","d":"Yoğunluk azaldığı için buz suyun üstünde yüzer."}],"ans":"Donunca hacim yaklaşık %9 artar, yoğunluk ~1'den ~0,92 g/cm³'e düşer; buz yüzer."},
{"q":"Bir buz dağının (aysberg) yalnızca küçük bir kısmının su üstünde görünmesini açıklayın.","fig":"<svg viewBox='0 0 320 180'><line x1='20' y1='95' x2='300' y2='95' stroke='#2b6be0'/><rect x='20' y='95' width='280' height='75' fill='#cfe3f5'/><polygon points='130,55 175,95 100,95' fill='#eaf4fc' stroke='#1a2b45'/><polygon points='100,95 175,95 195,150 90,150' fill='#dcebf7' stroke='#1a2b45'/><text x='160' y='168' font-size='10' text-anchor='middle' fill='#1a2b45'>büyük kısım su altında</text></svg>","steps":[{"t":"Yoğunluk oranı","a":"0,92/1,00","d":"Buzun yoğunluğu suyun yaklaşık %92'sidir."},{"t":"Yüzme dengesi","a":"batan = ~%92","d":"Cismin ağırlığını taşıyacak kadarı suya batar, bu da hacmin yaklaşık %92'sidir."},{"t":"Görünen","a":"~%8","d":"Geriye yalnızca yaklaşık %8'lik bir tepe kısmı su üstünde kalır."}],"ans":"Buz suyun ~%92'si kadar yoğun olduğundan hacminin ~%92'si batar, yalnızca ~%8'i görünür."},
{"q":"Suyun yoğunluk anomalisi olmasaydı kutup denizleri ve yaşam nasıl etkilenirdi?","steps":[{"t":"Buz batardı","a":"dipten donma","d":"Buz sudan yoğun olsaydı oluştuğu anda dibe çökerdi."},{"t":"Tüm su donardı","a":"kalıcı buz","d":"Üstte yalıtım tabakası olmayınca deniz tabandan yukarı tamamen donabilirdi."},{"t":"Yaşam zorlanır","a":"sıvı su yok","d":"Sıvı su kalmayınca su canlıları yaşam ortamı bulamazdı."}],"ans":"Anomali olmasa buz dibe çöker, sular tümüyle donar ve su yaşamı büyük zarar görürdü."}
]},"lise":{"kolay":[
{"q":"Suyun yoğunluk anomalisinde anahtar moleküller arası kuvvet nedir?","steps":[{"t":"Polar molekül","a":"O kısmen eksi","d":"Su polar bir moleküldür; O ucu kısmen (−), H uçları kısmen (+) yüklüdür."},{"t":"Hidrojen bağı","a":"O···H","d":"Bir molekülün O'su, komşunun H'siyle hidrojen bağı kurar; anomalinin nedeni budur."}],"ans":"Anomalinin nedeni su molekülleri arasındaki hidrojen bağlarıdır."},
{"q":"Buz örgüsünde her su molekülü kaç hidrojen bağıyla çevrelenir?","steps":[{"t":"Tetrahedral","a":"4 komşu","d":"Buzda her su molekülü dört komşu molekülle hidrojen bağı kurar."},{"t":"Açık yapı","a":"boşluklu örgü","d":"Bu dörtyüzlü düzen boşluklu, açık bir kristal örgü oluşturur."}],"ans":"Buzda her su molekülü 4 hidrojen bağıyla dörtyüzlü, açık bir örgü kurar."},
{"q":"Buzun yoğunluğunun sudan düşük olması niceliksel olarak ne kadardır?","steps":[{"t":"Su","a":"1,00 g/cm³","d":"Sıvı suyun yoğunluğu 4 °C'de yaklaşık 1,00 g/cm³'tür."},{"t":"Buz","a":"0,917 g/cm³","d":"0 °C buzunun yoğunluğu yaklaşık 0,917 g/cm³'tür."}],"ans":"Buzun yoğunluğu (~0,917 g/cm³) suyunkinden (~1,00 g/cm³) düşüktür."},
{"q":"Sıvı suda hidrojen bağları buzdakine göre nasıl bir düzendedir?","steps":[{"t":"Sıvı su","a":"düzensiz","d":"Sıvı suda hidrojen bağları sürekli kurulup kopar, düzensizdir."},{"t":"Daha sıkı","a":"boşluk az","d":"Düzensiz yerleşim molekülleri daha sıkı paketler, hacim küçük olur."}],"ans":"Sıvı suda hidrojen bağları düzensizdir ve moleküller daha sıkı paketlendiğinden hacim küçüktür."},
{"q":"Suyun en yüksek yoğunluğa ulaştığı +4 °C neyi temsil eder?","steps":[{"t":"İki etki","a":"yarışır","d":"Soğuma molekülleri yaklaştırır; ancak açık örgü eğilimi onları uzaklaştırır."},{"t":"Denge","a":"+4 °C","d":"Bu iki etkinin dengelendiği noktada hacim en küçük, yoğunluk en yüksektir."}],"ans":"+4 °C, büzülme ile açık örgü oluşumunun dengelendiği en yoğun noktadır."},
{"q":"Göllerde +4 °C'lik su neden dibe çöker?","steps":[{"t":"En yoğun","a":"+4 °C suyu","d":"Su +4 °C'de en yüksek yoğunluğa sahiptir."},{"t":"Çökme","a":"dibe iner","d":"En yoğun su olduğu için göl tabanına yerleşir; daha soğuk su üstte kalır."}],"ans":"+4 °C'deki su en yoğun olduğundan göl dibine çöker, daha soğuk su üstte kalır."},
{"q":"Buzun erime sırasında hacmi nasıl değişir?","steps":[{"t":"Örgü çöker","a":"bağlar kısmen kopar","d":"Buz erirken açık hidrojen bağı örgüsünün bir kısmı bozulur."},{"t":"Hacim azalır","a":"su sıkışır","d":"Moleküller boşlukları doldurarak daha sıkı yerleşir, hacim küçülür."}],"ans":"Buz erirken açık örgü çöker, moleküller sıkışır ve hacim azalır."},
{"q":"Yoğunluk anomalisi 'kolligatif' bir özellik midir, yoksa yapısal mı?","steps":[{"t":"Yapısal neden","a":"hidrojen bağı","d":"Anomali, su molekülünün geometrisi ve hidrojen bağı örgüsünden kaynaklanır."},{"t":"Sonuç","a":"yapısal","d":"Tanecik sayısına değil, yapıya bağlı olduğu için yapısal bir özelliktir."}],"ans":"Yoğunluk anomalisi, hidrojen bağı örgüsünden gelen yapısal bir özelliktir."},
{"q":"Buzun su üstünde yüzmesini Arşimet ilkesiyle nasıl ifade ederiz?","steps":[{"t":"Kaldırma kuvveti","a":"taşan suyun ağırlığı","d":"Buza etkiyen kaldırma kuvveti, taşırdığı suyun ağırlığına eşittir."},{"t":"Denge","a":"buz < su yoğunluğu","d":"Buzun yoğunluğu düşük olduğundan, ağırlığını taşıyacak kaldırma kuvvetine hacmin bir kısmı batınca ulaşılır ve buz yüzer."}],"ans":"Buz daha az yoğun olduğu için hacminin bir kısmı battığında kaldırma kuvveti ağırlığını dengeler ve yüzer."},
{"q":"Suyun anomalisi, gezegende sıcaklık dengelemesine nasıl katkı yapar?","steps":[{"t":"Buz yalıtımı","a":"üstte tabaka","d":"Yüzeyde oluşan buz, alttaki suyu soğuktan yalıtır."},{"t":"Sıvı su korunur","a":"ısı deposu","d":"Korunan büyük su kütlesi ısıyı depolayıp salarak iklimi dengeler."}],"ans":"Yüzen buz suyu yalıtır, korunan büyük su kütlesi ısı deposu olarak iklimi dengeler."}
],"zor":[
{"q":"Buzdaki tetrahedral hidrojen bağı örgüsü, sıvı sudan daha düşük yoğunluğu moleküler düzeyde nasıl doğurur?","steps":[{"t":"Geometri","a":"104,5° açı","d":"Su molekülü açısaldır; O üzerinde iki ortaklanmamış çift, iki O–H bağı vardır."},{"t":"Buz örgüsü","a":"4 yönlü bağ","d":"Her molekül 4 komşuyla dörtyüzlü hidrojen bağı kurarak büyük boşluklu bir kristal oluşturur."},{"t":"Sonuç","a":"hacim ↑, d ↓","d":"Boşluklu örgü birim hücrede daha az molekül barındırır; yoğunluk düşer."}],"ans":"Açısal molekülün 4 yönlü tetrahedral hidrojen bağı örgüsü boşluklu olduğundan buzun yoğunluğu düşer."},
{"q":"Bir göl yüzeyi −10 °C havada donarken su sütununda sıcaklık ve yoğunluk dağılımı nasıl oluşur?","steps":[{"t":"Üst tabaka","a":"0 °C buz","d":"Yüzeyde 0 °C'de buz oluşur ve hafif olduğundan üstte kalır."},{"t":"Orta tabaka","a":"0–4 °C","d":"Buzun hemen altında 0 ile 4 °C arası soğuk su bulunur."},{"t":"Dip","a":"+4 °C en yoğun","d":"En yoğun +4 °C suyu dibe çökerek tabanda toplanır; canlılar burada yaşar."}],"ans":"Üstte buz, altında 0–4 °C su, dipte +4 °C en yoğun su; bu katmanlaşma dipteki yaşamı korur."},
{"q":"100 g su 0 °C'de tamamen donduğunda hacim değişimini hesaplayın (ρ_su=1,00 g/cm³, ρ_buz=0,92 g/cm³).","steps":[{"t":"Su hacmi","a":"V = m/ρ = 100 cm³","d":"100 g ÷ 1,00 g/cm³ = 100 cm³ sıvı su hacmi bulunur."},{"t":"Buz hacmi","a":"100/0,92 ≈ 108,7 cm³","d":"Kütle korunur; 100 g ÷ 0,92 g/cm³ ≈ 108,7 cm³ buz hacmi olur."},{"t":"Değişim","a":"ΔV ≈ +8,7 cm³","d":"Hacim 100'den 108,7 cm³'e çıkar, yaklaşık %8,7 artar."}],"ans":"Hacim ~100 cm³'ten ~108,7 cm³'e çıkar; yaklaşık %8,7 artış olur."},
{"q":"Yoğunluğu 0,917 g/cm³ olan buzun, yoğunluğu 1,00 g/cm³ olan tatlı suda hacminin yüzde kaçı su üstünde kalır?","steps":[{"t":"Yüzme dengesi","a":"batan kısım = ρ_buz/ρ_su","d":"Yüzen cisimde batan hacim oranı, cismin yoğunluğunun sıvı yoğunluğuna oranına eşittir."},{"t":"Batan oran","a":"0,917/1,00 = %91,7","d":"Hacmin yaklaşık %91,7'si suya batar."},{"t":"Üstte kalan","a":"%8,3","d":"100 − 91,7 = yaklaşık %8,3'lük kısım su üstünde görünür."}],"ans":"Hacmin yaklaşık %91,7'si batar, yaklaşık %8,3'ü su üstünde kalır."},
{"q":"Aynı buz tatlı su yerine yoğunluğu 1,025 g/cm³ olan deniz suyunda yüzdürülürse görünen kısım nasıl değişir?","steps":[{"t":"Deniz suyu yoğun","a":"1,025 g/cm³","d":"Tuz nedeniyle deniz suyu tatlı sudan daha yoğundur."},{"t":"Batan oran","a":"0,917/1,025 ≈ %89,5","d":"Batan hacim oranı 0,917 ÷ 1,025 ≈ %89,5'e düşer."},{"t":"Üstte kalan","a":"≈ %10,5","d":"Daha yoğun sıvıda buz biraz daha yüzer; görünen kısım ~%8,3'ten ~%10,5'e çıkar."}],"ans":"Deniz suyu daha yoğun olduğundan buz biraz daha yüzer; görünen kısım ~%10,5'e çıkar."},
{"q":"Suyun yoğunluk anomalisi göl ekosisteminde 'sonbahar/ilkbahar dönüşümü' (turnover) olayını nasıl yönetir?","steps":[{"t":"Yaz katmanı","a":"sıcak üstte","d":"Yazın ılık, az yoğun su üstte; soğuk su dipte katmanlaşır."},{"t":"Soğuma","a":"+4 °C çöker","d":"Sonbaharda yüzey suyu +4 °C'ye soğuyunca en yoğun olur ve dibe çöker."},{"t":"Karışım","a":"besin/oksijen dağılır","d":"Bu çökme su sütununu karıştırır; oksijen dibe, besin yüzeye taşınır."}],"ans":"+4 °C suyunun en yoğun olması mevsimsel çökme-karışmayı (turnover) tetikleyerek oksijen ve besini dağıtır."},
{"q":"Buz erirken hacmin azalması, çoğu maddenin tersi davranışıdır; bunun termodinamik/yapısal nedeni nedir?","steps":[{"t":"Genel kural","a":"katı yoğun","d":"Çoğu maddede katı hâl sıvıdan daha sıkı paketlenir, bu yüzden daha yoğundur."},{"t":"Suda istisna","a":"açık örgü","d":"Buz hidrojen bağı örgüsü nedeniyle boşluklu olduğundan sıvıdan az yoğundur."},{"t":"Erime","a":"hacim azalır","d":"Eriyince örgü kısmen çöker, moleküller sıkışır ve hacim küçülür."}],"ans":"Buzun açık hidrojen bağı örgüsü sıvıdan boşluklu olduğundan, erirken örgü çöker ve hacim azalır."},
{"q":"Clausius–Clapeyron/erime eğrisi bağlamında suyun katı-sıvı denge eğrisinin negatif eğimli olması neyi gösterir?","steps":[{"t":"Hacim ilişkisi","a":"V_buz > V_su","d":"Erimede sıvı, katıdan küçük hacim kaplar (ΔV erime < 0)."},{"t":"Eğim","a":"negatif","d":"P–T grafiğinde erime eğrisinin eğimi ΔV ile aynı işaretli olduğundan negatif olur."},{"t":"Sonuç","a":"basınç eritir","d":"Basınç artışı buzun erime sıcaklığını düşürür; basınç buzu eritebilir."}],"ans":"Negatif eğim, buzun sıvıdan daha hacimli olduğunu ve artan basıncın erime sıcaklığını düşürdüğünü gösterir."},
{"q":"Bir su deposu kışın kısmen donduğunda, donmuş ve sıvı kısımların yoğunluk farkı depo içi tabakalaşmayı nasıl belirler?","steps":[{"t":"Buz üstte","a":"ρ düşük","d":"Yoğunluğu düşük buz daima yüzeyde toplanır."},{"t":"+4 °C dipte","a":"ρ yüksek","d":"En yoğun +4 °C suyu tabanda yer alır."},{"t":"Ara katman","a":"0–4 °C","d":"Arada sıcaklığı 0 ile 4 °C arasında değişen, yoğunluğu kademeli su bulunur."}],"ans":"Düşük yoğunluklu buz üstte, en yoğun +4 °C su dipte, arada kademeli soğuk su olacak şekilde tabakalaşır."},
{"q":"Suyun yoğunluk anomalisi olmasaydı Dünya'da hayatın ortaya çıkışı neden büyük ölçüde engellenirdi?","steps":[{"t":"Buz dibe çökerdi","a":"yalıtım yok","d":"Buz sudan yoğun olsaydı oluştuğu anda dibe iner, yüzeyde yalıtıcı örtü olmazdı."},{"t":"Kütlesel donma","a":"sular tümüyle donar","d":"Yalıtım olmadan denizler ve göller tabandan yüzeye kademeli donardı."},{"t":"Yaşam ortamı yok","a":"sıvı su kalmaz","d":"Kalıcı sıvı su olmayınca ilk hücresel yaşamın gelişeceği kararlı su ortamı oluşamazdı."}],"ans":"Anomali olmasa buz dibe çöküp sular tümüyle donar, kararlı sıvı su kalmaz ve yaşamın gelişimi engellenirdi."}
]}}};
