globalThis.__OUT = {"iyonikGiris":{"ilkokul":{"kolay":[
{"q":"İyonik bağ hangi atomlar arasında kurulur?","steps":[{"t":"Bir metal","a":"sodyum gibi","d":"İyonik bağda bir tarafta metal (örneğin sodyum) bulunur."},{"t":"Bir ametal","a":"klor gibi","d":"Diğer tarafta ametal (örneğin klor) bulunur; bunlar birleşir."}],"ans":"İyonik bağ bir metal ile bir ametal atom arasında kurulur."},
{"q":"Metal atom bağ kurarken elektronlarına ne yapar?","steps":[{"t":"Dış elektron","a":"fazla gibi","d":"Metalin dış elektronları kolayca ayrılabilir."},{"t":"Verir","a":"elektron verir","d":"Metal bu dış elektronları başka atoma verir."}],"ans":"Metal atom, dış elektronlarını başka atoma verir."},
{"q":"Ametal atom bağ kurarken ne yapar?","steps":[{"t":"Eksik elektron","a":"yer var","d":"Ametalin dış katmanında elektron için boş yer vardır."},{"t":"Alır","a":"elektron alır","d":"Ametal, metalin verdiği elektronu alarak dış katmanını tamamlar."}],"ans":"Ametal atom, başka atomdan elektron alır."},
{"q":"Yemek tuzu hangi iki atomdan oluşur?","fig":"<svg viewBox='0 0 320 150'><circle cx='110' cy='75' r='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='110' y='80' font-size='12' text-anchor='middle' fill='#1a2b45'>Na</text><circle cx='210' cy='75' r='26' fill='#9ed9a8' stroke='#1a2b45'/><text x='210' y='80' font-size='12' text-anchor='middle' fill='#1a2b45'>Cl</text><text x='160' y='130' font-size='11' text-anchor='middle' fill='#1a2b45'>tuz (NaCl)</text></svg>","steps":[{"t":"Birinci atom","a":"sodyum","d":"Yemek tuzunda sodyum (Na) atomu bulunur."},{"t":"İkinci atom","a":"klor","d":"Sodyum, klor (Cl) ile birleşerek tuzu (NaCl) oluşturur."}],"ans":"Yemek tuzu sodyum (Na) ve klor (Cl) atomlarından oluşur."},
{"q":"Artı ve eksi yüklü iki tanecik karşılaşınca ne olur?","steps":[{"t":"Zıt yükler","a":"+ ve −","d":"Bir tanecik artı, diğeri eksi yüklüdür."},{"t":"Çekim","a":"birbirini çeker","d":"Zıt yükler birbirini çeker, böylece birbirine tutunurlar."}],"ans":"Artı ve eksi yüklü tanecikler birbirini çeker ve birbirine tutunur."}
],"zor":[
{"q":"Sodyum elektronunu verince ne tür yük kazanır?","steps":[{"t":"Elektron verir","a":"eksi gider","d":"Sodyum bir elektron (eksi yük) verir."},{"t":"Sonuç","a":"artı yük","d":"Eksi yük gidince geriye artı yüklü sodyum (Na⁺) kalır."}],"ans":"Sodyum elektronunu verince artı yüklü (Na⁺) hale gelir."},
{"q":"Klor elektron alınca ne tür yük kazanır?","steps":[{"t":"Elektron alır","a":"eksi gelir","d":"Klor bir elektron (eksi yük) alır."},{"t":"Sonuç","a":"eksi yük","d":"Fazladan eksi yük geldiği için klor eksi yüklü (Cl⁻) hale gelir."}],"ans":"Klor elektron alınca eksi yüklü (Cl⁻) hale gelir."},
{"q":"Na⁺ ve Cl⁻ neden birbirine tutunur?","fig":"<svg viewBox='0 0 320 150'><circle cx='110' cy='75' r='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='110' y='80' font-size='12' text-anchor='middle' fill='#1a2b45'>Na⁺</text><circle cx='210' cy='75' r='26' fill='#9ed9a8' stroke='#1a2b45'/><text x='210' y='80' font-size='12' text-anchor='middle' fill='#1a2b45'>Cl⁻</text><line x1='136' y1='75' x2='184' y2='75' stroke='#2b6be0' stroke-width='2'/><text x='160' y='130' font-size='10' text-anchor='middle' fill='#1a2b45'>zıt yükler çekilir</text></svg>","steps":[{"t":"Yükler","a":"artı ve eksi","d":"Na⁺ artı, Cl⁻ eksi yüklüdür."},{"t":"Çekim","a":"zıt yük","d":"Zıt yükler birbirini çektiği için Na⁺ ve Cl⁻ sıkıca tutunur."}],"ans":"Na⁺ artı, Cl⁻ eksi yüklü olduğu için zıt yükler birbirini çeker ve tutunurlar."},
{"q":"İyon nedir, basitçe açıklayın?","steps":[{"t":"Yük kazanma","a":"al ya da ver","d":"Bir atom elektron alıp verince elektriksel yük kazanır."},{"t":"İyon","a":"yüklü atom","d":"Yük kazanmış (artı veya eksi) bu atoma iyon denir."}],"ans":"İyon, elektron alıp vererek artı ya da eksi yük kazanmış atomdur."},
{"q":"Metal mi yoksa ametal mi elektron almaya daha yatkındır?","steps":[{"t":"Metal","a":"verir","d":"Metaller dış elektronlarını kolayca verir."},{"t":"Ametal","a":"alır","d":"Ametaller ise elektron almaya yatkındır."}],"ans":"Ametaller elektron almaya, metaller ise vermeye yatkındır."}
]},"ortaokul":{"kolay":[
{"q":"İyonik bağ nasıl oluşur?","steps":[{"t":"Elektron aktarımı","a":"metal → ametal","d":"Metal, değerlik elektronlarını ametale aktarır."},{"t":"Zıt iyon çekimi","a":"+ ve − çekilir","d":"Oluşan artı ve eksi iyonlar elektriksel çekimle birbirine bağlanır."}],"ans":"İyonik bağ, metalden ametale elektron aktarımı ve oluşan zıt iyonların çekimiyle oluşur."},
{"q":"Katyon ve anyon ne demektir?","steps":[{"t":"Katyon","a":"artı iyon","d":"Elektron veren atom artı yüklenir; bu artı iyona katyon denir."},{"t":"Anyon","a":"eksi iyon","d":"Elektron alan atom eksi yüklenir; bu eksi iyona anyon denir."}],"ans":"Katyon elektron vererek artı yüklenmiş, anyon ise elektron alarak eksi yüklenmiş iyondur."},
{"q":"NaCl oluşumunda sodyum ve klor hangi iyonlara dönüşür?","fig":"<svg viewBox='0 0 320 160'><circle cx='95' cy='80' r='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='95' y='85' font-size='12' text-anchor='middle' fill='#1a2b45'>Na</text><circle cx='225' cy='80' r='26' fill='#9ed9a8' stroke='#1a2b45'/><text x='225' y='85' font-size='12' text-anchor='middle' fill='#1a2b45'>Cl</text><line x1='123' y1='80' x2='193' y2='80' stroke='#2b6be0' stroke-width='2'/><polygon points='193,80 183,75 183,85' fill='#2b6be0'/><text x='159' y='66' font-size='10' text-anchor='middle' fill='#1a2b45'>e⁻</text><text x='159' y='145' font-size='10' text-anchor='middle' fill='#1a2b45'>Na⁺ + Cl⁻</text></svg>","steps":[{"t":"Sodyum","a":"Na⁺","d":"Sodyum 1 değerlik elektronunu vererek Na⁺ katyonuna dönüşür."},{"t":"Klor","a":"Cl⁻","d":"Klor bu elektronu alarak Cl⁻ anyonuna dönüşür."}],"ans":"NaCl oluşumunda sodyum Na⁺ katyonuna, klor ise Cl⁻ anyonuna dönüşür."},
{"q":"Metaller neden kolayca katyon oluşturur?","steps":[{"t":"Az değerlik e⁻","a":"1-2-3 elektron","d":"Metallerin son katmanında az sayıda (genelde 1-3) elektron vardır."},{"t":"Vermek kolay","a":"katyon","d":"Bu az elektronu vermek, oktete ulaşmanın en kolay yoludur; veren atom katyon olur."}],"ans":"Metallerin son katmanında az elektron olduğundan bunları verip katyon oluşturmak kolaydır."},
{"q":"İyonik bağda atomların amacı nedir?","steps":[{"t":"Oktet","a":"son katman 8","d":"Her iki atom da son katmanını 8'e (oktete) tamamlamak ister."},{"t":"Aktarımla ulaşma","a":"al-ver","d":"Metal verip, ametal alarak her ikisi de soy gaz düzenine ulaşır ve kararlı olur."}],"ans":"İyonik bağda atomlar, elektron aktarımıyla son katmanlarını oktete tamamlayıp kararlı hale gelmeyi amaçlar."}
],"zor":[
{"q":"Magnezyum ve oksijen MgO bileşiğini nasıl oluşturur?","fig":"<svg viewBox='0 0 320 160'><circle cx='95' cy='80' r='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='95' y='85' font-size='11' text-anchor='middle' fill='#1a2b45'>Mg</text><circle cx='225' cy='80' r='26' fill='#e0552b' stroke='#1a2b45'/><text x='225' y='85' font-size='11' text-anchor='middle' fill='#fff'>O</text><line x1='123' y1='73' x2='193' y2='73' stroke='#2b6be0' stroke-width='2'/><line x1='123' y1='87' x2='193' y2='87' stroke='#2b6be0' stroke-width='2'/><text x='159' y='145' font-size='10' text-anchor='middle' fill='#1a2b45'>Mg²⁺ + O²⁻</text></svg>","steps":[{"t":"Elektron aktarımı","a":"2 elektron","d":"Magnezyum 2 değerlik elektronunu, 2 elektrona ihtiyacı olan oksijene aktarır."},{"t":"İyonlar","a":"Mg²⁺ ve O²⁻","d":"Mg²⁺ ve O²⁻ iyonları oluşur; zıt yükler çekilerek MgO bileşiğini kurar."}],"ans":"Magnezyum 2 elektronunu oksijene verir; oluşan Mg²⁺ ve O²⁻ iyonları çekimle MgO'yu oluşturur."},
{"q":"İyonik bileşiklerin erime noktaları neden yüksektir?","steps":[{"t":"İyon örgüsü","a":"düzenli ağ","d":"İyonik katıda artı ve eksi iyonlar üç boyutlu düzenli bir örgüde güçlü çekimle dizilir."},{"t":"Çok enerji","a":"erimesi zor","d":"Bu güçlü iyonik çekimleri kırıp eritmek için çok yüksek sıcaklık (enerji) gerekir."}],"ans":"İyonik bileşiklerde zıt iyonlar arası çekim çok güçlü ve örgü düzenli olduğundan erime noktaları yüksektir."},
{"q":"Neden Na 1 elektron verirken O 2 elektron alır, ama yine de Na₂O dengeli oluşur?","steps":[{"t":"Yük gereksinimi","a":"Na⁺ ve O²⁻","d":"Sodyum 1 elektron verip Na⁺ olur; oksijen 2 elektron alıp O²⁻ olur."},{"t":"Yük dengesi","a":"2 Na : 1 O","d":"Toplam yük sıfır olmalı; iki Na⁺ (toplam +2) bir O²⁻ (−2) ile dengelenir, bileşik Na₂O olur."}],"ans":"Oksijen 2 elektron istediği için iki sodyum birer elektron verir; yük dengesi 2 Na⁺ + 1 O²⁻ olur ve bileşik Na₂O biçiminde oluşur."},
{"q":"İyonik bileşikler katı halde elektriği iletmezken eriyik veya çözeltide neden iletir?","steps":[{"t":"Katı hal","a":"iyonlar sabit","d":"Katıda iyonlar örgüde sıkıca sabittir, hareket edemediğinden yük taşıyamaz."},{"t":"Eriyik/çözelti","a":"serbest iyon","d":"Eridiğinde ya da suda çözündüğünde iyonlar serbest hareket eder ve elektrik yükünü taşıyabilir."}],"ans":"Katıda iyonlar sabit olduğundan iletmez; eriyik/çözeltide serbest kalan iyonlar yük taşıyabildiği için elektriği iletir."},
{"q":"Bir atomun katyon mu anyon mu olacağını nasıl tahmin ederiz?","steps":[{"t":"Tür","a":"metal/ametal","d":"Atomun metal mi ametal mi olduğuna bakarız; metaller verir, ametaller alır."},{"t":"Değerlik sayısı","a":"oktete uzaklık","d":"Son katmanı yarıdan az dolu (1-3 e⁻) ise verir → katyon; yarıdan fazla (5-7 e⁻) ise alır → anyon."}],"ans":"Metal ve az değerlik elektronlu atomlar verip katyon, ametal ve çok değerlik elektronlu atomlar alıp anyon olur."}
]},"lise":{"kolay":[
{"q":"İyonik bağın oluşum mekanizmasını açıklayınız.","steps":[{"t":"Elektron aktarımı","a":"metal → ametal","d":"Düşük iyonlaşma enerjili metal, değerlik elektron(lar)ını yüksek elektronegatiflikli ametale aktarır."},{"t":"Elektrostatik çekim","a":"zıt iyonlar","d":"Oluşan katyon ve anyon arasındaki güçlü elektrostatik (Coulomb) çekimi iyonik bağı meydana getirir."}],"ans":"İyonik bağ, metalden ametale elektron aktarımıyla oluşan zıt iyonlar arasındaki elektrostatik çekimle meydana gelir."},
{"q":"Katyon ve anyon kavramlarını oluşum yönüyle tanımlayınız.","steps":[{"t":"Katyon","a":"e verir, + yük","d":"Bir veya daha çok elektron veren atom proton fazlalığıyla artı yüklenir; bu pozitif iyona katyon denir (Na⁺, Mg²⁺)."},{"t":"Anyon","a":"e alır, − yük","d":"Elektron alan atom elektron fazlalığıyla eksi yüklenir; bu negatif iyona anyon denir (Cl⁻, O²⁻)."}],"ans":"Katyon elektron vererek artı yüklenmiş, anyon ise elektron alarak eksi yüklenmiş iyondur."},
{"q":"NaCl oluşumunu değerlik elektronu ve oktet açısından açıklayınız.","fig":"<svg viewBox='0 0 320 175'><circle cx='95' cy='85' r='28' fill='#cfd8e8' stroke='#1a2b45'/><text x='95' y='90' font-size='12' text-anchor='middle' fill='#1a2b45'>Na</text><circle cx='225' cy='85' r='28' fill='#9ed9a8' stroke='#1a2b45'/><text x='225' y='90' font-size='12' text-anchor='middle' fill='#1a2b45'>Cl</text><line x1='124' y1='85' x2='194' y2='85' stroke='#2b6be0' stroke-width='2'/><polygon points='194,85 184,80 184,90' fill='#2b6be0'/><text x='159' y='72' font-size='10' text-anchor='middle' fill='#1a2b45'>e⁻ aktarımı</text><text x='159' y='160' font-size='11' text-anchor='middle' fill='#1a2b45'>Na⁺ + Cl⁻ → NaCl</text></svg>","steps":[{"t":"Sodyum","a":"1 e⁻ verir","d":"Sodyumun 1 değerlik elektronu vardır; bunu verince bir alttaki dolu katman açığa çıkar, Na⁺ neon düzenine ulaşır."},{"t":"Klor","a":"1 e⁻ alır","d":"Klorun 7 değerlik elektronu vardır; 1 elektron alarak oktete ulaşır, Cl⁻ argon düzenine erişir."}],"ans":"Sodyum 1 değerlik elektronunu verip Na⁺, klor o elektronu alıp Cl⁻ olur; her ikisi de soy gaz oktetine ulaşır ve NaCl oluşur."},
{"q":"İyonik bileşiklerin yüksek erime/kaynama noktasını yapısal olarak açıklayınız.","steps":[{"t":"Kristal örgü","a":"iyonik kafes","d":"İyonik bileşikler tek molekül değil, çok sayıda iyondan oluşan üç boyutlu kristal örgü kurar."},{"t":"Kuvvetli çekim","a":"yüksek enerji","d":"Örgüdeki yoğun ve kuvvetli iyon-iyon çekimlerini koparmak yüksek enerji gerektirdiğinden erime/kaynama noktaları yüksektir."}],"ans":"İyonik bileşikler güçlü çekimli üç boyutlu kristal örgü oluşturduğundan, bu çekimleri kırmak yüksek enerji ister; erime/kaynama noktaları yüksektir."},
{"q":"Bir iyonik bileşiğin formülünü yük dengesi ile nasıl belirleriz?","steps":[{"t":"İyon yükleri","a":"katyon ve anyon","d":"Önce katyonun ve anyonun yüklerini belirleriz (örneğin Al³⁺ ve O²⁻)."},{"t":"Yük denkleştirme","a":"çapraz katsayı","d":"Toplam yük sıfır olacak şekilde katsayılar bulunur; Al³⁺ ve O²⁻ için 2 Al ve 3 O alınır, formül Al₂O₃ olur."}],"ans":"İyonların yükleri bulunup toplam yük sıfır olacak şekilde denkleştirilir; örneğin Al³⁺ ve O²⁻ için formül Al₂O₃'tür."}
],"zor":[
{"q":"İyonik bağ oluşumunu enerji basamakları (örgü enerjisi dahil) ile açıklayınız.","steps":[{"t":"İyon oluşturma","a":"enerji gerektirir","d":"Metalin iyonlaşması (Na → Na⁺ + e⁻) enerji ister; ametalin elektron alması (Cl + e⁻ → Cl⁻) bir miktar enerji açığa çıkarır ama tek başına yeterli değildir."},{"t":"Örgü enerjisi","a":"net kararlılık","d":"İyonların kristal örgü kurarken açığa çıkardığı büyük örgü enerjisi, harcanan enerjiyi fazlasıyla karşılar; net sonuç enerji düşüşü ve kararlı bileşiktir."}],"ans":"İyon oluşumu net enerji gerektirse de, kristal örgü kurulurken açığa çıkan büyük örgü enerjisi süreci ekzotermik kılar; bileşik bu yüzden kararlıdır."},
{"q":"Örgü enerjisi neye bağlıdır ve NaCl ile MgO karşılaştırması nasıldır?","steps":[{"t":"Bağımlılık","a":"yük ve yarıçap","d":"Örgü enerjisi iyon yüklerinin çarpımıyla doğru, iyonlar arası uzaklıkla (yarıçap toplamı) ters orantılıdır."},{"t":"Karşılaştırma","a":"MgO ≫ NaCl","d":"MgO'da iyon yükleri (2+ ve 2−) NaCl'dekinden (1+ ve 1−) büyük olduğundan MgO'nun örgü enerjisi ve erime noktası çok daha yüksektir."}],"ans":"Örgü enerjisi iyon yüklerinin çarpımıyla artar, uzaklıkla azalır; MgO (2+/2−) yükleri büyük olduğundan NaCl'den (1+/1−) çok daha yüksek örgü enerjisine ve erime noktasına sahiptir."},
{"q":"İyonik bağ tamamen 'saf iyonik' midir; polarizasyon (Fajans) etkisini açıklayınız.","steps":[{"t":"İdeal iyonik","a":"tam aktarım","d":"İdeal iyonik bağda elektron tam aktarılır ve iyonlar küresel kabul edilir."},{"t":"Polarizasyon","a":"kısmi kovalent","d":"Küçük ve yüksek yüklü katyon, büyük anyonun elektron bulutunu çarpıtır (polarize eder); bu kovalent karakter katar, yani bağ kısmen kovalentleşir."}],"ans":"Gerçekte saf iyonik bağ idealleştirmedir; küçük/yüksek yüklü katyonun anyonu polarize etmesi (Fajans kuralları) bağa kısmi kovalent karakter kazandırır."},
{"q":"İyonik bileşikler neden serttir ama darbeyle (çekiçle) kolayca kırılır?","steps":[{"t":"Sertlik","a":"güçlü örgü","d":"İyonlar arası güçlü ve yönlü çekimler örgüyü sert ve dayanıklı yapar."},{"t":"Kırılganlık","a":"yük itmesi","d":"Darbeyle katmanlar kayınca aynı yüklü iyonlar karşı karşıya gelir; oluşan itme örgüyü iter ve kristal aniden kırılır (kırılganlık)."}],"ans":"Güçlü iyonik örgü bileşiği sert yapar; ancak darbeyle katmanlar kayınca aynı yüklü iyonlar yan yana gelip birbirini ittiğinden kristal kolayca kırılır."},
{"q":"Bir bağın iyonik mi kovalent mi olacağını elektronegatiflik farkıyla nasıl değerlendiririz?","steps":[{"t":"Fark ölçütü","a":"ΔEN","d":"İki atom arasındaki elektronegatiflik farkı (ΔEN) büyüdükçe bağ daha iyoniktir; yaklaşık ΔEN > 1,7 belirgin iyonik karakter gösterir."},{"t":"Ara durumlar","a":"polar kovalent","d":"ΔEN küçükse (≈0) apolar kovalent, orta değerlerde (0 < ΔEN < 1,7) polar kovalent bağ oluşur; geçiş süreklidir."}],"ans":"Bağ türü elektronegatiflik farkıyla değerlendirilir: fark büyükse (≈1,7 üzeri) iyonik, çok küçükse apolar kovalent, ara değerlerde polar kovalent karakterdedir."}
]}}};
