globalThis.__OUT = {"temasYuzeyi":{"ilkokul":{"kolay":[
{"q":"Toz şeker mi yoksa kesme şeker mi suda daha çabuk erir?","steps":[{"t":"Toz şeker","a":"küçük tanecik","d":"Toz şeker küçük taneciklerden oluşur, suyla her yeri temas eder."},{"t":"Sonuç","a":"çabuk erir","d":"Daha çok temas olduğu için toz şeker suda daha çabuk erir."}],"ans":"Toz şeker küçük taneli olduğu ve suyla çok temas ettiği için daha çabuk erir."},
{"q":"Bir odunu kütük hâlinde mi yoksa ince çıralar hâlinde mi tutuşturmak daha kolaydır?","steps":[{"t":"İnce çıra","a":"çok yüzey","d":"İnce çıralar daha çok havayla temas eder."},{"t":"Kolay tutuşur","a":"çabuk yanar","d":"Çok temas olduğu için çıralar kütükten daha kolay ve çabuk tutuşur."}],"ans":"İnce çıralar havayla çok temas ettiği için kütükten daha kolay ve çabuk tutuşur."},
{"q":"Bütün bir elma mı yoksa dilimlenmiş elma mı daha çabuk kararır?","steps":[{"t":"Dilimli elma","a":"açık yüzey","d":"Dilimlenince elmanın iç yüzeyi havaya açılır."},{"t":"Çabuk kararır","a":"daha hızlı","d":"Havayla daha çok temas ettiği için dilimli elma daha çabuk kararır."}],"ans":"Dilimlenmiş elma iç yüzeyi havaya açıldığı için bütününden daha çabuk kararır."},
{"q":"Tuz hangi hâlde suda daha hızlı çözünür?","fig":"<svg viewBox='0 0 320 150'><rect x='30' y='40' width='40' height='40' fill='#cfd8e8' stroke='#1a2b45'/><text x='50' y='110' font-size='10' text-anchor='middle' fill='#1a2b45'>iri parca</text><circle cx='210' cy='45' r='5' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='230' cy='55' r='5' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='225' cy='70' r='5' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='245' cy='65' r='5' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='205' cy='68' r='5' fill='#cfd8e8' stroke='#1a2b45'/><text x='225' y='110' font-size='10' text-anchor='middle' fill='#1a2b45'>toz hali</text></svg>","steps":[{"t":"Toz hâli","a":"küçük tanecik","d":"İnce öğütülmüş toz tuz küçük taneciklerden oluşur."},{"t":"Sonuç","a":"hızlı çözünür","d":"Daha çok yüzey suyla temas ettiği için toz tuz daha hızlı çözünür."}],"ans":"Toz (ince) hâldeki tuz, suyla daha çok temas ettiği için daha hızlı çözünür."},
{"q":"İlaç tableti ile aynı ilacın toz hâli midede hangisi daha çabuk çözülür?","steps":[{"t":"Toz hâli","a":"çok yüzey","d":"Toz ilaç küçük taneciklere ayrılmış olduğu için çok yüzeye sahiptir."},{"t":"Çabuk çözülür","a":"hızlı etki","d":"Daha çok temas olduğu için toz ilaç tabletten daha çabuk çözülür."}],"ans":"Toz hâlindeki ilaç daha çok yüzeye sahip olduğu için tabletten daha çabuk çözülür."}
],"zor":[
{"q":"Patates kızartırken neden ince doğrananlar kalın doğrananlardan daha çabuk pişer?","steps":[{"t":"İnce dilim","a":"çok yüzey","d":"İnce dilimlerin yüzeyi hacmine göre daha geniştir, yağla çok temas eder."},{"t":"Çabuk pişer","a":"hızlı ısı","d":"Çok temas ısının her yere hızlı ulaşmasını sağlar, ince dilimler çabuk pişer."}],"ans":"İnce dilimlerin yüzeyi geniş olduğu için yağ ve ısıyla çok temas eder, daha çabuk pişer."},
{"q":"Bir avuç un, bir somun ekmekten neden çok daha kolay tutuşabilir, hatta patlayabilir?","steps":[{"t":"Un tanecikleri","a":"çok küçük yüzey","d":"Un çok ince taneciklerden oluşur, toplam yüzeyi çok büyüktür."},{"t":"Hızlı yanma","a":"ani tepkime","d":"Havadaki oksijenle bu kadar geniş yüzey ani ve şiddetli yanma (patlama) yapabilir."}],"ans":"Unun tanecikleri çok ince olup büyük yüzey sunduğundan havayla ani ve şiddetli yanabilir."},
{"q":"Aynı miktar şekerin küp hâli ile toz hâli çayda eritiliyor. Hangisini karıştırınca daha çabuk çözünür ve neden?","steps":[{"t":"Toz hâli","a":"geniş yüzey","d":"Toz şekerin toplam yüzeyi küp şekerden çok daha büyüktür."},{"t":"Karıştırma","a":"temas artar","d":"Karıştırmak suyu sürekli yeniler; geniş yüzeyle birleşince toz şeker çok daha hızlı çözünür."}],"ans":"Toz şeker geniş yüzeye sahip olduğundan, karıştırınca küp şekerden çok daha hızlı çözünür."},
{"q":"Demir bir çivi ile demir tozu havada nemle hangisi daha çabuk paslanır?","steps":[{"t":"Demir tozu","a":"çok yüzey","d":"Demir tozu küçük taneciklere ayrılmış, toplam yüzeyi çok geniştir."},{"t":"Hızlı paslanma","a":"çok temas","d":"Geniş yüzey havadaki oksijen ve nemle çok temas ettiği için toz çabuk paslanır."}],"ans":"Demir tozu çok geniş yüzeye sahip olup oksijenle çok temas ettiği için çividen daha çabuk paslanır."},
{"q":"Mangal yakarken kömürü neden önce kırıp küçük parçalara ayırırız?","steps":[{"t":"Küçük parça","a":"çok yüzey","d":"Kömürü kırınca toplam yüzeyi artar, havayla daha çok temas eder."},{"t":"Kolay yanar","a":"hızlı tutuşur","d":"Geniş yüzey oksijenle daha çok temas ettiği için kömür daha kolay ve hızlı tutuşur."}],"ans":"Kömürü kırmak yüzeyini artırır, oksijenle daha çok temas ettiği için daha kolay ve hızlı tutuşur."}
]},"ortaokul":{"kolay":[
{"q":"Temas yüzeyi arttıkça tepkime hızı nasıl değişir?","steps":[{"t":"Geniş yüzey","a":"çok çarpışma","d":"Yüzey arttıkça tepkimeye giren tanecikler birbirine daha çok temas eder."},{"t":"Hız","a":"artar","d":"Daha çok temas (çarpışma) tepkime hızını artırır."}],"ans":"Temas yüzeyi arttıkça tanecikler daha çok çarpışır, bu yüzden tepkime hızı artar."},
{"q":"Bir maddeyi toz hâline getirmek tepkime hızını neden artırır?","steps":[{"t":"Parçalama","a":"yüzey artar","d":"Bir maddeyi öğütmek toplam yüzey alanını çok artırır."},{"t":"Hız","a":"yükselir","d":"Artan yüzey daha çok temas demektir, tepkime hızlanır."}],"ans":"Toz hâline getirmek toplam yüzey alanını artırdığı için tepkime hızlanır."},
{"q":"Aynı kütlede mermer tozu mu yoksa mermer parçası mı asitle daha hızlı tepkir?","steps":[{"t":"Mermer tozu","a":"geniş yüzey","d":"Toz hâli aynı kütlede çok daha geniş yüzeye sahiptir."},{"t":"Hızlı tepkime","a":"çok temas","d":"Asitle daha çok yüzey temas ettiği için toz daha hızlı tepkir."}],"ans":"Mermer tozu aynı kütlede daha geniş yüzeye sahip olduğu için asitle daha hızlı tepkir."},
{"q":"Yüzey alanının tepkime hızına etkisi günlük hayatta nerelerde görülür?","fig":"<svg viewBox='0 0 320 150'><rect x='40' y='50' width='50' height='50' fill='#cfd8e8' stroke='#1a2b45'/><text x='65' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>butun</text><rect x='180' y='50' width='24' height='24' fill='#cfd8e8' stroke='#1a2b45'/><rect x='210' y='50' width='24' height='24' fill='#cfd8e8' stroke='#1a2b45'/><rect x='180' y='80' width='24' height='24' fill='#cfd8e8' stroke='#1a2b45'/><rect x='210' y='80' width='24' height='24' fill='#cfd8e8' stroke='#1a2b45'/><text x='207' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>parcalanmis</text></svg>","steps":[{"t":"Örnekler","a":"çıra, toz ilaç, kömür","d":"İnce çıranın tutuşması, toz ilacın çabuk çözülmesi, kırık kömürün hızlı yanması örnektir."},{"t":"Ortak nokta","a":"yüzey artışı","d":"Hepsinde madde parçalanarak yüzey artırılır ve tepkime hızlanır."}],"ans":"Çıra, toz ilaç ve kırık kömür gibi örneklerde yüzey artışı tepkime hızını artırır."},
{"q":"İki tepken katı ise yüzey alanı neden tepkime hızı için önemlidir?","steps":[{"t":"Temas sınırı","a":"sadece yüzeyde","d":"Katılarda tepkime yalnızca dış yüzeyde, temas eden noktalarda olur."},{"t":"Yüzey artışı","a":"hız artar","d":"Yüzey arttıkça temas noktası çoğalır, tepkime hızlanır."}],"ans":"Katılarda tepkime yalnızca yüzeyde olduğundan, yüzey arttıkça temas noktası çoğalır ve hız artar."}
],"zor":[
{"q":"Aynı kütledeki çinkonun toz ve levha hâli asitle tepkimede neden farklı hız gösterir?","fig":"<svg viewBox='0 0 320 150'><rect x='40' y='50' width='70' height='50' fill='#5b6b85' stroke='#1a2b45'/><text x='75' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>levha (az yuzey)</text><circle cx='190' cy='55' r='6' fill='#5b6b85' stroke='#1a2b45'/><circle cx='215' cy='70' r='6' fill='#5b6b85' stroke='#1a2b45'/><circle cx='240' cy='55' r='6' fill='#5b6b85' stroke='#1a2b45'/><circle cx='205' cy='90' r='6' fill='#5b6b85' stroke='#1a2b45'/><circle cx='235' cy='90' r='6' fill='#5b6b85' stroke='#1a2b45'/><text x='220' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>toz (cok yuzey)</text></svg>","steps":[{"t":"Yüzey farkı","a":"toz geniş","d":"Toz çinkonun toplam yüzeyi levhadan kat kat fazladır."},{"t":"Çarpışma","a":"daha sık","d":"Geniş yüzeyde asit tanecikleri çinkoya daha sık çarpar."},{"t":"Sonuç","a":"toz hızlı","d":"Bu yüzden toz çinko levhadan çok daha hızlı tepkir ve gazı çabuk çıkarır."}],"ans":"Toz çinkonun yüzeyi çok geniş olduğundan asitle daha sık çarpışır ve levhadan çok daha hızlı tepkir."},
{"q":"Bir küp 1 cm kenarlı iken, onu 8 eşit küçük küpe bölersek toplam yüzey nasıl değişir?","fig":"<svg viewBox='0 0 320 150'><rect x='40' y='40' width='60' height='60' fill='#cfd8e8' stroke='#1a2b45'/><text x='70' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>1 kup: 6 cm²</text><rect x='190' y='40' width='28' height='28' fill='#cfd8e8' stroke='#1a2b45'/><rect x='222' y='40' width='28' height='28' fill='#cfd8e8' stroke='#1a2b45'/><rect x='190' y='72' width='28' height='28' fill='#cfd8e8' stroke='#1a2b45'/><rect x='222' y='72' width='28' height='28' fill='#cfd8e8' stroke='#1a2b45'/><text x='220' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>8 kup: 12 cm²</text></svg>","steps":[{"t":"Başlangıç yüzey","a":"6 cm²","d":"1 cm'lik küpün yüzeyi 6×(1×1) = 6 cm²'dir."},{"t":"Bölünmüş küpler","a":"0,5 cm kenar","d":"8 eşit küpe bölünürse her birinin kenarı 0,5 cm, yüzeyi 6×0,25 = 1,5 cm²'dir."},{"t":"Toplam","a":"12 cm²","d":"8 küp toplamda 8×1,5 = 12 cm²; yani toplam yüzey 2 katına çıkar."}],"ans":"Küpü 8 eşit parçaya bölmek toplam yüzeyi 6 cm²'den 12 cm²'ye, yani 2 katına çıkarır; tepkime hızlanır."},
{"q":"Toz hâlindeki yanıcı maddeler (un, kömür tozu) fabrikalarda neden patlama riski taşır?","steps":[{"t":"Çok geniş yüzey","a":"havayla temas","d":"Havada asılı kalan toz tanecikleri oksijenle çok geniş bir yüzeyden temas eder."},{"t":"Ani yanma","a":"patlama","d":"Bir kıvılcımla bu geniş yüzey aynı anda yanınca enerji çok hızlı açığa çıkar, patlama olur."}],"ans":"Havada asılı tozun yüzeyi çok geniş olduğundan oksijenle ani ve şiddetli yanar; bu, toz patlaması riskine yol açar."},
{"q":"Aynı çözünen için karıştırma ve toz hâline getirme birlikte çözünmeyi nasıl hızlandırır?","steps":[{"t":"Toz hâli","a":"yüzey artar","d":"Toz hâli çözünenin yüzeyini artırır, suyla teması çoğaltır."},{"t":"Karıştırma","a":"temas yeniler","d":"Karıştırma doymaya başlayan suyu uzaklaştırıp taze su getirir."},{"t":"Birlikte","a":"çok hızlı","d":"Geniş yüzey ve sürekli yenilenen temas birleşince çözünme çok hızlanır."}],"ans":"Toz hâli yüzeyi artırır, karıştırma teması sürekli yeniler; ikisi birlikte çözünmeyi çok hızlandırır."},
{"q":"Sindirim sisteminde çiğneme neden önemlidir; temas yüzeyiyle ilişkilendirin.","steps":[{"t":"Çiğneme","a":"parçalar","d":"Çiğnemek besini küçük parçalara ayırır, yüzeyini artırır."},{"t":"Enzim teması","a":"hızlanır","d":"Geniş yüzeyde sindirim enzimleri besinle daha çok temas eder."},{"t":"Sonuç","a":"hızlı sindirim","d":"Bu yüzden iyi çiğnenmiş besin daha hızlı ve kolay sindirilir."}],"ans":"Çiğneme besinin yüzeyini artırır; enzimler daha çok temas ettiği için sindirim hızlanır."}
]},"lise":{"kolay":[
{"q":"Temas yüzeyinin tepkime hızını artırması çarpışma kuramıyla nasıl açıklanır?","fig":"<svg viewBox='0 0 320 150'><line x1='120' y1='30' x2='120' y2='120' stroke='#1a2b45'/><rect x='60' y='50' width='50' height='50' fill='#5b6b85' stroke='#1a2b45'/><circle cx='30' cy='75' r='6' fill='#2b6be0'/><line x1='36' y1='75' x2='58' y2='75' stroke='#2b6be0'/><circle cx='200' cy='45' r='5' fill='#5b6b85' stroke='#1a2b45'/><circle cx='230' cy='75' r='5' fill='#5b6b85' stroke='#1a2b45'/><circle cx='200' cy='105' r='5' fill='#5b6b85' stroke='#1a2b45'/><circle cx='160' cy='45' r='6' fill='#2b6be0'/><circle cx='270' cy='75' r='6' fill='#2b6be0'/><circle cx='160' cy='105' r='6' fill='#2b6be0'/><text x='235' y='138' font-size='9' text-anchor='middle' fill='#1a2b45'>genis yuzey: cok carpisma</text></svg>","steps":[{"t":"Çarpışma kuramı","a":"temas gerekir","d":"Tepkime için tanecikler çarpışmalı; çarpışma yüzeyde gerçekleşir."},{"t":"Yüzey artışı","a":"çarpışma sıklığı","d":"Yüzey arttıkça birim zamanda etkili çarpışma sayısı artar, hız yükselir."}],"ans":"Yüzey arttıkça etkili çarpışma sayısı arttığından, çarpışma kuramına göre tepkime hızı yükselir."},
{"q":"Temas yüzeyi faktörü hangi hâldeki tepkenler için belirleyicidir?","steps":[{"t":"Heterojen tepkime","a":"farklı faz","d":"Yüzey etkisi özellikle katı-sıvı, katı-gaz gibi farklı fazlı (heterojen) tepkimelerde belirleyicidir."},{"t":"Homojen","a":"etkisiz","d":"Tek faz (gaz-gaz, çözelti) homojen tepkimelerde temas yüzeyi anlamlı bir değişken değildir."}],"ans":"Temas yüzeyi, katı içeren heterojen tepkimelerde belirleyicidir; tek fazlı homojen tepkimelerde etkisizdir."},
{"q":"Hacme göre yüzey oranı (yüzey/hacim) parçacık küçüldükçe nasıl değişir?","steps":[{"t":"Küçülme","a":"oran artar","d":"Parçacık küçüldükçe yüzeyin hacme oranı büyür."},{"t":"Sonuç","a":"daha reaktif","d":"Yüksek yüzey/hacim oranı daha çok temas demektir, küçük parçacıklar daha reaktiftir."}],"ans":"Parçacık küçüldükçe yüzey/hacim oranı büyür; bu da daha çok temas ve daha yüksek tepkime hızı demektir."},
{"q":"Nanoparçacıkların yüksek reaktifliği temas yüzeyiyle nasıl ilişkilidir?","steps":[{"t":"Çok küçük boyut","a":"dev yüzey","d":"Nanoparçacıklar çok küçük olduğundan kütlelerine göre çok büyük yüzey sunar."},{"t":"Reaktiflik","a":"yüksek","d":"Bu dev yüzey çok temas sağladığından nanoparçacıklar olağanüstü reaktif olur."}],"ans":"Nanoparçacıkların kütlelerine göre çok büyük yüzeyi olduğundan teması çok fazladır, bu da onları çok reaktif yapar."},
{"q":"Mermer (CaCO₃) ile HCl tepkimesinde yüzey artışının gaz çıkış hızına etkisi nedir?","fig":"<svg viewBox='0 0 320 150'><rect x='40' y='70' width='60' height='50' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='55' cy='60' r='3' fill='#5b6b85'/><circle cx='75' cy='45' r='3' fill='#5b6b85'/><text x='70' y='138' font-size='9' text-anchor='middle' fill='#1a2b45'>parca: az gaz</text><rect x='200' y='70' width='60' height='50' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='210' cy='55' r='3' fill='#5b6b85'/><circle cx='230' cy='40' r='3' fill='#5b6b85'/><circle cx='245' cy='52' r='3' fill='#5b6b85'/><circle cx='250' cy='35' r='3' fill='#5b6b85'/><text x='230' y='138' font-size='9' text-anchor='middle' fill='#1a2b45'>toz: cok CO₂</text></svg>","steps":[{"t":"Tepkime","a":"CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂","d":"Mermer asitle tepkiyerek CO₂ gazı çıkarır."},{"t":"Toz hâli","a":"hızlı CO₂","d":"Mermer toz hâline getirilirse yüzey artar, CO₂ gazı çok daha hızlı çıkar."}],"ans":"CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂ tepkimesinde mermerin toz hâli yüzeyi artırarak CO₂ çıkış hızını yükseltir."}
],"zor":[
{"q":"1 cm kenarlı bir küpü 1000 eşit küçük küpe bölersek toplam yüzey kaç katına çıkar?","fig":"<svg viewBox='0 0 320 150'><rect x='40' y='40' width='60' height='60' fill='#cfd8e8' stroke='#1a2b45'/><text x='70' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>1 buyuk kup</text><rect x='190' y='40' width='14' height='14' fill='#cfd8e8' stroke='#1a2b45'/><rect x='210' y='40' width='14' height='14' fill='#cfd8e8' stroke='#1a2b45'/><rect x='230' y='40' width='14' height='14' fill='#cfd8e8' stroke='#1a2b45'/><rect x='190' y='60' width='14' height='14' fill='#cfd8e8' stroke='#1a2b45'/><rect x='210' y='60' width='14' height='14' fill='#cfd8e8' stroke='#1a2b45'/><rect x='230' y='60' width='14' height='14' fill='#cfd8e8' stroke='#1a2b45'/><text x='215' y='120' font-size='10' text-anchor='middle' fill='#1a2b45'>cok kucuk kup</text></svg>","steps":[{"t":"Başlangıç","a":"6 cm²","d":"1 cm'lik küpün yüzeyi 6 cm²'dir."},{"t":"Bölme","a":"0,1 cm kenar","d":"1000 = 10³ eşit küpe bölünürse her küpün kenarı 0,1 cm, yüzeyi 6×0,01 = 0,06 cm²'dir."},{"t":"Toplam","a":"60 cm²","d":"1000×0,06 = 60 cm²; toplam yüzey 6'dan 60'a, yani 10 katına çıkar."}],"ans":"Küpü 1000 eşit parçaya bölmek toplam yüzeyi 6 cm²'den 60 cm²'ye, yani 10 katına çıkarır."},
{"q":"Heterojen katalizde (örneğin egzoz katalizöründe) bal peteği yapı neden tercih edilir? Temas yüzeyiyle açıklayın.","steps":[{"t":"Bal peteği yapı","a":"çok kanal","d":"Bal peteği yapı çok sayıda ince kanal ve gözenek içerir."},{"t":"Geniş yüzey","a":"çok aktif merkez","d":"Bu yapı küçük hacimde çok büyük bir katalizör yüzeyi sunar."},{"t":"Sonuç","a":"hızlı dönüşüm","d":"Geniş yüzey egzoz gazlarıyla çok temas sağlar, zararlı gazlar hızlıca zararsızlara dönüşür."}],"ans":"Bal peteği yapı küçük hacimde çok büyük katalizör yüzeyi sunduğundan egzoz gazlarıyla teması artırır ve dönüşümü hızlandırır."},
{"q":"İki deneyde 5 g çinko toz, 5 g çinko levha aynı asitle tepkiyor. Üretilen H₂ gazının toplam miktarı ve hızı nasıl olur?","steps":[{"t":"Toplam H₂","a":"eşit","d":"Aynı kütlede çinko aynı mol H₂ verir; toplam gaz miktarı iki deneyde eşittir."},{"t":"Hız","a":"toz hızlı","d":"Toz hâlin yüzeyi geniş olduğundan başlangıç hızı yüksektir, gaz çabuk çıkar."},{"t":"Süre","a":"toz erken biter","d":"Toz deneyi daha erken tamamlanır; levha aynı gazı daha uzun sürede çıkarır."}],"ans":"Toplam H₂ miktarı eşittir; ancak toz çinko geniş yüzeyi sayesinde gazı daha hızlı çıkarıp tepkimeyi daha erken bitirir."},
{"q":"Yüzey alanı, sıcaklık ve derişim faktörleri arasında temas yüzeyinin kendine özgü farkı nedir?","steps":[{"t":"Sıcaklık/derişim","a":"enerji ve tanecik","d":"Sıcaklık tanecik enerjisini, derişim birim hacimdeki tanecik sayısını değiştirir."},{"t":"Yüzey alanı","a":"temas sınırı","d":"Yüzey alanı ise yalnızca fazlar arası temas sınırını büyütür, çarpışmaların olabileceği alanı artırır."},{"t":"Fark","a":"sadece heterojen","d":"Bu yüzden yüzey etkisi yalnızca katı içeren heterojen sistemlerde anlamlıdır; diğer ikisi her sistemde etkilidir."}],"ans":"Yüzey alanı, sıcaklık ve derişimden farklı olarak fazlar arası temas sınırını büyütür ve etkisi yalnızca katı içeren heterojen sistemlerde görülür."},
{"q":"Bir parçacığın yarıçapı yarıya inerse aynı kütle için toplam yüzey alanı nasıl değişir?","steps":[{"t":"Hacim ve sayı","a":"8 kat parça","d":"Yarıçap yarıya inince her parçanın hacmi 1/8'e iner; aynı kütle için parça sayısı 8 katına çıkar."},{"t":"Tek yüzey","a":"1/4 olur","d":"Tek bir parçanın yüzeyi yarıçapın karesiyle orantılı olduğundan 1/4'e iner."},{"t":"Toplam","a":"2 katı","d":"Toplam yüzey = 8 × (1/4) = 2 kat; yani parçacık yarıçapı yarıya inince toplam yüzey 2 katına çıkar."}],"ans":"Yarıçap yarıya inince parça sayısı 8 katına, tek yüzey 1/4'e iner; toplam yüzey 2 katına çıkar, böylece tepkime hızlanır."}
]}}};
