globalThis.__OUT = {"katalizor":{"ilkokul":{"kolay":[
{"q":"Bazı maddeler bir işi daha çabuk bitirmemize yardım eder. Tepkimeyi hızlandıran bu yardımcıya ne denir?","steps":[{"t":"Yardımcı madde","a":"hızlandırır","d":"Bir tepkimenin daha çabuk olmasını sağlayan yardımcı maddeler vardır."},{"t":"Adı","a":"katalizör","d":"Tepkimeyi hızlandıran bu yardımcı maddeye katalizör denir."}],"ans":"Tepkimeyi hızlandıran yardımcı maddeye katalizör denir."},
{"q":"Katalizör tepkimeyi hızlandırır ama kendisine ne olur?","steps":[{"t":"İş biter","a":"hâlâ orada","d":"Tepkime bittiğinde katalizör hâlâ vardır, yok olmaz."},{"t":"Tükenmez","a":"aynı kalır","d":"Bir köprü gibi sadece yardım eder, kendisi tükenmez."}],"ans":"Katalizör tepkime sonunda tükenmez, hemen hemen aynı kalır."},
{"q":"Bir kaydıraktan inerken yol kısa olunca aşağı daha çabuk inersin. Katalizör de tepkimeye nasıl yardım eder?","fig":"<svg viewBox='0 0 320 150'><path d='M40 30 Q90 30 120 130' fill='none' stroke='#5b6b85' stroke-width='3'/><path d='M180 70 Q210 70 250 130' fill='none' stroke='#2b6be0' stroke-width='3'/><circle cx='45' cy='30' r='8' fill='#e0552b'/><circle cx='185' cy='70' r='8' fill='#e0552b'/><text x='80' y='25' font-size='10' fill='#5b6b85'>uzun yol</text><text x='210' y='65' font-size='10' fill='#2b6be0'>kısa yol</text></svg>","steps":[{"t":"Kısa yol","a":"daha kolay","d":"Katalizör tepkimeye daha kolay, kısa bir yol açar."},{"t":"Çabuk biter","a":"hızlanır","d":"Bu kolay yol sayesinde tepkime daha çabuk olur."}],"ans":"Katalizör daha kolay bir yol açtığı için tepkime daha çabuk gerçekleşir."},
{"q":"Vücudumuzda yediğimiz besinleri parçalamaya yardım eden doğal yardımcılara ne denir?","steps":[{"t":"Vücutta yardımcı","a":"enzim","d":"Vücudumuzda besinleri parçalamaya yardım eden yardımcılara enzim denir."},{"t":"Görevi","a":"hızlandırır","d":"Enzimler de bir tür katalizördür, işleri hızlandırır."}],"ans":"Vücudumuzdaki bu doğal yardımcılara enzim denir; onlar da işleri hızlandırır."},
{"q":"Bir madde tepkimeyi yavaşlatıyorsa, bu katalizörün tersi olan maddeye ne denir?","steps":[{"t":"Yavaşlatan","a":"engel olur","d":"Bazı maddeler tepkimeyi hızlandırmak yerine yavaşlatır."},{"t":"Adı","a":"inhibitör","d":"Tepkimeyi yavaşlatan bu maddeye inhibitör denir, katalizörün tersidir."}],"ans":"Tepkimeyi yavaşlatan maddeye inhibitör denir; bu katalizörün tersidir."}
],"zor":[
{"q":"Katalizör eklediğimizde tepkime hızlanır. Peki katalizör tepkimeden sonra azalır mı?","steps":[{"t":"Yalnız yardım","a":"kullanılmaz","d":"Katalizör tepkimenin malzemesi gibi harcanmaz, sadece yardım eder."},{"t":"Sonuç","a":"azalmaz","d":"Tepkime bitince katalizörün miktarı neredeyse hiç azalmaz."}],"ans":"Hayır, katalizör tepkime boyunca harcanmadığı için sonunda miktarı azalmaz."},
{"q":"Aynı katalizörü bir tepkimede tekrar tekrar kullanabilir miyiz?","steps":[{"t":"Tükenmez","a":"aynı kalır","d":"Katalizör her seferinde tükenmediği için kaybolmaz."},{"t":"Tekrar kullanım","a":"evet","d":"Aynı katalizör tekrar tekrar kullanılabilir, çünkü her işten sonra hâlâ ortadadır."}],"ans":"Evet, katalizör tükenmediği için aynı tepkimede tekrar tekrar kullanılabilir."},
{"q":"Çamaşır tozlarının içine konan enzimler kirleri çıkarmaya nasıl yardım eder?","steps":[{"t":"Enzim katalizör","a":"hızlandırır","d":"Enzimler bir tür katalizördür ve kir lekelerinin çözülmesini hızlandırır."},{"t":"Sonuç","a":"daha temiz","d":"Böylece lekeler daha çabuk çözülür ve çamaşır daha kolay temizlenir."}],"ans":"Çamaşır tozundaki enzimler katalizör gibi davranıp leke çözülmesini hızlandırır, böylece kir daha kolay çıkar."},
{"q":"Katalizör tepkimeyi hızlandırır ama tepkimede açığa çıkan ısıyı ya da sonucu değiştirir mi?","steps":[{"t":"Sadece hız","a":"hızı artırır","d":"Katalizör yalnızca tepkimenin daha çabuk olmasını sağlar."},{"t":"Sonuç aynı","a":"değişmez","d":"Tepkimenin sonunda elde edilen ürün ve açığa çıkan ısı aynı kalır."}],"ans":"Katalizör sadece hızı artırır; tepkimenin ürününü veya açığa çıkan ısıyı değiştirmez."},
{"q":"Bir oyunda hem gidiş hem dönüş yolunu kısaltırsan ikisi de hızlanır. Katalizör tepkimenin sadece ileri yönünü mü hızlandırır?","steps":[{"t":"İki yön","a":"ileri ve geri","d":"Bazı tepkimeler hem ileri hem geri gidebilir."},{"t":"Eşit yardım","a":"ikisini de","d":"Katalizör hem ileri hem geri yönü hızlandırır, sadece birini değil."}],"ans":"Hayır, katalizör tepkimenin hem ileri hem geri yönünü birlikte hızlandırır."}
]},"ortaokul":{"kolay":[
{"q":"Katalizör bir tepkimenin hızını nasıl etkiler?","steps":[{"t":"Hız değişimi","a":"artar","d":"Katalizör eklenince tepkimenin gerçekleşme hızı artar."},{"t":"Kendisi","a":"tükenmez","d":"Katalizör bu sırada harcanmaz, tepkime sonunda geri kazanılır."}],"ans":"Katalizör tepkime hızını artırır ve kendisi tükenmeden tepkime sonunda geri kazanılır."},
{"q":"Bir tepkimenin başlaması için aşılması gereken enerji engeline ne ad verilir?","steps":[{"t":"Enerji engeli","a":"eşik enerji","d":"Tepkimenin başlaması için tanecikler en az belli bir enerjiye ulaşmalıdır."},{"t":"Adı","a":"aktivasyon enerjisi","d":"Bu en düşük enerji engeline aktivasyon enerjisi denir."}],"ans":"Tepkimenin başlaması için aşılması gereken bu enerji engeline aktivasyon enerjisi denir."},
{"q":"Katalizör aktivasyon enerjisini nasıl etkiler?","fig":"<svg viewBox='0 0 320 175'><line x1='30' y1='150' x2='300' y2='150' stroke='#1a2b45'/><line x1='30' y1='150' x2='30' y2='20' stroke='#1a2b45'/><path d='M50 130 Q120 30 190 110' fill='none' stroke='#5b6b85' stroke-width='2'/><path d='M50 130 Q120 70 190 110' fill='none' stroke='#2b6be0' stroke-width='2' stroke-dasharray='4 3'/><text x='120' y='25' font-size='10' fill='#5b6b85'>katalizörsüz</text><text x='130' y='62' font-size='10' fill='#2b6be0'>katalizörlü</text><text x='200' y='115' font-size='10' fill='#1a2b45'>ürün</text></svg>","steps":[{"t":"Engeli düşürür","a":"alternatif yol","d":"Katalizör tepkimeye daha düşük enerji gerektiren yeni (alternatif) bir yol sağlar."},{"t":"Sonuç","a":"hız artar","d":"Aktivasyon enerjisi düştüğü için daha çok tanecik engeli aşar ve hız artar."}],"ans":"Katalizör daha düşük enerjili alternatif bir yol sunarak aktivasyon enerjisini düşürür, böylece hızı artırır."},

{"q":"Canlıların vücudundaki biyolojik katalizörlere ne ad verilir?","steps":[{"t":"Biyolojik yardımcı","a":"enzim","d":"Canlı hücrelerdeki tepkimeleri hızlandıran protein yapılı katalizörler vardır."},{"t":"Adı","a":"enzim","d":"Bu biyolojik katalizörlere enzim denir; örneğin tükürükteki amilaz nişastayı parçalar."}],"ans":"Canlılardaki biyolojik katalizörlere enzim denir."},
{"q":"İnhibitör bir tepkimeye nasıl etki eder?","steps":[{"t":"Etki yönü","a":"yavaşlatır","d":"İnhibitör, katalizörün tersine tepkimenin hızını azaltır."},{"t":"Kullanım","a":"engelleyici","d":"İstenmeyen tepkimeleri yavaşlatmak için inhibitör kullanılır."}],"ans":"İnhibitör tepkimeyi yavaşlatır; bu yönüyle katalizörün tersidir."}
],"zor":[
{"q":"Katalizör tepkimenin denge konumunu (ürün miktarını) değiştirir mi?","steps":[{"t":"İleri ve geri","a":"eşit hızlanır","d":"Katalizör hem ileri hem geri tepkimeyi aynı oranda hızlandırır."},{"t":"Denge aynı","a":"daha erken ulaşılır","d":"İki yön eşit hızlandığı için denge konumu değişmez; sadece dengeye daha çabuk ulaşılır."}],"ans":"Hayır, katalizör ileri ve geri tepkimeyi eşit hızlandırdığından denge konumunu değiştirmez, yalnızca dengeye daha çabuk ulaştırır."},
{"q":"Katalizör tepkimenin verdiği ya da aldığı ısı miktarını (ΔH) değiştirir mi?","steps":[{"t":"Yol değişir","a":"enerji aynı","d":"Katalizör sadece tepkimenin izlediği yolu değiştirir, başlangıç ve bitiş enerjilerini değiştirmez."},{"t":"ΔH sabit","a":"değişmez","d":"Tepkimenin açığa çıkardığı veya aldığı net ısı (ΔH) aynı kalır."}],"ans":"Hayır, katalizör tepkimenin net ısısını (ΔH) değiştirmez; yalnızca aktivasyon enerjisini düşürür."},
{"q":"Bir katalizör tepkimeye katılır gibi görünür ama sonunda neden geri kazanılır?","steps":[{"t":"Ara basamak","a":"geçici birleşme","d":"Katalizör tepkimenin ara basamağında tepkenlerle geçici olarak birleşir."},{"t":"Yeniden serbest","a":"geri çıkar","d":"Tepkime tamamlanınca katalizör bağlandığı yerden ayrılıp serbest kalır, böylece net olarak tükenmez."}],"ans":"Katalizör ara basamakta geçici olarak birleşip sonunda yeniden serbest kaldığı için net olarak tükenmez ve geri kazanılır."},
{"q":"Homojen ve heterojen katalizör arasındaki fark nedir?","steps":[{"t":"Homojen","a":"aynı fazda","d":"Homojen katalizör, tepkenlerle aynı fazdadır (örneğin ikisi de çözeltide)."},{"t":"Heterojen","a":"farklı fazda","d":"Heterojen katalizör farklı fazdadır; örneğin katı katalizör yüzeyinde gaz tepkimesi gerçekleşir."}],"ans":"Homojen katalizör tepkenlerle aynı fazda, heterojen katalizör ise farklı fazda (örneğin katı yüzey) bulunur."},
{"q":"Enzimlerin belirli bir tepkimeye özgü çalışması neyle açıklanır?","fig":"<svg viewBox='0 0 320 165'><path d='M40 110 Q40 50 110 50 L150 50 Q150 70 130 80 Q150 90 150 110 Z' fill='#9ed9a8' stroke='#1a2b45'/><rect x='128' y='72' width='18' height='16' fill='#e0552b' stroke='#1a2b45'/><text x='80' y='95' font-size='10' fill='#1a2b45'>enzim</text><text x='175' y='84' font-size='10' fill='#1a2b45'>substrat</text></svg>","steps":[{"t":"Aktif bölge","a":"özel şekil","d":"Her enzimin substrata uyan özel bir aktif bölgesi (cebi) vardır."},{"t":"Anahtar-kilit","a":"seçici","d":"Anahtar-kilit uyumu gibi, yalnızca uygun substrat bağlanabildiğinden enzim seçicidir."}],"ans":"Enzimin aktif bölgesinin substrata anahtar-kilit gibi uyması, onu belirli bir tepkimeye özgü ve seçici kılar."}
]},"lise":{"kolay":[
{"q":"Katalizörün tepkime hızını artırma mekanizması nedir?","fig":"<svg viewBox='0 0 320 165'><line x1='30' y1='140' x2='300' y2='140' stroke='#1a2b45'/><line x1='30' y1='140' x2='30' y2='20' stroke='#1a2b45'/><path d='M45 110 Q110 25 175 95 L290 95' fill='none' stroke='#5b6b85' stroke-width='2'/><path d='M45 110 Q90 78 120 82 Q150 86 175 95' fill='none' stroke='#2b6be0' stroke-width='2' stroke-dasharray='4 3'/><text x='110' y='22' font-size='9' fill='#5b6b85'>Ea büyük</text><text x='90' y='72' font-size='9' fill='#2b6be0'>Ea küçük</text><text x='250' y='90' font-size='9' fill='#1a2b45'>ürünler</text></svg>","steps":[{"t":"Alternatif yol","a":"farklı mekanizma","d":"Katalizör, tepkimenin daha düşük aktivasyon enerjili alternatif bir mekanizma izlemesini sağlar."},{"t":"Etkin çarpışma","a":"daha fazla tanecik","d":"Aktivasyon enerjisi düştüğünden, eşik enerjiyi aşıp etkin çarpışma yapan tanecik sayısı artar ve hız büyür."}],"ans":"Katalizör daha düşük aktivasyon enerjili alternatif bir yol sunar; böylece etkin çarpışma yapan tanecik oranı artar ve tepkime hızı yükselir."},
{"q":"Katalizör tepkimenin entalpi değişimini (ΔH) neden değiştirmez?","fig":"<svg viewBox='0 0 320 180'><line x1='30' y1='160' x2='300' y2='160' stroke='#1a2b45'/><line x1='30' y1='160' x2='30' y2='20' stroke='#1a2b45'/><path d='M45 120 Q110 30 175 100 L290 100' fill='none' stroke='#5b6b85' stroke-width='2'/><path d='M45 120 Q110 65 175 100' fill='none' stroke='#2b6be0' stroke-width='2' stroke-dasharray='4 3'/><line x1='45' y1='120' x2='45' y2='160' stroke='#1a2b45' stroke-dasharray='2 2'/><text x='48' y='115' font-size='9' fill='#1a2b45'>tepkenler</text><text x='250' y='95' font-size='9' fill='#1a2b45'>ürünler</text><text x='110' y='25' font-size='9' fill='#5b6b85'>Ea (katalizörsüz)</text></svg>","steps":[{"t":"Başlangıç-bitiş","a":"sabit","d":"ΔH yalnızca tepkenlerin ve ürünlerin enerji düzeyine bağlıdır; bu düzeyler katalizörden etkilenmez."},{"t":"Sadece tepe","a":"Ea düşer","d":"Katalizör yalnızca enerji engelinin (Ea) yüksekliğini düşürür, başlangıç ve bitiş enerjilerini değiştirmez."}],"ans":"ΔH tepkenler ve ürünlerin enerji farkına bağlıdır; katalizör yalnızca aktivasyon enerjisini düşürdüğünden ΔH değişmez."},
{"q":"Bir katalizör dengeye nasıl etki eder?","steps":[{"t":"İki yönü hızlandırır","a":"ileri = geri","d":"Katalizör ileri ve geri tepkimenin hız sabitlerini aynı oranda büyütür."},{"t":"Denge sabiti","a":"K değişmez","d":"İki yön eşit etkilendiğinden denge sabiti (K) ve ürün miktarı değişmez; yalnızca dengeye ulaşma süresi kısalır."}],"ans":"Katalizör ileri ve geri tepkimeyi eşit hızlandırdığından denge sabitini ve denge konumunu değiştirmez, yalnızca dengeye daha kısa sürede ulaşılmasını sağlar."},
{"q":"İnhibitör ile katalizör arasındaki temel fark nedir?","steps":[{"t":"Katalizör","a":"hızlandırır","d":"Katalizör aktivasyon enerjisini düşürerek tepkime hızını artırır."},{"t":"İnhibitör","a":"yavaşlatır","d":"İnhibitör ise tepkime hızını azaltır; örneğin enzimlerin aktif bölgesini bloke ederek (enzim inhibitörü) çalışmayı engelleyebilir."}],"ans":"Katalizör tepkimeyi hızlandırırken inhibitör yavaşlatır; ikisi de hız üzerinde etkilidir ama zıt yönde çalışır."},
{"q":"Heterojen katalizde katı katalizör yüzeyinin önemi nedir?","steps":[{"t":"Yüzeyde tutunma","a":"adsorpsiyon","d":"Gaz tepkenler katı katalizör yüzeyine tutunur (adsorpsiyon), böylece tanecikler uygun konuma gelir."},{"t":"Bağ zayıflar","a":"hız artar","d":"Yüzeyde tepkenlerin bağları zayıflar, aktivasyon enerjisi düşer ve tepkime yüzeyde hızla gerçekleşir."}],"ans":"Heterojen katalizde tepkenler katı yüzeye tutunarak bağları zayıflar ve aktivasyon enerjisi düşer; bu nedenle yüzey alanı arttıkça katalitik etki güçlenir."}
],"zor":[
{"q":"Bir katalizör tepkimeye katılmasına rağmen tepkime denkleminde neden yer almaz?","steps":[{"t":"Ara basamak","a":"oluşup tüketilir","d":"Katalizör ilk basamakta tepkenlerle birleşip ara tür oluşturur, sonraki basamakta yeniden açığa çıkar."},{"t":"Net denklem","a":"sadeleşir","d":"Basamaklar toplanıp net denklem yazıldığında katalizör hem girende hem üründe yer aldığından sadeleşir; bu yüzden net denklemde görünmez."}],"ans":"Katalizör ara basamaklarda oluşup yeniden tüketildiğinden, basamaklar toplanınca sadeleşir ve net tepkime denkleminde yer almaz."},
{"q":"Katalizör Maxwell-Boltzmann enerji dağılımı açısından hızı nasıl artırır?","fig":"<svg viewBox='0 0 320 175'><line x1='30' y1='150' x2='300' y2='150' stroke='#1a2b45'/><line x1='30' y1='150' x2='30' y2='20' stroke='#1a2b45'/><path d='M30 150 Q90 30 150 70 Q220 120 295 145' fill='none' stroke='#1a2b45' stroke-width='2'/><line x1='150' y1='30' x2='150' y2='150' stroke='#5b6b85' stroke-dasharray='3 3'/><line x1='210' y1='30' x2='210' y2='150' stroke='#2b6be0' stroke-dasharray='3 3'/><text x='128' y='25' font-size='9' fill='#5b6b85'>Ea(kat.)</text><text x='200' y='25' font-size='9' fill='#2b6be0'>Ea</text></svg>","steps":[{"t":"Eşik düşer","a":"Ea azalır","d":"Katalizör aktivasyon enerjisini düşürdüğünden eşik değer dağılım eğrisinde sola kayar."},{"t":"Daha geniş alan","a":"daha çok tanecik aşar","d":"Eşik solda olduğundan eğrinin altında eşiği aşan bölge (etkin tanecik sayısı) büyür; sıcaklık değişmeden hız artar."}],"ans":"Katalizör aktivasyon enerjisini düşürerek Maxwell-Boltzmann eğrisinde eşiği sola kaydırır; böylece sıcaklık sabitken eşik enerjiyi aşan tanecik oranı artar ve hız büyür."},
{"q":"Ara ürün ile katalizör, bir tepkime mekanizmasında nasıl ayırt edilir?","steps":[{"t":"Katalizör","a":"önce girer sonra çıkar","d":"Katalizör ilk basamakta tepken olarak girer, sonraki basamakta ürün olarak geri çıkar; net denklemde yer almaz."},{"t":"Ara ürün","a":"önce oluşur sonra tükenir","d":"Ara ürün ise bir basamakta ürün olarak oluşur, sonraki basamakta tepken olarak tükenir; net denklemde görünmez ama tersi sırayla."}],"ans":"Katalizör mekanizmaya önce girip sonra geri çıkar; ara ürün ise önce oluşup sonra tükenir. İkisi de net denklemde görünmez ama katalizör başta, ara ürün sonra ortaya çıkar."},
{"q":"Enzim katalizinde sıcaklık arttıkça hız neden bir noktadan sonra düşer?","steps":[{"t":"Optimum sıcaklık","a":"hız artar","d":"Belirli bir sıcaklığa kadar artan sıcaklıkla tanecik enerjisi ve hız artar (optimum sıcaklık)."},{"t":"Denatürasyon","a":"aktif bölge bozulur","d":"Optimumu aşan sıcaklıkta enzimin protein yapısı bozulur (denatürasyon); aktif bölge şeklini kaybeder ve katalitik etki düşer."}],"ans":"Enzimde sıcaklık optimuma kadar hızı artırır; aşılınca protein yapı denatüre olup aktif bölge bozulduğundan katalitik etki ve hız düşer."},
{"q":"Bir tepkimede katalizör hem ileri hem geri hız sabitini eşit oranda artırırsa, denge sabiti K neden sabit kalır?","steps":[{"t":"K tanımı","a":"K = k_ileri / k_geri","d":"Denge sabiti, ileri ve geri hız sabitlerinin oranına eşittir (K = k_ileri / k_geri)."},{"t":"Oran korunur","a":"aynı kat ile çarpılır","d":"Katalizör iki sabiti de aynı kat ile çarptığından oran değişmez; bu yüzden K aynı kalır."}],"ans":"K = k_ileri / k_geri olduğundan, katalizör her iki hız sabitini de aynı oranda artırınca oran (dolayısıyla K) değişmez; denge konumu korunur."}
]}}};
