globalThis.__OUT = {"bayatlamaHiz":{"ilkokul":{"kolay":[
{"q":"Sütü neden buzdolabında saklarız?","steps":[{"t":"Soğuk yavaşlatır","a":"buzdolabı","d":"Buzdolabı soğuk olduğu için sütün bozulmasını yavaşlatır."},{"t":"Daha uzun durur","a":"taze kalır","d":"Bu sayede süt daha uzun süre taze ve içilebilir kalır."}],"ans":"Buzdolabı soğuk olduğu için sütün bozulmasını yavaşlatır, süt daha uzun taze kalır."},
{"q":"Ekmek açık havada mı yoksa poşet içinde mi daha çabuk bayatlar?","steps":[{"t":"Açık hava","a":"hızlı bayatlar","d":"Açıkta duran ekmek havayla temas eder ve daha çabuk bayatlar."},{"t":"Poşet içinde","a":"yavaş bayatlar","d":"Kapalı poşet havayı engeller, ekmek daha yavaş bayatlar."}],"ans":"Açık havada duran ekmek daha çabuk bayatlar; poşette daha yavaş bayatlar."},
{"q":"Yazın sıcakta bırakılan dondurma neden hemen erir ve bozulur?","steps":[{"t":"Sıcaklık yüksek","a":"hızlanır","d":"Hava sıcak olunca her şey daha hızlı değişir, dondurma çabuk erir."},{"t":"Bozulma","a":"çabuk bozulur","d":"Eriyen ve sıcakta kalan dondurma çabucak bozulur."}],"ans":"Sıcak hava değişimi hızlandırdığı için dondurma hemen erir ve bozulur."},
{"q":"Meyveleri taze tutmak için ne yapmamız iyi olur?","fig":"<svg viewBox='0 0 320 160'><rect x='40' y='30' width='100' height='100' rx='8' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='90' cy='80' r='16' fill='#e0552b' stroke='#1a2b45'/><text x='90' y='148' font-size='11' text-anchor='middle' fill='#1a2b45'>buzdolabi</text><rect x='190' y='30' width='100' height='100' rx='8' fill='#f5d7c0' stroke='#1a2b45'/><circle cx='240' cy='80' r='16' fill='#e0552b' stroke='#1a2b45'/><text x='240' y='148' font-size='11' text-anchor='middle' fill='#1a2b45'>sicak masa</text></svg>","steps":[{"t":"Soğukta sakla","a":"buzdolabı","d":"Meyveleri buzdolabında soğukta saklamak iyi olur."},{"t":"Yavaş bozulur","a":"taze kalır","d":"Soğuk bozulmayı yavaşlattığı için meyveler daha uzun taze kalır."}],"ans":"Meyveleri buzdolabında saklamak iyidir; soğuk bozulmayı yavaşlatır."},
{"q":"Aynı elmadan biri masada, biri buzdolabında. Hangisi daha çabuk çürür?","steps":[{"t":"Masadaki","a":"sıcak","d":"Masadaki elma daha ılık ortamda durur."},{"t":"Sonuç","a":"çabuk çürür","d":"Sıcak yer bozulmayı hızlandırdığından masadaki elma daha çabuk çürür."}],"ans":"Masadaki (daha sıcak) elma buzdolabındakinden daha çabuk çürür."}
],"zor":[
{"q":"Annemiz yemeği neden hemen buzdolabına koyar, masada bırakmaz?","steps":[{"t":"Masada bekleme","a":"hızlı bozulur","d":"Ilık masada bekleyen yemek daha hızlı bozulur."},{"t":"Buzdolabı","a":"yavaşlatır","d":"Soğuk buzdolabı bozulmayı yavaşlattığı için yemek daha uzun süre dayanır."}],"ans":"Soğuk buzdolabı bozulmayı yavaşlattığı için yemek masada bırakılmaz, dolaba konur."},
{"q":"Derin dondurucudaki et neden aylarca dayanırken buzdolabındaki birkaç günde bozulur?","steps":[{"t":"Çok soğuk","a":"dondurucu","d":"Derin dondurucu buzdolabından çok daha soğuktur."},{"t":"Daha yavaş","a":"uzun dayanır","d":"Daha soğuk ortam bozulmayı çok daha fazla yavaşlattığı için et aylarca dayanır."}],"ans":"Derin dondurucu çok daha soğuk olduğundan bozulmayı daha çok yavaşlatır, et aylarca dayanır."},
{"q":"Bir bardak süt kışın balkonda, yazın aynı balkonda bırakılıyor. Hangisi daha çabuk bozulur?","steps":[{"t":"Sıcaklık farkı","a":"yaz sıcak","d":"Yazın balkon çok daha sıcaktır, kışın ise soğuktur."},{"t":"Sonuç","a":"yaz hızlı","d":"Sıcak ortam bozulmayı hızlandırdığından yazın bırakılan süt daha çabuk bozulur."}],"ans":"Yazın sıcak balkonda bırakılan süt, kışın soğukta bırakılandan daha çabuk bozulur."},
{"q":"Konserve ve reçel neden uzun süre bozulmadan durur?","steps":[{"t":"Kapalı kavanoz","a":"hava giremez","d":"Konserve ve reçel ağzı kapalı kavanozda saklanır, hava giremez."},{"t":"Yavaş bozulma","a":"uzun dayanır","d":"Hava ve mikroplar giremediği için bozulma çok yavaşlar, uzun süre dayanır."}],"ans":"Ağzı kapalı kavanozda hava giremediği için bozulma yavaşlar, konserve ve reçel uzun dayanır."},
{"q":"Piknikte yiyecekleri buzlukta (soğutucu çantada) taşımamız neden mantıklıdır?","steps":[{"t":"Sıcak hava","a":"bozar","d":"Piknikte hava sıcaktır, yiyecekler çabuk bozulabilir."},{"t":"Soğutucu çanta","a":"yavaşlatır","d":"Buzluk içini soğuk tutar, soğuk bozulmayı yavaşlatır."}],"ans":"Buzluk içini soğuk tuttuğu için bozulmayı yavaşlatır, yiyecekler piknikte daha uzun dayanır."}
]},"ortaokul":{"kolay":[
{"q":"Sıcaklık arttıkça gıdaların bozulma (tepkime) hızı nasıl değişir?","steps":[{"t":"Kural","a":"hız artar","d":"Sıcaklık arttıkça taneciklerin hareketi hızlanır, bozulma tepkimeleri hızlanır."},{"t":"Sonuç","a":"çabuk bozulur","d":"Bu yüzden sıcakta gıdalar daha çabuk bozulur, bayatlar."}],"ans":"Sıcaklık arttıkça bozulma hızı artar; gıdalar sıcakta daha çabuk bozulur."},
{"q":"Buzdolabı yiyecekleri nasıl daha uzun süre korur?","steps":[{"t":"Düşük sıcaklık","a":"yavaşlatır","d":"Buzdolabı sıcaklığı düşürür, böylece bozulma tepkimeleri yavaşlar."},{"t":"Mikroplar","a":"yavaş ürer","d":"Soğukta mikroorganizmalar da yavaş çoğaldığı için gıda uzun korunur."}],"ans":"Buzdolabı sıcaklığı düşürerek bozulma tepkimelerini ve mikrop üremesini yavaşlatır."},
{"q":"Açık havada bekleyen yiyecek neden buzdolabındakinden hızlı bozulur?","steps":[{"t":"Oda sıcaklığı","a":"daha sıcak","d":"Açık hava (oda) sıcaklığı buzdolabından yüksektir."},{"t":"Hız","a":"daha hızlı","d":"Yüksek sıcaklıkta bozulma tepkimeleri daha hızlı olur."}],"ans":"Açık havadaki sıcaklık daha yüksek olduğu için bozulma tepkimesi hızlanır."},
{"q":"Gıda saklamada hangi yöntemler bozulmayı yavaşlatır?","fig":"<svg viewBox='0 0 320 150'><rect x='20' y='40' width='80' height='70' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='60' y='128' font-size='10' text-anchor='middle' fill='#1a2b45'>soğutma</text><rect x='120' y='40' width='80' height='70' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='160' y='128' font-size='10' text-anchor='middle' fill='#1a2b45'>kurutma</text><rect x='220' y='40' width='80' height='70' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='260' y='128' font-size='10' text-anchor='middle' fill='#1a2b45'>tuzlama</text></svg>","steps":[{"t":"Yöntemler","a":"soğutma, kurutma, tuzlama","d":"Soğutma, kurutma, tuzlama, salamura ve konserve bozulmayı yavaşlatır."},{"t":"Ortak amaç","a":"tepkimeyi yavaşlatma","d":"Hepsi sıcaklığı, suyu veya havayı azaltarak bozulma hızını düşürür."}],"ans":"Soğutma, kurutma, tuzlama ve konserve gibi yöntemler bozulma hızını düşürerek gıdayı korur."},
{"q":"Donmuş gıda neden çok uzun süre dayanır?","steps":[{"t":"Çok düşük sıcaklık","a":"donma","d":"Donmada sıcaklık çok düşüktür, tanecik hareketi neredeyse durur."},{"t":"Bozulma","a":"çok yavaş","d":"Bu yüzden bozulma tepkimeleri çok yavaşlar, gıda aylarca dayanır."}],"ans":"Çok düşük sıcaklıkta bozulma tepkimeleri çok yavaşladığı için donmuş gıda uzun dayanır."}
],"zor":[
{"q":"Sıcaklığın artması bozulma tepkimesini neden hızlandırır? Tanecik düzeyinde açıkla.","fig":"<svg viewBox='0 0 320 150'><text x='75' y='25' font-size='10' text-anchor='middle' fill='#1a2b45'>soguk: yavas</text><circle cx='50' cy='70' r='8' fill='#2b6be0'/><circle cx='90' cy='90' r='8' fill='#2b6be0'/><circle cx='70' cy='110' r='8' fill='#2b6be0'/><text x='245' y='25' font-size='10' text-anchor='middle' fill='#1a2b45'>sicak: hizli</text><circle cx='210' cy='60' r='8' fill='#e0552b'/><circle cx='260' cy='80' r='8' fill='#e0552b'/><circle cx='230' cy='110' r='8' fill='#e0552b'/><line x1='210' y1='60' x2='240' y2='95' stroke='#1a2b45'/><line x1='260' y1='80' x2='232' y2='105' stroke='#1a2b45'/></svg>","steps":[{"t":"Tanecik hareketi","a":"hızlanır","d":"Sıcaklık artınca tanecikler daha hızlı hareket eder, daha sık çarpışır."},{"t":"Etkili çarpışma","a":"artar","d":"Daha hızlı ve enerjik çarpışmalar bozulma tepkimesini hızlandırır."}],"ans":"Sıcaklık taneciklerin hızını ve çarpışma sıklığını artırdığı için bozulma tepkimesi hızlanır."},
{"q":"Bir yiyecek oda sıcaklığında 2 günde, buzdolabında 10 günde bozuluyorsa bu fark neyi gösterir?","fig":"<svg viewBox='0 0 320 150'><text x='160' y='25' font-size='10' text-anchor='middle' fill='#1a2b45'>bozulma suresi (gun)</text><rect x='60' y='85' width='40' height='30' fill='#e0552b'/><text x='80' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>oda: 2</text><rect x='200' y='35' width='40' height='80' fill='#2b6be0'/><text x='220' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>dolap: 10</text></svg>","steps":[{"t":"Karşılaştırma","a":"5 kat","d":"Buzdolabında bozulma süresi 5 kat uzamıştır."},{"t":"Yorum","a":"hız düşmüş","d":"Düşük sıcaklık bozulma hızını yaklaşık 5 kat azaltmıştır."}],"ans":"Soğuk ortam bozulma süresini 5 kat uzatmış, yani bozulma hızını yaklaşık 5 kat azaltmıştır."},
{"q":"Pastörizasyonda süt neden kısa süre ısıtılıp sonra hızla soğutulur?","steps":[{"t":"Isıtma","a":"mikrop öldürür","d":"Kısa süreli ısıtma sütteki zararlı mikroorganizmaları öldürür."},{"t":"Hızlı soğutma","a":"yavaş bozulur","d":"Sonra hızla soğutmak kalan bozulmayı yavaşlatır, süt uzun dayanır."}],"ans":"Isıtma mikropları öldürür, ardından hızlı soğutma bozulma hızını düşürdüğü için süt uzun dayanır."},
{"q":"Kurutulmuş meyve (kuru kayısı, kuru üzüm) neden taze hâline göre çok daha uzun dayanır?","steps":[{"t":"Su azaltma","a":"kurutma","d":"Kurutmada meyvedeki su uzaklaştırılır."},{"t":"Bozulma","a":"yavaşlar","d":"Su olmadan mikroplar üreyemez ve bozulma tepkimeleri çok yavaşlar."}],"ans":"Kurutma suyu uzaklaştırdığı için mikrop üremesi ve bozulma yavaşlar, kuru meyve uzun dayanır."},
{"q":"Vakumlu (havasız) paketleme bozulmayı nasıl yavaşlatır?","fig":"<svg viewBox='0 0 320 150'><rect x='40' y='40' width='90' height='70' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='60' cy='60' r='4' fill='#5b6b85'/><circle cx='100' cy='80' r='4' fill='#5b6b85'/><circle cx='80' cy='95' r='4' fill='#5b6b85'/><text x='85' y='128' font-size='10' text-anchor='middle' fill='#1a2b45'>havali</text><rect x='190' y='55' width='90' height='40' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='235' y='128' font-size='10' text-anchor='middle' fill='#1a2b45'>vakum (O₂ yok)</text></svg>","steps":[{"t":"Hava çekilir","a":"oksijen yok","d":"Vakumlamada paketteki hava, özellikle oksijen alınır."},{"t":"Yavaşlama","a":"yükseltgenme azalır","d":"Oksijen olmayınca yükseltgenme (acılaşma) ve oksijen seven mikroplar azalır, bozulma yavaşlar."}],"ans":"Vakum oksijeni uzaklaştırdığı için yükseltgenme ve mikrop üremesi azalır, bozulma yavaşlar."}
]},"lise":{"kolay":[
{"q":"Tepkime hızını etkileyen başlıca faktörler nelerdir?","steps":[{"t":"Faktörler","a":"sıcaklık, derişim, yüzey, katalizör","d":"Sıcaklık, derişim, temas yüzeyi, katalizör ve ortam (su, oksijen) tepkime hızını etkiler."},{"t":"Gıda örneği","a":"bozulma","d":"Gıda bozulması da bir tepkimedir; aynı faktörler hızını belirler."}],"ans":"Tepkime hızını sıcaklık, derişim, temas yüzeyi ve katalizör etkiler; gıda bozulması da buna uyar."},
{"q":"Sıcaklığın tepkime hızına etkisi neden bu kadar belirgindir?","steps":[{"t":"Aktivasyon enerjisi","a":"eşik","d":"Tepkimenin olması için taneciklerin aktivasyon enerjisini aşması gerekir."},{"t":"Sıcaklık","a":"enerjili tanecik artar","d":"Sıcaklık artınca eşiği aşacak enerjili tanecik sayısı hızla artar."}],"ans":"Sıcaklık arttıkça aktivasyon enerjisini aşan tanecik oranı hızla arttığı için tepkime belirgin hızlanır."},
{"q":"Bir kuralla, sıcaklık 10 °C arttığında tepkime hızı kabaca nasıl değişir?","steps":[{"t":"Yaklaşık kural","a":"2 kat","d":"Birçok tepkimede sıcaklık 10 °C artınca hız kabaca 2 katına çıkar."},{"t":"Yorum","a":"hızlı bozulma","d":"Bu yüzden ılık ortam bozulmayı belirgin hızlandırır."}],"ans":"Genel bir yaklaşımla sıcaklık 10 °C artınca tepkime hızı kabaca iki katına çıkar."},
{"q":"Buzdolabı sıcaklığı (4 °C) ile oda sıcaklığı (24 °C) arasında bozulma hızı kabaca kaç kat değişir?","fig":"<svg viewBox='0 0 320 150'><line x1='40' y1='115' x2='290' y2='115' stroke='#1a2b45' stroke-width='2'/><rect x='70' y='95' width='30' height='20' fill='#2b6be0'/><text x='85' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>4°C ×1</text><rect x='210' y='35' width='30' height='80' fill='#e0552b'/><text x='225' y='135' font-size='10' text-anchor='middle' fill='#1a2b45'>24°C ×4</text><text x='160' y='25' font-size='10' text-anchor='middle' fill='#1a2b45'>bozulma hizi</text></svg>","steps":[{"t":"Fark","a":"20 °C","d":"İki sıcaklık arasındaki fark 24 − 4 = 20 °C'dir."},{"t":"Yaklaşım","a":"2² = 4 kat","d":"Her 10 °C için 2 kat alınırsa 20 °C için 2×2 = 4 kat hız değişir."}],"ans":"Yaklaşık 20 °C fark için bozulma hızı kabaca 4 kat değişir; oda sıcaklığında çok daha hızlı bozulur."},
{"q":"Oksijenin gıda bozulmasındaki (acılaşma) rolü nedir?","steps":[{"t":"Yükseltgenme","a":"O₂ tepkir","d":"Yağlar oksijenle tepkiyerek yükseltgenir ve acılaşır."},{"t":"Engelleme","a":"vakum/antioksidan","d":"Oksijeni azaltmak (vakum) veya antioksidan eklemek bu tepkimeyi yavaşlatır."}],"ans":"Oksijen yağların yükseltgenmesini (acılaşma) sağlar; vakum ve antioksidanlar bu bozulmayı yavaşlatır."}
],"zor":[
{"q":"Bir gıda 25 °C'de 4 günde bozuluyor. Her 10 °C düşüşte hız yarıya iniyorsa 5 °C'de kaç günde bozulur?","fig":"<svg viewBox='0 0 320 150'><line x1='40' y1='120' x2='290' y2='120' stroke='#1a2b45' stroke-width='2'/><line x1='40' y1='120' x2='40' y2='20' stroke='#1a2b45' stroke-width='2'/><text x='60' y='135' font-size='10' fill='#1a2b45'>5°C</text><text x='250' y='135' font-size='10' fill='#1a2b45'>25°C</text><circle cx='70' cy='100' r='5' fill='#2b6be0'/><circle cx='260' cy='40' r='5' fill='#e0552b'/><text x='160' y='18' font-size='10' text-anchor='middle' fill='#1a2b45'>hiz: sicaklikla artar</text></svg>","steps":[{"t":"Sıcaklık farkı","a":"20 °C","d":"25 − 5 = 20 °C düşüş, yani iki kez 10 °C düşüş vardır."},{"t":"Hız çarpanı","a":"1/4","d":"Her 10 °C'de hız yarıya inerse 20 °C'de hız (1/2)×(1/2) = 1/4 olur."},{"t":"Süre","a":"4×4 = 16 gün","d":"Hız 1/4'e düşünce bozulma süresi 4 katına çıkar: 4×4 = 16 gün."}],"ans":"5 °C'de gıda yaklaşık 16 günde bozulur (hız 1/4'e iner, süre 4 katına çıkar)."},
{"q":"Oda sıcaklığında 1 günde bozulan et −18 °C'de aylarca dayanıyor. Bu büyük farkı kinetik olarak açıklayın.","steps":[{"t":"Büyük sıcaklık düşüşü","a":"çok az enerjili tanecik","d":"−18 °C'de eşik enerjisini aşan tanecik sayısı çok azdır."},{"t":"Hız sabiti","a":"çok küçük","d":"Hız sabiti üstel olarak çok küçüldüğünden enzim ve mikrop tepkimeleri neredeyse durur."},{"t":"Sonuç","a":"aylarca","d":"Bu yüzden bozulma çok yavaşlar ve et aylarca dayanır."}],"ans":"Çok düşük sıcaklık eşiği aşan tanecik oranını üstel olarak azaltıp hız sabitini çok küçülttüğü için bozulma neredeyse durur ve et aylarca dayanır."},
{"q":"Aktivasyon enerjisi büyük olan bir bozulma tepkimesi, sıcaklık değişimine neden daha duyarlıdır?","steps":[{"t":"Üstel bağ","a":"e^(−Ea/RT)","d":"Hız sabiti, aktivasyon enerjisi ile e^(−Ea/RT) çarpanına bağlıdır."},{"t":"Büyük Ea","a":"keskin değişim","d":"Ea büyükse sıcaklıktaki küçük değişim bu çarpanı çok değiştirir."},{"t":"Sonuç","a":"duyarlı","d":"Bu yüzden büyük Ea'lı tepkimenin hızı sıcaklığa daha duyarlıdır."}],"ans":"Hız sabiti e^(−Ea/RT) ile orantılı olduğundan büyük aktivasyon enerjili tepkimeler sıcaklık değişimine daha duyarlıdır."},
{"q":"Soğutma bozulmayı yavaşlatır ama tepkimenin dengesini (ürün miktarını) değiştirir mi? Açıklayın.","steps":[{"t":"Hız vs denge","a":"farklı","d":"Sıcaklık hem hızı hem dengeyi etkiler ama bunlar farklı kavramlardır."},{"t":"Hız","a":"yavaşlar","d":"Soğutma bozulma hızını (ne kadar çabuk) belirgin düşürür."},{"t":"Pratik sonuç","a":"süre uzar","d":"Gıda saklamada amaç hızı düşürmektir; bozulma yine olur ama çok yavaş gerçekleşir."}],"ans":"Soğutma asıl olarak bozulma hızını düşürür; bozulma tümden durmaz, sadece çok yavaşladığı için gıda uzun süre korunur."},
{"q":"Bir konserve neden hem ısıl işlem hem de hava boşaltma ile korunur; iki yöntemin tepkime hızına etkisini birlikte değerlendirin.","steps":[{"t":"Isıl işlem","a":"mikrop öldürür","d":"Yüksek sıcaklıkta sterilizasyon mevcut mikropları ve sporları öldürür."},{"t":"Hava boşaltma","a":"oksijen yok","d":"Havası alınınca oksijenli bozulma (yükseltgenme) ve oksijen seven mikrop üremesi durur."},{"t":"Birlikte","a":"çok düşük hız","d":"İki etki birleşince bozulma tepkimelerinin hızı neredeyse sıfıra iner, konserve yıllarca dayanır."}],"ans":"Isıl işlem mikropları öldürür, hava boşaltma oksijenli bozulmayı durdurur; birlikte bozulma hızını neredeyse sıfıra indirip konserveyi yıllarca korur."}
]}}};
