globalThis.__OUT = {"notrlesme":{"ilkokul":{"kolay":[
{"q":"Bir asit ile bir baz karıştırıldığında birbirinin etkisini gidermesine ne denir?","steps":[{"t":"Karışma","a":"asit + baz","d":"Asit ve baz bir araya geldiğinde tepkimeye girer."},{"t":"Etki kaybı","a":"nötrleşme","d":"Birbirinin etkisini yok ettikleri bu olaya nötrleşme denir."}],"ans":"Asit ile bazın birbirinin etkisini gidermesine nötrleşme denir."},
{"q":"Limon ve sirke gibi ekşi tatlı maddeler hangi gruba girer?","steps":[{"t":"Tat","a":"ekşi","d":"Limon ve sirke ekşi tada sahiptir."},{"t":"Grup","a":"asit","d":"Ekşi tatlı bu maddeler asitler grubuna girer."}],"ans":"Limon ve sirke gibi ekşi maddeler asitlerdir."},
{"q":"Sabun ve karbonat gibi maddeler hangi gruba girer?","steps":[{"t":"His","a":"kayganımsı","d":"Sabun ve karbonatlı maddeler elde kaygan hissedilir, acı olabilir."},{"t":"Grup","a":"baz","d":"Bu maddeler bazlar grubuna girer."}],"ans":"Sabun ve karbonat gibi kaygan maddeler bazlardır."},
{"q":"Karıncanın ya da arının soktuğu yere neden karbonatlı (bazik) su sürülür?","fig":"<svg viewBox='0 0 320 150'><circle cx='90' cy='75' r='24' fill='#e0552b' stroke='#1a2b45'/><text x='90' y='80' font-size='10' text-anchor='middle' fill='#fff'>asit</text><text x='135' y='80' font-size='16' text-anchor='middle' fill='#1a2b45'>+</text><circle cx='185' cy='75' r='24' fill='#2b6be0' stroke='#1a2b45'/><text x='185' y='80' font-size='10' text-anchor='middle' fill='#fff'>baz</text><text x='230' y='80' font-size='16' text-anchor='middle' fill='#1a2b45'>→</text><text x='280' y='80' font-size='10' text-anchor='middle' fill='#1a2b45'>nötr</text></svg>","steps":[{"t":"Sokma asidik","a":"asit bırakır","d":"Arı/karınca sokunca deriye asidik bir madde bırakır."},{"t":"Bazla nötrleme","a":"karbonat","d":"Bazik karbonatlı su bu asidi nötrleştirip yanma hissini azaltır."}],"ans":"Sokma asidik olduğu için, bazik karbonatlı su asidi nötrleştirir ve rahatsızlığı azaltır."},
{"q":"Saf su asidik mi, bazik mi yoksa nötr müdür?","steps":[{"t":"Ne ekşi ne kaygan","a":"ortada","d":"Saf su ne ekşidir ne de bazların özelliğini gösterir."},{"t":"Sonuç","a":"nötr","d":"Bu yüzden saf su nötr kabul edilir."}],"ans":"Saf su nötrdür; asidik de bazik de değildir."}
],"zor":[
{"q":"Midemiz çok ekşidiğinde (mide ekşimesi) neden bazik bir ilaç (mide ilacı) içilir?","steps":[{"t":"Fazla asit","a":"midede asit","d":"Mide ekşimesinde midede fazla asit (HCl) bulunur."},{"t":"Bazla nötrleme","a":"ilaç bazik","d":"Bazik mide ilacı bu fazla asidi nötrleştirip rahatsızlığı giderir."}],"ans":"Mide ekşimesinde fazla mide asidini nötrleştirmek için bazik mide ilacı içilir."},
{"q":"Asit ile baz tam olarak nötrleşince ortaya hangi iki tür madde çıkar?","steps":[{"t":"Birinci ürün","a":"tuz","d":"Asit ve baz tepkimesinden bir tuz oluşur."},{"t":"İkinci ürün","a":"su","d":"Ayrıca su (H₂O) açığa çıkar; yani ürünler tuz ve sudur."}],"ans":"Asit ile baz nötrleşince tuz ve su oluşur."},
{"q":"Turnusol kâğıdı asitte ve bazda hangi renkleri alır?","fig":"<svg viewBox='0 0 320 150'><rect x='60' y='55' width='60' height='40' fill='#e0552b' stroke='#1a2b45'/><text x='90' y='115' font-size='10' text-anchor='middle' fill='#1a2b45'>asit: kırmızı</text><rect x='200' y='55' width='60' height='40' fill='#2b6be0' stroke='#1a2b45'/><text x='230' y='115' font-size='10' text-anchor='middle' fill='#1a2b45'>baz: mavi</text></svg>","steps":[{"t":"Asit","a":"kırmızı","d":"Mavi turnusol asitte kırmızıya döner."},{"t":"Baz","a":"mavi","d":"Kırmızı turnusol bazda maviye döner."}],"ans":"Turnusol asitte kırmızı, bazda mavi renk alır."},
{"q":"Toprak çok asidikse (ekşiyse) çiftçiler neden kireç (bazik) ekler?","steps":[{"t":"Asidik toprak","a":"bitkiye zor","d":"Çok asidik toprak bazı bitkiler için uygun değildir."},{"t":"Kireçle nötrleme","a":"bazik kireç","d":"Bazik olan kireç toprağın asidini nötrleştirip pH'ı dengeler, toprağı bitkiye uygun hale getirir."}],"ans":"Asidik toprağı nötrleştirmek için bazik özellikteki kireç eklenir; böylece toprak bitki için uygun hale gelir."},
{"q":"Diş macunu çoğunlukla neden hafif baziktir?","steps":[{"t":"Ağızda asit","a":"diş çürütür","d":"Yiyecek artıkları ağızda asit oluşturur, bu asit dişi aşındırır."},{"t":"Bazik macun","a":"nötrler","d":"Hafif bazik diş macunu bu asidi nötrleştirerek dişleri korur."}],"ans":"Diş macunu, ağızdaki asidi nötrleştirip dişleri koruduğu için çoğunlukla hafif baziktir."}
]},"ortaokul":{"kolay":[
{"q":"Nötrleşme tepkimesinin genel denklemi nasıldır?","steps":[{"t":"Girenler","a":"asit + baz","d":"Bir asit ile bir baz tepkimeye girer."},{"t":"Ürünler","a":"tuz + su","d":"Sonuçta bir tuz ve su oluşur: asit + baz → tuz + su."}],"ans":"Nötrleşmenin genel denklemi: asit + baz → tuz + su biçimindedir."},
{"q":"HCl + NaOH → NaCl + H₂O tepkimesinde hangi tuz oluşur?","fig":"<svg viewBox='0 0 320 150'><text x='75' y='75' font-size='12' text-anchor='middle' fill='#1a2b45'>HCl + NaOH</text><text x='160' y='75' font-size='16' text-anchor='middle' fill='#1a2b45'>→</text><text x='245' y='75' font-size='12' text-anchor='middle' fill='#1a2b45'>NaCl + H₂O</text></svg>","steps":[{"t":"Asit ve baz","a":"HCl ve NaOH","d":"Hidroklorik asit (HCl) ile sodyum hidroksit (NaOH) tepkimeye girer."},{"t":"Tuz","a":"NaCl","d":"Oluşan tuz sodyum klorürdür (NaCl, yemek tuzu); ayrıca su açığa çıkar."}],"ans":"HCl + NaOH → NaCl + H₂O tepkimesinde sodyum klorür (NaCl) tuzu ve su oluşur."},
{"q":"pH cetvelinde 7 değeri neyi gösterir?","steps":[{"t":"Cetvel","a":"0 - 14","d":"pH cetveli 0 ile 14 arasında değer alır."},{"t":"Orta nokta","a":"nötr","d":"pH = 7 nötrlüğü gösterir; 7'den küçük asidik, büyük baziktir."}],"ans":"pH = 7 nötrlüğü gösterir; 7'den küçük değerler asidik, büyük değerler baziktir."},
{"q":"Nötrleşme sırasında ortamın pH'ı genel olarak nasıl değişir?","steps":[{"t":"Başlangıç","a":"asit düşük pH","d":"Asidik ortamın pH'ı düşüktür (7'nin altında)."},{"t":"Baz eklenince","a":"7'ye doğru","d":"Üzerine baz eklendikçe asit nötrleşir ve pH 7'ye (nötre) doğru yaklaşır."}],"ans":"Asidik ortama baz eklendikçe asit nötrleşir ve pH 7'ye (nötr değere) doğru yaklaşır."},
{"q":"Nötrleşmenin günlük hayattan bir örneğini veriniz.","steps":[{"t":"Olay","a":"mide ekşimesi","d":"Midede fazla asit (HCl) birikince mide ekşimesi olur."},{"t":"Çözüm","a":"bazik ilaç","d":"Bazik mide ilacı (örneğin Mg(OH)₂ içeren) bu asidi nötrleştirir."}],"ans":"Mide ekşimesinde bazik mide ilacının fazla mide asidini nötrleştirmesi, nötrleşmenin günlük bir örneğidir."}
],"zor":[
{"q":"HCl + NaOH → NaCl + H₂O denkleminin denk olduğunu gösteriniz.","steps":[{"t":"H ve Cl","a":"H 2=2, Cl 1=1","d":"Solda HCl (1 H, 1 Cl) + NaOH (1 H) → 2 H; sağda H₂O → 2 H ve NaCl → 1 Cl; eşit."},{"t":"Na ve O","a":"Na 1=1, O 1=1","d":"Solda NaOH → 1 Na, 1 O; sağda NaCl → 1 Na, H₂O → 1 O atomu; eşit, denklem denktir."}],"ans":"H (2 = 2), Cl (1 = 1), Na (1 = 1) ve O (1 = 1) atomları iki tarafta eşit olduğundan HCl + NaOH → NaCl + H₂O denktir."},
{"q":"Sülfürik asitin sodyum hidroksitle nötrleşmesi neden 2NaOH gerektirir? (H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O)","fig":"<svg viewBox='0 0 320 150'><text x='85' y='70' font-size='11' text-anchor='middle' fill='#1a2b45'>H₂SO₄ + 2NaOH</text><text x='175' y='70' font-size='15' text-anchor='middle' fill='#1a2b45'>→</text><text x='255' y='70' font-size='11' text-anchor='middle' fill='#1a2b45'>Na₂SO₄ + 2H₂O</text></svg>","steps":[{"t":"İki H⁺","a":"diprotik asit","d":"H₂SO₄ iki adet H⁺ verebilir, bu yüzden iki OH⁻ ile tepkimesi gerekir."},{"t":"Denklik","a":"2NaOH gerekir","d":"İki OH⁻ sağlamak için 2NaOH alınır; böylece H 4=4, Na 2=2, S 1=1, O 6=6 olarak denkleşir."}],"ans":"H₂SO₄ iki H⁺ verdiğinden iki OH⁻ gerekir; bu yüzden 2NaOH alınır ve H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O denkleşir."},
{"q":"Nötrleşme tepkimesi enerji açısından neden ekzotermiktir?","steps":[{"t":"İyon birleşmesi","a":"H⁺ + OH⁻","d":"Nötrleşmede asitten gelen H⁺ ile bazdan gelen OH⁻ birleşerek su oluşturur."},{"t":"Enerji salımı","a":"ısı verir","d":"Bu birleşme daha kararlı (düşük enerjili) su molekülü oluşturduğundan ısı açığa çıkar; bu yüzden nötrleşme ekzotermiktir."}],"ans":"Nötrleşmede H⁺ ile OH⁻ birleşip kararlı su oluşturduğundan ısı açığa çıkar; bu nedenle tepkime ekzotermiktir."},
{"q":"Bir tepkimede pH 2 olan asit ortamına yeterince baz eklenirse pH nasıl ve neden değişir?","steps":[{"t":"Asit nötrlenir","a":"H⁺ azalır","d":"Eklenen baz, ortamdaki H⁺ iyonlarını OH⁻ ile birleştirerek azaltır."},{"t":"pH artar","a":"7'ye, sonra üstüne","d":"H⁺ azaldıkça pH 2'den yükselir; tam nötrleşmede 7 olur, fazla baz eklenirse 7'nin üstüne (bazik tarafa) çıkar."}],"ans":"Baz eklendikçe H⁺ azaldığı için pH 2'den yükselir; tam nötrleşmede 7'ye gelir, fazla baz eklenirse pH 7'nin üstüne çıkar."},
{"q":"Bir asidin pH'ı 3 ise H⁺ derişimi ne kadardır ve bu ortam asidik mi baziktir? (pH = −log[H⁺])","steps":[{"t":"Bağıntı","a":"pH = −log[H⁺]","d":"pH ile H⁺ derişimi pH = −log[H⁺] bağıntısıyla ilişkilidir."},{"t":"Hesap","a":"[H⁺] = 10⁻³ mol/L","d":"pH = 3 için [H⁺] = 10⁻³ mol/L olur; pH 7'den küçük olduğundan ortam asidiktir."}],"ans":"pH = 3 için [H⁺] = 10⁻³ mol/L'dir ve pH 7'den küçük olduğundan ortam asidiktir."}
]},"lise":{"kolay":[
{"q":"Nötrleşme tepkimesi Arrhenius yaklaşımıyla nasıl tanımlanır?","steps":[{"t":"Asit ve baz","a":"H⁺ ve OH⁻","d":"Arrhenius'a göre asit suya H⁺, baz ise OH⁻ verir."},{"t":"Net olay","a":"su oluşur","d":"Nötrleşmede H⁺ + OH⁻ → H₂O olur; genel olarak asit + baz → tuz + su biçimindedir."}],"ans":"Arrhenius yaklaşımıyla nötrleşme, asidin verdiği H⁺ ile bazın verdiği OH⁻'nin birleşip su oluşturmasıdır: asit + baz → tuz + su."},
{"q":"Nötrleşmenin net iyon denklemi nedir ve neden tuz bu denklemde görünmez?","steps":[{"t":"İzleyici iyon","a":"tuz iyonları","d":"Tuzu oluşturan iyonlar (örneğin Na⁺, Cl⁻) tepkimeye doğrudan katılmaz, ortamda serbest kalır (izleyici iyon)."},{"t":"Net denklem","a":"H⁺ + OH⁻ → H₂O","d":"Geriye sadece H⁺ ile OH⁻'nin su oluşturması kalır; net iyon denklemi H⁺ + OH⁻ → H₂O'dur."}],"ans":"Nötrleşmenin net iyon denklemi H⁺ + OH⁻ → H₂O'dur; tuz iyonları izleyici olduğundan tepkimeye girmez ve net denklemde görünmez."},
{"q":"Kuvvetli asit-kuvvetli baz nötrleşmesinde eşdeğerlik noktasında pH neden 7'dir?","steps":[{"t":"Tam tepkime","a":"H⁺ = OH⁻","d":"Kuvvetli asit ve kuvvetli baz tam iyonlaştığından eşdeğerlik noktasında H⁺ ve OH⁻ tam birbirini tüketir."},{"t":"Nötr tuz","a":"pH = 7","d":"Oluşan tuz suyu asidik/bazik etkilemez (hidroliz olmaz); 25 °C'de ortam nötr, pH = 7 olur."}],"ans":"Kuvvetli asit-kuvvetli baz nötrleşmesinde H⁺ ve OH⁻ tam tükenir ve oluşan tuz nötr olduğundan 25 °C'de eşdeğerlik noktasında pH = 7'dir."},
{"q":"pH + pOH toplamı 25 °C'de neden 14'tür?","steps":[{"t":"Suyun iyon dengesi","a":"Kw = 10⁻¹⁴","d":"25 °C'de suyun iyon çarpımı Kw = [H⁺]·[OH⁻] = 1,0·10⁻¹⁴'tür."},{"t":"Logaritma","a":"pH + pOH = 14","d":"Bu eşitliğin negatif logaritması alınınca pH + pOH = 14 elde edilir."}],"ans":"25 °C'de Kw = [H⁺]·[OH⁻] = 10⁻¹⁴ olduğundan, negatif logaritmasıyla pH + pOH = 14 olur."},
{"q":"Günlük hayatta antasit (mide ilacı) Mg(OH)₂'nin mide asidini nötrlemesi nasıl açıklanır?","steps":[{"t":"Mide asidi","a":"HCl","d":"Mide özsuyu hidroklorik asit (HCl) içerir; fazlası ekşimeye yol açar."},{"t":"Nötrleşme","a":"Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O","d":"Bazik Mg(OH)₂ asitle tepkimeye girip tuz ve su oluşturarak fazla asidi nötrler."}],"ans":"Bazik Mg(OH)₂, mide asidiyle Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O tepkimesini verip fazla HCl'yi nötrleştirir; bu nötrleşmenin günlük bir uygulamasıdır."}
],"zor":[
{"q":"H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O denkleminin tüm atomlar için denk olduğunu gösteriniz.","fig":"<svg viewBox='0 0 320 150'><text x='85' y='65' font-size='11' text-anchor='middle' fill='#1a2b45'>H₂SO₄ + 2NaOH</text><text x='175' y='65' font-size='15' text-anchor='middle' fill='#1a2b45'>→</text><text x='255' y='65' font-size='11' text-anchor='middle' fill='#1a2b45'>Na₂SO₄ + 2H₂O</text><text x='160' y='105' font-size='10' text-anchor='middle' fill='#1a2b45'>H:4 Na:2 S:1 O:6</text></svg>","steps":[{"t":"H ve Na","a":"H 4=4, Na 2=2","d":"Solda H₂SO₄ (2 H) + 2NaOH (2 H) = 4 H; sağda 2H₂O → 4 H. Na: solda 2NaOH → 2 Na, sağda Na₂SO₄ → 2 Na; eşit."},{"t":"S ve O","a":"S 1=1, O 6=6","d":"S: her iki tarafta 1. O: solda H₂SO₄ (4 O) + 2NaOH (2 O) = 6 O; sağda Na₂SO₄ (4 O) + 2H₂O (2 O) = 6 O; eşit, denklem denktir."}],"ans":"H (4 = 4), Na (2 = 2), S (1 = 1) ve O (6 = 6) atom sayıları iki tarafta eşit olduğundan H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O denktir."},
{"q":"0,1 mol HCl içeren çözeltiyi tam nötrlemek için 0,5 M NaOH çözeltisinden kaç litre gerekir? (HCl + NaOH → NaCl + H₂O)","steps":[{"t":"Mol oranı","a":"1 HCl : 1 NaOH","d":"Denkleme göre 1 mol HCl, 1 mol NaOH ile nötrleşir; 0,1 mol HCl için 0,1 mol NaOH gerekir."},{"t":"Hacim","a":"V = mol / M","d":"V = 0,1 mol / 0,5 mol/L = 0,2 L."}],"ans":"0,1 mol HCl için 0,1 mol NaOH gerekir; 0,5 M çözeltiden V = 0,1 / 0,5 = 0,2 litre (200 mL) gerekir."},
{"q":"[H⁺] = 1,0·10⁻⁴ mol/L olan bir çözeltinin pH ve pOH değerlerini bulunuz. (pH + pOH = 14)","steps":[{"t":"pH","a":"4","d":"pH = −log[H⁺] = −log(10⁻⁴) = 4; pH 7'den küçük olduğundan ortam asidiktir."},{"t":"pOH","a":"10","d":"pH + pOH = 14 olduğundan pOH = 14 − 4 = 10."}],"ans":"[H⁺] = 10⁻⁴ mol/L için pH = 4 ve pOH = 14 − 4 = 10'dur; ortam asidiktir."},
{"q":"Kuvvetli ve zayıf asit-baz nötrleşmelerinde eşdeğerlik noktası pH'ını ve nedenini karşılaştırınız.","steps":[{"t":"Kuvvetli-kuvvetli","a":"pH ≈ 7","d":"Kuvvetli asit + kuvvetli baz nötrleşmesinde oluşan tuz hidroliz olmaz, eşdeğerlik noktası pH'ı 7 civarındadır."},{"t":"Zayıf bileşen","a":"7'den sapar","d":"Zayıf asit + kuvvetli baz tuzu bazik hidroliz yapar (pH > 7); kuvvetli asit + zayıf baz tuzu asidik hidroliz yapar (pH < 7)."}],"ans":"Kuvvetli asit-kuvvetli bazda eşdeğerlik pH'ı yaklaşık 7'dir; zayıf asit-kuvvetli bazda oluşan tuz bazik hidrolizle pH'ı 7'nin üstüne, kuvvetli asit-zayıf bazda asidik hidrolizle 7'nin altına kaydırır."},
{"q":"50 mL 0,2 M HCl çözeltisi, 50 mL 0,2 M NaOH ile karıştırılırsa ortam asidik mi bazik mi nötr olur ve neden?","steps":[{"t":"Mol hesabı","a":"0,01 = 0,01 mol","d":"HCl: 0,050 L × 0,2 mol/L = 0,01 mol; NaOH: 0,050 L × 0,2 mol/L = 0,01 mol; mol sayıları eşit."},{"t":"Tam nötrleşme","a":"pH ≈ 7","d":"1:1 mol oranıyla H⁺ ve OH⁻ tam birbirini tüketir; oluşan NaCl nötr tuzdur, dolayısıyla ortam nötr (pH ≈ 7) olur."}],"ans":"HCl ve NaOH mol sayıları eşit (0,01 mol) olduğundan 1:1 oranla tam nötrleşir; oluşan NaCl nötr tuz olduğundan ortam nötr (pH ≈ 7) olur."}
]}}};
