globalThis.__OUT = {"bagEnerjisi":{"ilkokul":{"kolay":[
{"q":"İki Lego parçasını birbirine takmak mı, ayırmak mı daha çok güç ister?","steps":[{"t":"Takma","a":"yerine oturur","d":"İki parça takılınca kendiliğinden sıkıca tutunur."},{"t":"Ayırma","a":"güç gerekir","d":"Onları ayırmak için çekmek, yani güç (enerji) harcamak gerekir."}],"ans":"Lego parçalarını ayırmak güç (enerji) ister; takmak ise kendiliğinden tutunur."},
{"q":"Atomlar birbirine bağlanırken mi yoksa ayrılırken mi enerji açığa çıkar?","steps":[{"t":"Bağlanma","a":"enerji çıkar","d":"Atomlar birbirine bağlandığında enerji açığa çıkar."},{"t":"Ayrılma","a":"enerji ister","d":"Bağı koparıp ayrılmak için ise enerji vermek gerekir."}],"ans":"Atomlar bağlanırken enerji açığa çıkar; ayrılırken enerji gerekir."},
{"q":"Mum yandığında etrafa ne yayar?","steps":[{"t":"Yanma","a":"ısı ve ışık","d":"Mum yanarken etrafa ısı ve ışık yayar."},{"t":"Enerji çıkar","a":"ekzotermik","d":"Yanma enerji açığa çıkaran bir olaydır, etrafı ısıtır."}],"ans":"Mum yandığında etrafa ısı ve ışık (enerji) yayar."},
{"q":"Aşağıdaki gibi iki atomu birbirine bağlı tutan şeye ne denir?","fig":"<svg viewBox='0 0 320 150'><circle cx='110' cy='75' r='24' fill='#e0552b' stroke='#1a2b45'/><circle cx='210' cy='75' r='24' fill='#cfd8e8' stroke='#1a2b45'/><line x1='134' y1='75' x2='186' y2='75' stroke='#1a2b45' stroke-width='4'/><text x='160' y='130' font-size='12' text-anchor='middle' fill='#1a2b45'>iki atom arasi</text></svg>","steps":[{"t":"İki atom","a":"birleşik","d":"İki atom birbirine tutunmuş durumdadır."},{"t":"Tutan şey","a":"bağ","d":"Atomları bir arada tutan bu çekime bağ denir."}],"ans":"İki atomu birbirine tutan çekime bağ denir."},
{"q":"Sıcak bir sobaya yaklaşınca ısınırız. Bu ısı nereden gelir?","steps":[{"t":"Yanma olur","a":"odun/kömür","d":"Sobada odun ya da kömür yanar."},{"t":"Enerji çıkar","a":"ısı","d":"Yanma sırasında enerji açığa çıkar, biz de bu ısıyı hissederiz."}],"ans":"Sobadaki ısı, yanma sırasında açığa çıkan enerjiden gelir."}
],"zor":[
{"q":"Bir kibrit yanarken neden ısı verir?","steps":[{"t":"Yanma","a":"yeni bağlar","d":"Kibrit yanarken maddeler havadaki oksijenle birleşir, yeni bağlar kurulur."},{"t":"Enerji","a":"açığa çıkar","d":"Yeni bağlar kurulurken enerji açığa çıktığı için kibrit ısı verir."}],"ans":"Kibrit yanarken yeni bağlar kurulduğu için enerji açığa çıkar ve ısı verir."},
{"q":"Bir buz parçasını eritmek için neden ısı vermemiz gerekir?","steps":[{"t":"Tanecikler bağlı","a":"birbirini tutar","d":"Buzdaki su tanecikleri birbirine tutunmuş durumdadır."},{"t":"Ayırmak","a":"ısı gerekir","d":"Onları gevşetip ayırmak için dışarıdan ısı (enerji) vermemiz gerekir."}],"ans":"Buzdaki tanecikleri ayırmak için dışarıdan ısı vermemiz gerekir."},
{"q":"Soğuk bir buz paketi (cold pack) açılınca neden soğur?","steps":[{"t":"Enerji çeker","a":"emer","d":"İçindeki madde çözünürken ortamdan enerji çeker."},{"t":"Soğuma","a":"ısı emilir","d":"Etraftan ısı emildiği için paket ve çevresi soğur."}],"ans":"Buz paketi çözünürken ortamdan ısı emdiği için soğur."},
{"q":"Güçlü bağı koparmak mı, gevşek bağı koparmak mı daha çok enerji ister?","steps":[{"t":"Güçlü bağ","a":"sıkı tutar","d":"Güçlü bağ atomları daha sıkı tutar."},{"t":"Çok enerji","a":"zor kopar","d":"Bu yüzden güçlü bağı koparmak için daha çok enerji gerekir."}],"ans":"Güçlü bağı koparmak gevşek bağa göre daha çok enerji ister."},
{"q":"Havai fişek patlarken ışık ve ses çıkarması neyi gösterir?","steps":[{"t":"Hızlı tepkime","a":"yanma","d":"Havai fişek içindeki maddeler çok hızlı yanar (tepkir)."},{"t":"Enerji","a":"açığa çıkar","d":"Bu tepkimede büyük enerji açığa çıkar; bu enerji ışık, ses ve ısı olur."}],"ans":"Havai fişeğin ışık ve sesi, tepkimede büyük enerjinin açığa çıktığını gösterir."}
]},"ortaokul":{"kolay":[
{"q":"Ekzotermik tepkime ne demektir?","steps":[{"t":"Tanım","a":"ısı verir","d":"Çevreye enerji (ısı) veren tepkimeye ekzotermik denir."},{"t":"Örnek","a":"yanma","d":"Yanma ve çoğu nötrleşme tepkimesi ekzotermiktir, ortamı ısıtır."}],"ans":"Ekzotermik tepkime çevreye ısı veren tepkimedir; yanma buna örnektir."},
{"q":"Endotermik tepkime ne demektir?","steps":[{"t":"Tanım","a":"ısı alır","d":"Çevreden enerji (ısı) alan tepkimeye endotermik denir."},{"t":"Sonuç","a":"ortam soğur","d":"Ortamdan ısı çekildiği için çevre soğur."}],"ans":"Endotermik tepkime çevreden ısı alan tepkimedir; ortam soğur."},
{"q":"Bağ kırmak için enerji mi gerekir, yoksa bağ kırmak enerji mi verir?","steps":[{"t":"Bağ kırma","a":"enerji gerekir","d":"Bir bağı koparmak için dışarıdan enerji vermek gerekir (endotermik adım)."},{"t":"Bağ oluşma","a":"enerji verir","d":"Bağ oluşurken ise enerji açığa çıkar (ekzotermik adım)."}],"ans":"Bağ kırmak enerji gerektirir; bağ oluşturmak ise enerji verir."},
{"q":"Bir tepkimede ısı alışverişini gösteren şema aşağıdaki gibidir. Ekzotermik olanda enerji ne yönde gider?","fig":"<svg viewBox='0 0 320 150'><rect x='40' y='40' width='80' height='60' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='80' y='75' font-size='10' text-anchor='middle' fill='#1a2b45'>sistem</text><line x1='120' y1='70' x2='220' y2='70' stroke='#e0552b' stroke-width='3'/><polygon points='220,70 212,65 212,75' fill='#e0552b'/><text x='250' y='75' font-size='11' fill='#1a2b45'>cevre</text><text x='170' y='55' font-size='10' text-anchor='middle' fill='#1a2b45'>isi</text></svg>","steps":[{"t":"Ekzotermik","a":"sistemden çevreye","d":"Ekzotermik tepkimede enerji sistemden çevreye doğru gider."},{"t":"Sonuç","a":"çevre ısınır","d":"Çevreye ısı verildiği için ortam ısınır."}],"ans":"Ekzotermik tepkimede enerji sistemden çevreye gider, çevre ısınır."},
{"q":"Yemek pişirmek için ocak yakmamız tepkimenin hangi türüne örnektir?","steps":[{"t":"Doğal gaz yanar","a":"yanma","d":"Ocakta doğal gaz oksijenle yanar."},{"t":"Isı verir","a":"ekzotermik","d":"Yanma ısı açığa çıkardığı için ekzotermik tepkimedir."}],"ans":"Ocakta gazın yanması ısı verdiği için ekzotermik tepkimeye örnektir."}
],"zor":[
{"q":"Bir tepkimede toplam 500 kJ bağ kırılıp 700 kJ bağ oluşuyorsa tepkime endotermik mi ekzotermik mi olur?","fig":"<svg viewBox='0 0 320 150'><line x1='40' y1='120' x2='290' y2='120' stroke='#1a2b45' stroke-width='2'/><rect x='70' y='70' width='40' height='50' fill='#5b6b85'/><text x='90' y='138' font-size='10' text-anchor='middle' fill='#1a2b45'>kirilan 500</text><rect x='200' y='40' width='40' height='80' fill='#e0552b'/><text x='220' y='138' font-size='10' text-anchor='middle' fill='#1a2b45'>olusan 700</text><text x='160' y='25' font-size='10' text-anchor='middle' fill='#1a2b45'>olusan>kirilan: ekzo</text></svg>","steps":[{"t":"Kural","a":"karşılaştır","d":"Oluşan bağ enerjisi kırılandan büyükse tepkime ekzotermiktir."},{"t":"Karşılaştırma","a":"700 > 500","d":"Oluşan 700 kJ, kırılan 500 kJ'den büyüktür; fazla enerji açığa çıkar."},{"t":"Sonuç","a":"ekzotermik","d":"Net 200 kJ enerji çevreye verilir, tepkime ekzotermiktir."}],"ans":"Oluşan (700 kJ) kırılandan (500 kJ) büyük olduğu için tepkime ekzotermiktir, 200 kJ açığa çıkar."},
{"q":"Bir tepkimede 900 kJ bağ kırılıp 750 kJ bağ oluşuyorsa ısı alışverişi nasıl olur?","fig":"<svg viewBox='0 0 320 150'><line x1='40' y1='120' x2='290' y2='120' stroke='#1a2b45' stroke-width='2'/><rect x='70' y='35' width='40' height='85' fill='#5b6b85'/><text x='90' y='138' font-size='10' text-anchor='middle' fill='#1a2b45'>kirilan 900</text><rect x='200' y='55' width='40' height='65' fill='#e0552b'/><text x='220' y='138' font-size='10' text-anchor='middle' fill='#1a2b45'>olusan 750</text><text x='160' y='25' font-size='10' text-anchor='middle' fill='#1a2b45'>kirilan>olusan: endo</text></svg>","steps":[{"t":"Karşılaştırma","a":"900 > 750","d":"Kırılan bağ enerjisi (900 kJ) oluşandan (750 kJ) büyüktür."},{"t":"Net","a":"150 kJ emilir","d":"Eksik kalan 150 kJ dışarıdan emilir, tepkime endotermiktir."}],"ans":"Kırılan (900 kJ) oluşandan (750 kJ) büyük olduğu için tepkime endotermiktir, 150 kJ enerji emilir."},
{"q":"Fotosentez endotermik, solunum ekzotermiktir. Bunu bağ enerjisiyle nasıl açıklarız?","steps":[{"t":"Fotosentez","a":"enerji depolar","d":"Fotosentezde güneş enerjisi kullanılarak yüksek enerjili bağlar (glikoz) kurulur, enerji depolanır."},{"t":"Solunum","a":"enerji açar","d":"Solunumda bu bağlar kırılıp daha kararlı bağlar oluşunca depolanan enerji açığa çıkar."}],"ans":"Fotosentez enerji depolayıp bağ kurduğu için endotermik, solunum bu enerjiyi bağ kırarak açtığı için ekzotermiktir."},
{"q":"Yanma tepkimeleri neden hep ekzotermiktir; bağ enerjisiyle açıklayın.","steps":[{"t":"Bağlar kırılır","a":"enerji emilir","d":"Önce yakıt ve oksijendeki bağlar kırılır, bu enerji ister."},{"t":"Güçlü bağlar","a":"çok enerji çıkar","d":"Oluşan CO₂ ve H₂O bağları çok güçlü olduğundan kırılandan fazla enerji açığa çıkar."},{"t":"Net","a":"ekzotermik","d":"Açığa çıkan enerji emilenden fazla olduğu için yanma ekzotermiktir."}],"ans":"Yanmada oluşan CO₂ ve H₂O bağları kırılanlardan çok daha fazla enerji saldığı için tepkime hep ekzotermiktir."},
{"q":"Bir kimyasal soğuk paket (cold pack) çözünürken neden soğur; bağ/etkileşim enerjisiyle açıklayın.","steps":[{"t":"Bağ kırma","a":"enerji emer","d":"Tuz çözünürken iyonlar arası bağları kırmak enerji gerektirir."},{"t":"Yeni etkileşim","a":"az enerji verir","d":"Oluşan iyon-su etkileşimleri daha az enerji saldığında net enerji emilir."},{"t":"Sonuç","a":"endotermik","d":"Sistem ortamdan ısı çektiği için paket soğur."}],"ans":"Kırılan bağlar oluşan etkileşimlerden fazla enerji gerektirdiği için çözünme endotermiktir ve paket soğur."}
]},"lise":{"kolay":[
{"q":"Bağ enerjisinden tepkime ısısı (ΔH) nasıl hesaplanır?","steps":[{"t":"Formül","a":"ΔH = Σkırılan − Σoluşan","d":"Tepkime ısısı, kırılan bağ enerjileri toplamından oluşan bağ enerjileri toplamı çıkarılarak bulunur."},{"t":"İşaret","a":"yorum","d":"ΔH negatifse ekzotermik, pozitifse endotermiktir."}],"ans":"ΔH = Σ(kırılan bağ enerjileri) − Σ(oluşan bağ enerjileri); negatifse ekzotermik, pozitifse endotermiktir."},
{"q":"Bağ kırma adımı neden hep endotermiktir?","steps":[{"t":"Çekim yenilir","a":"enerji girer","d":"Atomları tutan çekimi yenmek için sisteme enerji vermek gerekir."},{"t":"İşaret","a":"pozitif","d":"Enerji girdiği için bağ kırma adımının enerjisi daima pozitif (endotermik) değerlidir."}],"ans":"Bağ kırmak atomlar arası çekimi yenmek için enerji gerektirdiğinden bu adım daima endotermiktir."},
{"q":"Bağ oluşma adımı neden hep ekzotermiktir?","steps":[{"t":"Kararlılık","a":"enerji düşer","d":"Atomlar bağ kurunca sistemin enerjisi düşer, daha kararlı olur."},{"t":"İşaret","a":"negatif","d":"Fazla enerji dışarı salındığı için bağ oluşma adımı daima ekzotermiktir."}],"ans":"Bağ oluşurken sistem daha kararlı, düşük enerjili duruma geçip enerji saldığından bu adım daima ekzotermiktir."},
{"q":"Bağ derecesi (tek, çift, üçlü) arttıkça bağ enerjisi nasıl değişir?","steps":[{"t":"Bağ derecesi","a":"artar","d":"Bağ derecesi arttıkça atomlar arası çekim güçlenir."},{"t":"Sıralama","a":"tek<çift<üçlü","d":"Bu yüzden bağ enerjisi tek < çift < üçlü sırasıyla artar."}],"ans":"Bağ derecesi arttıkça bağ enerjisi büyür: tek bağ < çift bağ < üçlü bağ."},
{"q":"ΔH = +180 kJ/mol bulunan bir tepkime için ne söylenebilir?","steps":[{"t":"İşaret","a":"pozitif","d":"ΔH pozitif olduğundan sistem dışarıdan enerji alır."},{"t":"Yorum","a":"endotermik","d":"Kırılan bağlar oluşanlardan güçlüdür; tepkime endotermiktir ve 180 kJ ısı emer."}],"ans":"ΔH = +180 kJ/mol tepkimenin endotermik olduğunu ve 180 kJ ısı emdiğini gösterir."}
],"zor":[
{"q":"C₂H₄ + H₂ → C₂H₆ tepkimesinin ΔH'ını bağ enerjileriyle hesaplayın (C=C=614, C–C=348, C–H=413, H–H=436 kJ/mol).","fig":"<svg viewBox='0 0 320 150'><text x='20' y='60' font-size='13' fill='#1a2b45'>C₂H₄ + H₂</text><line x1='130' y1='55' x2='180' y2='55' stroke='#1a2b45' stroke-width='2'/><polygon points='180,55 172,51 172,59' fill='#1a2b45'/><text x='195' y='60' font-size='13' fill='#1a2b45'>C₂H₆</text><text x='160' y='115' font-size='11' text-anchor='middle' fill='#1a2b45'>ekzotermik katilma</text></svg>","steps":[{"t":"Kırılan","a":"1 C=C + 1 H–H","d":"Etende çift bağ açılır: 1×614 + 1×436 = 1050 kJ kırılan (C–H bağları korunur)."},{"t":"Oluşan","a":"1 C–C + 2 C–H","d":"Çift bağ tek bağa döner ve 2 yeni C–H kurulur: 1×348 + 2×413 = 348 + 826 = 1174 kJ oluşan."},{"t":"ΔH","a":"1050 − 1174 = −124","d":"ΔH = Σkırılan − Σoluşan = 1050 − 1174 = −124 kJ/mol."}],"ans":"ΔH = −124 kJ/mol; eten ile hidrojenin katılma tepkimesi ekzotermiktir."},
{"q":"2HBr → H₂ + Br₂ tepkimesinin ΔH'ını hesaplayın (H–Br=366, H–H=436, Br–Br=193 kJ/mol).","fig":"<svg viewBox='0 0 320 150'><text x='20' y='60' font-size='13' fill='#1a2b45'>2HBr</text><line x1='90' y1='55' x2='140' y2='55' stroke='#1a2b45' stroke-width='2'/><polygon points='140,55 132,51 132,59' fill='#1a2b45'/><text x='155' y='60' font-size='13' fill='#1a2b45'>H₂ + Br₂</text><text x='160' y='115' font-size='11' text-anchor='middle' fill='#1a2b45'>endotermik ayrisma</text></svg>","steps":[{"t":"Kırılan","a":"2 H–Br","d":"2 mol H–Br bağı kırılır: 2×366 = 732 kJ."},{"t":"Oluşan","a":"H–H + Br–Br","d":"1 H–H ve 1 Br–Br oluşur: 436 + 193 = 629 kJ."},{"t":"ΔH","a":"732 − 629 = +103","d":"ΔH = 732 − 629 = +103 kJ/mol; pozitif olduğundan endotermik."}],"ans":"ΔH = +103 kJ/mol; HBr'nin ayrışması endotermik bir tepkimedir."},
{"q":"C₂H₂ + 2H₂ → C₂H₆ tepkimesinin ΔH'ını bulun (C≡C=839, C–C=348, C–H=413, H–H=436 kJ/mol).","steps":[{"t":"Kırılan","a":"1 C≡C + 2 H–H","d":"Üçlü bağ ve 2 H–H kırılır: 1×839 + 2×436 = 839 + 872 = 1711 kJ (mevcut C–H'ler korunur)."},{"t":"Oluşan","a":"1 C–C + 4 C–H","d":"Üçlü bağ tek bağa döner, 4 yeni C–H kurulur: 1×348 + 4×413 = 348 + 1652 = 2000 kJ."},{"t":"ΔH","a":"1711 − 2000 = −289","d":"ΔH = 1711 − 2000 = −289 kJ/mol; güçlü ekzotermik."}],"ans":"ΔH = −289 kJ/mol; asetilenin hidrojenle doyurulması ekzotermiktir."},
{"q":"H₂ + F₂ → 2HF tepkimesinin ΔH'ını hesaplayın (H–H=436, F–F=159, H–F=567 kJ/mol).","fig":"<svg viewBox='0 0 320 150'><text x='20' y='60' font-size='13' fill='#1a2b45'>H₂ + F₂</text><line x1='110' y1='55' x2='160' y2='55' stroke='#1a2b45' stroke-width='2'/><polygon points='160,55 152,51 152,59' fill='#1a2b45'/><text x='175' y='60' font-size='13' fill='#1a2b45'>2HF</text><text x='160' y='115' font-size='11' text-anchor='middle' fill='#1a2b45'>guclu ekzotermik</text></svg>","steps":[{"t":"Kırılan","a":"H–H + F–F","d":"1 H–H ve 1 F–F kırılır: 436 + 159 = 595 kJ."},{"t":"Oluşan","a":"2 H–F","d":"2 mol H–F bağı oluşur: 2×567 = 1134 kJ."},{"t":"ΔH","a":"595 − 1134 = −539","d":"ΔH = 595 − 1134 = −539 kJ/mol; çok güçlü ekzotermik (zayıf F–F ve güçlü H–F nedeniyle)."}],"ans":"ΔH = −539 kJ/mol; HF oluşumu zayıf F–F ve çok güçlü H–F bağı nedeniyle güçlü ekzotermiktir."},
{"q":"Bağ enerjileriyle hesaplanan ΔH ile deneysel (kalorimetrik) ΔH arasında neden küçük farklar olur? Üç neden verin.","steps":[{"t":"Ortalama değerler","a":"yaklaşık","d":"Tablo bağ enerjileri çok molekülün ortalamasıdır, gerçek molekülde biraz farklıdır."},{"t":"Faz varsayımı","a":"gaz fazı","d":"Yöntem tüm türleri gaz kabul eder; sıvı/katı hal değişim enerjileri ihmal edilir."},{"t":"Rezonans/çevre","a":"ek etki","d":"Rezonans kararlılığı ve molekül içi etkileşimler tabloya tam yansımaz, küçük sapma oluşturur."}],"ans":"Tablo değerlerinin ortalama olması, gaz fazı varsayımı ve rezonans/çevre etkilerinin tam yansımaması nedeniyle hesaplanan ΔH deneysel değerden biraz sapar."}
]}}};
