globalThis.__OUT = {"mekanizma":{"ilkokul":{"kolay":[
{"q":"Bir tepkime tek bir anda mı olur, yoksa adım adım mı gerçekleşir?","steps":[{"t":"Tek anda değil","a":"adımlar var","d":"Çoğu tepkime tek seferde değil, küçük adımlar halinde olur."},{"t":"Sıra ile","a":"basamak basamak","d":"Tıpkı merdiven çıkar gibi tepkime basamak basamak ilerler."}],"ans":"Bir tepkime çoğu zaman tek anda değil, adım adım (basamaklar halinde) gerçekleşir."},
{"q":"Tepkimenin adım adım gerçekleşme sırasına ne ad verilir?","steps":[{"t":"Adımların sırası","a":"yol","d":"Tepkimenin hangi adımlardan geçtiğinin sırasıdır."},{"t":"Adı","a":"mekanizma","d":"Bu adım adım gerçekleşme yoluna tepkime mekanizması denir."}],"ans":"Tepkimenin adım adım gerçekleşme yoluna mekanizma denir."},
{"q":"Bir trende en yavaş vagon tüm trenin hızını belirler. Tepkimede de en yavaş adım neyi belirler?","fig":"<svg viewBox='0 0 320 130'><rect x='30' y='55' width='50' height='35' rx='5' fill='#2b6be0' stroke='#1a2b45'/><rect x='95' y='55' width='50' height='35' rx='5' fill='#e0552b' stroke='#1a2b45'/><rect x='160' y='55' width='50' height='35' rx='5' fill='#2b6be0' stroke='#1a2b45'/><circle cx='45' cy='95' r='6' fill='#1a2b45'/><circle cx='65' cy='95' r='6' fill='#1a2b45'/><circle cx='175' cy='95' r='6' fill='#1a2b45'/><circle cx='195' cy='95' r='6' fill='#1a2b45'/><circle cx='110' cy='95' r='6' fill='#1a2b45'/><circle cx='130' cy='95' r='6' fill='#1a2b45'/><text x='120' y='40' font-size='10' text-anchor='middle' fill='#1a2b45'>en yavaş vagon</text></svg>","steps":[{"t":"En yavaş adım","a":"frenler","d":"Adımlardan biri çok yavaşsa, tüm tepkime onun hızında ilerler."},{"t":"Sonuç","a":"toplam hız","d":"En yavaş adım tepkimenin toplam hızını belirler."}],"ans":"En yavaş adım, tüm tepkimenin hızını belirler."},
{"q":"Bir adımda oluşup hemen sonraki adımda kullanılan, sonunda kalmayan maddeye ne benzetebiliriz?","steps":[{"t":"Geçici madde","a":"ortada görünmez","d":"Bir adımda oluşan, sonraki adımda harcanan geçici bir madde vardır."},{"t":"Ara ürün","a":"sonunda yok","d":"Bu geçici maddeye ara ürün denir; tepkime bitince ortada kalmaz."}],"ans":"Bir adımda oluşup sonraki adımda harcanan geçici maddeye ara ürün denir; sonunda kalmaz."},
{"q":"Bir köprüyü inşa edip iş bitince geri toplayan vinç gibi, tepkimeye girip sonra geri çıkan yardımcı maddeye ne denir?","steps":[{"t":"Girip çıkar","a":"yardımcı","d":"Bu madde tepkimeye girer, yardım eder, sonra yeniden dışarı çıkar."},{"t":"Adı","a":"katalizör","d":"Girip sonra geri çıkan bu yardımcı maddeye katalizör denir."}],"ans":"Tepkimeye girip sonra geri çıkan yardımcı maddeye katalizör denir."}
],"zor":[
{"q":"Tepkime basamaklarından biri çok yavaş, biri çok hızlıysa tepkime ne kadar sürede biter?","steps":[{"t":"Yavaş belirleyici","a":"yavaş adım","d":"Tepkimenin toplam süresini en yavaş adım belirler."},{"t":"Sonuç","a":"yavaş adıma bağlı","d":"Hızlı adım ne kadar çabuk olursa olsun, yavaş adım bitmeden tepkime tamamlanmaz."}],"ans":"Tepkime, en yavaş basamağın süresince tamamlanır; hızlı adımlar bunu değiştirmez."},
{"q":"Ara ürün ile katalizör arasındaki en basit fark nedir?","steps":[{"t":"Ara ürün","a":"oluşur, tükenir","d":"Ara ürün önce bir adımda oluşur, sonra başka adımda harcanır."},{"t":"Katalizör","a":"girer, çıkar","d":"Katalizör ise önce tepkimeye girer, sonra geri çıkar; tükenmez."}],"ans":"Ara ürün önce oluşup sonra tükenir; katalizör ise önce girip sonra geri çıkar ve tükenmez."},
{"q":"Bir pasta yaparken hamuru karıştırmak çok hızlı, fırında pişirmek çok yavaşsa, pasta ne zaman hazır olur?","steps":[{"t":"En yavaş iş","a":"pişirme","d":"En yavaş adım fırında pişirmektir."},{"t":"Toplam süre","a":"pişirmeye bağlı","d":"Pasta, en yavaş adım olan pişirme tamamlanınca hazır olur."}],"ans":"Pasta, en yavaş adım olan pişirme bitince hazır olur; en yavaş adım toplam süreyi belirler."},
{"q":"Bir tepkime iki adımda olduğunda, ilk adımda çıkan ürün hemen ikinci adımda kullanılırsa bu maddeye ne denir?","steps":[{"t":"İlk adım ürünü","a":"hemen kullanılır","d":"İlk adımda oluşan madde beklemeden ikinci adımda harcanır."},{"t":"Ara ürün","a":"adı budur","d":"Bu şekilde oluşup hemen tüketilen maddeye ara ürün denir."}],"ans":"İlk adımda oluşup ikinci adımda hemen kullanılan bu maddeye ara ürün denir."},
{"q":"Tepkime mekanizmasını bilmek bize ne işe yarar?","steps":[{"t":"Adımları görme","a":"nasıl olduğu","d":"Mekanizma, tepkimenin hangi adımlarla gerçekleştiğini gösterir."},{"t":"Hızı anlama","a":"yavaş adım","d":"Hangi adımın yavaş olduğunu bilince tepkimeyi nasıl hızlandıracağımızı anlarız."}],"ans":"Mekanizmayı bilmek, tepkimenin nasıl olduğunu ve hangi adımı hızlandırırsak hızlanacağını anlamamızı sağlar."}
]},"ortaokul":{"kolay":[
{"q":"Tepkime mekanizması ne anlama gelir?","steps":[{"t":"Basamaklar","a":"adım adım","d":"Çoğu tepkime tek hamlede değil, birbirini izleyen küçük basamaklar halinde gerçekleşir."},{"t":"Tanım","a":"basamaklar dizisi","d":"Bu basamakların tamamına ve sırasına tepkime mekanizması denir."}],"ans":"Tepkime mekanizması, bir tepkimenin gerçekleştiği basamakların tamamı ve sırasıdır."},
{"q":"Hız belirleyen basamak hangisidir?","fig":"<svg viewBox='0 0 320 165'><rect x='40' y='110' width='50' height='40' fill='#2b6be0' stroke='#1a2b45'/><rect x='130' y='40' width='50' height='110' fill='#e0552b' stroke='#1a2b45'/><rect x='220' y='100' width='50' height='50' fill='#2b6be0' stroke='#1a2b45'/><text x='65' y='135' font-size='10' text-anchor='middle' fill='#fff'>hızlı</text><text x='155' y='95' font-size='10' text-anchor='middle' fill='#fff'>yavaş</text><text x='245' y='130' font-size='10' text-anchor='middle' fill='#fff'>hızlı</text></svg>","steps":[{"t":"En yavaş adım","a":"belirleyici","d":"Mekanizmadaki en yavaş basamak tüm tepkimenin hızını belirler."},{"t":"Adı","a":"hız belirleyen basamak","d":"Bu en yavaş basamağa hız belirleyen basamak denir."}],"ans":"Mekanizmadaki en yavaş basamak hız belirleyen basamaktır; tüm tepkimenin hızını o belirler."},
{"q":"Ara ürün nedir?","steps":[{"t":"Oluşma","a":"bir basamakta","d":"Ara ürün, bir basamakta oluşan bir maddedir."},{"t":"Tükenme","a":"sonraki basamakta","d":"Sonraki basamakta tükendiği için net tepkime denkleminde görünmez."}],"ans":"Ara ürün, bir basamakta oluşup sonraki basamakta tükenen ve net denklemde görünmeyen maddedir."},
{"q":"Katalizör mekanizmada nasıl davranır?","steps":[{"t":"Önce girer","a":"tepken gibi","d":"Katalizör ilk basamakta tepken olarak tepkimeye girer."},{"t":"Sonra çıkar","a":"geri kazanılır","d":"Sonraki basamakta tekrar açığa çıkar, böylece net olarak tükenmez."}],"ans":"Katalizör mekanizmada önce tepkimeye girer, sonra geri çıkar; net olarak tükenmez."},
{"q":"Neden en yavaş basamak tepkimenin toplam hızını belirler?","steps":[{"t":"Darboğaz","a":"en yavaş geçit","d":"En yavaş basamak bir darboğaz gibidir; tepkime bu adımdan daha hızlı ilerleyemez."},{"t":"Sonuç","a":"hız ona bağlı","d":"Hızlı basamaklar yavaş basamağı beklediği için toplam hız yavaş adıma bağlıdır."}],"ans":"En yavaş basamak bir darboğaz oluşturur; tepkime ondan hızlı ilerleyemediğinden toplam hızı o belirler."}
],"zor":[
{"q":"İki basamaklı bir tepkimede ilk basamak yavaşsa, hız hangi basamağa bağlıdır?","steps":[{"t":"Yavaş basamak","a":"ilk basamak","d":"İlk basamak yavaş olduğundan hız belirleyen basamak odur."},{"t":"Hız ifadesi","a":"yavaşa göre","d":"Tepkime hızı, hız belirleyen (yavaş) basamaktaki tepken derişimlerine bağlıdır."}],"ans":"İlk basamak yavaşsa hız ona bağlıdır; tepkime hızı yavaş (hız belirleyen) basamaktaki tepkenlere göre belirlenir."},
{"q":"Ara ürün ve katalizör net tepkime denkleminde neden ikisi de görünmez?","fig":"<svg viewBox='0 0 320 120'><text x='20' y='40' font-size='10' fill='#1a2b45'>1. A + K → AK</text><text x='20' y='65' font-size='10' fill='#1a2b45'>2. AK + B → C + K</text><line x1='15' y1='80' x2='200' y2='80' stroke='#1a2b45'/><text x='20' y='100' font-size='10' fill='#1a2b45'>net: A + B → C</text><text x='150' y='40' font-size='9' fill='#9ed9a8'>AK ara ürün</text><text x='200' y='65' font-size='9' fill='#e0552b'>K katalizör</text></svg>","steps":[{"t":"Ara ürün","a":"oluşup tükenir","d":"Ara ürün bir basamakta oluşup diğerinde harcandığından basamaklar toplanınca sadeleşir."},{"t":"Katalizör","a":"girip çıkar","d":"Katalizör de önce girip sonra çıktığından toplamda sadeleşir; ikisi de net denklemde yer almaz."}],"ans":"Ara ürün oluşup tükendiği, katalizör girip çıktığı için basamaklar toplandığında her ikisi de sadeleşir ve net denklemde görünmez."},
{"q":"Bir mekanizmada ilk basamak hızlı, ikinci basamak yavaşsa hangi basamak hız belirleyendir?","steps":[{"t":"Yavaş olan","a":"ikinci basamak","d":"Hız belirleyen basamak her zaman en yavaş olandır; burada ikinci basamak yavaştır."},{"t":"Sonuç","a":"ikinci belirler","d":"Bu nedenle tepkimenin hızını ikinci (yavaş) basamak belirler."}],"ans":"En yavaş olan ikinci basamak hız belirleyen basamaktır; tepkimenin hızını o belirler."},
{"q":"Tek basamakta gerçekleşen bir tepkime ile çok basamaklı tepkime arasındaki fark nedir?","steps":[{"t":"Tek basamak","a":"doğrudan","d":"Tek basamaklı (elementer) tepkimede tepkenler tek bir çarpışmada doğrudan ürüne dönüşür."},{"t":"Çok basamak","a":"ara türler var","d":"Çok basamaklıda araya ara ürünler girer ve birden çok adım vardır; bu adımların en yavaşı hızı belirler."}],"ans":"Tek basamaklı tepkime tek hamlede gerçekleşir; çok basamaklıda ise ara ürünler içeren birden çok adım bulunur ve en yavaş adım hızı belirler."},
{"q":"Mekanizmayı bilmek bir tepkimenin hızını artırmak için neden önemlidir?","steps":[{"t":"Yavaş adım hedef","a":"darboğazı bul","d":"Mekanizma sayesinde hangi basamağın hız belirleyen (yavaş) olduğu bulunur."},{"t":"Müdahale","a":"o adımı hızlandır","d":"Tepkimeyi hızlandırmak için doğru noktaya, yani yavaş adıma (örneğin katalizörle) müdahale edilir."}],"ans":"Mekanizma, hız belirleyen yavaş basamağı gösterir; tepkimeyi hızlandırmak için tam o adıma müdahale edileceğinden bilmek önemlidir."}
]},"lise":{"kolay":[
{"q":"Bir tepkime mekanizmasını oluşturan elementer basamaklar nedir?","steps":[{"t":"Elementer basamak","a":"tek adımda","d":"Elementer basamak, tek bir çarpışma veya olayla gerçekleşen, daha alt adıma bölünemeyen tepkime adımıdır."},{"t":"Mekanizma","a":"basamaklar dizisi","d":"Mekanizma, net tepkimeyi veren bu elementer basamakların ardışık dizisidir."}],"ans":"Mekanizma, net tepkimeyi veren ve her biri tek bir olayla gerçekleşen elementer basamakların ardışık dizisidir."},
{"q":"Hız belirleyen basamak tepkime hız ifadesini nasıl belirler?","steps":[{"t":"En yavaş basamak","a":"darboğaz","d":"Tepkime, en yavaş (hız belirleyen) basamaktan daha hızlı ilerleyemez."},{"t":"Hız ifadesi","a":"o basamağa göre","d":"Bu yüzden deneysel hız ifadesi, hız belirleyen basamaktaki tepkenlerin derişimlerine göre yazılır."}],"ans":"Hız belirleyen (en yavaş) basamak tepkimenin darboğazıdır; deneysel hız ifadesi bu basamağın tepken derişimlerine göre belirlenir."},
{"q":"Ara ürün ile katalizör mekanizmada nasıl ayırt edilir?","fig":"<svg viewBox='0 0 320 150'><line x1='30' y1='75' x2='290' y2='75' stroke='#1a2b45' stroke-width='2'/><polygon points='290,75 280,70 280,80' fill='#1a2b45'/><circle cx='110' cy='75' r='14' fill='#9ed9a8' stroke='#1a2b45'/><text x='110' y='79' font-size='9' text-anchor='middle' fill='#1a2b45'>ara</text><text x='110' y='45' font-size='8' text-anchor='middle' fill='#1a2b45'>oluşur-tükenir</text><circle cx='210' cy='75' r='14' fill='#e0552b' stroke='#1a2b45'/><text x='210' y='79' font-size='9' text-anchor='middle' fill='#fff'>kat</text><text x='210' y='45' font-size='8' text-anchor='middle' fill='#1a2b45'>girer-çıkar</text></svg>","steps":[{"t":"Ara ürün","a":"önce oluşur","d":"Ara ürün bir basamakta ürün olarak oluşur, sonraki basamakta tepken olarak tükenir."},{"t":"Katalizör","a":"önce girer","d":"Katalizör ise ilk basamakta tepken olarak girer, sonraki basamakta yeniden oluşur (geri kazanılır)."}],"ans":"Ara ürün önce oluşup sonra tükenir; katalizör önce tüketilip sonra geri kazanılır. İkisi de net denklemde görünmez ama ortaya çıkış sırası terstir."},
{"q":"Bir mekanizmanın geçerli kabul edilmesi için hangi koşulu sağlaması gerekir?","steps":[{"t":"Toplam = net","a":"basamaklar toplanır","d":"Elementer basamaklar toplandığında ara türler sadeleşip net (deneysel) tepkime denklemini vermelidir."},{"t":"Hız uyumu","a":"deneysel hız","d":"Ayrıca mekanizmadan türetilen hız ifadesi, deneyle bulunan hız ifadesiyle uyuşmalıdır."}],"ans":"Geçerli mekanizma, basamakları toplandığında net tepkimeyi vermeli ve türetilen hız ifadesi deneysel hız ifadesiyle uyuşmalıdır."},
{"q":"Moleküleritesi (basamağa giren tanecik sayısı) ile hız ifadesi arasındaki ilişki nedir?","steps":[{"t":"Moleküleriti","a":"giren tanecik","d":"Bir elementer basamağın moleküleritesi, o basamakta çarpışan tanecik sayısıdır (tek, çift, üçlü)."},{"t":"Üs = katsayı","a":"sadece elementerde","d":"Yalnızca elementer basamakta hız ifadesindeki üsler, tepken katsayılarına eşittir."}],"ans":"Elementer bir basamakta hız ifadesindeki derişim üsleri, basamağın moleküleritesini veren tepken katsayılarına eşittir; bu net tepkime için geçerli değildir."}
],"zor":[
{"q":"İki basamaklı bir mekanizmada birinci basamak yavaşsa hız ifadesi nasıl yazılır?","steps":[{"t":"Yavaş basamak","a":"hız belirleyen","d":"Birinci basamak yavaşsa hız belirleyen odur; hız bu basamaktaki tepken derişimlerine bağlıdır."},{"t":"Hız ifadesi","a":"yavaş basamaktan","d":"Örneğin yavaş basamak A + B → C ise hız = k·[A]·[B] şeklinde, yavaş basamağın tepkenlerine göre yazılır."}],"ans":"Birinci basamak yavaşsa hız belirleyen odur; hız ifadesi doğrudan o basamağın tepken derişimlerine göre (örn. hız = k·[A]·[B]) yazılır."},
{"q":"Hız belirleyen basamak ikinci basamaksa ve ara ürün içeriyorsa, hız ifadesindeki ara ürün derişimi nasıl yok edilir?","steps":[{"t":"Ön denge","a":"hızlı 1. basamak","d":"Hızlı birinci basamak dengede kabul edilir (ön denge yaklaşımı); ileri ve geri hızlar eşitlenir."},{"t":"Yerine koyma","a":"ara ürünü ifade et","d":"Bu eşitlikten ara ürün derişimi, başlangıç tepkenleri cinsinden çözülüp yavaş basamağın hız ifadesinde yerine konur."}],"ans":"Hızlı birinci basamak ön dengede kabul edilir; bu dengeden ara ürün derişimi tepkenler cinsinden bulunup yavaş basamağın hız ifadesinde yerine konarak ara ürün ifadeden çıkarılır."},
{"q":"Bir tepkimenin deneysel hız derecesi (mol sayısının) toplam denklem katsayılarına eşit olmayabilir; bunun nedeni mekanizma açısından nedir?","steps":[{"t":"Net denklem","a":"toplam reaksiyon","d":"Net denklem yalnızca başlangıç ve bitiş maddelerini gösterir, gerçek adımları göstermez."},{"t":"Hız belirleyen","a":"sadece yavaş adım","d":"Hız yalnızca hız belirleyen basamaktaki tanecik sayısına bağlı olduğundan, derece net denklem katsayılarıyla genelde örtüşmez."}],"ans":"Hız yalnızca hız belirleyen (yavaş) basamağa bağlı olduğundan, net denklemdeki toplam katsayılar gerçek adımları yansıtmaz; bu yüzden deneysel hız derecesi net denklem katsayılarına eşit olmayabilir."},
{"q":"Kararlı hal (steady-state) yaklaşımı bir mekanizmada ara ürün için neyi varsayar?","steps":[{"t":"Varsayım","a":"derişim sabit","d":"Kararlı hal yaklaşımında, tepken kısa süre sonra ara ürünün oluşma ve tükenme hızları eşitlenir, derişimi yaklaşık sabit kabul edilir."},{"t":"Net hız sıfır","a":"d[ara]/dt ≈ 0","d":"Ara ürünün net derişim değişimi sıfır alınarak (d[ara ürün]/dt ≈ 0) derişimi tepkenler cinsinden çözülür ve hız ifadesinden elenir."}],"ans":"Kararlı hal yaklaşımı, ara ürünün oluşma ve tükenme hızlarının eşitlenip derişiminin sabit (d[ara ürün]/dt ≈ 0) kaldığını varsayar; böylece ara ürün hız ifadesinden çıkarılır."},
{"q":"Bir katalizörlü tepkimede mekanizma incelendiğinde katalizörün varlığı net denkleme ve ΔH'ye neden yansımaz?","steps":[{"t":"Net denklemde yok","a":"girip çıkar","d":"Katalizör ilk basamakta girip son basamakta geri çıktığından, basamaklar toplanınca sadeleşir ve net denklemde görünmez."},{"t":"ΔH değişmez","a":"uç enerjiler aynı","d":"Mekanizma değişse de tepkenler ve ürünlerin enerji düzeyleri sabittir; katalizör yalnızca aktivasyon enerjisini düşürür, ΔH'yi değiştirmez."}],"ans":"Katalizör mekanizmada girip geri çıktığından net denklemde sadeleşir; ayrıca yalnızca aktivasyon enerjisini düşürüp tepken/ürün enerji düzeylerini değiştirmediğinden ΔH'ye de yansımaz."}
]}}};
