globalThis.__OUT = {"esitFarkli":{"ilkokul":{"kolay":[
{"q":"10 tane misket ile 10 tane balon aynı ağırlıkta mıdır?","steps":[{"t":"Sayı aynı","a":"ikisi de 10","d":"Misketler de balonlar da 10 tanedir; sayıları eşittir."},{"t":"Ağırlık farklı","a":"misket ağır","d":"Ama misket balondan çok daha ağırdır; aynı sayıda olsalar da ağırlıkları farklıdır."}],"ans":"Hayır; sayıları eşit olsa da misketler balonlardan daha ağırdır."},
{"q":"Aynı sayıda elma ve kiraz hangisi daha ağır gelir?","steps":[{"t":"Tek tane","a":"elma ağır","d":"Bir elma, bir kirazdan çok daha ağırdır."},{"t":"Aynı sayı","a":"elmalar ağır","d":"Aynı sayıda alsak bile elmalar toplamda daha ağır gelir."}],"ans":"Aynı sayıda olsalar da elmalar kirazlardan daha ağır gelir."},
{"q":"12 tane saçma tanesi ile 12 tane patlamış mısır eşit ağırlıkta mıdır?","fig":"<svg viewBox='0 0 320 150'><circle cx='90' cy='100' r='25' fill='#5b6b85' stroke='#1a2b45'/><text x='90' y='105' font-size='10' text-anchor='middle' fill='#fff'>ağır</text><circle cx='230' cy='100' r='25' fill='#f0e2b6' stroke='#1a2b45'/><text x='230' y='105' font-size='10' text-anchor='middle' fill='#1a2b45'>hafif</text><text x='90' y='40' font-size='10' text-anchor='middle' fill='#1a2b45'>12 saçma</text><text x='230' y='40' font-size='10' text-anchor='middle' fill='#1a2b45'>12 mısır</text></svg>","steps":[{"t":"Sayı aynı","a":"ikisi de 12","d":"Saçma da mısır da 12 tanedir; sayıları eşittir."},{"t":"Ağırlık farklı","a":"saçma ağır","d":"Saçma tanesi mısırdan çok daha ağır olduğundan toplam ağırlık eşit değildir."}],"ans":"Hayır; sayıları eşit olsa da 12 saçma, 12 mısırdan çok daha ağırdır."},
{"q":"Neden aynı sayıda iki farklı nesne farklı ağırlıkta olabilir?","steps":[{"t":"Tek nesne ağırlığı","a":"farklı","d":"Her nesnenin tek başına ağırlığı farklıdır."},{"t":"Toplam","a":"ağır olan baskın","d":"Sayı aynı olsa bile tek tane ağırlığı büyük olanın toplamı daha ağır olur."}],"ans":"Çünkü her nesnenin tek başına ağırlığı farklıdır; sayı aynı olsa da ağır olanın toplamı daha ağır gelir."},
{"q":"Terazinin bir kefesine 5 ceviz, diğerine 5 fındık koyarsak ne olur?","steps":[{"t":"Sayı eşit","a":"5 ve 5","d":"İki kefede de 5'er tane vardır; sayılar eşittir."},{"t":"Ceviz ağır","a":"o kefe iner","d":"Ceviz fındıktan ağır olduğundan cevizli kefe aşağı iner."}],"ans":"Sayıları eşit olsa da ceviz daha ağır olduğundan cevizli kefe aşağı iner."}
],"zor":[
{"q":"12 tane oyun hamuru topu ile 12 tane demir bilye karşılaştırılırsa hangisi ağır olur, neden?","steps":[{"t":"Sayı eşit","a":"ikisi de 12","d":"Hamur topları da demir bilyeler de 12 tanedir."},{"t":"Madde farkı","a":"demir ağır","d":"Demir, oyun hamurundan daha ağır bir maddedir; bu yüzden 12 demir bilye toplamda daha ağır gelir."}],"ans":"12 demir bilye daha ağırdır; çünkü demir, oyun hamurundan daha ağır bir maddedir."},
{"q":"Aynı sayıda farklı nesnenin ağırlığını eşitlemek için ne yapmak gerekir?","steps":[{"t":"Eşit değil","a":"sayı yetmiyor","d":"Sayıyı eşit tutmak ağırlığı eşitlemez, çünkü tek tane ağırlıkları farklıdır."},{"t":"Sayı ayarı","a":"hafif olandan çok","d":"Ağırlıkları eşitlemek için hafif olan nesneden daha çok almak gerekir."}],"ans":"Ağırlığı eşitlemek için hafif olan nesneden daha fazla sayıda almak gerekir; sadece sayıyı eşitlemek yetmez."},
{"q":"Bir poşet pamuk ile aynı sayıda demir vidayı taşımak neden farklıdır?","fig":"<svg viewBox='0 0 320 150'><circle cx='90' cy='80' r='30' fill='#eef2f8' stroke='#1a2b45'/><text x='90' y='85' font-size='10' text-anchor='middle' fill='#1a2b45'>pamuk</text><rect x='200' y='60' width='50' height='40' fill='#5b6b85' stroke='#1a2b45'/><text x='225' y='85' font-size='10' text-anchor='middle' fill='#fff'>vida</text><text x='90' y='130' font-size='10' text-anchor='middle' fill='#1a2b45'>hafif</text><text x='225' y='130' font-size='10' text-anchor='middle' fill='#1a2b45'>ağır</text></svg>","steps":[{"t":"Sayı aynı","a":"eşit adet","d":"Pamuk parçaları ve vidalar aynı sayıda olabilir."},{"t":"Ağırlık çok farklı","a":"vida ağır","d":"Demir vidalar pamuktan çok daha ağır olduğundan, taşımak çok daha güçtür."}],"ans":"Aynı sayıda olsalar da demir vidalar pamuktan çok daha ağır olduğundan taşımak çok daha zordur."},
{"q":"Annene yardım ederken 10 tane patates mi yoksa 10 tane limon mu taşımak daha kolaydır?","steps":[{"t":"Sayı eşit","a":"10 ve 10","d":"İkisi de 10 tanedir; sayıları aynıdır."},{"t":"Limon hafif","a":"daha kolay","d":"Limon patatesten daha hafif olduğundan 10 limon taşımak daha kolaydır."}],"ans":"10 limon taşımak daha kolaydır; çünkü limon patatesten daha hafiftir, sayıları eşit olsa bile."},
{"q":"Bir kutuya sığan ceviz sayısı ile fındık sayısı neden farklı olabilir?","steps":[{"t":"Boyut farkı","a":"fındık küçük","d":"Fındık cevizden daha küçüktür, bu yüzden aynı kutuya daha çok fındık sığar."},{"t":"Sayı-kütle","a":"farklı dolar","d":"Aynı kutu daha çok fındık alsa bile, her birinin ağırlığı farklı olduğundan toplam ağırlıkları da farklıdır."}],"ans":"Fındık daha küçük olduğundan kutuya daha çok sığar; nesnelerin boyut ve ağırlığı farklı olduğundan sayıları ve toplam ağırlıkları farklı olur."}
]},"ortaokul":{"kolay":[
{"q":"Aynı sayıda hidrojen atomu ile oksijen atomu eşit kütlede midir?","steps":[{"t":"Sayı aynı","a":"eşit adet","d":"Örneğin 100 hidrojen ve 100 oksijen atomu sayıca eşittir."},{"t":"Kütle farklı","a":"oksijen ağır","d":"Bir oksijen atomu bir hidrojen atomundan çok daha ağırdır; bu yüzden kütleleri eşit olmaz."}],"ans":"Hayır; aynı sayıda olsalar da oksijen atomları hidrojen atomlarından daha ağır olduğu için kütleleri farklıdır."},
{"q":"Atomların kütlesinin farklı olmasının nedeni nedir?","steps":[{"t":"Tanecik içeriği","a":"proton-nötron","d":"Atomun kütlesi büyük ölçüde içindeki proton ve nötron sayısına bağlıdır."},{"t":"Element farkı","a":"farklı atom = farklı kütle","d":"Farklı elementlerin atomlarında farklı sayıda proton ve nötron bulunur, bu yüzden kütleleri farklıdır."}],"ans":"Atomların kütlesi içindeki proton ve nötron sayısına bağlıdır; farklı elementlerde bu sayılar farklı olduğundan atom kütleleri de farklıdır."},
{"q":"12 karbon atomu ile 12 oksijen atomundan hangisinin toplam kütlesi daha büyüktür?","fig":"<svg viewBox='0 0 320 150'><circle cx='90' cy='80' r='28' fill='#33415588' stroke='#1a2b45'/><text x='90' y='85' font-size='12' text-anchor='middle' fill='#fff'>C</text><circle cx='230' cy='80' r='32' fill='#e0552b' stroke='#1a2b45'/><text x='230' y='85' font-size='12' text-anchor='middle' fill='#fff'>O</text><text x='90' y='130' font-size='10' text-anchor='middle' fill='#1a2b45'>12 (kütle 12)</text><text x='230' y='130' font-size='10' text-anchor='middle' fill='#1a2b45'>16 (kütle 16)</text></svg>","steps":[{"t":"Atom kütleleri","a":"C=12, O=16","d":"Bir karbon atomunun kütlesi 12, bir oksijen atomunun kütlesi 16 birimdir."},{"t":"Sayı eşit, kütle farklı","a":"oksijen ağır","d":"Sayıları eşit (12'şer) olsa da her oksijen daha ağır olduğundan toplam kütlesi daha büyüktür."}],"ans":"12 oksijen atomunun toplam kütlesi daha büyüktür; çünkü oksijen atomu karbon atomundan daha ağırdır."},
{"q":"Aynı kütlede karbon ve oksijen alırsak atom sayıları eşit olur mu?","steps":[{"t":"Hafif olandan çok","a":"karbon fazla","d":"Karbon atomu daha hafif olduğundan, aynı kütleyi oluşturmak için daha çok karbon atomu gerekir."},{"t":"Sonuç","a":"sayılar farklı","d":"Bu yüzden eşit kütledeki karbonda, oksijene göre daha fazla atom bulunur; sayılar eşit olmaz."}],"ans":"Hayır; karbon daha hafif olduğundan aynı kütlede karbonda oksijenden daha çok atom bulunur, atom sayıları eşit olmaz."},
{"q":"Eşit sayıda farklı atomun kütlesinin farklı olması bize molar kütle hakkında ne sezdirir?","steps":[{"t":"Atom başına kütle","a":"elemente özgü","d":"Her elementin atomunun kendine özgü bir kütlesi vardır."},{"t":"Mol kütlesi","a":"farklı g/mol","d":"Aynı sayıda (1 mol) atom alsak bile her elementin kütlesi farklı çıkar; buna molar kütle denir."}],"ans":"Eşit sayıda farklı atomun farklı kütlede olması, her elementin 1 molünün farklı kütleye (molar kütleye) sahip olduğunu sezdirir."}
],"zor":[
{"q":"1 mol hidrojen atomu ile 1 mol oksijen atomu aynı sayıda tanecik içerdiği halde neden farklı kütlededir?","steps":[{"t":"Sayı eşit","a":"6,02·10²³ tane","d":"Her ikisi de 1 mol olduğundan aynı sayıda (6,02·10²³) atom içerir."},{"t":"Atom kütlesi farklı","a":"H=1, O=16 g/mol","d":"Bir oksijen atomu bir hidrojen atomundan 16 kat ağır olduğundan, 1 mol oksijen 16 g, 1 mol hidrojen 1 g gelir."}],"ans":"İkisi de eşit sayıda (6,02·10²³) atom içerir ama oksijen atomu hidrojenden ağır olduğundan, 1 mol oksijen 16 g, 1 mol hidrojen 1 g'dır; sayı eşit, kütle farklıdır."},
{"q":"Aynı kütlede (örneğin 12 g) karbon ve magnezyum alındığında hangisinde daha çok atom bulunur?","steps":[{"t":"Atom kütleleri","a":"C=12, Mg=24","d":"Karbonun atom kütlesi 12, magnezyumunki 24 g/mol'dür; magnezyum atomu daha ağırdır."},{"t":"Mol karşılaştır","a":"12 g C = 1 mol, 12 g Mg = 0,5 mol","d":"12 g karbon 1 mol (6,02·10²³ atom), 12 g magnezyum yalnızca 0,5 mol (3,01·10²³ atom) eder."}],"ans":"Aynı 12 g kütlede karbonda daha çok atom bulunur; çünkü karbon atomu daha hafif olduğundan aynı kütle daha fazla (iki kat) atom içerir."},
{"q":"Bir tepkimede 'aynı sayıda atom' ile 'aynı kütlede madde' kavramlarını karıştırmak neden hataya yol açar?","fig":"<svg viewBox='0 0 320 150'><circle cx='70' cy='70' r='14' fill='#cfd8e8' stroke='#1a2b45'/><text x='70' y='75' font-size='9' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='110' cy='70' r='14' fill='#cfd8e8' stroke='#1a2b45'/><text x='110' y='75' font-size='9' text-anchor='middle' fill='#1a2b45'>H</text><circle cx='220' cy='70' r='24' fill='#e0552b' stroke='#1a2b45'/><text x='220' y='75' font-size='10' text-anchor='middle' fill='#fff'>O</text><circle cx='265' cy='70' r='24' fill='#e0552b' stroke='#1a2b45'/><text x='265' y='75' font-size='10' text-anchor='middle' fill='#fff'>O</text><text x='90' y='120' font-size='9' text-anchor='middle' fill='#1a2b45'>2 H (kütle 2)</text><text x='242' y='120' font-size='9' text-anchor='middle' fill='#1a2b45'>2 O (kütle 32)</text></svg>","steps":[{"t":"Sayı ≠ kütle","a":"farklı kavram","d":"Atom sayısı tanecik adedini, kütle ise toplam ağırlığı belirtir; bu ikisi farklı atomlarda eşit olmaz."},{"t":"Stokiyometri etkisi","a":"mol oranı önemli","d":"Tepkimeler atom/mol sayısı oranıyla yürür; kütleyi sayı sanmak mol oranını ve hesabı yanlış yapar."}],"ans":"Atom sayısı (adet) ile kütle (ağırlık) farklı kavramlardır; farklı atomlarda eşit sayı eşit kütle demek değildir. Tepkimeler mol/atom oranıyla yürüdüğünden, kütleyi sayı gibi kullanmak stokiyometri hesabını yanlış yapar."},
{"q":"6,02·10²³ tane demir atomu 56 g, aynı sayıda kükürt atomu 32 g geliyorsa bu fark neden kaynaklanır?","steps":[{"t":"Sayı eşit","a":"1'er mol","d":"Her ikisi de 6,02·10²³ tane, yani 1'er mol atom içerir."},{"t":"Atom kütlesi","a":"Fe=56, S=32","d":"Demir atomu 56, kükürt atomu 32 birim kütleye sahiptir; demir atomu daha ağırdır."},{"t":"Sonuç","a":"56 g > 32 g","d":"Aynı sayıda atom olsa da demir atomu ağır olduğundan toplam kütlesi (56 g) kükürtten (32 g) büyüktür."}],"ans":"İkisi de 1 mol (6,02·10²³ atom) olmasına rağmen demir atomu kükürt atomundan ağır olduğundan, demirin molar kütlesi 56 g, kükürdünki 32 g'dır; fark atom kütlelerinden kaynaklanır."},
{"q":"Molar kütle kavramı, 'eşit sayıda farklı atom farklı kütlededir' gerçeğiyle nasıl ilişkilidir?","steps":[{"t":"Gözlem","a":"sayı eşit, kütle farklı","d":"Eşit sayıda farklı atomun farklı kütlede olması, her atomun kendine özgü bir kütlesi olmasından kaynaklanır."},{"t":"Molar kütle tanımı","a":"1 molün kütlesi","d":"Molar kütle, 1 mol (6,02·10²³ tane) atomun gram cinsinden kütlesidir; her element için farklıdır ve atom kütlesine eşit sayıdadır."}],"ans":"Eşit sayıda farklı atomun farklı kütlede olması, her elementin atomunun farklı kütlesi olmasından gelir; molar kütle de bu gerçeği niceler: her elementin 1 molünün (eşit sayıda atomun) kütlesi farklıdır ve atom kütlesine eşit sayıyı g cinsinden verir."}
]},"lise":{"kolay":[
{"q":"Eşit sayıda farklı atomun farklı kütlede olmasının temel nedeni nedir?","steps":[{"t":"Atom kütlesi","a":"proton + nötron","d":"Bir atomun kütlesi çekirdeğindeki proton ve nötron sayısına bağlıdır; elektronun katkısı ihmal edilir."},{"t":"Elemente özgü","a":"farklı çekirdek","d":"Farklı elementlerin çekirdeklerinde farklı sayıda nükleon bulunur, bu yüzden atom kütleleri ve eşit sayıdaki kütleleri farklıdır."}],"ans":"Atom kütlesi çekirdekteki proton ve nötron sayısına bağlıdır; farklı elementlerde bu sayı farklı olduğundan, eşit sayıda atom alınsa bile kütleleri farklı olur."},
{"q":"Molar kütle nedir ve neden her element için farklıdır?","steps":[{"t":"Tanım","a":"1 molün g kütlesi","d":"Molar kütle, 1 mol (6,02·10²³ tane) taneciğin gram cinsinden kütlesidir; birimi g/mol'dür."},{"t":"Element farkı","a":"atom kütlesine bağlı","d":"Atom kütleleri elementten elemente değiştiğinden, eşit sayıdaki (1 mol) atomun kütlesi de farklıdır."}],"ans":"Molar kütle, 1 moldeki taneciklerin gram cinsinden kütlesidir (g/mol); atom kütleleri elemente özgü olduğundan her element için farklı bir değer alır."},
{"q":"1 mol H atomu 1 g, 1 mol C atomu 12 g geliyorsa atom sayıları arasında nasıl bir ilişki vardır?","steps":[{"t":"Sayı eşit","a":"6,02·10²³","d":"Her ikisi de 1 mol olduğundan eşit sayıda (6,02·10²³) atom içerir."},{"t":"Kütle oranı","a":"12 kat","d":"Karbon atomu hidrojenden 12 kat ağır olduğundan, eşit sayıda olmalarına rağmen karbonun kütlesi 12 katıdır."}],"ans":"Atom sayıları eşittir (her biri 6,02·10²³); kütle farkı yalnızca karbon atomunun hidrojenden 12 kat ağır olmasından kaynaklanır."},
{"q":"4 g hidrojen (H, 1 g/mol) ile 4 g helyum (He, 4 g/mol) örneklerinden hangisi daha çok atom içerir?","steps":[{"t":"Mol hesabı","a":"mol = kütle / molar kütle","d":"4 g H = 4 / 1 = 4 mol; 4 g He = 4 / 4 = 1 mol."},{"t":"Atom sayısı","a":"H daha çok","d":"4 mol hidrojen, 1 mol helyumdan dört kat fazla atom içerir."}],"ans":"4 g hidrojen daha çok atom içerir; çünkü hidrojen atomu daha hafif olduğundan aynı kütle (4 g) dört kat fazla (4 mol) atom barındırır."},
{"q":"Neden iki maddenin kütlesi eşit olduğu halde mol sayıları (tanecik sayıları) farklı olabilir?","steps":[{"t":"Molar kütle farkı","a":"g/mol farklı","d":"Her maddenin molar kütlesi farklı olduğundan, aynı kütle farklı sayıda mole karşılık gelir."},{"t":"Mol = kütle / molar kütle","a":"ters orantı","d":"Eşit kütlede molar kütlesi küçük olan madde daha çok mol (daha çok tanecik) içerir."}],"ans":"Maddelerin molar kütleleri farklı olduğundan, eşit kütle farklı mol sayısına karşılık gelir; molar kütlesi küçük olan madde aynı kütlede daha çok tanecik içerir."}
],"zor":[
{"q":"Eşit sayıda farklı atomun farklı kütlede olması gerçeği, mol ve molar kütle kavramlarının doğmasını nasıl gerektirmiştir?","steps":[{"t":"Sorun","a":"sayı-kütle ayrımı","d":"Tanecikler sayılamadığından kütleyle çalışılır; ama eşit sayıda farklı atom farklı kütlede olduğu için kütle tek başına tanecik sayısını vermez."},{"t":"Çözüm","a":"mol + molar kütle","d":"Mol, sabit tanecik sayısını (6,02·10²³) tanımlar; molar kütle ise her elementin 1 molünün kütlesini verir, böylece kütleden tanecik sayısına geçilir."}],"ans":"Eşit sayıda farklı atom farklı kütlede olduğundan kütle, tanecik sayısını doğrudan vermez; bu sorunu çözmek için sabit tanecik sayısını tanımlayan mol ve her elementin 1 molünün kütlesini veren molar kütle kavramları geliştirilmiştir."},
{"q":"32 g oksijen gazı (O₂, 32 g/mol) ile 32 g metan (CH₄, 16 g/mol) örneklerinin molekül sayılarını karşılaştırınız.","steps":[{"t":"Mol O₂","a":"32 / 32 = 1 mol","d":"O₂'nin molar kütlesi 32 g/mol olduğundan 32 g, 1 mol O₂ eder."},{"t":"Mol CH₄","a":"32 / 16 = 2 mol","d":"CH₄'ün molar kütlesi 16 g/mol olduğundan 32 g, 2 mol CH₄ eder."},{"t":"Molekül sayısı","a":"CH₄ iki kat","d":"2 mol CH₄, 1 mol O₂'nin iki katı kadar molekül (2 × 6,02·10²³) içerir."}],"ans":"Eşit kütlede (32 g) olmalarına rağmen metan iki kat fazla molekül içerir; çünkü CH₄'ün molar kütlesi (16 g/mol) oksijenin (32 g/mol) yarısıdır, dolayısıyla aynı kütle iki kat mol verir."},
{"q":"1 mol Mg (24 g/mol) atomu ile 1 mol O (16 g/mol) atomunun kütlelerini ve atom sayılarını karşılaştırınız.","steps":[{"t":"Atom sayısı","a":"eşit: 6,02·10²³","d":"Her ikisi de 1 mol olduğundan eşit sayıda (6,02·10²³) atom içerir."},{"t":"Kütle","a":"Mg 24 g, O 16 g","d":"Magnezyum atomu daha ağır olduğundan 1 mol Mg 24 g, 1 mol O 16 g gelir."},{"t":"Yorum","a":"sayı eşit, kütle farklı","d":"Bu, 'eşit sayı eşit kütle demek değildir' ilkesinin somut örneğidir: aynı tanecik sayısı, farklı toplam kütle verir."}],"ans":"İkisi de 6,02·10²³ atom (eşit sayıda) içerir, ancak magnezyum atomu ağır olduğundan 1 mol Mg 24 g, 1 mol O 16 g gelir; eşit sayı eşit kütle anlamına gelmez."},
{"q":"Eşit hacimde (NK) iki farklı gaz aynı sayıda molekül içerdiği halde neden farklı kütlede olabilir?","fig":"<svg viewBox='0 0 320 155'><rect x='35' y='35' width='90' height='90' rx='6' fill='none' stroke='#1a2b45'/><circle cx='60' cy='65' r='6' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='95' cy='80' r='6' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='70' cy='100' r='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='80' y='145' font-size='10' text-anchor='middle' fill='#1a2b45'>H₂ (hafif)</text><rect x='195' y='35' width='90' height='90' rx='6' fill='none' stroke='#1a2b45'/><circle cx='220' cy='65' r='9' fill='#e0552b' stroke='#1a2b45'/><circle cx='255' cy='80' r='9' fill='#e0552b' stroke='#1a2b45'/><circle cx='230' cy='100' r='9' fill='#e0552b' stroke='#1a2b45'/><text x='240' y='145' font-size='10' text-anchor='middle' fill='#1a2b45'>O₂ (ağır)</text></svg>","steps":[{"t":"Avogadro ilkesi","a":"eşit hacim = eşit molekül","d":"NK'de eşit hacimdeki gazlar eşit sayıda molekül içerir (Avogadro hipotezi)."},{"t":"Molar kütle farkı","a":"O₂ ağır","d":"Molekül sayısı eşit olsa da O₂ (32 g/mol) molekülü H₂ (2 g/mol) molekülünden ağır olduğundan, eşit hacim O₂ daha kütlelidir."}],"ans":"NK'de eşit hacimdeki gazlar eşit sayıda molekül içerir; ancak molekül kütleleri (molar kütleleri) farklı olduğundan, eşit sayıda molekül farklı toplam kütle verir, örneğin O₂ örneği H₂'den ağır olur."},
{"q":"Bir öğrenci 'eşit sayıda atom her zaman eşit kütle demektir' diyor. Bu yargıyı bir hesapla çürütünüz.","steps":[{"t":"Örnek seç","a":"1 mol Na, 1 mol Ca","d":"1 mol sodyum ve 1 mol kalsiyum alalım; her ikisi de 6,02·10²³ atom (eşit sayıda) içerir."},{"t":"Kütleleri bul","a":"Na 23 g, Ca 40 g","d":"Molar kütleler Na = 23 g/mol, Ca = 40 g/mol olduğundan kütleleri 23 g ve 40 g çıkar."},{"t":"Sonuç","a":"23 g ≠ 40 g","d":"Eşit sayıda atom olmasına rağmen kütleler farklıdır; yargı yanlıştır."}],"ans":"Yargı yanlıştır: 1 mol Na ve 1 mol Ca eşit sayıda (6,02·10²³) atom içerir ama kütleleri sırasıyla 23 g ve 40 g'dır; eşit sayıda atom eşit kütle anlamına gelmez, kütle atomun molar kütlesine bağlıdır."}
]}}};
