globalThis.__OUT = {"denklemDenklestirme":{"ilkokul":{"kolay":[
{"q":"Bir kimyasal değişimde maddenin toplam kütlesi değişir mi?","steps":[{"t":"Atomlar yok olmaz","a":"sayı korunur","d":"Tepkimede atomlar sadece yer değiştirir; hiçbiri yok olmaz, yeni atom da oluşmaz."},{"t":"Kütle aynı kalır","a":"korunur","d":"Atom sayısı değişmediği için başlangıç ve sonuç kütlesi birbirine eşit kalır."}],"ans":"Kimyasal değişimde toplam kütle korunur, yani aynı kalır."},
{"q":"İki hidrojen tanesi (H₂) ve bir oksijen tanesi (O₂) su (H₂O) oluşturuyor. Sağda ve solda atomların sayısı neden eşit olmalı?","steps":[{"t":"Atomlar kaybolmaz","a":"hepsi geçer","d":"Sol taraftaki her atom sağ tarafta da bulunmalıdır; hiçbiri kaybolmaz."},{"t":"Denge kuralı","a":"eşit sayı","d":"Bu yüzden her atomdan iki tarafta eşit sayıda olacak şekilde sayılar ayarlanır."}],"ans":"Atomlar kaybolmadığı için her atomdan iki tarafta eşit sayıda bulunması gerekir."},
{"q":"Bir mum yandığında kütlesi azalır gibi görünür. Aslında kütle nereye gider?","steps":[{"t":"Gaz oluşur","a":"havaya karışır","d":"Mum yanınca su buharı ve karbondioksit gazı oluşur ve bunlar havaya karışıp uçar."},{"t":"Kütle korunur","a":"yok olmaz","d":"Uçan gazların kütlesini de sayarsak toplam kütle yine aynı kalır, yok olmamıştır."}],"ans":"Mumun azalan kütlesi gaz olarak havaya karışır; toplam kütle yine korunur."},
{"q":"Kapalı bir kapta tepkime olursa kütle artar mı, azalır mı, aynı mı kalır?","steps":[{"t":"Kapalı kap","a":"hiçbir şey çıkmaz","d":"Kap kapalı olduğu için içeriden dışarıya hiçbir madde çıkamaz, dışarıdan da giremez."},{"t":"Sonuç","a":"aynı kalır","d":"Madde girip çıkmadığı için tepkime sonrası toplam kütle başlangıçtaki kadardır."}],"ans":"Kapalı kapta tepkime sonrası toplam kütle aynı kalır (değişmez)."},
{"q":"Denklemi denkleştirmek için atomların sayısını değiştirmek yerine ne yaparız?","fig":"<svg viewBox='0 0 320 120'><text x='30' y='45' font-size='16' fill='#1a2b45'>2 H₂</text><text x='80' y='45' font-size='16' fill='#1a2b45'>+</text><text x='105' y='45' font-size='16' fill='#1a2b45'>O₂</text><text x='150' y='45' font-size='18' fill='#e0552b'>→</text><text x='185' y='45' font-size='16' fill='#1a2b45'>2 H₂O</text><text x='160' y='95' font-size='11' text-anchor='middle' fill='#5b6b85'>öndeki büyük sayı: katsayı</text></svg>","steps":[{"t":"Formül değişmez","a":"H₂O aynı kalır","d":"Maddenin formülünü (örneğin H₂O) değiştiremeyiz, yoksa madde başka madde olur."},{"t":"Katsayı yazılır","a":"önüne sayı","d":"Onun yerine formülün önüne büyük bir sayı (katsayı) yazarak tane sayısını ayarlarız."}],"ans":"Formülü değiştirmeyiz; formülün önüne katsayı (büyük sayı) yazarak sayıları ayarlarız."}
],"zor":[
{"q":"2 H₂ + O₂ → 2 H₂O tepkimesinde sol ve sağda kaç hidrojen atomu vardır?","steps":[{"t":"Soldaki H","a":"4 tane","d":"2 H₂ demek 2·2 = 4 hidrojen atomu demektir."},{"t":"Sağdaki H","a":"4 tane","d":"2 H₂O demek 2·2 = 4 hidrojen atomu demektir; iki taraf da 4'tür, denktir."}],"ans":"Hem solda hem sağda 4 hidrojen atomu vardır; denklem denktir."},
{"q":"2 H₂ + O₂ → 2 H₂O tepkimesinde sol ve sağda kaç oksijen atomu vardır?","steps":[{"t":"Soldaki O","a":"2 tane","d":"O₂ bir tane olduğu için 2 oksijen atomu içerir."},{"t":"Sağdaki O","a":"2 tane","d":"2 H₂O içinde 2·1 = 2 oksijen atomu vardır; iki taraf eşit, denktir."}],"ans":"Hem solda hem sağda 2 oksijen atomu vardır; denklem denktir."},
{"q":"2 Na + Cl₂ → 2 NaCl tepkimesinde sodyum (Na) atomları iki tarafta eşit midir?","steps":[{"t":"Soldaki Na","a":"2 tane","d":"2 Na ifadesi 2 sodyum atomu demektir."},{"t":"Sağdaki Na","a":"2 tane","d":"2 NaCl içinde 2 sodyum atomu bulunur; iki taraf eşittir."}],"ans":"Solda 2, sağda 2 sodyum atomu vardır; eşittir, denklem denktir."},
{"q":"Bir tepkimede solda toplam 10 atom varsa, sağda kaç atom olmalıdır?","fig":"<svg viewBox='0 0 320 110'><rect x='25' y='35' width='90' height='40' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='70' y='60' font-size='13' text-anchor='middle' fill='#1a2b45'>sol: 10</text><text x='150' y='60' font-size='18' fill='#e0552b'>→</text><rect x='195' y='35' width='90' height='40' rx='6' fill='#cfd8e8' stroke='#1a2b45'/><text x='240' y='60' font-size='13' text-anchor='middle' fill='#1a2b45'>sağ: 10</text></svg>","steps":[{"t":"Kütle korunumu","a":"atom korunur","d":"Atomlar tepkimede yok olmaz; soldaki tüm atomlar sağda da bulunur."},{"t":"Sonuç","a":"10 atom","d":"Solda 10 atom varsa sağda da tam 10 atom olmalıdır."}],"ans":"Sağda da tam 10 atom olmalıdır; atom sayısı korunur."},
{"q":"C + O₂ → CO₂ tepkimesi denk midir? Atomları sayarak gör.","steps":[{"t":"Karbon sayısı","a":"1 = 1","d":"Solda 1 karbon (C), sağda CO₂ içinde 1 karbon vardır; eşit."},{"t":"Oksijen sayısı","a":"2 = 2","d":"Solda O₂ ile 2 oksijen, sağda CO₂ içinde 2 oksijen vardır; eşit, denklem denktir."}],"ans":"Karbon 1=1, oksijen 2=2 olduğu için C + O₂ → CO₂ denktir."}
]},"ortaokul":{"kolay":[
{"q":"Kütlenin korunumu yasası kimyasal denklem denkleştirmeyle nasıl bağlantılıdır?","steps":[{"t":"Yasa","a":"kütle korunur","d":"Kütlenin korunumu yasasına göre tepkimede atomlar ne yaratılır ne yok edilir."},{"t":"Denklik gereği","a":"atom eşitliği","d":"Bu yüzden denklemde her elementin atom sayısı girenlerde ve ürünlerde eşit olmalıdır; bunu sağlamak denkleştirmektir."}],"ans":"Kütle korunduğu için denklemde her atom türü iki tarafta eşitlenir; denkleştirmenin temeli budur."},
{"q":"H₂ + O₂ → H₂O denklemi neden denk değildir, nasıl denkleştirilir?","steps":[{"t":"Oksijeni say","a":"2 ≠ 1","d":"Solda O₂ ile 2 oksijen var, sağda H₂O içinde 1 oksijen var; eşit değil."},{"t":"Katsayı ekle","a":"2 H₂ + O₂ → 2 H₂O","d":"H₂O önüne 2, H₂ önüne 2 yazınca: H 4=4, O 2=2 olur ve denklem denkleşir."}],"ans":"Denk hâli 2 H₂ + O₂ → 2 H₂O'dur; böylece H 4=4 ve O 2=2 olur."},
{"q":"Denklem denkleştirirken maddenin alt indisini (örneğin H₂O'daki 2) değiştirebilir miyiz?","steps":[{"t":"Alt indis","a":"değiştirilemez","d":"Alt indis maddenin kimliğini belirler; değiştirirsek H₂O su olmaktan çıkar, başka madde olur."},{"t":"Doğru yol","a":"katsayı kullan","d":"Sayıları ayarlamak için sadece formülün önüne katsayı yazılır, alt indise dokunulmaz."}],"ans":"Hayır; alt indis değiştirilemez, sadece formülün önündeki katsayı ayarlanır."},
{"q":"2 Mg + O₂ → 2 MgO denkleminde magnezyum ve oksijeni sayarak denk olup olmadığını göster.","steps":[{"t":"Magnezyum","a":"2 = 2","d":"Solda 2 Mg, sağda 2 MgO içinde 2 magnezyum vardır; eşit."},{"t":"Oksijen","a":"2 = 2","d":"Solda O₂ ile 2 oksijen, sağda 2 MgO içinde 2 oksijen vardır; eşit, denklem denktir."}],"ans":"Mg 2=2 ve O 2=2 olduğundan 2 Mg + O₂ → 2 MgO denktir."},
{"q":"N₂ + 3 H₂ → 2 NH₃ tepkimesinde hidrojen atomları iki tarafta eşit midir?","fig":"<svg viewBox='0 0 320 110'><text x='25' y='50' font-size='15' fill='#1a2b45'>N₂ + 3H₂</text><text x='140' y='50' font-size='18' fill='#e0552b'>→</text><text x='180' y='50' font-size='15' fill='#1a2b45'>2NH₃</text><text x='160' y='90' font-size='11' text-anchor='middle' fill='#5b6b85'>H: 6 = 6, N: 2 = 2</text></svg>","steps":[{"t":"Soldaki H","a":"6 tane","d":"3 H₂ demek 3·2 = 6 hidrojen atomu demektir."},{"t":"Sağdaki H","a":"6 tane","d":"2 NH₃ içinde 2·3 = 6 hidrojen atomu vardır; iki taraf eşit."}],"ans":"Solda 6, sağda 6 hidrojen atomu vardır; eşittir, denklem denktir."}
],"zor":[
{"q":"CH₄ + O₂ → CO₂ + H₂O denklemini denkleştir.","steps":[{"t":"C ve H'yi dengele","a":"H için 2 H₂O","d":"1 karbon iki tarafta da var. CH₄'te 4 H olduğundan sağda 2 H₂O (4 H) gerekir."},{"t":"Oksijeni dengele","a":"2 O₂ ekle","d":"Sağda CO₂'de 2, 2 H₂O'da 2, toplam 4 oksijen var; solda 4 oksijen için 2 O₂ gerekir. Sonuç: CH₄ + 2 O₂ → CO₂ + 2 H₂O."}],"ans":"Denk hâli CH₄ + 2 O₂ → CO₂ + 2 H₂O'dur (C 1=1, H 4=4, O 4=4)."},
{"q":"Fe + O₂ → Fe₂O₃ denklemini denkleştir.","fig":"<svg viewBox='0 0 320 110'><text x='15' y='50' font-size='14' fill='#1a2b45'>4Fe + 3O₂</text><text x='135' y='50' font-size='18' fill='#e0552b'>→</text><text x='175' y='50' font-size='14' fill='#1a2b45'>2Fe₂O₃</text><text x='160' y='90' font-size='11' text-anchor='middle' fill='#5b6b85'>Fe: 4=4, O: 6=6</text></svg>","steps":[{"t":"Demir ve oksijeni eşitle","a":"2 Fe₂O₃","d":"Tek molekül oksijeni çift sayı yapmak için sağa 2 Fe₂O₃ yazılır; bu 4 Fe ve 6 O verir."},{"t":"Katsayıları tamamla","a":"4 Fe + 3 O₂","d":"4 demir için solda 4 Fe, 6 oksijen için 3 O₂ gerekir. Sonuç: 4 Fe + 3 O₂ → 2 Fe₂O₃."}],"ans":"Denk hâli 4 Fe + 3 O₂ → 2 Fe₂O₃'tür (Fe 4=4, O 6=6)."},
{"q":"Al + HCl → AlCl₃ + H₂ denklemini denkleştir.","steps":[{"t":"Klor ve hidrojeni dengele","a":"6 HCl, 2 AlCl₃","d":"Klor ve hidrojeni çift yapmak için: 2 AlCl₃ (6 Cl) ve solda 6 HCl (6 H, 6 Cl) alınır; H₂'yi 3 yapınca 6 H olur."},{"t":"Alüminyumu tamamla","a":"2 Al","d":"2 AlCl₃ için solda 2 Al gerekir. Sonuç: 2 Al + 6 HCl → 2 AlCl₃ + 3 H₂ (Al 2=2, H 6=6, Cl 6=6)."}],"ans":"Denk hâli 2 Al + 6 HCl → 2 AlCl₃ + 3 H₂'dir (Al 2=2, Cl 6=6, H 6=6)."},
{"q":"C₃H₈ + O₂ → CO₂ + H₂O (propan yanması) denklemini denkleştir.","steps":[{"t":"Karbon ve hidrojen","a":"3 CO₂, 4 H₂O","d":"3 karbon için 3 CO₂, 8 hidrojen için 4 H₂O (4·2=8 H) yazılır."},{"t":"Oksijeni dengele","a":"5 O₂","d":"Sağda 3·2 + 4·1 = 10 oksijen vardır; solda 10 oksijen için 5 O₂ gerekir. Sonuç: C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O."}],"ans":"Denk hâli C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O'dur (C 3=3, H 8=8, O 10=10)."},
{"q":"CaCO₃ → CaO + CO₂ denklemi neden katsayı eklemeden denktir?","steps":[{"t":"Atomları say","a":"Ca 1, C 1, O 3","d":"Solda CaCO₃: 1 kalsiyum, 1 karbon, 3 oksijen vardır."},{"t":"Sağı say","a":"Ca 1, C 1, O 3","d":"Sağda CaO (1 Ca, 1 O) + CO₂ (1 C, 2 O) toplam 1 Ca, 1 C, 3 O verir; tüm atomlar eşittir."}],"ans":"Ca 1=1, C 1=1, O 3=3 olduğundan CaCO₃ → CaO + CO₂ baştan denktir."}
]},"lise":{"kolay":[
{"q":"Kimyasal bir denklemi denkleştirmenin dayandığı temel ilke nedir?","steps":[{"t":"İlke","a":"kütlenin korunumu","d":"Lavoisier'in kütlenin korunumu yasasına göre kapalı sistemde atomlar yaratılamaz ve yok edilemez."},{"t":"Uygulama","a":"atom dengesi","d":"Bu nedenle her elementin atom sayısı girenler ve ürünlerde eşitlenir; yükler de korunur."}],"ans":"Denkleştirme, kütlenin korunumu yasasına dayanır; her elementin atom sayısı iki tarafta eşitlenir."},
{"q":"Denkleştirmede neden formüllerin alt indisleri değil, yalnızca katsayılar değiştirilir?","steps":[{"t":"Alt indisin anlamı","a":"madde kimliği","d":"Alt indis bileşiğin sabit bileşimini gösterir; değiştirmek bileşiği başka bir maddeye dönüştürür."},{"t":"Katsayının rolü","a":"mol/molekül sayısı","d":"Katsayı yalnızca o maddenin molekül (mol) sayısını gösterir; bunu değiştirmek madde kimliğini bozmaz."}],"ans":"Alt indis madde kimliğini belirlediğinden sabit kalır; yalnızca molekül sayısını veren katsayılar ayarlanır."},
{"q":"N₂ + H₂ ⇌ NH₃ (amonyak sentezi) denklemini denkleştir ve denge okunu açıkla.","steps":[{"t":"Katsayıları belirle","a":"N₂ + 3 H₂ ⇌ 2 NH₃","d":"2 N için 2 NH₃, 6 H için 3 H₂ gerekir; N 2=2, H 6=6 olur ve denklem denkleşir."},{"t":"Denge oku","a":"⇌","d":"Çift yönlü ok (⇌), tepkimenin tersinir olduğunu, ileri ve geri yönde aynı anda yürüyebildiğini gösterir."}],"ans":"Denk hâli N₂ + 3 H₂ ⇌ 2 NH₃'tür; ⇌ tepkimenin tersinir (denge) olduğunu belirtir."},
{"q":"Yarım (kesirli) katsayı kullanılarak ½ O₂ yazılan bir denklem nasıl tam sayılı hâle getirilir?","steps":[{"t":"Kesir sorunu","a":"½ O₂","d":"Örneğin H₂ + ½ O₂ → H₂O denktir ama termokimya dışında kesirli katsayı tercih edilmez."},{"t":"Tümünü çarp","a":"×2","d":"Tüm denklemi 2 ile çarpınca 2 H₂ + O₂ → 2 H₂O elde edilir; katsayılar en küçük tam sayı hâline gelir."}],"ans":"Denklemin tüm terimlerini ortak paydayla (örneğin 2 ile) çarparak kesirli katsayılar tam sayıya çevrilir."},
{"q":"Bir denklemin denk olup olmadığı nasıl kontrol edilir?","steps":[{"t":"Atom sayımı","a":"her element ayrı","d":"Her element için girenlerdeki ve ürünlerdeki atom sayısı (katsayı × alt indis) ayrı ayrı toplanır."},{"t":"Eşitlik testi","a":"iki taraf eşit","d":"Her element için iki tarafın toplamı eşitse ve yük korunuyorsa denklem denktir."}],"ans":"Her element için katsayı × alt indis toplamı iki tarafta eşitse (ve yük korunuyorsa) denklem denktir."}
],"zor":[
{"q":"C₂H₆ + O₂ → CO₂ + H₂O (etan yanması) denklemini denkleştir.","steps":[{"t":"C ve H'yi dengele","a":"2 CO₂, 3 H₂O","d":"2 karbon için 2 CO₂; 6 hidrojen için 3 H₂O (3·2=6 H) yazılır."},{"t":"Oksijeni dengele","a":"kesirden tam sayıya","d":"Sağda 2·2 + 3·1 = 7 oksijen var; solda 7/2 O₂ gerekir. Tüm denklemi 2 ile çarpınca: 2 C₂H₆ + 7 O₂ → 4 CO₂ + 6 H₂O olur (C 4=4, H 12=12, O 14=14)."}],"ans":"Denk hâli 2 C₂H₆ + 7 O₂ → 4 CO₂ + 6 H₂O'dur (C 4=4, H 12=12, O 14=14)."},
{"q":"İyon-elektron yöntemine gerek kalmadan, KClO₃ → KCl + O₂ ayrışma denklemini denkleştir.","steps":[{"t":"Oksijeni dengele","a":"ortak kat","d":"Solda KClO₃'te 3 oksijen (tek), sağda O₂'de 2 oksijen (çift) var; ortak kat 6'dır."},{"t":"Katsayıları belirle","a":"2 KClO₃ → 2 KCl + 3 O₂","d":"6 oksijen için solda 2 KClO₃, sağda 3 O₂ gerekir; bu da 2 K ve 2 Cl verir. K 2=2, Cl 2=2, O 6=6 olur."}],"ans":"Denk hâli 2 KClO₃ → 2 KCl + 3 O₂'dir (K 2=2, Cl 2=2, O 6=6)."},
{"q":"Fe₂O₃ + CO → Fe + CO₂ (demir indirgenmesi) denklemini denkleştir.","steps":[{"t":"Demiri dengele","a":"2 Fe","d":"Solda Fe₂O₃'te 2 demir var; sağa 2 Fe yazılır."},{"t":"Karbon ve oksijeni dengele","a":"3 CO, 3 CO₂","d":"Oksijen sayısını eşitlemek için 3 CO ve 3 CO₂ alınır: solda 3+3=6 O, sağda 3·2=6 O; C 3=3 olur. Sonuç: Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂."}],"ans":"Denk hâli Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂'dir (Fe 2=2, C 3=3, O 6=6)."},
{"q":"C₄H₁₀ + O₂ → CO₂ + H₂O (bütan yanması) denklemini denkleştir.","fig":"<svg viewBox='0 0 320 110'><text x='8' y='50' font-size='13' fill='#1a2b45'>2C₄H₁₀ + 13O₂</text><text x='150' y='50' font-size='17' fill='#e0552b'>→</text><text x='185' y='50' font-size='13' fill='#1a2b45'>8CO₂ + 10H₂O</text><text x='160' y='92' font-size='10' text-anchor='middle' fill='#5b6b85'>C:8=8, H:20=20, O:26=26</text></svg>","steps":[{"t":"C ve H'yi dengele","a":"4 CO₂, 5 H₂O","d":"Bir C₄H₁₀ için 4 CO₂ (4 C) ve 5 H₂O (10 H) yazılır."},{"t":"Oksijen ve tam sayı","a":"×2","d":"Sağda 4·2 + 5·1 = 13 oksijen var; solda 13/2 O₂ gerekir. Tümünü 2 ile çarpınca: 2 C₄H₁₀ + 13 O₂ → 8 CO₂ + 10 H₂O (C 8=8, H 20=20, O 26=26)."}],"ans":"Denk hâli 2 C₄H₁₀ + 13 O₂ → 8 CO₂ + 10 H₂O'dur (C 8=8, H 20=20, O 26=26)."},
{"q":"Al + H₂SO₄ → Al₂(SO₄)₃ + H₂ denklemini denkleştir.","steps":[{"t":"Sülfat grubunu dengele","a":"3 SO₄","d":"Sağda Al₂(SO₄)₃ üç sülfat grubu içerir; solda 3 H₂SO₄ gerekir, böylece sülfat 3=3 olur."},{"t":"Al ve H'yi tamamla","a":"2 Al, 3 H₂","d":"2 alüminyum için 2 Al; 3 H₂SO₄'teki 6 hidrojen için 3 H₂ gerekir. Sonuç: 2 Al + 3 H₂SO₄ → Al₂(SO₄)₃ + 3 H₂ (Al 2=2, S 3=3, O 12=12, H 6=6)."}],"ans":"Denk hâli 2 Al + 3 H₂SO₄ → Al₂(SO₄)₃ + 3 H₂'dir (Al 2=2, S 3=3, H 6=6, O 12=12)."}
]}}};
