globalThis.__OUT = {"kutleTartisi":{"ilkokul":{"kolay":[
{"q":"Bir maddenin 1 molünün gram cinsinden kütlesine ne ad verilir?","steps":[{"t":"1 mol","a":"belli miktar madde","d":"1 mol, belli sayıda tanecik içeren madde miktarıdır."},{"t":"Kütlesi","a":"molar kütle","d":"Bu 1 molün gram olarak kütlesine <b>molar kütle</b> denir."}],"ans":"1 molün gram cinsinden kütlesine <b>molar kütle</b> denir (birimi g/mol)."},
{"q":"Bir maddeyi terazide neyle ölçeriz: tane sayısı mı, kütle mi?","steps":[{"t":"Terazi","a":"kütle ölçer","d":"Terazi bize maddenin kütlesini, yani gram olarak ağırlığını söyler."},{"t":"Sonuç","a":"kütle","d":"Atomları tek tek sayamadığımız için maddeyi gram olarak tartarız."}],"ans":"Maddeyi terazide <b>kütle</b> (gram) olarak ölçeriz, tane tane saymayız."},
{"q":"1 mol su (H₂O) kaç gram gelir?","steps":[{"t":"Bilgi","a":"verilen değer","d":"1 mol suyun kütlesi bize 18 gram olarak verilir."},{"t":"Sonuç","a":"18 gram","d":"Yani 1 mol su tartıldığında terazi 18 gram gösterir."}],"ans":"1 mol su <b>18 gram</b> gelir."},
{"q":"İki farklı maddenin 1 molü aynı gram mı gelir?","steps":[{"t":"Tanecik sayısı","a":"aynı","d":"Birer mollerinde aynı sayıda tanecik vardır."},{"t":"Kütle","a":"farklı olabilir","d":"Ama tanecikler farklı ağırlıkta olduğundan kütleleri farklı olur."}],"ans":"Hayır; aynı sayıda tanecik içerseler de 1 molleri genelde <b>farklı gram</b> gelir."},
{"q":"Tuz (NaCl) ile su (H₂O) gibi maddelerin molar kütleleri farklı mıdır?","steps":[{"t":"Farklı maddeler","a":"farklı tanecik","d":"Tuz ve su farklı atomlardan oluşur."},{"t":"Kütle","a":"farklı g/mol","d":"Bu yüzden 1 mollerinin kütleleri (molar kütleleri) birbirinden farklıdır."}],"ans":"Evet; farklı maddeler oldukları için molar kütleleri (1 mollerinin gramı) <b>farklıdır</b>."}
],"zor":[
{"q":"1 mol su 18 gram ise 2 mol su kaç gram gelir?","steps":[{"t":"1 mol","a":"18 gram","d":"1 mol suyun kütlesi 18 gramdır."},{"t":"2 mol","a":"2 × 18","d":"2 mol için 2 × 18 = 36 gram buluruz."}],"ans":"2 mol su <b>36 gram</b> gelir."},
{"q":"1 mol karbondioksit (CO₂) 44 gram ise yarım mol kaç gram gelir?","steps":[{"t":"1 mol","a":"44 gram","d":"1 mol CO₂ 44 gramdır."},{"t":"Yarısı","a":"44 ÷ 2","d":"0,5 mol için kütlenin yarısını alırız: 44 ÷ 2 = 22 gram."}],"ans":"0,5 mol CO₂ <b>22 gram</b> gelir."},
{"q":"Neden atomları tek tek saymak yerine maddeyi tartarız?","steps":[{"t":"Saymak imkânsız","a":"çok küçük","d":"Atomlar gözle görülemeyecek kadar küçük ve çok sayıda olduğu için tek tek sayılamaz."},{"t":"Tartmak kolay","a":"terazi","d":"Onun yerine maddeyi terazide tartarız; kütlesinden mol sayısını bulabiliriz."}],"ans":"Atomlar sayılamayacak kadar küçük olduğu için onları saymak yerine maddeyi <b>tartarız</b>."},
{"q":"36 gram su kaç mol eder (1 mol su = 18 gram)?","steps":[{"t":"1 mol","a":"18 gram","d":"1 mol su 18 gramdır."},{"t":"Bölme","a":"36 ÷ 18","d":"36 gramı 18'e böleriz ve 2 buluruz."}],"ans":"36 gram su <b>2 mol</b> eder."},
{"q":"1 mol su 18 g, 1 mol CO₂ 44 g ise hangisinin 1 molü daha ağırdır?","steps":[{"t":"Su","a":"18 gram","d":"1 mol suyun kütlesi 18 gramdır."},{"t":"Karşılaştırma","a":"CO₂ ağır","d":"1 mol CO₂ 44 gramdır; 44 > 18 olduğundan CO₂'nin 1 molü daha ağırdır."}],"ans":"1 mol <b>CO₂ (44 g)</b>, 1 mol sudan (18 g) daha ağırdır."}
]},"ortaokul":{"kolay":[
{"q":"Molar kütle nedir ve birimi nedir?","steps":[{"t":"Tanım","a":"1 molün kütlesi","d":"Molar kütle, bir maddenin 1 molünün gram cinsinden kütlesidir."},{"t":"Birim","a":"g/mol","d":"Birimi gram bölü mol (g/mol) şeklinde yazılır."}],"ans":"Molar kütle, 1 molün gram cinsinden kütlesidir; birimi <b>g/mol</b>'dür."},
{"q":"Suyun (H₂O) molar kütlesi formülden nasıl bulunur (H=1, O=16)?","steps":[{"t":"Atomlar","a":"2 H + 1 O","d":"H₂O'da 2 hidrojen ve 1 oksijen atomu vardır."},{"t":"Toplam","a":"2·1 + 16","d":"Atom kütlelerini toplarız: 2×1 + 16 = 18 g/mol."}],"ans":"Suyun molar kütlesi <b>18 g/mol</b>'dür (2×1 + 16)."},
{"q":"Mol sayısı (n) kütleden (m) nasıl hesaplanır?","steps":[{"t":"Bağıntı","a":"n = m / M","d":"Mol sayısı, kütlenin molar kütleye bölünmesiyle bulunur."},{"t":"Anlam","a":"gram → mol","d":"Burada m gram cinsinden kütle, M ise g/mol cinsinden molar kütledir."}],"ans":"Mol sayısı <b>n = m / M</b> bağıntısıyla hesaplanır."},
{"q":"CO₂'nin molar kütlesi kaçtır (C=12, O=16)?","steps":[{"t":"Atomlar","a":"1 C + 2 O","d":"CO₂'de 1 karbon ve 2 oksijen atomu vardır."},{"t":"Toplam","a":"12 + 2·16","d":"12 + 2×16 = 12 + 32 = 44 g/mol."}],"ans":"CO₂'nin molar kütlesi <b>44 g/mol</b>'dür."},
{"q":"Yemek tuzunun (NaCl) molar kütlesi kaçtır (Na=23, Cl=35,5)?","steps":[{"t":"Atomlar","a":"1 Na + 1 Cl","d":"NaCl'de 1 sodyum ve 1 klor atomu vardır."},{"t":"Toplam","a":"23 + 35,5","d":"23 + 35,5 = 58,5 g/mol."}],"ans":"NaCl'nin molar kütlesi <b>58,5 g/mol</b>'dür."}
],"zor":[
{"q":"36 gram su (H₂O, M=18 g/mol) kaç moldür?","steps":[{"t":"Bağıntı","a":"n = m / M","d":"Mol sayısı = kütle / molar kütle."},{"t":"İşlem","a":"36 ÷ 18","d":"36 gramı 18 g/mol'e böleriz: 2 mol."}],"ans":"36 gram su <b>2 mol</b> eder."},
{"q":"3 mol CO₂'nin (M=44 g/mol) kütlesi kaç gramdır?","steps":[{"t":"Bağıntı","a":"m = n × M","d":"Kütle = mol sayısı × molar kütle."},{"t":"İşlem","a":"3 × 44","d":"3 × 44 = 132 gram."}],"ans":"3 mol CO₂'nin kütlesi <b>132 gram</b>'dır."},
{"q":"117 gram yemek tuzu (NaCl, M=58,5 g/mol) kaç moldür?","steps":[{"t":"Bağıntı","a":"n = m / M","d":"Mol sayısı = kütle / molar kütle."},{"t":"İşlem","a":"117 ÷ 58,5","d":"117 gramı 58,5 g/mol'e böleriz: 2 mol."}],"ans":"117 gram NaCl <b>2 mol</b> eder."},
{"q":"Amonyağın (NH₃) molar kütlesi kaçtır (N=14, H=1)?","steps":[{"t":"Atomlar","a":"1 N + 3 H","d":"NH₃'te 1 azot ve 3 hidrojen atomu vardır."},{"t":"Toplam","a":"14 + 3·1","d":"14 + 3×1 = 14 + 3 = 17 g/mol."}],"ans":"NH₃'ün molar kütlesi <b>17 g/mol</b>'dür."},
{"q":"0,5 mol oksijen gazının (O₂, O=16) kütlesi kaç gramdır?","steps":[{"t":"Molar kütle","a":"O₂ = 32 g/mol","d":"O₂'de 2 oksijen atomu vardır: 2×16 = 32 g/mol."},{"t":"Kütle","a":"m = n × M","d":"m = 0,5 × 32 = 16 gram."}],"ans":"0,5 mol O₂'nin kütlesi <b>16 gram</b>'dır."}
]},"lise":{"kolay":[
{"q":"Molar kütle kavramı, atom/molekül kütlesi ile gram dünyası arasında nasıl bir bağ kurar?","steps":[{"t":"Bağıl kütle","a":"akb cinsinden","d":"Bir molekülün kütlesi atomik kütle birimi cinsinden, atom kütlelerinin toplamıdır (örneğin H₂O = 18 akb)."},{"t":"Molar kütle","a":"aynı sayı, g/mol","d":"Bu bağıl kütle sayısı, 1 mol için gram cinsinden molar kütleye eşittir; H₂O için 18 g/mol."}],"ans":"Molar kütle, bir taneciğin bağıl kütlesini (akb) aynı sayısal değerle <b>g/mol</b> cinsinden 1 molün kütlesine bağlar."},
{"q":"Glikozun (C₆H₁₂O₆) molar kütlesi nasıl hesaplanır (C=12, H=1, O=16)?","steps":[{"t":"Atom katkıları","a":"6C + 12H + 6O","d":"6 karbon, 12 hidrojen ve 6 oksijen atomunun kütleleri toplanır."},{"t":"Toplam","a":"6·12 + 12·1 + 6·16","d":"72 + 12 + 96 = 180 g/mol."}],"ans":"Glikozun (C₆H₁₂O₆) molar kütlesi <b>180 g/mol</b>'dür."},
{"q":"Kütle, mol ve molar kütle arasındaki dönüşüm bağıntıları nelerdir?","steps":[{"t":"Mole çevirme","a":"n = m / M","d":"Mol sayısı, kütlenin molar kütleye bölünmesiyle bulunur."},{"t":"Kütleye çevirme","a":"m = n × M","d":"Kütle ise mol sayısı ile molar kütlenin çarpımıdır."}],"ans":"Dönüşümler <b>n = m / M</b> ve <b>m = n × M</b> bağıntılarıyla yapılır."},
{"q":"88 gram CO₂ (M=44 g/mol) kaç mol ve kaç tane molekül içerir (N_A=6,02·10²³)?","steps":[{"t":"Mol sayısı","a":"n = m / M","d":"n = 88 / 44 = 2 mol."},{"t":"Molekül sayısı","a":"N = n × N_A","d":"N = 2 × 6,02·10²³ = 1,204·10²⁴ tane molekül."}],"ans":"88 gram CO₂ = <b>2 mol</b> ve <b>1,204·10²⁴</b> tane molekül içerir."},
{"q":"Sülfürik asidin (H₂SO₄) molar kütlesi kaçtır (H=1, S=32, O=16)?","steps":[{"t":"Atom katkıları","a":"2H + 1S + 4O","d":"2 hidrojen, 1 kükürt ve 4 oksijen atomu vardır."},{"t":"Toplam","a":"2·1 + 32 + 4·16","d":"2 + 32 + 64 = 98 g/mol."}],"ans":"H₂SO₄'ün molar kütlesi <b>98 g/mol</b>'dür."}
],"zor":[
{"q":"45 gram glikozun (C₆H₁₂O₆, M=180 g/mol) içerdiği mol sayısı ve molekül sayısı nedir?","steps":[{"t":"Mol sayısı","a":"n = m / M","d":"n = 45 / 180 = 0,25 mol."},{"t":"Molekül sayısı","a":"N = n × N_A","d":"N = 0,25 × 6,02·10²³ = 1,505·10²³ tane molekül."}],"ans":"45 gram glikoz = <b>0,25 mol</b> ve <b>1,505·10²³</b> tane molekül içerir."},
{"q":"54 gram suda (H₂O, M=18 g/mol) toplam kaç tane hidrojen atomu bulunur?","steps":[{"t":"Mol sayısı","a":"n = 54 / 18","d":"54 gram su = 3 mol H₂O."},{"t":"H atomu sayısı","a":"3 × 2 × N_A","d":"Her molekülde 2 H atomu olduğundan: 3 mol × 2 × 6,02·10²³ = 3,612·10²⁴ tane H atomu."}],"ans":"54 gram suda <b>3,612·10²⁴</b> tane hidrojen atomu bulunur."},
{"q":"Bir bileşiğin 0,5 molünün kütlesi 49 gram ise molar kütlesi kaçtır ve hangi bileşik olabilir?","steps":[{"t":"Molar kütle","a":"M = m / n","d":"M = 49 / 0,5 = 98 g/mol."},{"t":"Bileşik","a":"H₂SO₄","d":"98 g/mol, sülfürik asit (H₂SO₄) molar kütlesine uyar (2+32+64=98)."}],"ans":"Molar kütle <b>98 g/mol</b>'dür; bu, <b>H₂SO₄</b> (sülfürik asit) ile uyumludur."},
{"q":"100 gram kalsiyum karbonatta (CaCO₃, Ca=40, C=12, O=16) kaç mol bileşik vardır?","steps":[{"t":"Molar kütle","a":"40+12+3·16","d":"CaCO₃ = 40 + 12 + 48 = 100 g/mol."},{"t":"Mol sayısı","a":"n = m / M","d":"n = 100 / 100 = 1 mol."}],"ans":"100 gram CaCO₃ <b>1 mol</b> bileşik içerir (M = 100 g/mol)."},
{"q":"23 gram sodyum (Na, M=23 g/mol) ile 24 gram magnezyum (Mg, M=24 g/mol) örneklerinden hangisi daha çok atom içerir?","steps":[{"t":"Na molü","a":"23/23 = 1 mol","d":"23 gram sodyum 1 mol Na, yani 6,02·10²³ atom içerir."},{"t":"Mg molü","a":"24/24 = 1 mol","d":"24 gram magnezyum da 1 mol Mg, yani 6,02·10²³ atom içerir; ikisi eşittir."}],"ans":"İkisi de <b>1'er mol</b> (6,02·10²³ atom) içerdiğinden atom sayıları <b>eşittir</b>."}
]}}};
