globalThis.__OUT = {"verimHesabi":{"ilkokul":{"kolay":[
{"q":"Annen hamurdan 20 kurabiye çıkmasını bekliyordu ama fırından 18 kurabiye çıktı. Beklenenin yüzde kaçı gerçekleşti?","fig":"<svg viewBox='0 0 320 130'><circle cx='60' cy='50' r='14' fill='#e0552b'/><circle cx='100' cy='50' r='14' fill='#e0552b'/><circle cx='140' cy='50' r='14' fill='#e0552b'/><text x='100' y='95' font-size='11' text-anchor='middle' fill='#1a2b45'>18 / 20 kurabiye</text></svg>","steps":[{"t":"Oranı kur","a":"18 ÷ 20","d":"Gerçekleşeni beklenene böleriz: 18 ÷ 20 = 0,9 olur."},{"t":"Yüzdeye çevir","a":"%90","d":"0,9 sayısını 100 ile çarparız: 0,9 × 100 = 90, yani verim %90 olur."}],"ans":"18 kurabiye 20'nin yüzde 90'ıdır; yani verim %90 olmuştur."},
{"q":"Bir sınıf 50 kâğıt uçak yapmayı planladı ama yalnızca 25 tane bitirebildi. Planın yüzde kaçı tamamlandı?","steps":[{"t":"Oranı kur","a":"25 ÷ 50","d":"Yapılanı planlanana böleriz: 25 ÷ 50 = 0,5 çıkar."},{"t":"Yüzdeye çevir","a":"%50","d":"0,5 × 100 = 50, yani planın yarısı, yüzde 50'si tamamlanmıştır."}],"ans":"25 uçak 50'nin yarısıdır; plan yüzde 50 oranında tamamlanmıştır."},
{"q":"Limonatadan 10 bardak çıkması bekleniyordu, 10 bardak çıktı. Bu işin verimi yüzde kaçtır?","steps":[{"t":"Oranı kur","a":"10 ÷ 10","d":"Çıkan miktarı beklenen miktara böleriz: 10 ÷ 10 = 1 olur."},{"t":"Yüzdeye çevir","a":"%100","d":"1 × 100 = 100, yani hiç kayıp yok, verim tam yüzde 100'dür."}],"ans":"Beklenen kadar çıktığı için kayıp yoktur; verim yüzde 100'dür."},
{"q":"Verim 'beklenenin ne kadarını elde ettik' demektir. Daha çok kayıp olunca verim yüzdesi artar mı azalır mı?","steps":[{"t":"Kayıp nedir","a":"elde edemediğimiz","d":"Kayıp, beklediğimiz ama gerçekte elde edemediğimiz kısımdır."},{"t":"Etkisi","a":"verim azalır","d":"Kayıp arttıkça elimizde kalan azalır, bu yüzden verim yüzdesi de azalır."}],"ans":"Kayıp arttıkça elde ettiğimiz azalır; bu yüzden verim yüzdesi azalır."},
{"q":"Bir fabrikada 100 oyuncaktan 80'i sağlam çıktı, 20'si bozuktu. Sağlam oyuncakların verimi yüzde kaçtır?","fig":"<svg viewBox='0 0 320 120'><rect x='40' y='40' width='160' height='30' fill='#2b6be0'/><rect x='200' y='40' width='40' height='30' fill='#cfd8e8' stroke='#1a2b45'/><text x='120' y='95' font-size='11' text-anchor='middle' fill='#1a2b45'>80 sağlam</text><text x='220' y='95' font-size='10' text-anchor='middle' fill='#1a2b45'>20 bozuk</text></svg>","steps":[{"t":"Oranı kur","a":"80 ÷ 100","d":"Sağlam çıkanı toplam beklenene böleriz: 80 ÷ 100 = 0,8 olur."},{"t":"Yüzdeye çevir","a":"%80","d":"0,8 × 100 = 80, yani sağlam oyuncak verimi yüzde 80'dir."}],"ans":"80 sağlam oyuncak 100'ün yüzde 80'idir; verim %80'dir."}
],"zor":[
{"q":"Bir pasta tarifinden 24 dilim çıkması bekleniyordu ama 18 dilim çıktı. Verim yüzde kaçtır?","steps":[{"t":"Oranı kur","a":"18 ÷ 24","d":"Gerçekleşeni beklenene böleriz: 18 ÷ 24 = 0,75 olur."},{"t":"Yüzdeye çevir","a":"%75","d":"0,75 × 100 = 75, yani verim yüzde 75'tir; dörtte üçü elde edilmiştir."}],"ans":"18 dilim 24'ün dörtte üçüdür; verim %75'tir."},
{"q":"İki arkadaştan biri planının %90'ını, diğeri %60'ını tamamladı. Hangisinin verimi daha yüksektir ve bu ne anlama gelir?","steps":[{"t":"Karşılaştır","a":"%90 > %60","d":"90 sayısı 60'tan büyüktür, bu yüzden ilk arkadaşın verimi daha yüksektir."},{"t":"Anlamı","a":"daha az kayıp","d":"Yüksek verim, planlanana daha yakın sonuç ve daha az kayıp demektir."}],"ans":"İlk arkadaşın verimi (%90) daha yüksektir; bu, planına daha yakın sonuç aldığı ve daha az kaybı olduğu anlamına gelir."},
{"q":"Bir bahçeden 40 kg domates beklenirken kuraklık yüzünden 30 kg toplandı. Verimi bulup kayıp yüzdesini söyleyiniz.","fig":"<svg viewBox='0 0 320 120'><circle cx='70' cy='55' r='12' fill='#e0552b'/><circle cx='105' cy='55' r='12' fill='#e0552b'/><circle cx='140' cy='55' r='12' fill='#e0552b'/><circle cx='180' cy='55' r='12' fill='#cfd8e8' stroke='#1a2b45'/><text x='125' y='100' font-size='11' text-anchor='middle' fill='#1a2b45'>30 / 40 kg</text></svg>","steps":[{"t":"Verimi bul","a":"30 ÷ 40","d":"Toplananı beklenene böleriz: 30 ÷ 40 = 0,75; yüzdeye çevirince %75 verim."},{"t":"Kaybı bul","a":"%25","d":"Tamamı %100 olduğundan kayıp 100 − 75 = %25'tir."}],"ans":"Verim %75'tir; kalan %25 ise kuraklık nedeniyle kayıptır."},
{"q":"Bir öğrenci 200 boncuktan bileklik yapacaktı ama 150 boncuk kullanabildi. Verim yüzde kaçtır ve kaç boncuk işe yaramadı?","steps":[{"t":"Verimi bul","a":"150 ÷ 200","d":"Kullanılanı planlanana böleriz: 150 ÷ 200 = 0,75; yani %75 verim."},{"t":"Artan boncuk","a":"50 boncuk","d":"200 − 150 = 50 boncuk kullanılamamış, yani işe yaramamıştır."}],"ans":"Verim %75'tir; 200 − 150 = 50 boncuk kullanılamamıştır."},
{"q":"Bir limonatacı 1 limondan 2 bardak yapmayı planlıyor. 10 limon kullandı ama 16 bardak çıktı. Verim yüzde kaçtır?","steps":[{"t":"Beklenen miktar","a":"20 bardak","d":"10 limon × 2 bardak = 20 bardak çıkması beklenir; bu teorik (beklenen) miktardır."},{"t":"Verimi bul","a":"16 ÷ 20","d":"Gerçek çıkanı beklenene böleriz: 16 ÷ 20 = 0,8; yani verim %80'dir."}],"ans":"Beklenen 20 bardaktı; 16 bardak çıktığı için verim 16 ÷ 20 = %80'dir."}
]},"ortaokul":{"kolay":[
{"q":"Verim hesabında 'teorik ürün' ve 'gerçek ürün' ne anlama gelir?","steps":[{"t":"Teorik ürün","a":"beklenen en çok","d":"Teorik ürün, tepkimenin hesapça verebileceği en yüksek (beklenen) ürün miktarıdır."},{"t":"Gerçek ürün","a":"deneyde elde edilen","d":"Gerçek ürün ise deneyi yaptığımızda elimize geçen, çoğunlukla kayıplar nedeniyle daha az olan miktardır."}],"ans":"Teorik ürün hesapça beklenen en yüksek miktar, gerçek ürün ise deneyde gerçekten elde edilen miktardır."},
{"q":"Bir tepkimede teorik olarak 50 g ürün beklenirken 40 g elde edildi. Yüzde verim kaçtır?","fig":"<svg viewBox='0 0 320 120'><text x='160' y='28' font-size='11' text-anchor='middle' fill='#1a2b45'>verim = gerçek / teorik × 100</text><rect x='50' y='50' width='160' height='26' fill='#2b6be0'/><rect x='210' y='50' width='40' height='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='130' y='100' font-size='11' text-anchor='middle' fill='#1a2b45'>40 g / 50 g</text></svg>","steps":[{"t":"Formül","a":"gerçek/teorik×100","d":"Yüzde verim = (gerçek ürün ÷ teorik ürün) × 100 bağıntısıyla bulunur."},{"t":"Yerine koy","a":"%80","d":"(40 ÷ 50) × 100 = 0,8 × 100 = 80, yani verim %80'dir."}],"ans":"(40 ÷ 50) × 100 = %80; tepkimenin verimi yüzde 80'dir."},
{"q":"Yüzde verim formülü nedir ve neden hiçbir zaman %100'ü geçmez?","steps":[{"t":"Formül","a":"(gerçek/teorik)×100","d":"Yüzde verim = (gerçek ürün ÷ teorik ürün) × 100 olarak tanımlanır."},{"t":"Neden ≤ %100","a":"gerçek ≤ teorik","d":"Gerçek ürün, hesaplanan teorik üründen fazla olamaz; kayıplar nedeniyle ona eşit ya da daha az olur, bu yüzden verim %100'ü geçmez."}],"ans":"Yüzde verim = (gerçek ürün ÷ teorik ürün) × 100'dür; gerçek ürün teoriği aşamadığından verim %100'ü geçmez."},
{"q":"Bir tepkimede gerçek ürün, teorik ürüne tam olarak eşit çıkarsa verim kaç olur?","steps":[{"t":"Eşitlik","a":"gerçek = teorik","d":"Gerçek ürün teorik ürüne eşitse oran tam 1 olur."},{"t":"Yüzde","a":"%100","d":"1 × 100 = 100, yani hiç kayıp olmadığını gösteren ideal %100 verim elde edilir."}],"ans":"Gerçek ürün teoriğe eşitse verim %100'dür; bu kaybın olmadığı ideal durumu gösterir."},
{"q":"Verimin %100 olmamasının başlıca nedenleri nelerdir?","steps":[{"t":"Kayıplar","a":"yan tepkime, kaçak","d":"Maddenin bir kısmı yan tepkimelere girebilir, kaplarda kalabilir ya da süzme-aktarmada kaybolabilir."},{"t":"Eksik tepkime","a":"tam dönüşmeme","d":"Tepkenlerin tümü ürüne dönüşmeyebilir; bu nedenlerle gerçek ürün teoriğin altında kalır."}],"ans":"Yan tepkimeler, madde kaçakları, aktarma kayıpları ve tepkimenin tam tamamlanmaması verimi %100'ün altına indirir."}
],"zor":[
{"q":"Bir tepkimede teorik ürün 80 g, elde edilen gerçek ürün 60 g'dır. Yüzde verimi hesaplayınız.","steps":[{"t":"Formülü yaz","a":"(gerçek/teorik)×100","d":"Yüzde verim = (gerçek ürün ÷ teorik ürün) × 100 bağıntısı kullanılır."},{"t":"Yerine koy","a":"%75","d":"(60 ÷ 80) × 100 = 0,75 × 100 = 75; tepkimenin verimi %75'tir."}],"ans":"(60 ÷ 80) × 100 = %75; tepkimenin yüzde verimi 75'tir."},
{"q":"Bir tepkimenin teorik ürünü 200 g, verimi %90 ise gerçekte kaç gram ürün elde edilir?","steps":[{"t":"İlişkiyi kur","a":"gerçek = verim×teorik","d":"Yüzde verim formülünden gerçek ürün = (verim ÷ 100) × teorik ürün olarak çekilir."},{"t":"Yerine koy","a":"180 g","d":"(90 ÷ 100) × 200 = 0,9 × 200 = 180 g gerçek ürün elde edilir."}],"ans":"Gerçek ürün = 0,90 × 200 = 180 g; verim %90 olduğunda 180 g ürün elde edilir."},
{"q":"2H₂ + O₂ → 2H₂O tepkimesinde teorik olarak 36 g su beklenirken 27 g su elde edildi. Verim yüzde kaçtır?","fig":"<svg viewBox='0 0 320 120'><text x='160' y='26' font-size='11' text-anchor='middle' fill='#1a2b45'>2H₂ + O₂ → 2H₂O</text><rect x='50' y='48' width='150' height='26' fill='#2b6be0'/><rect x='200' y='48' width='50' height='26' fill='#cfd8e8' stroke='#1a2b45'/><text x='140' y='98' font-size='11' text-anchor='middle' fill='#1a2b45'>27 g / 36 g su</text></svg>","steps":[{"t":"Teorik ve gerçek","a":"36 g ve 27 g","d":"Hesapça beklenen teorik su 36 g, deneyde elde edilen gerçek su ise 27 g'dır."},{"t":"Verimi bul","a":"%75","d":"(27 ÷ 36) × 100 = 0,75 × 100 = 75; suyun elde ediliş verimi %75'tir."}],"ans":"(27 ÷ 36) × 100 = %75; tepkimede suyun verimi yüzde 75'tir."},
{"q":"C + O₂ → CO₂ tepkimesinde 12 g karbon tam yanarsa teorik olarak 44 g CO₂ beklenir. Gerçekte 33 g CO₂ oluşursa verim kaçtır? (C=12, O=16)","steps":[{"t":"Teorik ürün","a":"44 g CO₂","d":"12 g karbon (1 mol) tam yanınca 1 mol, yani 44 g CO₂ oluşması beklenir; bu teorik üründür."},{"t":"Verimi bul","a":"%75","d":"(33 ÷ 44) × 100 = 0,75 × 100 = 75; tepkimenin verimi %75'tir."}],"ans":"Teorik 44 g CO₂'ye karşılık 33 g elde edildiğinden verim (33 ÷ 44) × 100 = %75'tir."},
{"q":"Bir tepkimenin verimi %80 ve gerçekte 48 g ürün elde edilmiştir. Teorik ürün kaç gramdır?","steps":[{"t":"İlişkiyi kur","a":"teorik = gerçek/verim","d":"Yüzde verim = (gerçek ÷ teorik) × 100 olduğundan teorik ürün = gerçek ÷ (verim ÷ 100) olur."},{"t":"Yerine koy","a":"60 g","d":"48 ÷ (80 ÷ 100) = 48 ÷ 0,8 = 60 g; teorik ürün 60 gramdır."}],"ans":"Teorik ürün = 48 ÷ 0,80 = 60 g; %80 verimle 48 g elde edildiğine göre teorik 60 gramdır."}
]},"lise":{"kolay":[
{"q":"Yüzde verim kavramını tanımlayıp teorik verim ile gerçek verim arasındaki farkı açıklayınız.","steps":[{"t":"Tanım","a":"(gerçek/teorik)×100","d":"Yüzde verim, gerçek ürün miktarının teorik ürün miktarına oranının yüzdesidir: % verim = (gerçek ürün ÷ teorik ürün) × 100."},{"t":"Fark","a":"hesap vs deney","d":"Teorik verim, sınırlayıcı bileşene göre stokiyometriyle hesaplanan en yüksek üründür; gerçek verim ise deneyde fiilen elde edilen ve kayıplar nedeniyle daha düşük olan miktardır."}],"ans":"Yüzde verim = (gerçek ürün ÷ teorik ürün) × 100'dür; teorik verim hesapla bulunan en yüksek miktar, gerçek verim ise deneyde elde edilen ve genellikle daha az olan miktardır."},
{"q":"N₂ + 3H₂ ⇌ 2NH₃ tepkimesinde teorik olarak 34 g NH₃ beklenirken 23,8 g elde edildi. Yüzde verim kaçtır? (N=14, H=1)","fig":"<svg viewBox='0 0 320 120'><text x='160' y='26' font-size='11' text-anchor='middle' fill='#1a2b45'>N₂ + 3H₂ ⇌ 2NH₃</text><rect x='50' y='50' width='140' height='24' fill='#2b6be0'/><rect x='190' y='50' width='60' height='24' fill='#cfd8e8' stroke='#1a2b45'/><text x='150' y='98' font-size='11' text-anchor='middle' fill='#1a2b45'>23,8 g / 34 g NH₃</text></svg>","steps":[{"t":"Teorik ve gerçek","a":"34 g ve 23,8 g","d":"Teorik amonyak 34 g (2 mol × 17 g/mol), deneyde elde edilen gerçek amonyak 23,8 g'dır."},{"t":"Verimi bul","a":"%70","d":"(23,8 ÷ 34) × 100 = 0,7 × 100 = 70; amonyak sentezinin verimi %70'tir."}],"ans":"(23,8 ÷ 34) × 100 = %70; amonyak sentezinin yüzde verimi 70'tir."},
{"q":"Yüzde verimin teorik üst sınırının %100 olmasının nedeni nedir; gerçek verim teoriği neden aşamaz?","steps":[{"t":"Teorik tanım","a":"maksimum ürün","d":"Teorik ürün, kütlenin korunumu ve stokiyometri gereği tepkenlerden oluşabilecek en yüksek üründür."},{"t":"Üst sınır","a":"gerçek ≤ teorik","d":"Gerçek ürün, var olan atomlardan fazlasını içeremeyeceğinden teoriği aşamaz; bu nedenle yüzde verim en çok %100 olur, ölçüm fazlası ürün safsızlık/kuru bırakılmama gibi hatalardan gelir."}],"ans":"Teorik ürün kütle korunumuyla belirlenen maksimumdur; gerçek ürün var olan atomdan fazlasını içeremeyeceği için teoriği aşamaz, dolayısıyla verim en çok %100'dür."},
{"q":"Verimi %100'ün altına çeken laboratuvar kaynaklı başlıca kayıp türlerini açıklayınız.","steps":[{"t":"Tepkime kaynaklı","a":"yan tepkime, denge","d":"Tepkenlerin bir kısmı istenmeyen yan ürünlere dönüşebilir ya da denge tepkimesi tam tamamlanmadan dengeye ulaşır."},{"t":"İşlem kaynaklı","a":"aktarma, süzme, çözünme","d":"Süzme, kristallendirme, aktarma sırasında madde kaybı olur; ürünün bir kısmı çözücüde kalabilir. Bu kayıpların tümü gerçek ürünü azaltır."}],"ans":"Yan tepkimeler ve tamamlanmamış denge ile süzme, aktarma, çözücüde kalma gibi işlem kayıpları gerçek ürünü azaltarak verimi %100'ün altına indirir."},
{"q":"CaCO₃ → CaO + CO₂ tepkimesinde 100 g CaCO₃ ısıtıldığında teorik olarak 56 g CaO beklenir. 50,4 g CaO elde edilirse verim kaçtır? (Ca=40, C=12, O=16)","steps":[{"t":"Teorik CaO","a":"56 g","d":"100 g CaCO₃ (1 mol) bozununca 1 mol, yani 56 g CaO oluşması beklenir; bu teorik üründür."},{"t":"Verimi bul","a":"%90","d":"(50,4 ÷ 56) × 100 = 0,9 × 100 = 90; bozunma tepkimesinin verimi %90'dır."}],"ans":"Teorik 56 g CaO'ya karşılık 50,4 g elde edildiğinden verim (50,4 ÷ 56) × 100 = %90'dır."}
],"zor":[
{"q":"CH₄ + 2O₂ → CO₂ + 2H₂O tepkimesinde 16 g metan tam yakılıyor, deneyde 33 g CO₂ toplanıyor. Yüzde verimi bulunuz. (C=12, H=1, O=16)","steps":[{"t":"Mol ve teorik ürün","a":"1 mol CH₄ → 44 g CO₂","d":"CH₄ molkütlesi 16 g/mol; 16 g = 1 mol. Mol oranı 1 CH₄ : 1 CO₂ olduğundan 1 mol CO₂, yani 44 g CO₂ teorik olarak beklenir."},{"t":"Verim formülü","a":"(33/44)×100","d":"Yüzde verim = (gerçek ÷ teorik) × 100 = (33 ÷ 44) × 100 bağıntısıyla hesaplanır."},{"t":"Sonuç","a":"%75","d":"(33 ÷ 44) × 100 = 0,75 × 100 = 75; yanmanın CO₂ verimi %75'tir."}],"ans":"1 mol metandan teorik 44 g CO₂ beklenir; 33 g elde edildiğinden verim (33 ÷ 44) × 100 = %75'tir."},
{"q":"2Na + Cl₂ → 2NaCl tepkimesinde 23 g sodyum tam tepkiyor. Verim %80 ise gerçekte kaç gram NaCl elde edilir? (Na=23, Cl=35,5)","fig":"<svg viewBox='0 0 320 120'><text x='160' y='26' font-size='11' text-anchor='middle' fill='#1a2b45'>2Na + Cl₂ → 2NaCl</text><rect x='50' y='50' width='130' height='24' fill='#2b6be0'/><rect x='180' y='50' width='40' height='24' fill='#cfd8e8' stroke='#1a2b45'/><text x='140' y='98' font-size='11' text-anchor='middle' fill='#1a2b45'>%80 verim</text></svg>","steps":[{"t":"Teorik NaCl","a":"58,5 g","d":"23 g Na = 1 mol; mol oranı 2 Na : 2 NaCl = 1 : 1 olduğundan 1 mol NaCl, yani 58,5 g teorik olarak beklenir."},{"t":"Gerçek ürün","a":"verim×teorik","d":"Gerçek ürün = (verim ÷ 100) × teorik = 0,80 × 58,5 olarak hesaplanır."},{"t":"Sonuç","a":"46,8 g","d":"0,80 × 58,5 = 46,8 g; %80 verimle 46,8 g NaCl elde edilir."}],"ans":"Teorik 58,5 g NaCl beklenir; %80 verimle gerçek ürün 0,80 × 58,5 = 46,8 g olur."},
{"q":"Bir sentezde teorik ürün 250 g, elde edilen gerçek ürün 200 g'dır. Verimi bulup, aynı verimle 400 g teorikten kaç gram ürün beklenir?","steps":[{"t":"Verimi bul","a":"%80","d":"(200 ÷ 250) × 100 = 0,8 × 100 = 80; tepkimenin verimi %80'dir."},{"t":"Yeni gerçek ürün","a":"verim×teorik","d":"Aynı %80 verimle gerçek ürün = 0,80 × teorik formülüyle hesaplanır."},{"t":"Sonuç","a":"320 g","d":"0,80 × 400 = 320 g; aynı verimle 400 g teorikten 320 g ürün beklenir."}],"ans":"Verim (200 ÷ 250) × 100 = %80'dir; aynı verimle 400 g teorikten 0,80 × 400 = 320 g ürün beklenir."},
{"q":"C + O₂ → CO₂ tepkimesinde 24 g karbon yakılıyor, deney sonunda 66 g CO₂ toplanıyor. Yüzde verimi hesaplayınız. (C=12, O=16)","steps":[{"t":"Mol ve teorik ürün","a":"2 mol C → 88 g CO₂","d":"24 g karbon = 2 mol; mol oranı 1 C : 1 CO₂ olduğundan 2 mol CO₂, yani 2 × 44 = 88 g CO₂ teorik olarak beklenir."},{"t":"Verim formülü","a":"(66/88)×100","d":"Yüzde verim = (gerçek ÷ teorik) × 100 = (66 ÷ 88) × 100 bağıntısı kullanılır."},{"t":"Sonuç","a":"%75","d":"(66 ÷ 88) × 100 = 0,75 × 100 = 75; tepkimenin verimi %75'tir."}],"ans":"2 mol karbondan teorik 88 g CO₂ beklenir; 66 g toplandığından verim (66 ÷ 88) × 100 = %75'tir."},
{"q":"N₂ + 3H₂ ⇌ 2NH₃ tepkimesinde 28 g azot ile yeterli hidrojen tepkiyor. Verim %85 ise kaç gram NH₃ elde edilir? (N=14, H=1)","steps":[{"t":"Mol ve teorik ürün","a":"1 mol N₂ → 34 g NH₃","d":"28 g azot = 1 mol N₂; mol oranı 1 N₂ : 2 NH₃ olduğundan 2 mol NH₃, yani 2 × 17 = 34 g NH₃ teorik olarak beklenir."},{"t":"Gerçek ürün","a":"0,85×34","d":"Gerçek ürün = (verim ÷ 100) × teorik = 0,85 × 34 olarak hesaplanır."},{"t":"Sonuç","a":"28,9 g","d":"0,85 × 34 = 28,9 g; %85 verimle 28,9 g amonyak elde edilir."}],"ans":"1 mol azottan teorik 34 g NH₃ beklenir; %85 verimle gerçek ürün 0,85 × 34 = 28,9 g olur."}
]}}};
