globalThis.__OUT = {"molarKutle":{"ilkokul":{"kolay":[
{"q":"Bir maddenin bir <b>mol</b>'ünün gram cinsinden kütlesine ne ad verilir?","steps":[{"t":"Bir mol","a":"belirli sayıda tanecik","d":"Mol, çok sayıda taneciği bir arada saymak için kullanılan bir ölçüdür."},{"t":"Gram karşılığı","a":"molar kütle","d":"Bir molün gram cinsinden kütlesine molar kütle (g/mol) denir."}],"ans":"Bir molün gram cinsinden kütlesine molar kütle denir; birimi g/mol'dür."},
{"q":"Su (H₂O) molekülünde kaç hidrojen, kaç oksijen atomu vardır?","steps":[{"t":"H sayısı","a":"2 hidrojen","d":"H₂ alt indisi 2, suda iki hidrojen atomu olduğunu gösterir."},{"t":"O sayısı","a":"1 oksijen","d":"O yanında sayı yoktur, yani bir oksijen atomu vardır."}],"ans":"Su molekülünde 2 hidrojen ve 1 oksijen atomu bulunur."},
{"q":"Karbondioksit (CO₂) molekülünde toplam kaç atom vardır?","steps":[{"t":"Atomları say","a":"1 C + 2 O","d":"Bir karbon ve iki oksijen atomu vardır."},{"t":"Toplam","a":"3 atom","d":"1 + 2 = 3 atom bulunur."}],"ans":"CO₂ molekülünde toplam 3 atom (1 karbon, 2 oksijen) bulunur."},
{"q":"Bir oksijen atomunun kütlesi 16 birim, bir hidrojen atomunun kütlesi 1 birimdir. Hangisi daha ağırdır?","steps":[{"t":"Sayıları karşılaştır","a":"16 > 1","d":"Oksijenin kütle değeri 16, hidrojeninki 1'dir."},{"t":"Sonuç","a":"oksijen","d":"Daha büyük sayıya sahip oksijen daha ağırdır."}],"ans":"Oksijen atomu (16) hidrojen atomundan (1) daha ağırdır."},
{"q":"Bir düzine yumurta 12 yumurta demektir. Mol da çok büyük bir miktarı sayar; doğru mu?","steps":[{"t":"Düzine örneği","a":"sayma birimi","d":"Düzine gibi mol da bir sayma birimidir."},{"t":"Mol büyüklüğü","a":"çok büyük","d":"Mol, atom gibi çok küçük tanecikleri saymak için kullanılan çok büyük bir sayıdır."}],"ans":"Evet; düzine 12'yi sayar, mol ise çok daha büyük bir tanecik miktarını sayar."}
],"zor":[
{"q":"Suyun molar kütlesi 18 g/mol'dür. 1 mol suyun kütlesi kaç gramdır?","steps":[{"t":"Molar kütle anlamı","a":"18 g/mol","d":"1 mol suyun kütlesinin 18 gram olduğunu gösterir."},{"t":"Sonuç","a":"18 g","d":"Bu yüzden 1 mol su 18 gramdır."}],"ans":"1 mol suyun kütlesi 18 gramdır."},
{"q":"1 mol suyun kütlesi 18 gram ise, 2 mol suyun kütlesi kaç gramdır?","steps":[{"t":"Bir molü bul","a":"18 g","d":"1 mol su 18 gramdır."},{"t":"İki ile çarp","a":"2 × 18","d":"2 mol için 18'i 2 ile çarparız: 2 × 18 = 36 g."}],"ans":"2 mol suyun kütlesi 36 gramdır."},
{"q":"Karbondioksitin (CO₂) molar kütlesi 44 g/mol'dür. Yarım (0,5) mol CO₂ kaç gramdır?","steps":[{"t":"Bir mol","a":"44 g","d":"1 mol CO₂ 44 gramdır."},{"t":"Yarısını al","a":"44 ÷ 2","d":"Yarım mol için 44'ü ikiye böleriz: 44 ÷ 2 = 22 g."}],"ans":"0,5 mol CO₂ 22 gramdır."},
{"q":"Karbon atomunun kütlesi 12, oksijen atomunun kütlesi 16 birimdir. CO molekülünün kütlesi kaç birimdir?","steps":[{"t":"Atomları yaz","a":"1 C + 1 O","d":"CO molekülünde bir karbon ve bir oksijen vardır."},{"t":"Topla","a":"12 + 16","d":"Kütleleri toplarız: 12 + 16 = 28 birim."}],"ans":"CO molekülünün kütlesi 28 birimdir (molar kütle 28 g/mol)."},
{"q":"36 gram su kaç mol eder? (1 mol su = 18 g)","fig":"<svg viewBox='0 0 320 150'><rect x='60' y='55' width='50' height='40' fill='#cfd8e8' stroke='#1a2b45'/><text x='85' y='80' font-size='10' text-anchor='middle' fill='#1a2b45'>36 g</text><text x='150' y='80' font-size='13' text-anchor='middle' fill='#1a2b45'>÷ 18</text><text x='200' y='80' font-size='16' text-anchor='middle' fill='#1a2b45'>→</text><text x='260' y='80' font-size='13' text-anchor='middle' fill='#e0552b'>2 mol</text></svg>","steps":[{"t":"Bir mol kütlesi","a":"18 g","d":"1 mol su 18 gramdır."},{"t":"Böl","a":"36 ÷ 18","d":"Kütleyi molar kütleye böleriz: 36 ÷ 18 = 2 mol."}],"ans":"36 gram su 2 mol eder."}
]},"ortaokul":{"kolay":[
{"q":"Molar kütle nasıl hesaplanır?","steps":[{"t":"Formüldeki atomlar","a":"atom kütleleri","d":"Formüldeki her atomun kütlesini, atom sayısıyla çarparız."},{"t":"Topla","a":"toplam","d":"Bütün atomların kütlelerini toplarız; sonuç g/mol cinsinden molar kütledir."}],"ans":"Molar kütle, formüldeki tüm atomların kütlelerinin toplamına eşittir (g/mol)."},
{"q":"Su (H₂O) molekülünün molar kütlesi kaç g/mol'dür? (H=1, O=16)","fig":"<svg viewBox='0 0 320 150'><circle cx='160' cy='65' r='20' fill='#e0552b' stroke='#1a2b45'/><circle cx='120' cy='100' r='13' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='200' cy='100' r='13' fill='#cfd8e8' stroke='#1a2b45'/><line x1='146' y1='78' x2='128' y2='90' stroke='#1a2b45'/><line x1='174' y1='78' x2='192' y2='90' stroke='#1a2b45'/><text x='160' y='69' font-size='10' text-anchor='middle' fill='#fff'>O 16</text><text x='118' y='104' font-size='8' text-anchor='middle' fill='#1a2b45'>H 1</text><text x='202' y='104' font-size='8' text-anchor='middle' fill='#1a2b45'>H 1</text><text x='160' y='135' font-size='11' text-anchor='middle' fill='#1a2b45'>1+1+16 = 18 g/mol</text></svg>","steps":[{"t":"Atom kütleleri","a":"2·H + O","d":"İki hidrojen ve bir oksijen: 2·1 + 16."},{"t":"Topla","a":"2 + 16 = 18","d":"Toplam 18 g/mol bulunur."}],"ans":"Suyun molar kütlesi 18 g/mol'dür."},
{"q":"Karbondioksitin (CO₂) molar kütlesi kaç g/mol'dür? (C=12, O=16)","fig":"<svg viewBox='0 0 320 150'><circle cx='100' cy='75' r='16' fill='#cfd8e8' stroke='#1a2b45'/><circle cx='160' cy='75' r='20' fill='#33415588' stroke='#1a2b45'/><circle cx='220' cy='75' r='16' fill='#e0552b' stroke='#1a2b45'/><line x1='120' y1='75' x2='142' y2='75' stroke='#1a2b45'/><line x1='178' y1='75' x2='204' y2='75' stroke='#1a2b45'/><text x='160' y='80' font-size='10' text-anchor='middle' fill='#fff'>C</text><text x='100' y='80' font-size='10' text-anchor='middle' fill='#1a2b45'>O</text><text x='220' y='80' font-size='10' text-anchor='middle' fill='#fff'>O</text></svg>","steps":[{"t":"Atomları çarp","a":"C + 2·O","d":"Bir karbon (12) ve iki oksijen (2·16 = 32)."},{"t":"Topla","a":"12 + 32 = 44","d":"Toplam 44 g/mol bulunur."}],"ans":"CO₂'nin molar kütlesi 44 g/mol'dür."},
{"q":"Metan (CH₄) gazının molar kütlesi kaç g/mol'dür? (C=12, H=1)","steps":[{"t":"Atom kütleleri","a":"C + 4·H","d":"Bir karbon (12) ve dört hidrojen (4·1 = 4)."},{"t":"Topla","a":"12 + 4 = 16","d":"Toplam 16 g/mol bulunur."}],"ans":"Metanın (CH₄) molar kütlesi 16 g/mol'dür."},
{"q":"Oksijen gazının (O₂) molar kütlesi kaç g/mol'dür? (O=16)","steps":[{"t":"İki oksijen","a":"2·16","d":"O₂ iki oksijen atomundan oluşur: 2·16."},{"t":"Sonuç","a":"32","d":"Toplam 32 g/mol bulunur."}],"ans":"Oksijen gazının (O₂) molar kütlesi 32 g/mol'dür."}
],"zor":[
{"q":"Kalsiyum karbonatın (CaCO₃) molar kütlesi kaç g/mol'dür? (Ca=40, C=12, O=16)","fig":"<svg viewBox='0 0 320 150'><text x='160' y='40' font-size='13' text-anchor='middle' fill='#1a2b45'>CaCO₃</text><text x='60' y='75' font-size='10' text-anchor='middle' fill='#1a2b45'>Ca: 40</text><text x='130' y='75' font-size='10' text-anchor='middle' fill='#1a2b45'>C: 12</text><text x='220' y='75' font-size='10' text-anchor='middle' fill='#1a2b45'>3·O: 48</text><line x1='30' y1='90' x2='290' y2='90' stroke='#1a2b45'/><text x='160' y='120' font-size='13' text-anchor='middle' fill='#e0552b'>= 100 g/mol</text></svg>","steps":[{"t":"Atomları ayır","a":"Ca + C + 3·O","d":"Bir kalsiyum (40), bir karbon (12) ve üç oksijen (3·16 = 48)."},{"t":"Topla","a":"40 + 12 + 48","d":"Toplam: 40 + 12 + 48 = 100 g/mol."}],"ans":"CaCO₃'ün molar kütlesi 100 g/mol'dür."},
{"q":"Sülfürik asidin (H₂SO₄) molar kütlesi kaç g/mol'dür? (H=1, S=32, O=16)","fig":"<svg viewBox='0 0 320 150'><text x='160' y='38' font-size='13' text-anchor='middle' fill='#1a2b45'>H₂SO₄</text><text x='55' y='75' font-size='10' text-anchor='middle' fill='#1a2b45'>2·H: 2</text><text x='130' y='75' font-size='10' text-anchor='middle' fill='#1a2b45'>S: 32</text><text x='220' y='75' font-size='10' text-anchor='middle' fill='#1a2b45'>4·O: 64</text><line x1='30' y1='90' x2='290' y2='90' stroke='#1a2b45'/><text x='160' y='120' font-size='13' text-anchor='middle' fill='#e0552b'>= 98 g/mol</text></svg>","steps":[{"t":"Atomları ayır","a":"2·H + S + 4·O","d":"İki hidrojen (2), bir kükürt (32) ve dört oksijen (4·16 = 64)."},{"t":"Topla","a":"2 + 32 + 64","d":"Toplam: 2 + 32 + 64 = 98 g/mol."}],"ans":"H₂SO₄'ün molar kütlesi 98 g/mol'dür."},
{"q":"3 mol suyun (H₂O) kütlesi kaç gramdır? (molar kütle 18 g/mol)","steps":[{"t":"Molar kütle","a":"18 g/mol","d":"1 mol su 18 gramdır."},{"t":"Mol ile çarp","a":"3 × 18","d":"Kütle = mol × molar kütle = 3 × 18 = 54 g."}],"ans":"3 mol suyun kütlesi 54 gramdır."},
{"q":"88 gram karbondioksit (CO₂) kaç moldür? (molar kütle 44 g/mol)","steps":[{"t":"Molar kütle","a":"44 g/mol","d":"1 mol CO₂ 44 gramdır."},{"t":"Kütleyi böl","a":"88 ÷ 44","d":"mol = kütle ÷ molar kütle = 88 ÷ 44 = 2 mol."}],"ans":"88 gram CO₂ 2 moldür."},
{"q":"Glikozun (C₆H₁₂O₆) molar kütlesi kaç g/mol'dür? (C=12, H=1, O=16)","steps":[{"t":"Atomları ayır","a":"6·C + 12·H + 6·O","d":"Altı karbon (6·12 = 72), on iki hidrojen (12·1 = 12), altı oksijen (6·16 = 96)."},{"t":"Topla","a":"72 + 12 + 96","d":"Toplam: 72 + 12 + 96 = 180 g/mol."}],"ans":"Glikozun (C₆H₁₂O₆) molar kütlesi 180 g/mol'dür."}
]},"lise":{"kolay":[
{"q":"Molar kütle ile mol miktarı arasındaki ilişki nedir?","steps":[{"t":"Tanım","a":"M = m / n","d":"Molar kütle (M), kütlenin (m) mol sayısına (n) bölümüdür."},{"t":"Düzenle","a":"n = m / M","d":"Buradan mol = kütle ÷ molar kütle bağıntısı elde edilir."}],"ans":"n = m / M; mol miktarı, kütlenin molar kütleye bölümüne eşittir."},
{"q":"Amonyak (NH₃) molekülünün molar kütlesi kaç g/mol'dür? (N=14, H=1)","steps":[{"t":"Atomları ayır","a":"N + 3·H","d":"Bir azot (14) ve üç hidrojen (3·1 = 3)."},{"t":"Topla","a":"14 + 3 = 17","d":"Toplam 17 g/mol bulunur."}],"ans":"Amonyağın (NH₃) molar kütlesi 17 g/mol'dür."},
{"q":"Sodyum klorürün (NaCl) molar kütlesi kaç g/mol'dür? (Na=23, Cl=35,5)","steps":[{"t":"İyonları topla","a":"Na + Cl","d":"Bir sodyum (23) ve bir klor (35,5)."},{"t":"Topla","a":"23 + 35,5","d":"Toplam: 23 + 35,5 = 58,5 g/mol."}],"ans":"NaCl'ün molar kütlesi 58,5 g/mol'dür."},
{"q":"0,5 mol glikoz (C₆H₁₂O₆) kaç gramdır? (molar kütle 180 g/mol)","steps":[{"t":"Molar kütle","a":"180 g/mol","d":"1 mol glikoz 180 gramdır."},{"t":"Hesapla","a":"0,5 × 180","d":"Kütle = n × M = 0,5 × 180 = 90 g."}],"ans":"0,5 mol glikoz 90 gramdır."},
{"q":"Bağıl atom kütlesi ile molar kütle arasındaki ilişki nedir?","steps":[{"t":"Bağıl atom kütlesi","a":"akb cinsinden","d":"Bir atomun karbon-12'ye göre kütlesi, atom kütle birimiyle (akb) verilir."},{"t":"Sayısal eşitlik","a":"aynı sayı","d":"Bir maddenin molar kütlesi, formül kütlesiyle sayıca aynıdır; sadece birimi g/mol'dür."}],"ans":"Molar kütle, formül kütlesiyle sayıca eşittir; birimi g/mol'dür (örneğin su 18 akb, molar kütle 18 g/mol)."}
],"zor":[
{"q":"49 gram sülfürik asit (H₂SO₄) kaç moldür? (molar kütle 98 g/mol)","steps":[{"t":"Molar kütle","a":"98 g/mol","d":"Önce H₂SO₄'ün molar kütlesi: 2·1 + 32 + 4·16 = 98 g/mol."},{"t":"Mol bağıntısı","a":"n = m / M","d":"n = 49 ÷ 98 yazarız."},{"t":"Hesapla","a":"0,5 mol","d":"49 ÷ 98 = 0,5 mol bulunur."}],"ans":"49 gram H₂SO₄ 0,5 moldür."},
{"q":"250 gram kalsiyum karbonat (CaCO₃) kaç moldür? (molar kütle 100 g/mol)","steps":[{"t":"Molar kütle","a":"100 g/mol","d":"CaCO₃: 40 + 12 + 3·16 = 100 g/mol."},{"t":"Mol bağıntısı","a":"n = m / M","d":"n = 250 ÷ 100 yazarız."},{"t":"Hesapla","a":"2,5 mol","d":"250 ÷ 100 = 2,5 mol bulunur."}],"ans":"250 gram CaCO₃ 2,5 moldür."},
{"q":"Molar kütlesi 18 g/mol olan su örneğinde 1,5 mol bulunuyorsa kütle kaç gramdır?","steps":[{"t":"Bağıntı","a":"m = n · M","d":"Kütle = mol × molar kütle bağıntısını kullanırız."},{"t":"Değerleri yaz","a":"1,5 × 18","d":"m = 1,5 × 18 işlemini yaparız."},{"t":"Hesapla","a":"27 g","d":"1,5 × 18 = 27 g bulunur."}],"ans":"1,5 mol suyun kütlesi 27 gramdır."},
{"q":"Bir bileşiğin 0,25 molü 11 gram geliyorsa molar kütlesi kaç g/mol'dür?","steps":[{"t":"Bağıntı","a":"M = m / n","d":"Molar kütle = kütle ÷ mol bağıntısını kullanırız."},{"t":"Değerleri yaz","a":"11 ÷ 0,25","d":"M = 11 ÷ 0,25 işlemini yaparız."},{"t":"Hesapla","a":"44 g/mol","d":"11 ÷ 0,25 = 44 g/mol; bu CO₂ ile uyumludur."}],"ans":"Bileşiğin molar kütlesi 44 g/mol'dür."},
{"q":"Glikozun (C₆H₁₂O₆, 180 g/mol) 540 gramı kaç moldür?","fig":"<svg viewBox='0 0 320 150'><text x='160' y='40' font-size='12' text-anchor='middle' fill='#1a2b45'>C₆H₁₂O₆ → 180 g/mol</text><text x='160' y='80' font-size='12' text-anchor='middle' fill='#1a2b45'>n = 540 ÷ 180</text><text x='160' y='120' font-size='14' text-anchor='middle' fill='#e0552b'>n = 3 mol</text></svg>","steps":[{"t":"Molar kütle","a":"180 g/mol","d":"C₆H₁₂O₆: 6·12 + 12·1 + 6·16 = 180 g/mol."},{"t":"Mol bağıntısı","a":"n = m / M","d":"n = 540 ÷ 180 yazarız."},{"t":"Hesapla","a":"3 mol","d":"540 ÷ 180 = 3 mol bulunur."}],"ans":"540 gram glikoz 3 moldür."}
]}}};
