globalThis.__BQ = {
  "siviBasinci": {
    "lise": {
      "kolay": [
        {"q":"Durgun sıvıda basınç formülü nedir?","steps":[{"t":"Formül","a":"P = ρ·g·h","d":"P sıvı basıncı (Pa), ρ sıvı yoğunluğu (kg/m³), g yerçekimi ivmesi (m/s²), h sıvı yüzeyinden derinlik (m)."},{"t":"Yorum","a":"Yalnızca derinliğe bağlı","d":"Aynı derinlikte basınç yönden bağımsız; kaba bağlı değildir."}],"ans":"P = ρ·g·h","o":["P = ρ·g/h","P = m·g·h","P = ρ·V·g","P = F/(ρ·g)"]},
        {"q":"Aynı derinlikte sıvı basıncı hangi yönlerde eşittir?","steps":[{"t":"Pascal prensibi","a":"Tüm yönlerde eşit","d":"Durgun sıvıda basınç yönden bağımsızdır; aynı derinlikte yatay, dikey veya çapraz yönde aynı basınç ölçülür."},{"t":"Sonuç","a":"P = ρ·g·h → yalnızca h'e bağlı","d":"Yatay konuma göre değişmez; derinlik arttıkça artar."}],"ans":"Tüm yönlerde eşittir (basınç yönden bağımsızdır)","o":["Yalnızca aşağı yönde","Yalnızca yatay yönde","Derin olan yönde daha büyük","Kaba bağlı olarak değişir"]},
        {"q":"Sıvı basıncı kabın şekline bağlı mıdır?","steps":[{"t":"Bağımsızlık","a":"Hayır, şekilden bağımsız","d":"P = ρ·g·h formülünde kap şekli yer almaz; aynı derinlikte basınç kabın biçiminden etkilenmez."},{"t":"Önem","a":"Yalnızca h, ρ, g önemlidir","d":"Hidrostatikte kap şekli basıncı değiştirmez."}],"ans":"Hayır; P = ρ·g·h yalnızca derinliğe, yoğunluğa ve g'ye bağlıdır","o":["Evet, silindirik kaplarda daha yüksektir","Evet, konik kaplarda daha düşüktür","Evet, dar kaplarda artar","Hayır, yalnızca kap tabanının alanına bağlıdır"]},
        {"q":"Derinlik iki katına çıkarılırsa sıvı basıncı nasıl değişir?","steps":[{"t":"Orantı","a":"P ∝ h","d":"P = ρ·g·h; ρ ve g sabit olduğunda P derinlikle doğru orantılıdır."},{"t":"Sonuç","a":"P iki katına çıkar","d":"h = 2 m'de P = 2ρg, h = 4 m'de P = 4ρg olur."}],"ans":"İki katına çıkar (P ∝ h)","o":["Dört katına çıkar","Değişmez","Yarıya düşer","Karekökle artar"]},
        {"q":"Yoğunluğu daha büyük sıvının aynı derinlikte basıncı nasıl olur?","steps":[{"t":"P = ρ·g·h","a":"P ∝ ρ","d":"Aynı h ve g için yoğunluk büyük olan sıvının basıncı daha büyüktür."},{"t":"Örnek","a":"Cıva (ρ=13600) vs su (ρ=1000)","d":"Aynı derinlikte cıvanın basıncı suyun 13,6 katıdır."}],"ans":"Daha büyük olur (P ∝ ρ)","o":["Daha küçük olur","Aynı olur","Bağımsızdır","Yalnızca sıcaklığa bağlıdır"]}
      ],
      "zor": [
        {"q":"Suyla dolu (ρ = 1000 kg/m³) bir tankın dibindeki basınç kaç kPa'dır? Tank yüksekliği h = 4 m, g = 10 m/s².","steps":[{"t":"Formül","a":"P = ρ·g·h","d":"ρ = 1000, g = 10, h = 4."},{"t":"Hesap","a":"P = 1000 × 10 × 4 = 40 000 Pa","d":"40 000 Pa = 40 kPa."},{"t":"Sonuç","a":"P = 40 kPa","d":"Atmosfer basıncının yaklaşık 0,4 katıdır."}],"ans":"40 kPa","o":["4 kPa","400 kPa","20 kPa","80 kPa"]},
        {"q":"Deniz suyunun yoğunluğu ρ = 1025 kg/m³ ve g = 10 m/s² ise 200 m derinlikte basınç kaç atm'dir? (1 atm ≈ 10⁵ Pa)","steps":[{"t":"Hesap","a":"P = 1025 × 10 × 200 = 2 050 000 Pa","d":"P = ρ·g·h."},{"t":"Atm'ye çevir","a":"P ≈ 2 050 000/100 000 = 20,5 atm","d":"1 atm ≈ 10⁵ Pa kabulüyle."},{"t":"Sonuç","a":"P ≈ 20,5 atm","d":"200 m derinlikte basınç yaklaşık 20 atm'dir."}],"ans":"≈ 20,5 atm","o":["2,05 atm","205 atm","10 atm","40 atm"]},
        {"q":"İçinde yoğunluğu ρ = 800 kg/m³ olan yağ bulunan bir tankte dipte P = 16 000 Pa ölçülüyor. Tankın yüksekliği kaç m'dir? (g = 10 m/s²)","steps":[{"t":"Formül çevir","a":"h = P/(ρ·g)","d":"P = ρ·g·h → h = P/(ρ·g)."},{"t":"Hesap","a":"h = 16 000/(800 × 10) = 2 m","d":"Tank yüksekliği 2 m."},{"t":"Sonuç","a":"h = 2 m","d":"Yağ tankında 2 m yükseklik 16 kPa basınç oluşturur."}],"ans":"2 m","o":["1 m","4 m","0,5 m","8 m"]}
      ]
    }
  },
  "bilesikKaplar": {
    "lise": {
      "kolay": [
        {"q":"Bileşik kaplarda aynı sıvı kullanılıyorsa kapların sıvı seviyeleri nasıl olur?","steps":[{"t":"Denge koşulu","a":"Aynı yüksekliğe gelir","d":"Birbirine bağlı kaplarda aynı sıvı için taban basınçları eşit olmalıdır; bu yalnızca seviyeler eşit olduğunda sağlanır."},{"t":"Şekil bağımsızlığı","a":"Kap şekli önemli değildir","d":"Silindir, konik veya küresel kap fark etmez; seviyeler her zaman eşitlenir."}],"ans":"Kap şeklinden bağımsız olarak tüm kaplarda aynı seviyeye ulaşır","o":["Dar kapta daha yüksek olur","Geniş kapta daha yüksek olur","Her kapta farklı seviyelere ulaşır","Yalnızca silindirsel kaplarda eşit olur"]},
        {"q":"Bileşik kaplarda farklı yoğunlukta sıvılar kullanılıyorsa denge koşulu nedir?","steps":[{"t":"Basınç dengesi","a":"ρ₁·h₁ = ρ₂·h₂","d":"Bağlantı noktasında her iki sıvının basıncı eşit olmalıdır."},{"t":"Yorum","a":"Yoğun sıvı daha alçak durur","d":"ρ₁ > ρ₂ ise h₁ < h₂."}],"ans":"ρ₁·h₁ = ρ₂·h₂ (bağlantı noktasında basınç eşitliği)","o":["h₁ = h₂ her zaman","ρ₁·h₁² = ρ₂·h₂²","ρ₁/h₁ = ρ₂/h₂","m₁ = m₂"]},
        {"q":"Bileşik kaplar ilkesi günlük hayatta nerelerde kullanılır?","steps":[{"t":"Su deposu","a":"Musluk suyu baskısı","d":"Şehir su şebekesinde yüksekteki depo ile alçaktaki musluklar bileşik kap ilkesine dayanır."},{"t":"Seviye göstergesi","a":"Kazanlarda su seviyesi camı","d":"Kazan dışındaki şeffaf cam boru kazan içindeki su seviyesini gösterir."}],"ans":"Su şebekesi, kazan su seviyesi göstergesi, yazıcı mürekkep haznesi","o":["Yalnızca laboratuvar aletlerinde","Yalnızca uçak yakıt sistemlerinde","Yalnızca tıbbi cihazlarda","Hiçbir günlük uygulama yoktur"]},
        {"q":"Birbirine U borusuyla bağlı iki kapta su seviyesi eşit iken sol kaba daha fazla su eklenirse ne olur?","steps":[{"t":"Denge bozulur","a":"Sol kap basıncı artar","d":"Sol kap taban basıncı artar; sağ kap basıncı daha düşük kalır."},{"t":"Yeni denge","a":"Su sağa akar, seviyeler eşitlenir","d":"Sıvı yüksek basınçlı taraftan alçak basınçlı tarafa akar."}],"ans":"Su sağ kaba akar; her iki kaptaki seviyeler yeniden eşitlenir","o":["Sol kap taşar, sağ kapta değişim olmaz","Sağ kap boşalır","Seviyeler asla eşitlenmez","Sol kaptaki su donar"]},
        {"q":"Bileşik kaplarda taban basıncı ile sıvı seviyesi arasındaki ilişki nedir?","steps":[{"t":"P = ρ·g·h","a":"Basınç yükseklikle belirlenir","d":"Aynı sıvı için tüm kaplarda taban basıncı P = ρ·g·H olur; H bağlantı noktasından sıvı yüzeyine yüksekliktir."},{"t":"Denge","a":"Eşit taban basıncı → eşit seviye","d":"Sıvı seviyeleri eşit olduğunda tüm kaplarda taban basıncı aynıdır."}],"ans":"Eşit sıvı seviyesi → eşit taban basıncı; basınç seviyeyle doğru orantılıdır","o":["Basınç kap hacmiyle orantılıdır","Basınç yalnızca kapla belirlenir","Her kapta farklı taban basıncı oluşur","Basınç yalnızca sıcaklığa bağlıdır"]}
      ],
      "zor": [
        {"q":"Bileşik U borusunun sol kolunda su (ρ₁ = 1000 kg/m³, h₁ = 15 cm), sağ kolunda yağ (ρ₂ = 800 kg/m³) var. Sağ koldaki yağ yüksekliği h₂ kaç cm'dir?","steps":[{"t":"Denge","a":"ρ₁·h₁ = ρ₂·h₂","d":"g sadeleşir: 1000 × 15 = 800 × h₂."},{"t":"Hesap","a":"h₂ = 15 000/800 = 18,75 cm","d":"Yağ daha hafif olduğundan daha yüksek sütun oluşturur."},{"t":"Sonuç","a":"h₂ = 18,75 cm","d":"Kontrol: 1000/800 = 1,25 → 15 × 1,25 = 18,75."}],"ans":"18,75 cm","o":["12 cm","15 cm","20 cm","10 cm"]},
        {"q":"Bileşik kaplarda sol kolda h₁ = 20 cm su, sağ kolda ρ₂ = 1250 kg/m³ sıvı var. Denge için h₂ kaç cm olmalıdır? (ρ_su = 1000 kg/m³)","steps":[{"t":"Denge koşulu","a":"1000 × 20 = 1250 × h₂","d":"ρ₁·h₁ = ρ₂·h₂ uygulanır."},{"t":"Hesap","a":"h₂ = 20 000/1250 = 16 cm","d":"Daha yoğun sıvı daha alçak sütun oluşturur."},{"t":"Sonuç","a":"h₂ = 16 cm","d":"ρ₂ > ρ₁ olduğundan h₂ < h₁."}],"ans":"16 cm","o":["25 cm","20 cm","12,5 cm","8 cm"]},
        {"q":"Bileşik kaplarda sol kol su (ρ = 1000 kg/m³), sağ kol cıva (ρ = 13600 kg/m³) içeriyor. Su sütunu h₁ = 27,2 cm ise cıva sütunu h₂ kaç cm'dir?","steps":[{"t":"Denge","a":"1000 × 27,2 = 13600 × h₂","d":"ρ₁·h₁ = ρ₂·h₂ koşulu."},{"t":"Hesap","a":"h₂ = 27 200/13 600 = 2 cm","d":"Cıva çok yoğun olduğundan çok daha kısa sütun oluşturur."},{"t":"Sonuç","a":"h₂ = 2 cm","d":"27,2 cm su sütunu yalnızca 2 cm cıva sütununa denk gelir."}],"ans":"2 cm","o":["27,2 cm","13,6 cm","4 cm","0,2 cm"]}
      ]
    }
  },
  "hidrostatik": {
    "lise": {
      "kolay": [
        {"q":"U borusunda iki farklı sıvının dengesi için koşul nedir?","steps":[{"t":"Basınç eşitliği","a":"ρ₁·g·h₁ = ρ₂·g·h₂","d":"Bağlantı noktasında her iki koldan gelen basınç eşit olmalıdır."},{"t":"Sadeleştirme","a":"ρ₁·h₁ = ρ₂·h₂","d":"g her iki tarafta aynı olduğundan ifadeden çıkarılır."}],"ans":"ρ₁·h₁ = ρ₂·h₂","o":["ρ₁ = ρ₂","h₁ = h₂","ρ₁·h₁² = ρ₂·h₂²","ρ₁/h₁ = ρ₂/h₂"]},
        {"q":"Sıvı içine daldırılmış ve iple asılı bir cismin denge denklemi nedir?","steps":[{"t":"Kuvvetler","a":"T + F_k = W","d":"T ip gerilmesi, F_k kaldırma kuvveti, W cismin ağırlığıdır."},{"t":"İp gerilmesi","a":"T = W - F_k","d":"Kaldırma kuvveti ağırlığın bir kısmını taşır; ip yalnızca kalan kısmı taşır."}],"ans":"T = W - F_k (ip gerilmesi = ağırlık - kaldırma kuvveti)","o":["T = W + F_k","T = F_k - W","T = W × F_k","T = W / F_k"]},
        {"q":"Bir cisim havada 50 N, sıvıda asıldığında 30 N ağırlık ölçüyor. Kaldırma kuvveti kaç N'dur?","steps":[{"t":"Kaldırma kuvveti","a":"F_k = W - T","d":"W = 50 N (hava), T = 30 N (sıvıda görünen ağırlık)."},{"t":"Hesap","a":"F_k = 50 - 30 = 20 N","d":"Sıvı cisme 20 N kaldırma kuvveti uygulamaktadır."}],"ans":"20 N","o":["30 N","50 N","80 N","10 N"]},
        {"q":"Kaldırma kuvveti (Arşimet kuvveti) neye eşittir?","steps":[{"t":"Arşimet prensibi","a":"F_k = ρ_sıvı·V_batık·g","d":"Bir cisme etki eden kaldırma kuvveti, cismin yerinden ettiği sıvının ağırlığına eşittir."},{"t":"Formül","a":"F_k = ρ_f·V·g","d":"ρ_f sıvı yoğunluğu, V cismin sıvıdaki hacmi."}],"ans":"Cismin yerinden ettiği sıvının ağırlığına eşit: F_k = ρ_f·V·g","o":["Cismin kendi ağırlığına eşit","Cismin hacmine eşit","Sıvının toplam ağırlığına eşit","Sıvı basıncıyla çarpılan yüzey alanına eşit"]},
        {"q":"U borusunda sol kolda h₁ = 10 cm su, sağ kolda h₂ = 8 cm bilinmeyen sıvı var ve denge sağlanmış. Bilinmeyen sıvının yoğunluğu nedir? (ρ_su = 1000 kg/m³)","steps":[{"t":"Denge","a":"1000 × 10 = ρ_x × 8","d":"ρ₁·h₁ = ρ₂·h₂ koşulundan ρ_x hesaplanır."},{"t":"Hesap","a":"ρ_x = 10 000/8 = 1250 kg/m³","d":"Bilinmeyen sıvı sudan daha yoğundur."}],"ans":"1250 kg/m³","o":["800 kg/m³","1000 kg/m³","1500 kg/m³","2000 kg/m³"]}
      ],
      "zor": [
        {"q":"Kütlesi m = 0,5 kg ve yoğunluğu ρ_cisim = 2500 kg/m³ olan bir cisim yoğunluğu ρ_f = 1000 kg/m³ olan suya tamamen batırılarak iple tutturuluyor. İpteki gerilme kuvveti kaç N'dur? (g = 10 m/s²)","steps":[{"t":"Hacim","a":"V = 0,5/2500 = 2×10⁻⁴ m³","d":"Cismin hacmi kütlesi yoğunluğuna bölünerek bulunur."},{"t":"Kaldırma","a":"F_k = 1000 × 2×10⁻⁴ × 10 = 2 N","d":"Suyun cisme uyguladığı kaldırma kuvveti."},{"t":"Gerilme","a":"T = 5 - 2 = 3 N","d":"W = mg = 0,5 × 10 = 5 N; T = W - F_k = 3 N."}],"ans":"3 N","o":["5 N","2 N","7 N","1 N"]},
        {"q":"Bir taşın havadaki ağırlığı 12 N, suda görünür ağırlığı 9 N'dur. Taşın yoğunluğu kaç kg/m³'tür? (ρ_su = 1000 kg/m³, g = 10 m/s²)","steps":[{"t":"Kaldırma kuvveti","a":"F_k = 12 - 9 = 3 N","d":"Görünen ağırlık azalması kaldırma kuvvetine eşittir."},{"t":"Hacim","a":"V = 3/(1000×10) = 3×10⁻⁴ m³","d":"F_k = ρ_su·V·g → V = F_k/(ρ_su·g)."},{"t":"Yoğunluk","a":"ρ = (12/10)/(3×10⁻⁴) = 4000 kg/m³","d":"m = 12/10 = 1,2 kg; ρ = 1,2/(3×10⁻⁴) = 4000 kg/m³."}],"ans":"4000 kg/m³","o":["3000 kg/m³","2000 kg/m³","1333 kg/m³","12 000 kg/m³"]},
        {"q":"U borusuna sol kolda h₁ = 25 cm su doldurulmuş; denge sağlandıktan sonra sol kola 5 cm daha su ekleniyor. Cıva sütununun artışı Δh kaç cm'dir? (ρ_su = 1000, ρ_Hg = 13600 kg/m³)","steps":[{"t":"Başlangıç","a":"h₂ = 1000×25/13600 ≈ 1,838 cm","d":"ρ_su·h₁ = ρ_Hg·h₂."},{"t":"Yeni denge","a":"h₂_yeni = 1000×30/13600 ≈ 2,206 cm","d":"Su 25+5 = 30 cm olur."},{"t":"Artış","a":"Δh = 1000×5/13600 ≈ 0,37 cm","d":"Fark: 2,206 - 1,838 ≈ 0,37 cm."}],"ans":"≈ 0,37 cm","o":["5 cm","1,84 cm","0,74 cm","0,185 cm"]}
      ]
    }
  },
  "toricelli": {
    "lise": {
      "kolay": [
        {"q":"Torricelli deneyi nedir?","steps":[{"t":"Düzenek","a":"Cıva dolu kapalı tüp, cıva havzasına daldırılır","d":"Tüpte kalan cıva sütununun yüksekliği ölçülerek atmosfer basıncı belirlenir."},{"t":"Sonuç","a":"h ≈ 76 cm cıva → 1 atm","d":"Deniz seviyesinde atmosfer basıncı 76 cm cıva sütununa karşılık gelir."}],"ans":"Kapalı tüpte cıva sütununun 76 cm'de dengelenmesiyle atmosfer basıncını ölçer","o":["Sıvının yüzey gerilimini ölçer","Cıvanın yoğunluğunu belirler","Havanın nem oranını ölçer","Kılcal yükselmeyi ölçer"]},
        {"q":"Torricelli barometresinde P_atm = ρ·g·h formülünde ρ neyin yoğunluğudur?","steps":[{"t":"Formül","a":"ρ = cıvanın yoğunluğu","d":"h cıva sütununun yüksekliği, ρ_Hg = 13 600 kg/m³."},{"t":"Hesap","a":"P_atm = 13600 × 10 × 0,76 ≈ 103 360 Pa","d":"Standart g = 9,81 ile tam değer 101 325 Pa."}],"ans":"Cıvanın yoğunluğu (ρ_Hg = 13 600 kg/m³)","o":["Suyun yoğunluğu","Havanın yoğunluğu","Cam tüpün yoğunluğu","Cıva buharının yoğunluğu"]},
        {"q":"Torricelli barometresinde tüpün üst kısmında ne bulunur?","steps":[{"t":"Üst bölge","a":"Torricelli boşluğu (vakum)","d":"Tüpün kapalı ucunda cıvanın buhar basıncı ihmal edilirse burası neredeyse mükemmel vakumdur."},{"t":"Önemi","a":"Atmosfer basıncı cıvayı sütunda tutar","d":"Havza yüzeyindeki atmosfer basıncı tüpteki cıvayı 76 cm yüksekliğe destekler."}],"ans":"Torricelli boşluğu (neredeyse mükemmel vakum)","o":["Sıkıştırılmış hava","Su buharı","Azot gazı","Karbondioksit"]},
        {"q":"Yüksek rakımda atmosfer basıncı ve barometredeki cıva sütunu nasıl değişir?","steps":[{"t":"Rakım etkisi","a":"P_atm azalır","d":"Yükseldikçe üstümüzdeki hava sütunu kısalır; atmosfer basıncı düşer."},{"t":"Cıva sütunu","a":"h azalır","d":"P_atm = ρ·g·h; P_atm azalınca h de azalır."}],"ans":"P_atm azalır; barometredeki cıva sütunu kısalır","o":["P_atm artar; cıva sütunu uzar","P_atm değişmez; yalnızca cıva genleşir","P_atm azalır; cıva sütunu uzar","P_atm artar; cıva sütunu kısalır"]},
        {"q":"Cıva yerine su kullanılsaydı Torricelli barometresinde su sütunu yaklaşık kaç m olurdu? (ρ_Hg = 13600, ρ_su = 1000, h_Hg = 0,76 m)","steps":[{"t":"Denklem","a":"h_su = h_Hg × ρ_Hg/ρ_su","d":"P_atm eşitliğinden: h_su = 0,76 × 13,6."},{"t":"Hesap","a":"h_su = 0,76 × 13,6 = 10,34 m","d":"Su sütunu yaklaşık 10 m olurdu."}],"ans":"≈ 10,34 m (yaklaşık 10 m)","o":["76 cm","1,36 m","100 m","0,56 m"]}
      ],
      "zor": [
        {"q":"Standart atmosfer basıncı P_atm = 101 325 Pa ve ρ_Hg = 13 600 kg/m³ ise Torricelli barometresindeki cıva sütun yüksekliği kaç cm'dir? (g = 9,81 m/s²)","steps":[{"t":"Formül","a":"h = P_atm/(ρ_Hg·g)","d":"h = 101 325/(13600 × 9,81)."},{"t":"Hesap","a":"h ≈ 0,7594 m = 75,9 cm","d":"Standart barometre değeri ≈ 76 cm ile örtüşür."},{"t":"Sonuç","a":"h ≈ 76 cm","d":"Küçük fark g değerinden kaynaklanır."}],"ans":"≈ 76 cm","o":["13,6 cm","101 cm","10 cm","760 cm"]},
        {"q":"Bir dağda atmosfer basıncı P = 0,85 atm olarak ölçüldü. Bu basınç kaç cm cıva sütununa eşittir? (1 atm = 76 cm Hg)","steps":[{"t":"Orantı","a":"h = 0,85 × 76 cm","d":"1 atm = 76 cm Hg olduğundan 0,85 atm = 0,85 × 76."},{"t":"Hesap","a":"h = 64,6 cm","d":"Dağda basınç azaldığından cıva sütunu kısalır."},{"t":"Sonuç","a":"h = 64,6 cm","d":"Yaklaşık 64,6 cm cıva sütunu."}],"ans":"64,6 cm","o":["76 cm","89,4 cm","50 cm","85 cm"]},
        {"q":"Gliserin (ρ = 1260 kg/m³) dolu Torricelli barometresinde gliserin sütunu kaç m olur? (P_atm = 101 325 Pa, g = 10 m/s²)","steps":[{"t":"Formül","a":"h = P_atm/(ρ·g)","d":"h = 101 325/(1260 × 10) = 101 325/12 600."},{"t":"Hesap","a":"h ≈ 8,04 m","d":"Gliserin su ile cıva arasında yoğunluğa sahip olduğundan ara bir değer verir."},{"t":"Sonuç","a":"h ≈ 8,04 m","d":"Pratik barometre için elverişsiz; cıva tercih edilir."}],"ans":"≈ 8,04 m","o":["0,76 m","10 m","1,26 m","80,4 m"]}
      ]
    }
  },
  "manometre": {
    "lise": {
      "kolay": [
        {"q":"Manometre nedir ve ne ölçer?","steps":[{"t":"Tanım","a":"Basınç ölçüm cihazı","d":"Manometre, bir gazın veya sıvının basıncını ölçen alettir. Açık manometre atmosfer basıncına göre bağıl basıncı ölçer."},{"t":"Bağıl basınç","a":"P_bağıl = P_mutlak - P_atm","d":"Manometre okuma değeri bağıl basıncı verir; mutlak basınç için P_atm eklenmesi gerekir."}],"ans":"Açık manometre, bir sistemin atmosfer basıncına göre bağıl (gösterge) basıncını ölçer","o":["Sıcaklık ölçer","Mutlak sıfıra göre basıncı ölçer","Yalnızca gaz hacmini ölçer","Sıvı yoğunluğunu ölçer"]},
        {"q":"Açık U manometresinde Δh = 20 cm su yükseklik farkı varsa bağıl basınç kaç Pa'dır? (ρ_su = 1000 kg/m³, g = 10 m/s²)","steps":[{"t":"Formül","a":"P_bağıl = ρ·g·Δh","d":"Manometredeki sıvı yükseklik farkı bağıl basıncı verir."},{"t":"Hesap","a":"P = 1000 × 10 × 0,20 = 2000 Pa","d":"Δh = 20 cm = 0,20 m."}],"ans":"2000 Pa","o":["200 Pa","20 000 Pa","2 Pa","20 Pa"]},
        {"q":"Mutlak basınç ve bağıl (gösterge) basınç arasındaki fark nedir?","steps":[{"t":"Mutlak basınç","a":"P_mutlak = P_bağıl + P_atm","d":"Mutlak sıfıra (vakum) göre ölçülen basınçtır."},{"t":"Bağıl basınç","a":"P_bağıl = P_mutlak - P_atm","d":"Atmosfer basıncına göre fazlalık miktarıdır."}],"ans":"P_mutlak = P_bağıl + P_atm; bağıl basınç atmosfere göre fazlalığı ifade eder","o":["İkisi birbirine eşittir","P_mutlak = P_bağıl - P_atm","Bağıl basınç her zaman sıfırdır","P_bağıl = P_mutlak × P_atm"]},
        {"q":"Kapalı bir kap manometresinde cıva sütunu Δh = 5 cm yükseldi. Bağıl basınç kaç Pa'dır? (ρ_Hg = 13600 kg/m³, g = 10 m/s²)","steps":[{"t":"Formül","a":"P_bağıl = ρ_Hg·g·Δh","d":"Cıva manometresinde Δh = 0,05 m."},{"t":"Hesap","a":"P = 13600 × 10 × 0,05 = 6800 Pa","d":"Sonuç 6800 Pa = 6,8 kPa."}],"ans":"6800 Pa (6,8 kPa)","o":["680 Pa","68 000 Pa","1360 Pa","136 Pa"]},
        {"q":"Kapalı manometre ile açık manometre arasındaki temel fark nedir?","steps":[{"t":"Açık manometre","a":"Bir kolu atmosfere açık","d":"Atmosfer basıncına göre bağıl basınç ölçer."},{"t":"Kapalı manometre","a":"Her iki kol kapalı","d":"Referans tarafta bilinen sabit bir basınç bulunur."}],"ans":"Açık manometre bağıl basınç ölçer; kapalı manometre referans basınca göre ölçer","o":["İkisi tamamen aynıdır","Kapalı manometre yalnızca sıvı ölçer","Açık manometre mutlak basınç ölçer","Kapalı manometre yalnızca vakum ölçer"]}
      ],
      "zor": [
        {"q":"Bir gaz tankına bağlı açık cıva manometresinde atmosfer kolu gaz kolundan Δh = 12 cm yüksek. P_atm = 101 325 Pa, ρ_Hg = 13600 kg/m³, g = 10 m/s². Gaz mutlak basıncı kaç Pa'dır?","steps":[{"t":"Bağıl basınç","a":"P_bağıl = 13600 × 10 × 0,12 = 16 320 Pa","d":"Atmosfer kolu daha yüksek → gaz basıncı atmosferden büyük."},{"t":"Mutlak basınç","a":"P_mutlak = 101 325 + 16 320 = 117 645 Pa","d":"P_mutlak = P_atm + P_bağıl."},{"t":"Sonuç","a":"P_mutlak = 117 645 Pa (≈ 1,16 atm)","d":"Yaklaşık 1,16 atmosfer."}],"ans":"117 645 Pa (≈ 1,16 atm)","o":["85 005 Pa","16 320 Pa","101 325 Pa","203 000 Pa"]},
        {"q":"Bir manometrede su (ρ = 1000 kg/m³) kullanılıyor; ölçülen bağıl basınç P_bağıl = 15 000 Pa. Su sütunu yükseklik farkı kaç cm'dir? (g = 10 m/s²)","steps":[{"t":"Formül","a":"Δh = P_bağıl/(ρ·g)","d":"P = ρ·g·Δh → Δh = P/(ρ·g)."},{"t":"Hesap","a":"Δh = 15 000/(1000×10) = 1,5 m = 150 cm","d":"Aynı basınç cıva manometresinde yalnızca ≈ 11 cm olurdu."},{"t":"Sonuç","a":"Δh = 150 cm","d":"Bu kadar büyük fark için cıva manometresi tercih edilir."}],"ans":"150 cm","o":["15 cm","1500 cm","1,5 cm","50 cm"]},
        {"q":"P_atm = 10⁵ Pa ortamında bir tüpteki gazın mutlak basıncı P = 85 000 Pa ise manometre Δh'yi cıva cinsinden ne gösterir? (ρ_Hg = 13600 kg/m³, g = 10 m/s²)","steps":[{"t":"Bağıl basınç","a":"P_bağıl = 85 000 - 100 000 = -15 000 Pa","d":"Negatif bağıl basınç gazın atmosferden daha az basınca sahip olduğunu gösterir (vakum)."},{"t":"Δh hesabı","a":"Δh = 15 000/(13600×10) ≈ 11 cm","d":"Gaz kolu daha yüksek, atmosfer kolu daha alçak."},{"t":"Sonuç","a":"≈ 11 cm; gaz tarafı daha yüksek (vakum basıncı)","d":"Gaz atmosfer basıncının altında."}],"ans":"≈ 11 cm (gaz tarafı daha yüksek; vakum basıncı)","o":["11 cm (atmosfer tarafı daha yüksek; aşırı basınç)","15 cm (vakum)","110 cm (vakum)","1,1 cm (vakum)"]}
      ]
    }
  }
};
